/* Lote A — 2.3, 2.4, 2.6, 2.9. Questões AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.3-040', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de posto de combustíveis, 15 anos na função de frentista, apresenta hemograma com leucopenia e plaquetopenia leves, persistentes em dois exames. Sobre a conduta, é CORRETO afirmar:',
  alts: [
    { t: 'Investigar o benzeno presente na gasolina, afastar o trabalhador da exposição e repetir o hemograma em série', ok: true,
      why: 'Correta. Citopenia em exposto ao benzeno é achado sentinela.' },
    { t: 'Repetir o hemograma em seis meses, pois alterações leves em duas amostras não exigem investigação.', ok: false,
      why: 'Errada. Em exposto ao benzeno, é achado sentinela que exige ação.' },
    { t: 'Investigar outras causas, pois o frentista não se expõe ao benzeno por não manipular o produto puro.', ok: false,
      why: 'Errada. A gasolina contém benzeno e os vapores expõem o frentista.' },
    { t: 'Solicitar dosagem de benzeno no sangue, exame de escolha para monitorar essa exposição ocupacional.', ok: false,
      why: 'Errada. Usam-se indicadores de metabólitos urinários, não o benzeno sanguíneo.' },
    { t: 'Atribuir a alteração ao tabagismo do trabalhador, encerrando a investigação da causa ocupacional.', ok: false,
      why: 'Errada. O tabagismo é fator concorrente, não excludente.' }
  ],
  comentario: 'Frentista é exposto ocupacional a benzeno. Citopenia persistente em exposto é achado sentinela: afasta da exposição, repete seriado e encaminha. E o monitoramento biológico do benzeno não é dosagem sanguínea do próprio agente.',
  pegadinha: 'A alternativa da dosagem sanguínea parece técnica e desconsidera a cinética do agente.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'IARC Monographs'] },

{ id: 'q-2.3-041', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de indústria de plásticos exposto a cloreto de vinila por duas décadas apresenta lesão hepática rara. Sobre o caso, é CORRETO afirmar:',
  alts: [
    { t: 'O angiossarcoma hepático tem forte associação com o cloreto de vinila, o que torna o nexo robusto.', ok: true,
      why: 'Correta. Tumor raro somado a exposição documentada é o cenário mais favorável ao nexo.' },
    { t: 'O angiossarcoma é tumor raro, o que dificulta o estabelecimento do nexo ocupacional no caso.', ok: false,
      why: 'Errada, é o oposto: a raridade com forte associação reforça o nexo.' },
    { t: 'O angiossarcoma tem várias causas, não tendo o cloreto de vinila carcinogenicidade reconhecida.', ok: false,
      why: 'Errada. É cancerígeno reconhecido para humanos.' },
    { t: 'O angiossarcoma se associa ao agente, afastando o nexo a ausência de hepatopatia crônica prévia.', ok: false,
      why: 'Errada. O tumor ocorre sem hepatopatia crônica associada.' },
    { t: 'O angiossarcoma se associa ao agente, mas o nexo está afastado por a exposição ter cessado há anos.', ok: false,
      why: 'Errada. A latência longa é característica desse tumor.' }
  ],
  comentario: 'Cloreto de vinila e angiossarcoma hepático é um dos pares mais bem estabelecidos da toxicologia ocupacional. Guarde a lógica: tumor raro + agente conhecido = nexo robusto, exatamente como mesotelioma e asbesto.',
  pegadinha: 'Usar a raridade contra o nexo inverte o raciocínio de força de associação.',
  refs: ['IARC Monographs', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.3-042', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as vias de absorção dos agentes químicos no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A via respiratória predomina, mas a cutânea pode ser a principal em agentes com notação de pele', ok: true,
      why: 'Correta. A digestiva ganha relevância com higiene inadequada no setor produtivo.' },
    { t: 'A via respiratória é a única relevante na exposição ocupacional a agentes químicos industriais.', ok: false,
      why: 'Errada. Cutânea e digestiva também contribuem, conforme o agente.' },
    { t: 'A respiratória predomina e a cutânea contribui, sendo a digestiva irrelevante em ambiente industrial.', ok: false,
      why: 'Errada. Comer e fumar no posto produz absorção digestiva relevante.' },
    { t: 'A respiratória predomina, ocorrendo a absorção cutânea apenas quando há lesão da pele exposta.', ok: false,
      why: 'Errada. Vários agentes atravessam a pele íntegra.' },
    { t: 'A respiratória predomina, captando a avaliação do ar a exposição total do trabalhador avaliado.', ok: false,
      why: 'Errada. Não capta a absorção cutânea nem a digestiva.' }
  ],
  comentario: 'Três vias: respiratória (a mais comum), cutânea (decisiva quando há notação de pele) e digestiva (mãos e alimentação no setor). A avaliação do ar só vê a primeira — daí a importância do monitoramento biológico, que integra todas.',
  pegadinha: 'Condicionar a absorção cutânea à existência de lesão ignora que muitos agentes atravessam pele íntegra.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'ACGIH — TLVs e BEIs'] },

{ id: 'q-2.4-040', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de frigorífico apresenta febre prolongada, sudorese noturna, artralgia e hepatoesplenomegalia, com história de manipulação de vísceras de bovinos. Sobre a hipótese, é CORRETO afirmar:',
  alts: [
    { t: 'Considerar brucelose, zoonose adquirida pelo contato com tecidos e secreções de animais infectados', ok: true,
      why: 'Correta. O quadro febril prolongado e inespecífico atrasa o diagnóstico.' },
    { t: 'Afastar zoonose ocupacional, por não haver relato de mordedura de animal no período de trabalho.', ok: false,
      why: 'Errada. O contato com tecidos e secreções é a via principal na brucelose.' },
    { t: 'Considerar brucelose, embora a ausência de contato com animais vivos afaste o diagnóstico.', ok: false,
      why: 'Errada. Carcaças, vísceras e secreções transmitem igualmente.' },
    { t: 'Considerar brucelose, não sendo as zoonoses ocupacionais passíveis de notificação compulsória.', ok: false,
      why: 'Errada. Integram a lista de agravos notificáveis.' },
    { t: 'Considerar brucelose, resumindo-se a prevenção à vacinação dos trabalhadores do abatedouro.', ok: false,
      why: 'Errada. Não há vacina humana; a prevenção é por barreiras e manejo.' }
  ],
  comentario: 'Frigorífico e abate concentram zoonoses: brucelose, leptospirose, tuberculose bovina, dermatoses por contato. Quadro febril prolongado e inespecífico em quem manipula vísceras merece história ocupacional dirigida.',
  pegadinha: 'Associar zoonose ocupacional exclusivamente a mordedura ignora a via de contato com tecidos e secreções.',
  refs: ['Classificação de Risco dos Agentes Biológicos — Ministério da Saúde', 'NR-36'] },

{ id: 'q-2.4-041', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o descarte de resíduos de serviços de saúde e o risco ocupacional associado, é CORRETO afirmar:',
  alts: [
    { t: 'A segregação correta na origem é o que mais reduz o risco de quem manuseia o resíduo adiante', ok: true,
      why: 'Correta. Erros na origem se propagam por toda a cadeia até a destinação.' },
    { t: 'O risco se restringe aos profissionais assistenciais que geram o resíduo no ponto de atendimento.', ok: false,
      why: 'Errada. Coleta, transporte e destinação expõem outros trabalhadores.' },
    { t: 'A segregação reduz o risco, sendo responsabilidade do serviço de limpeza terceirizado contratado.', ok: false,
      why: 'Errada. A segregação é de quem gera o resíduo.' },
    { t: 'A segregação reduz o risco, podendo os recipientes de perfurocortantes ir até a borda por economia.', ok: false,
      why: 'Errada. Ultrapassar o limite de enchimento causa acidentes na coleta.' },
    { t: 'A segregação reduz o risco, podendo químicos e biológicos ir no mesmo recipiente identificado.', ok: false,
      why: 'Errada. Exigem segregação e destinação distintas.' }
  ],
  comentario: 'A segregação na origem protege quem vem depois. O erro de quem descarta cai sobre quem coleta e quem tria — trabalhadores frequentemente terceirizados e menos protegidos.',
  pegadinha: 'Atribuir a segregação ao serviço de limpeza inverte a responsabilidade e é a causa da maioria dos acidentes na cadeia.',
  refs: ['NR-32', 'Ministério da Saúde — resíduos de serviços de saúde'] },

{ id: 'q-2.6-050', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao interpretar um valor-limite com notação de carcinogenicidade suspeita, o médico do trabalho precisa orientar a empresa. A orientação CORRETA é:',
  alts: [
    { t: 'Sinaliza evidência de carcinogenicidade e prioriza substituição e redução ao menor nível viável.', ok: true,
      why: 'Correta. O valor numérico não é tratado como fronteira de segurança.' },
    { t: 'É informação complementar da lista e não altera as medidas de controle exigidas para o agente.', ok: false,
      why: 'Errada. Muda a lógica de gestão para substituição e redução máxima.' },
    { t: 'Sinaliza carcinogenicidade, demonstrando a existência de valor numérico que há limiar seguro.', ok: false,
      why: 'Errada. Para cancerígenos não se assume limiar seguro.' },
    { t: 'Sinaliza carcinogenicidade, não exigindo os de carcinogenicidade suspeita monitoramento dos expostos.', ok: false,
      why: 'Errada. A suspeita já impõe vigilância e registro dos expostos.' },
    { t: 'Sinaliza carcinogenicidade, aplicando-se apenas aos agentes com efeito confirmado em humanos.', ok: false,
      why: 'Errada. Há categorias para evidência suficiente, provável e possível.' }
  ],
  comentario: 'Notação de carcinogenicidade é comando de gestão: substituir, e não podendo, reduzir ao mínimo viável, registrar a exposição e acompanhar os expostos — inclusive depois que a exposição termina.',
  pegadinha: 'Tratar a existência do valor numérico como prova de que há nível seguro é o erro central em todo o bloco de carcinogênicos.',
  refs: ['ACGIH — TLVs e BEIs', 'LINACH', 'IARC Monographs'] },

{ id: 'q-2.6-051', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o conceito de nível de ação em higiene ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'É o patamar, abaixo do limite, que dispara monitoramento, controle médico e capacitação.', ok: true,
      why: 'Correta. Antecipa a ação em vez de esperar a ultrapassagem do limite.' },
    { t: 'É sinônimo de limite de tolerância, com denominação distinta adotada em documentos técnicos.', ok: false,
      why: 'Errada. Situa-se abaixo do limite e tem função preventiva própria.' },
    { t: 'É o patamar de disparo de medidas, não sendo necessária medida alguma abaixo dele.', ok: false,
      why: 'Errada. O gerenciamento de riscos permanece em qualquer nível.' },
    { t: 'É o patamar de disparo de medidas, aplicável apenas aos agentes de natureza química.', ok: false,
      why: 'Errada. Aplica-se também a agentes físicos, como o ruído.' },
    { t: 'É o patamar de disparo, obrigando seu alcance ao afastamento imediato do trabalhador exposto.', ok: false,
      why: 'Errada. Dispara monitoramento e controle, não afastamento.' }
  ],
  comentario: 'Nível de ação é o gatilho antecipado: abaixo do limite, mas já suficiente para acionar monitoramento, controle médico dirigido e capacitação. É o conceito que separa prevenção de fiscalização de número.',
  pegadinha: 'Confundi-lo com o limite de tolerância elimina justamente a antecipação que ele representa.',
  refs: ['NR-9', 'NHO — Fundacentro'] },

{ id: 'q-2.9-040', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de mineração apresenta quadro neuropsiquiátrico com alterações de comportamento, seguido de sinais extrapiramidais com rigidez e alteração da marcha. Sobre a hipótese, é CORRETO afirmar:',
  alts: [
    { t: 'Considerar manganismo, com fase inicial neuropsiquiátrica seguida de quadro extrapiramidal claro', ok: true,
      why: 'Correta. Pode persistir após o afastamento, o que torna o reconhecimento precoce decisivo.' },
    { t: 'Considerar intoxicação por chumbo, cuja manifestação típica é o quadro extrapiramidal descrito.', ok: false,
      why: 'Errada. O quadro extrapiramidal caracteriza o manganismo.' },
    { t: 'Considerar doença degenerativa primária, pois sinais extrapiramidais afastam causa ocupacional.', ok: false,
      why: 'Errada. O manganismo é causa ocupacional reconhecida desse quadro.' },
    { t: 'Considerar manganismo, garantindo o afastamento da exposição a reversão completa do quadro.', ok: false,
      why: 'Errada. Alterações instaladas podem persistir após a cessação.' },
    { t: 'Considerar manganismo, excluindo o diagnóstico a ausência de tremor de repouso no exame.', ok: false,
      why: 'Errada. O tremor do manganismo costuma ser postural, não de repouso.' }
  ],
  comentario: 'Manganismo: fase psiquiátrica inicial, depois extrapiramidal, com reversão apenas parcial após o afastamento. Não confunda com saturnismo (cólica, anemia, punho caído) nem com mercúrio metálico (tremor, eretismo, gengivoestomatite).',
  pegadinha: 'Atribuir todo parkinsonismo a doença degenerativa primária faz perder a única causa que teria intervenção preventiva.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-2.9-041', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de garimpo apresenta tremor de extremidades, irritabilidade, alterações de memória e gengivite com sialorreia. Sobre a hipótese, é CORRETO afirmar:',
  alts: [
    { t: 'Considerar mercúrio metálico: tremor de intenção, alterações neuropsiquiátricas e gengivoestomatite', ok: true,
      why: 'Correta. O monitoramento biológico se faz preferencialmente por dosagem urinária.' },
    { t: 'Considerar intoxicação por manganês, cuja marca clínica é a gengivoestomatite descrita no caso.', ok: false,
      why: 'Errada. A gengivoestomatite compõe o quadro do mercúrio.' },
    { t: 'Considerar mercúrio, sendo a dosagem sanguínea o método de escolha na exposição crônica.', ok: false,
      why: 'Errada. Para o metálico, o indicador de escolha é urinário.' },
    { t: 'Considerar mercúrio, sendo o tremor descrito de repouso e caracterizando síndrome extrapiramidal.', ok: false,
      why: 'Errada. O tremor do mercúrio é de intenção e postural.' },
    { t: 'Considerar mercúrio, ocorrendo a exposição em garimpo apenas pela via digestiva, ao comer peixe.', ok: false,
      why: 'Errada. A via ocupacional principal é a inalação do vapor metálico.' }
  ],
  comentario: 'Mercúrio metálico: tremor de intenção, eretismo (irritabilidade, alterações de memória e personalidade) e gengivoestomatite. Exposição ocupacional por inalação de vapor; monitoramento por dosagem urinária.',
  pegadinha: 'A confusão entre exposição ocupacional a vapor de mercúrio e exposição ambiental por metilmercúrio em peixes troca via, forma química e quadro clínico.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'ACGIH — BEIs'] },

{ id: 'q-2.9-042', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a interpretação de resultados de monitoramento biológico em grupo de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Deve considerar a distribuição dos resultados no grupo, e não apenas os casos isolados encontrados', ok: true,
      why: 'Correta. Vários elevados apontam falha coletiva; um discrepante sugere fator individual.' },
    { t: 'Deve analisar cada resultado isoladamente, sem comparação com os demais resultados do grupo.', ok: false,
      why: 'Errada. A distribuição no grupo é o que revela falha de controle.' },
    { t: 'Deve considerar o grupo, indicando vários resultados elevados suscetibilidade coletiva incomum.', ok: false,
      why: 'Errada. Indica falha de controle da exposição, não suscetibilidade.' },
    { t: 'Deve considerar o grupo, descartando como erro laboratorial o resultado isolado muito elevado.', ok: false,
      why: 'Errada. Exige investigação de tarefa ou fator individual específico.' },
    { t: 'Deve considerar o grupo, sendo a média do grupo o parâmetro adequado para decidir intervenção.', ok: false,
      why: 'Errada. A média esconde os casos extremos que exigem ação.' }
  ],
  comentario: 'Leia o grupo, não só o indivíduo: vários elevados = falha de controle coletivo; um isolado = investigar tarefa, hábito ou fator individual. E nunca decida pela média — ela esconde exatamente quem precisa de ação.',
  pegadinha: 'Descartar o valor isolado alto como erro de laboratório elimina a pista que revelaria uma tarefa de alta exposição.',
  refs: ['ACGIH — BEIs', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.9-043', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a exposição combinada a solventes e o consumo de bebida alcoólica pelo trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'O álcool compete pelas mesmas vias de biotransformação e interfere no monitoramento biológico', ok: true,
      why: 'Correta. Deve ser considerado sem virar juízo moral ou motivo de discriminação.' },
    { t: 'O consumo de álcool não interfere na toxicidade nem no monitoramento biológico de solventes.', ok: false,
      why: 'Errada. Compete pelas mesmas vias metabólicas.' },
    { t: 'O álcool interfere, devendo a alteração ser atribuída a ele, encerrando a investigação da exposição.', ok: false,
      why: 'Errada. A exposição ocupacional continua a ser investigada.' },
    { t: 'O álcool interfere, devendo a informação sobre o consumo ser comunicada ao empregador.', ok: false,
      why: 'Errada. É informação de saúde protegida por sigilo.' },
    { t: 'O álcool interfere, ocorrendo a interação com solventes apenas no consumo de padrão abusivo.', ok: false,
      why: 'Errada. A competição metabólica ocorre também em consumo moderado.' }
  ],
  comentario: 'Interferentes individuais — álcool, medicamentos, tabagismo, polimorfismos — explicam boa parte das discrepâncias no monitoramento biológico. São dados clínicos a considerar, sob sigilo, e nunca justificativa para parar de investigar a exposição.',
  pegadinha: 'Usar o hábito do trabalhador para encerrar a investigação é o desvio que protege o processo produtivo e desprotege a pessoa.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'ACGIH — BEIs', 'Código de Ética Médica'] }

);
