/* Lote AB — 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.1-070', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a estabilidade acidentária prevista na legislação, é CORRETO afirmar:',
  alts: [
    { t: 'Decorre da percepção de benefício acidentário e vale pelo prazo mínimo previsto contado da cessação do auxílio, alcançando também a doença ocupacional constatada depois da dispensa.', ok: true,
      why: 'Correta. Nasce da natureza acidentária do benefício, conta-se da alta e o reconhecimento posterior do nexo, se ligado ao período contratual, também gera o direito.' },
    { t: 'Decorre da percepção de benefício acidentário, mas depende de requerimento expresso do trabalhador durante o afastamento, sob pena de preclusão do direito.', ok: false,
      why: 'Errada. É efeito automático da situação jurídica; não existe prazo para pedir nem perda por não requerer.' },
    { t: 'Decorre da percepção de benefício acidentário, mas se extingue com a dispensa, de modo que doença ocupacional constatada depois não gera qualquer direito.', ok: false,
      why: 'Errada. O reconhecimento posterior, com nexo estabelecido no período contratual, pode gerar o direito.' },
    { t: 'Decorre de qualquer afastamento previdenciário por doença superior a quinze dias, independentemente de o benefício ter natureza acidentária ou comum.', ok: false,
      why: 'Errada. É a natureza acidentária que a origina; afastamento previdenciário comum não gera estabilidade.' },
    { t: 'Decorre da percepção de benefício acidentário e vale pelo prazo mínimo previsto contado do início do afastamento, encerrando-se junto com a alta médica.', ok: false,
      why: 'Errada. A contagem começa na cessação do benefício, não no início do afastamento.' }
  ],
  comentario: 'Estabilidade acidentária: doze meses após a cessação do auxílio-doença acidentário, decorrente da natureza do benefício e não de requerimento — e alcança doença ocupacional reconhecida depois da dispensa, se o nexo é do período contratual.',
  pegadinha: 'Contar o prazo a partir do afastamento, e não da alta, é o erro de leitura mais frequente do dispositivo.',
  refs: ['Lei nº 8.213/1991 — art. 118', 'Súmulas do TST sobre estabilidade acidentária'] },

{ id: 'q-7.1-071', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a jornada de trabalho e seus intervalos na perspectiva da saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Os intervalos existem para recuperação fisiológica, e por isso a prorrogação habitual de jornada em atividade insalubre recebe tratamento normativo próprio.', ok: true,
      why: 'Correta. Somar mais exposição a menos recuperação é o que justifica a exigência específica para prorrogar jornada em insalubre.' },
    { t: 'Os intervalos existem para recuperação fisiológica, mas sua supressão é integralmente compensada pelo pagamento do adicional correspondente, que repõe o descanso perdido.', ok: false,
      why: 'Errada. O pagamento repara o bolso; não devolve a recuperação. A função do intervalo é fisiológica e não se compra.' },
    { t: 'Os intervalos existem para recuperação fisiológica, mas a prorrogação de jornada em atividade insalubre segue a regra geral, sem exigência normativa específica.', ok: false,
      why: 'Errada. Há exigência própria, justamente porque prorrogar em insalubre aumenta a exposição e reduz o descanso.' },
    { t: 'Os intervalos existem por convenção contratual, e o intervalo entre jornadas não tem relação demonstrada com risco de acidentes no trabalho seguinte.', ok: false,
      why: 'Errada. A privação de sono é fator de risco reconhecido para acidentes, e o interjornada existe para evitá-la.' },
    { t: 'Os intervalos existem para recuperação fisiológica, mas os regimes de compensação de jornada são neutros em saúde, por manterem a carga semanal total.', ok: false,
      why: 'Errada. Manter o total semanal não é neutro: muda a distribuição do esforço e dos períodos de recuperação.' }
  ],
  comentario: 'Intervalo é recuperação fisiológica, não benefício negociável: suprimi-lo e pagar por isso repara o bolso e não a fadiga. Por isso a prorrogação habitual em insalubre tem tratamento próprio — soma mais exposição a menos recuperação.',
  pegadinha: 'A compensação financeira do intervalo suprimido é reparação econômica, nunca prevenção.',
  refs: ['CLT — arts. 66, 71 e 60', 'NR-17'] },

{ id: 'q-7.2-080', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o fator acidentário de prevenção e as alíquotas de contribuição por acidentalidade, é CORRETO afirmar:',
  alts: [
    { t: 'A contribuição varia conforme o desempenho da empresa comparado ao de seu setor, o que cria incentivo à prevenção e, ao mesmo tempo, incentivo à subnotificação.', ok: true,
      why: 'Correta. O mesmo mecanismo que premia quem previne também premia quem apenas deixa de registrar.' },
    { t: 'A contribuição é fixada por grau de risco da atividade econômica e não varia conforme o desempenho individual da empresa dentro do próprio setor.', ok: false,
      why: 'Errada. O grau de risco define a faixa, mas o desempenho relativo da empresa faz a alíquota subir ou descer.' },
    { t: 'A contribuição varia conforme o desempenho da empresa, mecanismo que gera apenas incentivo à prevenção, sem efeito colateral sobre o registro dos acidentes.', ok: false,
      why: 'Errada. O incentivo perverso à subnotificação é reconhecido e precisa ser considerado ao ler os indicadores.' },
    { t: 'A contribuição varia conforme o desempenho da empresa comparado à média nacional de todas as atividades econômicas somadas.', ok: false,
      why: 'Errada. A comparação é feita dentro da mesma atividade econômica, não contra a média geral do país.' },
    { t: 'A contribuição varia conforme o desempenho da empresa, de modo que uma queda abrupta do indicador comprova a eficácia das medidas preventivas adotadas.', ok: false,
      why: 'Errada. Queda abrupta pede verificação: pode ser mudança no registro, não melhora real das condições.' }
  ],
  comentario: 'A contribuição varia conforme o desempenho da empresa dentro do próprio setor — bom incentivo à prevenção e, ao mesmo tempo, incentivo à subnotificação. Melhora abrupta de indicador merece verificação antes de comemoração.',
  pegadinha: 'Ler queda súbita de acidentalidade como sucesso preventivo ignora o incentivo econômico ao não registro.',
  refs: ['Lei nº 10.666/2003', 'Decreto nº 3.048/1999 — FAP e RAT'] },

{ id: 'q-7.2-081', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a carência para benefícios por incapacidade, é CORRETO afirmar:',
  alts: [
    { t: 'A regra geral exige um mínimo de contribuições, mas há dispensa de carência no acidente de qualquer natureza e nas doenças que constam de lista própria', ok: true,
      why: 'Correta. É a natureza do evento que decide: acidente de qualquer natureza e as doenças listadas dispensam a carência.' },
    { t: 'A regra geral exige contribuições mínimas para todo benefício por incapacidade, sem hipótese de dispensa, ainda que o afastamento decorra de acidente.', ok: false,
      why: 'Errada. Há dispensas expressas — acidente de qualquer natureza e doenças de lista própria.' },
    { t: 'A regra geral exige contribuições mínimas, com dispensa restrita aos acidentes de trabalho típicos, ocorridos no exercício da atividade para a empresa.', ok: false,
      why: 'Errada. A dispensa alcança acidente de qualquer natureza, inclusive os sem relação com o trabalho.' },
    { t: 'A regra geral exige contribuições mínimas, e a lista de doenças que dispensam carência coincide com a lista de doenças ocupacionais do anexo previdenciário.', ok: false,
      why: 'Errada. São listas distintas, com finalidades diferentes; confundi-las faz esperar dispensa onde não há.' },
    { t: 'A regra geral exige contribuições mínimas, exigência que alcança igualmente os benefícios de natureza acidentária, por serem espécie do mesmo gênero.', ok: false,
      why: 'Errada. O benefício acidentário dispensa carência, e é uma das dispensas mais relevantes na prática.' }
  ],
  comentario: 'Carência: exigida na regra geral previdenciária, dispensada em acidente de qualquer natureza, nos benefícios acidentários e nas doenças de lista própria — que não se confunde com a lista de doenças ocupacionais.',
  pegadinha: 'Confundir as duas listas leva a esperar dispensa de carência onde ela não existe.',
  refs: ['Lei nº 8.213/1991 — arts. 25 e 26', 'Portaria interministerial sobre doenças que dispensam carência'] },

{ id: 'q-7.3-080', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a interface entre vigilância sanitária e vigilância em saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'O mesmo estabelecimento pode ser objeto das duas, com focos distintos: a sanitária no produto e na população, a do trabalhador no processo produtivo.', ok: true,
      why: 'Correta. Focos diferentes sobre o mesmo objeto, e atuar de forma articulada amplia o alcance das duas.' },
    { t: 'O mesmo estabelecimento pode ser objeto das duas, que são denominações diferentes para a mesma atividade e compartilham integralmente objeto e método.', ok: false,
      why: 'Errada. Há sobreposição parcial, mas os focos são distintos: produto e população de um lado, processo e exposição do outro.' },
    { t: 'O mesmo estabelecimento pode ser objeto das duas, cabendo à vigilância em saúde do trabalhador examinar a qualidade do produto final que ali se fabrica.', ok: false,
      why: 'Errada. O produto é objeto da sanitária; a do trabalhador olha o processo e a exposição de quem produz.' },
    { t: 'O mesmo estabelecimento pode ser objeto das duas, mas a atuação conjunta é vedada, para evitar conflito de competências entre os órgãos envolvidos.', ok: false,
      why: 'Errada. A atuação conjunta é recomendada e amplia o alcance da fiscalização; não há vedação.' },
    { t: 'O mesmo estabelecimento pode ser objeto das duas, mas a inspeção sanitária se limita ao público atendido, sem considerar quem trabalha no local.', ok: false,
      why: 'Errada. Trabalhadores são pessoas expostas e podem ser alcançados pela atuação sanitária.' }
  ],
  comentario: 'Mesmo estabelecimento, focos distintos: sanitária olha produto e população, do trabalhador olha processo e exposição de quem produz. Atuar junto amplia as duas.',
  pegadinha: 'Tratar as duas vigilâncias como sinônimas apaga a especificidade do olhar sobre o processo produtivo.',
  refs: ['Lei nº 8.080/1990', 'PNSTT'] },

{ id: 'q-7.4-080', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o programa de gerenciamento de riscos ocupacionais e o inventário de riscos, é CORRETO afirmar:',
  alts: [
    { t: 'O inventário reúne perigos e riscos, e dele decorre o plano de ação com prazos e responsáveis, revisto também por acidente ou mudança de processo.', ok: true,
      why: 'Correta. Inventário e plano são partes do mesmo programa, e há gatilhos que antecipam a revisão.' },
    { t: 'O inventário reúne perigos e riscos avaliados e tem revisão exclusivamente periódica, no prazo máximo previsto, sem gatilhos que possam antecipá-la.', ok: false,
      why: 'Errada. Acidente, mudança de processo e inadequação identificada disparam revisão antes do prazo.' },
    { t: 'O inventário reúne perigos e riscos avaliados, e o plano de ação é peça complementar de adoção facultativa, conforme a maturidade de cada empresa.', ok: false,
      why: 'Errada. O plano de ação é componente exigido e decorre diretamente do inventário.' },
    { t: 'O inventário reúne os perigos físicos, químicos, biológicos e de acidente, ficando os fatores ergonômicos e psicossociais fora do seu alcance normativo.', ok: false,
      why: 'Errada. Ergonômicos e psicossociais integram expressamente o conjunto de riscos a inventariar.' },
    { t: 'O inventário reúne perigos e riscos avaliados e é elaborado pela equipe técnica, dispensando a participação dos trabalhadores em sua construção.', ok: false,
      why: 'Errada. A participação é prevista e é o que traz o trabalho como ele acontece de fato.' }
  ],
  comentario: 'Inventário identifica e avalia; plano de ação sai dele com prazo e responsável. Riscos ergonômicos e psicossociais entram, os trabalhadores participam, e acidente ou mudança de processo dispara revisão antes do prazo.',
  pegadinha: 'Tratar o inventário como documento de prateleira revisado anualmente perde os gatilhos que importam.',
  refs: ['NR-1 — gerenciamento de riscos ocupacionais'] },

{ id: 'q-7.5-050', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre prazos, retificações e penalidades nos eventos de segurança e saúde do eSocial, é CORRETO afirmar:',
  alts: [
    { t: 'Os eventos têm prazos próprios, admitem retificação, e informação incorreta ou fora do prazo pode gerar penalidade para a empresa e para quem assina.', ok: true,
      why: 'Correta. E a divergência entre o informado e o constatado fica visível por cruzamento, sem depender de inspeção.' },
    { t: 'Os eventos de saúde e segurança são transmitidos conforme a conveniência da empresa, já que a norma não fixou prazo específico para essa categoria.', ok: false,
      why: 'Errada. Cada evento tem prazo próprio de envio, e a intempestividade tem consequência.' },
    { t: 'Os eventos têm prazos próprios de envio, mas uma vez transmitidos tornam-se definitivos, não havendo procedimento de retificação previsto.', ok: false,
      why: 'Errada. A retificação é prevista, ainda que possa haver consequência pela intempestividade.' },
    { t: 'Os eventos têm prazos próprios, e a informação incorreta só produz consequência se houver fiscalização presencial que a identifique no estabelecimento.', ok: false,
      why: 'Errada. A inconsistência é detectável por cruzamento automático, sem que ninguém vá até a empresa.' },
    { t: 'Os eventos têm prazos próprios, e a responsabilidade pelo conteúdo técnico de saúde recai sobre o setor contábil, que opera a transmissão.', ok: false,
      why: 'Errada. Quem opera o envio não assume a responsabilidade pelo conteúdo do ato médico.' }
  ],
  comentario: 'Prazo por evento, retificação possível, penalidade por erro e intempestividade — e cruzamento automático que dispensa inspeção para achar inconsistência. O conteúdo técnico de saúde responde quem o produz.',
  pegadinha: 'Contar com a ausência de fiscalização presencial ignora que o sistema cruza dados sozinho.',
  refs: ['eSocial — manual de orientação', 'Legislação sobre penalidades administrativas'] },

{ id: 'q-7.6-050', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a relação do médico do trabalho com o médico assistente do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A comunicação entre eles é desejável, feita com autorização do paciente, e a crítica pública ao colega perante o trabalhador configura infração ética.', ok: true,
      why: 'Correta. Informar as exigências reais da função qualifica o atestado; desqualificar o colega é infração.' },
    { t: 'A comunicação entre eles é desejável e, por ocorrer entre médicos sujeitos ao mesmo sigilo, dispensa autorização prévia do paciente para o compartilhamento.', ok: false,
      why: 'Errada. O titular da informação é o paciente, e o compartilhamento depende da autorização dele.' },
    { t: 'A comunicação entre eles é desejável, e havendo divergência técnica é legítimo apontá-la publicamente para preservar o interesse do trabalhador.', ok: false,
      why: 'Errada. A divergência se resolve tecnicamente; a crítica pública ao colega é infração ética.' },
    { t: 'A comunicação entre eles é desejável e permite ao médico do trabalho ajustar a prescrição do assistente quando ela conflitar com as exigências da função.', ok: false,
      why: 'Errada. Não lhe cabe alterar conduta terapêutica de outro profissional; cabe informar e discutir.' },
    { t: 'A comunicação entre eles é desejável, mas informar ao assistente as exigências reais do posto é dispensável, por ser matéria alheia à conduta clínica.', ok: false,
      why: 'Errada. É justamente essa informação que o assistente não tem e que qualifica o atestado dele.' }
  ],
  comentario: 'Comunicar-se com o assistente, com autorização do paciente, informando as exigências reais da função — é o que melhora a qualidade do atestado que virá. Sem alterar prescrição e sem crítica pública ao colega.',
  pegadinha: 'Comunicação direta entre médicos parece inofensiva e ainda assim depende de autorização do titular.',
  refs: ['Código de Ética Médica'] },

{ id: 'q-7.7-050', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a telemedicina aplicada à medicina do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O critério é o ato praticado, não o meio: avaliações que dependem de exame físico exigem presença, e o remoto observa registro, sigilo e segurança.', ok: true,
      why: 'Correta. Não é a modalidade que define a licitude, e sim a adequação dela ao ato que se pratica.' },
    { t: 'O critério é a conveniência do serviço, de modo que todos os atos da medicina do trabalho podem ser realizados remotamente com o mesmo valor legal.', ok: false,
      why: 'Errada. Atos que dependem de exame físico dirigido ao risco exigem presença.' },
    { t: 'O critério é a segurança do paciente, e por isso a modalidade remota é vedada em toda e qualquer atividade da medicina do trabalho.', ok: false,
      why: 'Errada. Há atos plenamente compatíveis com a modalidade remota.' },
    { t: 'O critério é o ato praticado, e no atendimento remoto o registro em prontuário pode ser substituído pelo próprio histórico da plataforma utilizada.', ok: false,
      why: 'Errada. O registro em prontuário é exigência independente do meio pelo qual o ato ocorreu.' },
    { t: 'O critério é o ato praticado, e a segurança da informação segue as mesmas exigências do atendimento presencial, sem requisitos adicionais.', ok: false,
      why: 'Errada. A transmissão de dados sensíveis impõe requisitos reforçados na modalidade remota.' }
  ],
  comentario: 'O que decide não é o meio, é o ato: avaliação que depende de exame físico dirigido ao risco não se faz por tela. Registro e segurança da informação valem em qualquer modalidade — reforçados na remota.',
  pegadinha: 'Os dois extremos erram: liberar tudo remotamente e proibir a modalidade inteira.',
  refs: ['Resoluções do CFM sobre telemedicina', 'Código de Ética Médica'] },

{ id: 'q-7.8-050', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre incidentes de segurança envolvendo dados de saúde de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Incidentes com risco relevante são comunicados à autoridade e aos afetados, e ter plano de resposta prévio reduz o dano e o tempo de reação.', ok: true,
      why: 'Correta. O critério é o risco relevante, e dado de saúde é sensível por definição.' },
    { t: 'Incidentes são comunicados à autoridade e aos afetados somente quando houver dano financeiro comprovado a algum dos titulares atingidos pelo vazamento.', ok: false,
      why: 'Errada. O critério é o risco relevante, e o dano típico aqui é discriminação e constrangimento.' },
    { t: 'Incidentes com risco relevante são comunicados à autoridade, ficando o aviso aos titulares atingidos a critério do controlador responsável pelos dados.', ok: false,
      why: 'Errada. A comunicação aos afetados é devida quando há risco relevante, não é opcional.' },
    { t: 'Incidentes com dados de saúde têm baixo potencial lesivo, por não terem valor comercial equivalente ao de dados financeiros ou de credenciais de acesso.', ok: false,
      why: 'Errada. São dados sensíveis, com alto potencial de discriminação e constrangimento do titular.' },
    { t: 'Incidentes com risco relevante são comunicados à autoridade e aos afetados, sendo indiferente, para as consequências, haver ou não plano de resposta.', ok: false,
      why: 'Errada. O plano reduz o dano, encurta a reação e é considerado na avaliação de responsabilidade.' }
  ],
  comentario: 'Vazamento de dado de saúde: comunicar autoridade e afetados quando há risco relevante, com o que houve e o que foi feito. Plano prévio reduz dano e conta a favor na avaliação de responsabilidade.',
  pegadinha: 'Exigir dano financeiro para comunicar ignora que o dano do dado de saúde é discriminação e constrangimento.',
  refs: ['LGPD — arts. 48 e 50', 'Código de Ética Médica'] }

);
