/* Lote AS — 2.2, 2.3, 2.4, 2.6, 2.7, 2.9, 4.4, 4.5, 4.6, 4.8, 4.9, 4.10. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.2-140', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a radiação ultravioleta artificial, é CORRETO afirmar:',
  alts: [
    { t: 'Soldagem, esterilização por ultravioleta, fototerapia e processos de cura de resinas geram exposição, com risco de ceratoconjuntivite e lesão cutânea — e o alcance atinge trabalhadores próximos, o que justifica barreiras e delimitação de área, não apenas proteção do operador.', ok: true,
      why: 'Correta. O terceiro que passa perto é atingido sem estar protegido.' },
    { t: 'A exposição a ultravioleta artificial se limita ao operador direto do processo.', ok: false,
      why: 'Errada. Trabalhadores próximos são atingidos, o que exige barreiras.' },
    { t: 'A ceratoconjuntivite actínica se manifesta imediatamente durante a exposição.', ok: false,
      why: 'Errada. Costuma se manifestar horas depois, o que dificulta a associação com a causa.' },
    { t: 'Lâmpadas germicidas em ambientes de saúde não representam risco ocupacional.', ok: false,
      why: 'Errada. Exigem projeto e procedimento para evitar exposição de pessoas.' },
    { t: 'A proteção ocular convencional é suficiente para qualquer processo com ultravioleta.', ok: false,
      why: 'Errada. É preciso proteção com especificação adequada à faixa e à intensidade.' }
  ],
  comentario: 'Ultravioleta artificial: solda, germicida, fototerapia, cura de resina. Atinge quem passa perto, e a ceratoconjuntivite aparece horas depois — o que faz o trabalhador não relacionar o olho ardendo à noite com a solda da tarde.',
  pegadinha: 'A latência de horas do quadro ocular é o que impede o trabalhador de identificar a causa sozinho.',
  refs: ['ICNIRP', 'ACGIH', 'NR-15'] },

{ id: 'q-2.3-140', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a fumos metálicos em soldagem, é CORRETO afirmar:',
  alts: [
    { t: 'A composição dos fumos depende do metal base, do revestimento e do consumível utilizado, podendo conter cromo hexavalente, manganês, níquel e cádmio — de modo que a avaliação exige conhecer o material efetivamente soldado, e não apenas identificar a atividade como soldagem.', ok: true,
      why: 'Correta. "Soldagem" não é uma exposição: são muitas, conforme o material.' },
    { t: 'Os fumos de soldagem têm composição uniforme, independentemente do material.', ok: false,
      why: 'Errada. Metal base, revestimento e consumível determinam a composição.' },
    { t: 'A febre dos fumos metálicos é quadro sem relevância ocupacional.', ok: false,
      why: 'Errada. É quadro reconhecido, associado sobretudo à soldagem de galvanizados.' },
    { t: 'A ventilação geral do galpão é medida adequada de controle na soldagem.', ok: false,
      why: 'Errada. Exige-se exaustão junto ao ponto de soldagem.' },
    { t: 'A remoção de revestimentos antes da soldagem não altera a exposição.', ok: false,
      why: 'Errada. Revestimentos são fonte de agentes como cádmio, chumbo e cromo nos fumos.' }
  ],
  comentario: 'Fumo de solda depende do que se solda: cromo hexavalente no inoxidável, manganês nos consumíveis, cádmio e chumbo em revestimentos, zinco na febre dos fumos metálicos. Exaustão no ponto, não ventilação do galpão.',
  pegadinha: 'Registrar a exposição como "fumos de solda" sem identificar o material avalia um agente genérico que não existe.',
  refs: ['ACGIH', 'NHO — Fundacentro', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.4-140', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a agentes biológicos em atividades de limpeza urbana e coleta de resíduos, é CORRETO afirmar:',
  alts: [
    { t: 'Há exposição a material perfurocortante descartado inadequadamente por terceiros, além de agentes de zoonoses e resíduos de serviços de saúde misturados ao lixo comum — o que faz da segregação na origem uma medida de proteção desses trabalhadores.', ok: true,
      why: 'Correta. Quem se fere é o coletor, e a causa está no descarte de outra pessoa.' },
    { t: 'O risco desses trabalhadores decorre exclusivamente de agentes químicos.', ok: false,
      why: 'Errada. O risco biológico é central nessas atividades.' },
    { t: 'O descarte inadequado por terceiros não é fator de risco relevante.', ok: false,
      why: 'Errada. É a principal causa de acidentes com perfurocortantes nesse grupo.' },
    { t: 'A segregação de resíduos não tem relação com a saúde dos coletores.', ok: false,
      why: 'Errada. É a medida que mais reduz o risco de quem manuseia adiante.' },
    { t: 'Coletores não integram grupos com indicação de imunização antitetânica reforçada.', ok: false,
      why: 'Errada. O risco de ferimentos torna a proteção antitetânica prioridade nesse grupo.' }
  ],
  comentario: 'O coletor se acidenta com a agulha que outra pessoa descartou errado. Segregar na origem é medida de proteção dele — junto com imunização antitetânica e equipamento adequado.',
  pegadinha: 'Ver a segregação de resíduos como assunto ambiental esquece que ela protege quem recolhe.',
  refs: ['NR-32', 'RDC sobre resíduos de serviços de saúde', 'Programa Nacional de Imunizações'] },

{ id: 'q-2.6-140', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a leitura de uma lista de limites de exposição, é CORRETO afirmar:',
  alts: [
    { t: 'Além do valor numérico, a entrada de cada agente traz notações e o efeito crítico que fundamentou o limite — e conhecer o efeito crítico é o que permite escolher o exame de vigilância adequado para aquela exposição.', ok: true,
      why: 'Correta. O efeito crítico indica o que vigiar na saúde do exposto.' },
    { t: 'O valor numérico é a única informação relevante da entrada de cada agente.', ok: false,
      why: 'Errada. Notações e efeito crítico orientam medidas e vigilância.' },
    { t: 'O efeito crítico não tem utilidade para a definição dos exames de vigilância.', ok: false,
      why: 'Errada. É justamente o que indica o alvo a monitorar.' },
    { t: 'Notações como absorção cutânea e sensibilização são meramente informativas.', ok: false,
      why: 'Errada. Alteram as medidas de controle e a interpretação do limite.' },
    { t: 'Agentes sem valor numérico definido não constam dessas listas.', ok: false,
      why: 'Errada. Há entradas com recomendação de reduzir ao mínimo exequível, sem valor numérico.' }
  ],
  comentario: 'A entrada do agente traz mais que um número: notações e o efeito crítico que fundamentou o valor. É o efeito crítico que indica qual exame faz sentido na vigilância daquele exposto.',
  pegadinha: 'Copiar apenas o valor numérico da tabela descarta a informação que orienta o programa médico.',
  refs: ['ACGIH — TLVs e documentação', 'NR-7', 'NR-9'] },

{ id: 'q-2.7-120', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a calibração e a verificação de instrumentos usados em avaliações de higiene ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A calibração deve ser realizada por entidade competente com rastreabilidade, e a verificação de campo antes e depois de cada avaliação é procedimento distinto e igualmente necessário — sua ausência compromete a validade de todo o conjunto de medições.', ok: true,
      why: 'Correta. Calibração periódica e verificação de campo são coisas diferentes e ambas exigidas.' },
    { t: 'A calibração periódica dispensa a verificação de campo.', ok: false,
      why: 'Errada. São procedimentos distintos e complementares.' },
    { t: 'A verificação de campo pode ser feita apenas no início da avaliação.', ok: false,
      why: 'Errada. A verificação após a medição confirma que o instrumento manteve o desempenho.' },
    { t: 'O certificado de calibração não precisa constar da documentação do laudo.', ok: false,
      why: 'Errada. Integra a documentação que sustenta a confiabilidade do resultado.' },
    { t: 'Desvios identificados na verificação posterior não invalidam as medições realizadas.', ok: false,
      why: 'Errada. Desvio relevante compromete os resultados obtidos no período.' }
  ],
  comentario: 'Calibração com rastreabilidade e verificação de campo antes e depois — procedimentos distintos, ambos exigidos, ambos documentados. Desvio na verificação final compromete tudo o que foi medido no dia.',
  pegadinha: 'Verificar só no início deixa sem detecção o desvio que ocorreu durante a jornada de medição.',
  refs: ['NHO — Fundacentro', 'AIHA'] },

{ id: 'q-2.9-140', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de resultados de monitoramento biológico ao trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'O resultado deve ser comunicado e explicado ao trabalhador, incluindo o significado do valor e as medidas decorrentes — e resultados alterados exigem, além da conduta individual, revisão coletiva da exposição do grupo a que ele pertence.', ok: true,
      why: 'Correta. Um resultado alterado é sinal sobre o grupo, não apenas sobre a pessoa.' },
    { t: 'O resultado deve ser arquivado e comunicado apenas se houver necessidade de afastamento.', ok: false,
      why: 'Errada. O trabalhador tem direito de conhecer e compreender o resultado.' },
    { t: 'Resultado alterado em um trabalhador não indica necessidade de revisão do grupo.', ok: false,
      why: 'Errada. Sinaliza possível falha de controle que alcança os demais.' },
    { t: 'A explicação do significado do resultado é dispensável quando o valor está normal.', ok: false,
      why: 'Errada. Compreender o significado do monitoramento sustenta a adesão ao programa.' },
    { t: 'O resultado pode ser comunicado por meio da chefia imediata do trabalhador.', ok: false,
      why: 'Errada. É informação de saúde, comunicada diretamente pelo médico ao trabalhador.' }
  ],
  comentario: 'Resultado de monitoramento biológico se comunica e se explica ao trabalhador — diretamente, nunca pela chefia. E alterado em um é hipótese de falha de controle que alcança o grupo inteiro.',
  pegadinha: 'Tratar o resultado alterado como caso individual perde o sinal que ele dá sobre o setor.',
  refs: ['NR-7', 'ACGIH — BEIs', 'Código de Ética Médica'] },

{ id: 'q-4.4-140', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o retorno ao trabalho de trabalhador com dermatose ocupacional em mãos, é CORRETO afirmar:',
  alts: [
    { t: 'O retorno depende da eliminação ou do controle efetivo do contato, e o uso de luva pode ser insuficiente ou até prejudicial pela oclusão — de modo que a mudança de processo ou de produto costuma ser a intervenção que efetivamente permite a permanência na função.', ok: true,
      why: 'Correta. A intervenção que resolve costuma estar no processo, não no equipamento.' },
    { t: 'O uso de luva resolve a maioria dos casos, permitindo retorno imediato.', ok: false,
      why: 'Errada. Pode ser insuficiente e, pela oclusão, agravar a dermatite irritativa.' },
    { t: 'A cicatrização das lesões autoriza o retorno independentemente do controle do agente.', ok: false,
      why: 'Errada. Retorno ao mesmo contato reproduz o quadro.' },
    { t: 'A substituição do produto não é alternativa aplicável nesses casos.', ok: false,
      why: 'Errada. É frequentemente a intervenção mais eficaz.' },
    { t: 'Dermatose em mãos não gera repercussão funcional relevante.', ok: false,
      why: 'Errada. Compromete preensão, contato com materiais e higienização, com impacto direto em muitas funções.' }
  ],
  comentario: 'Retorno em dermatose de mãos exige eliminar ou controlar o contato — e luva pode piorar por oclusão. Trocar o produto ou o processo é o que costuma permitir a permanência na função.',
  pegadinha: 'Liberar o retorno na cicatrização, sem mexer no agente, agenda a próxima recidiva.',
  refs: ['Salim — Dermatoses Ocupacionais', 'NR-6'] },

{ id: 'q-4.5-130', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a caracterização da perda auditiva induzida por ruído para fins de reconhecimento, é CORRETO afirmar:',
  alts: [
    { t: 'A caracterização considera o padrão audiométrico, a história de exposição documentada e a exclusão razoável de outras causas — e o fato de a perda ser irreversível e não progredir após cessada a exposição é elemento que a distingue de outras etiologias.', ok: true,
      why: 'Correta. Estabilização após o afastamento é característica do quadro.' },
    { t: 'A perda induzida por ruído continua progredindo após o afastamento da exposição.', ok: false,
      why: 'Errada. Tende a estabilizar após cessada a exposição.' },
    { t: 'O padrão audiométrico isolado é suficiente para a caracterização.', ok: false,
      why: 'Errada. Exige história de exposição e exclusão de outras causas.' },
    { t: 'A perda induzida por ruído é reversível quando detectada precocemente.', ok: false,
      why: 'Errada. A perda permanente instalada é irreversível; o que se evita é a progressão.' },
    { t: 'A exposição extraocupacional a ruído não precisa ser investigada.', ok: false,
      why: 'Errada. Deve ser considerada na análise, sem que afaste automaticamente a contribuição ocupacional.' }
  ],
  comentario: 'Caracterizar exige padrão audiométrico, exposição documentada e exclusão razoável de outras causas. A perda é irreversível e estabiliza após o afastamento — o que se ganha detectando cedo é impedir a progressão.',
  pegadinha: 'Prometer recuperação com o afastamento cria expectativa que o quadro não permite.',
  refs: ['NR-7 — Anexo I', 'Diretrizes de audiologia ocupacional'] },

{ id: 'q-4.6-130', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o papel da chefia imediata na saúde mental das equipes, é CORRETO afirmar:',
  alts: [
    { t: 'O estilo de gestão da chefia imediata é um dos fatores mais consistentemente associados a desfechos de saúde mental da equipe, e sua capacitação em reconhecimento de sinais e em práticas de suporte é intervenção com efeito documentado.', ok: true,
      why: 'Correta. É a variável organizacional mais próxima do trabalhador.' },
    { t: 'O estilo de gestão da chefia não tem associação com a saúde mental da equipe.', ok: false,
      why: 'Errada. É associação consistentemente documentada.' },
    { t: 'A capacitação de chefias em saúde mental não altera desfechos.', ok: false,
      why: 'Errada. Há evidência de efeito sobre suporte percebido e sobre desfechos de afastamento.' },
    { t: 'A chefia deve ser informada dos diagnósticos dos membros da equipe para exercer esse papel.', ok: false,
      why: 'Errada. O papel se exerce com informação sobre restrições e suporte, nunca com diagnósticos.' },
    { t: 'O suporte da chefia é irrelevante no processo de retorno após afastamento.', ok: false,
      why: 'Errada. É um dos preditores mais fortes do sucesso do retorno.' }
  ],
  comentario: 'A chefia imediata é a variável organizacional mais próxima do trabalhador — e capacitá-la em reconhecimento e suporte tem efeito documentado. Sem jamais receber diagnóstico: recebe restrição e orientação de suporte.',
  pegadinha: 'Capacitar a chefia não significa informá-la de diagnósticos; a linha entre suporte e quebra de sigilo é essa.',
  refs: ['OIT — riscos psicossociais', 'Literatura sobre retorno ao trabalho', 'Código de Ética Médica'] },

{ id: 'q-4.8-130', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a substituição de agentes cancerígenos em processos produtivos, é CORRETO afirmar:',
  alts: [
    { t: 'A substituição deve ser precedida de avaliação do agente substituto, para evitar troca por substância de perfil toxicológico desconhecido ou pior — situação já ocorrida historicamente e conhecida como substituição lamentável.', ok: true,
      why: 'Correta. Trocar sem avaliar já produziu substituições piores que o original.' },
    { t: 'Qualquer substituição de agente cancerígeno representa ganho automático.', ok: false,
      why: 'Errada. O substituto pode ter perfil toxicológico pior ou desconhecido.' },
    { t: 'A ausência de classificação do substituto significa ausência de risco.', ok: false,
      why: 'Errada. Pode significar apenas ausência de estudos, o que é diferente.' },
    { t: 'A substituição dispensa reavaliação do inventário de riscos.', ok: false,
      why: 'Errada. Novo agente exige nova avaliação.' },
    { t: 'A avaliação do substituto deve considerar apenas a carcinogenicidade.', ok: false,
      why: 'Errada. Deve considerar o conjunto de efeitos, inclusive reprodutivos e sensibilizantes.' }
  ],
  comentario: 'Substituir cancerígeno é prioridade, mas com avaliação do substituto — inclusive efeitos reprodutivos e sensibilizantes. Ausência de classificação costuma significar ausência de estudo, não ausência de risco.',
  pegadinha: '"Não consta como cancerígeno" pode significar apenas que ninguém estudou.',
  refs: ['IARC', 'ACGIH', 'NR-9'] },

{ id: 'q-4.9-120', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a investigação de surto de doença transmissível em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A investigação define caso, levanta a curva epidêmica, identifica exposições comuns e testa hipóteses sobre a fonte — e a caracterização do padrão temporal e espacial dos casos costuma apontar a exposição compartilhada antes de qualquer exame laboratorial.', ok: true,
      why: 'Correta. Tempo e lugar dos casos indicam a fonte antes do laboratório.' },
    { t: 'A investigação depende necessariamente de confirmação laboratorial prévia.', ok: false,
      why: 'Errada. A investigação epidemiológica se inicia com definição de caso e não aguarda confirmação.' },
    { t: 'A distribuição espacial dos casos na planta não é informação relevante.', ok: false,
      why: 'Errada. É uma das principais pistas sobre a exposição compartilhada.' },
    { t: 'A definição de caso deve ser feita ao final da investigação.', ok: false,
      why: 'Errada. É a primeira etapa, e orienta toda a coleta subsequente.' },
    { t: 'Medidas de controle devem aguardar a conclusão da investigação.', ok: false,
      why: 'Errada. Medidas iniciais são adotadas em paralelo, conforme as hipóteses.' }
  ],
  comentario: 'Surto: define-se caso, monta-se a curva, mapeiam-se os casos no espaço e se testam hipóteses — com medidas de controle iniciadas em paralelo, sem esperar a conclusão nem o laboratório.',
  pegadinha: 'Aguardar confirmação laboratorial para agir consome o tempo em que a medida de controle interromperia a transmissão.',
  refs: ['Ministério da Saúde — investigação de surtos', 'NR-32'] },

{ id: 'q-4.10-120', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a indicação de imunização em trabalhadores de laboratório, é CORRETO afirmar:',
  alts: [
    { t: 'A indicação decorre dos agentes efetivamente manipulados e do nível de contenção da atividade, podendo incluir imunizações não previstas no calendário geral — e a avaliação deve ser refeita quando muda a linha de pesquisa ou o agente manipulado.', ok: true,
      why: 'Correta. Mudança de agente manipulado é gatilho de reavaliação vacinal.' },
    { t: 'A indicação segue apenas o calendário vacinal do adulto.', ok: false,
      why: 'Errada. Pode incluir imunizações específicas conforme os agentes manipulados.' },
    { t: 'A mudança de agente manipulado não requer reavaliação da situação vacinal.', ok: false,
      why: 'Errada. É gatilho direto de reavaliação.' },
    { t: 'O nível de contenção da atividade não influencia a indicação.', ok: false,
      why: 'Errada. Compõe a avaliação de risco que fundamenta a indicação.' },
    { t: 'A verificação de resposta sorológica não se aplica a esses trabalhadores.', ok: false,
      why: 'Errada. É especialmente indicada em grupos de alto risco de exposição.' }
  ],
  comentario: 'Em laboratório, a vacina segue o agente manipulado e o nível de contenção — inclusive imunizações fora do calendário geral. Trocou de linha de pesquisa, reavalia.',
  pegadinha: 'Aplicar o calendário do adulto e considerar resolvido ignora os agentes específicos daquela bancada.',
  refs: ['NR-32', 'Programa Nacional de Imunizações', 'Diretrizes de biossegurança'] }

);
