/* Lote G — 2.2, 1.3, 2.6, 2.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.2-050', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Operador de britadeira portátil e motorista de caminhão fora de estrada trabalham na mesma pedreira. Sobre a exposição a vibração, é CORRETO afirmar:',
  alts: [
    { t: 'O primeiro se expõe a vibração de mãos e braços; o segundo, a de corpo inteiro, associada a alterações lombares', ok: true,
      why: 'Correta. A via de entrada define o órgão-alvo, o método de avaliação e o desfecho esperado.' },
    { t: 'Ambos se expõem ao mesmo tipo de vibração, variando apenas a intensidade transmitida pela ferramenta ou pelo assento.', ok: false,
      why: 'Errada. Ferramenta manual e assento transmitem vibração por vias e a segmentos distintos.' },
    { t: 'O primeiro se expõe a vibração de mãos e braços; o segundo, a corpo inteiro, que produz o fenômeno de Raynaud.', ok: false,
      why: 'Errada. O fenômeno vascular dos dedos decorre da vibração de mãos e braços.' },
    { t: 'O primeiro se expõe a vibração de mãos e braços, principal causa ocupacional de lombalgia; o segundo, a corpo inteiro.', ok: false,
      why: 'Errada. A associação com lombalgia é da vibração de corpo inteiro.' },
    { t: 'O primeiro se expõe a vibração de mãos e braços e o segundo a corpo inteiro, sendo a postura irrelevante na avaliação.', ok: false,
      why: 'Errada. Postura sentada com flexão de tronco modula o efeito da vibração de corpo inteiro.' }
  ],
  comentario: 'Ferramenta na mão → vibração de mãos e braços → dedos brancos, parestesia, perda de destreza. Assento de veículo → corpo inteiro → coluna lombar. Métodos de medição, órgão-alvo e desfecho: tudo diferente.',
  pegadinha: 'Tratar as duas como uma só exposição, variando só a intensidade, elimina a distinção que organiza todo o tema.',
  refs: ['Normas de Higiene Ocupacional — Fundacentro', 'NR-15', 'Couto — Ergonomia'] },

{ id: 'q-2.2-051', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadores de uma caldeiraria relatam que, ao fim do turno, os sons parecem abafados, com recuperação durante a noite. Sobre o fenômeno, é CORRETO afirmar:',
  alts: [
    { t: 'É mudança temporária de limiar, reversível com repouso, cuja repetição antecede a perda permanente da audição', ok: true,
      why: 'Correta. O deslocamento temporário repetido sinaliza que o controle da exposição falhou.' },
    { t: 'É mudança temporária de limiar, esperada ao fim do turno e sem indicar necessidade de revisão do controle.', ok: false,
      why: 'Errada. Sua ocorrência sistemática é indicador de exposição excessiva.' },
    { t: 'É mudança temporária de limiar, e a recuperação durante a noite demonstra ausência de risco de dano permanente.', ok: false,
      why: 'Errada. A reversão do episódio não impede o acúmulo de dano com a repetição.' },
    { t: 'É mudança temporária de limiar, que só ocorre quando a exposição ultrapassa o limite de tolerância vigente.', ok: false,
      why: 'Errada. Pode ocorrer abaixo do limite, conforme a suscetibilidade e o padrão de exposição.' },
    { t: 'É mudança temporária de limiar, e a audiometria feita nessa condição reflete a audição basal do trabalhador.', ok: false,
      why: 'Errada. É exatamente a condição que o repouso auditivo prévio existe para evitar.' }
  ],
  comentario: 'Sensação de audição abafada ao fim do turno é deslocamento temporário de limiar. Reverte, mas repetido todo dia antecede a perda permanente — é indicador de que a exposição não está controlada.',
  pegadinha: 'A reversibilidade é usada para tranquilizar e é justamente o que precede o dano irreversível.',
  refs: ['NHO 01 — Fundacentro', 'Gândara — Doenças Otorrinolaringológicas Relacionadas ao Trabalho'] },

{ id: 'q-2.2-052', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a radiação ultravioleta em atividades a céu aberto, é CORRETO afirmar:',
  alts: [
    { t: 'A exposição é cumulativa, e o controle prioriza sombreamento, horários e vestimenta, com protetor complementar.', ok: true,
      why: 'Correta. A hierarquia se aplica aqui: sombra e horário antes de vestimenta, e esta antes do protetor.' },
    { t: 'A exposição é cumulativa ao longo dos anos, resumindo-se a proteção adequada ao fornecimento de protetor solar.', ok: false,
      why: 'Errada. É a última medida da hierarquia e depende de reaplicação frequente para funcionar.' },
    { t: 'A exposição é cumulativa e o controle prioriza sombreamento, sendo dispensáveis as medidas em dias nublados.', ok: false,
      why: 'Errada. Parcela relevante da radiação ultravioleta atravessa a cobertura de nuvens.' },
    { t: 'A exposição é cumulativa e o controle prioriza sombreamento, restringindo-se os efeitos à pele, sem repercussão ocular.', ok: false,
      why: 'Errada. Há efeitos oculares agudos e crônicos, incluindo catarata.' },
    { t: 'A exposição é cumulativa e o controle prioriza sombreamento, sem que a radiação solar seja reconhecida como carcinogênica.', ok: false,
      why: 'Errada. A radiação solar é reconhecida como carcinogênica para a pele.' }
  ],
  comentario: 'Trabalho a céu aberto é exposição ocupacional a radiação ultravioleta: cumulativa, com efeitos cutâneos, oculares e imunológicos. Controle por sombra e horário primeiro; protetor solar é complemento, não solução.',
  pegadinha: 'A crença de que dia nublado protege é comum entre trabalhadores rurais e de construção.',
  refs: ['IARC Monographs', 'Salim — Dermatoses Ocupacionais', 'NR-31'] },

{ id: 'q-1.3-050', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um estudo transversal em uma indústria encontrou associação entre tempo de exposição a um agente e prevalência de sintomas. Sobre as limitações do desenho, é CORRETO afirmar:',
  alts: [
    { t: 'Ele mede exposição e desfecho ao mesmo tempo, o que dificulta a temporalidade e o expõe ao trabalhador sadio.', ok: true,
      why: 'Correta. Quem adoeceu e saiu não está lá para ser contado, o que reduz a associação observada.' },
    { t: 'Ele mede exposição e desfecho de forma simultânea, o que permite estabelecer a relação temporal entre ambos.', ok: false,
      why: 'Errada. Medindo os dois ao mesmo tempo, a temporalidade não se estabelece.' },
    { t: 'Ele mede exposição e desfecho ao mesmo tempo, e o efeito do trabalhador sadio tende a superestimar a associação.', ok: false,
      why: 'Errada, é o oposto: tende a subestimar, porque os mais afetados já saíram.' },
    { t: 'Ele mede exposição e desfecho ao mesmo tempo, o que permite calcular a incidência da doença na população estudada.', ok: false,
      why: 'Errada. Ele mede prevalência, não incidência.' },
    { t: 'Ele mede exposição e desfecho ao mesmo tempo, e a ausência de grupo de comparação inviabiliza qualquer análise.', ok: false,
      why: 'Errada. É possível comparar estratos de exposição dentro da própria população estudada.' }
  ],
  comentario: 'Transversal mede prevalência, não incidência, e não estabelece temporalidade. Em população ocupacional ainda sofre o efeito do trabalhador sadio, que subestima a associação — quem adoeceu já não está no setor para responder.',
  pegadinha: 'Inverter o sentido do viés — dizer que superestima — é o erro mais frequente sobre o efeito do trabalhador sadio.',
  refs: ['Fletcher — Epidemiologia Clínica', 'Hulley — Delineando a pesquisa clínica'] },

{ id: 'q-1.3-051', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao avaliar a qualidade de um estudo que sustenta o nexo entre um agente e uma doença, o médico do trabalho considera os critérios de causalidade. Sobre eles, é CORRETO afirmar:',
  alts: [
    { t: 'São critérios de julgamento, não lista obrigatória: só a temporalidade é indispensável; os demais reforçam.', ok: true,
      why: 'Correta. Temporalidade é condição lógica; os outros aumentam a confiança sem serem requisitos isolados.' },
    { t: 'São critérios de julgamento que precisam estar todos presentes para que se admita a existência de relação causal.', ok: false,
      why: 'Errada. Exigir todos inviabilizaria o reconhecimento de praticamente qualquer causalidade em saúde.' },
    { t: 'São critérios de julgamento e não lista obrigatória, sendo a força de associação o único deles indispensável.', ok: false,
      why: 'Errada. O indispensável é a temporalidade: a causa precede o efeito.' },
    { t: 'São critérios de julgamento, entre os quais o gradiente dose-resposta, sempre observável nas doenças ocupacionais.', ok: false,
      why: 'Errada. Em fenômenos com limiar ou saturação, o gradiente pode não aparecer.' },
    { t: 'São critérios de julgamento, e a plausibilidade biológica depende de mecanismo completamente elucidado.', ok: false,
      why: 'Errada. Exige compatibilidade com o conhecimento disponível, não mecanismo totalmente conhecido.' }
  ],
  comentario: 'Os critérios de causalidade são ferramenta de julgamento, não checklist. Temporalidade é o único logicamente indispensável. Exigir todos os demais é a forma mais elegante de nunca reconhecer nexo algum.',
  pegadinha: 'Transformar os critérios em requisitos cumulativos é o argumento técnico mais sofisticado contra o reconhecimento de doenças ocupacionais.',
  refs: ['Fletcher — Epidemiologia Clínica'] },

{ id: 'q-1.3-052', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a interpretação de uma revisão sistemática que conclui pela ausência de evidência de associação entre um agente e um desfecho, é CORRETO afirmar:',
  alts: [
    { t: 'Ausência de evidência não é evidência de ausência: pode refletir escassez de estudos ou poder insuficiente.', ok: true,
      why: 'Correta. Distinguir as duas coisas é decisivo onde muitos agentes simplesmente não foram bem estudados.' },
    { t: 'A conclusão pela ausência de associação demonstra que o agente é seguro nas condições habituais de uso.', ok: false,
      why: 'Errada. Não estudado ou mal estudado não é sinônimo de seguro.' },
    { t: 'Ausência de evidência não é evidência de ausência, e a revisão sistemática dispensa avaliar a qualidade dos estudos.', ok: false,
      why: 'Errada. A qualidade dos estudos incluídos determina a confiança na conclusão.' },
    { t: 'Ausência de evidência não é evidência de ausência, mas a falta de estudos autoriza dispensar medidas de controle.', ok: false,
      why: 'Errada. Na ausência de conhecimento, a prudência recomenda manter o controle.' },
    { t: 'Ausência de evidência não é evidência de ausência, sendo revisão sistemática e metanálise termos sinônimos.', ok: false,
      why: 'Errada. A metanálise é a combinação estatística, que nem toda revisão sistemática comporta.' }
  ],
  comentario: 'Em saúde ocupacional, "não há evidência" costuma significar "não foi estudado". Converter isso em "é seguro" é o erro que sustentou décadas de exposição a agentes hoje reconhecidos como perigosos.',
  pegadinha: 'A conversão de ausência de evidência em prova de segurança é o argumento histórico da indústria do asbesto.',
  refs: ['Fletcher — Epidemiologia Clínica', 'Hulley — Delineando a pesquisa clínica'] },

{ id: 'q-2.6-060', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a relação entre limites de exposição ocupacional e suscetibilidade individual, é CORRETO afirmar:',
  alts: [
    { t: 'Protegem a maioria em condições definidas, mas hipersuscetíveis podem apresentar efeito abaixo do limite.', ok: true,
      why: 'Correta. É a limitação declarada nas próprias documentações e a razão de o acompanhamento ser individual.' },
    { t: 'Protegem todos os trabalhadores expostos, por serem fixados com margem de segurança sobre o efeito observado.', ok: false,
      why: 'Errada. Nenhuma documentação de referência faz essa afirmação.' },
    { t: 'Protegem a maioria, e a suscetibilidade individual justifica excluir esses trabalhadores da contratação.', ok: false,
      why: 'Errada e discriminatória. A resposta é controlar a exposição e acompanhar, não selecionar pessoas.' },
    { t: 'Protegem a maioria em condições definidas, sendo a suscetibilidade irrelevante quando a exposição está controlada.', ok: false,
      why: 'Errada. É justamente ela que explica efeitos em situações consideradas controladas.' },
    { t: 'Protegem a maioria, tornando dispensável o acompanhamento médico quando a exposição está abaixo do limite.', ok: false,
      why: 'Errada. O acompanhamento existe em boa parte para detectar quem responde diferente do esperado.' }
  ],
  comentario: 'Limite protege a maioria, não todos. Daí a existência do acompanhamento médico individual: ele é a rede que pega quem responde fora do padrão. E a resposta ao hipersuscetível é proteger, nunca excluir.',
  pegadinha: 'Usar a suscetibilidade individual para justificar seleção na admissão inverte a proteção em discriminação.',
  refs: ['ACGIH — TLVs e BEIs', 'NR-7'] },

{ id: 'q-2.6-061', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a aplicação de valores-limite a agentes com notação de risco reprodutivo ou de efeito sobre o desenvolvimento, é CORRETO afirmar:',
  alts: [
    { t: 'Sinaliza risco reprodutivo específico e exige afastar exposições incompatíveis, sem excluir mulheres da função', ok: true,
      why: 'Correta. A proteção é da exposição, não das pessoas, e o risco também alcança homens.' },
    { t: 'Sinaliza risco reprodutivo específico, o que justifica não contratar mulheres em idade fértil para a função.', ok: false,
      why: 'Errada e discriminatória. A solução é controlar a exposição, não selecionar por sexo.' },
    { t: 'Sinaliza risco reprodutivo específico, que atinge apenas as trabalhadoras mulheres expostas ao agente.', ok: false,
      why: 'Errada. Há efeitos sobre a fertilidade masculina documentados para diversos agentes.' },
    { t: 'Sinaliza risco reprodutivo específico, tornando-se irrelevante quando a exposição está abaixo do limite geral.', ok: false,
      why: 'Errada. A janela de vulnerabilidade é estreita e o limite geral pode não proteger.' },
    { t: 'Sinaliza risco reprodutivo específico, sendo dispensável a comunicação desse risco às trabalhadoras expostas.', ok: false,
      why: 'Errada. A informação é condição para decisões conscientes e para o exercício de direitos.' }
  ],
  comentario: 'Risco reprodutivo alcança homens e mulheres. A resposta é sempre a mesma: controlar a exposição e informar — nunca selecionar pessoas por sexo ou por planos reprodutivos, o que é discriminação e não protege ninguém.',
  pegadinha: 'A exclusão de mulheres da função aparece como proteção e é a forma clássica de discriminação em saúde ocupacional.',
  refs: ['ACGIH — TLVs e BEIs', 'CLT — proteção à maternidade', 'Lei nº 13.146/2015'] },

{ id: 'q-2.4-050', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de laboratório de pesquisa manipula cultura de agente de classe de risco 3 em procedimento que gera aerossol. Sobre a contenção necessária, é CORRETO afirmar:',
  alts: [
    { t: 'Exige contenção primária em cabine adequada, somada a práticas e instalação compatíveis com o nível exigido.', ok: true,
      why: 'Correta. A classe do agente define o piso, e o procedimento gerador de aerossol pode elevar a exigência.' },
    { t: 'Exige contenção definida integralmente pela classe do agente manipulado, independentemente do procedimento adotado.', ok: false,
      why: 'Errada. Procedimentos geradores de aerossol podem exigir contenção adicional.' },
    { t: 'Exige práticas laboratoriais adequadas, podendo o equipamento de proteção individual substituir a contenção primária.', ok: false,
      why: 'Errada. Contenção primária é barreira entre agente e trabalhador; o equipamento individual é complementar.' },
    { t: 'Exige contenção primária, sendo cabine de segurança biológica e capela de exaustão química intercambiáveis.', ok: false,
      why: 'Errada. Têm princípios e finalidades distintas; a capela química não protege contra risco biológico.' },
    { t: 'Exige contenção primária em cabine adequada, sendo dispensável a validação periódica de seu desempenho.', ok: false,
      why: 'Errada. A certificação periódica é condição para que a contenção continue existindo.' }
  ],
  comentario: 'Contenção = prática + equipamento + instalação. A classe do agente dá o piso; o procedimento gerador de aerossol pode elevar. E cabine de segurança biológica não é capela química — confundir as duas é erro grave e comum.',
  pegadinha: 'Tratar equipamento individual como substituto da contenção primária inverte a hierarquia de proteção.',
  refs: ['Classificação de Risco dos Agentes Biológicos — Ministério da Saúde', 'NR-32'] },

{ id: 'q-2.4-051', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o risco biológico em atividades funerárias e de necropsia, é CORRETO afirmar:',
  alts: [
    { t: 'Há exposição a agentes de transmissão sanguínea e por aerossóis, exigindo precauções padrão e protocolo próprio.', ok: true,
      why: 'Correta. O corpo sem vida não elimina o risco, e serra e perfurocortantes geram aerossol e ferimentos.' },
    { t: 'Há exposição a agentes de transmissão sanguínea durante a atividade, risco que cessa com o óbito do paciente.', ok: false,
      why: 'Errada. Diversos agentes permanecem viáveis por período variável após a morte.' },
    { t: 'Há exposição a agentes de transmissão sanguínea, não se aplicando as precauções padrão a atividades funerárias.', ok: false,
      why: 'Errada. Aplicam-se integralmente: o estado infeccioso frequentemente é desconhecido.' },
    { t: 'Há exposição a agentes de transmissão sanguínea, e o acidente com material biológico não segue o protocolo usual.', ok: false,
      why: 'Errada. A conduta pós-exposição segue a mesma lógica dos serviços de saúde.' },
    { t: 'Há exposição a agentes de transmissão sanguínea por perfurocortantes, não gerando os procedimentos com serra aerossol.', ok: false,
      why: 'Errada. São procedimentos reconhecidamente geradores de partículas e aerossóis.' }
  ],
  comentario: 'Atividade funerária e necropsia são serviços de saúde para efeito de risco biológico: precauções padrão, proteção contra perfurocortante e aerossol, e o mesmo protocolo de acidente com material biológico.',
  pegadinha: 'A ideia de que o risco cessa com o óbito é intuitiva e falsa para vários agentes.',
  refs: ['NR-32', 'Classificação de Risco dos Agentes Biológicos — Ministério da Saúde'] }

);
