/* Lote AH — 4.4, 4.5, 4.6, 4.8, 5.4, 5.5, 1.3, 4.10, 6.2, 6.3. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-4.4-110', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a acne ocupacional e a cloracne, é CORRETO afirmar:',
  alts: [
    { t: 'A acne por óleos melhora com higiene e troca de roupa; a cloracne marca exposição sistêmica significativa.', ok: true,
      why: 'Correta. Cloracne não é apenas dermatose: sinaliza absorção sistêmica e tem curso arrastado.' },
    { t: 'A acne por óleos afeta áreas de contato e a cloracne tem o mesmo significado clínico e prognóstico que ela.', ok: false,
      why: 'Errada. A cloracne indica exposição sistêmica e tem curso bem mais prolongado.' },
    { t: 'A acne por óleos melhora com higiene, e a cloracne regride rapidamente com o afastamento da exposição.', ok: false,
      why: 'Errada. Costuma persistir por longo período após o afastamento.' },
    { t: 'A cloracne marca exposição sistêmica, e a acne por óleos não guarda relação com o vestuário de trabalho.', ok: false,
      why: 'Errada. Roupas impregnadas mantêm o contato e perpetuam o quadro.' },
    { t: 'A cloracne é dermatose de contato local, cuja presença dispensa investigar outros efeitos sistêmicos.', ok: false,
      why: 'Errada. Deve motivar investigação ampliada, por indicar absorção significativa.' }
  ],
  comentario: 'Acne por óleos é local e melhora com higiene e troca de roupa. Cloracne é outra coisa: marca exposição sistêmica a hidrocarbonetos halogenados, persiste após o afastamento e exige investigar outros órgãos.',
  pegadinha: 'Tratar cloracne como problema dermatológico isolado perde o alerta de absorção sistêmica que ela representa.',
  refs: ['Salim — Dermatoses Ocupacionais', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-4.5-100', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a interpretação de audiometrias sequenciais em programa de conservação auditiva, é CORRETO afirmar:',
  alts: [
    { t: 'A piora frente à referência exige confirmação com repouso, avaliação otorrino e revisão da proteção.', ok: true,
      why: 'Correta. O desencadeamento identificado deve gerar ação, não apenas anotação.' },
    { t: 'A piora frente à referência deve ser registrada e reavaliada apenas no próximo exame periódico anual.', ok: false,
      why: 'Errada. Exige confirmação e ação imediata sobre exposição e proteção.' },
    { t: 'A piora frente à referência confirma o desencadeamento da perda já em uma única audiometria alterada.', ok: false,
      why: 'Errada. É necessária confirmação com repouso auditivo adequado.' },
    { t: 'A piora exige confirmação e avaliação otorrinolaringológica, ficando a revisão da proteção fora da conduta.', ok: false,
      why: 'Errada. É componente central da resposta ao achado.' },
    { t: 'A piora deve ser aferida contra a audiometria imediatamente anterior, e não contra a de referência.', ok: false,
      why: 'Errada. A comparação com a referência é o que revela a tendência acumulada.' }
  ],
  comentario: 'Piora em relação à referência: confirma-se com repouso, avalia-se o ouvido e revisa-se exposição e proteção — no mesmo mês, não no próximo ciclo anual. Comparar só com o exame anterior esconde a tendência.',
  pegadinha: 'Registrar a piora e aguardar o próximo periódico desperdiça o único sinal precoce que o programa produz.',
  refs: ['NR-7 — Anexo I', 'Diretrizes de audiologia ocupacional'] },

{ id: 'q-4.6-100', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a avaliação de riscos psicossociais no âmbito do gerenciamento de riscos ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'Deve identificar demandas, autonomia, papel, suporte e reconhecimento, preservado o anonimato das respostas.', ok: true,
      why: 'Correta. Sem anonimato, o instrumento mede o medo de responder.' },
    { t: 'Deve aplicar questionários de estresse individual, que traduzem o estado psíquico de cada trabalhador avaliado.', ok: false,
      why: 'Errada. O objeto são as condições organizacionais, não o estado psíquico individual.' },
    { t: 'Deve identificar demandas, autonomia e suporte, melhorando a identificação nominal a qualidade dos dados.', ok: false,
      why: 'Errada. Inibe respostas e subestima os problemas relatados.' },
    { t: 'Deve identificar demandas e suporte, dispensando plano de ação quando não há afastamentos registrados.', ok: false,
      why: 'Errada. O objetivo é agir antes que o adoecimento apareça nos afastamentos.' },
    { t: 'Deve identificar demandas e autonomia, fatores que não podem ser objeto de medidas de controle organizacionais.', ok: false,
      why: 'Errada. Redesenho de metas, pausas, clareza de papel e suporte são medidas de controle.' }
  ],
  comentario: 'Avaliar psicossocial é avaliar a organização — demandas, autonomia, papel, suporte, reconhecimento — com anonimato garantido. E resultado ruim gera plano de ação antes de aparecer afastamento.',
  pegadinha: 'Aplicar questionário identificado mede a disposição de responder, não a condição de trabalho.',
  refs: ['NR-1 — fatores psicossociais', 'OIT', 'Karasek & Theorell'] },

{ id: 'q-4.8-100', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a exposição ocupacional à radiação solar e o risco de câncer de pele, é CORRETO afirmar:',
  alts: [
    { t: 'A radiação solar é cancerígena reconhecida, e quem trabalha a céu aberto acumula dose muito maior que a população', ok: true,
      why: 'Correta. Sol é agente ocupacional, com hierarquia de controle aplicável como a qualquer outro.' },
    { t: 'A exposição solar ocupacional é condição ambiental inevitável, não considerada exposição a agente cancerígeno.', ok: false,
      why: 'Errada. A radiação solar tem classificação de cancerígeno para humanos.' },
    { t: 'A radiação solar é cancerígena, sendo a dose de quem trabalha a céu aberto semelhante à da população geral.', ok: false,
      why: 'Errada. É substancialmente maior pela duração diária e pelos anos de atividade.' },
    { t: 'A radiação solar é cancerígena, resumindo-se a prevenção à orientação individual sobre uso de protetor solar.', ok: false,
      why: 'Errada. Sombreamento e organização das tarefas por horário vêm antes.' },
    { t: 'A radiação solar é cancerígena e a dose ocupacional é maior, sem indicação de vigilância dermatológica.', ok: false,
      why: 'Errada. O exame de pele periódico nesses grupos tem indicação clara.' }
  ],
  comentario: 'Sol é agente cancerígeno ocupacional para quem trabalha a céu aberto — com dose muito acima da população geral. Aplica-se hierarquia de controle: sombra e horário antes do protetor, com vigilância dermatológica.',
  pegadinha: 'Não reconhecer o sol como agente ocupacional deixa milhões de trabalhadores fora de qualquer programa.',
  refs: ['IARC — radiação solar', 'INCA', 'NR-21'] },

{ id: 'q-5.4-110', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a perícia em pedido de auxílio-acidente por sequela auditiva, é CORRETO afirmar:',
  alts: [
    { t: 'Deve verificar a consolidação, o grau e a redução da capacidade, pois as agudas comprometem a comunicação', ok: true,
      why: 'Correta. A média tonal esconde o prejuízo de discriminação nas frequências agudas.' },
    { t: 'Deve verificar a consolidação e o grau, descrevendo a média tonal isolada a repercussão funcional da perda.', ok: false,
      why: 'Errada. Pode estar pouco alterada com prejuízo relevante de discriminação.' },
    { t: 'Deve verificar a consolidação da perda, gerando qualquer perda auditiva ocupacional direito ao benefício.', ok: false,
      why: 'Errada. É preciso demonstrar redução da capacidade para o trabalho habitual.' },
    { t: 'Deve verificar a consolidação, não gerando a perda auditiva auxílio-acidente por não impedir o trabalho.', ok: false,
      why: 'Errada. O benefício se destina justamente à redução de capacidade, não à incapacidade.' },
    { t: 'Deve verificar consolidação e grau, dispensada a análise das exigências comunicativas da função exercida.', ok: false,
      why: 'Errada. É o que determina a repercussão concreta da perda.' }
  ],
  comentario: 'Sequela auditiva e auxílio-acidente: consolidação, grau e redução da capacidade para o trabalho habitual — analisada contra as exigências comunicativas da função. Média tonal normal não afasta prejuízo de discriminação.',
  pegadinha: 'Concluir pela média tonal despreza justamente a faixa em que a perda por ruído se instala.',
  refs: ['Lei nº 8.213/1991 — art. 86', 'Diretrizes de audiologia ocupacional'] },

{ id: 'q-5.5-100', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a avaliação de capacidade em trabalhadores com dor crônica musculoesquelética, é CORRETO afirmar:',
  alts: [
    { t: 'O desempenho varia ao longo do dia, exigindo avaliar a sustentabilidade da atividade na jornada.', ok: true,
      why: 'Correta. Conseguir executar o gesto uma vez não é o mesmo que sustentar por oito horas.' },
    { t: 'O desempenho observado no exame demonstra aptidão para a jornada completa quando o movimento é executado.', ok: false,
      why: 'Errada. Repetição e sustentação ao longo do turno é o que determina a viabilidade.' },
    { t: 'O desempenho varia ao longo do dia e entre dias, indicando essa variabilidade inconsistência do relato.', ok: false,
      why: 'Errada. É característica esperada em quadros de dor crônica.' },
    { t: 'O desempenho varia ao longo do dia, mas exames de imagem normais afastam a limitação funcional relatada.', ok: false,
      why: 'Errada. A correlação entre achados de imagem e dor crônica é fraca.' },
    { t: 'O desempenho varia ao longo do dia, sem que condicionamento e descondicionamento influam na capacidade.', ok: false,
      why: 'Errada. O descondicionamento pelo afastamento prolongado é fator relevante e reversível.' }
  ],
  comentario: 'Dor crônica: o que importa é sustentar a atividade na jornada, não executar o gesto uma vez na sala. Variabilidade é característica do quadro, não sinal de inconsistência — e descondicionamento por afastamento é reversível.',
  pegadinha: 'Interpretar a variação de desempenho como incoerência transforma característica clínica em suspeita.',
  refs: ['CIF — OMS', 'Diretrizes de dor crônica e trabalho'] },

{ id: 'q-1.3-100', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a interpretação de estudos que não encontram associação entre exposição ocupacional e desfecho, é CORRETO afirmar:',
  alts: [
    { t: 'É preciso avaliar o poder, a qualidade da exposição medida e o seguimento frente à latência esperada', ok: true,
      why: 'Correta. Não achar não é o mesmo que não existir.' },
    { t: 'O resultado negativo obtido em estudo bem conduzido demonstra a ausência de risco associado ao agente.', ok: false,
      why: 'Errada. Pode refletir limitações do próprio estudo.' },
    { t: 'É preciso avaliar o poder do estudo, não influenciando o seguimento a detecção de desfechos de longa latência.', ok: false,
      why: 'Errada. Seguimento inferior à latência não permite observar o desfecho.' },
    { t: 'É preciso avaliar a exposição, pois a classificação errônea não diferencial tende a inflar a associação.', ok: false,
      why: 'Errada. Tende a aproximar a estimativa do valor nulo.' },
    { t: 'É preciso avaliar poder e seguimento, não devendo estudos negativos ser considerados em revisões sistemáticas.', ok: false,
      why: 'Errada. Devem ser incluídos, e sua exclusão produz viés de publicação.' }
  ],
  comentario: 'Estudo negativo pede três perguntas: tinha poder? mediu bem a exposição? seguiu tempo suficiente para a latência? Classificação errônea não diferencial dilui em direção ao nulo — e é o que mais produz falso negativo em estudo ocupacional.',
  pegadinha: 'Usar estudo negativo pequeno como prova de segurança é o argumento mais frequente contra o reconhecimento de risco.',
  refs: ['Rothman — Epidemiologia Moderna', 'Checkoway'] },

{ id: 'q-4.10-090', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vacinação de trabalhadores expostos a risco de exposição a agentes de zoonoses, é CORRETO afirmar:',
  alts: [
    { t: 'É indicada aos grupos com exposição continuada a animais, sem dispensar a conduta pós-exposição', ok: true,
      why: 'Correta. A pré-exposição simplifica a conduta posterior, mas não a elimina.' },
    { t: 'É indicada a grupos com exposição continuada a animais e elimina a necessidade de conduta após acidente.', ok: false,
      why: 'Errada. A conduta pós-exposição permanece, ainda que simplificada.' },
    { t: 'Não há indicação de profilaxia pré-exposição por motivo ocupacional, apenas após contato de risco confirmado.', ok: false,
      why: 'Errada. Veterinários, tratadores e trabalhadores de laboratório têm indicação.' },
    { t: 'É indicada a grupos com exposição continuada, não tendo a verificação sorológica periódica papel nesse grupo.', ok: false,
      why: 'Errada. É indicada conforme o nível de risco da atividade.' },
    { t: 'É indicada em geral, não requerendo os trabalhadores de zoonoses esquema além do calendário comum.', ok: false,
      why: 'Errada. O risco ocupacional define indicações vacinais adicionais.' }
  ],
  comentario: 'Pré-exposição antirrábica é indicada por risco ocupacional continuado, com sorologia periódica conforme o risco — e não dispensa a conduta pós-exposição, apenas a simplifica.',
  pegadinha: 'Supor que a pré-exposição encerra o assunto leva a não conduzir o acidente adequadamente.',
  refs: ['Programa Nacional de Imunizações', 'Ministério da Saúde — profilaxia da raiva'] },

{ id: 'q-6.2-100', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o laudo caracterizador de deficiência para fins de enquadramento, é CORRETO afirmar:',
  alts: [
    { t: 'Deve descrever o impedimento e sua repercussão segundo os critérios normativos, sem restringir alocação.', ok: true,
      why: 'Correta. O laudo caracteriza para inclusão; não é ferramenta de limitação de carreira.' },
    { t: 'Deve descrever o impedimento e indicar as funções que o trabalhador não pode exercer dentro da empresa.', ok: false,
      why: 'Errada. Restrições funcionais, se existirem, são objeto de outro documento e outra avaliação.' },
    { t: 'Deve descrever o impedimento, dependendo a caracterização exclusivamente do diagnóstico clínico registrado.', ok: false,
      why: 'Errada. Depende dos critérios normativos de impedimento e da avaliação funcional.' },
    { t: 'Deve descrever o impedimento, podendo ser emitido sem exame, com base nos documentos apresentados.', ok: false,
      why: 'Errada. A avaliação presencial é necessária para caracterizar a repercussão.' },
    { t: 'Deve descrever o impedimento, implicando a caracterização presunção de menor capacidade produtiva.', ok: false,
      why: 'Errada. É justamente a presunção que a legislação de inclusão combate.' }
  ],
  comentario: 'O laudo caracteriza o impedimento segundo critério normativo, com avaliação presencial — e serve à inclusão. Restrição funcional, se houver, é outro documento; e caracterizar não presume menor produtividade.',
  pegadinha: 'Usar o laudo caracterizador para listar o que o trabalhador não pode fazer converte instrumento de inclusão em barreira.',
  refs: ['Lei nº 13.146/2015', 'Lei nº 8.213/1991 — art. 93'] },

{ id: 'q-6.3-100', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre os distúrbios do sono e a sonolência ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A apneia não tratada eleva o risco de acidentes, sendo o tratamento efetivo, e não o afastamento, a resposta', ok: true,
      why: 'Correta. Tratada e com adesão demonstrada, a condição deixa de ser impedimento.' },
    { t: 'A apneia eleva o risco de acidentes, implicando seu diagnóstico inaptidão definitiva para condução profissional.', ok: false,
      why: 'Errada. Tratamento eficaz com adesão comprovada permite o exercício da função.' },
    { t: 'A apneia eleva o risco, sendo a sonolência diurna relatada queixa subjetiva sem valor na avaliação.', ok: false,
      why: 'Errada. É um dos preditores mais relevantes de risco de acidente.' },
    { t: 'A apneia não tratada eleva o risco de acidentes, sem que a obesidade se relacione ao risco de apneia.', ok: false,
      why: 'Errada. É um dos principais fatores de risco para a apneia obstrutiva.' },
    { t: 'A apneia tratada permite o exercício da função, sem necessidade de verificar a adesão nas reavaliações.', ok: false,
      why: 'Errada. A adesão é justamente o que sustenta a manutenção da aptidão.' }
  ],
  comentario: 'Apneia não tratada aumenta acidente; apneia tratada com adesão verificada não impede a função. A resposta é diagnosticar e tratar — e reavaliar a adesão, que é o que sustenta a aptidão.',
  pegadinha: 'Inabilitar definitivamente pelo diagnóstico desestimula o trabalhador a relatar os sintomas.',
  refs: ['Diretrizes de distúrbios do sono', 'Resoluções sobre exame de motorista profissional', 'NR-7'] }

);
