/* Lote D — seção 1 (1.1, 1.2, 1.4, 1.5, 1.6, 1.7, 1.9, 1.10). AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.1-039', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa de grau de risco elevado com 900 empregados pergunta ao médico do trabalho qual a diferença entre contratar um serviço externo de medicina ocupacional e constituir serviço especializado próprio. A orientação CORRETA é:',
  alts: [
    { t: 'É obrigação dimensionada por grau de risco e número de empregados, com profissionais dedicados.', ok: true,
      why: 'Correta. Contratar clínica para exames não substitui a estrutura exigida.' },
    { t: 'É obrigação da empresa, integralmente substituída pela contratação de clínica externa especializada.', ok: false,
      why: 'Errada. A clínica realiza exames; não substitui o serviço especializado.' },
    { t: 'É estrutura recomendada e facultativa, qualquer que seja o porte ou o grau de risco da empresa.', ok: false,
      why: 'Errada. É obrigação dimensionada por grau de risco e número de empregados.' },
    { t: 'É obrigação dimensionada, podendo seus profissionais acumular outras funções sem restrição.', ok: false,
      why: 'Errada. Devem se dedicar às atividades de segurança e saúde.' },
    { t: 'É obrigação dimensionada, respondendo o médico do trabalho hierarquicamente ao setor de produção.', ok: false,
      why: 'Errada. A subordinação técnica ao setor de produção compromete a autonomia.' }
  ],
  comentario: 'Executar exames não é ter serviço especializado. A estrutura interna existe para atuar sobre o ambiente, com profissionais dedicados — e a autonomia técnica do médico não se subordina à produção.',
  pegadinha: 'Confundir contrato de clínica com cumprimento da obrigação de serviço especializado é o erro mais comum das empresas de médio porte.',
  refs: ['NR-4', 'Código de Ética Médica'] },

{ id: 'q-1.1-040', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o campo de atuação do médico do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Atua na prevenção, no controle dos agravos, na aptidão, na perícia e na gestão de programas.', ok: true,
      why: 'Correta. Sua função assistencial, quando existe, não se confunde com a de assistente.' },
    { t: 'Atua na avaliação de aptidão, com atividade restrita aos exames admissionais e demissionais.', ok: false,
      why: 'Errada. A atuação alcança prevenção, vigilância, perícia e gestão.' },
    { t: 'Atua em várias frentes e é o médico assistente de todos os empregados da empresa contratante.', ok: false,
      why: 'Errada. As funções são distintas e não se confundem.' },
    { t: 'Atua na prevenção e na aptidão, sendo vedada ao médico do trabalho a atuação em perícia.', ok: false,
      why: 'Errada. A perícia é campo próprio da especialidade.' },
    { t: 'Atua na prevenção e na aptidão, sendo a gestão de programas matéria alheia à especialidade.', ok: false,
      why: 'Errada. A coordenação de programas é atribuição do médico do trabalho.' }
  ],
  comentario: 'O campo é amplo — prevenção, reconhecimento, controle, aptidão, perícia e gestão — e a fronteira que precisa ficar clara é com a assistência longitudinal, que pertence ao médico assistente.',
  pegadinha: 'Reduzir a especialidade a admissional e demissional é a visão que a própria empresa costuma ter e que a prova cobra que você recuse.',
  refs: ['Resolução CFM sobre normas para médicos que atendem o trabalhador', 'Dias — Manual Prático da Medicina do Trabalho'] },

{ id: 'q-1.2-030', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um pesquisador afirma que a análise da saúde de entregadores de aplicativo exige considerar a informalidade, a ausência de vínculo formal e a autonomia apenas aparente. Sobre essa abordagem, é CORRETO afirmar:',
  alts: [
    { t: 'É coerente com o campo, que toma o processo de trabalho como objeto e alcança toda inserção.', ok: true,
      why: 'Correta. Inclui as formas que escapam da proteção previdenciária e trabalhista clássica.' },
    { t: 'Trabalhadores sem vínculo formal ficam fora do campo da saúde do trabalhador, por falta de empregador.', ok: false,
      why: 'Errada. O campo alcança todas as formas de inserção no trabalho.' },
    { t: 'É coerente com o campo, eliminando a autonomia declarada a subordinação e, com ela, o risco.', ok: false,
      why: 'Errada. A exposição existe independentemente da forma do vínculo.' },
    { t: 'É coerente com o campo, sendo dispensável analisar o processo sem empregador identificado.', ok: false,
      why: 'Errada. O processo de trabalho é o objeto, com ou sem empregador.' },
    { t: 'É coerente com o campo, não se aplicando riscos psicossociais a trabalhadores sem vínculo formal.', ok: false,
      why: 'Errada. Insegurança e pressão por resultado os atingem intensamente.' }
  ],
  comentario: 'O campo se define pela relação com o TRABALHO, não pelo contrato. Formas novas de organização — plataformas, intermitência, informalidade — não estão fora dele; ao contrário, são onde a proteção clássica menos alcança.',
  pegadinha: 'A autonomia declarada nas plataformas é usada para afastar tanto o vínculo quanto o risco, e não afasta nenhum dos dois.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-1.2-031', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a determinação social do processo saúde-doença aplicada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Sustenta que o adoecimento se explica por determinantes sociais e pela organização do trabalho', ok: true,
      why: 'Correta. Não apenas por agentes isolados ou características individuais.' },
    { t: 'Sustenta os determinantes sociais, conceito incompatível com a análise de agentes de risco específicos.', ok: false,
      why: 'Errada. As duas abordagens se complementam.' },
    { t: 'Sustenta os determinantes sociais e nega a existência de suscetibilidade individual dos trabalhadores.', ok: false,
      why: 'Errada. Reconhece a suscetibilidade, sem reduzir o problema a ela.' },
    { t: 'Sustenta os determinantes sociais, que não são passíveis de intervenção pelo serviço ocupacional.', ok: false,
      why: 'Errada. Organização do trabalho e condições são intervenções possíveis.' },
    { t: 'Sustenta os determinantes sociais, perspectiva aplicável apenas às doenças de natureza infecciosa.', ok: false,
      why: 'Errada. É perspectiva geral do campo da saúde do trabalhador.' }
  ],
  comentario: 'Determinação social não substitui a toxicologia nem a higiene — soma-se a elas. É o que explica por que dois grupos com a mesma exposição química adoecem de forma diferente conforme jornada, ritmo e vínculo.',
  pegadinha: 'Opor determinação social e análise de agentes específicos cria um falso dilema entre duas ferramentas complementares.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.4-030', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa quer estimar o custo do adoecimento relacionado ao trabalho para justificar investimento em prevenção. Sobre a composição desse custo, é CORRETO afirmar:',
  alts: [
    { t: 'Combina diretos, como assistência e reposição, e indiretos, como presenteísmo e rotatividade.', ok: true,
      why: 'Correta. Inclui ainda o impacto sobre a alíquota de financiamento do benefício.' },
    { t: 'Resume-se aos dias de afastamento pagos pela empresa no período inicial de responsabilidade dela.', ok: false,
      why: 'Errada. Os custos indiretos costumam superar os diretos.' },
    { t: 'Combina diretos e indiretos, devendo estes ser desconsiderados por não serem estimáveis.', ok: false,
      why: 'Errada. Há métodos consolidados de estimativa.' },
    { t: 'Combina diretos e indiretos, sendo irrelevante o impacto sobre a alíquota de financiamento.', ok: false,
      why: 'Errada. A variação por acidentalidade tem impacto financeiro direto.' },
    { t: 'Combina diretos e indiretos, sendo o investimento em prevenção custo sem retorno mensurável.', ok: false,
      why: 'Errada. O retorno é mensurável e documentado.' }
  ],
  comentario: 'Diretos aparecem na folha; indiretos aparecem no resultado. Presenteísmo, retrabalho, rotatividade e a alíquota de financiamento acidentário costumam somar mais que os dias pagos — e são o argumento que convence a diretoria.',
  pegadinha: 'Descartar o custo indireto por ser difícil de medir é o que faz a prevenção parecer despesa.',
  refs: ['Zétola — Tratado de Gestão em Saúde do Trabalhador', 'Lei nº 8.213/1991'] },

{ id: 'q-1.5-040', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise crítica pela direção em um sistema de gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'É quando a alta direção avalia o desempenho do sistema e decide sobre recursos e mudanças', ok: true,
      why: 'Correta. É o que transforma o sistema em instrumento de decisão, não em documentação.' },
    { t: 'É atribuição do serviço especializado, que avalia o desempenho sem participação da alta direção.', ok: false,
      why: 'Errada. A análise crítica é da direção, e é onde se decidem recursos.' },
    { t: 'É etapa de verificação, limitada a conferir se os documentos do sistema estão atualizados.', ok: false,
      why: 'Errada. Avalia desempenho, resultados e cumprimento de objetivos.' },
    { t: 'É atribuição da direção, necessária apenas quando ocorre acidente grave no estabelecimento.', ok: false,
      why: 'Errada. É etapa periódica do ciclo de gestão.' },
    { t: 'É atribuição da direção, cujas decisões não precisam ser formalmente registradas em ata.', ok: false,
      why: 'Errada. O registro é o que permite acompanhar e cobrar as decisões.' }
  ],
  comentario: 'Análise crítica pela direção é onde o sistema vira decisão: recursos, mudança de processo, prioridade. Feita pelo serviço especializado sozinho, ela não tem poder de mudar nada — e é por isso que a norma a atribui à direção.',
  pegadinha: 'Delegar a análise crítica ao serviço técnico esvazia justamente o requisito de comprometimento da alta direção.',
  refs: ['OIT — Sistema de Gestão da SST', 'ISO 45001'] },

{ id: 'q-1.6-040', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a relação entre a política de saúde do trabalhador e a atenção primária à saúde, é CORRETO afirmar:',
  alts: [
    { t: 'É porta de entrada preferencial e território privilegiado para identificar a relação com o trabalho.', ok: true,
      why: 'Correta. Sua proximidade e o conhecimento das atividades locais explicam isso.' },
    { t: 'É porta de entrada geral, sendo a saúde do trabalhador matéria de serviços especializados.', ok: false,
      why: 'Errada. A atenção primária tem papel central na identificação e notificação.' },
    { t: 'É porta de entrada, devendo encaminhar todo caso suspeito sem qualquer registro local do atendimento.', ok: false,
      why: 'Errada. O registro e a notificação começam onde o caso é identificado.' },
    { t: 'É porta de entrada, não tendo as equipes de saúde da família papel na vigilância ocupacional.', ok: false,
      why: 'Errada. Conhecem o território e as atividades produtivas locais.' },
    { t: 'É porta de entrada, sendo a ocupação do paciente dado de interesse exclusivamente previdenciário.', ok: false,
      why: 'Errada. É dado clínico que orienta a suspeita diagnóstica.' }
  ],
  comentario: 'A atenção primária é onde a saúde do trabalhador acontece na prática, sobretudo para informais. Perguntar a ocupação, registrar e notificar são atos simples com enorme efeito sobre a visibilidade do problema.',
  pegadinha: 'Delegar tudo a serviços especializados deixa fora quem nunca chega a eles.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'Lei nº 8.080/1990'] },

{ id: 'q-1.7-040', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a participação social no sistema público de saúde aplicada à saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Conselhos e conferências de saúde são instâncias de controle social que alcançam o trabalhador', ok: true,
      why: 'Correta. A participação de trabalhadores e representações é diretriz do sistema.' },
    { t: 'O controle social não alcança a saúde do trabalhador, por envolver relações privadas de trabalho.', ok: false,
      why: 'Errada. É campo do sistema de saúde e sujeito ao controle social.' },
    { t: 'Conselhos existem, limitando-se a participação a consultas informais, sem instâncias formais previstas.', ok: false,
      why: 'Errada. Conselhos e conferências são instâncias formais.' },
    { t: 'Conselhos e conferências existem, não podendo representações sindicais participar dessas instâncias.', ok: false,
      why: 'Errada. A participação sindical é expressamente prevista.' },
    { t: 'Conselhos e conferências existem, substituindo o controle social a fiscalização técnica dos ambientes.', ok: false,
      why: 'Errada. São funções distintas e complementares.' }
  ],
  comentario: 'Controle social é diretriz do sistema e alcança a saúde do trabalhador. Ele não substitui a fiscalização técnica — soma-se a ela, e é o que dá voz a quem está exposto.',
  pegadinha: 'Alegar que relações de trabalho são "privadas" para afastar o controle social ignora que o objeto é a saúde, que é pública.',
  refs: ['Lei nº 8.080/1990', 'Lei nº 8.142/1990', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.9-040', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a notificação de acidente de trabalho grave, é CORRETO afirmar:',
  alts: [
    { t: 'Acidentes graves e fatais têm prazo diferenciado, pela necessidade de investigação oportuna', ok: true,
      why: 'Correta. A cena e as condições se alteram rapidamente após o evento.' },
    { t: 'Todos os agravos têm o mesmo prazo de notificação, independentemente da gravidade apresentada.', ok: false,
      why: 'Errada. Graves e fatais têm notificação imediata.' },
    { t: 'Graves e fatais têm prazo diferenciado, dispensando a notificação a investigação do ambiente.', ok: false,
      why: 'Errada. A notificação existe justamente para disparar a investigação.' },
    { t: 'Graves e fatais têm prazo diferenciado, sendo dispensável a notificação se a empresa já comunicou.', ok: false,
      why: 'Errada. São sistemas distintos e ambas as obrigações subsistem.' },
    { t: 'Graves e fatais têm prazo diferenciado, não sendo notificável o acidente com trabalhador informal.', ok: false,
      why: 'Errada. A notificação independe do vínculo.' }
  ],
  comentario: 'Acidente grave e fatal tem prazo curto por uma razão prática: se a investigação demora, a máquina é consertada, o setor é reorganizado e as evidências desaparecem. A pressa é metodológica.',
  pegadinha: 'Supor que a comunicação previdenciária dispensa a notificação sanitária confunde dois fluxos com finalidades diferentes.',
  refs: ['SINAN — Ministério da Saúde', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.10-040', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre programas de promoção da saúde no ambiente de trabalho e a proteção de dados dos participantes, é CORRETO afirmar:',
  alts: [
    { t: 'São dados sensíveis e não podem embasar decisões sobre vínculo, remuneração ou progressão.', ok: true,
      why: 'Correta. A adesão deve ser voluntária e não vinculada a benefícios contratuais.' },
    { t: 'Deixam de ser sensíveis quando coletados em programa voluntário, por haver consentimento prévio.', ok: false,
      why: 'Errada. A categoria do dado não muda com o consentimento.' },
    { t: 'São dados sensíveis, podendo a empresa usar os resultados para direcionar promoções e aumentos.', ok: false,
      why: 'Errada. É uso vedado e discriminatório.' },
    { t: 'São dados sensíveis, podendo a adesão ser obrigatória desde que o programa seja gratuito.', ok: false,
      why: 'Errada. Obrigatoriedade descaracteriza a adesão em programa de promoção.' },
    { t: 'São dados sensíveis, podendo os resultados individuais ser compartilhados com a chefia direta.', ok: false,
      why: 'Errada. Resultado individual é dado de saúde protegido por sigilo.' }
  ],
  comentario: 'Promoção da saúde e proteção de dados se encontram aqui: adesão voluntária, dado sensível, resultado agregado e proibição de uso para decisão contratual. Sem isso, o programa vira triagem disfarçada de cuidado.',
  pegadinha: 'O consentimento aparece de novo como salvo-conduto — e em relação de emprego ele é frágil e não legitima qualquer finalidade.',
  refs: ['LGPD — Lei nº 13.709/2018', 'OMS — Ambientes de trabalho saudáveis', 'Código de Ética Médica'] }

);
