/* Lote W — 6.2, 6.3, 6.4, 7.4, 7.2, 7.1. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-6.2-070', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a avaliação biopsicossocial da deficiência, é CORRETO afirmar:',
  alts: [
    { t: 'Considera impedimentos de longo prazo em interação com barreiras que obstruem a participação.', ok: true,
      why: 'Correta. A deficiência resulta dessa interação, o que desloca a resposta para remover barreiras.' },
    { t: 'Considera o grau de comprometimento anatômico ou funcional apresentado pela pessoa avaliada.', ok: false,
      why: 'Errada. A definição legal inclui a interação com barreiras.' },
    { t: 'Considera impedimentos de longo prazo, dispensando a avaliação biopsicossocial os fatores ambientais.', ok: false,
      why: 'Errada. As barreiras ambientais são elemento central da definição.' },
    { t: 'Considera impedimentos em interação com barreiras, inclusive os de caráter temporário.', ok: false,
      why: 'Errada. A definição se refere a impedimentos de longo prazo.' },
    { t: 'Considera impedimentos e barreiras, devendo a avaliação ser realizada exclusivamente por médico.', ok: false,
      why: 'Errada. A avaliação biopsicossocial é multiprofissional por definição.' }
  ],
  comentario: 'Deficiência é impedimento de longo prazo em interação com barreiras — não é medida só no corpo. Por isso a avaliação é multiprofissional e parte da resposta é remover barreira, não tratar pessoa.',
  pegadinha: 'Avaliar apenas o comprometimento corporal aplica um modelo que a lei brasileira já superou.',
  refs: ['Lei nº 13.146/2015 — art. 2º', 'CIF — OMS'] },

{ id: 'q-6.2-071', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o cumprimento da cota legal de pessoas com deficiência e reabilitados, é CORRETO afirmar:',
  alts: [
    { t: 'O percentual varia com o porte, e a dispensa exige contratar substituto em condição semelhante.', ok: true,
      why: 'Correta. A condição de substituição é o que dá efetividade à reserva.' },
    { t: 'O percentual da cota é único para empresas de qualquer porte que tenham empregados registrados.', ok: false,
      why: 'Errada. Varia por faixa de número de empregados.' },
    { t: 'O percentual varia conforme o porte, sem condição legal específica para a dispensa do enquadrado.', ok: false,
      why: 'Errada. Há condicionamento expresso à contratação de substituto.' },
    { t: 'O percentual varia com o porte, não contando os reabilitados pela previdência para a cota.', ok: false,
      why: 'Errada. A reserva legal alcança expressamente os reabilitados.' },
    { t: 'O percentual varia com o porte, podendo os contratados ser alocados todos na mesma função.', ok: false,
      why: 'Errada. Concentrar em funções desvalorizadas contraria a finalidade inclusiva.' }
  ],
  comentario: 'Cota: percentual por faixa de empregados, alcança reabilitados, e a dispensa por prazo indeterminado exige substituto em condição semelhante. Concentrar os contratados em uma função de menor valor cumpre o texto da norma e nega sua finalidade.',
  pegadinha: 'Esquecer que reabilitados contam para a cota é omissão frequente na leitura do dispositivo.',
  refs: ['Lei nº 8.213/1991 — art. 93', 'Lei nº 13.146/2015'] },

{ id: 'q-6.3-070', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Motorista profissional com diabetes em uso de insulina apresenta bom controle e nenhum episódio de hipoglicemia grave. Sobre a conduta, é CORRETO afirmar:',
  alts: [
    { t: 'Considera o controle, o histórico de hipoglicemias, a percepção dos sintomas e a adesão.', ok: true,
      why: 'Correta. O que decide é o risco de hipoglicemia incapacitante, não a via de tratamento.' },
    { t: 'Considera o tratamento adotado, implicando o uso de insulina inaptidão para condução profissional.', ok: false,
      why: 'Errada. A avaliação é individualizada e considera o controle e o histórico.' },
    { t: 'Considera o controle e o histórico, sem que a hipoglicemia assintomática altere a avaliação.', ok: false,
      why: 'Errada. A perda da percepção dos sintomas é o achado de maior risco.' },
    { t: 'Considera o controle glicêmico, cuja adequação dispensa reavaliações periódicas mais frequentes.', ok: false,
      why: 'Errada. A condição exige acompanhamento com periodicidade adequada ao risco.' },
    { t: 'Considera o controle e a adesão, podendo decidir sem informação sobre hipoglicemias prévias.', ok: false,
      why: 'Errada. O histórico de episódios é o dado mais relevante da avaliação.' }
  ],
  comentario: 'Insulina não decide aptidão; hipoglicemia decide. E o achado mais preocupante é a perda da percepção dos sintomas — quem não sente a hipoglicemia chegando não consegue parar o veículo a tempo.',
  pegadinha: 'Concluir pela via de tratamento em vez do risco funcional exclui trabalhadores bem controlados.',
  refs: ['Diretrizes de diabetes e direção veicular', 'NR-7', 'Resoluções sobre exame de motorista profissional'] },

{ id: 'q-6.3-071', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre os limites do rastreamento de doenças no exame ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Exames sem indicação ampliam achados incidentais e investigações sem benefício demonstrado.', ok: true,
      why: 'Correta. Ampliar a bateria não equivale a cuidar melhor do trabalhador.' },
    { t: 'Quanto mais exames o programa inclui, maior a proteção conferida ao trabalhador acompanhado.', ok: false,
      why: 'Errada. Exame sem indicação gera achado incidental e investigação sem benefício.' },
    { t: 'Exames sem indicação geram achados incidentais, sempre benéficos por permitirem diagnóstico precoce.', ok: false,
      why: 'Errada. Muitos levam a tratar condições que nunca causariam dano.' },
    { t: 'Exames devem ser indicados, seguindo o rastreamento populacional os mesmos critérios do ocupacional.', ok: false,
      why: 'Errada. São lógicas distintas: uma parte do risco populacional, a outra da exposição.' },
    { t: 'Exames devem ser indicados, sendo o custo o principal critério para incluí-los no programa.', ok: false,
      why: 'Errada. O critério é a indicação técnica frente ao risco e a evidência de benefício.' }
  ],
  comentario: 'Check-up ampliado não é cuidado ampliado: produz achado incidental, ansiedade e cascata de investigação. A indicação vem do risco da função e da evidência de benefício — não do desejo de parecer completo.',
  pegadinha: 'A bateria extensa é vendida como benefício e frequentemente é sobrediagnóstico com aparência de zelo.',
  refs: ['NR-7', 'Critérios de rastreamento — literatura de medicina preventiva'] },

{ id: 'q-6.4-070', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a queimadura química ocular no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A irrigação abundante e imediata é a medida de maior impacto e começa antes do transporte.', ok: true,
      why: 'Correta. Álcalis penetram progressivamente e tendem a ser mais graves que ácidos.' },
    { t: 'A irrigação é importante, devendo aguardar-se a avaliação especializada antes de iniciá-la.', ok: false,
      why: 'Errada. O atraso é o que determina a gravidade da lesão final.' },
    { t: 'A irrigação é imediata, sendo as queimaduras por ácidos sistematicamente mais graves que as por álcalis.', ok: false,
      why: 'Errada. Os álcalis penetram progressivamente e produzem lesão mais profunda.' },
    { t: 'A irrigação é imediata, sendo a neutralização com substância de pH oposto a conduta indicada.', ok: false,
      why: 'Errada. A reação de neutralização libera calor e agrava a lesão.' },
    { t: 'A irrigação é imediata, indicando a ausência de dor intensa lesão de menor gravidade.', ok: false,
      why: 'Errada. Lesões graves cursam com pouca dor por destruição de terminações nervosas.' }
  ],
  comentario: 'Olho com respingo químico: irrigar já, no local, em abundância. Álcali é pior que ácido pela penetração progressiva. Nada de neutralizar — a reação libera calor. E pouca dor pode significar lesão profunda, não lesão leve.',
  pegadinha: 'Tentar neutralizar quimicamente parece técnico e agrava a queimadura.',
  refs: ['Protocolos de queimadura química ocular', 'NR-1'] },

{ id: 'q-6.4-071', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso do desfibrilador externo automático em emergências cardiovasculares no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A eficácia depende do tempo até o choque, o que justifica proximidade e treinamento de leigos.', ok: true,
      why: 'Correta. O aparelho analisa o ritmo e só libera choque quando indicado.' },
    { t: 'A eficácia depende do tempo, podendo o equipamento ser operado apenas por profissional de saúde.', ok: false,
      why: 'Errada. É projetado para uso por leigos treinados.' },
    { t: 'A eficácia depende do tempo, devendo o choque ser aplicado independentemente da análise do ritmo.', ok: false,
      why: 'Errada. O aparelho analisa e só libera quando o ritmo é passível de choque.' },
    { t: 'A eficácia depende do tempo, devendo as compressões parar enquanto se busca o equipamento.', ok: false,
      why: 'Errada. As compressões continuam até o momento da análise do ritmo.' },
    { t: 'A eficácia depende do tempo, dispensando sua disponibilidade o acionamento do serviço de emergência.', ok: false,
      why: 'Errada. O acionamento é simultâneo e indispensável.' }
  ],
  comentario: 'Desfibrilador: tempo até o choque é tudo, por isso disponibilidade próxima e leigos treinados. Compressões não param enquanto o aparelho é buscado, e o acionamento da emergência é simultâneo.',
  pegadinha: 'Reservar o equipamento a profissionais de saúde anula a razão de ele existir em ambiente de trabalho.',
  refs: ['Diretrizes de suporte básico de vida', 'NR-1'] },

{ id: 'q-7.4-070', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o trabalho em espaços confinados, é CORRETO afirmar:',
  alts: [
    { t: 'Exige permissão, avaliação contínua da atmosfera, vigia externo e equipe de resgate preparada.', ok: true,
      why: 'Correta. A maioria das mortes decorre de tentativas de resgate improvisadas.' },
    { t: 'Exige permissão e avaliação inicial da atmosfera, suficiente para toda a permanência no espaço.', ok: false,
      why: 'Errada. As condições mudam durante o trabalho e exigem monitoramento contínuo.' },
    { t: 'Exige permissão e avaliação contínua, sendo o vigia externo recomendação e não requisito.', ok: false,
      why: 'Errada. É requisito da permissão de entrada e trabalho.' },
    { t: 'Exige permissão e avaliação, sendo adequado o respirador com filtro havendo dúvida sobre a atmosfera.', ok: false,
      why: 'Errada. Diante de dúvida, exige-se ar fornecido ou equipamento autônomo.' },
    { t: 'Exige permissão e capacitação, que é única e não requer reciclagem periódica posterior.', ok: false,
      why: 'Errada. Há previsão de capacitação periódica.' }
  ],
  comentario: 'Espaço confinado: permissão específica, atmosfera avaliada antes e durante, vigia externo permanente, resgate preparado e capacitação periódica. A causa mais comum de múltiplas mortes é o resgate improvisado.',
  pegadinha: 'Medir a atmosfera só na entrada ignora que ela muda com o próprio trabalho executado dentro.',
  refs: ['NR-33'] },

{ id: 'q-7.4-071', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a segurança em instalações e serviços em eletricidade, é CORRETO afirmar:',
  alts: [
    { t: 'A regra é desenergizar com bloqueio e sinalização, verificando a ausência de tensão antes.', ok: true,
      why: 'Correta. Trabalho energizado é exceção, com justificativa e controles específicos.' },
    { t: 'A regra é o trabalho em instalações energizadas quando a equipe é treinada e certificada.', ok: false,
      why: 'Errada. É exceção, condicionada a justificativa técnica e controles adicionais.' },
    { t: 'A regra é desenergizar, podendo bloqueio e sinalização ser dispensados em intervenções rápidas.', ok: false,
      why: 'Errada. A brevidade não dispensa o procedimento; é onde ocorrem acidentes graves.' },
    { t: 'A regra é desenergizar, dispensada a verificação de ausência de tensão após abrir o disjuntor.', ok: false,
      why: 'Errada. A verificação é etapa obrigatória e independente do desligamento.' },
    { t: 'A regra é desenergizar com bloqueio, não exigindo o risco de arco elétrico medidas específicas.', ok: false,
      why: 'Errada. Exige vestimenta adequada e análise específica desse risco.' }
  ],
  comentario: 'Eletricidade: desenergizar, bloquear, sinalizar e verificar ausência de tensão — nessa ordem e sem atalho por brevidade. Energizado é exceção justificada, e arco elétrico tem proteção própria.',
  pegadinha: 'A intervenção rápida sem bloqueio é a situação em que a religação por terceiro mata.',
  refs: ['NR-10'] },

{ id: 'q-7.2-070', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a ação regressiva acidentária, é CORRETO afirmar:',
  alts: [
    { t: 'Permite cobrar do empregador os valores dos benefícios quando há negligência quanto às normas.', ok: true,
      why: 'Correta. É a via pela qual o custo do benefício volta a quem descumpriu a norma.' },
    { t: 'Permite cobrar do empregador, impedindo a concessão do benefício qualquer cobrança posterior a ele.', ok: false,
      why: 'Errada. A ação regressiva existe justamente para essa cobrança.' },
    { t: 'Permite cobrar do empregador, independentemente de demonstrar descumprimento de normas de segurança.', ok: false,
      why: 'Errada. A negligência quanto às normas é seu fundamento.' },
    { t: 'Permite cobrar do empregador os valores despendidos, sendo proposta pelo trabalhador acidentado.', ok: false,
      why: 'Errada. É proposta pela autarquia previdenciária.' },
    { t: 'Permite cobrar do empregador, sendo os valores obtidos destinados ao trabalhador acidentado.', ok: false,
      why: 'Errada. Ressarcem os cofres da previdência, sem prejuízo da ação indenizatória.' }
  ],
  comentario: 'Ação regressiva: a previdência cobra do empregador negligente o que gastou com o benefício. Não substitui a indenização civil do trabalhador — e a documentação das medidas de segurança é o que a empresa tem para se defender.',
  pegadinha: 'Confundir a ação regressiva com a indenização do trabalhador troca autor, fundamento e destinatário.',
  refs: ['Lei nº 8.213/1991 — art. 120', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.1-060', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o adicional de insalubridade e o adicional de periculosidade, é CORRETO afirmar:',
  alts: [
    { t: 'São verbas distintas e não cumuláveis, cabendo ao trabalhador optar pela mais favorável.', ok: true,
      why: 'Correta. E a eliminação ou neutralização do agente cessa o direito ao adicional.' },
    { t: 'São verbas distintas e cumuláveis entre si quando presentes as duas condições no mesmo posto.', ok: false,
      why: 'Errada. A regra é a não cumulação, com opção pelo mais favorável.' },
    { t: 'São verbas distintas, sendo o adicional de insalubridade permanente após concedido ao trabalhador.', ok: false,
      why: 'Errada. Cessada a condição, cessa o adicional.' },
    { t: 'São verbas distintas e não cumuláveis, tendo ambas a mesma base de cálculo prevista em lei.', ok: false,
      why: 'Errada. As bases de cálculo são distintas.' },
    { t: 'São verbas distintas, eximindo o pagamento do adicional a empresa de controlar o agente.', ok: false,
      why: 'Errada. O dever de eliminar ou neutralizar o risco independe do pagamento.' }
  ],
  comentario: 'Insalubridade e periculosidade: fundamentos e bases distintos, não cumuláveis, com opção pelo mais favorável, e o adicional cessa quando a condição é eliminada. Pagar adicional nunca substitui controlar o risco.',
  pegadinha: 'Tratar o adicional como preço da exposição inverte a lógica: ele é compensação temporária, não licença para manter o risco.',
  refs: ['CLT — arts. 189 a 197', 'NR-15', 'NR-16'] }

);
