/* Lote I — temas de peso médio da Seção 1 e correlatos. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-020', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de saúde ocupacional apresenta à diretoria indicadores de absenteísmo por doença, mas não consegue explicar por que o indicador subiu. Sobre o uso de indicadores em gestão de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Indicador isolado descreve mas não explica: é preciso estratificar por setor, função, causa e tempo, e cruzar com dados de exposição e de organização do trabalho, para que o número indique onde intervir.', ok: true,
      why: 'Correta. Sem estratificação, o indicador vira placar e não instrumento de gestão.' },
    { t: 'A elevação do absenteísmo indica sempre piora das condições de trabalho.', ok: false,
      why: 'Errada. Pode refletir mudança de perfil, campanha de detecção, sazonalidade ou alteração de critérios de registro.' },
    { t: 'A queda do absenteísmo é sempre resultado desejável.', ok: false,
      why: 'Errada. Pode indicar presenteísmo — trabalhador doente que não se afasta por medo ou pressão.' },
    { t: 'Indicadores de saúde não devem ser apresentados à direção por conterem dados clínicos.', ok: false,
      why: 'Errada. Apresenta-se o agregado, sem identificação individual; é isso que sustenta decisão de gestão.' },
    { t: 'A meta de redução do indicador deve ser fixada antes de conhecer sua composição.', ok: false,
      why: 'Errada. Meta sobre indicador não compreendido induz manipulação do registro em vez de melhoria real.' }
  ],
  comentario: 'Indicador só vira gestão depois de estratificado e cruzado com exposição e organização do trabalho. E atenção ao efeito espelho: queda do absenteísmo pode ser presenteísmo, e meta sobre número não compreendido tende a produzir subnotificação.',
  pegadinha: 'Ler queda de absenteísmo como sucesso é o erro de leitura mais frequente em relatório gerencial.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'ILO/OIT — gestão em SST'] },

{ id: 'q-1.4-021', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o dimensionamento e a atuação do serviço especializado em segurança e medicina do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O dimensionamento segue o grau de risco da atividade e o número de trabalhadores do estabelecimento, e a atuação da equipe é multiprofissional e integrada, não uma soma de atendimentos isolados.', ok: true,
      why: 'Correta. Grau de risco e número de trabalhadores definem a composição; a integração define a eficácia.' },
    { t: 'O dimensionamento depende apenas do número de trabalhadores.', ok: false,
      why: 'Errada. O grau de risco da atividade econômica é o outro eixo.' },
    { t: 'A empresa pode substituir integralmente a equipe por serviço externo sem qualquer condição.', ok: false,
      why: 'Errada. Há requisitos definidos para as formas alternativas de organização do serviço.' },
    { t: 'A atuação do médico do trabalho se limita à realização dos exames ocupacionais.', ok: false,
      why: 'Errada. Ele participa do reconhecimento dos riscos, do programa de controle e das ações de vigilância.' },
    { t: 'O serviço responde à área de recursos humanos em suas decisões técnicas.', ok: false,
      why: 'Errada. Decisão técnica de saúde e segurança não é subordinada a conveniência administrativa.' }
  ],
  comentario: 'Dois eixos no dimensionamento: grau de risco e número de trabalhadores. E o ponto conceitual: o serviço é multiprofissional e integrado, com autonomia técnica — o médico do trabalho não é apenas quem assina exame.',
  pegadinha: 'Reduzir o médico do trabalho ao exame ocupacional é a distorção que a prova cobra com frequência.',
  refs: ['NR-4', 'NR-1'] },

{ id: 'q-1.6-020', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a Política Nacional de Saúde do Trabalhador e da Trabalhadora, é CORRETO afirmar:',
  alts: [
    { t: 'Ela abrange todos os trabalhadores, independentemente do vínculo formal, inclusive informais, autônomos e do trabalho doméstico — princípio que a distingue da lógica securitária, restrita ao segurado contribuinte.', ok: true,
      why: 'Correta. A universalidade da cobertura é o traço que separa a política de saúde da lógica previdenciária.' },
    { t: 'Ela se aplica apenas aos trabalhadores com vínculo formal registrado.', ok: false,
      why: 'Errada. A universalidade é justamente o seu princípio estruturante.' },
    { t: 'Ela substitui as normas regulamentadoras de segurança e saúde.', ok: false,
      why: 'Errada. São instrumentos de campos distintos que coexistem.' },
    { t: 'Sua execução é atribuição exclusiva do nível federal.', ok: false,
      why: 'Errada. É descentralizada, com atribuições nas três esferas de gestão.' },
    { t: 'Ela dispensa a participação dos trabalhadores em sua formulação e controle.', ok: false,
      why: 'Errada. O controle social é princípio expresso.' }
  ],
  comentario: 'Universalidade é a chave: a política de saúde do trabalhador alcança o informal, o autônomo, a doméstica — quem a lógica securitária deixa de fora. Descentralizada nas três esferas e com controle social.',
  pegadinha: 'Restringir a política ao trabalhador formal reproduz exatamente o recorte que ela veio corrigir.',
  refs: ['Portaria GM/MS nº 1.823/2012 — PNSTT', 'Lei nº 8.080/1990'] },

{ id: 'q-1.6-021', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os Centros de Referência em Saúde do Trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'São unidades de retaguarda técnica da rede, com funções de apoio matricial, investigação de agravos, capacitação e vigilância — e não porta de entrada substitutiva da atenção básica para o trabalhador.', ok: true,
      why: 'Correta. Retaguarda e matriciamento, não ambulatório paralelo.' },
    { t: 'Sua função principal é o atendimento clínico individual de todos os trabalhadores da região.', ok: false,
      why: 'Errada. O atendimento existe, mas a função estruturante é de retaguarda e vigilância.' },
    { t: 'Eles emitem benefícios previdenciários por doença ocupacional.', ok: false,
      why: 'Errada. A concessão de benefício é competência da perícia do órgão previdenciário.' },
    { t: 'Sua atuação independe da articulação com a vigilância sanitária e epidemiológica.', ok: false,
      why: 'Errada. A articulação é condição da vigilância em saúde do trabalhador.' },
    { t: 'Eles não participam da notificação de agravos relacionados ao trabalho.', ok: false,
      why: 'Errada. São unidades notificadoras de referência.' }
  ],
  comentario: 'O centro de referência é retaguarda técnica: matricia a rede, investiga agravos, capacita e faz vigilância. Não emite benefício — isso é perícia previdenciária — nem substitui a atenção básica.',
  pegadinha: 'Descrevê-lo como ambulatório especializado para todos os trabalhadores inverte sua função na rede.',
  refs: ['RENAST — Portaria GM/MS nº 2.728/2009', 'PNSTT'] },

{ id: 'q-1.7-020', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre as competências do Sistema Único de Saúde em saúde do trabalhador previstas na Lei Orgânica da Saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Estão previstas, entre outras, a avaliação do impacto das tecnologias sobre a saúde, a informação ao trabalhador e ao sindicato sobre riscos e resultados de exames, e a participação na normatização e fiscalização das condições de trabalho.', ok: true,
      why: 'Correta. São competências expressas, e a de informar o trabalhador e sua entidade sindical é frequentemente esquecida.' },
    { t: 'A fiscalização das condições de trabalho é competência exclusiva do órgão do trabalho.', ok: false,
      why: 'Errada. A lei prevê participação do sistema de saúde na normatização e fiscalização.' },
    { t: 'A informação sobre riscos deve ser prestada apenas ao empregador.', ok: false,
      why: 'Errada. O trabalhador e sua entidade sindical são destinatários expressos.' },
    { t: 'A avaliação do impacto de novas tecnologias não integra as competências do sistema de saúde.', ok: false,
      why: 'Errada. Consta expressamente entre as atribuições.' },
    { t: 'O sistema de saúde não pode interditar ambiente de trabalho.', ok: false,
      why: 'Errada. A vigilância sanitária dispõe de poder de interdição diante de risco iminente à saúde.' }
  ],
  comentario: 'A Lei Orgânica dá ao sistema de saúde papel amplo: avaliar tecnologias, informar o trabalhador e o sindicato, participar da normatização e fiscalização, e interditar diante de risco iminente. Competência concorrente, não exclusiva do órgão do trabalho.',
  pegadinha: 'Restringir a informação ao empregador contraria dispositivo expresso que nomeia o trabalhador e o sindicato.',
  refs: ['Lei nº 8.080/1990 — art. 6º, §3º'] },

{ id: 'q-1.7-021', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atenção básica e a saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A ocupação e a atividade laboral devem integrar a anamnese na atenção básica, pois é nela que a maior parte dos trabalhadores adoecidos busca atendimento primeiro — a não pergunta é a principal causa de invisibilidade do nexo.', ok: true,
      why: 'Correta. O agravo relacionado ao trabalho chega à unidade básica; o que falta é a pergunta.' },
    { t: 'Casos suspeitos de agravo relacionado ao trabalho devem ser encaminhados sem qualquer registro na unidade básica.', ok: false,
      why: 'Errada. O registro e a notificação começam onde o caso é identificado.' },
    { t: 'A atenção básica não tem atribuição em saúde do trabalhador.', ok: false,
      why: 'Errada. É porta de entrada e tem atribuições definidas na política.' },
    { t: 'A investigação de nexo é atribuição exclusiva de serviço especializado.', ok: false,
      why: 'Errada. A suspeita e o registro inicial cabem a quem atende.' },
    { t: 'Trabalhadores informais devem ser encaminhados à rede privada.', ok: false,
      why: 'Errada. A cobertura do sistema público é universal, e o informal é justamente quem mais depende dela.' }
  ],
  comentario: 'A pergunta "em que o senhor trabalha?" é o instrumento diagnóstico mais barato da saúde do trabalhador. Sem ela, o agravo ocupacional passa pela unidade básica como doença comum e desaparece das estatísticas.',
  pegadinha: 'Tratar nexo como assunto exclusivo de especialista adia a suspeita para depois da cronificação.',
  refs: ['PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.9-041', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a notificação compulsória de agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A notificação é obrigatória diante da suspeita, independentemente de confirmação diagnóstica ou de reconhecimento de nexo pela previdência, e independe do vínculo do trabalhador — inclusive informal.', ok: true,
      why: 'Correta. Notificar é ato de vigilância baseado em suspeita, não conclusão pericial.' },
    { t: 'Só se notifica após confirmação diagnóstica e reconhecimento do nexo.', ok: false,
      why: 'Errada. Esperar a confirmação atrasa a vigilância e perde o caso.' },
    { t: 'A notificação substitui a comunicação de acidente de trabalho.', ok: false,
      why: 'Errada. São instrumentos de sistemas distintos, com finalidades distintas, e ambos são devidos.' },
    { t: 'Trabalhadores informais não são objeto de notificação.', ok: false,
      why: 'Errada. A notificação independe de vínculo formal.' },
    { t: 'A notificação depende de autorização do empregador.', ok: false,
      why: 'Errada. É dever do profissional e do serviço de saúde, sem qualquer anuência do empregador.' }
  ],
  comentario: 'Notificação: por suspeita, sem esperar confirmação, sem depender de vínculo formal nem de autorização do empregador. E não substitui a comunicação de acidente — os dois instrumentos convivem.',
  pegadinha: 'Confundir notificação em saúde com comunicação de acidente faz o profissional emitir um e omitir o outro.',
  refs: ['Portaria de Consolidação nº 4/2017 — notificação compulsória', 'SINAN — fichas de agravos relacionados ao trabalho'] },

{ id: 'q-1.9-042', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a subnotificação de agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Ela produz subestimação sistemática do problema e, por consequência, subdimensionamento de políticas e de recursos — e afeta desigualmente os grupos com menor proteção, ampliando a desigualdade que já existe na exposição.', ok: true,
      why: 'Correta. A subnotificação não é aleatória: concentra-se onde a proteção já é menor.' },
    { t: 'A subnotificação afeta uniformemente todos os grupos de trabalhadores.', ok: false,
      why: 'Errada. Informais, terceirizados e pequenas empresas são sistematicamente menos representados.' },
    { t: 'A subnotificação não interfere no planejamento de políticas públicas.', ok: false,
      why: 'Errada. É a base de cálculo do dimensionamento das ações.' },
    { t: 'A principal causa da subnotificação é a fraude deliberada.', ok: false,
      why: 'Errada. As causas principais são o não reconhecimento do nexo e o desconhecimento do dever de notificar.' },
    { t: 'A subnotificação é problema exclusivo do sistema de saúde, sem reflexo previdenciário.', ok: false,
      why: 'Errada. Reflete-se diretamente no reconhecimento de benefícios acidentários.' }
  ],
  comentario: 'A subnotificação é seletiva: falta mais onde a proteção já falta. Suas causas principais não são fraude, mas não reconhecimento do nexo e desconhecimento do dever — as duas coisas que o médico do trabalho pode corrigir.',
  pegadinha: 'Supor uniformidade da subnotificação sugere que corrigi-la não mudaria o retrato — e mudaria, e desigualmente.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'SINAN'] },

{ id: 'q-1.10-020', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa lança programa de promoção da saúde com desafio de passos, palestra sobre alimentação e bonificação para quem reduzir o índice de massa corporal. Sobre esse desenho, é CORRETO afirmar:',
  alts: [
    { t: 'Ele desloca a responsabilidade para o comportamento individual sem tocar nos determinantes organizacionais — jornada, ritmo, oferta alimentar no local, tempo de pausa — e a bonificação por resultado corporal ainda introduz risco de discriminação.', ok: true,
      why: 'Correta. Promoção que só cobra comportamento culpa o trabalhador pelas condições que a empresa oferece.' },
    { t: 'O desenho é adequado porque atua sobre fatores de risco modificáveis.', ok: false,
      why: 'Errada. Atua apenas sobre o elo final, ignorando o que determina o comportamento no ambiente.' },
    { t: 'A bonificação por redução de medida corporal é instrumento neutro de incentivo.', ok: false,
      why: 'Errada. Premiar resultado corporal cria pressão e potencial discriminação de quem não atinge a meta.' },
    { t: 'Programas de promoção não devem considerar a organização do trabalho.', ok: false,
      why: 'Errada. É justamente ela que condiciona a viabilidade das mudanças propostas.' },
    { t: 'A adesão voluntária elimina qualquer questionamento ético ao programa.', ok: false,
      why: 'Errada. Voluntariedade em relação assimétrica é frágil, sobretudo quando há prêmio ou exposição de resultados.' }
  ],
  comentario: 'Promoção da saúde no trabalho não pode parar no comportamento individual: se a jornada impede o sono e a cantina só oferece fritura, cobrar passos é transferir a conta. Bonificação por medida corporal soma pressão e risco de discriminação.',
  pegadinha: '"Fator de risco modificável" soa técnico e esconde que o programa não modificou nada do ambiente.',
  refs: ['OMS — ambientes de trabalho saudáveis', 'PNSTT'] },

{ id: 'q-1.10-021', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a confidencialidade em programas de promoção da saúde conduzidos no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Dados individuais de saúde colhidos no programa não podem ser repassados ao empregador, que recebe apenas informação agregada — e a participação não pode condicionar avaliação de desempenho, promoção ou permanência no emprego.', ok: true,
      why: 'Correta. Sem essa separação, o programa vira instrumento de seleção.' },
    { t: 'O empregador que custeia o programa tem direito de acesso aos resultados individuais.', ok: false,
      why: 'Errada. Custeio não cria direito de acesso a dado clínico individual.' },
    { t: 'O consentimento assinado na admissão autoriza qualquer uso posterior dos dados.', ok: false,
      why: 'Errada. Consentimento genérico obtido em relação assimétrica não valida uso indeterminado.' },
    { t: 'Dados agregados podem ser divulgados por setor, mesmo em setores com poucos trabalhadores.', ok: false,
      why: 'Errada. Em grupo pequeno, o agregado reidentifica; é preciso agregar acima de um limiar seguro.' },
    { t: 'A participação pode ser exigida como requisito para benefícios contratuais.', ok: false,
      why: 'Errada. Isso converte a adesão em coação e contamina o próprio dado colhido.' }
  ],
  comentario: 'Regra de ouro: empregador recebe agregado, nunca individual. E cuidado com o agregado de setor pequeno, que reidentifica na prática. Participação condicionada a benefício não é voluntária.',
  pegadinha: 'O agregado por setor parece anônimo e deixa de ser quando o setor tem três pessoas.',
  refs: ['Código de Ética Médica', 'LGPD — dados sensíveis de saúde', 'Resoluções do CFM sobre medicina do trabalho'] },

{ id: 'q-2.7-020', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a diferença entre avaliar exposição pelas normas de higiene ocupacional de referência técnica e pelos anexos da norma regulamentadora de insalubridade, é CORRETO afirmar:',
  alts: [
    { t: 'As normas técnicas descrevem procedimento de medição e critérios de avaliação voltados à prevenção, enquanto os anexos da norma de insalubridade têm finalidade também de caracterização de direito — podendo haver divergência entre o resultado técnico e o enquadramento legal.', ok: true,
      why: 'Correta. Finalidades distintas produzem critérios e conclusões que podem não coincidir.' },
    { t: 'As duas abordagens usam sempre os mesmos critérios e produzem o mesmo resultado.', ok: false,
      why: 'Errada. Diferem em parâmetros e finalidade, e a divergência é conhecida.' },
    { t: 'A avaliação técnica preventiva não tem valor quando diverge do enquadramento legal.', ok: false,
      why: 'Errada. Ela orienta a prevenção, que é o objetivo maior, independentemente do enquadramento.' },
    { t: 'A caracterização legal de insalubridade indica que a exposição está tecnicamente controlada quando não caracterizada.', ok: false,
      why: 'Errada. Não caracterizar insalubridade não significa exposição segura.' },
    { t: 'A adoção de critério mais protetor que o legal é vedada à empresa.', ok: false,
      why: 'Errada. Adotar critério mais protetor é sempre permitido e desejável.' }
  ],
  comentario: 'Duas lógicas: a técnica busca proteger; a legal busca caracterizar direito. Elas divergem, e a divergência não invalida a técnica. Ausência de insalubridade caracterizada nunca equivale a exposição segura.',
  pegadinha: 'Ler "não caracterizou insalubridade" como "ambiente seguro" encerra a prevenção no ponto errado.',
  refs: ['NHO — Fundacentro', 'NR-15', 'ACGIH — TLVs'] },

{ id: 'q-4.10-020', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a vacinação de trabalhadores no âmbito do serviço de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A indicação deve ser baseada no risco ocupacional específico, com registro e verificação de resposta quando aplicável; a vacinação é oferecida sem custo ao trabalhador e sua recusa deve ser registrada, com esclarecimento sobre os riscos e sem exclusão automática da função.', ok: true,
      why: 'Correta. Indicação por risco, custeio pelo empregador, recusa registrada e esclarecida.' },
    { t: 'A recusa de vacinação autoriza a imediata dispensa do trabalhador.', ok: false,
      why: 'Errada. A conduta é esclarecimento, registro e reavaliação de risco, não dispensa automática.' },
    { t: 'O custo da vacinação ocupacional pode ser dividido com o trabalhador.', ok: false,
      why: 'Errada. Medidas de proteção são custeadas integralmente pelo empregador.' },
    { t: 'A verificação de resposta sorológica é desnecessária em qualquer situação.', ok: false,
      why: 'Errada. Para determinadas vacinas e grupos de risco, a verificação da resposta é indicada.' },
    { t: 'O esquema vacinal ocupacional é idêntico para todas as funções da empresa.', ok: false,
      why: 'Errada. A indicação decorre do risco específico de cada função.' }
  ],
  comentario: 'Vacinação ocupacional: indicada por risco de função, custeada pelo empregador, com verificação de resposta quando aplicável, e recusa esclarecida e registrada — não dispensa nem exclusão automática.',
  pegadinha: 'Tratar a recusa como causa de desligamento converte medida de proteção em instrumento disciplinar.',
  refs: ['NR-7', 'NR-32', 'Programa Nacional de Imunizações'] },

{ id: 'q-5.3-041', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador com hérnia discal degenerativa prévia desenvolve quadro incapacitante após dois anos em função com levantamento repetitivo de cargas. Sobre a análise do caso, é CORRETO afirmar:',
  alts: [
    { t: 'A doença preexistente não afasta a relação com o trabalho: se a atividade contribuiu para desencadear ou agravar o quadro, configura-se concausa, com as mesmas consequências do nexo por causa única.', ok: true,
      why: 'Correta. É a essência da concausalidade — o trabalho não precisa ser a única causa.' },
    { t: 'A preexistência da degeneração discal afasta qualquer nexo.', ok: false,
      why: 'Errada. Preexistência é precisamente a hipótese em que a concausa se aplica.' },
    { t: 'Configurada a concausa, os efeitos legais são proporcionalmente reduzidos.', ok: false,
      why: 'Errada. A lei não estabelece proporcionalidade: reconhecida a concausa, os efeitos são integrais.' },
    { t: 'A concausa só se aplica quando a contribuição do trabalho é majoritária.', ok: false,
      why: 'Errada. Basta que tenha contribuído para o resultado.' },
    { t: 'O caráter degenerativo do achado de imagem decide a questão do nexo.', ok: false,
      why: 'Errada. Achado de imagem degenerativo é comum em assintomáticos e não decide nexo isoladamente.' }
  ],
  comentario: 'Concausa: o trabalho contribuiu, ainda que não sozinho e ainda que não majoritariamente. Efeitos integrais, sem rateio. E o achado degenerativo de imagem não resolve nada — está presente em boa parte da população sem sintoma.',
  pegadinha: 'A ideia de "reduzir proporcionalmente" na concausa é atraente e não tem previsão legal.',
  refs: ['Lei nº 8.213/1991 — art. 21, I', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.3-042', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a distinção entre concausa preexistente, concomitante e superveniente, é CORRETO afirmar:',
  alts: [
    { t: 'A classificação se refere ao momento em que o fator concorrente atua em relação ao evento — antes, junto ou depois —, e todas as três podem configurar relação com o trabalho, inclusive a superveniente, como a complicação que se instala durante o tratamento do agravo ocupacional.', ok: true,
      why: 'Correta. A superveniente é a menos lembrada e a lei a contempla expressamente.' },
    { t: 'Apenas a concausa concomitante ao evento é reconhecida.', ok: false,
      why: 'Errada. As três modalidades são reconhecidas.' },
    { t: 'A concausa superveniente rompe o nexo com o evento original.', ok: false,
      why: 'Errada. Quando decorre do agravo ou de seu tratamento, mantém-se ligada ao evento original.' },
    { t: 'A concausa preexistente exige que o trabalhador tenha ocultado a condição na admissão.', ok: false,
      why: 'Errada. A existência da condição prévia é fato clínico, não questão de omissão.' },
    { t: 'A classificação em preexistente, concomitante ou superveniente altera os efeitos legais do reconhecimento.', ok: false,
      why: 'Errada. Reconhecida a concausa, os efeitos são os mesmos.' }
  ],
  comentario: 'Três momentos, mesmos efeitos. A superveniente é a que mais escapa: infecção hospitalar durante o tratamento da fratura do acidente segue ligada ao acidente.',
  pegadinha: 'Supor que a complicação posterior "quebra" o nexo desfaz justamente a modalidade superveniente.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Decreto nº 3.048/1999'] }

);
