/* Lote AM — 1.4 a 1.10, 2.5, 2.8, 4.3, 4.7, 4.9, 5.2, 5.3, 5.6, 6.1, 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-100', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a implantação de um serviço de saúde ocupacional em empresa que nunca teve estrutura própria, é CORRETO afirmar:',
  alts: [
    { t: 'A prioridade é conhecer processos e riscos reais, construindo o inventário antes da rotina de exames.', ok: true,
      why: 'Correta. O programa médico é consequência do inventário, não antecede a ele.' },
    { t: 'A prioridade é implantar de imediato a rotina de exames periódicos, base do acompanhamento da saúde.', ok: false,
      why: 'Errada. Sem conhecer os riscos, os exames escolhidos não correspondem à exposição.' },
    { t: 'A prioridade é o inventário de riscos, que pode ser feito integralmente por análise documental prévia.', ok: false,
      why: 'Errada. Exige visita aos setores e observação do trabalho real.' },
    { t: 'A prioridade é conhecer os processos e riscos, sendo dispensável a participação dos trabalhadores nisso.', ok: false,
      why: 'Errada. É a fonte mais direta sobre como o trabalho acontece.' },
    { t: 'A prioridade é o inventário, devendo a definição de indicadores esperar anos de operação do serviço.', ok: false,
      why: 'Errada. Sem linha de base inicial, não há como demonstrar evolução depois.' }
  ],
  comentario: 'Implantar serviço começa por conhecer processo e risco — visitando, observando e ouvindo. Exame vem depois, derivado do inventário. E define-se linha de base logo, ou não haverá com o que comparar daqui a três anos.',
  pegadinha: 'Começar pela rotina de exames entrega produção visível e um programa que não corresponde aos riscos reais.',
  refs: ['NR-1', 'NR-7', 'NR-4'] },

{ id: 'q-1.5-100', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a melhoria contínua em sistemas de gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'O ciclo exige que a verificação produza consequências reais, sob pena de acumular não conformidades.', ok: true,
      why: 'Correta. Não conformidade repetida ano após ano é o sintoma de ciclo aberto.' },
    { t: 'O ciclo prevê auditorias sucessivas, sendo esperada e sem significado a repetição de não conformidades.', ok: false,
      why: 'Errada. Indica que as ações corretivas não atacaram a causa.' },
    { t: 'O ciclo exige verificação, etapa que se esgota com a realização da auditoria programada do período.', ok: false,
      why: 'Errada. Precisa gerar ação corretiva e verificação de eficácia.' },
    { t: 'O ciclo exige verificação com consequência, sendo a análise crítica pela direção formalidade sem efeito.', ok: false,
      why: 'Errada. É onde se decidem recursos e prioridades, o que viabiliza as ações.' },
    { t: 'O ciclo exige verificação e correção, dispensando a melhoria contínua objetivos mensuráveis definidos.', ok: false,
      why: 'Errada. Sem objetivos mensuráveis não há como avaliar melhoria.' }
  ],
  comentario: 'O ciclo só fecha quando a verificação vira correção e a correção é verificada. Não conformidade que reaparece em auditorias sucessivas é o indicador mais honesto de que o sistema não está funcionando.',
  pegadinha: 'Auditar todo ano e reencontrar os mesmos achados é gestão da documentação, não do risco.',
  refs: ['ISO 45001', 'NR-1'] },

{ id: 'q-1.6-100', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre saúde do trabalhador e saúde ambiental, é CORRETO afirmar:',
  alts: [
    { t: 'Processos que expõem trabalhadores expõem também o entorno, e um caso pode revelar contaminação.', ok: true,
      why: 'Correta. O trabalhador costuma ser o primeiro caso detectado de uma exposição maior.' },
    { t: 'A exposição ocupacional e a ambiental são fenômenos distintos, sem interseção entre suas fontes.', ok: false,
      why: 'Errada. Compartilham frequentemente a mesma fonte.' },
    { t: 'Processos expõem trabalhadores e entorno, não devendo a investigação ambiental considerar os expostos.', ok: false,
      why: 'Errada. São o grupo de maior exposição e frequentemente os primeiros afetados.' },
    { t: 'Processos expõem os dois grupos, funcionando trabalhadores como sentinelas só em exposições agudas.', ok: false,
      why: 'Errada. Também em exposições crônicas, por concentrarem maior dose acumulada.' },
    { t: 'Processos expõem os dois grupos, ficando o entorno protegido quando a exposição interna está controlada.', ok: false,
      why: 'Errada. Emissões, resíduos e transporte podem afetar o entorno de todo modo.' }
  ],
  comentario: 'O trabalhador é sentinela: recebe a maior dose e adoece primeiro, o que pode revelar contaminação que também alcança o entorno. Vigilância ambiental e do trabalhador olham a mesma fonte por ângulos diferentes.',
  pegadinha: 'Investigar o caso ocupacional sem olhar o entorno perde a exposição comunitária que a mesma fonte produz.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Vigilância em saúde ambiental'] },

{ id: 'q-1.7-100', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o acesso do trabalhador aos serviços do sistema público durante o horário de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A dificuldade de conciliar horário de atendimento e jornada é barreira concreta de acesso.', ok: true,
      why: 'Correta. Serviço que só funciona no horário comercial exclui quem trabalha nesse horário.' },
    { t: 'A conciliação entre jornada e horário de atendimento não constitui barreira relevante de acesso.', ok: false,
      why: 'Errada. É uma das barreiras mais concretas para trabalhadores.' },
    { t: 'A barreira de horário existe, decorrendo a busca tardia exclusivamente de desinformação do trabalhador.', ok: false,
      why: 'Errada. Barreiras organizacionais de acesso têm peso determinante.' },
    { t: 'A barreira de horário existe, sendo a liberação para consulta liberalidade da empresa sem respaldo.', ok: false,
      why: 'Errada. Há previsões relativas a consultas e exames, sobretudo os ocupacionais.' },
    { t: 'A barreira de horário existe, sem que a ampliação de horário afete a cobertura de trabalhadores.', ok: false,
      why: 'Errada. É uma das medidas mais efetivas para esse grupo.' }
  ],
  comentario: 'Serviço aberto só em horário comercial não alcança quem trabalha em horário comercial. A busca tardia do trabalhador é, em boa parte, barreira de acesso — e ampliar horário é a medida que mais muda essa cobertura.',
  pegadinha: 'Explicar a procura tardia por desinformação individualiza uma barreira que é de organização do serviço.',
  refs: ['Lei nº 8.080/1990', 'PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.8-100', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a inspeção sanitária em ambiente de trabalho e a produção do relatório, é CORRETO afirmar:',
  alts: [
    { t: 'Deve descrever o observado, as fontes, as inadequações e as medidas exigidas com prazos.', ok: true,
      why: 'Correta. O retorno para verificar cumprimento é o que converte inspeção em mudança.' },
    { t: 'Deve descrever o observado e as inadequações, encerrando-se a inspeção com a entrega do relatório.', ok: false,
      why: 'Errada. A verificação do cumprimento é etapa essencial.' },
    { t: 'Deve descrever o observado e as medidas exigidas, sem necessidade de indicar prazos para cada uma.', ok: false,
      why: 'Errada. Sem prazo não há como verificar cumprimento nem cobrar.' },
    { t: 'Deve descrever o observado, não devendo constar dele as informações prestadas pelos trabalhadores.', ok: false,
      why: 'Errada. Devem constar, com a proteção da identidade de quem as prestou.' },
    { t: 'Deve descrever o observado e as inadequações, evitando o registro fotográfico das condições encontradas.', ok: false,
      why: 'Errada. O registro documenta a condição no momento e sustenta a exigência.' }
  ],
  comentario: 'Relatório de inspeção: o que se viu, de onde veio a informação, o que está inadequado, o que se exige e em que prazo — com identidade dos informantes protegida. E o retorno é o que faz a mudança acontecer.',
  pegadinha: 'Entregar relatório sem prazo e sem retorno produz arquivo, não correção.',
  refs: ['PNSTT', 'Legislação sanitária', 'Lei nº 8.080/1990'] },

{ id: 'q-1.9-100', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a investigação que se segue à notificação de um agravo relacionado ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'É o início do processo: cabe investigar a situação de trabalho e verificar outros expostos.', ok: true,
      why: 'Correta. Um caso notificado sinaliza um grupo exposto à mesma condição.' },
    { t: 'É o registro do caso, encerrando a atuação do serviço de saúde sobre aquele agravo notificado.', ok: false,
      why: 'Errada. É o disparador da investigação, não o seu fim.' },
    { t: 'É o início do processo, devendo a investigação limitar-se ao trabalhador que foi notificado.', ok: false,
      why: 'Errada. A verificação de outros expostos é o que produz efeito coletivo.' },
    { t: 'É o início do processo, dependendo a investigação da situação de trabalho de autorização da empresa.', ok: false,
      why: 'Errada. A vigilância tem competência própria de acesso e inspeção.' },
    { t: 'É o início do processo, não justificando casos isolados a investigação da situação de trabalho.', ok: false,
      why: 'Errada. Caso isolado pode ser o primeiro identificado entre vários existentes.' }
  ],
  comentario: 'Notificar é abrir o caso, não fechá-lo: investiga-se a situação de trabalho e procura-se quem mais está exposto. Caso isolado costuma ser o primeiro visto, não o único existente.',
  pegadinha: 'Tratar a notificação como conclusão transforma vigilância em cadastro.',
  refs: ['SINAN', 'PNSTT'] },

{ id: 'q-1.10-100', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre ações de promoção da saúde voltadas ao sono de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'A higiene do sono tem eficácia limitada quando a escala impede o descanso adequado.', ok: true,
      why: 'Correta. Não há higiene do sono que compense intervalo interjornada insuficiente.' },
    { t: 'As orientações de higiene do sono são suficientes, qualquer que seja a escala de trabalho praticada.', ok: false,
      why: 'Errada. Escala inadequada inviabiliza a aplicação das orientações.' },
    { t: 'A higiene do sono tem eficácia limitada, não integrando o tempo de deslocamento a análise do descanso.', ok: false,
      why: 'Errada. Consome o intervalo entre jornadas e reduz o tempo disponível para dormir.' },
    { t: 'A intervenção deve alcançar a escala, sem que a privação crônica de sono se relacione a acidentes.', ok: false,
      why: 'Errada. É fator de risco reconhecido para acidentes e erros.' },
    { t: 'A intervenção deve alcançar a escala, não tendo respaldo técnico os cochilos programados no turno noturno.', ok: false,
      why: 'Errada. Há evidência de redução de sonolência e de erros em turnos noturnos.' }
  ],
  comentario: 'Higiene do sono não compensa escala ruim: o que muda o quadro é o intervalo entre turnos, o desenho da escala e o deslocamento. Cochilo programado no noturno tem respaldo técnico e é subutilizado.',
  pegadinha: 'Entregar orientação de sono a quem tem onze horas entre turnos, sendo três de ônibus, é transferir um problema organizacional.',
  refs: ['Fischer, F. M. — trabalho em turnos e saúde', 'CLT — intervalos', 'OIT'] },

{ id: 'q-2.5-090', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a comunicação de riscos aos trabalhadores como componente do gerenciamento, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser informados dos riscos, das medidas e dos resultados, em linguagem compreensível.', ok: true,
      why: 'Correta. Informar em linguagem inacessível é cumprir formalmente e não informar.' },
    { t: 'Devem receber os laudos técnicos completos, entrega que cumpre integralmente o dever de informar.', ok: false,
      why: 'Errada. É preciso comunicar de forma compreensível ao destinatário.' },
    { t: 'Devem ser informados dos riscos, sem necessidade de comunicar resultados de avaliações ambientais.', ok: false,
      why: 'Errada. O acesso à informação sobre a própria exposição é direito.' },
    { t: 'Devem ser informados dos riscos, sendo a comunicação atribuição exclusiva da área de segurança.', ok: false,
      why: 'Errada. O médico do trabalho também tem esse dever.' },
    { t: 'Devem ser informados em linguagem acessível, omitindo-se os riscos ainda não confirmados.', ok: false,
      why: 'Errada. A incerteza deve ser comunicada como tal, não suprimida.' }
  ],
  comentario: 'Informar risco é comunicar em linguagem compreensível — inclusive a incerteza. Entregar o laudo completo satisfaz o protocolo e não informa ninguém; e o dever é também do médico, não só da segurança.',
  pegadinha: 'Omitir o risco ainda não confirmado "para não alarmar" retira do trabalhador a chance de se proteger.',
  refs: ['NR-1', 'Lei nº 8.080/1990 — art. 6º, §3º', 'Código de Ética Médica'] },

{ id: 'q-2.8-090', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação da aptidão do trabalhador para o uso de respirador, é CORRETO afirmar:',
  alts: [
    { t: 'O uso impõe carga respiratória e cardiovascular e pode gerar desconforto e claustrofobia.', ok: true,
      why: 'Correta. A inaptidão para um tipo de respirador não implica inaptidão para a função.' },
    { t: 'O uso de respirador é passivo e não impõe carga fisiológica adicional relevante ao trabalhador.', ok: false,
      why: 'Errada. Impõe carga respiratória e cardiovascular, especialmente em esforço.' },
    { t: 'O uso impõe carga adicional, implicando a inaptidão para um tipo de respirador inaptidão para a função.', ok: false,
      why: 'Errada. Existem alternativas técnicas com menor carga ou sem vedação facial.' },
    { t: 'O uso impõe carga cardiovascular, não sendo a claustrofobia aspecto relevante nessa avaliação médica.', ok: false,
      why: 'Errada. Pode inviabilizar o uso contínuo e é aspecto a considerar.' },
    { t: 'O uso impõe carga adicional, dispensando a avaliação de aptidão para respirador registro específico.', ok: false,
      why: 'Errada. Integra o programa de proteção respiratória e deve ser registrada.' }
  ],
  comentario: 'Respirador cansa: carga respiratória e cardiovascular, calor, desconforto, claustrofobia. Inapto para um tipo não é inapto para a função — equipamento motorizado ou com ar fornecido resolve boa parte dos casos.',
  pegadinha: 'Concluir pela inaptidão à função quando o problema é o tipo de equipamento elimina um trabalhador desnecessariamente.',
  refs: ['NR-6', 'Programa de Proteção Respiratória — Fundacentro'] },

{ id: 'q-4.3-080', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a bissinose e outras doenças respiratórias por poeiras orgânicas, é CORRETO afirmar:',
  alts: [
    { t: 'A bissinose, por poeiras de algodão, piora classicamente no primeiro dia após a folga.', ok: true,
      why: 'Correta. A piora na segunda-feira é a marca clínica clássica dessa doença.' },
    { t: 'Poeiras orgânicas produzem incômodo respiratório sem causar doença ocupacional relevante nos expostos.', ok: false,
      why: 'Errada. Causam bissinose, pneumonite de hipersensibilidade e síndrome tóxica.' },
    { t: 'A bissinose decorre de poeiras vegetais, com sintomas mais intensos ao fim da semana de trabalho.', ok: false,
      why: 'Errada. O padrão clássico é a piora no primeiro dia após o afastamento.' },
    { t: 'A bissinose decorre de poeiras de algodão, de instalação exclusivamente aguda, sem forma crônica.', ok: false,
      why: 'Errada. A exposição prolongada pode levar a comprometimento crônico.' },
    { t: 'A bissinose decorre de poeiras vegetais, sem valor diagnóstico o padrão temporal dos sintomas.', ok: false,
      why: 'Errada. É justamente o dado que mais orienta a suspeita nessa doença.' }
  ],
  comentario: 'Bissinose: poeira de algodão e fibras vegetais, com piora no primeiro dia após a folga — o padrão de segunda-feira. Poeira orgânica também causa pneumonite de hipersensibilidade e síndrome tóxica por poeira orgânica.',
  pegadinha: 'Esperar piora progressiva ao longo da semana inverte o padrão temporal característico.',
  refs: ['Diretrizes de pneumologia ocupacional', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-4.7-110', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o encaminhamento de trabalhador a serviço de saúde mental pela medicina do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Deve incluir as condições de trabalho relevantes, com autorização do próprio trabalhador.', ok: true,
      why: 'Correta. O assistente não conhece o posto; quem conhece é quem encaminha.' },
    { t: 'Deve conter a queixa relatada pelo trabalhador, elemento que orienta a avaliação do serviço assistencial.', ok: false,
      why: 'Errada. As condições de trabalho são informação essencial que só o serviço ocupacional tem.' },
    { t: 'Deve incluir as condições de trabalho, que podem ser enviadas sem autorização do trabalhador.', ok: false,
      why: 'Errada. O compartilhamento de informação relativa ao trabalhador exige sua autorização.' },
    { t: 'Deve incluir a queixa e o histórico, sendo a dimensão ocupacional irrelevante para a conduta assistencial.', ok: false,
      why: 'Errada. Influencia diretamente a conduta e o planejamento do retorno.' },
    { t: 'Deve incluir as condições de trabalho, cessando após o encaminhamento a responsabilidade do serviço.', ok: false,
      why: 'Errada. O acompanhamento e a atuação sobre o ambiente permanecem.' }
  ],
  comentario: 'Encaminhar bem é entregar o que só você tem: a descrição das condições de trabalho, com autorização do trabalhador. Sem isso, o assistente avalia o quadro sem a metade ocupacional dele.',
  pegadinha: 'Encaminhar apenas com a queixa entrega ao assistente a mesma informação que ele já teria sem você.',
  refs: ['Código de Ética Médica', 'Ministério da Saúde — transtornos mentais relacionados ao trabalho'] },

{ id: 'q-4.9-100', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o afastamento de trabalhadores com doenças transmissíveis, é CORRETO afirmar:',
  alts: [
    { t: 'Considera transmissibilidade, via de transmissão e natureza da atividade exercida pelo trabalhador.', ok: true,
      why: 'Correta. O critério é o risco a terceiros, não apenas a condição do trabalhador.' },
    { t: 'Considera a condição clínica do trabalhador, justificando-se o afastamento apenas por sua incapacidade.', ok: false,
      why: 'Errada. O risco de transmissão a terceiros é razão autônoma.' },
    { t: 'Considera transmissibilidade e via de transmissão, sem que a natureza da atividade influencie a decisão.', ok: false,
      why: 'Errada. Manipular alimentos ou assistir pacientes muda completamente a decisão.' },
    { t: 'Considera a transmissibilidade, devendo o afastamento durar até a cura clínica completa em todos os casos.', ok: false,
      why: 'Errada. O critério é o período de transmissibilidade, que pode ser menor.' },
    { t: 'Considera o risco a terceiros, devendo o período de afastamento ser descontado do trabalhador.', ok: false,
      why: 'Errada. O afastamento decorre de medida sanitária e não pode onerá-lo.' }
  ],
  comentario: 'Afastar por transmissibilidade é diferente de afastar por incapacidade: o critério é o período em que transmite e o risco da atividade. E medida sanitária não é falta do trabalhador.',
  pegadinha: 'Vincular o retorno à cura completa afasta além do necessário; vinculá-lo à melhora subjetiva devolve o trabalhador ainda transmitindo.',
  refs: ['Ministério da Saúde — períodos de transmissibilidade', 'RDC sobre manipulação de alimentos', 'NR-32'] },

{ id: 'q-5.2-090', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise de nexo em trabalhador com histórico de múltiplos vínculos e exposições em empresas distintas, é CORRETO afirmar:',
  alts: [
    { t: 'A exposição relevante pode estar em vínculo anterior, exigindo reconstituir a história completa.', ok: true,
      why: 'Correta. Dificuldade de atribuir a um empregador não é o mesmo que ausência de nexo.' },
    { t: 'A exposição pode estar em vínculo anterior, afastando a natureza ocupacional a impossibilidade de atribuí-la.', ok: false,
      why: 'Errada. São questões distintas: natureza ocupacional e responsabilidade individual.' },
    { t: 'A análise deve considerar o último vínculo do trabalhador, onde a exposição atual efetivamente ocorre.', ok: false,
      why: 'Errada. Exposições anteriores podem ser as determinantes em latências longas.' },
    { t: 'A exposição pode estar em vínculo anterior, não auxiliando documentos previdenciários a reconstituição.', ok: false,
      why: 'Errada. Registros de vínculos e documentos de exposição são fontes importantes.' },
    { t: 'A exposição pode estar em vínculo anterior, sem valor o relato do trabalhador por ser retrospectivo.', ok: false,
      why: 'Errada. Frequentemente é a única fonte sobre condições de décadas atrás.' }
  ],
  comentario: 'Com múltiplos vínculos, reconstitui-se a história inteira — registros previdenciários e relato do trabalhador incluídos. Não conseguir apontar um empregador responsável não descaracteriza a natureza ocupacional do agravo.',
  pegadinha: 'Confundir "não sei de quem é a responsabilidade" com "não é doença do trabalho" nega o reconhecimento pela razão errada.',
  refs: ['Lei nº 8.213/1991', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.3-100', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausalidade em transtornos mentais relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Fatores pessoais e familiares não afastam a contribuição do trabalho, podendo configurar concausa.', ok: true,
      why: 'Correta. Multideterminação é regra nesses quadros, não exceção que afasta o nexo.' },
    { t: 'A presença de fatores pessoais e familiares afasta o nexo ocupacional nos transtornos mentais.', ok: false,
      why: 'Errada. Pode configurar concausa, que é reconhecida.' },
    { t: 'Fatores pessoais não afastam a contribuição, embora transtornos mentais não admitam nexo com o trabalho.', ok: false,
      why: 'Errada. Constam expressamente da lista de doenças relacionadas ao trabalho.' },
    { t: 'Fatores pessoais podem coexistir, impedindo a multideterminação do quadro qualquer análise de nexo.', ok: false,
      why: 'Errada. A análise busca identificar a contribuição ocupacional dentro do conjunto.' },
    { t: 'Fatores pessoais podem configurar concausa, impedindo o histórico psiquiátrico prévio o reconhecimento.', ok: false,
      why: 'Errada. Agravamento de condição preexistente é hipótese expressa de concausa.' }
  ],
  comentario: 'Transtorno mental é multideterminado por definição — e isso não afasta a contribuição do trabalho, identificável e reconhecível como concausa. Histórico prévio abre a via do agravamento, não fecha a do nexo.',
  pegadinha: 'Usar a multideterminação para negar nexo eliminaria de saída toda a categoria dos transtornos mentais relacionados ao trabalho.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Ministério da Saúde — transtornos mentais relacionados ao trabalho'] },

{ id: 'q-5.6-100', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o retorno gradual ao trabalho como estratégia de reabilitação, é CORRETO afirmar:',
  alts: [
    { t: 'Consiste em retomada progressiva de carga e jornada, com acompanhamento e ajustes no processo.', ok: true,
      why: 'Correta. Associa-se a melhores desfechos de permanência, sobretudo em osteomusculares e saúde mental.' },
    { t: 'Consiste em retomada progressiva, sem vantagem demonstrada sobre o retorno integral imediato à função.', ok: false,
      why: 'Errada. Há evidência de melhores desfechos de permanência com a retomada progressiva.' },
    { t: 'Consiste em retomada progressiva de carga, dispensando acompanhamento durante o período de retomada.', ok: false,
      why: 'Errada. O acompanhamento é o que permite ajustar antes da recaída.' },
    { t: 'Consiste em retomada progressiva, com aplicação restrita aos quadros musculoesqueléticos crônicos.', ok: false,
      why: 'Errada. É especialmente útil também em saúde mental.' },
    { t: 'Consiste em retomada progressiva de jornada, implicando redução proporcional do salário do período.', ok: false,
      why: 'Errada. As condições devem ser definidas sem converter a estratégia em prejuízo.' }
  ],
  comentario: 'Retorno gradual: carga e jornada progressivas, com acompanhamento e ajuste. Melhores desfechos de permanência, útil em musculoesquelético e saúde mental — e não pode virar redução de salário disfarçada.',
  pegadinha: 'Retorno gradual sem acompanhamento vira retorno integral com atraso, e a recaída chega igual.',
  refs: ['Literatura sobre retorno ao trabalho', 'Lei nº 8.213/1991'] },

{ id: 'q-6.1-110', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a conclusão de aptidão com restrição, é CORRETO afirmar:',
  alts: [
    { t: 'Reconhece que ele pode exercer a função com limitações, exigindo que a empresa as implemente.', ok: true,
      why: 'Correta. Restrição não implementada é papel; o trabalhador segue na mesma condição.' },
    { t: 'Reconhece limitações específicas, transferindo ao trabalhador a responsabilidade de evitar o restrito.', ok: false,
      why: 'Errada. Cabe à empresa organizar o trabalho de modo a respeitar a restrição.' },
    { t: 'Reconhece limitações específicas, dispensando verificação posterior de cumprimento uma vez emitida.', ok: false,
      why: 'Errada. A verificação é parte do acompanhamento.' },
    { t: 'Reconhece limitações específicas, equivalendo na prática à inaptidão do trabalhador para a função.', ok: false,
      why: 'Errada. Reconhece a possibilidade de exercício com condições ajustadas.' },
    { t: 'Reconhece limitações, devendo indicar o diagnóstico que a motivou para que a empresa a compreenda.', ok: false,
      why: 'Errada. Descreve-se a limitação funcional; o diagnóstico permanece sob sigilo.' }
  ],
  comentario: 'Apto com restrição é meio caminho: cabe à empresa implementar as condições e ao serviço médico verificar. Sem implementação e sem verificação, a restrição não protege ninguém — e o diagnóstico não entra no documento.',
  pegadinha: 'Deixar ao trabalhador a tarefa de "evitar" a atividade restrita devolve a ele o risco que a restrição reconheceu.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.4-110', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a intoxicação aguda por exposição maciça a gases em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Gases pouco hidrossolúveis irritam pouco de início e causam lesão pulmonar tardia.', ok: true,
      why: 'Correta. É o padrão que faz um trabalhador aparentemente bem piorar horas depois.' },
    { t: 'A ausência de sintomas respiratórios logo após a exposição permite a liberação imediata do trabalhador.', ok: false,
      why: 'Errada. Alguns gases produzem edema pulmonar de instalação tardia.' },
    { t: 'Todos os gases irritantes produzem sintomas imediatos, proporcionais à gravidade da exposição sofrida.', ok: false,
      why: 'Errada. A hidrossolubilidade determina onde e quando o efeito aparece.' },
    { t: 'Gases pouco hidrossolúveis agem tardiamente, e os muito hidrossolúveis não dão alerta sensorial.', ok: false,
      why: 'Errada. Produzem irritação intensa e precoce, o que induz a fuga.' },
    { t: 'Gases pouco hidrossolúveis agem tardiamente, sem que identificar o gás altere a conduta de observação.', ok: false,
      why: 'Errada. Define o tempo de observação e os cuidados específicos.' }
  ],
  comentario: 'Hidrossolubilidade decide o padrão: gás muito solúvel irrita cedo e faz a pessoa fugir; gás pouco solúvel deixa chegar fundo e o edema pulmonar aparece horas depois. Por isso se observa mesmo quem está bem.',
  pegadinha: 'Liberar o trabalhador assintomático após exposição a gás pouco hidrossolúvel é a decisão que precede a piora noturna.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'Protocolos de emergências toxicológicas'] }

);
