/* Lote J — 5.4, 4.8, 2.9, 4.3. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-5.4-052', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em perícia judicial, o assistente técnico de uma das partes apresenta parecer divergente do laudo pericial. Sobre a conduta do perito, é CORRETO afirmar:',
  alts: [
    { t: 'Deve responder tecnicamente aos pontos divergentes, mantendo ou revendo conforme o mérito.', ok: true,
      why: 'Correta. A revisão fundamentada não desabona o laudo; recusar-se a enfrentar, sim.' },
    { t: 'Deve ignorar o parecer apresentado, por ser peça produzida por parte interessada no resultado.', ok: false,
      why: 'Errada. É elemento legítimo que precisa ser enfrentado tecnicamente.' },
    { t: 'Deve responder, comprometendo a revisão da conclusão diante de argumento procedente sua idoneidade.', ok: false,
      why: 'Errada. Rever com fundamento é sinal de rigor, não de fragilidade.' },
    { t: 'Deve responder e adotar a conclusão do assistente, de modo a não prolongar o andamento do feito.', ok: false,
      why: 'Errada. A conclusão se define pelo mérito técnico, não pela celeridade.' },
    { t: 'Deve responder tecnicamente, indicando a divergência erro necessário de um dos dois profissionais.', ok: false,
      why: 'Errada. Decorre da diferença de objeto e de perspectiva.' }
  ],
  comentario: 'O perito responde os pontos divergentes, e revê se o argumento procede. Rever com fundamento fortalece o laudo; ignorar a divergência o enfraquece. Aderir por conveniência é o pior dos caminhos.',
  pegadinha: 'Tratar a mudança de conclusão como sinal de fragilidade pressiona o perito a manter erro identificado.',
  refs: ['Código de Processo Civil — prova pericial', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-5.4-053', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o exame pericial e o acesso a documentos e informações do periciando, é CORRETO afirmar:',
  alts: [
    { t: 'Acessa o pertinente ao objeto, comunicando a natureza do ato e a ausência de relação assistencial.', ok: true,
      why: 'Correta. O sigilo permanece quanto ao que não integra o objeto pericial.' },
    { t: 'A perícia autoriza acesso irrestrito a todo o prontuário do periciando, por interesse processual.', ok: false,
      why: 'Errada. O acesso se limita ao pertinente ao objeto da perícia.' },
    { t: 'Acessa o pertinente ao objeto, devendo prestar orientação terapêutica ao periciando no exame.', ok: false,
      why: 'Errada. Orientar a procurar atendimento é diferente de prescrever.' },
    { t: 'Acessa o pertinente ao objeto, sem necessidade de informar o periciando sobre a finalidade do ato.', ok: false,
      why: 'Errada. A comunicação prévia da natureza do ato é dever ético.' },
    { t: 'Acessa o pertinente ao objeto, não se aplicando o sigilo médico à relação pericial em extensão alguma.', ok: false,
      why: 'Errada. O sigilo se mantém sobre o que não integra o objeto.' }
  ],
  comentario: 'A perícia abre uma exceção limitada ao sigilo: só o pertinente ao quesito, e com o periciando informado de que ali não há relação assistencial. Achado incidental relevante à saúde se comunica ao periciando para que busque assistência — sem virar consulta.',
  pegadinha: '"Perícia autoriza acesso a tudo" é a leitura mais comum e mais errada da exceção ao sigilo.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-4.8-053', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a vigilância de trabalhadores expostos a agentes cancerígenos, é CORRETO afirmar:',
  alts: [
    { t: 'Deve continuar após o fim da exposição, porque a latência pode ultrapassar décadas', ok: true,
      why: 'Correta. O registro histórico é o que permite relacionar o câncer ao trabalho anterior.' },
    { t: 'Pode ser encerrado com o fim da exposição, quando cessa o acréscimo de dose ao trabalhador.', ok: false,
      why: 'Errada. A latência longa é a razão do acompanhamento posterior.' },
    { t: 'Deve continuar, permitindo a ausência de sintomas ao fim do vínculo descartar risco futuro.', ok: false,
      why: 'Errada. O agravo se manifesta décadas depois, sem sintomas prévios.' },
    { t: 'Deve continuar, estando disponível rastreamento eficaz para a maioria dos cânceres ocupacionais.', ok: false,
      why: 'Errada. Para a maioria não há rastreamento eficaz disponível.' },
    { t: 'Deve continuar, podendo o registro de exposições ser descartado após o desligamento do trabalhador.', ok: false,
      why: 'Errada. É justamente depois que o registro se torna essencial.' }
  ],
  comentario: 'Cancerígeno tem latência de décadas: a vigilância não termina com o vínculo e o registro da exposição precisa sobreviver ao trabalhador na empresa. E como rastreamento eficaz é exceção, prevenir a exposição continua sendo a única medida de alto rendimento.',
  pegadinha: 'Descartar registros após o desligamento inviabiliza o nexo exatamente quando ele apareceria.',
  refs: ['IARC — monografias', 'NR-7', 'INCA — câncer relacionado ao trabalho'] },

{ id: 'q-4.8-054', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a hierarquia de medidas frente a agentes reconhecidamente cancerígenos para humanos, é CORRETO afirmar:',
  alts: [
    { t: 'A prioridade é substituir; inviável isso, sistema fechado e engenharia, com individual complementar.', ok: true,
      why: 'Correta. Não se admite tratar o limite de exposição como zona segura.' },
    { t: 'A prioridade é manter a exposição abaixo do limite estabelecido para o agente cancerígeno em uso.', ok: false,
      why: 'Errada. Para cancerígenos não se assume limiar seguro.' },
    { t: 'A prioridade é a proteção respiratória, medida de primeira linha diante de agentes cancerígenos.', ok: false,
      why: 'Errada. É o último degrau da hierarquia de controle.' },
    { t: 'A prioridade é substituir, o que só deve ser considerado quando o custo do substituto for equivalente.', ok: false,
      why: 'Errada. O custo não afasta a exigência de buscar a substituição.' },
    { t: 'A prioridade é substituir, reduzindo o rodízio de trabalhadores o risco individual proporcionalmente.', ok: false,
      why: 'Errada. Sem limiar, o rodízio distribui o risco em vez de reduzi-lo.' }
  ],
  comentario: 'Cancerígeno: substituir primeiro, engenharia depois, individual por último. Duas armadilhas conceituais — tomar o limite como zona segura e usar rodízio, que apenas distribui a exposição por mais pessoas.',
  pegadinha: 'O rodízio parece medida de proteção e, para agente sem limiar, aumenta o número de expostos.',
  refs: ['IARC', 'ACGIH — TLVs', 'NR-9'] },

{ id: 'q-2.9-050', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a interpretação de indicadores biológicos de exposição, é CORRETO afirmar:',
  alts: [
    { t: 'O momento da coleta é determinante e varia conforme a meia-vida do agente e do indicador.', ok: true,
      why: 'Correta. Coleta em momento inadequado inviabiliza a interpretação do resultado.' },
    { t: 'O momento da coleta é indiferente desde que o método analítico empregado seja adequado ao agente.', ok: false,
      why: 'Errada. A cinética do agente define quando o indicador reflete a exposição.' },
    { t: 'O momento é determinante, garantindo o resultado abaixo da referência a ausência de dano.', ok: false,
      why: 'Errada. Suscetibilidade individual pode produzir efeito abaixo do valor.' },
    { t: 'O momento é determinante, autorizando um único resultado alterado conclusão definitiva.', ok: false,
      why: 'Errada. Exige confirmação e avaliação do conjunto.' },
    { t: 'O momento é determinante, sem que a exposição extraocupacional interfira nos indicadores.', ok: false,
      why: 'Errada. Hobbies e exposições domiciliares podem elevá-los.' }
  ],
  comentario: 'Indicador biológico exige o momento certo de coleta, confirmação de resultado alterado e investigação de fonte extraocupacional. E o mais importante: valor dentro da referência não significa ausência de dano no indivíduo.',
  pegadinha: 'Tratar o valor de referência como certificado de segurança individual é o erro clássico de leitura.',
  refs: ['ACGIH — BEIs', 'NR-7', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.9-051', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o efeito da exposição simultânea a mais de um agente químico, é CORRETO afirmar:',
  alts: [
    { t: 'Agentes com o mesmo órgão-alvo tendem a efeito aditivo, exigindo somar as frações de exposição', ok: true,
      why: 'Correta. Comparar cada um isoladamente ao seu limite subestima a mistura.' },
    { t: 'Cada agente da mistura deve ser avaliado isoladamente contra seu próprio limite de exposição.', ok: false,
      why: 'Errada. Efeitos aditivos sobre o mesmo alvo exigem soma das frações.' },
    { t: 'O efeito é aditivo, não sendo reconhecida a interação sinérgica entre agentes ocupacionais.', ok: false,
      why: 'Errada. Há sinergias documentadas, como asbesto e tabagismo.' },
    { t: 'O efeito é aditivo, não apresentando o álcool e os solventes interação metabólica relevante.', ok: false,
      why: 'Errada. Competem pelas mesmas vias de biotransformação.' },
    { t: 'O efeito é aditivo, exigindo a avaliação de misturas método exclusivo, sem os limites individuais.', ok: false,
      why: 'Errada. Usa-se justamente a soma das frações dos limites individuais.' }
  ],
  comentario: 'Mistura com mesmo alvo: soma-se a fração de cada agente em relação ao seu limite. Três abaixo do limite podem somar acima do aceitável. E o sinergismo clássico da área é asbesto com tabagismo.',
  pegadinha: 'Avaliar agente por agente é o procedimento que faz uma mistura perigosa passar como conforme.',
  refs: ['ACGIH — TLVs, misturas', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.9-052', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as vias de absorção de agentes químicos no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A via cutânea pode ser significativa, e aí a proteção respiratória isolada é insuficiente.', ok: true,
      why: 'Correta. Daí a notação específica de absorção cutânea nas listas de limites.' },
    { t: 'A via respiratória é a única relevante no ambiente ocupacional para os agentes químicos usados.', ok: false,
      why: 'Errada. A cutânea pode ser predominante para alguns agentes.' },
    { t: 'A via cutânea é relevante, não tendo a via digestiva relevância no ambiente ocupacional.', ok: false,
      why: 'Errada. Comer e fumar no posto produz absorção digestiva.' },
    { t: 'A via cutânea é relevante, indicando a notação de absorção apenas risco de irritação local.', ok: false,
      why: 'Errada. Indica contribuição sistêmica pela pele.' },
    { t: 'A via cutânea é relevante quando há lesão, pois a pele íntegra impede a absorção química.', ok: false,
      why: 'Errada. Vários agentes atravessam a pele íntegra.' }
  ],
  comentario: 'Três vias: respiratória, cutânea e digestiva. A notação de pele nas listas de limites avisa que a absorção sistêmica pela pele é relevante — e nessas situações medir o ar e proteger a respiração não basta.',
  pegadinha: 'Ler a notação cutânea como aviso de irritação local subestima justamente a dose sistêmica.',
  refs: ['ACGIH — TLVs, notação Skin', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-4.3-050', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a asma relacionada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Abrange a asma com sensibilização a agente do trabalho e a preexistente agravada por ele.', ok: true,
      why: 'Correta. Melhora no afastamento com piora no retorno é achado de alto valor.' },
    { t: 'Abrange apenas a asma com sensibilização comprovada a agente específico do ambiente de trabalho.', ok: false,
      why: 'Errada. A asma agravada pelo trabalho também é relacionada a ele.' },
    { t: 'Abrange várias formas, afastando a ausência de sensibilização identificada a origem ocupacional.', ok: false,
      why: 'Errada. Há formas irritativas e agravamento sem sensibilização.' },
    { t: 'Abrange várias formas, afastando a espirometria normal em consulta o diagnóstico da doença.', ok: false,
      why: 'Errada. A asma cursa com função normal fora das crises.' },
    { t: 'Abrange várias formas, sendo preferível manter a exposição com proteção respiratória adequada.', ok: false,
      why: 'Errada. No sensibilizado, o afastamento do agente é a conduta central.' }
  ],
  comentario: 'Asma relacionada ao trabalho tem dois ramos: por sensibilização e por agravamento. Espirometria normal não afasta nada, e a chave clínica é o padrão de melhora nas férias com piora no retorno. Confirmada a sensibilização, afastar o agente — a proteção individual não substitui isso.',
  pegadinha: 'Usar uma espirometria normal para encerrar a investigação é o erro que mais atrasa o diagnóstico.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'Diretrizes de pneumologia ocupacional'] },

{ id: 'q-4.3-051', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a doença pulmonar obstrutiva crônica de origem ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Parcela relevante tem contribuição ocupacional por poeiras, gases, fumos e vapores.', ok: true,
      why: 'Correta. O tabagismo é fator concorrente, e não excludente.' },
    { t: 'A doença decorre do tabagismo, que afasta a contribuição ocupacional para o quadro obstrutivo.', ok: false,
      why: 'Errada. É fator concorrente e não exclui a contribuição do trabalho.' },
    { t: 'Há contribuição ocupacional, mas a doença obstrutiva ocupacional só ocorre em não fumantes.', ok: false,
      why: 'Errada. Ocorre em fumantes e não fumantes, com interação entre os fatores.' },
    { t: 'Há contribuição ocupacional, causando a exposição a poeiras minerais apenas doença restritiva.', ok: false,
      why: 'Errada. Poeiras e irritantes também produzem quadros obstrutivos.' },
    { t: 'Há contribuição ocupacional, excluindo a ausência de alteração radiológica a doença obstrutiva.', ok: false,
      why: 'Errada. A doença obstrutiva se avalia por prova funcional, não por imagem.' }
  ],
  comentario: 'Fração significativa da doença obstrutiva crônica tem contribuição ocupacional, e o tabagismo é concorrente, não excludente. Diagnóstico funcional, não radiológico — e a exposição a poeiras não produz só restrição.',
  pegadinha: '"É fumante, logo não é do trabalho" é a negação de nexo mais frequente e mais frágil.',
  refs: ['ATS/ERS — DPOC ocupacional', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-4.3-052', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a espirometria em programas de vigilância respiratória ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'O valor está na comparação seriada, que revela declínio acelerado antes de sair da referência.', ok: true,
      why: 'Correta. Padronização técnica e guarda dos exames anteriores são essenciais.' },
    { t: 'O exame isolado dentro da faixa de referência descarta dano funcional no trabalhador exposto.', ok: false,
      why: 'Errada. O declínio acelerado ocorre ainda dentro da faixa.' },
    { t: 'O valor está na comparação seriada, que dispensa padronização técnica entre os exames comparados.', ok: false,
      why: 'Errada. Sem padronização a comparação não é válida.' },
    { t: 'O valor está na comparação seriada, substituindo a espirometria a avaliação da exposição ambiental.', ok: false,
      why: 'Errada. São complementares: uma mede efeito, a outra mede exposição.' },
    { t: 'O valor está na comparação seriada, podendo os exames anteriores ser descartados após o laudo.', ok: false,
      why: 'Errada. São exatamente eles que permitem a comparação futura.' }
  ],
  comentario: 'A espirometria de vigilância só rende comparada consigo mesma ao longo dos anos: queda acelerada aparece antes de o valor sair da faixa de referência. Exige padronização e guarda dos exames antigos — e não substitui a avaliação do ambiente.',
  pegadinha: 'Interpretar cada exame contra a referência populacional perde exatamente o declínio individual que se quer detectar.',
  refs: ['ATS/ERS — padronização da espirometria', 'NR-7'] }

);
