/* Lote AQ — 4.4, 4.5, 4.6, 4.8, 4.9, 4.10, 4.7, 5.2, 5.3, 5.4, 5.5, 5.6. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-4.4-130', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre as dermatoses ocupacionais por agentes físicos, é CORRETO afirmar:',
  alts: [
    { t: 'Calor, frio, umidade, radiação e microtraumatismos repetidos produzem quadros próprios — como miliária, perniose, maceração, queimadura actínica e calosidades —, muitas vezes atribuídos a causas pessoais por não envolverem produto químico identificável.', ok: true,
      why: 'Correta. Sem um produto para apontar, a origem ocupacional deixa de ser considerada.' },
    { t: 'Dermatoses ocupacionais decorrem exclusivamente de agentes químicos.', ok: false,
      why: 'Errada. Agentes físicos e biológicos também as produzem.' },
    { t: 'Microtraumatismos repetidos não produzem alterações cutâneas relevantes.', ok: false,
      why: 'Errada. Produzem calosidades, fissuras e lesões características de determinadas ocupações.' },
    { t: 'A umidade constante não é fator de dermatose ocupacional.', ok: false,
      why: 'Errada. O trabalho úmido é um dos principais fatores da dermatite irritativa.' },
    { t: 'Lesões por frio em ambientes refrigerados não têm relevância ocupacional.', ok: false,
      why: 'Errada. Perniose e lesões por frio ocorrem em câmaras frias e frigoríficos.' }
  ],
  comentario: 'Nem toda dermatose ocupacional tem produto químico: calor, frio, umidade, radiação e microtrauma dão quadros próprios. Justamente por não haver um agente para apontar, costumam ser lidos como problema pessoal.',
  pegadinha: 'Procurar sempre um produto químico faz passar despercebida a dermatose por agente físico.',
  refs: ['Salim — Dermatoses Ocupacionais'] },

{ id: 'q-4.5-120', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de comunicação e a percepção de sinais sonoros em ambientes ruidosos, é CORRETO afirmar:',
  alts: [
    { t: 'A perda auditiva e a proteção auditiva excessiva comprometem a percepção de alarmes e de aproximação de equipamentos, o que exige considerar sinalização visual complementar e seleção de protetor com atenuação adequada — nem insuficiente, nem excessiva.', ok: true,
      why: 'Correta. Superproteção transforma proteção auditiva em risco de acidente.' },
    { t: 'Quanto maior a atenuação do protetor, melhor em qualquer situação.', ok: false,
      why: 'Errada. Atenuação excessiva prejudica comunicação e percepção de alertas.' },
    { t: 'A sinalização visual não tem papel em ambientes com ruído elevado.', ok: false,
      why: 'Errada. É complemento necessário quando a percepção sonora está comprometida.' },
    { t: 'A perda auditiva não interfere na segurança do trabalhador em ambiente industrial.', ok: false,
      why: 'Errada. Compromete a percepção de alertas e a localização de fontes sonoras.' },
    { t: 'Protetores com atenuação uniforme por frequência não existem.', ok: false,
      why: 'Errada. Há modelos com atenuação mais plana, que preservam melhor a inteligibilidade da fala.' }
  ],
  comentario: 'Proteger demais também é problema: alarme não ouvido e empilhadeira não percebida. Seleciona-se atenuação adequada, considera-se protetor de resposta mais plana e complementa-se com sinalização visual.',
  pegadinha: 'Escolher sempre o protetor de maior atenuação parece conservador e cria um risco novo.',
  refs: ['NR-6', 'NHO 01 — Fundacentro', 'NIOSH'] },

{ id: 'q-4.6-120', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a organização do trabalho por metas e sua relação com a saúde mental, é CORRETO afirmar:',
  alts: [
    { t: 'Metas continuamente elevadas, divulgação comparativa de desempenho individual e vinculação de remuneração ao resultado compõem um padrão associado a sofrimento psíquico — e a exposição pública do desempenho é elemento que agrava especialmente o quadro.', ok: true,
      why: 'Correta. Ranking exposto é humilhação institucionalizada, com efeito documentado.' },
    { t: 'A existência de metas é, por si, fator de adoecimento.', ok: false,
      why: 'Errada. O problema está no padrão de escalada, exposição e vinculação, não na existência de meta.' },
    { t: 'A divulgação comparativa de desempenho individual não tem repercussão em saúde.', ok: false,
      why: 'Errada. É elemento agravante reconhecido.' },
    { t: 'A remuneração variável não interfere na organização do trabalho.', ok: false,
      why: 'Errada. Molda ritmo, pausas e disposição a assumir riscos.' },
    { t: 'Metas inatingíveis produzem apenas frustração, sem repercussão clínica.', ok: false,
      why: 'Errada. Associam-se a quadros ansiosos e depressivos documentados.' }
  ],
  comentario: 'Meta não adoece; o padrão adoece: escalada contínua, ranking exposto e salário atrelado ao resultado. E a remuneração variável muda ritmo e disposição a correr risco — o que aparece nos acidentes.',
  pegadinha: 'Defender que "meta faz parte de qualquer trabalho" desvia da discussão sobre escalada e exposição pública.',
  refs: ['NR-1 — fatores psicossociais', 'Siegrist', 'OIT'] },

{ id: 'q-4.8-120', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o reconhecimento previdenciário de neoplasia relacionada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A dificuldade prática do reconhecimento decorre da latência longa, da perda de registros de exposição e da multicausalidade — e não da ausência de previsão normativa, já que diversas associações constam da lista de doenças relacionadas ao trabalho.', ok: true,
      why: 'Correta. O obstáculo é probatório, não normativo.' },
    { t: 'Neoplasias não constam da lista de doenças relacionadas ao trabalho.', ok: false,
      why: 'Errada. Diversas associações entre agentes e neoplasias constam expressamente.' },
    { t: 'A latência longa impede juridicamente o reconhecimento.', ok: false,
      why: 'Errada. Dificulta a prova, mas não impede o reconhecimento.' },
    { t: 'A multicausalidade afasta o nexo em neoplasias.', ok: false,
      why: 'Errada. Contribuição relevante basta, como em qualquer doença multicausal.' },
    { t: 'A ausência de registros de exposição inviabiliza qualquer reconhecimento.', ok: false,
      why: 'Errada. A história ocupacional e outros elementos podem sustentar a análise.' }
  ],
  comentario: 'Câncer ocupacional tem previsão normativa; o que falta é prova — registros perdidos, décadas decorridas, várias causas em jogo. Nada disso impede o reconhecimento, mas tudo isso o dificulta.',
  pegadinha: 'Concluir pela ausência de previsão normativa quando o obstáculo real é probatório encerra a discussão no lugar errado.',
  refs: ['Decreto nº 3.048/1999 — Anexo II', 'IARC', 'INCA'] },

{ id: 'q-4.9-110', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre doenças infecciosas em trabalhadores que viajam a serviço, é CORRETO afirmar:',
  alts: [
    { t: 'A orientação pré-viagem — imunizações indicadas para o destino, profilaxias, cuidados com água e alimentos e proteção contra vetores — integra o cuidado ocupacional, e a doença adquirida em viagem a serviço pode ter relação com o trabalho.', ok: true,
      why: 'Correta. Deslocamento a serviço é exposição decorrente do trabalho.' },
    { t: 'Doenças adquiridas em viagem a serviço não guardam relação com o trabalho.', ok: false,
      why: 'Errada. A exposição decorre do deslocamento determinado pelo trabalho.' },
    { t: 'A orientação pré-viagem é responsabilidade exclusiva do trabalhador.', ok: false,
      why: 'Errada. Integra o cuidado ocupacional quando o deslocamento é a serviço.' },
    { t: 'Vacinas indicadas para destinos específicos não são custeadas pelo empregador.', ok: false,
      why: 'Errada. Sendo medida de proteção decorrente do trabalho, são custeadas por ele.' },
    { t: 'A avaliação no retorno da viagem é desnecessária.', ok: false,
      why: 'Errada. É oportunidade de identificar quadros de incubação prolongada.' }
  ],
  comentario: 'Viagem a serviço é exposição ocupacional: orientação e vacinas antes, custeadas pelo empregador, e avaliação no retorno para os quadros de incubação longa. Doença adquirida ali pode ter nexo.',
  pegadinha: 'Tratar a orientação pré-viagem como assunto pessoal deixa sem cobertura uma exposição criada pelo trabalho.',
  refs: ['Ministério da Saúde — saúde do viajante', 'NR-7'] },

{ id: 'q-4.10-110', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre campanhas de vacinação conduzidas no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Devem observar as mesmas exigências técnicas de qualquer ato vacinal — avaliação de contraindicações, condições de conservação do imunobiológico, registro e capacidade de atendimento a eventos adversos imediatos —, não sendo evento meramente administrativo.', ok: true,
      why: 'Correta. Vacinar no refeitório não reduz nenhuma exigência técnica.' },
    { t: 'Campanhas no local de trabalho dispensam avaliação individual de contraindicações.', ok: false,
      why: 'Errada. A avaliação é exigência de qualquer ato vacinal.' },
    { t: 'A conservação do imunobiológico é preocupação apenas do fornecedor.', ok: false,
      why: 'Errada. A cadeia de frio deve ser assegurada até o momento da aplicação.' },
    { t: 'Não é necessário prever atendimento a eventos adversos imediatos.', ok: false,
      why: 'Errada. A capacidade de atender reação imediata é requisito.' },
    { t: 'O registro individual das doses aplicadas é dispensável em campanhas.', ok: false,
      why: 'Errada. O registro é o que permite continuidade e conduta futura.' }
  ],
  comentario: 'Campanha no trabalho é ato vacinal completo: contraindicações avaliadas, cadeia de frio mantida, registro individual e estrutura para reação imediata. Conveniência de local não altera requisito técnico.',
  pegadinha: 'Organizar a campanha como logística e não como ato de saúde é o que produz falha de conservação e registro.',
  refs: ['Programa Nacional de Imunizações', 'NR-7', 'Resoluções sanitárias sobre vacinação'] },

{ id: 'q-4.7-120', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do serviço de saúde ocupacional após evento crítico que afeta uma equipe, é CORRETO afirmar:',
  alts: [
    { t: 'A resposta envolve acolhimento coletivo e individual, identificação de quem apresenta maior risco, encaminhamento com continuidade e acompanhamento ao longo das semanas seguintes — evitando tanto a ausência de resposta quanto intervenções únicas e obrigatórias sem seguimento.', ok: true,
      why: 'Correta. Sessão única obrigatória logo após o evento não é a intervenção recomendada.' },
    { t: 'A intervenção deve consistir em sessão única obrigatória de relato detalhado do ocorrido.', ok: false,
      why: 'Errada. Intervenção única e obrigatória com reexposição detalhada não é recomendada.' },
    { t: 'A ausência de reação imediata dispensa qualquer acompanhamento posterior.', ok: false,
      why: 'Errada. Manifestações tardias são frequentes.' },
    { t: 'O acompanhamento deve se restringir a quem presenciou diretamente o evento.', ok: false,
      why: 'Errada. Colegas próximos e quem prestou socorro também são afetados.' },
    { t: 'A resposta organizacional ao evento não influencia o desfecho da equipe.', ok: false,
      why: 'Errada. É um dos principais determinantes da evolução do grupo.' }
  ],
  comentario: 'Após evento crítico: acolher, identificar quem está em maior risco, encaminhar com continuidade e acompanhar por semanas. Sessão obrigatória única com relato detalhado não é o que a evidência recomenda.',
  pegadinha: 'A intervenção de sessão única com reexposição detalhada parece cuidado imediato e não é a conduta indicada.',
  refs: ['OMS — primeiros cuidados psicológicos', 'Ministério da Saúde'] },

{ id: 'q-5.2-100', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do médico assistente na caracterização de doença relacionada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Ele pode e deve registrar a suspeita de relação com o trabalho, emitir a comunicação de acidente quando cabível e notificar o agravo — atribuições que não dependem de ser médico do trabalho nem de reconhecimento prévio pela previdência.', ok: true,
      why: 'Correta. O assistente é legitimado para a comunicação e obrigado à notificação.' },
    { t: 'A caracterização da relação com o trabalho é exclusiva do médico do trabalho.', ok: false,
      why: 'Errada. Qualquer médico pode e deve registrar a suspeita e notificar.' },
    { t: 'O médico assistente não é legitimado a emitir a comunicação de acidente.', ok: false,
      why: 'Errada. Consta expressamente entre os legitimados.' },
    { t: 'A notificação depende do reconhecimento prévio do nexo pela previdência.', ok: false,
      why: 'Errada. É ato de vigilância baseado em suspeita.' },
    { t: 'O registro da ocupação no prontuário é informação sem utilidade prática.', ok: false,
      why: 'Errada. É o que permite suspeitar e o que sustenta a investigação posterior.' }
  ],
  comentario: 'O assistente é peça central: registra a ocupação, levanta a suspeita, emite a comunicação de acidente e notifica. Nada disso exige ser médico do trabalho nem esperar decisão previdenciária.',
  pegadinha: 'Delegar tudo ao médico do trabalho faz o caso passar pela consulta sem qualquer registro de relação com o trabalho.',
  refs: ['Lei nº 8.213/1991 — art. 22', 'Portaria de notificação compulsória', 'Código de Ética Médica'] },

{ id: 'q-5.3-110', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausa e o agravamento de condição preexistente por acidente do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O acidente que agrava condição prévia e resulta em incapacidade maior do que a que existiria isoladamente configura relação com o trabalho quanto ao agravamento — e a preexistência não reduz nem fraciona os efeitos do reconhecimento.', ok: true,
      why: 'Correta. Reconhecido o agravamento, os efeitos são integrais.' },
    { t: 'A preexistência da condição afasta a relação com o acidente.', ok: false,
      why: 'Errada. O agravamento é hipótese expressa de concausa.' },
    { t: 'Os efeitos do reconhecimento são reduzidos proporcionalmente à condição prévia.', ok: false,
      why: 'Errada. Não há previsão de fracionamento.' },
    { t: 'A omissão da condição prévia na admissão impede o reconhecimento.', ok: false,
      why: 'Errada. O reconhecimento depende do agravamento demonstrado, não do histórico de declaração.' },
    { t: 'O agravamento só é reconhecido quando a condição prévia era assintomática.', ok: false,
      why: 'Errada. Condição prévia sintomática também pode ser agravada pelo evento.' }
  ],
  comentario: 'Acidente que piora condição prévia gera nexo quanto ao agravamento, com efeitos integrais e sem fracionamento. Nem a preexistência sintomática nem a ausência de declaração na admissão afastam isso.',
  pegadinha: 'A omissão no exame admissional é frequentemente invocada e não é o critério que decide o agravamento.',
  refs: ['Lei nº 8.213/1991 — art. 21, I', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.4-130', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a conduta do perito diante de periciando que apresenta agravamento voluntário ou simulação de sintomas, é CORRETO afirmar:',
  alts: [
    { t: 'A conclusão exige fundamentação em inconsistências objetivas e documentadas entre relato, exame, história e funcionalidade observada — não bastando impressão subjetiva do examinador, dado o peso da acusação implícita nessa conclusão.', ok: true,
      why: 'Correta. É a conclusão de maior carga acusatória e a que mais exige demonstração.' },
    { t: 'A impressão clínica do perito é fundamentação suficiente para essa conclusão.', ok: false,
      why: 'Errada. Exige-se demonstração de inconsistências objetivas.' },
    { t: 'Sintomas desproporcionais aos achados objetivos comprovam simulação.', ok: false,
      why: 'Errada. Ocorrem em quadros legítimos, especialmente de dor crônica.' },
    { t: 'A conclusão por simulação não tem repercussões relevantes para o periciando.', ok: false,
      why: 'Errada. Tem repercussões graves, inclusive em outras esferas.' },
    { t: 'A ausência de achado em exame complementar demonstra ausência do quadro relatado.', ok: false,
      why: 'Errada. Muitos quadros legítimos não têm tradução em exames complementares.' }
  ],
  comentario: 'Concluir por simulação é acusar, e por isso exige inconsistências objetivas e documentadas — não impressão. Desproporção entre queixa e achado ocorre em quadros legítimos, sobretudo de dor crônica.',
  pegadinha: 'Transformar desproporção entre sintoma e exame em conclusão de simulação penaliza quadros reais e frequentes.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-5.5-120', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a documentação da avaliação funcional em prontuário e relatórios, é CORRETO afirmar:',
  alts: [
    { t: 'Descrições funcionais devem ser específicas e verificáveis — indicando o que a pessoa consegue executar, por quanto tempo e com que limitação —, pois expressões genéricas não orientam alocação, não sustentam conclusão pericial e não permitem acompanhar evolução.', ok: true,
      why: 'Correta. Descrição genérica não serve a nenhum dos três usos.' },
    { t: 'Expressões genéricas sobre limitação são suficientes para orientar a alocação.', ok: false,
      why: 'Errada. Não indicam o que pode ou não ser feito na prática.' },
    { t: 'A descrição funcional é dispensável quando o diagnóstico é claro.', ok: false,
      why: 'Errada. O diagnóstico não descreve a funcionalidade.' },
    { t: 'A evolução funcional não precisa ser registrada em atendimentos sucessivos.', ok: false,
      why: 'Errada. É o registro seriado que demonstra melhora, estabilização ou piora.' },
    { t: 'Relatórios funcionais devem incluir o diagnóstico para serem aceitos pela empresa.', ok: false,
      why: 'Errada. À empresa cabe a limitação funcional; o diagnóstico permanece sob sigilo.' }
  ],
  comentario: 'Descrição funcional útil é específica: o que faz, por quanto tempo, com que limite — registrada de forma seriada. "Evitar esforços" não aloca ninguém, não sustenta perícia e não mostra evolução.',
  pegadinha: 'A expressão genérica parece proteger e na prática impede alocação, conclusão e acompanhamento.',
  refs: ['CIF — OMS', 'Resoluções do CFM sobre prontuário'] },

{ id: 'q-5.6-110', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as barreiras à reabilitação profissional bem-sucedida, é CORRETO afirmar:',
  alts: [
    { t: 'Baixa escolaridade, ausência de vagas compatíveis na região, resistência da empresa e afastamento prolongado figuram entre as principais barreiras — de natureza social e organizacional, e não apenas clínica, o que exige articulação além do campo médico.', ok: true,
      why: 'Correta. A maior parte das barreiras não é clínica.' },
    { t: 'As barreiras à reabilitação são predominantemente clínicas.', ok: false,
      why: 'Errada. Escolaridade, mercado local e resistência da empresa pesam mais.' },
    { t: 'A escolaridade do trabalhador não influencia as possibilidades de requalificação.', ok: false,
      why: 'Errada. Limita as alternativas de requalificação viáveis.' },
    { t: 'A disponibilidade de vagas na região não é fator relevante.', ok: false,
      why: 'Errada. Requalificar para função inexistente na região não recoloca ninguém.' },
    { t: 'O tempo de afastamento não influencia o sucesso da reabilitação.', ok: false,
      why: 'Errada. Afastamento prolongado reduz a probabilidade de retorno.' }
  ],
  comentario: 'O que trava a reabilitação raramente é clínico: escolaridade, mercado local, resistência da empresa e tempo de afastamento. Por isso a articulação precisa ir além do consultório.',
  pegadinha: 'Tratar o insucesso da reabilitação como problema clínico ignora as barreiras que efetivamente o produzem.',
  refs: ['Lei nº 8.213/1991 — arts. 89 a 93', 'Literatura sobre retorno ao trabalho'] }

);
