/* Lote C — 5.2, 5.4, 5.5, 4.3, 3.2. Questões AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-5.2-030', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa contesta administrativamente a aplicação do nexo epidemiológico a benefício concedido a empregado, alegando que adota todas as medidas de proteção previstas. Sobre o argumento, é CORRETO afirmar:',
  alts: [
    { t: 'A alegação genérica não basta: é preciso demonstrar no caso concreto a inexistência de relação.', ok: true,
      why: 'Correta. Exige elementos técnicos sobre a exposição real daquele trabalhador.' },
    { t: 'A apresentação dos documentos de saúde e segurança da empresa é suficiente para afastar o nexo.', ok: false,
      why: 'Errada. Documento genérico não descreve a exposição individual.' },
    { t: 'A alegação genérica não basta, sendo a presunção do nexo epidemiológico absoluta e incontestável.', ok: false,
      why: 'Errada. É presunção relativa, com via própria de contestação.' },
    { t: 'A alegação não basta, e afastado o nexo epidemiológico ficam afastadas as demais formas de nexo.', ok: false,
      why: 'Errada. O nexo individual e o técnico permanecem possíveis.' },
    { t: 'A alegação não basta, suspendendo a contestação automaticamente o benefício até a decisão final.', ok: false,
      why: 'Errada. A contestação não tem efeito suspensivo automático.' }
  ],
  comentario: 'Presunção relativa significa que se pode afastá-la — mas com prova concreta sobre aquele trabalhador. E mesmo afastado o epidemiológico, restam o nexo profissional e o individual, que seguem caminhos próprios.',
  pegadinha: 'Confundir conformidade documental com prova de ausência de exposição é a defesa padrão nessas contestações.',
  refs: ['Lei nº 8.213/1991 — art. 21-A', 'Decreto nº 3.048/1999'] },

{ id: 'q-5.2-031', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao aplicar a classificação de Schilling a um caso de asma em trabalhador de padaria exposto a farinha, é CORRETO afirmar:',
  alts: [
    { t: 'A sensibilização a agente exclusivo do trabalho torna o trabalho causa necessária da doença', ok: true,
      why: 'Correta. Sem a exposição a doença não existiria naquela forma.' },
    { t: 'Toda asma em trabalhador exposto se enquadra como doença comum agravada pelo trabalho exercido.', ok: false,
      why: 'Errada. Quando o agente é exclusivo do trabalho, ele é causa necessária.' },
    { t: 'A sensibilização caracteriza o quadro, não se aplicando a classificação a doenças respiratórias.', ok: false,
      why: 'Errada. Aplica-se a qualquer doença relacionada ao trabalho.' },
    { t: 'A sensibilização caracteriza o quadro, impedindo a atopia prévia o enquadramento ocupacional.', ok: false,
      why: 'Errada. Atopia é fator de suscetibilidade, não excludente.' },
    { t: 'A sensibilização caracteriza o quadro, sendo irrelevante a melhora nos períodos de férias.', ok: false,
      why: 'Errada. É justamente o padrão que sugere origem ocupacional.' }
  ],
  comentario: 'Distinção fina e muito cobrada: asma OCUPACIONAL, por sensibilização a agente do trabalho (Schilling I), versus asma preexistente AGRAVADA pelo trabalho (Schilling III). A pergunta é: sem essa exposição, existiria esse quadro?',
  pegadinha: 'Jogar toda asma em trabalhador no grupo de "doença comum agravada" apaga a asma ocupacional verdadeira.',
  refs: ['Diretriz AMB — Asma e Trabalho', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.4-050', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em perícia de acidente do trabalho, o perito precisa se manifestar sobre a existência de nexo entre o evento e a sequela apresentada. Sobre a metodologia, é CORRETO afirmar:',
  alts: [
    { t: 'Deve estabelecer compatibilidade entre mecanismo e lesão, temporalidade e análise documental.', ok: true,
      why: 'Correta. A documentação assistencial contemporânea é frequentemente decisiva.' },
    { t: 'Deve apoiar-se na documentação, cuja ausência impede qualquer conclusão sobre o nexo do caso.', ok: false,
      why: 'Errada. Outros elementos permitem a análise.' },
    { t: 'Deve considerar a temporalidade, sendo irrelevante a compatibilidade entre mecanismo e lesão.', ok: false,
      why: 'Errada. É um dos pilares do raciocínio pericial.' },
    { t: 'Deve seguir o relato do periciando sempre que não houver documentação técnica em sentido contrário.', ok: false,
      why: 'Errada. O relato se avalia criticamente junto dos demais elementos.' },
    { t: 'Deve estabelecer compatibilidade, não guardando nexo as sequelas de manifestação tardia.', ok: false,
      why: 'Errada. Manifestação tardia é compatível com vários mecanismos.' }
  ],
  comentario: 'Nexo em acidente: mecanismo compatível com a lesão, temporalidade e documentação contemporânea. Esta última costuma decidir — o que torna o registro no atendimento inicial um ato de enorme consequência futura.',
  pegadinha: 'Descartar sequela de manifestação tardia ignora quadros de instalação progressiva pós-traumática.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Tabela brasileira para apuração do dano corporal — ABMLPM'] },

{ id: 'q-5.4-051', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a perícia realizada por meio de análise documental, sem exame presencial do periciando, é CORRETO afirmar:',
  alts: [
    { t: 'É admissível em hipóteses específicas, com as limitações expressamente registradas no laudo.', ok: true,
      why: 'Correta. Não substitui o exame quando este é possível e necessário.' },
    { t: 'É admissível e tem o mesmo valor probatório da perícia com exame presencial em qualquer hipótese.', ok: false,
      why: 'Errada. Suas limitações são maiores e devem ser declaradas.' },
    { t: 'É modalidade vedada em qualquer circunstância, por não permitir o exame direto do periciando.', ok: false,
      why: 'Errada. É admissível em hipóteses específicas, como período pretérito.' },
    { t: 'É admissível em hipóteses específicas, sem que suas limitações precisem constar do laudo.', ok: false,
      why: 'Errada. O registro das limitações é condição de validade técnica.' },
    { t: 'É admissível, tornando-se dispensável o exame presencial quando há documentação abundante.', ok: false,
      why: 'Errada. Documentação não substitui o exame quando ele é possível.' }
  ],
  comentario: 'Perícia documental é recurso, não atalho. Cabe quando o exame é impossível ou quando se avalia período pretérito — e sempre com a limitação declarada. Volume de papel não substitui exame.',
  pegadinha: 'Equiparar as duas modalidades em valor probatório ignora o que o exame acrescenta.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-5.5-050', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador apresenta sequela de amputação de membro inferior e recebeu prótese com boa adaptação funcional. Sobre a avaliação da incapacidade, é CORRETO afirmar:',
  alts: [
    { t: 'Considera a funcionalidade com o dispositivo e as limitações remanescentes e a manutenção dele.', ok: true,
      why: 'Correta. A boa adaptação reduz, mas não elimina, a repercussão.' },
    { t: 'Considera a funcionalidade com o dispositivo, cessando a repercussão quando a prótese é bem adaptada.', ok: false,
      why: 'Errada. Restam limitações e a necessidade de manutenção e substituição.' },
    { t: 'Considera o dano, devendo a avaliação ser feita sem o dispositivo, para medir o prejuízo puro.', ok: false,
      why: 'Errada. A funcionalidade real se avalia com o dispositivo em uso.' },
    { t: 'Considera a funcionalidade com o dispositivo, sendo irrelevante a necessidade futura de substituição.', ok: false,
      why: 'Errada. Manutenção e troca compõem a repercussão ao longo do tempo.' },
    { t: 'Considera a funcionalidade com o dispositivo, implicando a amputação incapacidade omniprofissional.', ok: false,
      why: 'Errada. Muitas funções permanecem compatíveis.' }
  ],
  comentario: 'Avalie a funcionalidade COM o dispositivo — é assim que a pessoa vive — sem esquecer o que permanece limitado e a dependência de manutenção e substituição. Nem "com prótese está resolvido", nem "amputação é incapacidade total".',
  pegadinha: 'Avaliar sem o dispositivo mede um dano que não corresponde ao cotidiano do trabalhador.',
  refs: ['Tabela brasileira para apuração do dano corporal — ABMLPM', 'CIF'] },

{ id: 'q-5.5-051', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação de incapacidade em doenças de curso flutuante, como algumas condições reumatológicas e psiquiátricas, é CORRETO afirmar:',
  alts: [
    { t: 'A flutuação exige avaliar o padrão ao longo do tempo, e não só o estado no dia do exame.', ok: true,
      why: 'Correta. Frequência e duração das agudizações se confrontam com as exigências.' },
    { t: 'O estado clínico observado no dia do exame é suficiente para concluir sobre a capacidade laborativa.', ok: false,
      why: 'Errada. O curso flutuante exige avaliar o padrão ao longo do tempo.' },
    { t: 'A flutuação existe, não gerando incapacidade reconhecível as doenças de curso intermitente.', ok: false,
      why: 'Errada. Agudizações frequentes podem inviabilizar a atividade.' },
    { t: 'A flutuação exige avaliar o padrão, devendo o exame coincidir com período de agudização.', ok: false,
      why: 'Errada. Avalia-se o padrão, não o pior nem o melhor momento.' },
    { t: 'A flutuação exige avaliar o padrão, comprovando os períodos de remissão a inexistência da doença.', ok: false,
      why: 'Errada. Remissão é parte esperada do curso da doença.' }
  ],
  comentario: 'Em curso flutuante, o que importa é o padrão — frequência, duração e previsibilidade das crises — confrontado com as exigências da atividade. O dia do exame é uma amostra, não o retrato.',
  pegadinha: 'Concluir por capacidade em dia de remissão é o erro que gera alta pericial seguida de novo afastamento em semanas.',
  refs: ['Tabela brasileira para apuração do dano corporal — ABMLPM', 'Lei nº 8.213/1991'] },

{ id: 'q-4.3-030', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de aviário apresenta, após meses de atividade, tosse seca, dispneia e febre baixa recorrentes que melhoram nos fins de semana e recidivam no retorno. A tomografia mostra padrão de vidro fosco com nódulos centrolobulares. Sobre a hipótese, é CORRETO afirmar:',
  alts: [
    { t: 'Considerar pneumonite de hipersensibilidade, por antígenos orgânicos inalados, ligada à exposição.', ok: true,
      why: 'Correta. Evolui para fibrose se a exposição persistir; afastar o antígeno é central.' },
    { t: 'Considerar asma ocupacional, cuja imagem típica é vidro fosco com nódulos centrolobulares difusos.', ok: false,
      why: 'Errada. Esse padrão de imagem é da pneumonite de hipersensibilidade.' },
    { t: 'Considerar pneumonite, embora a melhora nos fins de semana afaste a origem ocupacional do quadro.', ok: false,
      why: 'Errada. É justamente o padrão que sugere origem ocupacional.' },
    { t: 'Considerar pneumonite, resumindo-se o tratamento a corticoide, mantida a mesma exposição.', ok: false,
      why: 'Errada. Sem afastar o antígeno o quadro progride para fibrose.' },
    { t: 'Considerar outra causa, pois a pneumonite não se relaciona a exposição ocupacional a material orgânico.', ok: false,
      why: 'Errada. É doença ocupacional clássica em várias atividades.' }
  ],
  comentario: 'Pneumonite de hipersensibilidade: antígeno orgânico, quadro que melhora no afastamento e recidiva no retorno, imagem com vidro fosco e nódulos centrolobulares, e progressão para fibrose se a exposição continuar. Afastar o antígeno é o tratamento.',
  pegadinha: 'Confundir com asma ocupacional troca o mecanismo, a imagem e a conduta.',
  refs: ['Santos, U.P. — Pneumologia Ocupacional', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-4.3-031', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a espirometria no acompanhamento de trabalhadores expostos a poeiras, é CORRETO afirmar:',
  alts: [
    { t: 'Complementa a avaliação, mas pode estar normal nas fases iniciais de uma pneumoconiose', ok: true,
      why: 'Correta. O diagnóstico se apoia na história de exposição e na imagem.' },
    { t: 'Complementa a avaliação, excluindo a espirometria normal o diagnóstico de pneumoconiose.', ok: false,
      why: 'Errada. Pode estar normal em fases iniciais da doença.' },
    { t: 'É o exame de escolha para o diagnóstico de pneumoconiose nos trabalhadores expostos a poeira.', ok: false,
      why: 'Errada. O diagnóstico se apoia na exposição e na imagem.' },
    { t: 'Complementa a avaliação, afastando o padrão obstrutivo em exposto a poeira a relação ocupacional.', ok: false,
      why: 'Errada. Há quadros obstrutivos ocupacionais por poeiras e irritantes.' },
    { t: 'Complementa a avaliação, sem que a qualidade técnica do exame influencie sua interpretação.', ok: false,
      why: 'Errada. Manobra inadequada invalida o resultado.' }
  ],
  comentario: 'Divisão de papéis: história ocupacional e imagem diagnosticam a pneumoconiose; espirometria mede a repercussão funcional, que pode vir depois. Normal não exclui — e a qualidade técnica do exame é condição de interpretação.',
  pegadinha: 'Usar espirometria normal para excluir pneumoconiose troca o exame de repercussão pelo exame de diagnóstico.',
  refs: ['Santos, U.P. — Pneumologia Ocupacional', 'NR-7'] },

{ id: 'q-3.2-040', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa de logística implanta sistema de metas individuais medidas em tempo real, com ranking visível e alertas automáticos quando o trabalhador fica abaixo do ritmo esperado. Sobre a organização do trabalho descrita, é CORRETO afirmar:',
  alts: [
    { t: 'O monitoramento contínuo com ritmo imposto reduz a autonomia e a regulação da própria atividade', ok: true,
      why: 'Correta. É fator de risco psicossocial e ergonômico que integra o inventário.' },
    { t: 'Os sistemas de medição em tempo real são neutros, pois apenas registram o desempenho realizado.', ok: false,
      why: 'Errada. O ritmo imposto e a exposição do desempenho têm efeito documentado.' },
    { t: 'O monitoramento reduz a autonomia, sendo o ranking visível medida motivacional sem efeito em saúde.', ok: false,
      why: 'Errada. É elemento agravante reconhecido de sofrimento psíquico.' },
    { t: 'O monitoramento reduz a autonomia, não integrando esses riscos o inventário de riscos da empresa.', ok: false,
      why: 'Errada. Fatores psicossociais integram expressamente o inventário.' },
    { t: 'O monitoramento reduz a autonomia, neutralizando as pausas previstas integralmente esse efeito.', ok: false,
      why: 'Errada. Pausas não compensam ritmo imposto e perda de autonomia.' }
  ],
  comentario: 'Gestão algorítmica do ritmo é o risco psicossocial contemporâneo: mede tudo, alerta em tempo real e elimina a margem de regulação. Entra no inventário de riscos como qualquer outro fator.',
  pegadinha: 'A alegação de neutralidade do sistema — "ele só registra" — ignora que medir continuamente muda o trabalho medido.',
  refs: ['NR-17', 'NR-1', 'De Lucca — Fatores Psicossociais e Saúde Mental no Trabalho'] },

{ id: 'q-3.2-041', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a participação dos trabalhadores na análise ergonômica do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A verbalização durante a observação revela estratégias e dificuldades que a observação não capta.', ok: true,
      why: 'Correta. É componente metodológico, não cortesia.' },
    { t: 'A observação é o método central, comprometendo a participação do trabalhador a objetividade.', ok: false,
      why: 'Errada. A verbalização é fonte essencial de informação.' },
    { t: 'A verbalização é útil, bastando aplicar questionário e dispensando a observação da atividade.', ok: false,
      why: 'Errada. Observação e verbalização se complementam.' },
    { t: 'A verbalização é essencial, sendo dispensável a validação das recomendações com os trabalhadores.', ok: false,
      why: 'Errada. A validação é etapa do método e condição de aplicabilidade.' },
    { t: 'A verbalização é essencial, encerrando-se a análise ergonômica na entrega do relatório final.', ok: false,
      why: 'Errada. A finalidade do método é transformar a situação de trabalho.' }
  ],
  comentario: 'Verbalização é método, não gentileza: é ela que revela por que o trabalho real difere do prescrito. E a análise só termina quando a situação muda — relatório entregue e nada alterado é análise inacabada.',
  pegadinha: 'Tratar a participação como ameaça à objetividade elimina a única fonte sobre a atividade real.',
  refs: ['NR-17', 'Couto — Ergonomia'] }

);
