/* Lote AR — 7.1 a 7.8, 1.3 a 1.10. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.2-120', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o encaminhamento de segurado para avaliação de aposentadoria por incapacidade permanente, é CORRETO afirmar:',
  alts: [
    { t: 'Pressupõe incapacidade insuscetível de reabilitação, e o segurado segue sujeito a reavaliações.', ok: true,
      why: 'Correta. Há previsão de reavaliação periódica, com exceções etárias.' },
    { t: 'Pressupõe incapacidade insuscetível de reabilitação, encerrando a concessão qualquer reavaliação.', ok: false,
      why: 'Errada. Há previsão de reavaliação periódica, com dispensa em situações específicas.' },
    { t: 'Pressupõe incapacidade para a função habitual, o que basta para a concessão do benefício.', ok: false,
      why: 'Errada. Exige-se incapacidade insuscetível de reabilitação para atividade que garanta subsistência.' },
    { t: 'Pressupõe incapacidade permanente, sendo irrelevante para a análise a tentativa de reabilitação.', ok: false,
      why: 'Errada. A insuscetibilidade de reabilitação é elemento do próprio conceito.' },
    { t: 'Pressupõe incapacidade insuscetível de reabilitação, sem que o retorno voluntário repercuta nele.', ok: false,
      why: 'Errada. Tem repercussão prevista sobre a manutenção do benefício.' }
  ],
  comentario: 'Aposentadoria por incapacidade permanente exige insuscetibilidade de reabilitação para atividade que garanta subsistência — não basta não poder exercer a função habitual. E há reavaliação periódica, com dispensas específicas.',
  pegadinha: 'Confundir incapacidade para a função com incapacidade para qualquer atividade antecipa uma exclusão definitiva.',
  refs: ['Lei nº 8.213/1991 — arts. 42 a 47', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-121', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a manutenção da qualidade de segurado e seus reflexos no acesso a benefícios, é CORRETO afirmar:',
  alts: [
    { t: 'Há período em que ele mantém a qualidade de segurado sem contribuir, com prazos variáveis.', ok: true,
      why: 'Correta. É o que decide o acesso quando a doença se manifesta depois do desligamento.' },
    { t: 'A qualidade de segurado cessa imediatamente com o fim das contribuições ao regime previdenciário.', ok: false,
      why: 'Errada. Há período de manutenção previsto em lei.' },
    { t: 'Há período de manutenção da qualidade de segurado, igual para todos os segurados do regime.', ok: false,
      why: 'Errada. Varia conforme o tempo de contribuição e a comprovação de desemprego.' },
    { t: 'Há período de manutenção, sem influência sobre o acesso a benefício por doença ocupacional.', ok: false,
      why: 'Errada. É determinante quando a manifestação ocorre após o desligamento.' },
    { t: 'Há período de manutenção com prazos definidos, que a comprovação de desemprego não altera.', ok: false,
      why: 'Errada. Pode ampliar o período previsto.' }
  ],
  comentario: 'Período de graça: mantém a qualidade de segurado sem contribuir, com prazo variável por tempo de contribuição e desemprego comprovado. É o que decide o acesso quando a doença ocupacional aparece meses após a saída.',
  pegadinha: 'Supor perda imediata da qualidade de segurado ao desligamento fecha o acesso que a lei mantém aberto.',
  refs: ['Lei nº 8.213/1991 — art. 15', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.3-120', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação sanitária em situações de contaminação que atingem trabalhadores e comunidade, é CORRETO afirmar:',
  alts: [
    { t: 'Deve mapear a fonte, as vias e as populações atingidas, com comunicação de risco aos envolvidos', ok: true,
      why: 'Correta. Quem trabalha na fonte recebe a maior dose e é prioritário na avaliação.' },
    { t: 'Deve mapear a fonte e restringir-se à população residente do entorno afetado pela contaminação.', ok: false,
      why: 'Errada. Os trabalhadores da fonte são o grupo de maior exposição.' },
    { t: 'Deve mapear fonte e vias de exposição, sendo dispensável a comunicação de risco às populações.', ok: false,
      why: 'Errada. É componente essencial da resposta sanitária.' },
    { t: 'Deve mapear a fonte e as populações, sem que identificar as vias altere as medidas adotadas.', ok: false,
      why: 'Errada. Define quais medidas interrompem efetivamente a exposição.' },
    { t: 'Deve mapear as populações atingidas, excluídos os trabalhadores contratados temporariamente.', ok: false,
      why: 'Errada. A avaliação alcança todos os expostos, independentemente do vínculo.' }
  ],
  comentario: 'Em contaminação, o trabalhador é o mais exposto e o primeiro a avaliar — inclusive o temporário. Mapear fonte e vias define as medidas, e comunicar risco é parte da resposta, não sua consequência.',
  pegadinha: 'Investigar só a comunidade do entorno deixa de fora quem esteve mais perto da fonte por mais tempo.',
  refs: ['Lei nº 8.080/1990', 'PNSTT', 'Vigilância em saúde ambiental'] },

{ id: 'q-7.4-120', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as condições sanitárias e de conforto nos locais de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Sanitários, vestiários, local para refeição e água potável têm repercussão direta sobre a saúde', ok: true,
      why: 'Correta. Banheiro distante e sujo faz o trabalhador beber menos água.' },
    { t: 'São exigências de conforto do ambiente laboral, sem repercussão clínica sobre os trabalhadores.', ok: false,
      why: 'Errada. Têm repercussão clínica documentada.' },
    { t: 'São exigências com repercussão, podendo a água potável ser substituída pela que cada um traz.', ok: false,
      why: 'Errada. O fornecimento é obrigação do empregador.' },
    { t: 'São exigências com repercussão, sem relevância a distância das instalações sanitárias ao posto.', ok: false,
      why: 'Errada. Distância e tempo de deslocamento influenciam diretamente o uso.' },
    { t: 'São exigências, não integrando os vestiários com separação adequada quando há poucos trabalhadores.', ok: false,
      why: 'Errada. A exigência independe do número, com dimensionamento proporcional.' }
  ],
  comentario: 'Banheiro, vestiário, refeitório e água potável não são conforto: banheiro distante e sujo produz restrição hídrica e retenção urinária. São exigências com desfecho clínico.',
  pegadinha: 'Classificar essas condições como conforto retira do escopo de saúde algo que produz infecção urinária e cálculo renal.',
  refs: ['NR-24', 'NR-18', 'NR-31'] },

{ id: 'q-7.5-090', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a implantação dos eventos de saúde e segurança no eSocial nas empresas, é CORRETO afirmar:',
  alts: [
    { t: 'Exige integração entre pessoal, segurança e medicina, com definição de responsáveis e de fluxos', ok: true,
      why: 'Correta. Quem opera o sistema não é quem detém a informação técnica.' },
    { t: 'Exige coordenação da área de tecnologia da informação, responsável exclusiva pela implantação.', ok: false,
      why: 'Errada. Exige participação das áreas que produzem a informação.' },
    { t: 'Exige integração entre as áreas, podendo o conteúdo técnico ser preenchido por qualquer setor.', ok: false,
      why: 'Errada. É a principal causa de inconsistência nos eventos transmitidos.' },
    { t: 'Exige integração, sendo a definição de responsáveis pelos eventos formalidade sem efeito prático.', ok: false,
      why: 'Errada. Define quem responde pela informação e quem acompanha prazos.' },
    { t: 'Exige integração e fluxos, sem necessidade de conferir a consistência com os documentos internos.', ok: false,
      why: 'Errada. A conferência é o que evita divergência detectável por cruzamento.' }
  ],
  comentario: 'Implantar os eventos exige integração entre pessoal, segurança e medicina, com responsáveis definidos e conferência contra os documentos internos. Delegar o conteúdo técnico a quem opera o sistema produz inconsistência.',
  pegadinha: 'Tratar a implantação como projeto de sistema deixa quem produz a informação fora do processo.',
  refs: ['eSocial — manual de orientação', 'NR-1', 'NR-7'] },

{ id: 'q-7.6-090', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de achados de exame ao trabalhador examinado, é CORRETO afirmar:',
  alts: [
    { t: 'Tem direito de conhecer os resultados e receber orientação, mesmo sem efeito sobre a aptidão.', ok: true,
      why: 'Correta. O achado que não muda a aptidão ainda é informação de saúde da pessoa.' },
    { t: 'Tem direito aos resultados relevantes, não sendo comunicados os achados que não afetam a aptidão.', ok: false,
      why: 'Errada. O trabalhador tem direito de conhecer sua condição de saúde.' },
    { t: 'Tem direito aos resultados, podendo a comunicação ser feita por meio do setor de pessoal.', ok: false,
      why: 'Errada. É comunicação médica, direta ao trabalhador.' },
    { t: 'Tem direito aos resultados, não integrando o encaminhamento para assistência a responsabilidade médica.', ok: false,
      why: 'Errada. Identificado o achado, o encaminhamento é parte do cuidado.' },
    { t: 'Tem direito de conhecer os resultados, sem direito a cópia dos exames que realizou.', ok: false,
      why: 'Errada. Tem direito de acesso aos próprios dados de saúde.' }
  ],
  comentario: 'Achado encontrado é informado ao trabalhador, com orientação e encaminhamento — mesmo quando não altera a aptidão. E a comunicação é médica e direta, não pelo setor de pessoal.',
  pegadinha: 'Guardar o achado irrelevante para a aptidão retira da pessoa uma informação que é dela.',
  refs: ['Código de Ética Médica', 'NR-7', 'LGPD'] },

{ id: 'q-7.7-090', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação simultânea do médico como assistente e como perito do mesmo paciente, é CORRETO afirmar:',
  alts: [
    { t: 'É vedado periciar paciente de quem se é ou foi assistente, por incompatibilidade de funções.', ok: true,
      why: 'Correta. Protege tanto a relação assistencial quanto a imparcialidade do ato pericial.' },
    { t: 'É vedado periciar o próprio paciente, salvo quando ele manifesta concordância expressa com o ato.', ok: false,
      why: 'Errada. A vedação não é afastada por concordância do periciando.' },
    { t: 'É vedado periciar o próprio paciente, aplicando-se a vedação apenas à assistência atual em curso.', ok: false,
      why: 'Errada. Alcança também quem foi assistente do periciando.' },
    { t: 'É vedado periciar o próprio paciente, vedação que decorre do risco de favorecê-lo na conclusão.', ok: false,
      why: 'Errada. Protege também a relação assistencial, comprometida pela função pericial.' },
    { t: 'É vedado ao perito judicial, sem restrição ao médico da empresa que pericia quem ele atende.', ok: false,
      why: 'Errada. O conflito de papéis exige atenção e, conforme a situação, impedimento.' }
  ],
  comentario: 'Assistente e perito do mesmo paciente é incompatível — inclusive quando a assistência foi passada, e mesmo com concordância dele. A vedação protege as duas relações, não apenas a imparcialidade.',
  pegadinha: 'Achar que o consentimento do periciando resolve o conflito ignora que a vedação não é disponível.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-7.8-090', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o encarregado de proteção de dados e a governança em serviços de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Deve indicar canal com os titulares, definir acesso e retenção e treinar quem manuseia os dados', ok: true,
      why: 'Correta. A governança de dados não pode abrir o que o sigilo médico fecha.' },
    { t: 'Deve definir políticas de acesso amplo aos dados de saúde para viabilizar auditorias internas.', ok: false,
      why: 'Errada. O sigilo profissional restringe o acesso mesmo internamente.' },
    { t: 'Deve definir acesso e retenção, sendo facultativa a indicação de canal de comunicação com titulares.', ok: false,
      why: 'Errada. É requisito para o exercício dos direitos do titular.' },
    { t: 'Deve indicar canal e treinar equipes, não se aplicando políticas de retenção a dados de saúde.', ok: false,
      why: 'Errada. Aplicam-se, respeitados os prazos legais de guarda, longos nesse campo.' },
    { t: 'Deve indicar canal e definir políticas, sendo o treinamento de quem manuseia sem efeito prático.', ok: false,
      why: 'Errada. Boa parte dos incidentes decorre de manuseio por pessoas não treinadas.' }
  ],
  comentario: 'Governança de dados em saúde ocupacional convive com o sigilo profissional: canal para titulares, políticas de acesso e retenção com prazos longos, e treinamento — sem abrir acesso interno a quem o sigilo exclui.',
  pegadinha: 'Justificar acesso interno amplo por "governança" ou "auditoria" contorna o sigilo pela via administrativa.',
  refs: ['LGPD — arts. 41 e 46', 'Código de Ética Médica'] },

{ id: 'q-7.1-110', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o afastamento por doença e a responsabilidade pelo pagamento nos primeiros dias, é CORRETO afirmar:',
  alts: [
    { t: 'Os primeiros quinze dias de afastamento cabem ao empregador e o período seguinte cabe à previdência', ok: true,
      why: 'Correta. Daí vem boa parte da fricção em torno de atestados de poucos dias.' },
    { t: 'A previdência arca com o afastamento por incapacidade desde o primeiro dia, em qualquer hipótese.', ok: false,
      why: 'Errada. Há período inicial de responsabilidade do empregador.' },
    { t: 'Os primeiros dias cabem ao empregador, sem efeito dessa regra sobre a aceitação de atestados.', ok: false,
      why: 'Errada. Cria incentivo econômico à contestação de afastamentos curtos.' },
    { t: 'Os primeiros dias cabem ao empregador, tratando-se afastamentos sucessivos como eventos independentes.', ok: false,
      why: 'Errada. Há regras específicas para afastamentos sucessivos em curto intervalo.' },
    { t: 'Os primeiros dias cabem ao empregador, cabendo ao médico considerar esse impacto ao definir o prazo.', ok: false,
      why: 'Errada. A definição é técnica e não se modula por conveniência econômica.' }
  ],
  comentario: 'Os primeiros dias são do empregador, o restante da previdência — e é dessa regra que nasce a pressão sobre atestados curtos. A definição do tempo de afastamento, porém, é técnica e não financeira.',
  pegadinha: 'Ajustar o tempo de afastamento ao impacto financeiro da empresa converte decisão clínica em decisão contábil.',
  refs: ['Lei nº 8.213/1991 — art. 60', 'CLT'] },

{ id: 'q-1.3-130', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a leitura crítica de um estudo que sustenta associação entre exposição ocupacional e desfecho, é CORRETO afirmar:',
  alts: [
    { t: 'Considera delineamento, aferição da exposição, confundimento, magnitude, precisão e coerência externa', ok: true,
      why: 'Correta. Corpo de evidência, não estudo único: nenhum estudo isolado encerra a questão.' },
    { t: 'Considera o delineamento e a magnitude, bastando um estudo bem conduzido para estabelecer causalidade.', ok: false,
      why: 'Errada. A causalidade se sustenta em conjunto de evidências.' },
    { t: 'Considera delineamento e confundimento, sendo a aferição da exposição detalhe de pouca relevância.', ok: false,
      why: 'Errada. É frequentemente o ponto mais frágil dos estudos ocupacionais.' },
    { t: 'Considera magnitude e precisão, devendo associações de pequena magnitude ser descartadas de imediato.', ok: false,
      why: 'Errada. Podem ter grande impacto quando a exposição é frequente na população.' },
    { t: 'Considera delineamento e magnitude, sem que a coerência com o conhecimento prévio integre a análise.', ok: false,
      why: 'Errada. É um dos critérios clássicos de apreciação de causalidade.' }
  ],
  comentario: 'Ler criticamente é olhar delineamento, aferição da exposição, confundimento, magnitude, precisão e coerência — e lembrar que associação pequena com exposição muito frequente pode importar muito.',
  pegadinha: 'Descartar associação de pequena magnitude ignora que o impacto populacional depende também da prevalência da exposição.',
  refs: ['Rothman — Epidemiologia Moderna', 'Fletcher — Epidemiologia Clínica'] },

{ id: 'q-1.4-110', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a gestão de contratos de serviços de saúde ocupacional terceirizados, é CORRETO afirmar:',
  alts: [
    { t: 'Contratar por menor preço, sem especificar tempo e escopo, tende a gerar serviço só de documentos.', ok: true,
      why: 'Correta. Terceirizar a execução não terceiriza a obrigação da contratante.' },
    { t: 'Contratar prestadora transfere a ela a responsabilidade pelas obrigações de saúde e segurança.', ok: false,
      why: 'Errada. A contratante permanece responsável.' },
    { t: 'Contratar exige cuidado, sendo irrelevante a especificação de tempo por exame no contrato.', ok: false,
      why: 'Errada. Determina diretamente a qualidade do que é possível fazer no atendimento.' },
    { t: 'Contratar exige especificar o escopo, sem necessidade de constar a qualificação dos profissionais.', ok: false,
      why: 'Errada. É requisito que a contratante deve especificar e verificar.' },
    { t: 'Contratar exige cuidado, resumindo-se a avaliação da qualidade à conferência dos documentos entregues.', ok: false,
      why: 'Errada. Documento entregue não demonstra que o exame foi adequadamente realizado.' }
  ],
  comentario: 'Contrato por menor preço sem especificar tempo, qualificação e escopo compra emissão de documento. E a obrigação continua sendo da contratante — que precisa avaliar mais do que a entrega de papéis.',
  pegadinha: 'Medir a prestadora pelo volume de documentos entregues premia exatamente o que se quer evitar.',
  refs: ['NR-4', 'NR-7', 'NR-1'] },

{ id: 'q-1.6-110', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a saúde do trabalhador de plataformas digitais e do trabalho por aplicativo, é CORRETO afirmar:',
  alts: [
    { t: 'Acumulam risco de trânsito, jornadas longas, pressão algorítmica e ausência total de cobertura', ok: true,
      why: 'Correta. Alta exposição somada a ausência total de estrutura de proteção.' },
    { t: 'Acumulam riscos, embora a ausência de vínculo formal reduza a exposição a riscos ocupacionais.', ok: false,
      why: 'Errada. Reduz a proteção, não a exposição.' },
    { t: 'Acumulam risco de trânsito, sem que a pressão por tempo de resposta seja fator de risco relevante.', ok: false,
      why: 'Errada. Associa-se a comportamento de risco no trânsito e a sofrimento psíquico.' },
    { t: 'Acumulam riscos, sendo cobertos pelos programas ocupacionais mantidos pelas próprias plataformas.', ok: false,
      why: 'Errada. Em regra não há cobertura por serviços de medicina do trabalho.' },
    { t: 'Acumulam riscos de trânsito, não devendo seus acidentes ser objeto de notificação em saúde.', ok: false,
      why: 'Errada. A notificação independe do vínculo.' }
  ],
  comentario: 'Trabalho por aplicativo soma trânsito, jornada longa e pressão algorítmica a nenhuma cobertura ocupacional. É prioridade de vigilância no território — e seus acidentes são notificáveis como quaisquer outros.',
  pegadinha: 'Informalidade reduz proteção e não exposição; tratar as duas como equivalentes apaga o grupo das estatísticas.',
  refs: ['PNSTT', 'OIT — trabalho em plataformas digitais'] },

{ id: 'q-1.7-110', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a integração entre serviços de saúde ocupacional das empresas e a rede pública, é CORRETO afirmar:',
  alts: [
    { t: 'Melhora a continuidade do cuidado e a qualidade da informação nos dois lados, que a têm pela metade', ok: true,
      why: 'Correta. O serviço da empresa conhece a exposição; a rede pública conduz o tratamento.' },
    { t: 'Os dois sistemas devem operar de forma independente entre si para preservar o sigilo do trabalhador.', ok: false,
      why: 'Errada. A articulação é possível com autorização do trabalhador e preserva o sigilo.' },
    { t: 'Melhora a continuidade, embora o serviço da empresa não detenha informação útil ao tratamento.', ok: false,
      why: 'Errada. Detém a informação sobre exposição e exigências da função.' },
    { t: 'Melhora a continuidade, não devendo a rede pública considerar a ocupação na condução do caso.', ok: false,
      why: 'Errada. A ocupação é elemento diagnóstico e terapêutico relevante.' },
    { t: 'Melhora a continuidade, exigindo compartilhamento irrestrito de prontuários entre os serviços.', ok: false,
      why: 'Errada. O compartilhamento é limitado ao necessário e depende de autorização.' }
  ],
  comentario: 'Serviço da empresa sabe da exposição; a rede pública conduz o tratamento. Articular os dois, com autorização e no limite do necessário, evita dois atendimentos paralelos que nunca se encontram.',
  pegadinha: 'Invocar o sigilo para justificar a não comunicação transforma proteção em isolamento do cuidado.',
  refs: ['PNSTT', 'Código de Ética Médica', 'Lei nº 8.080/1990'] },

{ id: 'q-1.8-110', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de mapas de risco elaborados com participação dos trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Permitem visualizar coletivamente os riscos por setor, sem substituir a avaliação quantitativa.', ok: true,
      why: 'Correta. Complementa, aproxima e não mede.' },
    { t: 'Permitem visualizar os riscos por setor e substituem a avaliação quantitativa das exposições.', ok: false,
      why: 'Errada. Não fornece medição nem comparação com limites.' },
    { t: 'Permitem visualizar riscos e devem ser elaborados exclusivamente pela área técnica da empresa.', ok: false,
      why: 'Errada. A elaboração participativa é o que lhe dá valor pedagógico.' },
    { t: 'Permitem visualizar riscos internamente, sem utilidade para a vigilância em saúde do trabalhador.', ok: false,
      why: 'Errada. Revela a percepção de risco dos trabalhadores e orienta a investigação.' },
    { t: 'Permitem visualizar riscos, sem que a percepção dos trabalhadores conte na identificação de perigos.', ok: false,
      why: 'Errada. É fonte primária sobre condições que a inspeção pontual não capta.' }
  ],
  comentario: 'Mapa de risco vale pela construção coletiva: revela a percepção de quem trabalha e orienta onde investigar. Não mede nada — e por isso complementa, sem substituir, a avaliação técnica.',
  pegadinha: 'Elaborar o mapa apenas na área técnica descarta justamente a informação que o justifica.',
  refs: ['NR-5', 'PNSTT'] },

{ id: 'q-1.9-110', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o fluxo da informação após o preenchimento da ficha de notificação, é CORRETO afirmar:',
  alts: [
    { t: 'A ficha vai à vigilância municipal, que insere, consolida e encaminha aos níveis superiores.', ok: true,
      why: 'Correta. Fluxo ascendente de dados e descendente de análise sustenta a notificação.' },
    { t: 'A ficha é inserida diretamente na base federal pelo próprio serviço que identificou o caso.', ok: false,
      why: 'Errada. O fluxo passa pela vigilância municipal.' },
    { t: 'A ficha vai à vigilância municipal, cuja consolidação não agrega valor à informação notificada.', ok: false,
      why: 'Errada. É onde ocorrem a crítica dos dados e a articulação com a ação local.' },
    { t: 'A ficha percorre os três níveis, sendo dispensável o retorno da análise aos serviços notificadores.', ok: false,
      why: 'Errada. É determinante da adesão e da qualidade do preenchimento.' },
    { t: 'A ficha vai à vigilância municipal, sendo os campos incompletos corrigidos pelo próprio sistema.', ok: false,
      why: 'Errada. A correção depende de busca ativa da informação faltante.' }
  ],
  comentario: 'Fluxo: serviço notifica, vigilância municipal insere e critica, consolida-se para estado e federação — e a análise volta para quem notificou. Sem esse retorno, a notificação desanima e a qualidade cai.',
  pegadinha: 'Esperar que o sistema corrija campos em branco substitui busca ativa por otimismo.',
  refs: ['SINAN', 'Ministério da Saúde — fluxos de notificação'] },

{ id: 'q-1.10-110', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre programas de alimentação do trabalhador e sua relação com a saúde, é CORRETO afirmar:',
  alts: [
    { t: 'A oferta alimentar, o tempo real de refeição e as condições do local influenciam o padrão alimentar', ok: true,
      why: 'Correta. Não há escolha alimentar quando o intervalo real é de quinze minutos.' },
    { t: 'O padrão alimentar do trabalhador depende das escolhas individuais que ele faz durante a jornada.', ok: false,
      why: 'Errada. Oferta, tempo e local condicionam fortemente a escolha.' },
    { t: 'Oferta e local influenciam o padrão, sem que o tempo disponível altere a qualidade da alimentação.', ok: false,
      why: 'Errada. Intervalo curto favorece refeições rápidas e de pior composição.' },
    { t: 'Oferta e tempo influenciam o padrão, sem repercussão em saúde das condições do local de refeição.', ok: false,
      why: 'Errada. Local inadequado favorece comer no posto de trabalho.' },
    { t: 'Oferta e tempo influenciam, sem relação dos programas de alimentação com desfechos ocupacionais.', ok: false,
      why: 'Errada. Repercutem sobre estado nutricional, doenças crônicas e desempenho.' }
  ],
  comentario: 'Alimentação no trabalho depende do que se oferece, de quanto tempo se tem e de onde se come. Orientar hábito sem mexer nisso transfere ao trabalhador uma decisão que a organização já tomou por ele.',
  pegadinha: 'Palestra de nutrição para quem tem quinze minutos e uma máquina de salgados é orientação sem objeto.',
  refs: ['NR-24', 'Programa de Alimentação do Trabalhador', 'OMS'] },

{ id: 'q-1.5-110', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a gestão de mudanças em sistemas de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Processo, equipamento, layout, quadro de pessoal e organização exigem análise de risco prévia', ok: true,
      why: 'Correta. Mudança pequena sem análise é origem clássica de evento inesperado.' },
    { t: 'Apenas as mudanças de grande porte exigem análise prévia de risco antes de sua implementação.', ok: false,
      why: 'Errada. Mudanças pequenas frequentemente introduzem riscos não previstos.' },
    { t: 'Mudanças exigem análise prévia, não configurando alterações no quadro de pessoal mudança relevante.', ok: false,
      why: 'Errada. Alteram experiência disponível, ritmo e supervisão.' },
    { t: 'Mudanças exigem análise prévia, dispensando-a as temporárias em razão de sua curta duração.', ok: false,
      why: 'Errada. Arranjos temporários são situação de risco reconhecida.' },
    { t: 'Mudanças exigem análise, restrita ela aos aspectos técnicos do equipamento que será alterado.', ok: false,
      why: 'Errada. Alcança também organização do trabalho e interfaces entre equipes.' }
  ],
  comentario: 'Gestão de mudanças: processo, equipamento, layout, pessoal e organização — inclusive as pequenas e as temporárias, que são justamente onde o risco não previsto aparece.',
  pegadinha: 'O arranjo provisório "só até semana que vem" é a mudança que menos recebe análise e mais produz acidente.',
  refs: ['ISO 45001', 'NR-1'] }

);
