/* Lote AM — 1.4 a 1.10, 2.5, 2.8, 4.3, 4.7, 4.9, 5.2, 5.3, 5.6, 6.1, 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-100', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a implantação de um serviço de saúde ocupacional em empresa que nunca teve estrutura própria, é CORRETO afirmar:',
  alts: [
    { t: 'A prioridade inicial é conhecer os processos e os riscos reais, construindo o inventário antes de definir a rotina de exames — começar pelos exames sem conhecer os riscos produz um programa desconectado do que existe no chão de fábrica.', ok: true,
      why: 'Correta. O programa médico é consequência do inventário, não antecede a ele.' },
    { t: 'A prioridade é implantar imediatamente a rotina de exames periódicos.', ok: false,
      why: 'Errada. Sem conhecer os riscos, os exames escolhidos não correspondem à exposição.' },
    { t: 'O reconhecimento dos riscos pode ser feito integralmente por análise documental.', ok: false,
      why: 'Errada. Exige visita aos setores e observação do trabalho real.' },
    { t: 'A participação dos trabalhadores nessa etapa é dispensável.', ok: false,
      why: 'Errada. É a fonte mais direta sobre como o trabalho acontece.' },
    { t: 'A definição de indicadores deve ser deixada para depois de anos de operação.', ok: false,
      why: 'Errada. Sem linha de base inicial, não há como demonstrar evolução posteriormente.' }
  ],
  comentario: 'Implantar serviço começa por conhecer processo e risco — visitando, observando e ouvindo. Exame vem depois, derivado do inventário. E define-se linha de base logo, ou não haverá com o que comparar daqui a três anos.',
  pegadinha: 'Começar pela rotina de exames entrega produção visível e um programa que não corresponde aos riscos reais.',
  refs: ['NR-1', 'NR-7', 'NR-4'] },

{ id: 'q-1.5-100', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a melhoria contínua em sistemas de gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'O ciclo de planejar, executar, verificar e agir exige que a etapa de verificação produza consequências reais — sistemas que verificam e não corrigem acumulam não conformidades repetidas, sinal clássico de ciclo que não fecha.', ok: true,
      why: 'Correta. Não conformidade repetida ano após ano é o sintoma de ciclo aberto.' },
    { t: 'A repetição de não conformidades entre auditorias é esperada e sem significado.', ok: false,
      why: 'Errada. Indica que as ações corretivas não atacaram a causa.' },
    { t: 'A etapa de verificação se esgota na realização da auditoria.', ok: false,
      why: 'Errada. Precisa gerar ação corretiva e verificação de eficácia.' },
    { t: 'A análise crítica pela direção é formalidade sem efeito prático.', ok: false,
      why: 'Errada. É onde se decidem recursos e prioridades, o que determina a viabilidade das ações.' },
    { t: 'A melhoria contínua dispensa a definição de objetivos mensuráveis.', ok: false,
      why: 'Errada. Sem objetivos mensuráveis não há como avaliar melhoria.' }
  ],
  comentario: 'O ciclo só fecha quando a verificação vira correção e a correção é verificada. Não conformidade que reaparece em auditorias sucessivas é o indicador mais honesto de que o sistema não está funcionando.',
  pegadinha: 'Auditar todo ano e reencontrar os mesmos achados é gestão da documentação, não do risco.',
  refs: ['ISO 45001', 'NR-1'] },

{ id: 'q-1.6-100', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre saúde do trabalhador e saúde ambiental, é CORRETO afirmar:',
  alts: [
    { t: 'Processos produtivos que expõem trabalhadores frequentemente expõem também a comunidade do entorno, de modo que a investigação de um caso ocupacional pode revelar contaminação ambiental — e a articulação entre as duas vigilâncias amplia o alcance de ambas.', ok: true,
      why: 'Correta. O trabalhador costuma ser o primeiro caso detectado de uma exposição maior.' },
    { t: 'A exposição ocupacional e a ambiental são fenômenos sem interseção.', ok: false,
      why: 'Errada. Compartilham frequentemente a mesma fonte.' },
    { t: 'A investigação de contaminação ambiental não deve considerar trabalhadores expostos.', ok: false,
      why: 'Errada. São o grupo de maior exposição e frequentemente os primeiros afetados.' },
    { t: 'Trabalhadores funcionam como sentinelas apenas em exposições agudas.', ok: false,
      why: 'Errada. Também em exposições crônicas, por concentrarem maior dose acumulada.' },
    { t: 'A comunidade do entorno não pode ser afetada quando a exposição ocupacional está controlada.', ok: false,
      why: 'Errada. Emissões, resíduos e transporte podem afetar o entorno independentemente do controle interno.' }
  ],
  comentario: 'O trabalhador é sentinela: recebe a maior dose e adoece primeiro, o que pode revelar contaminação que também alcança o entorno. Vigilância ambiental e do trabalhador olham a mesma fonte por ângulos diferentes.',
  pegadinha: 'Investigar o caso ocupacional sem olhar o entorno perde a exposição comunitária que a mesma fonte produz.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Vigilância em saúde ambiental'] },

{ id: 'q-1.7-100', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o acesso do trabalhador aos serviços do sistema público durante o horário de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A dificuldade de conciliar horário de atendimento e jornada é barreira concreta de acesso, que contribui para o adiamento do cuidado e para o agravamento de quadros — e é um dos determinantes da procura tardia por trabalhadores em geral.', ok: true,
      why: 'Correta. Serviço que só funciona no horário comercial exclui quem trabalha em horário comercial.' },
    { t: 'A conciliação entre jornada e horário de atendimento não constitui barreira relevante.', ok: false,
      why: 'Errada. É uma das barreiras mais concretas de acesso para trabalhadores.' },
    { t: 'A busca tardia por atendimento decorre exclusivamente de desinformação do trabalhador.', ok: false,
      why: 'Errada. Barreiras organizacionais de acesso têm peso determinante.' },
    { t: 'A liberação para consulta é liberalidade da empresa sem qualquer respaldo.', ok: false,
      why: 'Errada. Há previsões relativas a consultas e exames, especialmente os de natureza ocupacional.' },
    { t: 'Estratégias de ampliação de horário nos serviços não afetam a cobertura de trabalhadores.', ok: false,
      why: 'Errada. A ampliação de horário é uma das medidas mais efetivas para esse grupo.' }
  ],
  comentario: 'Serviço aberto só em horário comercial não alcança quem trabalha em horário comercial. A busca tardia do trabalhador é, em boa parte, barreira de acesso — e ampliar horário é a medida que mais muda essa cobertura.',
  pegadinha: 'Explicar a procura tardia por desinformação individualiza uma barreira que é de organização do serviço.',
  refs: ['Lei nº 8.080/1990', 'PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.8-100', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a inspeção sanitária em ambiente de trabalho e a produção do relatório, é CORRETO afirmar:',
  alts: [
    { t: 'O relatório deve descrever o que foi observado, as fontes de informação, as inadequações identificadas e as medidas exigidas com prazos — e o retorno para verificar o cumprimento é o que converte a inspeção em mudança efetiva.', ok: true,
      why: 'Correta. Inspeção sem retorno de verificação raramente muda a condição.' },
    { t: 'A inspeção se encerra com a entrega do relatório.', ok: false,
      why: 'Errada. A verificação do cumprimento é etapa essencial.' },
    { t: 'O relatório não precisa indicar prazos para as medidas exigidas.', ok: false,
      why: 'Errada. Sem prazo não há como verificar cumprimento nem cobrar.' },
    { t: 'As informações prestadas pelos trabalhadores não devem constar do relatório.', ok: false,
      why: 'Errada. Devem constar, com a proteção da identidade de quem as prestou.' },
    { t: 'A inspeção deve evitar o registro fotográfico das condições encontradas.', ok: false,
      why: 'Errada. O registro documenta a condição no momento e sustenta a exigência.' }
  ],
  comentario: 'Relatório de inspeção: o que se viu, de onde veio a informação, o que está inadequado, o que se exige e em que prazo — com identidade dos informantes protegida. E o retorno é o que faz a mudança acontecer.',
  pegadinha: 'Entregar relatório sem prazo e sem retorno produz arquivo, não correção.',
  refs: ['PNSTT', 'Legislação sanitária', 'Lei nº 8.080/1990'] },

{ id: 'q-1.9-100', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a investigação que se segue à notificação de um agravo relacionado ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A notificação é o início do processo, não seu fim: cabe investigar a situação de trabalho que gerou o agravo e verificar se outros trabalhadores estão expostos à mesma condição, transformando o caso individual em ação coletiva.', ok: true,
      why: 'Correta. Um caso notificado sinaliza um grupo exposto.' },
    { t: 'A notificação encerra a atuação do serviço de saúde sobre o caso.', ok: false,
      why: 'Errada. É o disparador da investigação.' },
    { t: 'A investigação deve se limitar ao trabalhador notificado.', ok: false,
      why: 'Errada. A verificação de outros expostos é o que produz efeito coletivo.' },
    { t: 'A investigação da situação de trabalho depende de autorização da empresa.', ok: false,
      why: 'Errada. A vigilância tem competência própria de acesso e inspeção.' },
    { t: 'Casos isolados não justificam investigação da situação de trabalho.', ok: false,
      why: 'Errada. Caso isolado pode ser o primeiro identificado entre vários existentes.' }
  ],
  comentario: 'Notificar é abrir o caso, não fechá-lo: investiga-se a situação de trabalho e procura-se quem mais está exposto. Caso isolado costuma ser o primeiro visto, não o único existente.',
  pegadinha: 'Tratar a notificação como conclusão transforma vigilância em cadastro.',
  refs: ['SINAN', 'PNSTT'] },

{ id: 'q-1.10-100', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre ações de promoção da saúde voltadas ao sono de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Orientações de higiene do sono têm eficácia limitada quando a escala de trabalho impede o descanso adequado — de modo que a intervenção precisa alcançar o desenho da escala, os intervalos entre turnos e o tempo de deslocamento.', ok: true,
      why: 'Correta. Não há higiene do sono que compense intervalo interjornada insuficiente.' },
    { t: 'Orientações de higiene do sono são suficientes independentemente da escala praticada.', ok: false,
      why: 'Errada. Escala inadequada inviabiliza a aplicação das orientações.' },
    { t: 'O tempo de deslocamento não integra a análise do descanso do trabalhador.', ok: false,
      why: 'Errada. Consome o intervalo entre jornadas e reduz o tempo disponível para dormir.' },
    { t: 'A privação crônica de sono não tem relação com risco de acidentes.', ok: false,
      why: 'Errada. É fator de risco reconhecido para acidentes e erros.' },
    { t: 'Cochilos programados em turnos noturnos não têm respaldo técnico.', ok: false,
      why: 'Errada. São estratégia com evidência de redução de sonolência e de erros em turnos noturnos.' }
  ],
  comentario: 'Higiene do sono não compensa escala ruim: o que muda o quadro é o intervalo entre turnos, o desenho da escala e o deslocamento. Cochilo programado no noturno tem respaldo técnico e é subutilizado.',
  pegadinha: 'Entregar orientação de sono a quem tem onze horas entre turnos, sendo três de ônibus, é transferir um problema organizacional.',
  refs: ['Fischer, F. M. — trabalho em turnos e saúde', 'CLT — intervalos', 'OIT'] },

{ id: 'q-2.5-090', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a comunicação de riscos aos trabalhadores como componente do gerenciamento, é CORRETO afirmar:',
  alts: [
    { t: 'Os trabalhadores devem ser informados dos riscos a que se expõem, das medidas de controle adotadas e dos resultados das avaliações que lhes dizem respeito, em linguagem compreensível — informação técnica não traduzida não cumpre a finalidade de permitir participação e autoproteção.', ok: true,
      why: 'Correta. Informar em linguagem inacessível é cumprir formalmente e não informar.' },
    { t: 'A entrega dos laudos técnicos completos cumpre integralmente o dever de informar.', ok: false,
      why: 'Errada. É preciso comunicar de forma compreensível ao destinatário.' },
    { t: 'Resultados de avaliações ambientais não precisam ser comunicados aos trabalhadores.', ok: false,
      why: 'Errada. O acesso à informação sobre a própria exposição é direito.' },
    { t: 'A comunicação de riscos é atribuição exclusiva da área de segurança.', ok: false,
      why: 'Errada. O médico do trabalho também tem esse dever.' },
    { t: 'A comunicação deve omitir riscos ainda não confirmados para evitar alarme.', ok: false,
      why: 'Errada. A incerteza deve ser comunicada como tal, não suprimida.' }
  ],
  comentario: 'Informar risco é comunicar em linguagem compreensível — inclusive a incerteza. Entregar o laudo completo satisfaz o protocolo e não informa ninguém; e o dever é também do médico, não só da segurança.',
  pegadinha: 'Omitir o risco ainda não confirmado "para não alarmar" retira do trabalhador a chance de se proteger.',
  refs: ['NR-1', 'Lei nº 8.080/1990 — art. 6º, §3º', 'Código de Ética Médica'] },

{ id: 'q-2.8-090', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação da aptidão do trabalhador para o uso de respirador, é CORRETO afirmar:',
  alts: [
    { t: 'O uso impõe carga respiratória e cardiovascular adicional e pode gerar desconforto e claustrofobia, de modo que a avaliação médica deve considerar essas condições — e a inaptidão para determinado tipo de respirador não implica inaptidão para a função, podendo haver alternativa técnica.', ok: true,
      why: 'Correta. Há alternativas, como equipamentos com ar fornecido ou motorizados.' },
    { t: 'O uso de respirador não impõe carga fisiológica adicional relevante.', ok: false,
      why: 'Errada. Impõe carga respiratória e cardiovascular, especialmente em esforço.' },
    { t: 'A inaptidão para um tipo de respirador implica inaptidão para a função.', ok: false,
      why: 'Errada. Existem alternativas técnicas com menor carga ou sem vedação facial.' },
    { t: 'Claustrofobia não é aspecto relevante nessa avaliação.', ok: false,
      why: 'Errada. Pode inviabilizar o uso contínuo e é aspecto a considerar.' },
    { t: 'A avaliação de aptidão para uso de respirador dispensa registro específico.', ok: false,
      why: 'Errada. Integra o programa de proteção respiratória e deve ser registrada.' }
  ],
  comentario: 'Respirador cansa: carga respiratória e cardiovascular, calor, desconforto, claustrofobia. Inapto para um tipo não é inapto para a função — equipamento motorizado ou com ar fornecido resolve boa parte dos casos.',
  pegadinha: 'Concluir pela inaptidão à função quando o problema é o tipo de equipamento elimina um trabalhador desnecessariamente.',
  refs: ['NR-6', 'Programa de Proteção Respiratória — Fundacentro'] },

{ id: 'q-4.3-080', tema: '4.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a bissinose e outras doenças respiratórias por poeiras orgânicas, é CORRETO afirmar:',
  alts: [
    { t: 'A bissinose, associada a poeiras de algodão e outras fibras vegetais, caracteriza-se classicamente por sintomas que pioram no primeiro dia de trabalho após a folga, padrão temporal que constitui pista diagnóstica de alto valor.', ok: true,
      why: 'Correta. A piora na segunda-feira é a marca clínica clássica dessa doença.' },
    { t: 'Poeiras orgânicas não causam doença respiratória ocupacional relevante.', ok: false,
      why: 'Errada. Causam bissinose, pneumonite de hipersensibilidade e síndrome tóxica por poeira orgânica.' },
    { t: 'Os sintomas da bissinose são mais intensos ao fim da semana de trabalho.', ok: false,
      why: 'Errada. O padrão clássico é a piora no primeiro dia após o período de afastamento.' },
    { t: 'A doença é de instalação exclusivamente aguda, sem forma crônica.', ok: false,
      why: 'Errada. A exposição prolongada pode levar a comprometimento crônico.' },
    { t: 'O padrão temporal dos sintomas não tem valor diagnóstico.', ok: false,
      why: 'Errada. É justamente o dado que mais orienta a suspeita nessa doença.' }
  ],
  comentario: 'Bissinose: poeira de algodão e fibras vegetais, com piora no primeiro dia após a folga — o padrão de segunda-feira. Poeira orgânica também causa pneumonite de hipersensibilidade e síndrome tóxica por poeira orgânica.',
  pegadinha: 'Esperar piora progressiva ao longo da semana inverte o padrão temporal característico.',
  refs: ['Diretrizes de pneumologia ocupacional', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-4.7-110', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o encaminhamento de trabalhador a serviço de saúde mental pela medicina do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O encaminhamento deve incluir informação sobre as condições de trabalho relevantes, com autorização do trabalhador, pois o serviço assistencial raramente tem acesso a esses dados — e é essa informação que permite ao assistente considerar a dimensão ocupacional do quadro.', ok: true,
      why: 'Correta. O assistente não conhece o posto; quem conhece é quem encaminha.' },
    { t: 'O encaminhamento deve conter apenas a queixa relatada pelo trabalhador.', ok: false,
      why: 'Errada. As condições de trabalho são informação essencial que só o serviço ocupacional tem.' },
    { t: 'Informações sobre o ambiente de trabalho podem ser enviadas sem autorização do trabalhador.', ok: false,
      why: 'Errada. O compartilhamento de informação relativa ao trabalhador exige sua autorização.' },
    { t: 'A dimensão ocupacional do quadro é irrelevante para a conduta assistencial.', ok: false,
      why: 'Errada. Influencia diretamente a conduta e o planejamento do retorno.' },
    { t: 'Após o encaminhamento, cessa a responsabilidade do serviço de saúde ocupacional.', ok: false,
      why: 'Errada. O acompanhamento e a atuação sobre o ambiente permanecem.' }
  ],
  comentario: 'Encaminhar bem é entregar o que só você tem: a descrição das condições de trabalho, com autorização do trabalhador. Sem isso, o assistente avalia o quadro sem a metade ocupacional dele.',
  pegadinha: 'Encaminhar apenas com a queixa entrega ao assistente a mesma informação que ele já teria sem você.',
  refs: ['Código de Ética Médica', 'Ministério da Saúde — transtornos mentais relacionados ao trabalho'] },

{ id: 'q-4.9-100', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o afastamento de trabalhadores com doenças transmissíveis, é CORRETO afirmar:',
  alts: [
    { t: 'A decisão considera o período de transmissibilidade, a via de transmissão e a natureza da atividade — sendo particularmente relevante em manipuladores de alimentos e trabalhadores de saúde, onde o risco alcança terceiros vulneráveis.', ok: true,
      why: 'Correta. O critério é o risco a terceiros, não apenas a condição do trabalhador.' },
    { t: 'O afastamento se justifica apenas pela incapacidade do trabalhador.', ok: false,
      why: 'Errada. O risco de transmissão a terceiros é razão autônoma.' },
    { t: 'A natureza da atividade não influencia a decisão de afastamento.', ok: false,
      why: 'Errada. Manipulação de alimentos e assistência a pacientes vulneráveis mudam completamente a decisão.' },
    { t: 'O afastamento deve durar até a cura clínica completa em todos os casos.', ok: false,
      why: 'Errada. O critério é o período de transmissibilidade, que pode ser menor que o de recuperação.' },
    { t: 'O trabalhador afastado por risco de transmissão deve ter o período descontado.', ok: false,
      why: 'Errada. O afastamento decorre de medida sanitária e não pode onerar o trabalhador.' }
  ],
  comentario: 'Afastar por transmissibilidade é diferente de afastar por incapacidade: o critério é o período em que transmite e o risco da atividade. E medida sanitária não é falta do trabalhador.',
  pegadinha: 'Vincular o retorno à cura completa afasta além do necessário; vinculá-lo à melhora subjetiva devolve o trabalhador ainda transmitindo.',
  refs: ['Ministério da Saúde — períodos de transmissibilidade', 'RDC sobre manipulação de alimentos', 'NR-32'] },

{ id: 'q-5.2-090', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise de nexo em trabalhador com histórico de múltiplos vínculos e exposições em empresas distintas, é CORRETO afirmar:',
  alts: [
    { t: 'A exposição relevante pode ter ocorrido em vínculo anterior, o que exige reconstituir a história ocupacional completa — e a atribuição a um único empregador nem sempre é possível, sem que isso afaste o reconhecimento da natureza ocupacional do agravo.', ok: true,
      why: 'Correta. Dificuldade de atribuir a um empregador não é o mesmo que ausência de nexo.' },
    { t: 'A impossibilidade de atribuir a exposição a um empregador específico afasta a natureza ocupacional.', ok: false,
      why: 'Errada. São questões distintas: natureza ocupacional e responsabilidade individual.' },
    { t: 'A análise deve considerar apenas o último vínculo do trabalhador.', ok: false,
      why: 'Errada. Exposições anteriores podem ser as determinantes, sobretudo em agravos de latência longa.' },
    { t: 'Documentos previdenciários não auxiliam a reconstituição da história ocupacional.', ok: false,
      why: 'Errada. Registros de vínculos e documentos de exposição são fontes importantes.' },
    { t: 'O relato do trabalhador sobre vínculos antigos não tem valor por ser retrospectivo.', ok: false,
      why: 'Errada. Frequentemente é a única fonte sobre condições de trabalho de décadas atrás.' }
  ],
  comentario: 'Com múltiplos vínculos, reconstitui-se a história inteira — registros previdenciários e relato do trabalhador incluídos. Não conseguir apontar um empregador responsável não descaracteriza a natureza ocupacional do agravo.',
  pegadinha: 'Confundir "não sei de quem é a responsabilidade" com "não é doença do trabalho" nega o reconhecimento pela razão errada.',
  refs: ['Lei nº 8.213/1991', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.3-100', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausalidade em transtornos mentais relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A existência de fatores pessoais e familiares não afasta a contribuição do trabalho, podendo configurar concausa — e a multideterminação, característica desses quadros, não é argumento válido para negar a participação de fatores ocupacionais identificáveis.', ok: true,
      why: 'Correta. Multideterminação é regra nesses quadros, não exceção que afasta o nexo.' },
    { t: 'A presença de fatores pessoais afasta o nexo ocupacional em transtornos mentais.', ok: false,
      why: 'Errada. Pode configurar concausa, que é reconhecida.' },
    { t: 'Transtornos mentais não admitem reconhecimento de nexo com o trabalho.', ok: false,
      why: 'Errada. Constam expressamente da lista de doenças relacionadas ao trabalho.' },
    { t: 'A multideterminação do quadro impede qualquer análise de nexo.', ok: false,
      why: 'Errada. A análise busca identificar a contribuição ocupacional dentro do conjunto.' },
    { t: 'O histórico psiquiátrico prévio impede o reconhecimento em qualquer hipótese.', ok: false,
      why: 'Errada. Agravamento de condição preexistente é hipótese expressa de concausa.' }
  ],
  comentario: 'Transtorno mental é multideterminado por definição — e isso não afasta a contribuição do trabalho, identificável e reconhecível como concausa. Histórico prévio abre a via do agravamento, não fecha a do nexo.',
  pegadinha: 'Usar a multideterminação para negar nexo eliminaria de saída toda a categoria dos transtornos mentais relacionados ao trabalho.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Ministério da Saúde — transtornos mentais relacionados ao trabalho'] },

{ id: 'q-5.6-100', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o retorno gradual ao trabalho como estratégia de reabilitação, é CORRETO afirmar:',
  alts: [
    { t: 'Consiste em retomada progressiva de carga e jornada, com acompanhamento e ajustes ao longo do processo, e está associada a melhores desfechos de permanência — sendo estratégia especialmente útil em quadros musculoesqueléticos e de saúde mental.', ok: true,
      why: 'Correta. Retorno progressivo com acompanhamento sustenta a permanência.' },
    { t: 'O retorno gradual não apresenta vantagem sobre o retorno integral imediato.', ok: false,
      why: 'Errada. Há evidência de melhores desfechos de permanência com a retomada progressiva.' },
    { t: 'O retorno gradual dispensa acompanhamento durante o período de retomada.', ok: false,
      why: 'Errada. O acompanhamento é o que permite ajustar antes da recaída.' },
    { t: 'A estratégia se aplica apenas a quadros musculoesqueléticos.', ok: false,
      why: 'Errada. É especialmente útil também em saúde mental.' },
    { t: 'O retorno gradual implica necessariamente redução proporcional de salário.', ok: false,
      why: 'Errada. As condições devem ser definidas sem converter a estratégia em prejuízo ao trabalhador.' }
  ],
  comentario: 'Retorno gradual: carga e jornada progressivas, com acompanhamento e ajuste. Melhores desfechos de permanência, útil em musculoesquelético e saúde mental — e não pode virar redução de salário disfarçada.',
  pegadinha: 'Retorno gradual sem acompanhamento vira retorno integral com atraso, e a recaída chega igual.',
  refs: ['Literatura sobre retorno ao trabalho', 'Lei nº 8.213/1991'] },

{ id: 'q-6.1-110', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a conclusão de aptidão com restrição, é CORRETO afirmar:',
  alts: [
    { t: 'Ela reconhece que o trabalhador pode exercer a função observadas limitações específicas, exigindo que a empresa implemente as condições correspondentes — e sem essa implementação, a conclusão perde efeito prático e o trabalhador permanece exposto ao que se pretendia evitar.', ok: true,
      why: 'Correta. Restrição não implementada é papel; o trabalhador segue na mesma condição.' },
    { t: 'A conclusão com restrição transfere ao trabalhador a responsabilidade de evitar as atividades restritas.', ok: false,
      why: 'Errada. Cabe à empresa organizar o trabalho de modo a respeitar a restrição.' },
    { t: 'A restrição, uma vez emitida, dispensa verificação posterior de cumprimento.', ok: false,
      why: 'Errada. A verificação é parte do acompanhamento.' },
    { t: 'A aptidão com restrição equivale a inaptidão para a função.', ok: false,
      why: 'Errada. Reconhece a possibilidade de exercício com condições ajustadas.' },
    { t: 'A restrição deve indicar o diagnóstico que a motivou para que a empresa a compreenda.', ok: false,
      why: 'Errada. Descreve-se a limitação funcional; o diagnóstico permanece sob sigilo.' }
  ],
  comentario: 'Apto com restrição é meio caminho: cabe à empresa implementar as condições e ao serviço médico verificar. Sem implementação e sem verificação, a restrição não protege ninguém — e o diagnóstico não entra no documento.',
  pegadinha: 'Deixar ao trabalhador a tarefa de "evitar" a atividade restrita devolve a ele o risco que a restrição reconheceu.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.4-110', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a intoxicação aguda por exposição maciça a gases em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Gases de baixa hidrossolubilidade podem produzir pouca irritação imediata das vias aéreas superiores e causar lesão pulmonar de instalação tardia — motivo pelo qual a ausência de sintomas iniciais não autoriza liberar o trabalhador sem período de observação.', ok: true,
      why: 'Correta. É o padrão que faz um trabalhador aparentemente bem piorar horas depois.' },
    { t: 'A ausência de sintomas respiratórios logo após a exposição permite liberação imediata.', ok: false,
      why: 'Errada. Alguns gases produzem edema pulmonar de instalação tardia.' },
    { t: 'Todos os gases irritantes produzem sintomas imediatos proporcionais à gravidade.', ok: false,
      why: 'Errada. A hidrossolubilidade determina onde e quando o efeito aparece.' },
    { t: 'Gases muito hidrossolúveis não produzem alerta sensorial na exposição.', ok: false,
      why: 'Errada. Produzem irritação intensa e precoce de olhos e vias aéreas superiores, o que induz a fuga.' },
    { t: 'A identificação do gás envolvido não altera a conduta de observação.', ok: false,
      why: 'Errada. Define o tempo de observação e os cuidados específicos.' }
  ],
  comentario: 'Hidrossolubilidade decide o padrão: gás muito solúvel irrita cedo e faz a pessoa fugir; gás pouco solúvel deixa chegar fundo e o edema pulmonar aparece horas depois. Por isso se observa mesmo quem está bem.',
  pegadinha: 'Liberar o trabalhador assintomático após exposição a gás pouco hidrossolúvel é a decisão que precede a piora noturna.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'Protocolos de emergências toxicológicas'] }

);
