/* Lote AI — 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 2.5, 2.8, 4.7, 4.9, 5.3, 5.6, 6.1, 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-090', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a gestão do absenteísmo por doença e o chamado presenteísmo, é CORRETO afirmar:',
  alts: [
    { t: 'O presenteísmo pode superar o absenteísmo e é favorecido por políticas punitivas de faltas.', ok: true,
      why: 'Correta. Reduzir o absenteísmo por pressão desloca o problema em vez de resolvê-lo.' },
    { t: 'O presenteísmo é conceito descritivo do trabalho com desempenho reduzido, sem repercussão mensurável.', ok: false,
      why: 'Errada. Há instrumentos de mensuração e impacto documentado.' },
    { t: 'O presenteísmo pode superar o absenteísmo, reduzindo-o as políticas de premiação por assiduidade.', ok: false,
      why: 'Errada. Tendem a aumentá-lo, pois penalizam quem se afasta para tratar.' },
    { t: 'O presenteísmo existe, sendo a redução do absenteísmo sempre indicador de melhora da saúde coletiva.', ok: false,
      why: 'Errada. Pode refletir apenas aumento do presenteísmo.' },
    { t: 'O presenteísmo pode superar o absenteísmo em custo, sem aumentar o risco de acidentes na operação.', ok: false,
      why: 'Errada. Trabalhador doente, medicado ou com dor tem atenção reduzida.' }
  ],
  comentario: 'Presenteísmo pode custar mais que absenteísmo e é alimentado por punição a faltas, prêmio por assiduidade e insegurança. Queda do absenteísmo sob pressão costuma ser deslocamento, não melhora.',
  pegadinha: 'O prêmio por assiduidade parece incentivo saudável e empurra o trabalhador doente para dentro da fábrica.',
  refs: ['OIT — presenteísmo e produtividade', 'Literatura de gestão em saúde ocupacional'] },

{ id: 'q-1.5-090', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a política de segurança e saúde de uma organização, é CORRETO afirmar:',
  alts: [
    { t: 'Deve declarar compromissos verificáveis e ser coerente com as decisões concretas de produção da empresa', ok: true,
      why: 'Correta. Uma decisão de produção contra a política ensina mais que qualquer cartaz.' },
    { t: 'Tem valor simbólico de orientação geral e não precisa declarar compromissos verificáveis e auditáveis.', ok: false,
      why: 'Errada. Compromissos verificáveis são o que permite cobrar e auditar.' },
    { t: 'Deve declarar compromissos verificáveis, bastando estar documentada e disponível para consulta.', ok: false,
      why: 'Errada. Precisa ser comunicada e compreendida pelos trabalhadores.' },
    { t: 'Deve declarar compromissos, sem que a coerência com as decisões de produção afete a cultura de segurança.', ok: false,
      why: 'Errada. É o principal determinante da credibilidade do sistema.' },
    { t: 'Deve declarar compromissos verificáveis, elaborados exclusivamente pela área técnica de segurança.', ok: false,
      why: 'Errada. Exige compromisso da alta direção e consulta aos trabalhadores.' }
  ],
  comentario: 'Política de segurança vale pelo que se decide quando ela conflita com o prazo de produção. Compromissos verificáveis, comunicação efetiva e coerência prática — o resto é cartaz.',
  pegadinha: 'Documentar e disponibilizar não é comunicar, e comunicar não é ser coerente na hora da decisão.',
  refs: ['ISO 45001', 'NR-1'] },

{ id: 'q-1.6-090', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as ações de saúde do trabalhador dirigidas ao trabalho informal, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem estratégias próprias, já que esses trabalhadores não têm serviço de medicina do trabalho.', ok: true,
      why: 'Correta. Sem empresa, não há serviço ocupacional; sobra o território e a atenção básica.' },
    { t: 'São alcançadas pelos programas ocupacionais das empresas que contratam esses serviços informais.', ok: false,
      why: 'Errada. Justamente por não terem vínculo, ficam fora desses programas.' },
    { t: 'Exigem estratégias próprias, ainda que a informalidade reduza a exposição a riscos ocupacionais.', ok: false,
      why: 'Errada. Costuma associar-se a maior exposição e menor proteção.' },
    { t: 'Exigem estratégias de aproximação, sem papel relevante da atenção básica junto a esse grupo.', ok: false,
      why: 'Errada. É a principal porta de entrada para esses trabalhadores.' },
    { t: 'Exigem estratégias próprias, impedindo a ausência de vínculo formal a notificação dos agravos.', ok: false,
      why: 'Errada. A notificação independe de vínculo.' }
  ],
  comentario: 'Informal não tem serviço de medicina do trabalho — tem unidade básica e território. Por isso a busca ativa e a pergunta sobre ocupação na atenção básica são a estratégia central para esse grupo.',
  pegadinha: 'Supor que a contratante cobre o informal desenha uma proteção que não existe na prática.',
  refs: ['PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.7-090', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a regionalização e a hierarquização aplicadas às ações de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A rede regionalizada oferta as ações de maior complexidade em base regional, apoiando as unidades locais', ok: true,
      why: 'Correta. Município pequeno não sustenta estrutura própria; a base regional resolve.' },
    { t: 'Cada município deve dispor de estrutura completa e autônoma de vigilância em saúde do trabalhador.', ok: false,
      why: 'Errada. A regionalização existe para viabilizar o que o município isolado não sustenta.' },
    { t: 'A rede é regionalizada, implicando a hierarquização que a atenção básica não participe das ações.', ok: false,
      why: 'Errada. Ela é porta de entrada e participa ativamente.' },
    { t: 'A rede é regionalizada na assistência, não se aplicando a regionalização às ações de vigilância.', ok: false,
      why: 'Errada. Aplica-se e é determinante de sua viabilidade.' },
    { t: 'A rede regionalizada oferta ações de maior complexidade, dispensando pactuação entre os gestores.', ok: false,
      why: 'Errada. A pactuação é o instrumento que viabiliza a organização regional.' }
  ],
  comentario: 'Regionalização viabiliza o que o município pequeno não sustenta sozinho, com pactuação entre gestores — e sem tirar a atenção básica do processo, que segue como porta de entrada.',
  pegadinha: 'Exigir estrutura completa por município condena a vigilância a existir só nas capitais.',
  refs: ['Lei nº 8.080/1990', 'Decreto nº 7.508/2011', 'RENAST'] },

{ id: 'q-1.8-090', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o uso de indicadores para priorizar ações de vigilância em saúde do trabalhador em um território, é CORRETO afirmar:',
  alts: [
    { t: 'Combina magnitude, gravidade, número de expostos e viabilidade técnica da intervenção proposta', ok: true,
      why: 'Correta. Setor com poucos registros pode significar ausência de vigilância, não de risco.' },
    { t: 'Combina magnitude e gravidade, podendo desconsiderar os setores sem registros de agravos notificados.', ok: false,
      why: 'Errada. A ausência de registro pode indicar ausência de vigilância anterior.' },
    { t: 'Toma a magnitude dos agravos como critério, por expressar o peso de cada problema na população.', ok: false,
      why: 'Errada. Gravidade, número de expostos e viabilidade também compõem a decisão.' },
    { t: 'Combina magnitude, gravidade e expostos, sem que a viabilidade de intervenção influencie a decisão.', ok: false,
      why: 'Errada. Priorizar o inviável consome recurso sem produzir mudança.' },
    { t: 'Combina magnitude e gravidade, feita sem participação dos trabalhadores e de suas entidades.', ok: false,
      why: 'Errada. Elas trazem informação sobre setores e riscos invisíveis nas bases.' }
  ],
  comentario: 'Priorizar por magnitude, gravidade, expostos e viabilidade — lembrando que setor sem registro pode ser setor nunca olhado. E sindicatos apontam o que a base não mostra.',
  pegadinha: 'Priorizar apenas onde já há registro perpetua a invisibilidade dos setores nunca fiscalizados.',
  refs: ['PNSTT', 'Ministério da Saúde — vigilância em saúde do trabalhador'] },

{ id: 'q-1.9-090', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os agravos relacionados ao trabalho de notificação compulsória, é CORRETO afirmar:',
  alts: [
    { t: 'Inclui acidentes graves e fatais, material biológico, intoxicação, perda auditiva, câncer e outros.', ok: true,
      why: 'Correta. A lista é ampla e alcança agravos crônicos, não apenas eventos agudos.' },
    { t: 'Inclui os acidentes de trabalho graves, fatais e com menores, únicos agravos ocupacionais notificáveis.', ok: false,
      why: 'Errada. Doenças crônicas relacionadas ao trabalho também integram a lista.' },
    { t: 'Inclui acidentes e intoxicações, ficando de fora os transtornos mentais relacionados ao trabalho.', ok: false,
      why: 'Errada. Integram expressamente a lista.' },
    { t: 'Inclui acidentes, intoxicações e dermatoses, não sendo o câncer relacionado ao trabalho notificável.', ok: false,
      why: 'Errada. É agravo de notificação compulsória.' },
    { t: 'Inclui perda auditiva induzida por ruído apenas nos casos que cursam com incapacidade instalada.', ok: false,
      why: 'Errada. A notificação decorre do agravo identificado, não do grau de incapacidade.' }
  ],
  comentario: 'A lista vai muito além do acidente: perda auditiva, transtornos mentais, dermatoses, pneumoconioses, câncer, lesões por esforços repetitivos, intoxicações. Os crônicos são justamente os menos notificados.',
  pegadinha: 'Reduzir a notificação a acidentes deixa fora todos os agravos de instalação lenta.',
  refs: ['Portaria de Consolidação nº 4/2017', 'SINAN'] },

{ id: 'q-1.10-090', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a promoção da atividade física no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Podem trazer benefícios, mas não substituem a correção de fatores ergonômicos e organizacionais.', ok: true,
      why: 'Correta. Pausa para ginástica sem reduzir o ritmo transfere ao trabalhador a compensação.' },
    { t: 'Podem trazer benefícios, substituindo a ginástica laboral as adequações ergonômicas do posto de trabalho.', ok: false,
      why: 'Errada. São medidas de naturezas distintas e não substitutivas.' },
    { t: 'Podem trazer benefícios, podendo a participação ser tornada obrigatória sem implicações para o trabalhador.', ok: false,
      why: 'Errada. Obrigatoriedade descaracteriza a adesão e gera constrangimento.' },
    { t: 'Podem trazer benefícios, não requerendo avaliação prévia das condições individuais dos participantes.', ok: false,
      why: 'Errada. Condições clínicas específicas exigem orientação individualizada.' },
    { t: 'Podem trazer benefícios, equivalendo a pausa para ginástica à pausa de recuperação da atividade.', ok: false,
      why: 'Errada. São finalidades distintas; a de recuperação decorre da exigência da tarefa.' }
  ],
  comentario: 'Ginástica laboral tem lugar, mas não corrige posto nem ritmo — e a pausa de ginástica não substitui a pausa de recuperação que a atividade exige. Sem obrigatoriedade e com atenção a condições individuais.',
  pegadinha: 'Contabilizar a ginástica como pausa de recuperação elimina o descanso que a tarefa exigia.',
  refs: ['NR-17', 'OMS — ambientes de trabalho saudáveis'] },

{ id: 'q-2.5-080', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a antecipação de riscos em projetos de novas instalações e processos, é CORRETO afirmar:',
  alts: [
    { t: 'Intervir no projeto é a oportunidade de maior eficácia e menor custo, eliminando o perigo antes.', ok: true,
      why: 'Correta. O que se resolve no desenho não precisa ser gerenciado depois.' },
    { t: 'A avaliação de riscos deve começar após o início da operação, quando as condições reais se revelam.', ok: false,
      why: 'Errada. A antecipação na fase de projeto é a etapa mais eficaz.' },
    { t: 'Intervir no projeto é possível, tendo as correções posteriores o mesmo custo e a mesma eficácia.', ok: false,
      why: 'Errada. São mais caras, mais limitadas e frequentemente parciais.' },
    { t: 'Intervir no projeto é mais eficaz, sendo dispensável a participação de saúde e segurança nessa fase.', ok: false,
      why: 'Errada. É onde sua contribuição tem maior alcance.' },
    { t: 'Intervir no projeto é mais eficaz, aplicando-se a antecipação apenas aos riscos de natureza química.', ok: false,
      why: 'Errada. Aplica-se a todos, inclusive ergonômicos e psicossociais do desenho.' }
  ],
  comentario: 'Antecipação é a etapa de maior retorno: elimina-se o perigo antes de ele existir, no papel, onde mudar é barato. Depois de instalado, a mesma correção enfrenta parede, orçamento e prazo.',
  pegadinha: 'Chamar a equipe de saúde e segurança só depois da inauguração reduz a atuação a remendo.',
  refs: ['NR-1', 'AIHA', 'Prevenção pelo desenho — literatura de referência'] },

{ id: 'q-2.8-080', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a higienização, a guarda e a manutenção de respiradores, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem higienização e inspeção periódicas e guarda protegida de contaminação, umidade e deformação', ok: true,
      why: 'Correta. Respirador guardado dobrado dentro do armário perde vedação.' },
    { t: 'Exigem higienização e inspeção periódicas, sem que a forma de guarda influencie seu desempenho.', ok: false,
      why: 'Errada. Deformação e contaminação comprometem vedação e proteção.' },
    { t: 'Exigem higienização periódica, que pode ser feita com qualquer produto de limpeza disponível.', ok: false,
      why: 'Errada. Produtos inadequados degradam o material e a vedação.' },
    { t: 'Exigem higienização e guarda adequadas, cabendo a inspeção do equipamento exclusivamente ao fornecedor.', ok: false,
      why: 'Errada. A inspeção pelo usuário antes do uso é parte do programa.' },
    { t: 'Exigem inspeção periódica, podendo componentes danificados ser mantidos até a troca programada.', ok: false,
      why: 'Errada. Componente danificado exige substituição imediata.' }
  ],
  comentario: 'Respirador reutilizável: higienizar com produto adequado, inspecionar antes de cada uso, guardar sem deformar nem contaminar e trocar componente danificado na hora — não no próximo ciclo.',
  pegadinha: 'Guardar o respirador amassado no armário anula o ensaio de vedação que foi feito com ele novo.',
  refs: ['NR-6', 'Programa de Proteção Respiratória — Fundacentro'] },

{ id: 'q-4.7-100', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a abordagem inicial do trabalhador em sofrimento psíquico identificado no serviço ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Envolve acolhimento, avaliação do risco imediato, encaminhamento com continuidade e análise do contexto.', ok: true,
      why: 'Correta. Encaminhar sem garantir continuidade equivale a não encaminhar.' },
    { t: 'Envolve acolhimento e avaliação, esgotando-se a conduta no encaminhamento a serviço externo de saúde.', ok: false,
      why: 'Errada. Sem continuidade garantida, o encaminhamento se perde.' },
    { t: 'Envolve acolhimento, sendo dispensável a avaliação de risco imediato sem relato espontâneo do trabalhador.', ok: false,
      why: 'Errada. A avaliação deve ser ativa, pois o relato espontâneo é a exceção.' },
    { t: 'Envolve acolhimento e encaminhamento, sem que o contexto de trabalho integre a avaliação inicial.', ok: false,
      why: 'Errada. É o que diferencia a abordagem ocupacional da assistencial comum.' },
    { t: 'Envolve acolhimento e encaminhamento, evitando-se perguntar sobre ideação para não aumentar o risco.', ok: false,
      why: 'Errada. Perguntar diretamente não induz o comportamento e permite intervir.' }
  ],
  comentario: 'Acolher, avaliar ativamente o risco, encaminhar com continuidade e olhar o contexto de trabalho. E perguntar sobre ideação não induz nada — é o que permite agir a tempo.',
  pegadinha: 'O receio de perguntar sobre ideação suicida é infundado e deixa o risco sem avaliação.',
  refs: ['Ministério da Saúde — prevenção do suicídio', 'Código de Ética Médica'] },

{ id: 'q-4.9-090', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a tuberculose em trabalhadores fora da área da saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Ambientes fechados e com aglomeração favorecem a transmissão em qualquer setor de atividade.', ok: true,
      why: 'Correta. A investigação de contato costuma parar na família e ignorar o turno inteiro.' },
    { t: 'A transmissão ocupacional de tuberculose se restringe aos serviços de saúde e laboratórios clínicos.', ok: false,
      why: 'Errada. Qualquer ambiente fechado com aglomeração favorece a transmissão.' },
    { t: 'Ambientes fechados favorecem a transmissão, devendo a investigação de contatos limitar-se ao domicílio.', ok: false,
      why: 'Errada. Colegas com convívio prolongado são contatos a investigar.' },
    { t: 'Ambientes fechados favorecem a transmissão, sem que a ventilação do local influencie esse risco.', ok: false,
      why: 'Errada. É um dos principais determinantes da transmissão.' },
    { t: 'Ambientes fechados favorecem a transmissão, não requerendo os mais vulneráveis atenção diferenciada.', ok: false,
      why: 'Errada. Concentram maior incidência e maior dificuldade de adesão ao tratamento.' }
  ],
  comentario: 'Tuberculose não é só risco de hospital: ambiente fechado, mal ventilado e com aglomeração transmite em qualquer setor. Caso identificado pede investigação de contatos no trabalho, não só em casa.',
  pegadinha: 'Investigar contatos apenas no domicílio deixa o turno inteiro sem rastreamento.',
  refs: ['Ministério da Saúde — controle da tuberculose', 'NR-24'] },

{ id: 'q-5.3-090', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausa e a quantificação da contribuição do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A lei não fixa percentuais, sendo a análise qualitativa quanto à existência da contribuição.', ok: true,
      why: 'Correta. O reconhecimento é binário; proporcionalidade é discussão da esfera civil.' },
    { t: 'A legislação previdenciária estabelece percentuais mínimos de contribuição do trabalho para o nexo.', ok: false,
      why: 'Errada. Não há previsão de percentuais para o reconhecimento.' },
    { t: 'A lei não fixa percentuais, sendo o benefício pago proporcionalmente à contribuição do trabalho.', ok: false,
      why: 'Errada. O benefício não é rateado por proporção de causa.' },
    { t: 'A lei não fixa percentuais, não aparecendo a discussão de proporcionalidade em nenhuma esfera.', ok: false,
      why: 'Errada. Pode ser considerada na fixação de indenização civil.' },
    { t: 'A análise da concausa é quantitativa e exige mensurar a contribuição de cada fator envolvido.', ok: false,
      why: 'Errada. É qualitativa quanto à existência da contribuição.' }
  ],
  comentario: 'Para o reconhecimento previdenciário, a pergunta é se o trabalho contribuiu — não quanto. Percentual não existe ali; proporcionalidade pode aparecer na indenização civil, que é outra discussão.',
  pegadinha: 'Misturar as duas esferas leva a exigir percentual onde a lei só pergunta se houve contribuição.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Código Civil'] },

{ id: 'q-5.6-090', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a estabilidade do trabalhador reabilitado e a reserva de vagas, é CORRETO afirmar:',
  alts: [
    { t: 'A dispensa em contrato por prazo indeterminado exige contratar substituto em condição semelhante', ok: true,
      why: 'Correta. A proteção é do preenchimento da reserva, mantendo o número de vagas.' },
    { t: 'A dispensa é condicionada, protegendo a regra apenas o trabalhador individualmente considerado.', ok: false,
      why: 'Errada. Protege a manutenção do percentual de vagas reservadas.' },
    { t: 'A regra protege o percentual de vagas, não sendo os reabilitados alcançados pela reserva legal.', ok: false,
      why: 'Errada. São expressamente alcançados pela reserva.' },
    { t: 'A dispensa é condicionada, aplicando-se a regra também a contratos por prazo determinado curtos.', ok: false,
      why: 'Errada. A condição legal se refere à dispensa em contrato por prazo indeterminado.' },
    { t: 'A dispensa é condicionada, podendo o substituto ser contratado em função de menor complexidade.', ok: false,
      why: 'Errada. A exigência é de contratação em condição semelhante.' }
  ],
  comentario: 'A regra da substituição protege o percentual: dispensar sem repor esvazia a reserva. Alcança reabilitados, refere-se ao contrato por prazo indeterminado e exige substituto em condição semelhante.',
  pegadinha: 'Ler a regra como proteção individual perde a razão de ser dela, que é manter o número de vagas ocupadas.',
  refs: ['Lei nº 8.213/1991 — art. 93, §1º'] },

{ id: 'q-6.1-100', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a guarda e a validade do atestado de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Uma via vai ao trabalhador, e o documento registra os riscos avaliados, os exames e a conclusão', ok: true,
      why: 'Correta. É documento de memória da exposição, não apenas de liberação para o trabalho.' },
    { t: 'Uma via fica arquivada na empresa, sendo facultativa a entrega de via ao próprio trabalhador.', ok: false,
      why: 'Errada. É exigência normativa.' },
    { t: 'Uma via vai ao trabalhador, sem necessidade de o documento indicar os riscos ocupacionais avaliados.', ok: false,
      why: 'Errada. Os riscos avaliados integram seu conteúdo obrigatório.' },
    { t: 'Uma via vai ao trabalhador, podendo a guarda ser encerrada com o desligamento do empregado.', ok: false,
      why: 'Errada. Os prazos de guarda são prolongados, pela latência de vários agravos.' },
    { t: 'Uma via vai ao trabalhador, podendo a conclusão ser omitida quando ele é considerado apto.', ok: false,
      why: 'Errada. A conclusão é elemento essencial do documento.' }
  ],
  comentario: 'O atestado registra riscos avaliados, exames feitos e conclusão, com via ao trabalhador e guarda prolongada. É a memória da exposição — e é por isso que a guarda não termina com o vínculo.',
  pegadinha: 'Tratar o documento como liberação para trabalhar ignora sua função de registro histórico da exposição.',
  refs: ['NR-7'] },

{ id: 'q-6.4-100', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a queimadura elétrica no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A lesão externa subestima o dano profundo, com necrose muscular, rabdomiólise e risco renal.', ok: true,
      why: 'Correta. A corrente lesa o trajeto interno; a pele mostra só entrada e saída.' },
    { t: 'A extensão da lesão cutânea visível estima adequadamente a gravidade do caso a ser atendido.', ok: false,
      why: 'Errada. O dano profundo ao longo do trajeto costuma ser muito maior.' },
    { t: 'A lesão externa subestima o dano, dispensando monitorização cardíaca a queimadura de lesão pequena.', ok: false,
      why: 'Errada. Arritmias podem ocorrer independentemente do tamanho da lesão cutânea.' },
    { t: 'A lesão externa subestima o dano profundo, não sendo a rabdomiólise complicação esperada nesses casos.', ok: false,
      why: 'Errada. É complicação clássica, com risco de lesão renal aguda.' },
    { t: 'A lesão externa subestima o dano, podendo a vítima ser retirada do contato diretamente com as mãos.', ok: false,
      why: 'Errada. É preciso desenergizar ou usar material isolante, sob risco de nova vítima.' }
  ],
  comentario: 'Queimadura elétrica: a pele engana. O dano segue o trajeto da corrente, com necrose muscular, rabdomiólise e risco renal, e a arritmia não pede lesão grande. E ninguém toca na vítima antes de desenergizar.',
  pegadinha: 'Estimar gravidade pela lesão cutânea subestima o caso justamente quando ele é mais grave.',
  refs: ['NR-10', 'Protocolos de atendimento a queimaduras elétricas'] }

);
