/* Lote AU — fechamento final das metas por tema. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.2-150', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a pressões anormais em trabalho subaquático, é CORRETO afirmar:',
  alts: [
    { t: 'A atividade exige avaliação médica específica, controle rigoroso de tempo e profundidade, tabelas de descompressão e registro individual dos perfis de mergulho — sendo o histórico acumulado de exposições elemento essencial para a avaliação de doença descompressiva crônica.', ok: true,
      why: 'Correta. Sem registro dos perfis, não há como avaliar a exposição acumulada.' },
    { t: 'O registro individual dos perfis de mergulho é dispensável.', ok: false,
      why: 'Errada. É a base para avaliar exposição acumulada e investigar agravos tardios.' },
    { t: 'A avaliação médica para mergulho profissional é igual à de qualquer função.', ok: false,
      why: 'Errada. Exige avaliação específica, com atenção a condições que contraindicam a atividade.' },
    { t: 'A osteonecrose disbárica não é agravo relacionado a essa atividade.', ok: false,
      why: 'Errada. É agravo reconhecido em mergulhadores e trabalhadores em ar comprimido.' },
    { t: 'Após a saída da atividade, não há necessidade de acompanhamento.', ok: false,
      why: 'Errada. Agravos de manifestação tardia justificam acompanhamento posterior.' }
  ],
  comentario: 'Mergulho profissional: avaliação médica específica, tabelas, controle de tempo e profundidade e registro dos perfis. A osteonecrose disbárica aparece tarde — e sem o registro, não se reconstitui a exposição.',
  pegadinha: 'Não registrar os perfis inviabiliza, anos depois, a análise do agravo que a atividade produz.',
  refs: ['NR-15 — Anexo 6', 'Medicina hiperbárica — literatura de referência'] },

{ id: 'q-2.3-150', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a gases anestésicos residuais em centros cirúrgicos, é CORRETO afirmar:',
  alts: [
    { t: 'A exposição decorre de escape de circuitos, técnicas de indução e ventilação inadequada, com preocupações quanto a efeitos neurocomportamentais e reprodutivos — sendo o sistema de exaustão de gases residuais e a manutenção dos equipamentos as medidas centrais de controle.', ok: true,
      why: 'Correta. Controle é exaustão de gases residuais e manutenção, não proteção individual.' },
    { t: 'Não há exposição ocupacional relevante a gases anestésicos em centros cirúrgicos modernos.', ok: false,
      why: 'Errada. Escapes e ventilação inadequada mantêm a exposição relevante.' },
    { t: 'A proteção respiratória individual é a medida adequada de controle nesse cenário.', ok: false,
      why: 'Errada. O controle é por exaustão de gases residuais e manutenção dos circuitos.' },
    { t: 'A preocupação com efeitos reprodutivos não tem fundamento nessa exposição.', ok: false,
      why: 'Errada. É uma das preocupações históricas associadas a esses agentes.' },
    { t: 'A manutenção dos equipamentos de anestesia não influencia a exposição da equipe.', ok: false,
      why: 'Errada. Vazamentos por manutenção deficiente são fonte principal de exposição.' }
  ],
  comentario: 'Gases anestésicos residuais: escape de circuito e ventilação inadequada expõem toda a equipe. Controle é exaustão de gases residuais e manutenção — proteção respiratória não resolve esse cenário.',
  pegadinha: 'Buscar solução em equipamento individual num ambiente que exige exaustão inverte a hierarquia de controle.',
  refs: ['NR-32', 'ACGIH', 'Diretrizes de segurança em centro cirúrgico'] },

{ id: 'q-2.4-150', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a agentes biológicos em atividades de reforma e demolição, é CORRETO afirmar:',
  alts: [
    { t: 'Edificações abandonadas podem conter excretas de aves e morcegos, com risco de histoplasmose, além de infestação por roedores associada à leptospirose — riscos frequentemente não previstos por serem atividades classificadas apenas pelos riscos físicos e químicos.', ok: true,
      why: 'Correta. Obra não é lembrada como atividade com risco biológico.' },
    { t: 'Atividades de reforma e demolição não apresentam risco biológico relevante.', ok: false,
      why: 'Errada. Excretas de aves e morcegos e infestação por roedores são riscos concretos.' },
    { t: 'A histoplasmose não guarda relação com atividades ocupacionais.', ok: false,
      why: 'Errada. Há surtos ocupacionais descritos em limpeza de locais com acúmulo de excretas.' },
    { t: 'A umidificação prévia da área não influencia a geração de aerossóis infectantes.', ok: false,
      why: 'Errada. Reduz a suspensão de partículas contendo o agente.' },
    { t: 'A proteção respiratória é desnecessária nessas atividades quando não há poeira visível.', ok: false,
      why: 'Errada. As partículas infectantes não são visíveis e exigem proteção adequada.' }
  ],
  comentario: 'Reforma e demolição têm risco biológico esquecido: excretas de aves e morcegos, com histoplasmose, e roedores, com leptospirose. Umidificar antes reduz aerossóis, e a partícula infectante não é visível.',
  pegadinha: 'Classificar obra apenas pelos riscos físicos e químicos deixa o risco biológico fora do inventário.',
  refs: ['NR-18', 'NR-32', 'Ministério da Saúde — histoplasmose e leptospirose'] },

{ id: 'q-2.6-150', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comparação entre limites nacionais e referências técnicas internacionais, é CORRETO afirmar:',
  alts: [
    { t: 'Divergências entre eles são frequentes e decorrem de datas de revisão e de critérios distintos, cabendo ao serviço adotar o critério mais protetor quando houver diferença — decisão que é permitida e tecnicamente recomendável.', ok: true,
      why: 'Correta. Nada impede adotar o critério mais protetor, e é o que a técnica recomenda.' },
    { t: 'A adoção de critério mais protetor que o normativo é irregular.', ok: false,
      why: 'Errada. É permitida e recomendável.' },
    { t: 'Não há divergência relevante entre limites nacionais e referências internacionais.', ok: false,
      why: 'Errada. Divergências são frequentes, dadas as diferentes datas de revisão.' },
    { t: 'O cumprimento do limite normativo demonstra que a exposição está tecnicamente controlada.', ok: false,
      why: 'Errada. O limite pode estar defasado em relação à evidência atual.' },
    { t: 'A escolha do critério adotado não precisa ser justificada no laudo.', ok: false,
      why: 'Errada. O critério adotado deve ser declarado e justificado.' }
  ],
  comentario: 'Limite nacional e referência internacional divergem por data de revisão e critério. Adotar o mais protetor é permitido e recomendável — declarando no laudo qual critério se usou e por quê.',
  pegadinha: 'Cumprir o limite normativo defasado não é o mesmo que ter exposição tecnicamente controlada.',
  refs: ['NR-15', 'ACGIH — TLVs', 'NHO — Fundacentro'] },

{ id: 'q-2.7-130', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a integração entre os resultados de avaliação de higiene ocupacional e o programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'Os resultados devem orientar a definição de exames, periodicidades e grupos a monitorar, e a inexistência dessa articulação produz dois programas paralelos — um que mede o ambiente e outro que examina pessoas, sem que um informe o outro.', ok: true,
      why: 'Correta. É a falha organizacional mais comum entre as duas áreas.' },
    { t: 'Os dois programas devem operar de forma independente.', ok: false,
      why: 'Errada. O programa médico deve derivar dos riscos avaliados.' },
    { t: 'Resultados de higiene ocupacional não influenciam a periodicidade dos exames.', ok: false,
      why: 'Errada. Nível de exposição e efeito crítico determinam a periodicidade.' },
    { t: 'A definição dos grupos a monitorar independe dos grupos homogêneos de exposição.', ok: false,
      why: 'Errada. Os grupos de exposição orientam diretamente os grupos de vigilância médica.' },
    { t: 'A comunicação entre as áreas técnica e médica é desejável, mas sem efeito prático.', ok: false,
      why: 'Errada. É o que torna o programa médico dirigido ao risco real.' }
  ],
  comentario: 'Higiene mede o ambiente e o programa médico examina as pessoas — se não conversam, viram dois programas paralelos. Grupos de exposição definem grupos de vigilância; nível e efeito crítico definem exame e periodicidade.',
  pegadinha: 'A separação entre as áreas produz medição que ninguém usa e exame que não vigia o risco medido.',
  refs: ['NR-7', 'NR-9', 'NHO — Fundacentro'] },

{ id: 'q-4.4-150', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vigilância de dermatoses em grupos de trabalhadores expostos, é CORRETO afirmar:',
  alts: [
    { t: 'O exame de pele dirigido, em trabalhadores de setores com agentes irritantes ou sensibilizantes, permite detectar quadros iniciais antes da cronificação — e a queixa espontânea costuma ocorrer tarde, quando a lesão já compromete a função.', ok: true,
      why: 'Correta. O trabalhador só procura quando a mão já não trabalha.' },
    { t: 'A queixa espontânea do trabalhador é indicador suficiente para a vigilância dermatológica.', ok: false,
      why: 'Errada. A procura espontânea ocorre tardiamente.' },
    { t: 'O exame de pele não faz parte do exame ocupacional dirigido ao risco.', ok: false,
      why: 'Errada. Em setores com agentes cutâneos, é exame dirigido ao efeito crítico.' },
    { t: 'Quadros iniciais de dermatite não têm repercussão sobre a evolução do caso.', ok: false,
      why: 'Errada. A intervenção precoce evita a cronificação.' },
    { t: 'A vigilância dermatológica se restringe à indústria química.', ok: false,
      why: 'Errada. Alcança construção, saúde, alimentação, limpeza e cabeleireiros, entre outros.' }
  ],
  comentario: 'Olhar a pele de quem trabalha com irritantes e sensibilizantes detecta cedo o que a queixa espontânea só traz quando já cronificou. E o alcance vai muito além da indústria química.',
  pegadinha: 'Esperar a queixa transforma um quadro tratável em dermatose crônica que limita a função.',
  refs: ['Salim — Dermatoses Ocupacionais', 'NR-7'] },

{ id: 'q-4.5-140', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação vestibular e o equilíbrio em trabalhadores expostos a agentes ototóxicos, é CORRETO afirmar:',
  alts: [
    { t: 'Alguns agentes afetam também o sistema vestibular, com queixas de tontura e desequilíbrio que têm repercussão direta em segurança — sobretudo em trabalho em altura e operação de equipamentos, o que justifica investigar a queixa em vez de atribuí-la a causas inespecíficas.', ok: true,
      why: 'Correta. Desequilíbrio em altura é risco imediato, não sintoma menor.' },
    { t: 'Agentes ototóxicos afetam exclusivamente a função auditiva.', ok: false,
      why: 'Errada. Alguns comprometem também a função vestibular.' },
    { t: 'Queixas de tontura em trabalhadores expostos devem ser atribuídas a causas inespecíficas.', ok: false,
      why: 'Errada. Exigem investigação, dada a repercussão em segurança.' },
    { t: 'O desequilíbrio não tem repercussão relevante em trabalho em altura.', ok: false,
      why: 'Errada. É risco direto e imediato nessa atividade.' },
    { t: 'A avaliação vestibular não integra a vigilância de expostos a ototóxicos.', ok: false,
      why: 'Errada. É indicada quando o agente tem esse potencial.' }
  ],
  comentario: 'Ototóxico pode atingir também o vestíbulo: tontura e desequilíbrio em quem trabalha em altura ou opera máquina é risco imediato. Investigar a queixa, não rotulá-la como inespecífica.',
  pegadinha: 'Tratar tontura como queixa vaga em trabalhador de altura ignora a consequência mais previsível.',
  refs: ['NR-35', 'NR-7 — Anexo I', 'ACGIH — ototoxicantes'] },

{ id: 'q-4.6-140', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação do impacto de reestruturações e demissões coletivas sobre a saúde dos trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Processos de reestruturação afetam também quem permanece, com aumento de carga, insegurança e sofrimento psíquico documentados — de modo que a avaliação de risco psicossocial deve considerar o período de reestruturação como situação de exposição aumentada.', ok: true,
      why: 'Correta. Quem fica acumula o trabalho de quem saiu, sob insegurança.' },
    { t: 'O impacto se restringe aos trabalhadores desligados.', ok: false,
      why: 'Errada. Quem permanece apresenta aumento de carga e de insegurança documentados.' },
    { t: 'Períodos de reestruturação não configuram exposição aumentada a fatores psicossociais.', ok: false,
      why: 'Errada. São reconhecidos como período de risco elevado.' },
    { t: 'O aumento de carga sobre os remanescentes não repercute em saúde.', ok: false,
      why: 'Errada. Repercute em sobrecarga, adoecimento e acidentes.' },
    { t: 'A comunicação sobre o processo de reestruturação não influencia seus efeitos.', ok: false,
      why: 'Errada. Transparência e previsibilidade reduzem o efeito da incerteza.' }
  ],
  comentario: 'Reestruturação adoece quem fica: mais carga, menos gente, insegurança sobre a próxima rodada. É período de exposição aumentada — e comunicação clara reduz parte do efeito da incerteza.',
  pegadinha: 'Avaliar o impacto apenas sobre os desligados ignora o grupo que segue trabalhando sob a nova carga.',
  refs: ['OIT — riscos psicossociais', 'NR-1 — fatores psicossociais'] },

{ id: 'q-4.8-140', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de risco a trabalhadores expostos a agentes cancerígenos, é CORRETO afirmar:',
  alts: [
    { t: 'Os trabalhadores devem ser informados da natureza cancerígena do agente, das medidas adotadas e da importância do acompanhamento após o fim da exposição — informação que precisa ser dada de modo compreensível e sem produzir fatalismo que desestimule a adesão às medidas.', ok: true,
      why: 'Correta. Informar mal produz negação ou fatalismo, e ambos afastam da prevenção.' },
    { t: 'A informação sobre a natureza cancerígena do agente deve ser omitida para evitar ansiedade.', ok: false,
      why: 'Errada. A omissão retira do trabalhador a base para se proteger e buscar direitos.' },
    { t: 'O acompanhamento após o fim da exposição não precisa ser explicado ao trabalhador.', ok: false,
      why: 'Errada. É o que sustenta a adesão ao seguimento de longo prazo.' },
    { t: 'A forma da comunicação não influencia a adesão às medidas de proteção.', ok: false,
      why: 'Errada. Comunicação fatalista desestimula a adesão.' },
    { t: 'A comunicação de risco encerra a obrigação da empresa quanto ao agente.', ok: false,
      why: 'Errada. Informar não substitui eliminar, substituir ou controlar a exposição.' }
  ],
  comentario: 'Informar que o agente é cancerígeno, o que se faz para controlar e por que o acompanhamento continua depois — em linguagem que não produza fatalismo. E informar nunca substitui controlar.',
  pegadinha: 'Comunicar de forma fatalista produz o mesmo efeito prático de não comunicar: ninguém adere às medidas.',
  refs: ['IARC', 'NR-1', 'Código de Ética Médica'] },

{ id: 'q-4.10-130', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a cobertura vacinal em grupos de trabalhadores e sua avaliação, é CORRETO afirmar:',
  alts: [
    { t: 'A avaliação da cobertura deve ser feita por grupo de risco e não apenas em números globais, pois cobertura elevada no conjunto pode conviver com bolsões de baixa cobertura justamente nos grupos de maior exposição.', ok: true,
      why: 'Correta. A média esconde o setor descoberto.' },
    { t: 'A cobertura vacinal global é indicador suficiente para avaliar o programa.', ok: false,
      why: 'Errada. Esconde diferenças entre grupos de risco.' },
    { t: 'Terceirizados não precisam ser incluídos na avaliação de cobertura.', ok: false,
      why: 'Errada. Estão frequentemente entre os grupos de menor cobertura e maior exposição.' },
    { t: 'Trabalhadores de turnos noturnos apresentam cobertura equivalente à dos demais.', ok: false,
      why: 'Errada. Costumam ter menor acesso a campanhas realizadas em horário comercial.' },
    { t: 'A dificuldade de acesso à vacinação em determinados turnos não é fator gerenciável.', ok: false,
      why: 'Errada. Ampliar horários da campanha é medida direta e eficaz.' }
  ],
  comentario: 'Cobertura global alta convive com bolsões descobertos: terceirizados e turno noturno costumam ficar de fora das campanhas em horário comercial. Avaliar por grupo revela o que a média esconde.',
  pegadinha: 'Reportar cobertura global elevada satisfaz o indicador e deixa descoberto o grupo mais exposto.',
  refs: ['Programa Nacional de Imunizações', 'NR-7', 'NR-32'] },

{ id: 'q-5.4-150', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do perito diante de periciando em situação de vulnerabilidade, é CORRETO afirmar:',
  alts: [
    { t: 'Baixa escolaridade, dificuldade de compreensão e limitações de comunicação exigem adaptação da entrevista e verificação do entendimento — pois relato empobrecido por barreira de comunicação pode ser lido, equivocadamente, como ausência de sintomas.', ok: true,
      why: 'Correta. Quem não consegue descrever pode parecer não ter o que descrever.' },
    { t: 'A entrevista pericial deve ser padronizada, sem adaptação ao periciando.', ok: false,
      why: 'Errada. A adaptação é o que permite obter informação de qualidade.' },
    { t: 'Relato pobre em detalhes indica ausência de sintomas relevantes.', ok: false,
      why: 'Errada. Pode refletir barreira de comunicação ou escolaridade.' },
    { t: 'A presença de acompanhante deve ser sempre recusada na perícia.', ok: false,
      why: 'Errada. Em situações específicas, o acompanhante viabiliza a comunicação.' },
    { t: 'A verificação do entendimento das orientações não integra o ato pericial.', ok: false,
      why: 'Errada. Assegurar que o periciando compreendeu o que foi informado é parte do ato.' }
  ],
  comentario: 'Barreira de comunicação empobrece o relato e pode ser lida como ausência de sintoma. Adaptar a entrevista, verificar o entendimento e, quando necessário, admitir acompanhante é o que produz informação confiável.',
  pegadinha: 'Interpretar relato pobre como quadro leve penaliza quem tem menos recursos para descrever o próprio sofrimento.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-5.5-140', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a reavaliação periódica de restrições funcionais, é CORRETO afirmar:',
  alts: [
    { t: 'Restrições devem ser reavaliadas em intervalos definidos, pois condições evoluem em ambas as direções — e restrição mantida por inércia após a recuperação limita indevidamente o trabalhador, enquanto restrição não revista após piora deixa de protegê-lo.', ok: true,
      why: 'Correta. Restrição desatualizada erra nos dois sentidos.' },
    { t: 'Restrições emitidas devem ser mantidas até que o trabalhador as questione.', ok: false,
      why: 'Errada. A reavaliação periódica é responsabilidade do serviço médico.' },
    { t: 'A recuperação do trabalhador não justifica revisão de restrições previamente emitidas.', ok: false,
      why: 'Errada. Justifica, e a manutenção indevida limita oportunidades.' },
    { t: 'Restrições definitivas dispensam qualquer reavaliação futura.', ok: false,
      why: 'Errada. Mesmo restrições de longo prazo comportam reavaliação diante de mudanças.' },
    { t: 'A revisão de restrição só pode ser feita mediante solicitação da empresa.', ok: false,
      why: 'Errada. Decorre da avaliação médica, independentemente de solicitação.' }
  ],
  comentario: 'Restrição não é definitiva por inércia: reavalia-se periodicamente porque a condição muda nos dois sentidos. Mantida sem revisão, ela limita quem já recuperou; não revista após piora, deixa de proteger.',
  pegadinha: 'Restrição esquecida no prontuário segue limitando o trabalhador anos depois de a condição ter se resolvido.',
  refs: ['NR-7', 'CIF — OMS'] },

{ id: 'q-6.2-140', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação com trabalhadores com deficiência auditiva no serviço de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A comunicação acessível é condição do próprio ato médico, e a ausência de intérprete ou de recurso adequado compromete a anamnese, o consentimento e a compreensão das orientações — não sendo aceitável conduzir a consulta por meio de acompanhante improvisado sem a concordância do trabalhador.', ok: true,
      why: 'Correta. Sem comunicação acessível não há anamnese nem consentimento válidos.' },
    { t: 'A comunicação escrita resolve adequadamente qualquer situação.', ok: false,
      why: 'Errada. Nem todos têm domínio da língua escrita como segunda língua.' },
    { t: 'A presença de acompanhante dispensa a garantia de comunicação acessível.', ok: false,
      why: 'Errada. Compromete a privacidade e nem sempre assegura fidelidade da comunicação.' },
    { t: 'A acessibilidade comunicacional não integra o conceito legal de acessibilidade.', ok: false,
      why: 'Errada. É dimensão expressamente prevista.' },
    { t: 'A dificuldade de comunicação justifica conclusões mais restritivas de aptidão.', ok: false,
      why: 'Errada. A barreira é do serviço, e não pode ser convertida em restrição ao trabalhador.' }
  ],
  comentario: 'Sem comunicação acessível não há anamnese, consentimento nem orientação compreendida. Escrita não resolve para todos, e acompanhante improvisado compromete privacidade — a barreira é do serviço, nunca do trabalhador.',
  pegadinha: 'Converter a dificuldade de comunicação do serviço em restrição de aptidão penaliza o trabalhador por uma falha que não é dele.',
  refs: ['Lei nº 13.146/2015', 'Código de Ética Médica'] },

{ id: 'q-6.3-140', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o rastreamento de doenças cardiovasculares em programas ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'A indicação de rastreamento segue critérios de risco individual e evidência de benefício, e não a conveniência de oferecer exames a todos — cabendo diferenciar rastreamento populacional de avaliação de aptidão para funções de risco, que têm finalidades distintas.', ok: true,
      why: 'Correta. Rastrear e avaliar aptidão são perguntas diferentes com métodos diferentes.' },
    { t: 'Rastreamento populacional e avaliação de aptidão seguem os mesmos critérios.', ok: false,
      why: 'Errada. Têm finalidades e critérios distintos.' },
    { t: 'A oferta ampla de exames cardiológicos a todos os trabalhadores é conduta recomendada.', ok: false,
      why: 'Errada. Sem indicação, produz achados incidentais e investigações desnecessárias.' },
    { t: 'A avaliação de risco individual não influencia a indicação de exames.', ok: false,
      why: 'Errada. É o principal determinante da indicação.' },
    { t: 'Achados de rastreamento devem ser comunicados à empresa para orientar a alocação.', ok: false,
      why: 'Errada. À empresa cabe aptidão e restrição; achados clínicos permanecem sob sigilo.' }
  ],
  comentario: 'Rastreamento populacional e avaliação de aptidão respondem perguntas diferentes. Oferecer exame a todos parece cuidado e produz achado incidental — e, em qualquer caso, à empresa vai aptidão, não achado.',
  pegadinha: 'Tratar o exame ocupacional como check-up geral confunde duas finalidades e gera investigação sem benefício.',
  refs: ['NR-7', 'Critérios de rastreamento — medicina preventiva'] },

{ id: 'q-7.2-140', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o requerimento administrativo e o acesso do trabalhador aos benefícios, é CORRETO afirmar:',
  alts: [
    { t: 'Orientar o trabalhador sobre a existência do direito, os documentos necessários e os prazos integra o cuidado, pois o desconhecimento é uma das principais barreiras de acesso — e a orientação não configura interferência indevida na esfera previdenciária.', ok: true,
      why: 'Correta. Desconhecimento é barreira real, e orientar é parte do cuidado.' },
    { t: 'A orientação sobre direitos previdenciários está fora do escopo do cuidado médico.', ok: false,
      why: 'Errada. Integra o cuidado, sobretudo em agravos relacionados ao trabalho.' },
    { t: 'O desconhecimento sobre direitos não constitui barreira relevante de acesso.', ok: false,
      why: 'Errada. É uma das principais barreiras identificadas.' },
    { t: 'Orientar o trabalhador configura interferência indevida na esfera previdenciária.', ok: false,
      why: 'Errada. Informar sobre a existência do direito não interfere na decisão administrativa.' },
    { t: 'A qualidade dos documentos médicos apresentados não influencia o acesso ao benefício.', ok: false,
      why: 'Errada. Documentação bem elaborada é determinante na instrução do requerimento.' }
  ],
  comentario: 'Informar que o direito existe, quais documentos reunir e quais prazos observar é parte do cuidado — não interferência. E a qualidade do relatório médico é o que instrui bem o requerimento.',
  pegadinha: 'Considerar a orientação sobre direitos como assunto alheio à medicina deixa o trabalhador sem a informação que decide o acesso.',
  refs: ['Lei nº 8.213/1991', 'Código de Ética Médica', 'PNSTT'] },

{ id: 'q-7.3-140', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação da vigilância sanitária com o ministério público em situações de risco à saúde de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'A comunicação de situações de risco não corrigido a órgãos com poder de atuação judicial e extrajudicial amplia as possibilidades de solução — e o termo de ajustamento de conduta é instrumento frequente nesses casos, com prazos e obrigações pactuados.', ok: true,
      why: 'Correta. É a via que costuma destravar situações persistentes.' },
    { t: 'A vigilância não deve comunicar situações de risco a outros órgãos.', ok: false,
      why: 'Errada. A articulação amplia a capacidade de solução.' },
    { t: 'O ministério público não dispõe de instrumentos extrajudiciais nesse campo.', ok: false,
      why: 'Errada. O termo de ajustamento de conduta é instrumento extrajudicial usual.' },
    { t: 'A atuação conjunta reduz a autonomia técnica da vigilância.', ok: false,
      why: 'Errada. Cada órgão preserva sua competência e sua autonomia técnica.' },
    { t: 'Situações de risco persistente após autuação não comportam outras medidas.', ok: false,
      why: 'Errada. É justamente quando a articulação com outros órgãos se torna necessária.' }
  ],
  comentario: 'Risco que persiste depois da autuação pede articulação: comunicar a quem tem instrumento judicial e extrajudicial. O termo de ajustamento de conduta é o caminho mais usado, com prazos pactuados.',
  pegadinha: 'Encerrar a atuação na autuação deixa sem resposta exatamente os casos que não se resolvem com ela.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Lei da Ação Civil Pública'] },

{ id: 'q-7.4-140', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o transporte, a movimentação e o manuseio de materiais, é CORRETO afirmar:',
  alts: [
    { t: 'A prioridade é a mecanização e a eliminação do transporte manual, seguida da adequação de peso, distância, frequência e altura de pega — e a orientação sobre técnica de levantamento, isoladamente, tem eficácia limitada quando as condições da tarefa permanecem inalteradas.', ok: true,
      why: 'Correta. Treinar postura sem mudar carga e frequência não muda o desfecho.' },
    { t: 'O treinamento em técnica de levantamento é a medida de maior eficácia.', ok: false,
      why: 'Errada. Sua eficácia isolada é limitada; a mudança das condições da tarefa é o que importa.' },
    { t: 'O peso da carga é o único parâmetro relevante na avaliação.', ok: false,
      why: 'Errada. Distância, frequência, altura de pega e torção também determinam a carga sobre a coluna.' },
    { t: 'A mecanização não é considerada medida prioritária nesses casos.', ok: false,
      why: 'Errada. Eliminar o transporte manual é a medida de maior hierarquia.' },
    { t: 'A altura de pega e de depósito não influencia o esforço exigido.', ok: false,
      why: 'Errada. Pegar do chão ou acima dos ombros aumenta substancialmente a exigência.' }
  ],
  comentario: 'Movimentação de cargas: mecanizar primeiro, depois ajustar peso, distância, frequência e altura de pega. Treinar técnica sem mudar a tarefa é a intervenção mais oferecida e a de menor efeito.',
  pegadinha: 'A palestra sobre postura para levantar peso é popular justamente porque não muda nada na organização da tarefa.',
  refs: ['NR-17', 'NR-11', 'Equação de levantamento — NIOSH'] },

{ id: 'q-7.5-110', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o acesso do trabalhador às informações a seu respeito transmitidas pelo eSocial, é CORRETO afirmar:',
  alts: [
    { t: 'O trabalhador pode consultar informações que lhe dizem respeito e identificar divergências em relação à sua realidade de trabalho — o que torna a conferência periódica pelo próprio interessado uma via prática de correção antes que o erro se consolide.', ok: true,
      why: 'Correta. Conferir enquanto o vínculo existe é muito mais fácil que corrigir depois.' },
    { t: 'O trabalhador não tem acesso às informações transmitidas a seu respeito.', ok: false,
      why: 'Errada. Há vias de consulta às informações que lhe dizem respeito.' },
    { t: 'Divergências identificadas pelo trabalhador não podem ser corrigidas.', ok: false,
      why: 'Errada. Há procedimento de retificação previsto.' },
    { t: 'A conferência das informações é responsabilidade exclusiva da empresa.', ok: false,
      why: 'Errada. O interessado direto na correção é o próprio trabalhador.' },
    { t: 'Erros identificados tardiamente são corrigidos com a mesma facilidade.', ok: false,
      why: 'Errada. A correção tardia enfrenta dificuldade de comprovação e de reconstituição.' }
  ],
  comentario: 'O trabalhador pode e deve conferir o que foi transmitido sobre ele — e corrigir enquanto o vínculo existe e há como comprovar. Descobrir o erro na hora da aposentadoria é descobrir tarde demais.',
  pegadinha: 'Deixar a conferência inteiramente com a empresa entrega a quem tem menos interesse na correção.',
  refs: ['eSocial', 'LGPD — direitos do titular', 'Lei nº 8.213/1991'] },

{ id: 'q-1.3-140', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de indicadores epidemiológicos na comparação entre setores econômicos, é CORRETO afirmar:',
  alts: [
    { t: 'A comparação exige atenção às diferenças de composição da força de trabalho, de formalização e de capacidade de notificação — pois setores com maior informalidade tendem a apresentar indicadores artificialmente favoráveis por ausência de registro.', ok: true,
      why: 'Correta. Setor que não registra aparece como setor seguro.' },
    { t: 'Setores com menores taxas registradas apresentam necessariamente melhores condições de trabalho.', ok: false,
      why: 'Errada. Podem apenas registrar menos.' },
    { t: 'O grau de formalização do setor não influencia seus indicadores.', ok: false,
      why: 'Errada. Determina diretamente a capacidade de registro e notificação.' },
    { t: 'A composição etária e de tempo de casa não interfere na comparação entre setores.', ok: false,
      why: 'Errada. São fatores que exigem padronização.' },
    { t: 'Indicadores de acidentalidade não são afetados por incentivos à subnotificação.', ok: false,
      why: 'Errada. São diretamente afetados por eles.' }
  ],
  comentario: 'Comparar setores exige olhar formalização, composição da força de trabalho e capacidade de notificação. Setor informal registra pouco e aparece seguro — que é o oposto do que costuma ser.',
  pegadinha: 'Ler taxa baixa como condição melhor premia justamente o setor que menos registra.',
  refs: ['Rothman — Epidemiologia Moderna', 'SINAN', 'PNSTT'] },

{ id: 'q-1.4-120', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a apresentação de resultados do programa de saúde ocupacional à alta direção, é CORRETO afirmar:',
  alts: [
    { t: 'A apresentação deve relacionar os achados de saúde às condições de trabalho e às decisões que dependem da direção, com dados agregados e sem identificação individual — relatórios que apenas informam volumes de exames não sustentam decisão alguma.', ok: true,
      why: 'Correta. O que a direção decide é sobre condições, não sobre número de exames.' },
    { t: 'A apresentação deve incluir casos individuais para dar concretude aos achados.', ok: false,
      why: 'Errada. Casos identificáveis violam o sigilo; a apresentação é agregada.' },
    { t: 'Relatórios de volume de exames realizados são suficientes para orientar decisões.', ok: false,
      why: 'Errada. Não relacionam saúde a condições nem indicam o que decidir.' },
    { t: 'A relação entre achados de saúde e condições de trabalho não interessa à direção.', ok: false,
      why: 'Errada. É exatamente o que fundamenta as decisões de investimento e organização.' },
    { t: 'Dados agregados de setores muito pequenos podem ser apresentados sem restrição.', ok: false,
      why: 'Errada. Em grupos pequenos, o agregado reidentifica e exige agregação em nível superior.' }
  ],
  comentario: 'Relatório à direção conecta achados de saúde a condições e às decisões que só ela pode tomar — sempre agregado, com cuidado extra em setores pequenos, onde o agregado reidentifica.',
  pegadinha: 'Apresentar volume de exames entrega atividade e não entrega informação para decisão.',
  refs: ['NR-7', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-1.6-120', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a participação de trabalhadores e suas entidades na formulação de políticas de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A participação é princípio estruturante do campo, com raízes no movimento operário pela saúde, e traz para a formulação o conhecimento sobre o trabalho real — informação que os documentos técnicos e as bases de dados não contêm.', ok: true,
      why: 'Correta. É o traço histórico que distingue a saúde do trabalhador da medicina do trabalho tradicional.' },
    { t: 'A participação dos trabalhadores é etapa consultiva sem efeito sobre a formulação.', ok: false,
      why: 'Errada. É princípio estruturante do campo.' },
    { t: 'O conhecimento dos trabalhadores sobre o próprio trabalho não acrescenta à formulação técnica.', ok: false,
      why: 'Errada. É informação que nenhuma outra fonte fornece.' },
    { t: 'A origem histórica do campo não guarda relação com a participação dos trabalhadores.', ok: false,
      why: 'Errada. O movimento operário pela saúde é uma de suas raízes constitutivas.' },
    { t: 'A participação sindical compromete a objetividade técnica das políticas.', ok: false,
      why: 'Errada. Acrescenta informação sobre a realidade do trabalho, sem substituir a análise técnica.' }
  ],
  comentario: 'A participação não é consulta protocolar: é princípio estruturante, com raiz no movimento operário pela saúde, e traz o conhecimento sobre o trabalho real que nenhum documento técnico contém.',
  pegadinha: 'Tratar participação como etapa consultiva descarta a informação que justifica sua existência.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Modelo operário italiano'] },

{ id: 'q-1.7-120', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a assistência ao trabalhador acidentado na rede pública, é CORRETO afirmar:',
  alts: [
    { t: 'O atendimento independe de comprovação de vínculo ou de emissão prévia de comunicação de acidente, e o registro da relação com o trabalho no prontuário e na notificação é o que permite, depois, o reconhecimento e a análise coletiva do caso.', ok: true,
      why: 'Correta. Atende-se primeiro; o registro é o que preserva a informação para depois.' },
    { t: 'O atendimento depende da apresentação prévia da comunicação de acidente.', ok: false,
      why: 'Errada. O atendimento é universal e independe de qualquer documento.' },
    { t: 'O registro da relação com o trabalho no prontuário é irrelevante para o caso.', ok: false,
      why: 'Errada. É o que sustenta o reconhecimento posterior.' },
    { t: 'Trabalhadores informais devem ser encaminhados a serviços privados.', ok: false,
      why: 'Errada. O atendimento no sistema público é universal.' },
    { t: 'A emissão da comunicação de acidente não pode partir do serviço público que atendeu.', ok: false,
      why: 'Errada. O médico assistente é legitimado a emiti-la.' }
  ],
  comentario: 'Atende-se sem exigir documento nenhum — e registra-se a relação com o trabalho no prontuário e na notificação. O serviço público que atendeu também pode emitir a comunicação de acidente.',
  pegadinha: 'Condicionar o atendimento a documento de vínculo contraria a universalidade e atrasa o socorro.',
  refs: ['Lei nº 8.080/1990', 'Lei nº 8.213/1991 — art. 22', 'PNSTT'] },

{ id: 'q-1.8-120', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a proteção de trabalhadores que colaboram com ações de vigilância, é CORRETO afirmar:',
  alts: [
    { t: 'A identidade de quem presta informações deve ser preservada, pois o receio de represália é a principal barreira à colaboração — e a ausência dessa garantia inviabiliza o acesso à informação sobre o trabalho real.', ok: true,
      why: 'Correta. Sem garantia de anonimato, ninguém fala.' },
    { t: 'A identificação dos informantes é necessária para dar validade ao relatório.', ok: false,
      why: 'Errada. O relatório se sustenta na verificação técnica, não na identificação de quem informou.' },
    { t: 'O receio de represália não é barreira relevante à colaboração.', ok: false,
      why: 'Errada. É a principal barreira identificada.' },
    { t: 'Entrevistas com trabalhadores devem ser realizadas na presença da chefia.', ok: false,
      why: 'Errada. A presença da chefia inibe o relato e compromete a informação obtida.' },
    { t: 'Informações obtidas de trabalhadores não devem orientar a inspeção.', ok: false,
      why: 'Errada. Orientam onde olhar e o que verificar tecnicamente.' }
  ],
  comentario: 'Preservar a identidade de quem informa é condição de obter informação. Entrevista na presença da chefia não produz relato — produz confirmação do que a chefia já disse.',
  pegadinha: 'Entrevistar o trabalhador com o supervisor ao lado é o procedimento que garante não descobrir nada.',
  refs: ['PNSTT', 'Legislação sanitária', 'Lei nº 8.080/1990'] },

{ id: 'q-1.9-120', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso das bases de notificação para estimar a magnitude dos agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'As bases fornecem estimativas mínimas, dado o reconhecimento da subnotificação — de modo que os números observados devem ser lidos como piso, e não como retrato completo do problema.', ok: true,
      why: 'Correta. O dado disponível é o mínimo, nunca o total.' },
    { t: 'As bases de notificação fornecem estimativa completa da magnitude dos agravos.', ok: false,
      why: 'Errada. A subnotificação é reconhecida e substancial.' },
    { t: 'A subnotificação afeta igualmente todos os agravos notificáveis.', ok: false,
      why: 'Errada. Agravos crônicos e de nexo menos evidente são muito mais subnotificados.' },
    { t: 'A comparação entre períodos não é afetada por mudanças na capacidade de notificação.', ok: false,
      why: 'Errada. Aumento de notificações pode refletir melhora do registro, não piora da situação.' },
    { t: 'Estudos de base populacional não acrescentam à estimativa fornecida pelas bases.', ok: false,
      why: 'Errada. São justamente o que permite estimar a magnitude da subnotificação.' }
  ],
  comentario: 'Base de notificação dá piso, não total — e a subnotificação é maior nos agravos crônicos. Aumento de notificações pode ser melhora do registro; comparar períodos exige considerar isso.',
  pegadinha: 'Ler aumento de notificações como piora das condições confunde melhora da vigilância com agravamento do problema.',
  refs: ['SINAN', 'Estudos de base populacional em saúde do trabalhador'] },

{ id: 'q-1.10-120', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre promoção da saúde e prevenção de riscos ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'As duas abordagens são complementares e não substitutivas, e programas de promoção não podem ocupar o espaço da prevenção de riscos — situação que ocorre quando a empresa investe em ações de estilo de vida enquanto mantém exposições não controladas.', ok: true,
      why: 'Correta. Promoção não compensa exposição não controlada.' },
    { t: 'Programas de promoção da saúde podem substituir medidas de controle de exposições.', ok: false,
      why: 'Errada. São abordagens complementares, com objetos distintos.' },
    { t: 'A promoção da saúde não tem lugar em ambientes com riscos ocupacionais relevantes.', ok: false,
      why: 'Errada. Tem lugar, desde que não substitua o controle dos riscos.' },
    { t: 'A prevenção de riscos ocupacionais é responsabilidade do trabalhador.', ok: false,
      why: 'Errada. É obrigação do empregador.' },
    { t: 'A coexistência das duas abordagens gera conflito técnico insuperável.', ok: false,
      why: 'Errada. São complementares e se reforçam quando bem articuladas.' }
  ],
  comentario: 'Promoção e prevenção se complementam — e a distorção aparece quando a empresa investe em ginástica e alimentação enquanto mantém a exposição sem controle. Uma não paga a conta da outra.',
  pegadinha: 'Programa de promoção robusto convivendo com exposição descontrolada é deslocamento de foco, não cuidado.',
  refs: ['OMS — ambientes de trabalho saudáveis', 'NR-1', 'PNSTT'] }

);
