/* Lote AR — 7.1 a 7.8, 1.3 a 1.10. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.2-120', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o encaminhamento de segurado para avaliação de aposentadoria por incapacidade permanente, é CORRETO afirmar:',
  alts: [
    { t: 'A concessão pressupõe incapacidade insuscetível de reabilitação para atividade que garanta a subsistência, e o segurado permanece sujeito a reavaliações periódicas — não sendo, em regra, benefício definitivamente irrevisível.', ok: true,
      why: 'Correta. Há previsão de reavaliação periódica, com exceções etárias.' },
    { t: 'A concessão do benefício encerra definitivamente qualquer reavaliação.', ok: false,
      why: 'Errada. Há previsão de reavaliação periódica, com regras de dispensa em situações específicas.' },
    { t: 'A incapacidade para a função habitual é suficiente para a concessão.', ok: false,
      why: 'Errada. Exige-se incapacidade insuscetível de reabilitação para atividade que garanta a subsistência.' },
    { t: 'A tentativa de reabilitação profissional é irrelevante para a análise.', ok: false,
      why: 'Errada. A insuscetibilidade de reabilitação é elemento do próprio conceito.' },
    { t: 'O retorno voluntário ao trabalho não repercute sobre o benefício.', ok: false,
      why: 'Errada. Tem repercussão prevista sobre a manutenção do benefício.' }
  ],
  comentario: 'Aposentadoria por incapacidade permanente exige insuscetibilidade de reabilitação para atividade que garanta subsistência — não basta não poder exercer a função habitual. E há reavaliação periódica, com dispensas específicas.',
  pegadinha: 'Confundir incapacidade para a função com incapacidade para qualquer atividade antecipa uma exclusão definitiva.',
  refs: ['Lei nº 8.213/1991 — arts. 42 a 47', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-121', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a manutenção da qualidade de segurado e seus reflexos no acesso a benefícios, é CORRETO afirmar:',
  alts: [
    { t: 'Há período em que o trabalhador mantém a qualidade de segurado mesmo sem contribuir, com prazos que variam conforme o tempo de contribuição e a situação de desemprego — período determinante para o acesso a benefícios em agravos de manifestação tardia.', ok: true,
      why: 'Correta. É o que decide o acesso quando a doença se manifesta depois do desligamento.' },
    { t: 'A qualidade de segurado cessa imediatamente com o fim das contribuições.', ok: false,
      why: 'Errada. Há período de manutenção previsto em lei.' },
    { t: 'O período de manutenção é igual para todos os segurados.', ok: false,
      why: 'Errada. Varia conforme o tempo de contribuição e a comprovação de desemprego.' },
    { t: 'A manutenção da qualidade de segurado não influencia o acesso a benefício por doença ocupacional.', ok: false,
      why: 'Errada. É determinante quando a manifestação ocorre após o desligamento.' },
    { t: 'A comprovação de desemprego não altera o período de manutenção.', ok: false,
      why: 'Errada. Pode ampliar o período previsto.' }
  ],
  comentario: 'Período de graça: mantém a qualidade de segurado sem contribuir, com prazo variável por tempo de contribuição e desemprego comprovado. É o que decide o acesso quando a doença ocupacional aparece meses após a saída.',
  pegadinha: 'Supor perda imediata da qualidade de segurado ao desligamento fecha o acesso que a lei mantém aberto.',
  refs: ['Lei nº 8.213/1991 — art. 15', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.3-120', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação sanitária em situações de contaminação que atingem trabalhadores e comunidade, é CORRETO afirmar:',
  alts: [
    { t: 'A investigação deve mapear a fonte, as vias de exposição e as populações atingidas, com comunicação de risco às pessoas envolvidas — e trabalhadores costumam ser o grupo com maior dose acumulada, o que os torna prioritários na avaliação.', ok: true,
      why: 'Correta. Quem trabalha na fonte recebe a maior dose.' },
    { t: 'A investigação deve se restringir à população residente do entorno.', ok: false,
      why: 'Errada. Os trabalhadores da fonte são o grupo de maior exposição.' },
    { t: 'A comunicação de risco às populações atingidas é etapa dispensável.', ok: false,
      why: 'Errada. É componente essencial da resposta sanitária.' },
    { t: 'A identificação das vias de exposição não altera as medidas adotadas.', ok: false,
      why: 'Errada. Define quais medidas interrompem efetivamente a exposição.' },
    { t: 'Trabalhadores contratados temporariamente não integram a população a avaliar.', ok: false,
      why: 'Errada. A avaliação alcança todos os expostos, independentemente do vínculo.' }
  ],
  comentario: 'Em contaminação, o trabalhador é o mais exposto e o primeiro a avaliar — inclusive o temporário. Mapear fonte e vias define as medidas, e comunicar risco é parte da resposta, não sua consequência.',
  pegadinha: 'Investigar só a comunidade do entorno deixa de fora quem esteve mais perto da fonte por mais tempo.',
  refs: ['Lei nº 8.080/1990', 'PNSTT', 'Vigilância em saúde ambiental'] },

{ id: 'q-7.4-120', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as condições sanitárias e de conforto nos locais de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Instalações sanitárias, vestiários, locais para refeição e fornecimento de água potável são exigências com repercussão direta em saúde — e sua precariedade se associa a restrição voluntária de ingestão hídrica e a adiamento de necessidades fisiológicas, com efeitos clínicos concretos.', ok: true,
      why: 'Correta. Banheiro distante e sujo faz o trabalhador beber menos água.' },
    { t: 'Essas exigências são apenas questões de conforto, sem repercussão em saúde.', ok: false,
      why: 'Errada. Têm repercussão clínica documentada.' },
    { t: 'O fornecimento de água potável pode ser substituído por permissão para o trabalhador trazer a sua.', ok: false,
      why: 'Errada. O fornecimento é obrigação do empregador.' },
    { t: 'A distância das instalações sanitárias em relação ao posto não é fator relevante.', ok: false,
      why: 'Errada. Distância e tempo de deslocamento influenciam diretamente o uso.' },
    { t: 'Vestiários com separação adequada não integram as exigências quando há poucos trabalhadores.', ok: false,
      why: 'Errada. A exigência independe do número, com dimensionamento proporcional.' }
  ],
  comentario: 'Banheiro, vestiário, refeitório e água potável não são conforto: banheiro distante e sujo produz restrição hídrica e retenção urinária. São exigências com desfecho clínico.',
  pegadinha: 'Classificar essas condições como conforto retira do escopo de saúde algo que produz infecção urinária e cálculo renal.',
  refs: ['NR-24', 'NR-18', 'NR-31'] },

{ id: 'q-7.5-090', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a implantação dos eventos de saúde e segurança no eSocial nas empresas, é CORRETO afirmar:',
  alts: [
    { t: 'A implantação exige integração entre as áreas de pessoal, segurança e medicina do trabalho, com definição de responsáveis e fluxos — e a atribuição do preenchimento a quem não domina o conteúdo técnico é causa frequente de informação inconsistente.', ok: true,
      why: 'Correta. Quem opera o sistema não é quem detém a informação técnica.' },
    { t: 'A implantação é responsabilidade exclusiva da área de tecnologia da informação.', ok: false,
      why: 'Errada. Exige participação das áreas que produzem a informação.' },
    { t: 'O conteúdo técnico pode ser preenchido por qualquer setor sem prejuízo.', ok: false,
      why: 'Errada. É a principal causa de inconsistência nos eventos transmitidos.' },
    { t: 'A definição de responsáveis pelos eventos é formalidade sem efeito prático.', ok: false,
      why: 'Errada. Define quem responde pela informação e quem acompanha prazos.' },
    { t: 'Não é necessário conferir a consistência entre os eventos transmitidos e os documentos internos.', ok: false,
      why: 'Errada. A conferência é o que evita divergência detectável por cruzamento.' }
  ],
  comentario: 'Implantar os eventos exige integração entre pessoal, segurança e medicina, com responsáveis definidos e conferência contra os documentos internos. Delegar o conteúdo técnico a quem opera o sistema produz inconsistência.',
  pegadinha: 'Tratar a implantação como projeto de sistema deixa quem produz a informação fora do processo.',
  refs: ['eSocial — manual de orientação', 'NR-1', 'NR-7'] },

{ id: 'q-7.6-090', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de achados de exame ao trabalhador examinado, é CORRETO afirmar:',
  alts: [
    { t: 'O trabalhador tem direito de conhecer os resultados dos exames a que foi submetido e de receber orientação sobre eles, inclusive quando os achados não afetam a conclusão de aptidão — e o encaminhamento para assistência é parte dessa responsabilidade.', ok: true,
      why: 'Correta. O achado que não muda a aptidão ainda é informação de saúde da pessoa.' },
    { t: 'Achados que não afetam a aptidão não precisam ser comunicados.', ok: false,
      why: 'Errada. O trabalhador tem direito de conhecer sua condição de saúde.' },
    { t: 'A comunicação dos resultados pode ser feita por meio do setor de pessoal.', ok: false,
      why: 'Errada. É comunicação médica, direta ao trabalhador.' },
    { t: 'O encaminhamento para assistência não integra a responsabilidade do médico do trabalho.', ok: false,
      why: 'Errada. Identificado o achado, o encaminhamento é parte do cuidado.' },
    { t: 'O trabalhador não tem direito a cópia dos resultados de seus exames.', ok: false,
      why: 'Errada. Tem direito de acesso aos próprios dados de saúde.' }
  ],
  comentario: 'Achado encontrado é informado ao trabalhador, com orientação e encaminhamento — mesmo quando não altera a aptidão. E a comunicação é médica e direta, não pelo setor de pessoal.',
  pegadinha: 'Guardar o achado irrelevante para a aptidão retira da pessoa uma informação que é dela.',
  refs: ['Código de Ética Médica', 'NR-7', 'LGPD'] },

{ id: 'q-7.7-090', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação simultânea do médico como assistente e como perito do mesmo paciente, é CORRETO afirmar:',
  alts: [
    { t: 'É vedado periciar paciente de quem se é ou foi assistente, por incompatibilidade entre as funções — vedação que protege tanto a relação assistencial quanto a imparcialidade exigida do ato pericial.', ok: true,
      why: 'Correta. As duas funções têm objetos e compromissos incompatíveis.' },
    { t: 'A atuação simultânea é admissível quando o paciente concorda.', ok: false,
      why: 'Errada. A vedação não é afastada por concordância do periciando.' },
    { t: 'A vedação se aplica apenas quando a assistência é atual.', ok: false,
      why: 'Errada. Alcança também quem foi assistente do periciando.' },
    { t: 'A vedação decorre apenas de risco de favorecimento ao paciente.', ok: false,
      why: 'Errada. Protege também a relação assistencial, que se compromete com a função pericial.' },
    { t: 'O médico do trabalho da empresa não sofre restrição alguma ao periciar trabalhador que atende.', ok: false,
      why: 'Errada. O conflito de papéis exige atenção e, conforme a situação, impedimento.' }
  ],
  comentario: 'Assistente e perito do mesmo paciente é incompatível — inclusive quando a assistência foi passada, e mesmo com concordância dele. A vedação protege as duas relações, não apenas a imparcialidade.',
  pegadinha: 'Achar que o consentimento do periciando resolve o conflito ignora que a vedação não é disponível.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-7.8-090', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o encarregado de proteção de dados e a governança em serviços de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A organização deve indicar canal de comunicação com titulares e autoridade, definir políticas de acesso e retenção e treinar quem manuseia dados — e em serviços de saúde ocupacional o desenho dessas políticas precisa respeitar o sigilo profissional, que restringe o acesso mesmo dentro da própria organização.', ok: true,
      why: 'Correta. A governança de dados não pode abrir o que o sigilo médico fecha.' },
    { t: 'A governança de dados autoriza o acesso interno amplo a dados de saúde para fins de auditoria.', ok: false,
      why: 'Errada. O sigilo profissional restringe o acesso mesmo internamente.' },
    { t: 'A indicação de canal de comunicação com titulares é facultativa.', ok: false,
      why: 'Errada. É requisito para o exercício dos direitos do titular.' },
    { t: 'Políticas de retenção não se aplicam a dados de saúde ocupacional.', ok: false,
      why: 'Errada. Aplicam-se, respeitados os prazos legais de guarda, que são longos nesse campo.' },
    { t: 'O treinamento de quem manuseia dados é medida sem efeito prático.', ok: false,
      why: 'Errada. Boa parte dos incidentes decorre de manuseio inadequado por pessoas não treinadas.' }
  ],
  comentario: 'Governança de dados em saúde ocupacional convive com o sigilo profissional: canal para titulares, políticas de acesso e retenção com prazos longos, e treinamento — sem abrir acesso interno a quem o sigilo exclui.',
  pegadinha: 'Justificar acesso interno amplo por "governança" ou "auditoria" contorna o sigilo pela via administrativa.',
  refs: ['LGPD — arts. 41 e 46', 'Código de Ética Médica'] },

{ id: 'q-7.1-110', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o afastamento por doença e a responsabilidade pelo pagamento nos primeiros dias, é CORRETO afirmar:',
  alts: [
    { t: 'Os primeiros dias de afastamento por incapacidade são de responsabilidade do empregador, cabendo à previdência o período subsequente — regra que cria incentivo econômico à contestação de atestados curtos e à pressão pelo retorno precoce.', ok: true,
      why: 'Correta. É de onde vem boa parte da fricção em torno de atestados de poucos dias.' },
    { t: 'A previdência arca com o afastamento desde o primeiro dia em qualquer hipótese.', ok: false,
      why: 'Errada. Há período inicial de responsabilidade do empregador.' },
    { t: 'A regra de pagamento inicial não gera qualquer efeito sobre a prática de aceitação de atestados.', ok: false,
      why: 'Errada. Cria incentivo econômico à contestação de afastamentos curtos.' },
    { t: 'Afastamentos sucessivos pela mesma doença são sempre tratados como eventos independentes.', ok: false,
      why: 'Errada. Há regras específicas para afastamentos sucessivos em curto intervalo.' },
    { t: 'O médico deve considerar o impacto financeiro para a empresa ao definir o tempo de afastamento.', ok: false,
      why: 'Errada. A definição é técnica e não pode ser modulada por conveniência econômica.' }
  ],
  comentario: 'Os primeiros dias são do empregador, o restante da previdência — e é dessa regra que nasce a pressão sobre atestados curtos. A definição do tempo de afastamento, porém, é técnica e não financeira.',
  pegadinha: 'Ajustar o tempo de afastamento ao impacto financeiro da empresa converte decisão clínica em decisão contábil.',
  refs: ['Lei nº 8.213/1991 — art. 60', 'CLT'] },

{ id: 'q-1.3-130', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a leitura crítica de um estudo que sustenta associação entre exposição ocupacional e desfecho, é CORRETO afirmar:',
  alts: [
    { t: 'A avaliação considera delineamento, forma de aferição da exposição, controle de confundimento, magnitude e precisão da associação e coerência com o conhecimento prévio — e nenhum estudo isolado, por melhor que seja, encerra a questão.', ok: true,
      why: 'Correta. Corpo de evidência, não estudo único.' },
    { t: 'Um estudo bem conduzido é suficiente para estabelecer causalidade.', ok: false,
      why: 'Errada. A causalidade se sustenta em conjunto de evidências.' },
    { t: 'A forma de aferição da exposição é detalhe metodológico de pouca relevância.', ok: false,
      why: 'Errada. É frequentemente o ponto mais frágil dos estudos ocupacionais.' },
    { t: 'Associações de pequena magnitude devem ser descartadas de imediato.', ok: false,
      why: 'Errada. Podem ter grande impacto quando a exposição é frequente na população.' },
    { t: 'A coerência com o conhecimento prévio não integra a avaliação crítica.', ok: false,
      why: 'Errada. É um dos critérios clássicos de apreciação de causalidade.' }
  ],
  comentario: 'Ler criticamente é olhar delineamento, aferição da exposição, confundimento, magnitude, precisão e coerência — e lembrar que associação pequena com exposição muito frequente pode importar muito.',
  pegadinha: 'Descartar associação de pequena magnitude ignora que o impacto populacional depende também da prevalência da exposição.',
  refs: ['Rothman — Epidemiologia Moderna', 'Fletcher — Epidemiologia Clínica'] },

{ id: 'q-1.4-110', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a gestão de contratos de serviços de saúde ocupacional terceirizados, é CORRETO afirmar:',
  alts: [
    { t: 'A contratação por menor preço, sem especificar tempo por exame, qualificação e escopo de atuação, tende a produzir serviço restrito à emissão de documentos — e a empresa contratante permanece responsável pelo cumprimento das obrigações de saúde e segurança.', ok: true,
      why: 'Correta. Terceirizar a execução não terceiriza a obrigação.' },
    { t: 'A terceirização transfere à prestadora a responsabilidade pelas obrigações de saúde e segurança.', ok: false,
      why: 'Errada. A contratante permanece responsável.' },
    { t: 'A especificação de tempo por exame no contrato é detalhe irrelevante.', ok: false,
      why: 'Errada. Determina diretamente a qualidade do que é possível fazer no atendimento.' },
    { t: 'A qualificação dos profissionais não precisa constar do contrato.', ok: false,
      why: 'Errada. É requisito que a contratante deve especificar e verificar.' },
    { t: 'A avaliação da qualidade do serviço prestado se resume à conferência de documentos entregues.', ok: false,
      why: 'Errada. Documento entregue não demonstra que o exame foi adequadamente realizado.' }
  ],
  comentario: 'Contrato por menor preço sem especificar tempo, qualificação e escopo compra emissão de documento. E a obrigação continua sendo da contratante — que precisa avaliar mais do que a entrega de papéis.',
  pegadinha: 'Medir a prestadora pelo volume de documentos entregues premia exatamente o que se quer evitar.',
  refs: ['NR-4', 'NR-7', 'NR-1'] },

{ id: 'q-1.6-110', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a saúde do trabalhador de plataformas digitais e do trabalho por aplicativo, é CORRETO afirmar:',
  alts: [
    { t: 'Esses trabalhadores acumulam exposição a riscos de trânsito, jornadas longas, pressão algorítmica por tempo de resposta e ausência de cobertura por serviços ocupacionais — o que os torna grupo prioritário para ações de vigilância no território.', ok: true,
      why: 'Correta. Alta exposição somada a ausência total de estrutura de proteção.' },
    { t: 'A ausência de vínculo formal reduz a exposição a riscos ocupacionais desse grupo.', ok: false,
      why: 'Errada. Reduz a proteção, não a exposição.' },
    { t: 'A pressão por tempo de resposta não constitui fator de risco relevante.', ok: false,
      why: 'Errada. Associa-se a comportamento de risco no trânsito e a sofrimento psíquico.' },
    { t: 'Esses trabalhadores são cobertos pelos programas ocupacionais das plataformas.', ok: false,
      why: 'Errada. Em regra não há cobertura por serviços de medicina do trabalho.' },
    { t: 'Acidentes desses trabalhadores não devem ser objeto de notificação em saúde.', ok: false,
      why: 'Errada. A notificação independe do vínculo.' }
  ],
  comentario: 'Trabalho por aplicativo soma trânsito, jornada longa e pressão algorítmica a nenhuma cobertura ocupacional. É prioridade de vigilância no território — e seus acidentes são notificáveis como quaisquer outros.',
  pegadinha: 'Informalidade reduz proteção e não exposição; tratar as duas como equivalentes apaga o grupo das estatísticas.',
  refs: ['PNSTT', 'OIT — trabalho em plataformas digitais'] },

{ id: 'q-1.7-110', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a integração entre serviços de saúde ocupacional das empresas e a rede pública, é CORRETO afirmar:',
  alts: [
    { t: 'A articulação melhora a continuidade do cuidado e a qualidade da informação em ambos os lados — o serviço da empresa conhece a exposição e a rede pública conduz o tratamento —, e sua ausência produz atendimentos paralelos que não se comunicam.', ok: true,
      why: 'Correta. Cada lado tem metade da informação necessária.' },
    { t: 'Os dois sistemas devem operar de forma independente para preservar o sigilo.', ok: false,
      why: 'Errada. A articulação é possível com autorização do trabalhador e preserva o sigilo.' },
    { t: 'O serviço da empresa não detém informação útil ao tratamento na rede pública.', ok: false,
      why: 'Errada. Detém a informação sobre exposição e exigências da função, que a rede não tem.' },
    { t: 'A rede pública não deve considerar a ocupação do paciente na condução do caso.', ok: false,
      why: 'Errada. A ocupação é elemento diagnóstico e terapêutico relevante.' },
    { t: 'A articulação exige compartilhamento irrestrito de prontuários entre os serviços.', ok: false,
      why: 'Errada. O compartilhamento é limitado ao necessário e depende de autorização do trabalhador.' }
  ],
  comentario: 'Serviço da empresa sabe da exposição; a rede pública conduz o tratamento. Articular os dois, com autorização e no limite do necessário, evita dois atendimentos paralelos que nunca se encontram.',
  pegadinha: 'Invocar o sigilo para justificar a não comunicação transforma proteção em isolamento do cuidado.',
  refs: ['PNSTT', 'Código de Ética Médica', 'Lei nº 8.080/1990'] },

{ id: 'q-1.8-110', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de mapas de risco elaborados com participação dos trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Constituem instrumento de visualização coletiva dos riscos por setor, com valor pedagógico e de participação — mas não substituem a avaliação técnica quantitativa, funcionando como complemento e ponto de partida para ela.', ok: true,
      why: 'Correta. Complementa, aproxima e não mede.' },
    { t: 'O mapa de risco substitui a avaliação quantitativa das exposições.', ok: false,
      why: 'Errada. Não fornece medição nem comparação com limites.' },
    { t: 'O mapa deve ser elaborado exclusivamente pela área técnica.', ok: false,
      why: 'Errada. A elaboração participativa é o que lhe dá valor pedagógico e de reconhecimento.' },
    { t: 'O mapa não tem utilidade para a vigilância em saúde do trabalhador.', ok: false,
      why: 'Errada. Revela a percepção de risco dos trabalhadores e orienta a investigação.' },
    { t: 'A percepção de risco dos trabalhadores não deve ser considerada na identificação de perigos.', ok: false,
      why: 'Errada. É fonte primária sobre condições que a inspeção pontual não capta.' }
  ],
  comentario: 'Mapa de risco vale pela construção coletiva: revela a percepção de quem trabalha e orienta onde investigar. Não mede nada — e por isso complementa, sem substituir, a avaliação técnica.',
  pegadinha: 'Elaborar o mapa apenas na área técnica descarta justamente a informação que o justifica.',
  refs: ['NR-5', 'PNSTT'] },

{ id: 'q-1.9-110', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o fluxo da informação após o preenchimento da ficha de notificação, é CORRETO afirmar:',
  alts: [
    { t: 'A ficha é encaminhada à vigilância municipal, que a insere no sistema, consolida e encaminha aos níveis estadual e federal — e o retorno da análise aos serviços notificadores é o que sustenta a qualidade e a continuidade da notificação.', ok: true,
      why: 'Correta. Fluxo ascendente de dados e descendente de análise.' },
    { t: 'A notificação é inserida diretamente na base federal pelo serviço notificador.', ok: false,
      why: 'Errada. O fluxo passa pela vigilância municipal.' },
    { t: 'A consolidação municipal não agrega valor à informação.', ok: false,
      why: 'Errada. É onde ocorrem a crítica dos dados e a articulação com a ação local.' },
    { t: 'O retorno da informação aos serviços notificadores é dispensável.', ok: false,
      why: 'Errada. É determinante da adesão e da qualidade do preenchimento.' },
    { t: 'Fichas com campos incompletos são automaticamente corrigidas pelo sistema.', ok: false,
      why: 'Errada. A correção depende de busca ativa da informação faltante.' }
  ],
  comentario: 'Fluxo: serviço notifica, vigilância municipal insere e critica, consolida-se para estado e federação — e a análise volta para quem notificou. Sem esse retorno, a notificação desanima e a qualidade cai.',
  pegadinha: 'Esperar que o sistema corrija campos em branco substitui busca ativa por otimismo.',
  refs: ['SINAN', 'Ministério da Saúde — fluxos de notificação'] },

{ id: 'q-1.10-110', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre programas de alimentação do trabalhador e sua relação com a saúde, é CORRETO afirmar:',
  alts: [
    { t: 'A oferta alimentar no local de trabalho, o tempo real disponível para a refeição e as condições do local de alimentação influenciam diretamente o padrão alimentar — de modo que orientar hábitos sem alterar essas condições transfere ao trabalhador uma escolha que ele não tem.', ok: true,
      why: 'Correta. Não há escolha alimentar quando o intervalo real é de quinze minutos.' },
    { t: 'O padrão alimentar do trabalhador depende exclusivamente de escolhas individuais.', ok: false,
      why: 'Errada. Oferta, tempo e local condicionam fortemente a escolha.' },
    { t: 'O tempo disponível para a refeição não influencia a qualidade da alimentação.', ok: false,
      why: 'Errada. Intervalo curto favorece refeições rápidas e de pior composição.' },
    { t: 'As condições do local de refeição não têm repercussão em saúde.', ok: false,
      why: 'Errada. Local inadequado desestimula a refeição adequada e favorece comer no posto.' },
    { t: 'Programas de alimentação não têm relação com desfechos de saúde ocupacional.', ok: false,
      why: 'Errada. Repercutem sobre estado nutricional, doenças crônicas e desempenho.' }
  ],
  comentario: 'Alimentação no trabalho depende do que se oferece, de quanto tempo se tem e de onde se come. Orientar hábito sem mexer nisso transfere ao trabalhador uma decisão que a organização já tomou por ele.',
  pegadinha: 'Palestra de nutrição para quem tem quinze minutos e uma máquina de salgados é orientação sem objeto.',
  refs: ['NR-24', 'Programa de Alimentação do Trabalhador', 'OMS'] },

{ id: 'q-1.5-110', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a gestão de mudanças em sistemas de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Alterações de processo, equipamento, layout, quadro de pessoal ou organização do trabalho devem ser precedidas de análise de risco — e a ausência dessa análise em mudanças aparentemente pequenas é causa reconhecida de acidentes.', ok: true,
      why: 'Correta. Mudança pequena sem análise é origem clássica de evento inesperado.' },
    { t: 'Apenas mudanças de grande porte exigem análise prévia de risco.', ok: false,
      why: 'Errada. Mudanças pequenas frequentemente introduzem riscos não previstos.' },
    { t: 'Alterações no quadro de pessoal não configuram mudança relevante.', ok: false,
      why: 'Errada. Alteram experiência disponível, ritmo e supervisão.' },
    { t: 'Mudanças temporárias dispensam análise por sua curta duração.', ok: false,
      why: 'Errada. Arranjos temporários são situação de risco reconhecida.' },
    { t: 'A análise de mudança se restringe a aspectos técnicos do equipamento.', ok: false,
      why: 'Errada. Alcança também organização do trabalho e interfaces entre equipes.' }
  ],
  comentario: 'Gestão de mudanças: processo, equipamento, layout, pessoal e organização — inclusive as pequenas e as temporárias, que são justamente onde o risco não previsto aparece.',
  pegadinha: 'O arranjo provisório "só até semana que vem" é a mudança que menos recebe análise e mais produz acidente.',
  refs: ['ISO 45001', 'NR-1'] }

);
