/* Lote AU — fechamento final das metas por tema. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.2-150', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a pressões anormais em trabalho subaquático, é CORRETO afirmar:',
  alts: [
    { t: 'Exige avaliação médica específica, controle de tempo e profundidade e registro dos perfis de mergulho', ok: true,
      why: 'Correta. Sem registro dos perfis, não há como avaliar a exposição acumulada.' },
    { t: 'Exige avaliação específica e tabelas de descompressão, sendo dispensável o registro individual dos perfis.', ok: false,
      why: 'Errada. É a base para avaliar exposição acumulada e investigar agravos tardios.' },
    { t: 'Exige controle de tempo e profundidade, sendo a avaliação médica igual à de qualquer outra função.', ok: false,
      why: 'Errada. Exige avaliação específica, com atenção a condições que contraindicam a atividade.' },
    { t: 'Exige avaliação específica e registro dos perfis, não sendo a osteonecrose disbárica agravo relacionado.', ok: false,
      why: 'Errada. É agravo reconhecido em mergulhadores e trabalhadores em ar comprimido.' },
    { t: 'Exige controle rigoroso durante a atividade, sem necessidade de acompanhamento após a saída dela.', ok: false,
      why: 'Errada. Agravos de manifestação tardia justificam acompanhamento posterior.' }
  ],
  comentario: 'Mergulho profissional: avaliação médica específica, tabelas, controle de tempo e profundidade e registro dos perfis. A osteonecrose disbárica aparece tarde — e sem o registro, não se reconstitui a exposição.',
  pegadinha: 'Não registrar os perfis inviabiliza, anos depois, a análise do agravo que a atividade produz.',
  refs: ['NR-15 — Anexo 6', 'Medicina hiperbárica — literatura de referência'] },

{ id: 'q-2.3-150', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a gases anestésicos residuais em centros cirúrgicos, é CORRETO afirmar:',
  alts: [
    { t: 'Decorre de escape de circuitos e de ventilação inadequada, sendo a exaustão de gases a medida central', ok: true,
      why: 'Correta. Controle é exaustão de gases residuais e manutenção, não proteção individual.' },
    { t: 'Não há exposição ocupacional relevante a gases anestésicos em centros cirúrgicos modernos e ventilados.', ok: false,
      why: 'Errada. Escapes e ventilação inadequada mantêm a exposição relevante.' },
    { t: 'Decorre de escape de circuitos, sendo a proteção respiratória individual a medida adequada de controle.', ok: false,
      why: 'Errada. O controle é por exaustão de gases residuais e manutenção dos circuitos.' },
    { t: 'Decorre de escape de circuitos, sem fundamento a preocupação com efeitos reprodutivos da exposição.', ok: false,
      why: 'Errada. É uma das preocupações históricas associadas a esses agentes.' },
    { t: 'Decorre da técnica de indução, sem que a manutenção dos equipamentos influencie a exposição da equipe.', ok: false,
      why: 'Errada. Vazamentos por manutenção deficiente são fonte principal de exposição.' }
  ],
  comentario: 'Gases anestésicos residuais: escape de circuito e ventilação inadequada expõem toda a equipe. Controle é exaustão de gases residuais e manutenção — proteção respiratória não resolve esse cenário.',
  pegadinha: 'Buscar solução em equipamento individual num ambiente que exige exaustão inverte a hierarquia de controle.',
  refs: ['NR-32', 'ACGIH', 'Diretrizes de segurança em centro cirúrgico'] },

{ id: 'q-2.4-150', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a agentes biológicos em atividades de reforma e demolição, é CORRETO afirmar:',
  alts: [
    { t: 'Edificações abandonadas trazem risco de histoplasmose por excretas e de leptospirose por roedores.', ok: true,
      why: 'Correta. Obra não é lembrada como atividade com risco biológico.' },
    { t: 'Reforma e demolição envolvem riscos físicos e químicos, sem risco biológico relevante para os expostos.', ok: false,
      why: 'Errada. Excretas de aves e morcegos e infestação por roedores são riscos concretos.' },
    { t: 'Edificações abandonadas trazem risco de leptospirose, sem relação da histoplasmose com o trabalho.', ok: false,
      why: 'Errada. Há surtos ocupacionais descritos em limpeza de locais com acúmulo de excretas.' },
    { t: 'Edificações abandonadas trazem riscos, sem que a umidificação prévia influencie a geração de aerossóis.', ok: false,
      why: 'Errada. Reduz a suspensão de partículas contendo o agente.' },
    { t: 'Edificações abandonadas trazem riscos, sendo desnecessária a proteção respiratória sem poeira visível.', ok: false,
      why: 'Errada. As partículas infectantes não são visíveis e exigem proteção adequada.' }
  ],
  comentario: 'Reforma e demolição têm risco biológico esquecido: excretas de aves e morcegos, com histoplasmose, e roedores, com leptospirose. Umidificar antes reduz aerossóis, e a partícula infectante não é visível.',
  pegadinha: 'Classificar obra apenas pelos riscos físicos e químicos deixa o risco biológico fora do inventário.',
  refs: ['NR-18', 'NR-32', 'Ministério da Saúde — histoplasmose e leptospirose'] },

{ id: 'q-2.6-150', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comparação entre limites nacionais e referências técnicas internacionais, é CORRETO afirmar:',
  alts: [
    { t: 'As divergências são frequentes, cabendo ao serviço adotar o critério mais protetor entre os dois', ok: true,
      why: 'Correta. Nada impede adotar o critério mais protetor, e é o que a técnica recomenda.' },
    { t: 'Divergências são frequentes, sendo irregular a adoção de critério mais protetor que o normativo.', ok: false,
      why: 'Errada. É permitida e tecnicamente recomendável.' },
    { t: 'Não há divergência relevante entre os limites nacionais e as referências técnicas internacionais.', ok: false,
      why: 'Errada. Divergências são frequentes, dadas as diferentes datas de revisão.' },
    { t: 'Divergências são frequentes, demonstrando o cumprimento do limite normativo exposição controlada.', ok: false,
      why: 'Errada. O limite pode estar defasado em relação à evidência atual.' },
    { t: 'Divergências são frequentes, não precisando o critério adotado ser justificado no laudo técnico.', ok: false,
      why: 'Errada. O critério adotado deve ser declarado e justificado.' }
  ],
  comentario: 'Limite nacional e referência internacional divergem por data de revisão e critério. Adotar o mais protetor é permitido e recomendável — declarando no laudo qual critério se usou e por quê.',
  pegadinha: 'Cumprir o limite normativo defasado não é o mesmo que ter exposição tecnicamente controlada.',
  refs: ['NR-15', 'ACGIH — TLVs', 'NHO — Fundacentro'] },

{ id: 'q-2.7-130', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a integração entre os resultados de avaliação de higiene ocupacional e o programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'Os resultados devem orientar exames, periodicidades e grupos a monitorar no programa médico da empresa', ok: true,
      why: 'Correta. Sem isso ficam dois programas paralelos: um mede o ambiente, outro examina pessoas.' },
    { t: 'Os dois programas devem operar de forma independente, cada um com sua metodologia e seu cronograma.', ok: false,
      why: 'Errada. O programa médico deve derivar dos riscos avaliados.' },
    { t: 'Os resultados orientam os exames, sem influenciar a periodicidade com que eles são realizados.', ok: false,
      why: 'Errada. Nível de exposição e efeito crítico determinam a periodicidade.' },
    { t: 'Os resultados orientam os exames, independendo os grupos a monitorar dos grupos homogêneos de exposição.', ok: false,
      why: 'Errada. Os grupos de exposição orientam diretamente os grupos de vigilância médica.' },
    { t: 'Os resultados orientam o programa, sendo a comunicação entre as áreas desejável mas sem efeito prático.', ok: false,
      why: 'Errada. É o que torna o programa médico dirigido ao risco real.' }
  ],
  comentario: 'Higiene mede o ambiente e o programa médico examina as pessoas — se não conversam, viram dois programas paralelos. Grupos de exposição definem grupos de vigilância; nível e efeito crítico definem exame e periodicidade.',
  pegadinha: 'A separação entre as áreas produz medição que ninguém usa e exame que não vigia o risco medido.',
  refs: ['NR-7', 'NR-9', 'NHO — Fundacentro'] },

{ id: 'q-4.4-150', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vigilância de dermatoses em grupos de trabalhadores expostos, é CORRETO afirmar:',
  alts: [
    { t: 'O exame de pele dirigido detecta os quadros iniciais antes da cronificação nesses setores expostos', ok: true,
      why: 'Correta. O trabalhador só procura quando a mão já não trabalha.' },
    { t: 'A queixa espontânea do trabalhador é indicador suficiente para orientar a vigilância dermatológica.', ok: false,
      why: 'Errada. A procura espontânea ocorre tardiamente, com lesão já instalada.' },
    { t: 'O exame dirigido detecta quadros iniciais, mas o exame de pele não integra o exame ocupacional.', ok: false,
      why: 'Errada. Em setores com agentes cutâneos, é exame dirigido ao efeito crítico.' },
    { t: 'O exame dirigido detecta quadros iniciais, que não têm repercussão sobre a evolução do caso.', ok: false,
      why: 'Errada. A intervenção precoce evita a cronificação.' },
    { t: 'O exame dirigido detecta quadros iniciais, restringindo-se essa vigilância à indústria química.', ok: false,
      why: 'Errada. Alcança construção, saúde, alimentação, limpeza e cabeleireiros.' }
  ],
  comentario: 'Olhar a pele de quem trabalha com irritantes e sensibilizantes detecta cedo o que a queixa espontânea só traz quando já cronificou. E o alcance vai muito além da indústria química.',
  pegadinha: 'Esperar a queixa transforma um quadro tratável em dermatose crônica que limita a função.',
  refs: ['Salim — Dermatoses Ocupacionais', 'NR-7'] },

{ id: 'q-4.5-140', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação vestibular e o equilíbrio em trabalhadores expostos a agentes ototóxicos, é CORRETO afirmar:',
  alts: [
    { t: 'Alguns agentes afetam o sistema vestibular, com tontura e desequilíbrio de repercussão em segurança.', ok: true,
      why: 'Correta. Desequilíbrio em altura é risco imediato, não sintoma menor.' },
    { t: 'Agentes ototóxicos afetam a função auditiva, comprometendo a cóclea sem repercussão vestibular.', ok: false,
      why: 'Errada. Alguns comprometem também a função vestibular.' },
    { t: 'Alguns agentes afetam o vestíbulo, devendo a tontura ser atribuída a causas inespecíficas comuns.', ok: false,
      why: 'Errada. Exige investigação, dada a repercussão em segurança.' },
    { t: 'Alguns agentes afetam o vestíbulo, sem repercussão relevante do desequilíbrio no trabalho em altura.', ok: false,
      why: 'Errada. É risco direto e imediato nessa atividade.' },
    { t: 'Alguns agentes afetam o vestíbulo, não integrando a avaliação vestibular a vigilância dos expostos.', ok: false,
      why: 'Errada. É indicada quando o agente tem esse potencial.' }
  ],
  comentario: 'Ototóxico pode atingir também o vestíbulo: tontura e desequilíbrio em quem trabalha em altura ou opera máquina é risco imediato. Investigar a queixa, não rotulá-la como inespecífica.',
  pegadinha: 'Tratar tontura como queixa vaga em trabalhador de altura ignora a consequência mais previsível.',
  refs: ['NR-35', 'NR-7 — Anexo I', 'ACGIH — ototoxicantes'] },

{ id: 'q-4.6-140', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação do impacto de reestruturações e demissões coletivas sobre a saúde dos trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'A reestruturação afeta também quem permanece, com aumento de carga e insegurança documentados.', ok: true,
      why: 'Correta. Quem fica acumula o trabalho de quem saiu, sob insegurança.' },
    { t: 'A reestruturação afeta os trabalhadores desligados, que perdem vínculo e renda com o processo.', ok: false,
      why: 'Errada. Quem permanece apresenta aumento de carga e de insegurança documentados.' },
    { t: 'A reestruturação afeta quem permanece, sem configurar o período exposição psicossocial aumentada.', ok: false,
      why: 'Errada. São reconhecidos como período de risco elevado.' },
    { t: 'A reestruturação afeta quem permanece, sem que o aumento de carga sobre eles repercuta em saúde.', ok: false,
      why: 'Errada. Repercute em sobrecarga, adoecimento e acidentes.' },
    { t: 'A reestruturação afeta quem permanece, sem que a comunicação sobre o processo influencie os efeitos.', ok: false,
      why: 'Errada. Transparência e previsibilidade reduzem o efeito da incerteza.' }
  ],
  comentario: 'Reestruturação adoece quem fica: mais carga, menos gente, insegurança sobre a próxima rodada. É período de exposição aumentada — e comunicação clara reduz parte do efeito da incerteza.',
  pegadinha: 'Avaliar o impacto apenas sobre os desligados ignora o grupo que segue trabalhando sob a nova carga.',
  refs: ['OIT — riscos psicossociais', 'NR-1 — fatores psicossociais'] },

{ id: 'q-4.8-140', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de risco a trabalhadores expostos a agentes cancerígenos, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser informados da natureza cancerígena do agente, das medidas e do acompanhamento posterior', ok: true,
      why: 'Correta. Informar mal produz negação ou fatalismo, e ambos afastam da prevenção.' },
    { t: 'Devem ser informados das medidas adotadas, omitida a natureza cancerígena para evitar ansiedade.', ok: false,
      why: 'Errada. A omissão retira do trabalhador a base para se proteger e buscar direitos.' },
    { t: 'Devem ser informados do agente e das medidas, sem precisar explicar o acompanhamento posterior.', ok: false,
      why: 'Errada. É o que sustenta a adesão ao seguimento de longo prazo.' },
    { t: 'Devem ser informados da natureza do agente, sem que a forma da comunicação influencie a adesão.', ok: false,
      why: 'Errada. Comunicação fatalista desestimula a adesão às medidas.' },
    { t: 'Devem ser informados do risco, encerrando essa comunicação a obrigação da empresa quanto ao agente.', ok: false,
      why: 'Errada. Informar não substitui eliminar, substituir ou controlar a exposição.' }
  ],
  comentario: 'Informar que o agente é cancerígeno, o que se faz para controlar e por que o acompanhamento continua depois — em linguagem que não produza fatalismo. E informar nunca substitui controlar.',
  pegadinha: 'Comunicar de forma fatalista produz o mesmo efeito prático de não comunicar: ninguém adere às medidas.',
  refs: ['IARC', 'NR-1', 'Código de Ética Médica'] },

{ id: 'q-4.10-130', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a cobertura vacinal em grupos de trabalhadores e sua avaliação, é CORRETO afirmar:',
  alts: [
    { t: 'A cobertura vacinal deve ser avaliada por grupo de risco, e não apenas em números globais da empresa', ok: true,
      why: 'Correta. A média esconde o setor descoberto, que costuma ser o de maior exposição.' },
    { t: 'A cobertura vacinal global da empresa é indicador suficiente para avaliar o programa implantado.', ok: false,
      why: 'Errada. Esconde diferenças entre grupos de risco.' },
    { t: 'A cobertura deve ser avaliada por grupo, não sendo necessário incluir os trabalhadores terceirizados.', ok: false,
      why: 'Errada. Estão entre os grupos de menor cobertura e maior exposição.' },
    { t: 'A cobertura deve ser avaliada por grupo, apresentando os turnos noturnos cobertura equivalente aos demais.', ok: false,
      why: 'Errada. Costumam ter menor acesso a campanhas em horário comercial.' },
    { t: 'A cobertura deve ser avaliada por grupo, não sendo gerenciável a dificuldade de acesso em certos turnos.', ok: false,
      why: 'Errada. Ampliar horários da campanha é medida direta e eficaz.' }
  ],
  comentario: 'Cobertura global alta convive com bolsões descobertos: terceirizados e turno noturno costumam ficar de fora das campanhas em horário comercial. Avaliar por grupo revela o que a média esconde.',
  pegadinha: 'Reportar cobertura global elevada satisfaz o indicador e deixa descoberto o grupo mais exposto.',
  refs: ['Programa Nacional de Imunizações', 'NR-7', 'NR-32'] },

{ id: 'q-5.4-150', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do perito diante de periciando em situação de vulnerabilidade, é CORRETO afirmar:',
  alts: [
    { t: 'Baixa escolaridade e limitações de comunicação exigem adaptar a entrevista e checar o entendimento.', ok: true,
      why: 'Correta. Quem não consegue descrever pode parecer não ter o que descrever.' },
    { t: 'A entrevista pericial deve ser padronizada e igual para todos, sem adaptação ao periciando avaliado.', ok: false,
      why: 'Errada. A adaptação é o que permite obter informação de qualidade.' },
    { t: 'A entrevista deve ser adaptada, indicando o relato pobre em detalhes ausência de sintomas relevantes.', ok: false,
      why: 'Errada. Pode refletir barreira de comunicação ou escolaridade.' },
    { t: 'A entrevista deve ser adaptada, devendo a presença de acompanhante ser sempre recusada na perícia.', ok: false,
      why: 'Errada. Em situações específicas, o acompanhante viabiliza a comunicação.' },
    { t: 'A entrevista deve ser adaptada, não integrando o ato pericial a verificação do entendimento.', ok: false,
      why: 'Errada. Assegurar que o periciando compreendeu é parte do ato.' }
  ],
  comentario: 'Barreira de comunicação empobrece o relato e pode ser lida como ausência de sintoma. Adaptar a entrevista, verificar o entendimento e, quando necessário, admitir acompanhante é o que produz informação confiável.',
  pegadinha: 'Interpretar relato pobre como quadro leve penaliza quem tem menos recursos para descrever o próprio sofrimento.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-5.5-140', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a reavaliação periódica de restrições funcionais, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser reavaliadas em intervalos definidos, pois as condições evoluem nos dois sentidos possíveis', ok: true,
      why: 'Correta. Restrição desatualizada erra tanto por limitar quanto por deixar de proteger.' },
    { t: 'Devem ser mantidas conforme emitidas até que o próprio trabalhador as questione formalmente.', ok: false,
      why: 'Errada. A reavaliação periódica é responsabilidade do serviço médico.' },
    { t: 'Devem ser reavaliadas, não justificando a recuperação do trabalhador a revisão das já emitidas.', ok: false,
      why: 'Errada. Justifica, e a manutenção indevida limita oportunidades.' },
    { t: 'Devem ser reavaliadas periodicamente, dispensando as restrições definitivas qualquer reavaliação futura.', ok: false,
      why: 'Errada. Mesmo restrições de longo prazo comportam reavaliação diante de mudanças.' },
    { t: 'Devem ser reavaliadas, podendo a revisão ocorrer apenas mediante solicitação formal da empresa.', ok: false,
      why: 'Errada. Decorre da avaliação médica, independentemente de solicitação.' }
  ],
  comentario: 'Restrição não é definitiva por inércia: reavalia-se periodicamente porque a condição muda nos dois sentidos. Mantida sem revisão, ela limita quem já recuperou; não revista após piora, deixa de proteger.',
  pegadinha: 'Restrição esquecida no prontuário segue limitando o trabalhador anos depois de a condição ter se resolvido.',
  refs: ['NR-7', 'CIF — OMS'] },

{ id: 'q-6.2-140', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação com trabalhadores com deficiência auditiva no serviço de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A comunicação acessível é condição do ato médico: sem ela não há anamnese nem consentimento.', ok: true,
      why: 'Correta. Não é aceitável conduzir a consulta por acompanhante improvisado sem concordância.' },
    { t: 'A comunicação acessível é necessária, resolvendo a comunicação escrita adequadamente qualquer situação.', ok: false,
      why: 'Errada. Nem todos têm domínio da língua escrita como segunda língua.' },
    { t: 'A comunicação acessível é necessária, dispensando-a a presença de acompanhante na consulta.', ok: false,
      why: 'Errada. Compromete a privacidade e nem sempre assegura fidelidade da comunicação.' },
    { t: 'A comunicação acessível é boa prática, sem integrar o conceito legal de acessibilidade previsto.', ok: false,
      why: 'Errada. É dimensão expressamente prevista.' },
    { t: 'A comunicação acessível é necessária, justificando sua dificuldade conclusões mais restritivas de aptidão.', ok: false,
      why: 'Errada. A barreira é do serviço, e não pode ser convertida em restrição ao trabalhador.' }
  ],
  comentario: 'Sem comunicação acessível não há anamnese, consentimento nem orientação compreendida. Escrita não resolve para todos, e acompanhante improvisado compromete privacidade — a barreira é do serviço, nunca do trabalhador.',
  pegadinha: 'Converter a dificuldade de comunicação do serviço em restrição de aptidão penaliza o trabalhador por uma falha que não é dele.',
  refs: ['Lei nº 13.146/2015', 'Código de Ética Médica'] },

{ id: 'q-6.3-140', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o rastreamento de doenças cardiovasculares em programas ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'Segue critérios de risco individual e evidência de benefício, distinto da avaliação de aptidão.', ok: true,
      why: 'Correta. Rastrear e avaliar aptidão são perguntas diferentes com métodos diferentes.' },
    { t: 'Segue os mesmos critérios da avaliação de aptidão, por avaliarem ambos o risco cardiovascular.', ok: false,
      why: 'Errada. Têm finalidades e critérios distintos.' },
    { t: 'Segue critérios de risco, sendo recomendada a oferta ampla de exames cardiológicos a todos.', ok: false,
      why: 'Errada. Sem indicação, produz achados incidentais e investigações desnecessárias.' },
    { t: 'Segue a evidência de benefício, não influenciando a avaliação de risco individual a indicação.', ok: false,
      why: 'Errada. É o principal determinante da indicação.' },
    { t: 'Segue critérios de risco, devendo os achados ser comunicados à empresa para orientar a alocação.', ok: false,
      why: 'Errada. À empresa cabe aptidão e restrição; achados clínicos permanecem sob sigilo.' }
  ],
  comentario: 'Rastreamento populacional e avaliação de aptidão respondem perguntas diferentes. Oferecer exame a todos parece cuidado e produz achado incidental — e, em qualquer caso, à empresa vai aptidão, não achado.',
  pegadinha: 'Tratar o exame ocupacional como check-up geral confunde duas finalidades e gera investigação sem benefício.',
  refs: ['NR-7', 'Critérios de rastreamento — medicina preventiva'] },

{ id: 'q-7.2-140', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o requerimento administrativo e o acesso do trabalhador aos benefícios, é CORRETO afirmar:',
  alts: [
    { t: 'Orientar sobre a existência do direito, os documentos e os prazos integra o cuidado ao trabalhador', ok: true,
      why: 'Correta. Desconhecimento é barreira real, e orientar não é interferência indevida.' },
    { t: 'A orientação sobre direitos previdenciários está fora do escopo do cuidado médico prestado.', ok: false,
      why: 'Errada. Integra o cuidado, sobretudo em agravos relacionados ao trabalho.' },
    { t: 'Orientar integra o cuidado, embora o desconhecimento não seja barreira relevante de acesso.', ok: false,
      why: 'Errada. É uma das principais barreiras identificadas.' },
    { t: 'Orientar o trabalhador sobre prazos configura interferência indevida na esfera previdenciária.', ok: false,
      why: 'Errada. Informar sobre a existência do direito não interfere na decisão administrativa.' },
    { t: 'Orientar integra o cuidado, sem que a qualidade dos documentos médicos influencie o acesso.', ok: false,
      why: 'Errada. Documentação bem elaborada é determinante na instrução do requerimento.' }
  ],
  comentario: 'Informar que o direito existe, quais documentos reunir e quais prazos observar é parte do cuidado — não interferência. E a qualidade do relatório médico é o que instrui bem o requerimento.',
  pegadinha: 'Considerar a orientação sobre direitos como assunto alheio à medicina deixa o trabalhador sem a informação que decide o acesso.',
  refs: ['Lei nº 8.213/1991', 'Código de Ética Médica', 'PNSTT'] },

{ id: 'q-7.3-140', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação da vigilância sanitária com o ministério público em situações de risco à saúde de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Comunicar risco não corrigido a órgãos com poder de atuação amplia as possibilidades de solução.', ok: true,
      why: 'Correta. O termo de ajustamento de conduta costuma destravar situações persistentes.' },
    { t: 'A vigilância deve resolver internamente, sem comunicar situações de risco a outros órgãos.', ok: false,
      why: 'Errada. A articulação amplia a capacidade de solução.' },
    { t: 'Comunicar amplia as possibilidades, embora o ministério público não disponha de instrumentos extrajudiciais.', ok: false,
      why: 'Errada. O termo de ajustamento de conduta é instrumento extrajudicial usual.' },
    { t: 'Comunicar amplia as possibilidades, reduzindo a atuação conjunta a autonomia técnica da vigilância.', ok: false,
      why: 'Errada. Cada órgão preserva sua competência e sua autonomia técnica.' },
    { t: 'Comunicar é possível, não comportando outras medidas as situações de risco persistente após autuação.', ok: false,
      why: 'Errada. É justamente quando a articulação com outros órgãos se torna necessária.' }
  ],
  comentario: 'Risco que persiste depois da autuação pede articulação: comunicar a quem tem instrumento judicial e extrajudicial. O termo de ajustamento de conduta é o caminho mais usado, com prazos pactuados.',
  pegadinha: 'Encerrar a atuação na autuação deixa sem resposta exatamente os casos que não se resolvem com ela.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Lei da Ação Civil Pública'] },

{ id: 'q-7.4-140', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o transporte, a movimentação e o manuseio de materiais, é CORRETO afirmar:',
  alts: [
    { t: 'A prioridade é mecanizar, seguida da adequação de peso, distância, frequência e altura de pega.', ok: true,
      why: 'Correta. Treinar postura sem mudar carga e frequência não muda o desfecho.' },
    { t: 'A prioridade é o treinamento em técnica de levantamento, medida de maior eficácia nesses casos.', ok: false,
      why: 'Errada. Sua eficácia isolada é limitada; o que importa é mudar as condições da tarefa.' },
    { t: 'A prioridade é adequar a carga, sendo o peso o único parâmetro relevante nessa avaliação.', ok: false,
      why: 'Errada. Distância, frequência, altura de pega e torção também determinam a carga.' },
    { t: 'A prioridade é adequar peso e frequência, não sendo a mecanização considerada medida prioritária.', ok: false,
      why: 'Errada. Eliminar o transporte manual é a medida de maior hierarquia.' },
    { t: 'A prioridade é mecanizar e adequar o peso, sem que a altura de pega influencie o esforço exigido.', ok: false,
      why: 'Errada. Pegar do chão ou acima dos ombros aumenta muito a exigência.' }
  ],
  comentario: 'Movimentação de cargas: mecanizar primeiro, depois ajustar peso, distância, frequência e altura de pega. Treinar técnica sem mudar a tarefa é a intervenção mais oferecida e a de menor efeito.',
  pegadinha: 'A palestra sobre postura para levantar peso é popular justamente porque não muda nada na organização da tarefa.',
  refs: ['NR-17', 'NR-11', 'Equação de levantamento — NIOSH'] },

{ id: 'q-7.5-110', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o acesso do trabalhador às informações a seu respeito transmitidas pelo eSocial, é CORRETO afirmar:',
  alts: [
    { t: 'Ele pode consultar o que lhe diz respeito e identificar divergências com sua realidade de trabalho.', ok: true,
      why: 'Correta. Conferir enquanto o vínculo existe é muito mais fácil que corrigir depois.' },
    { t: 'Ele não tem acesso às informações transmitidas a seu respeito, prestadas pela empresa ao sistema.', ok: false,
      why: 'Errada. Há vias de consulta às informações que lhe dizem respeito.' },
    { t: 'Ele pode consultar as informações, não podendo as divergências identificadas ser corrigidas depois.', ok: false,
      why: 'Errada. Há procedimento de retificação previsto.' },
    { t: 'Ele pode consultar as informações, sendo a conferência responsabilidade exclusiva da empresa.', ok: false,
      why: 'Errada. O interessado direto na correção é o próprio trabalhador.' },
    { t: 'Ele pode consultar, sendo os erros identificados tardiamente corrigidos com a mesma facilidade.', ok: false,
      why: 'Errada. A correção tardia enfrenta dificuldade de comprovação e de reconstituição.' }
  ],
  comentario: 'O trabalhador pode e deve conferir o que foi transmitido sobre ele — e corrigir enquanto o vínculo existe e há como comprovar. Descobrir o erro na hora da aposentadoria é descobrir tarde demais.',
  pegadinha: 'Deixar a conferência inteiramente com a empresa entrega a quem tem menos interesse na correção.',
  refs: ['eSocial', 'LGPD — direitos do titular', 'Lei nº 8.213/1991'] },

{ id: 'q-1.3-140', tema: '1.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de indicadores epidemiológicos na comparação entre setores econômicos, é CORRETO afirmar:',
  alts: [
    { t: 'Exige atenção às diferenças de composição, formalização e capacidade de notificação dos setores.', ok: true,
      why: 'Correta. Setor que não registra aparece como setor seguro.' },
    { t: 'Os setores com menores taxas registradas apresentam melhores condições de trabalho e de gestão.', ok: false,
      why: 'Errada. Podem apenas registrar menos.' },
    { t: 'Exige atenção à composição da força de trabalho, sem que a formalização influencie os indicadores.', ok: false,
      why: 'Errada. Determina diretamente a capacidade de registro e notificação.' },
    { t: 'Exige atenção à formalização, não interferindo a composição etária e o tempo de casa na comparação.', ok: false,
      why: 'Errada. São fatores que exigem padronização.' },
    { t: 'Exige atenção à formalização, não sendo os indicadores afetados por incentivos à subnotificação.', ok: false,
      why: 'Errada. São diretamente afetados por eles.' }
  ],
  comentario: 'Comparar setores exige olhar formalização, composição da força de trabalho e capacidade de notificação. Setor informal registra pouco e aparece seguro — que é o oposto do que costuma ser.',
  pegadinha: 'Ler taxa baixa como condição melhor premia justamente o setor que menos registra.',
  refs: ['Rothman — Epidemiologia Moderna', 'SINAN', 'PNSTT'] },

{ id: 'q-1.4-120', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a apresentação de resultados do programa de saúde ocupacional à alta direção, é CORRETO afirmar:',
  alts: [
    { t: 'Deve relacionar achados de saúde a condições de trabalho, com dados agregados e sem identificação.', ok: true,
      why: 'Correta. O que a direção decide é sobre condições, não sobre número de exames.' },
    { t: 'Deve incluir casos individuais representativos, para dar concretude aos achados apresentados à direção.', ok: false,
      why: 'Errada. Casos identificáveis violam o sigilo; a apresentação é agregada.' },
    { t: 'Deve trazer o volume de exames realizados no período, suficiente para orientar as decisões da direção.', ok: false,
      why: 'Errada. Não relaciona saúde a condições nem indica o que decidir.' },
    { t: 'Deve trazer dados agregados, sem que a relação entre saúde e condições de trabalho interesse à direção.', ok: false,
      why: 'Errada. É exatamente o que fundamenta as decisões de investimento e organização.' },
    { t: 'Deve trazer dados agregados, podendo apresentar sem restrição os de setores muito pequenos.', ok: false,
      why: 'Errada. Em grupos pequenos, o agregado reidentifica e exige agregação superior.' }
  ],
  comentario: 'Relatório à direção conecta achados de saúde a condições e às decisões que só ela pode tomar — sempre agregado, com cuidado extra em setores pequenos, onde o agregado reidentifica.',
  pegadinha: 'Apresentar volume de exames entrega atividade e não entrega informação para decisão.',
  refs: ['NR-7', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-1.6-120', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a participação de trabalhadores e suas entidades na formulação de políticas de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'É princípio estruturante do campo e traz o conhecimento sobre o trabalho real à formulação técnica', ok: true,
      why: 'Correta. É o traço histórico que distingue a saúde do trabalhador da medicina do trabalho.' },
    { t: 'É etapa consultiva prevista nos processos, sem efeito sobre a formulação técnica das políticas.', ok: false,
      why: 'Errada. É princípio estruturante do campo.' },
    { t: 'É princípio do campo, sem que o conhecimento dos trabalhadores acrescente à formulação técnica.', ok: false,
      why: 'Errada. É informação que nenhuma outra fonte fornece.' },
    { t: 'É princípio do campo, sem relação da origem histórica dele com a participação dos trabalhadores.', ok: false,
      why: 'Errada. O movimento operário pela saúde é uma de suas raízes constitutivas.' },
    { t: 'É princípio previsto, comprometendo a participação sindical a objetividade técnica das políticas.', ok: false,
      why: 'Errada. Acrescenta informação sobre a realidade do trabalho, sem substituir a análise.' }
  ],
  comentario: 'A participação não é consulta protocolar: é princípio estruturante, com raiz no movimento operário pela saúde, e traz o conhecimento sobre o trabalho real que nenhum documento técnico contém.',
  pegadinha: 'Tratar participação como etapa consultiva descarta a informação que justifica sua existência.',
  refs: ['PNSTT', 'Lei nº 8.080/1990', 'Modelo operário italiano'] },

{ id: 'q-1.7-120', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a assistência ao trabalhador acidentado na rede pública, é CORRETO afirmar:',
  alts: [
    { t: 'Independe de comprovação de vínculo, e o registro da relação com o trabalho preserva o caso.', ok: true,
      why: 'Correta. Atende-se primeiro; o registro é o que preserva a informação para depois.' },
    { t: 'Depende da apresentação prévia da comunicação de acidente emitida pela empresa empregadora.', ok: false,
      why: 'Errada. O atendimento é universal e independe de qualquer documento.' },
    { t: 'Independe de comprovação de vínculo, sendo irrelevante o registro da relação com o trabalho.', ok: false,
      why: 'Errada. É o que sustenta o reconhecimento posterior do caso.' },
    { t: 'Independe de vínculo formal, devendo os trabalhadores informais ser encaminhados a serviços privados.', ok: false,
      why: 'Errada. O atendimento no sistema público é universal.' },
    { t: 'Independe de vínculo, não podendo a comunicação de acidente partir do serviço público que atendeu.', ok: false,
      why: 'Errada. O médico assistente é legitimado a emiti-la.' }
  ],
  comentario: 'Atende-se sem exigir documento nenhum — e registra-se a relação com o trabalho no prontuário e na notificação. O serviço público que atendeu também pode emitir a comunicação de acidente.',
  pegadinha: 'Condicionar o atendimento a documento de vínculo contraria a universalidade e atrasa o socorro.',
  refs: ['Lei nº 8.080/1990', 'Lei nº 8.213/1991 — art. 22', 'PNSTT'] },

{ id: 'q-1.8-120', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a proteção de trabalhadores que colaboram com ações de vigilância, é CORRETO afirmar:',
  alts: [
    { t: 'A identidade de quem informa deve ser preservada, pois o receio de represália é a maior barreira.', ok: true,
      why: 'Correta. Sem garantia de anonimato, ninguém fala sobre o trabalho real.' },
    { t: 'A identificação dos informantes é necessária para conferir validade ao relatório da inspeção realizada.', ok: false,
      why: 'Errada. O relatório se sustenta na verificação técnica, não em quem informou.' },
    { t: 'A identidade deve ser preservada, embora o receio de represália não seja barreira relevante.', ok: false,
      why: 'Errada. É a principal barreira identificada à colaboração.' },
    { t: 'A identidade deve ser preservada, devendo as entrevistas ocorrer na presença da chefia do setor.', ok: false,
      why: 'Errada. A presença da chefia inibe o relato e compromete a informação obtida.' },
    { t: 'A identidade deve ser preservada, não devendo as informações obtidas orientar a inspeção técnica.', ok: false,
      why: 'Errada. Orientam onde olhar e o que verificar tecnicamente.' }
  ],
  comentario: 'Preservar a identidade de quem informa é condição de obter informação. Entrevista na presença da chefia não produz relato — produz confirmação do que a chefia já disse.',
  pegadinha: 'Entrevistar o trabalhador com o supervisor ao lado é o procedimento que garante não descobrir nada.',
  refs: ['PNSTT', 'Legislação sanitária', 'Lei nº 8.080/1990'] },

{ id: 'q-1.9-120', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso das bases de notificação para estimar a magnitude dos agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Fornecem estimativas mínimas, devendo os números ser lidos como piso, e não como total.', ok: true,
      why: 'Correta. A subnotificação é reconhecida e substancial.' },
    { t: 'Fornecem estimativa completa da magnitude dos agravos ocupacionais ocorridos no período analisado.', ok: false,
      why: 'Errada. A subnotificação é reconhecida e substancial.' },
    { t: 'Fornecem estimativas mínimas, afetando a subnotificação igualmente todos os agravos notificáveis.', ok: false,
      why: 'Errada. Agravos crônicos e de nexo menos evidente são muito mais subnotificados.' },
    { t: 'Fornecem estimativas mínimas, sem que mudanças na capacidade de notificação afetem a comparação.', ok: false,
      why: 'Errada. Aumento de notificações pode refletir melhora do registro, não piora.' },
    { t: 'Fornecem estimativas mínimas, sem que estudos de base populacional acrescentem a elas.', ok: false,
      why: 'Errada. São justamente o que permite estimar a magnitude da subnotificação.' }
  ],
  comentario: 'Base de notificação dá piso, não total — e a subnotificação é maior nos agravos crônicos. Aumento de notificações pode ser melhora do registro; comparar períodos exige considerar isso.',
  pegadinha: 'Ler aumento de notificações como piora das condições confunde melhora da vigilância com agravamento do problema.',
  refs: ['SINAN', 'Estudos de base populacional em saúde do trabalhador'] },

{ id: 'q-1.10-120', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre promoção da saúde e prevenção de riscos ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'São complementares e não substitutivas: a promoção não pode ocupar o espaço da prevenção de riscos', ok: true,
      why: 'Correta. Promoção não compensa exposição não controlada.' },
    { t: 'São abordagens equivalentes, podendo os programas de promoção substituir o controle de exposições.', ok: false,
      why: 'Errada. São complementares, com objetos distintos.' },
    { t: 'São complementares, não tendo a promoção lugar em ambientes com riscos ocupacionais relevantes.', ok: false,
      why: 'Errada. Tem lugar, desde que não substitua o controle dos riscos.' },
    { t: 'São complementares, sendo a prevenção de riscos ocupacionais responsabilidade do próprio trabalhador.', ok: false,
      why: 'Errada. É obrigação do empregador.' },
    { t: 'São abordagens distintas, gerando sua coexistência conflito técnico insuperável no programa.', ok: false,
      why: 'Errada. São complementares e se reforçam quando bem articuladas.' }
  ],
  comentario: 'Promoção e prevenção se complementam — e a distorção aparece quando a empresa investe em ginástica e alimentação enquanto mantém a exposição sem controle. Uma não paga a conta da outra.',
  pegadinha: 'Programa de promoção robusto convivendo com exposição descontrolada é deslocamento de foco, não cuidado.',
  refs: ['OMS — ambientes de trabalho saudáveis', 'NR-1', 'PNSTT'] }

);
