/* Lote AQ — 4.4, 4.5, 4.6, 4.8, 4.9, 4.10, 4.7, 5.2, 5.3, 5.4, 5.5, 5.6. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-4.4-130', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre as dermatoses ocupacionais por agentes físicos, é CORRETO afirmar:',
  alts: [
    { t: 'Calor, frio, umidade, radiação e microtraumatismos produzem quadros próprios, atribuídos a causas pessoais.', ok: true,
      why: 'Correta. Sem um produto químico para apontar, a origem ocupacional deixa de ser considerada.' },
    { t: 'Dermatoses ocupacionais decorrem de agentes químicos, únicos capazes de produzir lesão cutânea no trabalho.', ok: false,
      why: 'Errada. Agentes físicos e biológicos também as produzem.' },
    { t: 'Calor, frio e umidade produzem quadros próprios, não gerando os microtraumatismos repetidos alterações relevantes.', ok: false,
      why: 'Errada. Produzem calosidades, fissuras e lesões características de certas ocupações.' },
    { t: 'Calor, frio e radiação produzem quadros próprios, não sendo a umidade constante fator de dermatose ocupacional.', ok: false,
      why: 'Errada. O trabalho úmido é um dos principais fatores da dermatite irritativa.' },
    { t: 'Calor e umidade produzem quadros próprios, sem relevância ocupacional as lesões por frio em ambientes refrigerados.', ok: false,
      why: 'Errada. Perniose e lesões por frio ocorrem em câmaras frias e frigoríficos.' }
  ],
  comentario: 'Nem toda dermatose ocupacional tem produto químico: calor, frio, umidade, radiação e microtrauma dão quadros próprios. Justamente por não haver um agente para apontar, costumam ser lidos como problema pessoal.',
  pegadinha: 'Procurar sempre um produto químico faz passar despercebida a dermatose por agente físico.',
  refs: ['Salim — Dermatoses Ocupacionais'] },

{ id: 'q-4.5-120', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de comunicação e a percepção de sinais sonoros em ambientes ruidosos, é CORRETO afirmar:',
  alts: [
    { t: 'Perda auditiva e superproteção comprometem a percepção de alarmes, exigindo sinalização visual como complemento', ok: true,
      why: 'Correta. Superproteção transforma proteção auditiva em risco de acidente.' },
    { t: 'A percepção de alarmes melhora com a atenuação, sendo o protetor de maior atenuação preferível em qualquer situação.', ok: false,
      why: 'Errada. Atenuação excessiva prejudica comunicação e percepção de alertas.' },
    { t: 'Perda auditiva e superproteção comprometem a percepção, sem papel para a sinalização visual em ruído elevado.', ok: false,
      why: 'Errada. É complemento necessário quando a percepção sonora está comprometida.' },
    { t: 'A superproteção compromete a percepção de alarmes, sem que a perda auditiva interfira na segurança do trabalhador.', ok: false,
      why: 'Errada. Compromete a percepção de alertas e a localização de fontes sonoras.' },
    { t: 'Perda e superproteção comprometem a percepção, não existindo protetores com atenuação uniforme por frequência.', ok: false,
      why: 'Errada. Há modelos com atenuação mais plana, que preservam a inteligibilidade da fala.' }
  ],
  comentario: 'Proteger demais também é problema: alarme não ouvido e empilhadeira não percebida. Seleciona-se atenuação adequada, considera-se protetor de resposta mais plana e complementa-se com sinalização visual.',
  pegadinha: 'Escolher sempre o protetor de maior atenuação parece conservador e cria um risco novo.',
  refs: ['NR-6', 'NHO 01 — Fundacentro', 'NIOSH'] },

{ id: 'q-4.6-120', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a organização do trabalho por metas e sua relação com a saúde mental, é CORRETO afirmar:',
  alts: [
    { t: 'Metas em escalada, ranking individual exposto e remuneração vinculada compõem padrão de sofrimento psíquico.', ok: true,
      why: 'Correta. Ranking exposto é humilhação institucionalizada, com efeito documentado.' },
    { t: 'A existência de metas de desempenho é, por si só, fator de adoecimento dos trabalhadores submetidos a elas.', ok: false,
      why: 'Errada. O problema está no padrão de escalada, exposição e vinculação, não na meta em si.' },
    { t: 'Metas em escalada compõem padrão de sofrimento, sem repercussão em saúde a divulgação comparativa individual.', ok: false,
      why: 'Errada. É elemento agravante reconhecido.' },
    { t: 'Metas em escalada e ranking exposto adoecem, não interferindo a remuneração variável na organização do trabalho.', ok: false,
      why: 'Errada. Molda ritmo, pausas e disposição a assumir riscos.' },
    { t: 'Metas em escalada compõem esse padrão, produzindo as metas inatingíveis apenas frustração, sem quadro clínico.', ok: false,
      why: 'Errada. Associam-se a quadros ansiosos e depressivos documentados.' }
  ],
  comentario: 'Meta não adoece; o padrão adoece: escalada contínua, ranking exposto e salário atrelado ao resultado. E a remuneração variável muda ritmo e disposição a correr risco — o que aparece nos acidentes.',
  pegadinha: 'Defender que "meta faz parte de qualquer trabalho" desvia da discussão sobre escalada e exposição pública.',
  refs: ['NR-1 — fatores psicossociais', 'Siegrist', 'OIT'] },

{ id: 'q-4.8-120', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o reconhecimento previdenciário de neoplasia relacionada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A dificuldade decorre da latência, da perda de registros e da multicausalidade, não da falta de previsão.', ok: true,
      why: 'Correta. O obstáculo é probatório, não normativo: diversas associações constam da lista.' },
    { t: 'A dificuldade decorre de as neoplasias não constarem da lista de doenças relacionadas ao trabalho vigente.', ok: false,
      why: 'Errada. Diversas associações entre agentes e neoplasias constam expressamente.' },
    { t: 'A dificuldade decorre da latência longa, que impede juridicamente o reconhecimento desses agravos.', ok: false,
      why: 'Errada. Dificulta a prova, mas não impede o reconhecimento.' },
    { t: 'A dificuldade decorre da multicausalidade das neoplasias, que afasta o nexo com qualquer exposição isolada.', ok: false,
      why: 'Errada. Contribuição relevante basta, como em qualquer doença multicausal.' },
    { t: 'A dificuldade decorre da perda de registros, cuja ausência inviabiliza por completo o reconhecimento.', ok: false,
      why: 'Errada. A história ocupacional e outros elementos podem sustentar a análise.' }
  ],
  comentario: 'Câncer ocupacional tem previsão normativa; o que falta é prova — registros perdidos, décadas decorridas, várias causas em jogo. Nada disso impede o reconhecimento, mas tudo isso o dificulta.',
  pegadinha: 'Concluir pela ausência de previsão normativa quando o obstáculo real é probatório encerra a discussão no lugar errado.',
  refs: ['Decreto nº 3.048/1999 — Anexo II', 'IARC', 'INCA'] },

{ id: 'q-4.9-110', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre doenças infecciosas em trabalhadores que viajam a serviço, é CORRETO afirmar:',
  alts: [
    { t: 'A orientação pré-viagem integra o cuidado ocupacional, e a doença adquirida a serviço pode ter nexo com ele', ok: true,
      why: 'Correta. Deslocamento a serviço é exposição decorrente do trabalho.' },
    { t: 'A orientação pré-viagem integra o cuidado, mas doenças adquiridas em viagem não guardam relação com o trabalho.', ok: false,
      why: 'Errada. A exposição decorre do deslocamento determinado pelo trabalho.' },
    { t: 'A doença adquirida a serviço pode ter nexo, sendo a orientação pré-viagem responsabilidade exclusiva do trabalhador.', ok: false,
      why: 'Errada. Integra o cuidado ocupacional quando o deslocamento é a serviço.' },
    { t: 'A orientação pré-viagem integra o cuidado, não sendo custeadas pelo empregador as vacinas do destino.', ok: false,
      why: 'Errada. Sendo medida de proteção decorrente do trabalho, são custeadas por ele.' },
    { t: 'A orientação pré-viagem integra o cuidado ocupacional, sendo desnecessária a avaliação no retorno da viagem.', ok: false,
      why: 'Errada. É oportunidade de identificar quadros de incubação prolongada.' }
  ],
  comentario: 'Viagem a serviço é exposição ocupacional: orientação e vacinas antes, custeadas pelo empregador, e avaliação no retorno para os quadros de incubação longa. Doença adquirida ali pode ter nexo.',
  pegadinha: 'Tratar a orientação pré-viagem como assunto pessoal deixa sem cobertura uma exposição criada pelo trabalho.',
  refs: ['Ministério da Saúde — saúde do viajante', 'NR-7'] },

{ id: 'q-4.10-110', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre campanhas de vacinação conduzidas no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Observam as exigências de qualquer ato vacinal: contraindicações, conservação, registro e eventos adversos.', ok: true,
      why: 'Correta. Vacinar no refeitório não reduz nenhuma exigência técnica.' },
    { t: 'Observam exigências simplificadas, dispensando a avaliação individual de contraindicações pelo caráter coletivo.', ok: false,
      why: 'Errada. A avaliação é exigência de qualquer ato vacinal.' },
    { t: 'Observam as exigências de qualquer ato vacinal, sendo a conservação preocupação apenas do fornecedor.', ok: false,
      why: 'Errada. A cadeia de frio deve ser assegurada até o momento da aplicação.' },
    { t: 'Observam as exigências técnicas usuais, sem necessidade de prever atendimento a eventos adversos imediatos.', ok: false,
      why: 'Errada. A capacidade de atender reação imediata é requisito.' },
    { t: 'Observam as exigências de qualquer ato vacinal, sendo dispensável o registro individual das doses aplicadas.', ok: false,
      why: 'Errada. O registro é o que permite continuidade e conduta futura.' }
  ],
  comentario: 'Campanha no trabalho é ato vacinal completo: contraindicações avaliadas, cadeia de frio mantida, registro individual e estrutura para reação imediata. Conveniência de local não altera requisito técnico.',
  pegadinha: 'Organizar a campanha como logística e não como ato de saúde é o que produz falha de conservação e registro.',
  refs: ['Programa Nacional de Imunizações', 'NR-7', 'Resoluções sanitárias sobre vacinação'] },

{ id: 'q-4.7-120', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do serviço de saúde ocupacional após evento crítico que afeta uma equipe, é CORRETO afirmar:',
  alts: [
    { t: 'Envolve acolhimento, identificação de quem tem maior risco, encaminhamento e seguimento por semanas', ok: true,
      why: 'Correta. Sessão única obrigatória logo após o evento não é a intervenção recomendada.' },
    { t: 'Envolve sessão única obrigatória de relato detalhado do ocorrido, logo após o evento, com toda a equipe.', ok: false,
      why: 'Errada. Intervenção única e obrigatória com reexposição detalhada não é recomendada.' },
    { t: 'Envolve acolhimento e encaminhamento, dispensando a ausência de reação imediata o acompanhamento posterior.', ok: false,
      why: 'Errada. Manifestações tardias são frequentes.' },
    { t: 'Envolve acolhimento e seguimento, restrito a quem presenciou diretamente o evento crítico ocorrido.', ok: false,
      why: 'Errada. Colegas próximos e quem prestou socorro também são afetados.' },
    { t: 'Envolve acolhimento e encaminhamento individual, sem que a resposta organizacional influencie o desfecho.', ok: false,
      why: 'Errada. É um dos principais determinantes da evolução do grupo.' }
  ],
  comentario: 'Após evento crítico: acolher, identificar quem está em maior risco, encaminhar com continuidade e acompanhar por semanas. Sessão obrigatória única com relato detalhado não é o que a evidência recomenda.',
  pegadinha: 'A intervenção de sessão única com reexposição detalhada parece cuidado imediato e não é a conduta indicada.',
  refs: ['OMS — primeiros cuidados psicológicos', 'Ministério da Saúde'] },

{ id: 'q-5.2-100', tema: '5.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do médico assistente na caracterização de doença relacionada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Pode registrar a suspeita no prontuário, emitir a comunicação de acidente quando cabível e notificar o agravo', ok: true,
      why: 'Correta. O assistente é legitimado para a comunicação e obrigado à notificação.' },
    { t: 'Pode registrar a suspeita no prontuário, sendo a caracterização da relação com o trabalho do médico do trabalho.', ok: false,
      why: 'Errada. Qualquer médico pode e deve registrar a suspeita e notificar.' },
    { t: 'Pode registrar a suspeita e notificar o agravo, não sendo legitimado a emitir a comunicação de acidente.', ok: false,
      why: 'Errada. Consta expressamente entre os legitimados a emiti-la.' },
    { t: 'Pode registrar a suspeita, dependendo a notificação do reconhecimento prévio do nexo pela previdência.', ok: false,
      why: 'Errada. É ato de vigilância baseado em suspeita.' },
    { t: 'Pode registrar a suspeita e notificar, sendo o registro da ocupação no prontuário sem utilidade prática.', ok: false,
      why: 'Errada. É o que permite suspeitar e o que sustenta a investigação posterior.' }
  ],
  comentario: 'O assistente é peça central: registra a ocupação, levanta a suspeita, emite a comunicação de acidente e notifica. Nada disso exige ser médico do trabalho nem esperar decisão previdenciária.',
  pegadinha: 'Delegar tudo ao médico do trabalho faz o caso passar pela consulta sem qualquer registro de relação com o trabalho.',
  refs: ['Lei nº 8.213/1991 — art. 22', 'Portaria de notificação compulsória', 'Código de Ética Médica'] },

{ id: 'q-5.3-110', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausa e o agravamento de condição preexistente por acidente do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O acidente que agrava condição prévia configura relação com o trabalho quanto a esse agravamento sofrido', ok: true,
      why: 'Correta. Reconhecido o agravamento, os efeitos são integrais, sem fracionamento.' },
    { t: 'O acidente pode agravar condição prévia, afastando a preexistência a relação com o evento ocorrido.', ok: false,
      why: 'Errada. O agravamento é hipótese expressa de concausa.' },
    { t: 'O agravamento configura relação com o trabalho, reduzidos os efeitos proporcionalmente à condição prévia.', ok: false,
      why: 'Errada. Não há previsão de fracionamento dos efeitos.' },
    { t: 'O agravamento configura relação, impedindo o reconhecimento a omissão da condição prévia na admissão.', ok: false,
      why: 'Errada. O reconhecimento depende do agravamento demonstrado, não do histórico de declaração.' },
    { t: 'O agravamento configura relação com o trabalho apenas quando a condição prévia era assintomática.', ok: false,
      why: 'Errada. Condição prévia sintomática também pode ser agravada pelo evento.' }
  ],
  comentario: 'Acidente que piora condição prévia gera nexo quanto ao agravamento, com efeitos integrais e sem fracionamento. Nem a preexistência sintomática nem a ausência de declaração na admissão afastam isso.',
  pegadinha: 'A omissão no exame admissional é frequentemente invocada e não é o critério que decide o agravamento.',
  refs: ['Lei nº 8.213/1991 — art. 21, I', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.4-130', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a conduta do perito diante de periciando que apresenta agravamento voluntário ou simulação de sintomas, é CORRETO afirmar:',
  alts: [
    { t: 'Exige fundamentação em inconsistências objetivas entre relato, exame, história e funcionalidade observada.', ok: true,
      why: 'Correta. É a conclusão de maior carga acusatória e a que mais exige demonstração.' },
    { t: 'Exige fundamentação, sendo a impressão clínica formada pelo perito suficiente para sustentar essa conclusão.', ok: false,
      why: 'Errada. Exige-se demonstração de inconsistências objetivas e documentadas.' },
    { t: 'Exige fundamentação objetiva, comprovando a simulação os sintomas desproporcionais aos achados de exame.', ok: false,
      why: 'Errada. Ocorrem em quadros legítimos, especialmente de dor crônica.' },
    { t: 'Exige fundamentação em inconsistências, embora a conclusão não traga repercussões relevantes ao periciando.', ok: false,
      why: 'Errada. Tem repercussões graves, inclusive em outras esferas.' },
    { t: 'Exige fundamentação, demonstrando a ausência de achado em exame complementar a inexistência do quadro.', ok: false,
      why: 'Errada. Muitos quadros legítimos não têm tradução em exames complementares.' }
  ],
  comentario: 'Concluir por simulação é acusar, e por isso exige inconsistências objetivas e documentadas — não impressão. Desproporção entre queixa e achado ocorre em quadros legítimos, sobretudo de dor crônica.',
  pegadinha: 'Transformar desproporção entre sintoma e exame em conclusão de simulação penaliza quadros reais e frequentes.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Código de Ética Médica'] },

{ id: 'q-5.5-120', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a documentação da avaliação funcional em prontuário e relatórios, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser específicas e verificáveis: o que a pessoa executa, por quanto tempo e com que limitação', ok: true,
      why: 'Correta. Descrição genérica não orienta alocação, não sustenta perícia e não mostra evolução.' },
    { t: 'Devem indicar a limitação em termos gerais, formulação suficiente para orientar a alocação do trabalhador.', ok: false,
      why: 'Errada. Não indica o que pode ou não ser feito na prática.' },
    { t: 'Devem ser específicas, sendo a descrição funcional dispensável quando o diagnóstico já está esclarecido.', ok: false,
      why: 'Errada. O diagnóstico não descreve a funcionalidade.' },
    { t: 'Devem ser específicas e verificáveis, sem necessidade de registrar a evolução em atendimentos sucessivos.', ok: false,
      why: 'Errada. É o registro seriado que demonstra melhora, estabilização ou piora.' },
    { t: 'Devem ser específicas e incluir o diagnóstico nos relatórios, para que sejam aceitos pela empresa.', ok: false,
      why: 'Errada. À empresa cabe a limitação funcional; o diagnóstico permanece sob sigilo.' }
  ],
  comentario: 'Descrição funcional útil é específica: o que faz, por quanto tempo, com que limite — registrada de forma seriada. "Evitar esforços" não aloca ninguém, não sustenta perícia e não mostra evolução.',
  pegadinha: 'A expressão genérica parece proteger e na prática impede alocação, conclusão e acompanhamento.',
  refs: ['CIF — OMS', 'Resoluções do CFM sobre prontuário'] },

{ id: 'q-5.6-110', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as barreiras à reabilitação profissional bem-sucedida, é CORRETO afirmar:',
  alts: [
    { t: 'Escolaridade, ausência de vagas na região, resistência da empresa e afastamento longo são as principais.', ok: true,
      why: 'Correta. A maior parte das barreiras é social e organizacional, não clínica.' },
    { t: 'As barreiras são predominantemente clínicas, decorrendo das limitações residuais de cada trabalhador reabilitado.', ok: false,
      why: 'Errada. Escolaridade, mercado local e resistência da empresa pesam mais.' },
    { t: 'Vagas e resistência da empresa são barreiras, não influenciando a escolaridade as possibilidades de requalificação.', ok: false,
      why: 'Errada. Limita diretamente as alternativas de requalificação viáveis.' },
    { t: 'Escolaridade e resistência da empresa são barreiras, não sendo relevante a disponibilidade de vagas na região.', ok: false,
      why: 'Errada. Requalificar para função inexistente na região não recoloca ninguém.' },
    { t: 'Escolaridade e vagas são barreiras, sem que o tempo de afastamento influencie o sucesso da reabilitação.', ok: false,
      why: 'Errada. Afastamento prolongado reduz a probabilidade de retorno.' }
  ],
  comentario: 'O que trava a reabilitação raramente é clínico: escolaridade, mercado local, resistência da empresa e tempo de afastamento. Por isso a articulação precisa ir além do consultório.',
  pegadinha: 'Tratar o insucesso da reabilitação como problema clínico ignora as barreiras que efetivamente o produzem.',
  refs: ['Lei nº 8.213/1991 — arts. 89 a 93', 'Literatura sobre retorno ao trabalho'] }

);
