/* Lote AS — 2.2, 2.3, 2.4, 2.6, 2.7, 2.9, 4.4, 4.5, 4.6, 4.8, 4.9, 4.10. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.2-140', tema: '2.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a radiação ultravioleta artificial, é CORRETO afirmar:',
  alts: [
    { t: 'Soldagem, esterilização e cura de resinas expõem, e o alcance atinge trabalhadores próximos.', ok: true,
      why: 'Correta. O terceiro que passa perto é atingido sem estar protegido; daí as barreiras.' },
    { t: 'Soldagem e esterilização geram exposição, limitada ao operador direto do processo que a produz.', ok: false,
      why: 'Errada. Trabalhadores próximos são atingidos, o que exige barreiras e delimitação.' },
    { t: 'Soldagem e cura de resinas expõem, manifestando-se a ceratoconjuntivite actínica durante a exposição.', ok: false,
      why: 'Errada. Costuma se manifestar horas depois, o que dificulta associar à causa.' },
    { t: 'Soldagem e cura de resinas expõem, não representando as lâmpadas germicidas risco ocupacional.', ok: false,
      why: 'Errada. Exigem projeto e procedimento para evitar exposição de pessoas.' },
    { t: 'Soldagem e esterilização expõem, sendo a proteção ocular convencional suficiente em qualquer processo.', ok: false,
      why: 'Errada. É preciso proteção com especificação adequada à faixa e à intensidade.' }
  ],
  comentario: 'Ultravioleta artificial: solda, germicida, fototerapia, cura de resina. Atinge quem passa perto, e a ceratoconjuntivite aparece horas depois — o que faz o trabalhador não relacionar o olho ardendo à noite com a solda da tarde.',
  pegadinha: 'A latência de horas do quadro ocular é o que impede o trabalhador de identificar a causa sozinho.',
  refs: ['ICNIRP', 'ACGIH', 'NR-15'] },

{ id: 'q-2.3-140', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição ocupacional a fumos metálicos em soldagem, é CORRETO afirmar:',
  alts: [
    { t: 'A composição depende do metal base, do revestimento e do consumível, exigindo conhecer o material.', ok: true,
      why: 'Correta. Soldagem não é uma exposição: são muitas, conforme o material soldado.' },
    { t: 'A composição dos fumos é uniforme entre processos, variando apenas a quantidade gerada por hora.', ok: false,
      why: 'Errada. Metal base, revestimento e consumível determinam a composição.' },
    { t: 'A composição depende do material soldado, sendo a febre dos fumos quadro sem relevância ocupacional.', ok: false,
      why: 'Errada. É quadro reconhecido, associado sobretudo à soldagem de galvanizados.' },
    { t: 'A composição depende do material, sendo a ventilação geral do galpão o controle adequado na soldagem.', ok: false,
      why: 'Errada. Exige-se exaustão junto ao ponto de soldagem.' },
    { t: 'A composição depende do metal base, sem que a remoção prévia de revestimentos altere a exposição.', ok: false,
      why: 'Errada. Revestimentos são fonte de cádmio, chumbo e cromo nos fumos.' }
  ],
  comentario: 'Fumo de solda depende do que se solda: cromo hexavalente no inoxidável, manganês nos consumíveis, cádmio e chumbo em revestimentos, zinco na febre dos fumos metálicos. Exaustão no ponto, não ventilação do galpão.',
  pegadinha: 'Registrar a exposição como "fumos de solda" sem identificar o material avalia um agente genérico que não existe.',
  refs: ['ACGIH', 'NHO — Fundacentro', 'Buschinelli — Toxicologia Ocupacional'] },

{ id: 'q-2.4-140', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a exposição a agentes biológicos em atividades de limpeza urbana e coleta de resíduos, é CORRETO afirmar:',
  alts: [
    { t: 'Há exposição a perfurocortantes descartados por terceiros, a zoonoses e a resíduos de saúde.', ok: true,
      why: 'Correta. Quem se fere é o coletor, e a causa está no descarte de outra pessoa.' },
    { t: 'O risco desses trabalhadores decorre de agentes químicos presentes nos resíduos que eles manuseiam.', ok: false,
      why: 'Errada. O risco biológico é central nessas atividades.' },
    { t: 'Há exposição a zoonoses e resíduos, não sendo o descarte inadequado por terceiros fator relevante.', ok: false,
      why: 'Errada. É a principal causa de acidentes com perfurocortantes nesse grupo.' },
    { t: 'Há exposição a perfurocortantes e zoonoses, sem relação da segregação de resíduos com a saúde deles.', ok: false,
      why: 'Errada. É a medida que mais reduz o risco de quem manuseia adiante.' },
    { t: 'Há exposição a perfurocortantes, não integrando os coletores os grupos com indicação antitetânica reforçada.', ok: false,
      why: 'Errada. O risco de ferimentos torna essa proteção prioridade no grupo.' }
  ],
  comentario: 'O coletor se acidenta com a agulha que outra pessoa descartou errado. Segregar na origem é medida de proteção dele — junto com imunização antitetânica e equipamento adequado.',
  pegadinha: 'Ver a segregação de resíduos como assunto ambiental esquece que ela protege quem recolhe.',
  refs: ['NR-32', 'RDC sobre resíduos de serviços de saúde', 'Programa Nacional de Imunizações'] },

{ id: 'q-2.6-140', tema: '2.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a leitura de uma lista de limites de exposição, é CORRETO afirmar:',
  alts: [
    { t: 'Além do valor, a entrada traz notações e o efeito crítico que fundamentou aquele limite.', ok: true,
      why: 'Correta. O efeito crítico é o que indica qual exame de vigilância adotar.' },
    { t: 'O valor numérico do limite é a informação relevante da entrada de cada agente listado.', ok: false,
      why: 'Errada. Notações e efeito crítico orientam medidas e vigilância.' },
    { t: 'Além do valor há notações e efeito crítico, sem utilidade este para definir os exames de vigilância.', ok: false,
      why: 'Errada. É justamente o que indica o alvo a monitorar.' },
    { t: 'Além do valor há o efeito crítico, sendo as notações de absorção e sensibilização meramente informativas.', ok: false,
      why: 'Errada. Alteram as medidas de controle e a interpretação do limite.' },
    { t: 'Além do valor há notações e efeito crítico, não constando dessas listas agentes sem valor numérico.', ok: false,
      why: 'Errada. Há entradas com recomendação de reduzir ao mínimo exequível.' }
  ],
  comentario: 'A entrada do agente traz mais que um número: notações e o efeito crítico que fundamentou o valor. É o efeito crítico que indica qual exame faz sentido na vigilância daquele exposto.',
  pegadinha: 'Copiar apenas o valor numérico da tabela descarta a informação que orienta o programa médico.',
  refs: ['ACGIH — TLVs e documentação', 'NR-7', 'NR-9'] },

{ id: 'q-2.7-120', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a calibração e a verificação de instrumentos usados em avaliações de higiene ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A calibração exige rastreabilidade, e a verificação de campo antes e depois é procedimento distinto.', ok: true,
      why: 'Correta. São coisas diferentes e ambas exigidas; faltar uma compromete todas as medições.' },
    { t: 'A calibração periódica por entidade competente dispensa a verificação de campo em cada avaliação.', ok: false,
      why: 'Errada. São procedimentos distintos e complementares.' },
    { t: 'A calibração exige rastreabilidade, podendo a verificação de campo ser feita só no início da avaliação.', ok: false,
      why: 'Errada. A verificação posterior confirma que o instrumento manteve o desempenho.' },
    { t: 'A calibração exige rastreabilidade, não precisando o certificado constar da documentação do laudo.', ok: false,
      why: 'Errada. Integra a documentação que sustenta a confiabilidade do resultado.' },
    { t: 'A calibração exige rastreabilidade, não invalidando desvios na verificação posterior as medições feitas.', ok: false,
      why: 'Errada. Desvio relevante compromete os resultados obtidos no período.' }
  ],
  comentario: 'Calibração com rastreabilidade e verificação de campo antes e depois — procedimentos distintos, ambos exigidos, ambos documentados. Desvio na verificação final compromete tudo o que foi medido no dia.',
  pegadinha: 'Verificar só no início deixa sem detecção o desvio que ocorreu durante a jornada de medição.',
  refs: ['NHO — Fundacentro', 'AIHA'] },

{ id: 'q-2.9-140', tema: '2.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de resultados de monitoramento biológico ao trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Deve ser comunicado e explicado, e o alterado exige revisão coletiva da exposição do grupo.', ok: true,
      why: 'Correta. Um resultado alterado é sinal sobre o grupo, não apenas sobre a pessoa.' },
    { t: 'Deve ser arquivado no prontuário e comunicado apenas quando houver necessidade de afastamento.', ok: false,
      why: 'Errada. O trabalhador tem direito de conhecer e compreender o resultado.' },
    { t: 'Deve ser comunicado e explicado, sem que o alterado em um trabalhador indique revisão do grupo.', ok: false,
      why: 'Errada. Sinaliza possível falha de controle que alcança os demais.' },
    { t: 'Deve ser comunicado, sendo dispensável explicar o significado quando o valor está dentro do normal.', ok: false,
      why: 'Errada. Compreender o significado do monitoramento sustenta a adesão ao programa.' },
    { t: 'Deve ser comunicado e explicado, podendo a transmissão ser feita pela chefia imediata do trabalhador.', ok: false,
      why: 'Errada. É informação de saúde, comunicada diretamente pelo médico ao trabalhador.' }
  ],
  comentario: 'Resultado de monitoramento biológico se comunica e se explica ao trabalhador — diretamente, nunca pela chefia. E alterado em um é hipótese de falha de controle que alcança o grupo inteiro.',
  pegadinha: 'Tratar o resultado alterado como caso individual perde o sinal que ele dá sobre o setor.',
  refs: ['NR-7', 'ACGIH — BEIs', 'Código de Ética Médica'] },

{ id: 'q-4.4-140', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o retorno ao trabalho de trabalhador com dermatose ocupacional em mãos, é CORRETO afirmar:',
  alts: [
    { t: 'Depende de eliminar ou de controlar o contato, podendo a luva ser insuficiente ou agravar pela oclusão', ok: true,
      why: 'Correta. A intervenção que resolve costuma estar no processo, não no equipamento.' },
    { t: 'Depende do controle do contato, resolvendo o uso de luva a maioria dos casos e permitindo retorno imediato.', ok: false,
      why: 'Errada. Pode ser insuficiente e, pela oclusão, agravar a dermatite irritativa.' },
    { t: 'Depende da cicatrização das lesões, que autoriza o retorno independentemente do controle do agente.', ok: false,
      why: 'Errada. Retorno ao mesmo contato reproduz o quadro.' },
    { t: 'Depende de eliminar ou controlar o contato, não sendo a substituição do produto alternativa aplicável.', ok: false,
      why: 'Errada. É frequentemente a intervenção mais eficaz.' },
    { t: 'Depende do controle do contato, não gerando a dermatose em mãos repercussão funcional relevante.', ok: false,
      why: 'Errada. Compromete preensão, contato com materiais e higienização.' }
  ],
  comentario: 'Retorno em dermatose de mãos exige eliminar ou controlar o contato — e luva pode piorar por oclusão. Trocar o produto ou o processo é o que costuma permitir a permanência na função.',
  pegadinha: 'Liberar o retorno na cicatrização, sem mexer no agente, agenda a próxima recidiva.',
  refs: ['Salim — Dermatoses Ocupacionais', 'NR-6'] },

{ id: 'q-4.5-130', tema: '4.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a caracterização da perda auditiva induzida por ruído para fins de reconhecimento, é CORRETO afirmar:',
  alts: [
    { t: 'Considera padrão audiométrico, exposição documentada e exclusão razoável de outras causas.', ok: true,
      why: 'Correta. A estabilização após cessada a exposição é característica que a distingue.' },
    { t: 'Considera o padrão audiométrico e a exposição, progredindo a perda mesmo após o afastamento do ruído.', ok: false,
      why: 'Errada. Tende a estabilizar após cessada a exposição.' },
    { t: 'Considera o padrão audiométrico, isoladamente suficiente para caracterizar a perda induzida por ruído.', ok: false,
      why: 'Errada. Exige história de exposição e exclusão de outras causas.' },
    { t: 'Considera padrão e exposição, sendo a perda reversível quando detectada precocemente no programa.', ok: false,
      why: 'Errada. A perda permanente instalada é irreversível; o que se evita é a progressão.' },
    { t: 'Considera padrão e exposição ocupacional, sem necessidade de investigar a exposição extraocupacional.', ok: false,
      why: 'Errada. Deve ser considerada, sem que afaste a contribuição ocupacional.' }
  ],
  comentario: 'Caracterizar exige padrão audiométrico, exposição documentada e exclusão razoável de outras causas. A perda é irreversível e estabiliza após o afastamento — o que se ganha detectando cedo é impedir a progressão.',
  pegadinha: 'Prometer recuperação com o afastamento cria expectativa que o quadro não permite.',
  refs: ['NR-7 — Anexo I', 'Diretrizes de audiologia ocupacional'] },

{ id: 'q-4.6-130', tema: '4.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o papel da chefia imediata na saúde mental das equipes, é CORRETO afirmar:',
  alts: [
    { t: 'O estilo da chefia imediata é dos fatores mais associados aos desfechos de saúde mental da equipe.', ok: true,
      why: 'Correta. É a variável organizacional mais próxima do trabalhador, e capacitá-la tem efeito documentado.' },
    { t: 'O estilo de gestão da chefia imediata não guarda associação com a saúde mental da equipe conduzida.', ok: false,
      why: 'Errada. É associação consistentemente documentada.' },
    { t: 'O estilo da chefia se associa aos desfechos, sem que sua capacitação em saúde mental os altere.', ok: false,
      why: 'Errada. Há evidência de efeito sobre suporte percebido e sobre afastamentos.' },
    { t: 'O estilo da chefia importa, devendo ela conhecer os diagnósticos da equipe para exercer esse papel.', ok: false,
      why: 'Errada. O papel se exerce com informação sobre restrições e suporte, nunca com diagnósticos.' },
    { t: 'O estilo da chefia importa no dia a dia, sendo o suporte dela irrelevante no retorno após afastamento.', ok: false,
      why: 'Errada. É um dos preditores mais fortes do sucesso do retorno.' }
  ],
  comentario: 'A chefia imediata é a variável organizacional mais próxima do trabalhador — e capacitá-la em reconhecimento e suporte tem efeito documentado. Sem jamais receber diagnóstico: recebe restrição e orientação de suporte.',
  pegadinha: 'Capacitar a chefia não significa informá-la de diagnósticos; a linha entre suporte e quebra de sigilo é essa.',
  refs: ['OIT — riscos psicossociais', 'Literatura sobre retorno ao trabalho', 'Código de Ética Médica'] },

{ id: 'q-4.8-130', tema: '4.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a substituição de agentes cancerígenos em processos produtivos, é CORRETO afirmar:',
  alts: [
    { t: 'Deve ser precedida de avaliação do substituto, para não trocar por agente pior ou desconhecido.', ok: true,
      why: 'Correta. Trocar sem avaliar já produziu substituições piores que o original.' },
    { t: 'Deve ser buscada sempre que possível, representando qualquer substituição de cancerígeno ganho automático.', ok: false,
      why: 'Errada. O substituto pode ter perfil toxicológico pior ou desconhecido.' },
    { t: 'Deve ser precedida de avaliação, significando a ausência de classificação do substituto ausência de risco.', ok: false,
      why: 'Errada. Pode significar apenas ausência de estudos, o que é diferente.' },
    { t: 'Deve ser precedida de avaliação do substituto, dispensando a troca a reavaliação do inventário de riscos.', ok: false,
      why: 'Errada. Novo agente exige nova avaliação.' },
    { t: 'Deve ser precedida de avaliação do substituto, restrita essa análise à carcinogenicidade do novo agente.', ok: false,
      why: 'Errada. Deve considerar o conjunto de efeitos, inclusive reprodutivos e sensibilizantes.' }
  ],
  comentario: 'Substituir cancerígeno é prioridade, mas com avaliação do substituto — inclusive efeitos reprodutivos e sensibilizantes. Ausência de classificação costuma significar ausência de estudo, não ausência de risco.',
  pegadinha: '"Não consta como cancerígeno" pode significar apenas que ninguém estudou.',
  refs: ['IARC', 'ACGIH', 'NR-9'] },

{ id: 'q-4.9-120', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a investigação de surto de doença transmissível em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Define caso, levanta a curva epidêmica, identifica exposições comuns e testa hipóteses sobre a fonte.', ok: true,
      why: 'Correta. Tempo e lugar dos casos apontam a fonte antes de qualquer exame laboratorial.' },
    { t: 'Define caso e levanta a curva, dependendo necessariamente de confirmação laboratorial prévia dos casos.', ok: false,
      why: 'Errada. A investigação se inicia com definição de caso e não aguarda confirmação.' },
    { t: 'Define caso e testa hipóteses, não sendo relevante a distribuição espacial dos casos na planta.', ok: false,
      why: 'Errada. É uma das principais pistas sobre a exposição compartilhada.' },
    { t: 'Levanta a curva epidêmica e identifica exposições, definindo o caso ao final da investigação conduzida.', ok: false,
      why: 'Errada. É a primeira etapa, e orienta toda a coleta subsequente.' },
    { t: 'Define caso e testa hipóteses, devendo as medidas de controle aguardar a conclusão da investigação.', ok: false,
      why: 'Errada. Medidas iniciais são adotadas em paralelo, conforme as hipóteses.' }
  ],
  comentario: 'Surto: define-se caso, monta-se a curva, mapeiam-se os casos no espaço e se testam hipóteses — com medidas de controle iniciadas em paralelo, sem esperar a conclusão nem o laboratório.',
  pegadinha: 'Aguardar confirmação laboratorial para agir consome o tempo em que a medida de controle interromperia a transmissão.',
  refs: ['Ministério da Saúde — investigação de surtos', 'NR-32'] },

{ id: 'q-4.10-120', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a indicação de imunização em trabalhadores de laboratório, é CORRETO afirmar:',
  alts: [
    { t: 'Decorre dos agentes manipulados e do nível de contenção, podendo ir além do calendário geral.', ok: true,
      why: 'Correta. Mudança de agente manipulado é gatilho de reavaliação vacinal.' },
    { t: 'Decorre do calendário vacinal do adulto, aplicável a esses trabalhadores como a qualquer outro grupo.', ok: false,
      why: 'Errada. Pode incluir imunizações específicas conforme os agentes manipulados.' },
    { t: 'Decorre dos agentes manipulados, não exigindo a mudança de agente reavaliação da situação vacinal.', ok: false,
      why: 'Errada. É gatilho direto de reavaliação.' },
    { t: 'Decorre dos agentes manipulados, sem que o nível de contenção da atividade influencie a indicação.', ok: false,
      why: 'Errada. Compõe a avaliação de risco que fundamenta a indicação.' },
    { t: 'Decorre dos agentes e da contenção, não se aplicando a verificação sorológica a esses trabalhadores.', ok: false,
      why: 'Errada. É especialmente indicada em grupos de alto risco de exposição.' }
  ],
  comentario: 'Em laboratório, a vacina segue o agente manipulado e o nível de contenção — inclusive imunizações fora do calendário geral. Trocou de linha de pesquisa, reavalia.',
  pegadinha: 'Aplicar o calendário do adulto e considerar resolvido ignora os agentes específicos daquela bancada.',
  refs: ['NR-32', 'Programa Nacional de Imunizações', 'Diretrizes de biossegurança'] }

);
