/* Lote AO — 7.1 a 7.8, 6.1 a 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.1-100', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a caracterização de periculosidade e suas diferenças em relação à insalubridade, é CORRETO afirmar:',
  alts: [
    { t: 'A periculosidade decorre da exposição a atividades e operações com risco acentuado de dano grave e imediato — como inflamáveis, explosivos, energia elétrica, roubos e motociclistas —, lógica distinta da insalubridade, que se apoia em agentes nocivos à saúde ao longo do tempo.', ok: true,
      why: 'Correta. Uma trata de risco de evento agudo grave; a outra, de dano à saúde por exposição.' },
    { t: 'Periculosidade e insalubridade seguem a mesma lógica de caracterização.', ok: false,
      why: 'Errada. Uma se apoia em risco de dano grave e imediato; a outra, em agente nocivo à saúde.' },
    { t: 'A periculosidade depende de medição quantitativa do agente.', ok: false,
      why: 'Errada. Caracteriza-se pela atividade ou operação descrita na norma.' },
    { t: 'A base de cálculo dos dois adicionais é a mesma.', ok: false,
      why: 'Errada. As bases de cálculo são distintas.' },
    { t: 'A exposição eventual e fortuita caracteriza periculosidade.', ok: false,
      why: 'Errada. A exposição eventual, por tempo extremamente reduzido, é excluída da caracterização.' }
  ],
  comentario: 'Periculosidade: risco de dano grave e imediato, caracterizado pela atividade descrita na norma, sem medição — inflamáveis, explosivos, eletricidade, segurança pessoal, motociclistas. Insalubridade é outra lógica e outra base de cálculo.',
  pegadinha: 'Buscar medição quantitativa para caracterizar periculosidade aplica o método da insalubridade ao instituto errado.',
  refs: ['CLT — art. 193', 'NR-16', 'NR-15'] },

{ id: 'q-7.2-110', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o salário-maternidade e a proteção previdenciária à trabalhadora, é CORRETO afirmar:',
  alts: [
    { t: 'O benefício é devido também em casos de aborto não criminoso, adoção e guarda judicial para fins de adoção, com prazos próprios — e sua concessão não se confunde com afastamento por incapacidade, tendo natureza e requisitos distintos.', ok: true,
      why: 'Correta. É benefício próprio, com hipóteses que vão além do parto.' },
    { t: 'O benefício é devido exclusivamente em caso de parto.', ok: false,
      why: 'Errada. Alcança também aborto não criminoso, adoção e guarda para adoção.' },
    { t: 'O salário-maternidade tem os mesmos requisitos do benefício por incapacidade.', ok: false,
      why: 'Errada. São benefícios de natureza e requisitos distintos.' },
    { t: 'A adoção não gera direito ao benefício.', ok: false,
      why: 'Errada. Gera, com prazos previstos em lei.' },
    { t: 'O afastamento por risco à gestação equivale ao salário-maternidade.', ok: false,
      why: 'Errada. O afastamento de atividade insalubre durante a gestação segue regra própria e distinta.' }
  ],
  comentario: 'Salário-maternidade alcança parto, aborto não criminoso, adoção e guarda para adoção — e não se confunde nem com benefício por incapacidade nem com o afastamento de atividade insalubre na gestação.',
  pegadinha: 'Misturar salário-maternidade com o afastamento de insalubre durante a gestação junta dois institutos com regras próprias.',
  refs: ['Lei nº 8.213/1991 — arts. 71 a 73', 'CLT — art. 394-A'] },

{ id: 'q-7.3-110', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o controle sanitário de estabelecimentos de saúde e a proteção dos trabalhadores desses serviços, é CORRETO afirmar:',
  alts: [
    { t: 'As exigências sanitárias de estrutura, fluxos e processos protegem simultaneamente pacientes e trabalhadores, de modo que inadequações de ventilação, de fluxo de material contaminado ou de área física repercutem sobre os dois grupos.', ok: true,
      why: 'Correta. As mesmas falhas atingem quem é atendido e quem trabalha.' },
    { t: 'As exigências sanitárias visam exclusivamente à proteção dos pacientes.', ok: false,
      why: 'Errada. Protegem também os trabalhadores do serviço.' },
    { t: 'Fluxos de material contaminado não têm relação com a saúde dos trabalhadores.', ok: false,
      why: 'Errada. O fluxo inadequado é fonte direta de exposição da equipe.' },
    { t: 'A adequação de área física é requisito sem repercussão ocupacional.', ok: false,
      why: 'Errada. Espaço insuficiente aumenta risco de acidentes e de exposição.' },
    { t: 'A fiscalização sanitária de serviços de saúde não considera condições de trabalho.', ok: false,
      why: 'Errada. Elas integram as condições do estabelecimento verificadas na inspeção.' }
  ],
  comentario: 'Em serviço de saúde, o requisito sanitário e o ocupacional convergem: ventilação, fluxo de material contaminado e área física protegem paciente e equipe pelas mesmas razões.',
  pegadinha: 'Separar exigência sanitária de exigência ocupacional trata como distintos dois efeitos da mesma falha.',
  refs: ['RDC sobre estabelecimentos de saúde', 'NR-32', 'Lei nº 8.080/1990'] },

{ id: 'q-7.4-110', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o trabalho em altura, é CORRETO afirmar:',
  alts: [
    { t: 'Exige análise de risco, permissão de trabalho para atividades não rotineiras, sistemas de proteção contra quedas e capacitação com reciclagem periódica — e é necessário haver procedimento de resgate, pois a suspensão inerte prolongada no cinturão gera risco próprio.', ok: true,
      why: 'Correta. Deter a queda é metade da solução; a outra é resgatar rápido.' },
    { t: 'O uso de cinturão de segurança encerra as exigências para trabalho em altura.', ok: false,
      why: 'Errada. Análise de risco, permissão, capacitação e plano de resgate integram os requisitos.' },
    { t: 'O resgate após queda detida pode aguardar a chegada de serviço externo.', ok: false,
      why: 'Errada. A suspensão inerte prolongada tem risco próprio e exige resgate rápido.' },
    { t: 'A capacitação para trabalho em altura é única, sem necessidade de reciclagem.', ok: false,
      why: 'Errada. Há previsão de capacitação periódica.' },
    { t: 'A avaliação de saúde para trabalho em altura é dispensável quando o trabalhador é experiente.', ok: false,
      why: 'Errada. A avaliação de aptidão é exigência independente da experiência.' }
  ],
  comentario: 'Altura: análise de risco, permissão para o não rotineiro, sistema de retenção, capacitação com reciclagem, avaliação de aptidão e — o mais esquecido — plano de resgate, porque ficar pendurado tem risco próprio.',
  pegadinha: 'Deter a queda e não conseguir resgatar em minutos transforma o sistema de proteção em outra emergência.',
  refs: ['NR-35'] },

{ id: 'q-7.5-080', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o monitoramento da saúde do trabalhador no eSocial e o sigilo das informações, é CORRETO afirmar:',
  alts: [
    { t: 'O evento transmite a conclusão de aptidão e os exames realizados, sem diagnósticos ou resultados — modelo que reproduz, no ambiente digital, o mesmo limite que separa o atestado de saúde ocupacional do prontuário médico.', ok: true,
      why: 'Correta. A separação entre o que circula e o que fica sob guarda médica é a mesma.' },
    { t: 'O evento deve conter os resultados dos exames complementares realizados.', ok: false,
      why: 'Errada. Informa-se a realização, não os resultados.' },
    { t: 'A transmissão digital reduz as exigências de sigilo aplicáveis.', ok: false,
      why: 'Errada. As exigências permanecem e a segurança da informação se soma a elas.' },
    { t: 'O sistema exige a informação do diagnóstico para validar a conclusão de aptidão.', ok: false,
      why: 'Errada. A conclusão de aptidão não requer diagnóstico associado.' },
    { t: 'A responsabilidade pelo sigilo passa integralmente ao operador do sistema.', ok: false,
      why: 'Errada. O médico responsável mantém suas obrigações de sigilo.' }
  ],
  comentario: 'No eSocial vai o que já ia no atestado: exames realizados e conclusão de aptidão. Diagnóstico e resultado ficam no prontuário — o meio digital não muda essa fronteira, apenas acrescenta requisitos de segurança.',
  pegadinha: 'Supor que o campo do sistema pede diagnóstico leva a inserir dado sensível em base compartilhada.',
  refs: ['eSocial — evento de monitoramento da saúde', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-7.6-080', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a emissão de atestado de saúde ocupacional por médico que não realizou o exame, é CORRETO afirmar:',
  alts: [
    { t: 'É vedado atestar sobre condição que não foi pessoalmente avaliada, e a assinatura de documentos sem realização do exame configura infração ética grave — prática que aparece em serviços que produzem atestados em volume incompatível com o tempo disponível.', ok: true,
      why: 'Correta. Atestar sem examinar é falsidade, ainda que o resultado "esteja certo".' },
    { t: 'A prática é admissível quando o exame foi realizado por outro profissional da equipe.', ok: false,
      why: 'Errada. Quem assina deve ter realizado a avaliação que atesta.' },
    { t: 'A responsabilidade recai sobre a empresa que organizou o serviço, e não sobre o médico signatário.', ok: false,
      why: 'Errada. A responsabilidade pelo ato é pessoal de quem assina.' },
    { t: 'O volume de exames realizados não é elemento relevante na apuração.', ok: false,
      why: 'Errada. Volume incompatível com o tempo disponível é indício investigado.' },
    { t: 'A prática configura apenas irregularidade administrativa, sem repercussão ética.', ok: false,
      why: 'Errada. É infração ética, com repercussão disciplinar própria.' }
  ],
  comentario: 'Assinar exame que não se fez é infração ética pessoal — não da empresa, não do serviço. E o volume de atestados por hora é justamente o indício que a fiscalização e o conselho examinam.',
  pegadinha: 'Delegar o exame e assinar o documento não distribui a responsabilidade: ela é de quem assina.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM'] },

{ id: 'q-7.7-080', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o prontuário médico segundo as resoluções do conselho profissional, é CORRETO afirmar:',
  alts: [
    { t: 'É documento único do paciente, de elaboração obrigatória e legível, com prazos definidos de guarda e possibilidade de manutenção em meio eletrônico desde que atendidos requisitos de segurança e integridade.', ok: true,
      why: 'Correta. Único, obrigatório, legível, guardado por prazo definido, admitindo meio eletrônico com requisitos.' },
    { t: 'O prontuário pode ser fragmentado em documentos separados por especialidade.', ok: false,
      why: 'Errada. É documento único do paciente, ainda que com registros de vários profissionais.' },
    { t: 'A guarda em meio eletrônico dispensa requisitos específicos de segurança.', ok: false,
      why: 'Errada. Exige requisitos de segurança, integridade e autenticidade.' },
    { t: 'A elaboração do prontuário é facultativa em atendimentos ocupacionais.', ok: false,
      why: 'Errada. É obrigatória em qualquer atendimento médico.' },
    { t: 'Não há prazo definido para guarda de prontuários.', ok: false,
      why: 'Errada. Há prazos estabelecidos, particularmente relevantes em saúde ocupacional pela latência dos agravos.' }
  ],
  comentario: 'Prontuário: único por paciente, obrigatório, legível, guardado por prazo definido, eletrônico admitido com requisitos de segurança. Em saúde ocupacional a guarda longa é o que sustenta o nexo décadas depois.',
  pegadinha: 'Fragmentar o prontuário por serviço ou especialidade desfaz o histórico que dá sentido a cada registro.',
  refs: ['Resoluções do CFM sobre prontuário', 'Código de Ética Médica'] },

{ id: 'q-7.8-080', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o tratamento de dados biométricos de trabalhadores para controle de jornada e acesso, é CORRETO afirmar:',
  alts: [
    { t: 'Dados biométricos são categoria sensível, exigindo finalidade específica, proporcionalidade e avaliação de alternativas menos invasivas — e a adoção deve considerar que biometria comprometida não pode ser trocada como uma senha.', ok: true,
      why: 'Correta. É o argumento decisivo: impressão digital vazada é permanente.' },
    { t: 'Dados biométricos são dados pessoais comuns, sem regime específico.', ok: false,
      why: 'Errada. São expressamente categoria sensível.' },
    { t: 'A adoção de biometria dispensa avaliação de alternativas.', ok: false,
      why: 'Errada. A proporcionalidade exige considerar meios menos invasivos.' },
    { t: 'O consentimento do empregado é base suficiente para o tratamento nesse contexto.', ok: false,
      why: 'Errada. A assimetria da relação de emprego fragiliza essa base.' },
    { t: 'Um incidente com dados biométricos tem impacto equivalente ao de um vazamento de senhas.', ok: false,
      why: 'Errada. Biometria não pode ser substituída após comprometimento, o que agrava o impacto.' }
  ],
  comentario: 'Biometria é dado sensível e irreversível: senha vazada se troca, digital não. Exige finalidade específica, proporcionalidade e avaliação de alternativas — e o consentimento do empregado é base frágil.',
  pegadinha: 'Tratar incidente com biometria como equivalente a vazamento de senha subestima um dano que é permanente.',
  refs: ['LGPD — art. 5º, II e art. 11', 'Autoridade Nacional de Proteção de Dados'] },

{ id: 'q-6.1-120', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a responsabilidade pela elaboração e coordenação do programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'A coordenação cabe a médico do trabalho, que responde tecnicamente pelo programa, e sua elaboração deve considerar os riscos identificados no inventário — sendo o programa documento vivo, revisto quando muda o risco, e não peça anual repetida.', ok: true,
      why: 'Correta. Coordenação técnica médica e revisão por mudança de risco.' },
    { t: 'A coordenação do programa pode ser atribuída a qualquer profissional de saúde.', ok: false,
      why: 'Errada. A coordenação é atribuição de médico do trabalho.' },
    { t: 'O programa deve ser revisto apenas na periodicidade máxima prevista.', ok: false,
      why: 'Errada. Mudança de risco ou de processo exige revisão antecipada.' },
    { t: 'A elaboração independe do inventário de riscos da empresa.', ok: false,
      why: 'Errada. O programa médico decorre dos riscos identificados.' },
    { t: 'A responsabilidade técnica pelo programa é da empresa contratante, e não do médico coordenador.', ok: false,
      why: 'Errada. A responsabilidade técnica é pessoal do médico coordenador.' }
  ],
  comentario: 'Coordenação por médico do trabalho, com responsabilidade técnica pessoal, programa derivado do inventário e revisto quando o risco muda — não copiado de um ano para o outro.',
  pegadinha: 'Reeditar o programa anualmente sem revisar os riscos produz documento em dia e desatualizado.',
  refs: ['NR-7', 'NR-4', 'NR-1'] },

{ id: 'q-6.2-120', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre tecnologia assistiva no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Abrange recursos e serviços que ampliam a funcionalidade e a autonomia, de leitores de tela a adaptações de posto e comunicação — e sua indicação deve partir da atividade concreta que a pessoa precisa executar, com participação dela na escolha.', ok: true,
      why: 'Correta. Recurso escolhido sem a pessoa costuma virar equipamento parado.' },
    { t: 'Tecnologia assistiva se restringe a equipamentos de alto custo.', ok: false,
      why: 'Errada. Inclui adaptações simples e de baixo custo, frequentemente as mais eficazes.' },
    { t: 'A escolha do recurso deve ser feita pela empresa, sem participação do trabalhador.', ok: false,
      why: 'Errada. A participação é determinante para a adequação e o uso efetivo.' },
    { t: 'A indicação deve partir do diagnóstico, e não da atividade a ser executada.', ok: false,
      why: 'Errada. Parte da atividade e da barreira concreta a ser superada.' },
    { t: 'Uma vez fornecido o recurso, não é necessário acompanhamento de sua adequação.', ok: false,
      why: 'Errada. O ajuste após o uso real costuma ser necessário.' }
  ],
  comentario: 'Tecnologia assistiva parte da atividade e da barreira concreta, com a pessoa participando da escolha — e muita coisa eficaz é simples e barata. Fornecer sem acompanhar produz equipamento encostado.',
  pegadinha: 'Escolher pelo diagnóstico em vez da tarefa entrega o recurso errado com boa intenção.',
  refs: ['Lei nº 13.146/2015', 'CIF — OMS'] },

{ id: 'q-6.3-120', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o trabalhador em uso de medicamentos e a avaliação de aptidão, é CORRETO afirmar:',
  alts: [
    { t: 'A avaliação considera os efeitos do medicamento sobre atenção, coordenação e resposta a condições ambientais, além da condição tratada — e o objetivo é viabilizar o trabalho com segurança, não desestimular o tratamento, que é o efeito de conclusões restritivas automáticas.', ok: true,
      why: 'Correta. Restrição automática por uso de medicamento faz o trabalhador esconder o tratamento.' },
    { t: 'O uso de qualquer medicamento contínuo justifica restrição de função.', ok: false,
      why: 'Errada. A restrição decorre do efeito funcional avaliado, não do uso em si.' },
    { t: 'Medicamentos que aumentam a sensibilidade ao calor ou à luz solar não têm relevância ocupacional.', ok: false,
      why: 'Errada. Fotossensibilizantes e fármacos que interferem na termorregulação têm relevância direta.' },
    { t: 'O trabalhador não precisa ser orientado sobre interações entre medicamento e exposições do trabalho.', ok: false,
      why: 'Errada. Essa orientação é parte do cuidado ocupacional.' },
    { t: 'A informação sobre medicamentos em uso deve constar do atestado entregue à empresa.', ok: false,
      why: 'Errada. É informação clínica que permanece no prontuário.' }
  ],
  comentario: 'Avalia-se o efeito funcional do medicamento e a interação com as exposições — fotossensibilidade, termorregulação, atenção. Restringir por uso, em vez de por efeito, ensina o trabalhador a omitir o tratamento.',
  pegadinha: 'A restrição automática por psicotrópico ou anti-hipertensivo produz omissão, que é pior para a segurança.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.4-120', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a organização dos primeiros socorros em frentes de trabalho remotas, é CORRETO afirmar:',
  alts: [
    { t: 'Quanto maior o isolamento, maior a capacidade própria exigida — com pessoal treinado, materiais compatíveis com os riscos da atividade, meios de comunicação confiáveis e plano de evacuação definido antes do início dos trabalhos.', ok: true,
      why: 'Correta. Em frente remota, o plano de evacuação precisa existir antes de ser necessário.' },
    { t: 'O padrão de primeiros socorros independe da distância até o serviço de emergência.', ok: false,
      why: 'Errada. O tempo de resposta externo determina a capacidade própria exigida.' },
    { t: 'Meios de comunicação são item acessório em frentes remotas.', ok: false,
      why: 'Errada. Sem comunicação confiável, não há acionamento nem evacuação.' },
    { t: 'O plano de evacuação pode ser definido no momento da ocorrência.', ok: false,
      why: 'Errada. Definir durante a emergência consome o tempo que faria diferença.' },
    { t: 'O material de primeiros socorros deve ser padronizado independentemente dos riscos da atividade.', ok: false,
      why: 'Errada. Deve ser compatível com os riscos específicos, como acidentes com peçonhentos ou químicos.' }
  ],
  comentario: 'Frente remota exige capacidade própria proporcional ao isolamento: gente treinada, material compatível com o risco, comunicação que funcione e evacuação planejada antes — não improvisada durante.',
  pegadinha: 'Kit padronizado em frente com risco de acidente ofídico não tem o que o caso vai exigir.',
  refs: ['NR-31', 'NR-1', 'NR-22'] }

);
