/* Lote AE — 6.1, 6.2, 6.3, 6.4, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-6.1-090', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o relatório analítico do programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'Consolida os resultados por grupo e por risco, sem identificação, e aponta o planejamento seguinte.', ok: true,
      why: 'Correta. É a peça que fecha o ciclo entre vigilância da saúde e ação sobre o ambiente.' },
    { t: 'Consolida os achados do período e deve conter os resultados individuais de cada trabalhador avaliado.', ok: false,
      why: 'Errada. É documento consolidado, sem identificação individual.' },
    { t: 'Consolida os resultados por grupo, sendo dispensável quando não houve alterações no período.', ok: false,
      why: 'Errada. É obrigatório, e a ausência de alterações também é resultado a analisar.' },
    { t: 'Consolida a produção do período, limitando-se a listar os quantitativos de exames realizados.', ok: false,
      why: 'Errada. Deve analisar os achados e propor o planejamento seguinte.' },
    { t: 'Consolida os resultados por grupo e por risco, sem que a empresa precise ter acesso a ele.', ok: false,
      why: 'Errada. É documento destinado a orientar as ações da empresa, no formato consolidado.' }
  ],
  comentario: 'O relatório analítico é o que transforma exames em informação de gestão: consolidado por grupo e risco, sem nomes, com análise dos achados e planejamento do período seguinte. Contagem de exames realizados não é relatório analítico.',
  pegadinha: 'Entregar quantitativos no lugar de análise cumpre a formalidade e não fecha o ciclo com o ambiente.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.2-090', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a acessibilidade e a adaptação razoável no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'São modificações necessárias que não imponham ônus desproporcional, e recusá-las é discriminação.', ok: true,
      why: 'Correta. Ônus desproporcional se demonstra; não se alega genericamente.' },
    { t: 'São modificações necessárias, obrigatórias apenas quando não geram qualquer custo à empresa.', ok: false,
      why: 'Errada. O critério é a desproporcionalidade do ônus, não a ausência de custo.' },
    { t: 'São modificações necessárias, sendo a recusa decisão discricionária do empregador contratante.', ok: false,
      why: 'Errada. A recusa injustificada configura discriminação.' },
    { t: 'São modificações necessárias, restringindo-se a acessibilidade às adaptações arquitetônicas do local.', ok: false,
      why: 'Errada. Abrange comunicação, tecnologia assistiva, mobiliário e organização do trabalho.' },
    { t: 'São modificações necessárias, que beneficiam exclusivamente o trabalhador com deficiência.', ok: false,
      why: 'Errada. Muitas adaptações beneficiam o conjunto dos trabalhadores.' }
  ],
  comentario: 'Adaptação razoável: necessária, adequada e sem ônus desproporcional — que precisa ser demonstrado. Acessibilidade vai além de rampa: comunicação, tecnologia assistiva, mobiliário e organização do trabalho.',
  pegadinha: 'Alegar custo sem demonstrá-lo é a forma mais comum de recusa disfarçada.',
  refs: ['Lei nº 13.146/2015', 'Convenção sobre os Direitos das Pessoas com Deficiência'] },

{ id: 'q-6.3-090', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a epilepsia e a avaliação de aptidão para atividades de risco, é CORRETO afirmar:',
  alts: [
    { t: 'Considera tipo de crise, tempo sem crises, adesão e fatores desencadeantes da atividade.', ok: true,
      why: 'Correta. O diagnóstico isolado é insuficiente para concluir por inaptidão.' },
    { t: 'Considera o diagnóstico de epilepsia, que implica inaptidão para qualquer atividade laboral.', ok: false,
      why: 'Errada. A maioria das funções não apresenta risco incompatível.' },
    { t: 'Considera o tipo de crise e a adesão, sem que o tempo sem crises influencie a avaliação.', ok: false,
      why: 'Errada. É um dos principais determinantes da decisão.' },
    { t: 'Considera o tipo de crise, sem que privação de sono e turnos interfiram no controle das crises.', ok: false,
      why: 'Errada. São fatores desencadeantes reconhecidos e relevantes na escala.' },
    { t: 'Considera vários fatores, afastando a omissão do diagnóstico a responsabilidade da empresa.', ok: false,
      why: 'Errada. As medidas de proteção coletiva no posto permanecem exigíveis.' }
  ],
  comentario: 'Epilepsia: decide tipo de crise, tempo livre de crises, adesão e desencadeantes na atividade — não o diagnóstico. Privação de sono e turnos são fatores desencadeantes que a escala pode evitar.',
  pegadinha: 'Concluir pelo diagnóstico afasta do trabalho pessoas com anos sem crise e boa adesão.',
  refs: ['Diretrizes de epilepsia e aptidão laboral', 'NR-7'] },

{ id: 'q-6.4-090', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o plano de resposta a emergências em empresas com riscos de processo, é CORRETO afirmar:',
  alts: [
    { t: 'Deve prever cenários, recursos, comunicação e articulação externa, com simulados periódicos.', ok: true,
      why: 'Correta. Plano nunca testado falha no primeiro uso real.' },
    { t: 'Deve ser genérico o bastante para cobrir qualquer situação de emergência que venha a ocorrer.', ok: false,
      why: 'Errada. Cenários específicos permitem preparo concreto de recursos e fluxos.' },
    { t: 'Deve prever cenários e recursos, sendo os simulados dispensáveis com o plano bem documentado.', ok: false,
      why: 'Errada. É o simulado que testa o plano e treina as pessoas.' },
    { t: 'Deve prever cenários e recursos, sendo desnecessária a articulação prévia com serviços externos.', ok: false,
      why: 'Errada. O tempo de resposta e a preparação externa dependem dessa articulação.' },
    { t: 'Deve prever cenários e simulados, sendo opcional a revisão do plano após um evento real.', ok: false,
      why: 'Errada. É a oportunidade mais valiosa de aprendizado e correção.' }
  ],
  comentario: 'Plano de emergência: cenários específicos, recursos definidos, fluxo de comunicação, articulação externa prévia e simulados periódicos. Plano documentado e nunca testado descobre suas falhas no pior momento.',
  pegadinha: 'O plano genérico dá conforto documental e não prepara ninguém para o cenário concreto.',
  refs: ['NR-1', 'Diretrizes de gerenciamento de emergências'] },

{ id: 'q-1.4-080', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a integração entre o serviço de saúde ocupacional e a comissão interna de prevenção de acidentes, é CORRETO afirmar:',
  alts: [
    { t: 'É canal privilegiado sobre as condições reais, e articulá-la ao serviço médico qualifica os dois.', ok: true,
      why: 'Correta. A comissão traz a informação que o exame não produz.' },
    { t: 'É canal de representação que deve atuar separadamente do serviço médico, para preservar imparcialidade.', ok: false,
      why: 'Errada. A articulação é prevista e aumenta a efetividade de ambos.' },
    { t: 'É canal privilegiado de informação, não devendo o médico do trabalho participar de suas reuniões.', ok: false,
      why: 'Errada. A participação técnica é prevista e desejável.' },
    { t: 'É instância de representação com função formal, sem contribuição técnica relevante ao serviço.', ok: false,
      why: 'Errada. Os representantes conhecem o trabalho real como ninguém no organograma.' },
    { t: 'É canal privilegiado de informação, cujas informações dispensam verificação técnica posterior.', ok: false,
      why: 'Errada. São ponto de partida valioso que deve ser verificado tecnicamente.' }
  ],
  comentario: 'A comissão traz o que o exame não mostra: como o trabalho acontece de fato. Articular o serviço médico com ela qualifica investigação e mapeamento — sem dispensar a verificação técnica do que é relatado.',
  pegadinha: 'Manter os dois separados "por imparcialidade" priva o serviço médico da sua melhor fonte de informação.',
  refs: ['NR-5', 'NR-4', 'NR-1'] },

{ id: 'q-1.5-080', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre auditorias de sistemas de gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Deve verificar a implementação efetiva, com observação do trabalho e entrevista com quem executa.', ok: true,
      why: 'Correta. Auditoria restrita a documentos certifica o sistema descrito, não o praticado.' },
    { t: 'Deve verificar a conformidade documental, evidência suficiente da implementação do sistema auditado.', ok: false,
      why: 'Errada. Documento conforme convive com prática divergente.' },
    { t: 'Deve verificar a implementação, não sendo a entrevista com trabalhadores método válido de auditoria.', ok: false,
      why: 'Errada. É método reconhecido e frequentemente o mais revelador.' },
    { t: 'Deve ser externa, pois auditorias internas não têm valor por lhes faltar independência efetiva.', ok: false,
      why: 'Errada. Têm valor quando conduzidas com independência em relação à área auditada.' },
    { t: 'Deve verificar a implementação, dispensando plano de ação as não conformidades de baixa gravidade.', ok: false,
      why: 'Errada. Toda não conformidade deve gerar tratamento proporcional.' }
  ],
  comentario: 'Auditar é verificar a prática: observar o trabalho, entrevistar quem executa, comparar com o documentado. Auditoria de gaveta certifica o sistema que está escrito, não o que acontece no chão de fábrica.',
  pegadinha: 'Sistema com documentação impecável e prática divergente passa em qualquer auditoria só documental.',
  refs: ['ISO 45001', 'ISO 19011'] },

{ id: 'q-1.6-080', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o controle social nas políticas de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Exerce-se por instâncias com participação de trabalhadores, e depende de acesso à informação.', ok: true,
      why: 'Correta. Participação sem informação qualificada é participação apenas formal.' },
    { t: 'Exerce-se pela eleição de representantes para as instâncias colegiadas previstas no sistema.', ok: false,
      why: 'Errada. Envolve formulação, acompanhamento e fiscalização das ações.' },
    { t: 'Exerce-se por instâncias participativas, sendo vedada nelas a participação de entidades sindicais.', ok: false,
      why: 'Errada. É expressamente prevista.' },
    { t: 'Exerce-se por instâncias participativas, sem que o acesso à informação condicione seu exercício.', ok: false,
      why: 'Errada. Sem informação, a participação se esvazia.' },
    { t: 'Exerce-se por instâncias participativas, incompatíveis com a autonomia técnica dos serviços.', ok: false,
      why: 'Errada. São dimensões complementares e não excludentes.' }
  ],
  comentario: 'Controle social é participar da formulação e do acompanhamento — com informação qualificada, sem a qual a presença nas instâncias é figurativa. Não compete com a autonomia técnica: complementa.',
  pegadinha: 'Garantir assento sem garantir informação produz participação decorativa.',
  refs: ['Lei nº 8.142/1990', 'PNSTT'] },

{ id: 'q-1.7-080', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o financiamento das ações de saúde do trabalhador no sistema público, é CORRETO afirmar:',
  alts: [
    { t: 'Integram o financiamento do sistema de saúde, com repasses específicos para certas estruturas.', ok: true,
      why: 'Correta. Estruturas mantidas por incentivo específico sofrem primeiro com mudança de prioridade.' },
    { t: 'São financiadas por recursos previdenciários arrecadados sobre a folha das empresas contribuintes.', ok: false,
      why: 'Errada. Integram o financiamento do sistema de saúde.' },
    { t: 'Integram o financiamento do sistema, sem que ele influencie a continuidade dessas ações.', ok: false,
      why: 'Errada. É determinante da sustentação e da capilaridade das estruturas.' },
    { t: 'Integram o financiamento do sistema, sem responsabilidade dos municípios nesse financiamento.', ok: false,
      why: 'Errada. O financiamento é tripartite.' },
    { t: 'Integram o financiamento do sistema, com aporte direto das empresas às ações de vigilância.', ok: false,
      why: 'Errada. Elas custeiam suas próprias obrigações; a vigilância pública é de financiamento público.' }
  ],
  comentario: 'Financiamento tripartite dentro do sistema de saúde, com incentivos específicos para certas estruturas — e é justamente essa dependência de indução que torna a rede vulnerável a mudanças de prioridade.',
  pegadinha: 'Atribuir o financiamento à previdência confunde quem paga benefício com quem custeia vigilância.',
  refs: ['Lei nº 8.080/1990', 'RENAST', 'PNSTT'] },

{ id: 'q-1.8-080', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a investigação de óbito relacionado ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A investigação envolve notificação, análise das circunstâncias e do processo de trabalho, e articulação entre saúde, trabalho e ministério público — e o preenchimento adequado da declaração de óbito, informando a relação com o trabalho, é elemento que sustenta toda a cadeia seguinte.', ok: true,
      why: 'Correta. Declaração mal preenchida apaga o caso de todas as bases.' },
    { t: 'A declaração de óbito não comporta informação sobre relação com o trabalho.', ok: false,
      why: 'Errada. Há campo específico para essa informação.' },
    { t: 'A investigação é atribuição exclusiva da fiscalização do trabalho.', ok: false,
      why: 'Errada. Envolve articulação entre setores, com competências próprias de cada um.' },
    { t: 'Óbitos por doença ocupacional não são objeto de investigação, apenas os por acidente.', ok: false,
      why: 'Errada. Ambos são objeto de vigilância.' },
    { t: 'A investigação deve se concentrar na conduta do trabalhador falecido.', ok: false,
      why: 'Errada. O objeto é o processo de trabalho e as falhas de barreira que permitiram o evento.' }
  ],
  comentario: 'Óbito relacionado ao trabalho: notificação, análise do processo de trabalho e articulação intersetorial — com a declaração de óbito informando a relação com o trabalho, sem a qual o caso desaparece das estatísticas.',
  pegadinha: 'Investigar a conduta do falecido em vez do processo de trabalho encerra a apuração onde ela deveria começar.',
  refs: ['Portarias de vigilância de óbitos relacionados ao trabalho', 'SINAN', 'PNSTT'] },

{ id: 'q-1.9-080', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a qualidade e a completitude dos dados em sistemas de informação de agravos, é CORRETO afirmar:',
  alts: [
    { t: 'Duplicidade, campos em branco e inconsistência comprometem a análise e exigem depuração.', ok: true,
      why: 'Correta. Base não depurada descreve o erro de registro, não o fenômeno.' },
    { t: 'O volume de notificações recebidas é o principal indicador da qualidade do sistema de informação.', ok: false,
      why: 'Errada. Volume sem completitude e sem consistência não sustenta análise.' },
    { t: 'A qualidade importa, sendo a depuração da base etapa administrativa sem relação com a vigilância.', ok: false,
      why: 'Errada. É condição para que a informação oriente ação.' },
    { t: 'A qualidade importa, sem que registros duplicados interfiram nas taxas calculadas no período.', ok: false,
      why: 'Errada. Inflam numeradores e distorcem comparações entre territórios e períodos.' },
    { t: 'A qualidade importa, devendo a inconsistência entre variáveis ser corrigida na publicação anual.', ok: false,
      why: 'Errada. A crítica deve ser contínua, para que o dado sirva à ação no tempo certo.' }
  ],
  comentario: 'Base de vigilância exige crítica contínua: duplicidade infla taxa, campo em branco inviabiliza estratificação e inconsistência entre variáveis produz análise do erro. Depurar é vigilância, não burocracia.',
  pegadinha: 'Medir o sistema pelo número de notificações premia volume e ignora a qualidade que sustenta a análise.',
  refs: ['SINAN', 'Ministério da Saúde — avaliação de sistemas de informação'] },

{ id: 'q-1.10-080', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre programas de apoio ao trabalhador para cessação do tabagismo, é CORRETO afirmar:',
  alts: [
    { t: 'O ambiente é favorável e deve combinar apoio terapêutico com ambiente livre de fumo.', ok: true,
      why: 'Correta. Abordagem punitiva afasta justamente quem mais precisa de apoio.' },
    { t: 'O ambiente é favorável, bastando a proibição de fumar nas dependências como programa de cessação.', ok: false,
      why: 'Errada. Ambiente livre de fumo é complementar, não substitui o apoio terapêutico.' },
    { t: 'O ambiente é favorável, podendo a adesão ser exigida para manutenção de benefícios da empresa.', ok: false,
      why: 'Errada. Condicionar benefício converte apoio em coação.' },
    { t: 'O ambiente é favorável, sem vantagem desses programas sobre a busca individual de tratamento.', ok: false,
      why: 'Errada. Proximidade, apoio de pares e continuidade favorecem a adesão.' },
    { t: 'O ambiente é favorável, podendo a informação sobre a participação ser compartilhada com a chefia.', ok: false,
      why: 'Errada. É informação de saúde, protegida por sigilo.' }
  ],
  comentario: 'Cessação de tabagismo no trabalho: apoio terapêutico mais ambiente livre de fumo, sem punição, sem condicionar benefício e com sigilo sobre a participação. Proibir sem apoiar não é programa.',
  pegadinha: 'O componente punitivo afasta exatamente o trabalhador com maior dependência.',
  refs: ['INCA — programa de controle do tabagismo', 'OMS'] }

);
