/* Lote I — temas de peso médio da Seção 1 e correlatos. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-020', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de saúde ocupacional apresenta à diretoria indicadores de absenteísmo por doença, mas não consegue explicar por que o indicador subiu. Sobre o uso de indicadores em gestão de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Indicador isolado descreve, mas não explica: exige estratificar por setor, função, causa e tempo.', ok: true,
      why: 'Correta. Cruzar com exposição e organização é o que indica onde intervir.' },
    { t: 'Indicador isolado é suficiente, indicando a elevação do absenteísmo piora das condições de trabalho.', ok: false,
      why: 'Errada. Pode refletir campanha, sazonalidade ou melhora do acesso a atestado.' },
    { t: 'Indicador isolado é suficiente, sendo a queda do absenteísmo sempre resultado desejável na gestão.', ok: false,
      why: 'Errada. Pode indicar aumento do presenteísmo por pressão.' },
    { t: 'Indicador exige estratificação, não devendo ser apresentado à direção por conter dados clínicos.', ok: false,
      why: 'Errada. Apresenta-se de forma agregada, sem identificação individual.' },
    { t: 'Indicador exige estratificação, devendo a meta ser fixada antes de conhecer sua composição real.', ok: false,
      why: 'Errada. Meta sobre indicador não compreendido gera manipulação do número.' }
  ],
  comentario: 'Indicador só vira gestão depois de estratificado e cruzado com exposição e organização do trabalho. E atenção ao efeito espelho: queda do absenteísmo pode ser presenteísmo, e meta sobre número não compreendido tende a produzir subnotificação.',
  pegadinha: 'Ler queda de absenteísmo como sucesso é o erro de leitura mais frequente em relatório gerencial.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'ILO/OIT — gestão em SST'] },

{ id: 'q-1.4-021', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o dimensionamento e a atuação do serviço especializado em segurança e medicina do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'O dimensionamento segue o grau de risco e o número de trabalhadores, com atuação integrada', ok: true,
      why: 'Correta. A equipe é multiprofissional, não uma soma de atendimentos isolados.' },
    { t: 'O dimensionamento depende do número de trabalhadores do estabelecimento onde o serviço atua.', ok: false,
      why: 'Errada. O grau de risco da atividade também determina o dimensionamento.' },
    { t: 'O dimensionamento segue risco e porte, podendo a equipe ser substituída por serviço externo sem condição.', ok: false,
      why: 'Errada. Há requisitos próprios para as formas alternativas de organização.' },
    { t: 'O dimensionamento segue risco e porte, limitando-se o médico à realização dos exames ocupacionais.', ok: false,
      why: 'Errada. A atuação alcança vigilância, programas e ambiente.' },
    { t: 'O dimensionamento segue risco e porte, respondendo o serviço tecnicamente ao setor de pessoal.', ok: false,
      why: 'Errada. As decisões técnicas não se subordinam à área administrativa.' }
  ],
  comentario: 'Dois eixos no dimensionamento: grau de risco e número de trabalhadores. E o ponto conceitual: o serviço é multiprofissional e integrado, com autonomia técnica — o médico do trabalho não é apenas quem assina exame.',
  pegadinha: 'Reduzir o médico do trabalho ao exame ocupacional é a distorção que a prova cobra com frequência.',
  refs: ['NR-4', 'NR-1'] },

{ id: 'q-1.6-020', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a Política Nacional de Saúde do Trabalhador e da Trabalhadora, é CORRETO afirmar:',
  alts: [
    { t: 'Abrange todos os trabalhadores, com ou sem vínculo formal, inclusive informais e domésticos.', ok: true,
      why: 'Correta. É o que a distingue da lógica securitária, restrita ao segurado contribuinte.' },
    { t: 'Abrange os trabalhadores com vínculo formal registrado, base sobre a qual o sistema se organiza.', ok: false,
      why: 'Errada. O princípio é a universalidade, independentemente do vínculo.' },
    { t: 'Abrange todos os trabalhadores e substitui as normas regulamentadoras de segurança e saúde.', ok: false,
      why: 'Errada. São conjuntos normativos distintos e complementares.' },
    { t: 'Abrange todos os trabalhadores, sendo sua execução atribuição exclusiva do nível federal do sistema.', ok: false,
      why: 'Errada. É descentralizada, com competências das três esferas.' },
    { t: 'Abrange todos os trabalhadores, dispensando a participação deles na formulação e no controle.', ok: false,
      why: 'Errada. O controle social é diretriz expressa do campo.' }
  ],
  comentario: 'Universalidade é a chave: a política de saúde do trabalhador alcança o informal, o autônomo, a doméstica — quem a lógica securitária deixa de fora. Descentralizada nas três esferas e com controle social.',
  pegadinha: 'Restringir a política ao trabalhador formal reproduz exatamente o recorte que ela veio corrigir.',
  refs: ['Portaria GM/MS nº 1.823/2012 — PNSTT', 'Lei nº 8.080/1990'] },

{ id: 'q-1.6-021', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os Centros de Referência em Saúde do Trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'São retaguarda técnica da rede, com apoio matricial, investigação, capacitação e vigilância', ok: true,
      why: 'Correta. Não são porta de entrada substitutiva da atenção básica.' },
    { t: 'São unidades de referência cuja função principal é o atendimento clínico de todos os trabalhadores.', ok: false,
      why: 'Errada. São retaguarda técnica, não porta de entrada substitutiva.' },
    { t: 'São retaguarda técnica da rede e emitem os benefícios previdenciários por doença ocupacional.', ok: false,
      why: 'Errada. A concessão de benefícios é da previdência.' },
    { t: 'São retaguarda técnica, com atuação independente da vigilância sanitária e epidemiológica local.', ok: false,
      why: 'Errada. A articulação com as vigilâncias é constitutiva de sua função.' },
    { t: 'São retaguarda técnica da rede, não participando da notificação de agravos relacionados ao trabalho.', ok: false,
      why: 'Errada. Notificam e qualificam a notificação da rede.' }
  ],
  comentario: 'O centro de referência é retaguarda técnica: matricia a rede, investiga agravos, capacita e faz vigilância. Não emite benefício — isso é perícia previdenciária — nem substitui a atenção básica.',
  pegadinha: 'Descrevê-lo como ambulatório especializado para todos os trabalhadores inverte sua função na rede.',
  refs: ['RENAST — Portaria GM/MS nº 2.728/2009', 'PNSTT'] },

{ id: 'q-1.7-020', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre as competências do Sistema Único de Saúde em saúde do trabalhador previstas na Lei Orgânica da Saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Incluem avaliar o impacto das tecnologias, informar trabalhador e sindicato e fiscalizar condições.', ok: true,
      why: 'Correta. A participação na normatização também integra as competências.' },
    { t: 'Incluem avaliar tecnologias, sendo a fiscalização das condições competência exclusiva do órgão do trabalho.', ok: false,
      why: 'Errada. O sistema de saúde tem competência própria e concorrente.' },
    { t: 'Incluem informar sobre riscos, informação que deve ser prestada apenas ao empregador responsável.', ok: false,
      why: 'Errada. Trabalhador e sindicato são destinatários expressos.' },
    { t: 'Incluem informar e fiscalizar, não integrando a avaliação do impacto de novas tecnologias o campo.', ok: false,
      why: 'Errada. Consta expressamente entre as competências.' },
    { t: 'Incluem informar e fiscalizar, não podendo o sistema de saúde interditar ambiente de trabalho.', ok: false,
      why: 'Errada. A interdição sanitária é medida prevista.' }
  ],
  comentario: 'A Lei Orgânica dá ao sistema de saúde papel amplo: avaliar tecnologias, informar o trabalhador e o sindicato, participar da normatização e fiscalização, e interditar diante de risco iminente. Competência concorrente, não exclusiva do órgão do trabalho.',
  pegadinha: 'Restringir a informação ao empregador contraria dispositivo expresso que nomeia o trabalhador e o sindicato.',
  refs: ['Lei nº 8.080/1990 — art. 6º, §3º'] },

{ id: 'q-1.7-021', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atenção básica e a saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A ocupação deve integrar a anamnese na atenção básica, onde a maioria busca atendimento', ok: true,
      why: 'Correta. Não perguntar é a principal causa de invisibilidade do nexo.' },
    { t: 'A ocupação importa, devendo os casos suspeitos ser encaminhados sem registro na unidade básica.', ok: false,
      why: 'Errada. O registro e a notificação começam onde o caso é identificado.' },
    { t: 'A ocupação é dado administrativo, não tendo a atenção básica atribuição em saúde do trabalhador.', ok: false,
      why: 'Errada. É porta de entrada e território privilegiado de identificação.' },
    { t: 'A ocupação deve constar, sendo a investigação de nexo atribuição exclusiva de serviço especializado.', ok: false,
      why: 'Errada. Qualquer médico pode e deve suspeitar e notificar.' },
    { t: 'A ocupação deve constar, devendo trabalhadores informais ser encaminhados à rede privada de saúde.', ok: false,
      why: 'Errada. O atendimento no sistema público é universal.' }
  ],
  comentario: 'A pergunta "em que o senhor trabalha?" é o instrumento diagnóstico mais barato da saúde do trabalhador. Sem ela, o agravo ocupacional passa pela unidade básica como doença comum e desaparece das estatísticas.',
  pegadinha: 'Tratar nexo como assunto exclusivo de especialista adia a suspeita para depois da cronificação.',
  refs: ['PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.9-041', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a notificação compulsória de agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'É obrigatória diante da suspeita, sem depender de confirmação nem de nexo previdenciário.', ok: true,
      why: 'Correta. E independe do vínculo do trabalhador, inclusive informal.' },
    { t: 'É obrigatória após a confirmação diagnóstica e o reconhecimento do nexo pela perícia previdenciária.', ok: false,
      why: 'Errada. A notificação se faz por suspeita.' },
    { t: 'É obrigatória diante da suspeita e substitui a comunicação de acidente de trabalho devida.', ok: false,
      why: 'Errada. São documentos distintos, com finalidades próprias.' },
    { t: 'É obrigatória diante da suspeita, não sendo objeto de notificação os trabalhadores informais.', ok: false,
      why: 'Errada. A notificação independe do vínculo.' },
    { t: 'É obrigatória diante da suspeita, dependendo sua realização de autorização do empregador.', ok: false,
      why: 'Errada. É dever do profissional que identifica o caso.' }
  ],
  comentario: 'Notificação: por suspeita, sem esperar confirmação, sem depender de vínculo formal nem de autorização do empregador. E não substitui a comunicação de acidente — os dois instrumentos convivem.',
  pegadinha: 'Confundir notificação em saúde com comunicação de acidente faz o profissional emitir um e omitir o outro.',
  refs: ['Portaria de Consolidação nº 4/2017 — notificação compulsória', 'SINAN — fichas de agravos relacionados ao trabalho'] },

{ id: 'q-1.9-042', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a subnotificação de agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Produz subestimação sistemática e subdimensiona políticas e recursos destinados ao campo.', ok: true,
      why: 'Correta. Afeta desigualmente os grupos com menor proteção, ampliando a desigualdade.' },
    { t: 'Produz subestimação do problema, afetando uniformemente todos os grupos de trabalhadores do país.', ok: false,
      why: 'Errada. Atinge mais os informais e os de menor proteção.' },
    { t: 'Produz subestimação dos números, sem interferir no planejamento das políticas públicas do setor.', ok: false,
      why: 'Errada. O dimensionamento das políticas decorre desses dados.' },
    { t: 'Produz subestimação, sendo a fraude deliberada a principal causa da subnotificação observada.', ok: false,
      why: 'Errada. Desconhecimento, sobrecarga e receio pesam muito mais.' },
    { t: 'Produz subestimação, problema restrito ao sistema de saúde, sem reflexo na esfera previdenciária.', ok: false,
      why: 'Errada. Reflete no reconhecimento de direitos e no custeio acidentário.' }
  ],
  comentario: 'A subnotificação é seletiva: falta mais onde a proteção já falta. Suas causas principais não são fraude, mas não reconhecimento do nexo e desconhecimento do dever — as duas coisas que o médico do trabalho pode corrigir.',
  pegadinha: 'Supor uniformidade da subnotificação sugere que corrigi-la não mudaria o retrato — e mudaria, e desigualmente.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'SINAN'] },

{ id: 'q-1.10-020', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa lança programa de promoção da saúde com desafio de passos, palestra sobre alimentação e bonificação para quem reduzir o índice de massa corporal. Sobre esse desenho, é CORRETO afirmar:',
  alts: [
    { t: 'Desloca a responsabilidade ao indivíduo sem tocar em jornada, ritmo, oferta alimentar e pausas', ok: true,
      why: 'Correta. A bonificação por resultado corporal ainda introduz risco de discriminação.' },
    { t: 'O desenho é adequado, pois atua diretamente sobre fatores de risco individuais modificáveis.', ok: false,
      why: 'Errada. Ignora os determinantes organizacionais do problema.' },
    { t: 'Desloca a responsabilidade, sendo a bonificação por medida corporal instrumento neutro de incentivo.', ok: false,
      why: 'Errada. Introduz pressão e risco de discriminação.' },
    { t: 'Desloca a responsabilidade, e programas de promoção não devem considerar a organização do trabalho.', ok: false,
      why: 'Errada. É justamente onde estão os determinantes mais fortes.' },
    { t: 'Desloca a responsabilidade, eliminando a adesão voluntária qualquer questionamento ético ao programa.', ok: false,
      why: 'Errada. Voluntariedade não corrige o desenho nem o uso dos dados.' }
  ],
  comentario: 'Promoção da saúde no trabalho não pode parar no comportamento individual: se a jornada impede o sono e a cantina só oferece fritura, cobrar passos é transferir a conta. Bonificação por medida corporal soma pressão e risco de discriminação.',
  pegadinha: '"Fator de risco modificável" soa técnico e esconde que o programa não modificou nada do ambiente.',
  refs: ['OMS — ambientes de trabalho saudáveis', 'PNSTT'] },

{ id: 'q-1.10-021', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a confidencialidade em programas de promoção da saúde conduzidos no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Dados individuais não vão ao empregador, que recebe apenas informação agregada do programa', ok: true,
      why: 'Correta. A participação não pode condicionar desempenho, promoção ou permanência.' },
    { t: 'O empregador que custeia o programa tem direito de acesso aos resultados individuais dos aderentes.', ok: false,
      why: 'Errada. Custeio não confere acesso a dado de saúde individual.' },
    { t: 'Dados individuais não vão ao empregador, autorizando o consentimento da admissão qualquer uso posterior.', ok: false,
      why: 'Errada. Consentimento genérico não legitima usos futuros indeterminados.' },
    { t: 'Dados individuais não vão ao empregador, podendo os agregados ser divulgados por setor pequeno.', ok: false,
      why: 'Errada. Em grupos pequenos o agregado reidentifica as pessoas.' },
    { t: 'Dados individuais não vão ao empregador, podendo a participação ser exigida para benefícios.', ok: false,
      why: 'Errada. Condicionar benefício converte adesão em coação.' }
  ],
  comentario: 'Regra de ouro: empregador recebe agregado, nunca individual. E cuidado com o agregado de setor pequeno, que reidentifica na prática. Participação condicionada a benefício não é voluntária.',
  pegadinha: 'O agregado por setor parece anônimo e deixa de ser quando o setor tem três pessoas.',
  refs: ['Código de Ética Médica', 'LGPD — dados sensíveis de saúde', 'Resoluções do CFM sobre medicina do trabalho'] },

{ id: 'q-2.7-020', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a diferença entre avaliar exposição pelas normas de higiene ocupacional de referência técnica e pelos anexos da norma regulamentadora de insalubridade, é CORRETO afirmar:',
  alts: [
    { t: 'As normas técnicas visam à prevenção; os anexos da insalubridade, à caracterização de direito.', ok: true,
      why: 'Correta. Pode haver divergência entre o resultado técnico e o enquadramento legal.' },
    { t: 'As duas abordagens usam os mesmos critérios e produzem sempre o mesmo resultado de avaliação.', ok: false,
      why: 'Errada. Finalidades distintas produzem critérios e resultados distintos.' },
    { t: 'As finalidades diferem, não tendo valor a avaliação técnica quando diverge do enquadramento legal.', ok: false,
      why: 'Errada. A avaliação preventiva mantém seu valor técnico próprio.' },
    { t: 'As finalidades diferem, indicando a não caracterização legal que a exposição está controlada.', ok: false,
      why: 'Errada. Não caracterizar insalubridade não significa exposição controlada.' },
    { t: 'As finalidades diferem, sendo vedada à empresa a adoção de critério mais protetor que o legal.', ok: false,
      why: 'Errada. É permitida e tecnicamente recomendável.' }
  ],
  comentario: 'Duas lógicas: a técnica busca proteger; a legal busca caracterizar direito. Elas divergem, e a divergência não invalida a técnica. Ausência de insalubridade caracterizada nunca equivale a exposição segura.',
  pegadinha: 'Ler "não caracterizou insalubridade" como "ambiente seguro" encerra a prevenção no ponto errado.',
  refs: ['NHO — Fundacentro', 'NR-15', 'ACGIH — TLVs'] },

{ id: 'q-4.10-020', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a vacinação de trabalhadores no âmbito do serviço de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A indicação segue o risco ocupacional, com registro, custo do empregador e recusa registrada.', ok: true,
      why: 'Correta. A recusa esclarecida não exclui automaticamente o trabalhador da função.' },
    { t: 'A indicação segue o risco, autorizando a recusa de vacinação a imediata dispensa do trabalhador.', ok: false,
      why: 'Errada. A recusa se registra e se reaborda, sem punição automática.' },
    { t: 'A indicação segue o risco, podendo o custo da vacinação ser dividido com o próprio trabalhador.', ok: false,
      why: 'Errada. É oferecida sem custo para o trabalhador.' },
    { t: 'A indicação segue o risco, sendo desnecessária a verificação de resposta sorológica em qualquer caso.', ok: false,
      why: 'Errada. É indicada quando altera a conduta pós-exposição.' },
    { t: 'A indicação segue o risco, sendo o esquema vacinal idêntico para todas as funções da empresa.', ok: false,
      why: 'Errada. É dirigido ao risco específico de cada função.' }
  ],
  comentario: 'Vacinação ocupacional: indicada por risco de função, custeada pelo empregador, com verificação de resposta quando aplicável, e recusa esclarecida e registrada — não dispensa nem exclusão automática.',
  pegadinha: 'Tratar a recusa como causa de desligamento converte medida de proteção em instrumento disciplinar.',
  refs: ['NR-7', 'NR-32', 'Programa Nacional de Imunizações'] },

{ id: 'q-5.3-041', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador com hérnia discal degenerativa prévia desenvolve quadro incapacitante após dois anos em função com levantamento repetitivo de cargas. Sobre a análise do caso, é CORRETO afirmar:',
  alts: [
    { t: 'A preexistência não afasta o nexo: contribuindo o trabalho, configura-se concausa.', ok: true,
      why: 'Correta. As consequências são as mesmas do nexo por causa única.' },
    { t: 'A preexistência da degeneração discal documentada afasta qualquer nexo com a atividade exercida.', ok: false,
      why: 'Errada. O agravamento é hipótese expressa de concausa.' },
    { t: 'A preexistência não afasta o nexo, sendo os efeitos legais proporcionalmente reduzidos na concausa.', ok: false,
      why: 'Errada. Não há previsão de fracionamento dos efeitos.' },
    { t: 'A preexistência não afasta o nexo, aplicando-se a concausa só se o trabalho contribuiu majoritariamente.', ok: false,
      why: 'Errada. Contribuição relevante basta, sem exigência de predominância.' },
    { t: 'A preexistência não afasta o nexo, decidindo a questão o caráter degenerativo do achado de imagem.', ok: false,
      why: 'Errada. Achados degenerativos são prevalentes e não decidem o nexo.' }
  ],
  comentario: 'Concausa: o trabalho contribuiu, ainda que não sozinho e ainda que não majoritariamente. Efeitos integrais, sem rateio. E o achado degenerativo de imagem não resolve nada — está presente em boa parte da população sem sintoma.',
  pegadinha: 'A ideia de "reduzir proporcionalmente" na concausa é atraente e não tem previsão legal.',
  refs: ['Lei nº 8.213/1991 — art. 21, I', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-5.3-042', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a distinção entre concausa preexistente, concomitante e superveniente, é CORRETO afirmar:',
  alts: [
    { t: 'Refere-se ao momento em que o fator concorrente atua: antes, junto ou depois do evento', ok: true,
      why: 'Correta. As três podem configurar relação com o trabalho, inclusive a superveniente.' },
    { t: 'Refere-se ao momento de atuação, sendo reconhecida apenas a concausa concomitante ao evento.', ok: false,
      why: 'Errada. As três modalidades são reconhecidas.' },
    { t: 'Refere-se ao momento, rompendo a concausa superveniente o nexo com o evento original ocorrido.', ok: false,
      why: 'Errada. A complicação do tratamento segue vinculada ao evento.' },
    { t: 'Refere-se ao momento, exigindo a preexistente que o trabalhador tenha ocultado a condição na admissão.', ok: false,
      why: 'Errada. O reconhecimento independe do histórico de declaração.' },
    { t: 'Refere-se ao momento de atuação, alterando essa classificação os efeitos legais do reconhecimento.', ok: false,
      why: 'Errada. Os efeitos são os mesmos nas três modalidades.' }
  ],
  comentario: 'Três momentos, mesmos efeitos. A superveniente é a que mais escapa: infecção hospitalar durante o tratamento da fratura do acidente segue ligada ao acidente.',
  pegadinha: 'Supor que a complicação posterior "quebra" o nexo desfaz justamente a modalidade superveniente.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Decreto nº 3.048/1999'] }

);
