/* Lote AI — 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 2.5, 2.8, 4.7, 4.9, 5.3, 5.6, 6.1, 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-090', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a gestão do absenteísmo por doença e o chamado presenteísmo, é CORRETO afirmar:',
  alts: [
    { t: 'O presenteísmo — trabalhar doente, com desempenho reduzido — pode superar o absenteísmo em impacto e é favorecido por políticas punitivas de faltas, metas individuais e insegurança no emprego, de modo que reduzir o absenteísmo por pressão pode piorar o resultado global.', ok: true,
      why: 'Correta. A pressão desloca o problema em vez de resolvê-lo.' },
    { t: 'O presenteísmo é fenômeno sem repercussão mensurável.', ok: false,
      why: 'Errada. Há instrumentos de mensuração e impacto documentado.' },
    { t: 'Políticas de premiação por assiduidade reduzem o presenteísmo.', ok: false,
      why: 'Errada. Tendem a aumentá-lo, pois penalizam quem se afasta para tratar.' },
    { t: 'A redução do absenteísmo é sempre indicador de melhora da saúde da força de trabalho.', ok: false,
      why: 'Errada. Pode refletir aumento do presenteísmo.' },
    { t: 'O presenteísmo não aumenta o risco de acidentes.', ok: false,
      why: 'Errada. Trabalhador doente, medicado ou com dor tem desempenho e atenção reduzidos.' }
  ],
  comentario: 'Presenteísmo pode custar mais que absenteísmo e é alimentado por punição a faltas, prêmio por assiduidade e insegurança. Queda do absenteísmo sob pressão costuma ser deslocamento, não melhora.',
  pegadinha: 'O prêmio por assiduidade parece incentivo saudável e empurra o trabalhador doente para dentro da fábrica.',
  refs: ['OIT — presenteísmo e produtividade', 'Literatura de gestão em saúde ocupacional'] },

{ id: 'q-1.5-090', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a política de segurança e saúde de uma organização, é CORRETO afirmar:',
  alts: [
    { t: 'Ela deve declarar compromissos verificáveis, ser comunicada e compreendida em todos os níveis, e sua credibilidade depende da coerência entre o declarado e as decisões concretas de produção — declaração desmentida pela prática corrói a cultura de segurança.', ok: true,
      why: 'Correta. Uma decisão de produção contra a política ensina mais que qualquer cartaz.' },
    { t: 'A política tem valor simbólico e não precisa de compromissos verificáveis.', ok: false,
      why: 'Errada. Compromissos verificáveis são o que permite cobrar e auditar.' },
    { t: 'Basta que a política esteja documentada e disponível para consulta.', ok: false,
      why: 'Errada. Precisa ser comunicada e compreendida pelos trabalhadores.' },
    { t: 'A coerência entre política e decisões de produção não afeta a cultura de segurança.', ok: false,
      why: 'Errada. É o principal determinante da credibilidade do sistema.' },
    { t: 'A política deve ser elaborada exclusivamente pela área técnica de segurança.', ok: false,
      why: 'Errada. Exige compromisso da alta direção e consulta aos trabalhadores.' }
  ],
  comentario: 'Política de segurança vale pelo que se decide quando ela conflita com o prazo de produção. Compromissos verificáveis, comunicação efetiva e coerência prática — o resto é cartaz.',
  pegadinha: 'Documentar e disponibilizar não é comunicar, e comunicar não é ser coerente na hora da decisão.',
  refs: ['ISO 45001', 'NR-1'] },

{ id: 'q-1.6-090', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as ações de saúde do trabalhador dirigidas ao trabalho informal, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem estratégias específicas de aproximação, já que esses trabalhadores não são alcançados por serviços de medicina do trabalho de empresas — o que torna a atenção básica e a busca ativa territorial as principais portas de acesso.', ok: true,
      why: 'Correta. Sem empresa, não há serviço ocupacional; sobra o território.' },
    { t: 'Trabalhadores informais são alcançados pelos programas ocupacionais das empresas contratantes.', ok: false,
      why: 'Errada. Justamente por não terem vínculo, ficam fora desses programas.' },
    { t: 'A informalidade reduz a exposição a riscos ocupacionais.', ok: false,
      why: 'Errada. Costuma associar-se a maior exposição e menor proteção.' },
    { t: 'A atenção básica não tem papel relevante nesse grupo.', ok: false,
      why: 'Errada. É a principal porta de entrada para esses trabalhadores.' },
    { t: 'A ausência de vínculo formal impede a notificação de agravos.', ok: false,
      why: 'Errada. A notificação independe de vínculo.' }
  ],
  comentario: 'Informal não tem serviço de medicina do trabalho — tem unidade básica e território. Por isso a busca ativa e a pergunta sobre ocupação na atenção básica são a estratégia central para esse grupo.',
  pegadinha: 'Supor que a contratante cobre o informal desenha uma proteção que não existe na prática.',
  refs: ['PNSTT', 'Política Nacional de Atenção Básica'] },

{ id: 'q-1.7-090', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a regionalização e a hierarquização aplicadas às ações de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A organização em rede regionalizada permite que ações de maior complexidade técnica sejam ofertadas em base regional, com apoio às unidades locais — o que é especialmente relevante em municípios pequenos, sem estrutura própria de vigilância.', ok: true,
      why: 'Correta. Município pequeno não sustenta estrutura própria; a base regional resolve.' },
    { t: 'Cada município deve dispor de estrutura completa e autônoma de vigilância em saúde do trabalhador.', ok: false,
      why: 'Errada. A regionalização existe justamente para viabilizar o que o município isolado não sustenta.' },
    { t: 'A hierarquização implica que a atenção básica não participe das ações.', ok: false,
      why: 'Errada. Ela é porta de entrada e participa ativamente.' },
    { t: 'A regionalização não se aplica às ações de vigilância.', ok: false,
      why: 'Errada. Aplica-se e é determinante de sua viabilidade.' },
    { t: 'Ações regionais dispensam pactuação entre os gestores envolvidos.', ok: false,
      why: 'Errada. A pactuação é o instrumento que viabiliza a organização regional.' }
  ],
  comentario: 'Regionalização viabiliza o que o município pequeno não sustenta sozinho, com pactuação entre gestores — e sem tirar a atenção básica do processo, que segue como porta de entrada.',
  pegadinha: 'Exigir estrutura completa por município condena a vigilância a existir só nas capitais.',
  refs: ['Lei nº 8.080/1990', 'Decreto nº 7.508/2011', 'RENAST'] },

{ id: 'q-1.8-090', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o uso de indicadores para priorizar ações de vigilância em saúde do trabalhador em um território, é CORRETO afirmar:',
  alts: [
    { t: 'A priorização combina magnitude dos agravos, gravidade, número de expostos e viabilidade de intervenção — e deve considerar que setores com poucos registros podem representar não ausência de risco, mas ausência de vigilância prévia.', ok: true,
      why: 'Correta. Silêncio na base pode ser cegueira, não ausência de problema.' },
    { t: 'Setores sem registros de agravos podem ser desconsiderados na priorização.', ok: false,
      why: 'Errada. A ausência de registro pode indicar ausência de vigilância anterior.' },
    { t: 'A magnitude dos agravos é o único critério relevante.', ok: false,
      why: 'Errada. Gravidade, número de expostos e viabilidade também compõem a decisão.' },
    { t: 'A viabilidade de intervenção não deve influenciar a priorização.', ok: false,
      why: 'Errada. Priorizar o inviável consome recurso sem produzir mudança.' },
    { t: 'A priorização deve ser feita sem participação dos trabalhadores e suas entidades.', ok: false,
      why: 'Errada. Elas trazem informação sobre setores e riscos invisíveis nas bases.' }
  ],
  comentario: 'Priorizar por magnitude, gravidade, expostos e viabilidade — lembrando que setor sem registro pode ser setor nunca olhado. E sindicatos apontam o que a base não mostra.',
  pegadinha: 'Priorizar apenas onde já há registro perpetua a invisibilidade dos setores nunca fiscalizados.',
  refs: ['PNSTT', 'Ministério da Saúde — vigilância em saúde do trabalhador'] },

{ id: 'q-1.9-090', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os agravos relacionados ao trabalho de notificação compulsória, é CORRETO afirmar:',
  alts: [
    { t: 'A lista inclui acidente de trabalho grave, fatal e com menores, acidente com material biológico, intoxicação exógena, perda auditiva induzida por ruído, transtornos mentais, dermatoses, pneumoconioses, câncer e lesões por esforços repetitivos relacionados ao trabalho.', ok: true,
      why: 'Correta. A lista é ampla e alcança agravos crônicos, não apenas eventos agudos.' },
    { t: 'Apenas acidentes de trabalho são objeto de notificação compulsória.', ok: false,
      why: 'Errada. Doenças crônicas relacionadas ao trabalho também integram a lista.' },
    { t: 'Transtornos mentais relacionados ao trabalho não são notificáveis.', ok: false,
      why: 'Errada. Integram expressamente a lista.' },
    { t: 'Câncer relacionado ao trabalho não é objeto de notificação.', ok: false,
      why: 'Errada. É agravo de notificação compulsória.' },
    { t: 'A notificação de perda auditiva induzida por ruído só se aplica a casos com incapacidade.', ok: false,
      why: 'Errada. A notificação decorre do agravo identificado, não do grau de incapacidade.' }
  ],
  comentario: 'A lista vai muito além do acidente: perda auditiva, transtornos mentais, dermatoses, pneumoconioses, câncer, lesões por esforços repetitivos, intoxicações. Os crônicos são justamente os menos notificados.',
  pegadinha: 'Reduzir a notificação a acidentes deixa fora todos os agravos de instalação lenta.',
  refs: ['Portaria de Consolidação nº 4/2017', 'SINAN'] },

{ id: 'q-1.10-090', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a promoção da atividade física no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Programas de ginástica no local podem trazer benefícios, mas não substituem a correção de fatores ergonômicos e organizacionais — e oferecer pausa para ginástica sem reduzir o ritmo transfere ao trabalhador a tarefa de compensar uma sobrecarga que permanece.', ok: true,
      why: 'Correta. Ginástica não corrige posto nem ritmo.' },
    { t: 'A ginástica laboral substitui as adequações ergonômicas do posto de trabalho.', ok: false,
      why: 'Errada. São medidas de naturezas distintas e não substitutivas.' },
    { t: 'A participação pode ser tornada obrigatória sem implicações.', ok: false,
      why: 'Errada. Obrigatoriedade em programa de promoção descaracteriza a adesão e gera constrangimento.' },
    { t: 'Programas de atividade física não requerem avaliação prévia de condições individuais.', ok: false,
      why: 'Errada. Condições clínicas específicas exigem orientação individualizada.' },
    { t: 'A pausa para ginástica equivale à pausa para recuperação prevista por exigência da atividade.', ok: false,
      why: 'Errada. São finalidades distintas; a pausa de recuperação decorre da exigência da tarefa.' }
  ],
  comentario: 'Ginástica laboral tem lugar, mas não corrige posto nem ritmo — e a pausa de ginástica não substitui a pausa de recuperação que a atividade exige. Sem obrigatoriedade e com atenção a condições individuais.',
  pegadinha: 'Contabilizar a ginástica como pausa de recuperação elimina o descanso que a tarefa exigia.',
  refs: ['NR-17', 'OMS — ambientes de trabalho saudáveis'] },

{ id: 'q-2.5-080', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a antecipação de riscos em projetos de novas instalações e processos, é CORRETO afirmar:',
  alts: [
    { t: 'Intervir na fase de projeto é a oportunidade de maior eficácia e menor custo, permitindo eliminar o perigo antes que ele exista — enquanto correções após a instalação enfrentam limitações físicas e resistência econômica muito maiores.', ok: true,
      why: 'Correta. O que se resolve no desenho não precisa ser gerenciado depois.' },
    { t: 'A avaliação de riscos deve começar apenas após o início da operação.', ok: false,
      why: 'Errada. A antecipação na fase de projeto é a etapa mais eficaz.' },
    { t: 'Correções após a instalação têm o mesmo custo e eficácia das feitas em projeto.', ok: false,
      why: 'Errada. São mais caras, mais limitadas e frequentemente parciais.' },
    { t: 'A participação de profissionais de saúde e segurança na fase de projeto é dispensável.', ok: false,
      why: 'Errada. É onde sua contribuição tem maior alcance.' },
    { t: 'A antecipação se aplica apenas a riscos químicos.', ok: false,
      why: 'Errada. Aplica-se a todos os riscos, inclusive ergonômicos e psicossociais decorrentes do desenho do processo.' }
  ],
  comentario: 'Antecipação é a etapa de maior retorno: elimina-se o perigo antes de ele existir, no papel, onde mudar é barato. Depois de instalado, a mesma correção enfrenta parede, orçamento e prazo.',
  pegadinha: 'Chamar a equipe de saúde e segurança só depois da inauguração reduz a atuação a remendo.',
  refs: ['NR-1', 'AIHA', 'Prevenção pelo desenho — literatura de referência'] },

{ id: 'q-2.8-080', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a higienização, a guarda e a manutenção de respiradores, é CORRETO afirmar:',
  alts: [
    { t: 'Respiradores reutilizáveis exigem higienização e inspeção periódicas, guarda protegida de contaminação, umidade e deformação, e substituição de componentes conforme critério definido — guarda inadequada compromete a vedação e o desempenho.', ok: true,
      why: 'Correta. Respirador guardado dobrado dentro do armário perde vedação.' },
    { t: 'A guarda do respirador não influencia seu desempenho.', ok: false,
      why: 'Errada. Deformação e contaminação comprometem vedação e proteção.' },
    { t: 'A higienização pode ser feita com qualquer produto disponível.', ok: false,
      why: 'Errada. Produtos inadequados degradam o material e a vedação.' },
    { t: 'A inspeção do equipamento cabe exclusivamente ao fornecedor.', ok: false,
      why: 'Errada. A inspeção pelo usuário antes do uso é parte do programa.' },
    { t: 'Componentes danificados podem ser mantidos até a próxima troca programada.', ok: false,
      why: 'Errada. Componente danificado exige substituição imediata.' }
  ],
  comentario: 'Respirador reutilizável: higienizar com produto adequado, inspecionar antes de cada uso, guardar sem deformar nem contaminar e trocar componente danificado na hora — não no próximo ciclo.',
  pegadinha: 'Guardar o respirador amassado no armário anula o ensaio de vedação que foi feito com ele novo.',
  refs: ['NR-6', 'Programa de Proteção Respiratória — Fundacentro'] },

{ id: 'q-4.7-100', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a abordagem inicial do trabalhador em sofrimento psíquico identificado no serviço ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'A conduta envolve acolhimento, avaliação do risco imediato, encaminhamento com continuidade garantida e avaliação da contribuição do contexto de trabalho — evitando tanto a banalização do sofrimento quanto o encaminhamento sem seguimento.', ok: true,
      why: 'Correta. Encaminhar sem garantir continuidade equivale a não encaminhar.' },
    { t: 'A conduta se esgota no encaminhamento a serviço externo.', ok: false,
      why: 'Errada. Sem continuidade garantida, o encaminhamento se perde.' },
    { t: 'A avaliação de risco imediato é dispensável quando não há relato espontâneo.', ok: false,
      why: 'Errada. A avaliação deve ser ativa, pois o relato espontâneo é a exceção.' },
    { t: 'A contribuição do contexto de trabalho não integra a avaliação inicial.', ok: false,
      why: 'Errada. É o que diferencia a abordagem ocupacional da assistencial comum.' },
    { t: 'Perguntar sobre ideação suicida aumenta o risco do trabalhador.', ok: false,
      why: 'Errada. Perguntar diretamente não induz o comportamento e permite intervir.' }
  ],
  comentario: 'Acolher, avaliar ativamente o risco, encaminhar com continuidade e olhar o contexto de trabalho. E perguntar sobre ideação não induz nada — é o que permite agir a tempo.',
  pegadinha: 'O receio de perguntar sobre ideação suicida é infundado e deixa o risco sem avaliação.',
  refs: ['Ministério da Saúde — prevenção do suicídio', 'Código de Ética Médica'] },

{ id: 'q-4.9-090', tema: '4.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a tuberculose em trabalhadores fora da área da saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Ambientes de trabalho fechados, com ventilação inadequada e aglomeração, favorecem a transmissão em qualquer setor — e o caso identificado exige investigação de contatos entre colegas, e não apenas no domicílio.', ok: true,
      why: 'Correta. Investigação de contato costuma parar na família e ignorar o turno inteiro.' },
    { t: 'A transmissão ocupacional de tuberculose se restringe a serviços de saúde.', ok: false,
      why: 'Errada. Qualquer ambiente fechado com aglomeração favorece a transmissão.' },
    { t: 'A investigação de contatos deve se limitar ao domicílio do caso.', ok: false,
      why: 'Errada. Colegas com convívio prolongado são contatos a investigar.' },
    { t: 'A ventilação do ambiente não influencia a transmissão.', ok: false,
      why: 'Errada. É um dos principais determinantes.' },
    { t: 'Trabalhadores em situação de maior vulnerabilidade social não requerem atenção diferenciada.', ok: false,
      why: 'Errada. Concentram maior incidência e maior dificuldade de adesão ao tratamento.' }
  ],
  comentario: 'Tuberculose não é só risco de hospital: ambiente fechado, mal ventilado e com aglomeração transmite em qualquer setor. Caso identificado pede investigação de contatos no trabalho, não só em casa.',
  pegadinha: 'Investigar contatos apenas no domicílio deixa o turno inteiro sem rastreamento.',
  refs: ['Ministério da Saúde — controle da tuberculose', 'NR-24'] },

{ id: 'q-5.3-090', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausa e a quantificação da contribuição do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A legislação não estabelece percentuais de contribuição para fins de reconhecimento, de modo que a análise é qualitativa quanto à existência da contribuição — ainda que a discussão de proporção possa aparecer na esfera indenizatória civil.', ok: true,
      why: 'Correta. Reconhecimento previdenciário é binário; proporcionalidade é discussão de outra esfera.' },
    { t: 'A legislação previdenciária estabelece percentuais mínimos de contribuição do trabalho.', ok: false,
      why: 'Errada. Não há previsão de percentuais para o reconhecimento.' },
    { t: 'Reconhecida a concausa, o benefício é pago proporcionalmente à contribuição do trabalho.', ok: false,
      why: 'Errada. O benefício não é rateado por proporção de causa.' },
    { t: 'A discussão de proporcionalidade não aparece em nenhuma esfera.', ok: false,
      why: 'Errada. Pode ser considerada na fixação de indenização civil.' },
    { t: 'A análise da concausa é quantitativa e exige mensuração da contribuição.', ok: false,
      why: 'Errada. É qualitativa quanto à existência da contribuição.' }
  ],
  comentario: 'Para o reconhecimento previdenciário, a pergunta é se o trabalho contribuiu — não quanto. Percentual não existe ali; proporcionalidade pode aparecer na indenização civil, que é outra discussão.',
  pegadinha: 'Misturar as duas esferas leva a exigir percentual onde a lei só pergunta se houve contribuição.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Código Civil'] },

{ id: 'q-5.6-090', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a estabilidade do trabalhador reabilitado e a reserva de vagas, é CORRETO afirmar:',
  alts: [
    { t: 'A dispensa de trabalhador reabilitado ou com deficiência, quando contratado na reserva legal e por prazo indeterminado, condiciona-se à contratação de substituto em condição semelhante — regra que protege o percentual e não apenas o indivíduo.', ok: true,
      why: 'Correta. A proteção é do preenchimento da reserva, mantendo o número.' },
    { t: 'A regra protege apenas o trabalhador individualmente considerado.', ok: false,
      why: 'Errada. Protege a manutenção do percentual de vagas reservadas.' },
    { t: 'Reabilitados não são alcançados pela reserva legal de vagas.', ok: false,
      why: 'Errada. São expressamente alcançados.' },
    { t: 'A regra se aplica também a contratos por prazo determinado de curta duração.', ok: false,
      why: 'Errada. A condição legal se refere à dispensa em contrato por prazo indeterminado.' },
    { t: 'A contratação de substituto pode se dar em função de menor complexidade sem qualquer restrição.', ok: false,
      why: 'Errada. A exigência é de condição semelhante.' }
  ],
  comentario: 'A regra da substituição protege o percentual: dispensar sem repor esvazia a reserva. Alcança reabilitados, refere-se ao contrato por prazo indeterminado e exige substituto em condição semelhante.',
  pegadinha: 'Ler a regra como proteção individual perde a razão de ser dela, que é manter o número de vagas ocupadas.',
  refs: ['Lei nº 8.213/1991 — art. 93, §1º'] },

{ id: 'q-6.1-100', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a guarda e a validade do atestado de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Uma via é entregue ao trabalhador e outra fica arquivada, e o documento registra os riscos avaliados, os exames realizados e a conclusão — sendo o registro que permite, anos depois, reconstituir a que riscos o trabalhador esteve exposto e o que foi avaliado.', ok: true,
      why: 'Correta. É documento de memória da exposição, não apenas de liberação para o trabalho.' },
    { t: 'A entrega de via ao trabalhador é facultativa.', ok: false,
      why: 'Errada. É exigência normativa.' },
    { t: 'O documento não precisa indicar os riscos ocupacionais avaliados.', ok: false,
      why: 'Errada. Os riscos avaliados integram seu conteúdo obrigatório.' },
    { t: 'Sua guarda pode ser encerrada com o desligamento do trabalhador.', ok: false,
      why: 'Errada. Os prazos de guarda são prolongados, pela latência de vários agravos.' },
    { t: 'A conclusão pode ser omitida quando o trabalhador é considerado apto.', ok: false,
      why: 'Errada. A conclusão é elemento essencial do documento.' }
  ],
  comentario: 'O atestado registra riscos avaliados, exames feitos e conclusão, com via ao trabalhador e guarda prolongada. É a memória da exposição — e é por isso que a guarda não termina com o vínculo.',
  pegadinha: 'Tratar o documento como liberação para trabalhar ignora sua função de registro histórico da exposição.',
  refs: ['NR-7'] },

{ id: 'q-6.4-100', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a queimadura elétrica no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A lesão externa pode subestimar gravemente o dano profundo, com necrose muscular, rabdomiólise e comprometimento renal — e a avaliação deve incluir monitorização cardíaca, pois arritmias podem ocorrer mesmo com lesão cutânea aparentemente pequena.', ok: true,
      why: 'Correta. A corrente lesa o trajeto interno; a pele mostra apenas as portas de entrada e saída.' },
    { t: 'A extensão da lesão cutânea estima adequadamente a gravidade do caso.', ok: false,
      why: 'Errada. O dano profundo ao longo do trajeto da corrente costuma ser muito maior.' },
    { t: 'Não há indicação de monitorização cardíaca em queimadura elétrica com lesão pequena.', ok: false,
      why: 'Errada. Arritmias podem ocorrer independentemente do tamanho da lesão cutânea.' },
    { t: 'A rabdomiólise não é complicação esperada nesses casos.', ok: false,
      why: 'Errada. É complicação clássica, com risco de lesão renal aguda.' },
    { t: 'A retirada da vítima do contato pode ser feita diretamente com as mãos.', ok: false,
      why: 'Errada. É preciso desenergizar ou usar material isolante, sob risco de nova vítima.' }
  ],
  comentario: 'Queimadura elétrica: a pele engana. O dano segue o trajeto da corrente, com necrose muscular, rabdomiólise e risco renal, e a arritmia não pede lesão grande. E ninguém toca na vítima antes de desenergizar.',
  pegadinha: 'Estimar gravidade pela lesão cutânea subestima o caso justamente quando ele é mais grave.',
  refs: ['NR-10', 'Protocolos de atendimento a queimaduras elétricas'] }

);
