/* Lote D — seção 1 (1.1, 1.2, 1.4, 1.5, 1.6, 1.7, 1.9, 1.10). AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.1-039', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa de grau de risco elevado com 900 empregados pergunta ao médico do trabalho qual a diferença entre contratar um serviço externo de medicina ocupacional e constituir serviço especializado próprio. A orientação CORRETA é:',
  alts: [
    { t: 'O serviço especializado é obrigação dimensionada por grau de risco e número de empregados, com profissionais vinculados ao estabelecimento e dedicados às atividades de segurança e saúde — o que difere da contratação de clínica para realizar exames, que não substitui a estrutura exigida.', ok: true,
      why: 'Correta. Uma coisa é executar exames; outra é manter a estrutura técnica exigida, com profissionais dedicados às atividades de prevenção no estabelecimento.' },
    { t: 'A contratação de clínica externa substitui integralmente o serviço especializado.', ok: false,
      why: 'Errada. São coisas distintas, com finalidades e exigências próprias.' },
    { t: 'O serviço especializado é facultativo em qualquer porte de empresa.', ok: false,
      why: 'Errada. É obrigatório conforme o dimensionamento previsto.' },
    { t: 'Os profissionais do serviço especializado podem acumular outras funções na empresa sem restrição.', ok: false,
      why: 'Errada. Espera-se dedicação às atividades de segurança e saúde, com restrições ao desvio de função.' },
    { t: 'O médico do trabalho do serviço especializado responde hierarquicamente ao setor de produção.', ok: false,
      why: 'Errada. A subordinação hierárquica não pode comprometer a autonomia técnica das decisões de saúde.' }
  ],
  comentario: 'Executar exames não é ter serviço especializado. A estrutura interna existe para atuar sobre o ambiente, com profissionais dedicados — e a autonomia técnica do médico não se subordina à produção.',
  pegadinha: 'Confundir contrato de clínica com cumprimento da obrigação de serviço especializado é o erro mais comum das empresas de médio porte.',
  refs: ['NR-4', 'Código de Ética Médica'] },

{ id: 'q-1.1-040', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o campo de atuação do médico do trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Ele atua na prevenção, no reconhecimento e no controle dos agravos relacionados ao trabalho, na avaliação de aptidão, na perícia e na gestão de programas — e sua função assistencial curativa, quando existe, não se confunde com a de médico assistente do trabalhador.', ok: true,
      why: 'Correta. O campo é predominantemente preventivo e de avaliação, e a separação em relação ao papel assistencial é o que preserva a confiança e a autonomia.' },
    { t: 'A atuação se restringe à realização de exames admissionais e demissionais.', ok: false,
      why: 'Errada. É a redução mais empobrecedora da especialidade.' },
    { t: 'O médico do trabalho é o médico assistente de todos os empregados da empresa.', ok: false,
      why: 'Errada. Assumir a assistência longitudinal confunde papéis e compromete a relação de confiança.' },
    { t: 'A atuação em perícia é vedada ao médico do trabalho.', ok: false,
      why: 'Errada. A perícia integra o campo, respeitados os impedimentos por vínculo com as partes.' },
    { t: 'A gestão de programas de saúde é matéria administrativa alheia à especialidade.', ok: false,
      why: 'Errada. Gestão em saúde do trabalhador integra a formação e a prática da especialidade.' }
  ],
  comentario: 'O campo é amplo — prevenção, reconhecimento, controle, aptidão, perícia e gestão — e a fronteira que precisa ficar clara é com a assistência longitudinal, que pertence ao médico assistente.',
  pegadinha: 'Reduzir a especialidade a admissional e demissional é a visão que a própria empresa costuma ter e que a prova cobra que você recuse.',
  refs: ['Resolução CFM sobre normas para médicos que atendem o trabalhador', 'Dias — Manual Prático da Medicina do Trabalho'] },

{ id: 'q-1.2-030', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um pesquisador afirma que a análise da saúde de entregadores de aplicativo exige considerar a informalidade, a ausência de vínculo formal e a autonomia apenas aparente. Sobre essa abordagem, é CORRETO afirmar:',
  alts: [
    { t: 'Ela é coerente com o campo da Saúde do Trabalhador, que toma o processo de trabalho como objeto e alcança todas as formas de inserção, inclusive as que escapam da proteção previdenciária e trabalhista clássica.', ok: true,
      why: 'Correta. É justamente para alcançar quem está fora da proteção formal que o campo se define pela relação com o trabalho, e não pelo contrato.' },
    { t: 'Trabalhadores sem vínculo formal estão fora do campo da saúde do trabalhador.', ok: false,
      why: 'Errada. A universalidade é traço definidor do campo.' },
    { t: 'A autonomia declarada nesses arranjos elimina a subordinação e, com ela, o risco ocupacional.', ok: false,
      why: 'Errada. Autonomia formal não elimina exposição a risco de trânsito, jornada extensa e pressão algorítmica.' },
    { t: 'A análise do processo de trabalho é dispensável quando não há empregador identificado.', ok: false,
      why: 'Errada. O processo de trabalho existe e é analisável independentemente da forma jurídica do vínculo.' },
    { t: 'Riscos psicossociais não se aplicam a trabalhadores sem vínculo formal.', ok: false,
      why: 'Errada. Insegurança de renda, avaliação por nota e imprevisibilidade são fatores psicossociais relevantes nesses arranjos.' }
  ],
  comentario: 'O campo se define pela relação com o TRABALHO, não pelo contrato. Formas novas de organização — plataformas, intermitência, informalidade — não estão fora dele; ao contrário, são onde a proteção clássica menos alcança.',
  pegadinha: 'A autonomia declarada nas plataformas é usada para afastar tanto o vínculo quanto o risco, e não afasta nenhum dos dois.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-1.2-031', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a determinação social do processo saúde-doença aplicada ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Ela sustenta que o adoecimento relacionado ao trabalho se explica por determinantes sociais e pela organização do trabalho, e não apenas por exposição a agentes isolados ou por características individuais.', ok: true,
      why: 'Correta. É o que permite enxergar ritmo, metas, precarização e informalidade como determinantes, ao lado dos agentes físicos e químicos.' },
    { t: 'A determinação social é conceito incompatível com a análise de agentes de risco específicos.', ok: false,
      why: 'Errada. São perspectivas complementares, não excludentes.' },
    { t: 'A abordagem nega a existência de suscetibilidade individual.', ok: false,
      why: 'Errada. Ela situa a suscetibilidade dentro de um contexto, sem negá-la.' },
    { t: 'Determinantes sociais não são passíveis de intervenção pelo serviço de saúde ocupacional.', ok: false,
      why: 'Errada. Organização do trabalho, jornada e formas de contratação são intervíveis e estão no alcance da gestão.' },
    { t: 'A perspectiva se aplica apenas a doenças infecciosas.', ok: false,
      why: 'Errada. Aplica-se a todo o espectro de agravos relacionados ao trabalho.' }
  ],
  comentario: 'Determinação social não substitui a toxicologia nem a higiene — soma-se a elas. É o que explica por que dois grupos com a mesma exposição química adoecem de forma diferente conforme jornada, ritmo e vínculo.',
  pegadinha: 'Opor determinação social e análise de agentes específicos cria um falso dilema entre duas ferramentas complementares.',
  refs: ['Mendes, R. — Patologia do Trabalho', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.4-030', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa quer estimar o custo do adoecimento relacionado ao trabalho para justificar investimento em prevenção. Sobre a composição desse custo, é CORRETO afirmar:',
  alts: [
    { t: 'O custo total combina componentes diretos — assistência, benefícios, reposição de mão de obra — e indiretos, como perda de produtividade, presenteísmo, retrabalho, rotatividade, treinamento de substitutos e impacto sobre a alíquota de financiamento do benefício acidentário.', ok: true,
      why: 'Correta. Os indiretos costumam superar os diretos e são justamente os que não aparecem em nenhuma planilha.' },
    { t: 'O custo se resume aos dias de afastamento pagos pela empresa.', ok: false,
      why: 'Errada. Ignora todo o custo indireto, que costuma ser maior.' },
    { t: 'Custos indiretos não são estimáveis e por isso devem ser desconsiderados.', ok: false,
      why: 'Errada. Existem metodologias de estimativa, e desconsiderá-los subdimensiona o problema.' },
    { t: 'O impacto sobre a alíquota de financiamento do benefício acidentário é irrelevante no cálculo.', ok: false,
      why: 'Errada. É um dos componentes mais tangíveis e mensuráveis.' },
    { t: 'Investimento em prevenção é custo, não gerando retorno mensurável.', ok: false,
      why: 'Errada. A redução de eventos e do fator de desempenho produz retorno mensurável.' }
  ],
  comentario: 'Diretos aparecem na folha; indiretos aparecem no resultado. Presenteísmo, retrabalho, rotatividade e a alíquota de financiamento acidentário costumam somar mais que os dias pagos — e são o argumento que convence a diretoria.',
  pegadinha: 'Descartar o custo indireto por ser difícil de medir é o que faz a prevenção parecer despesa.',
  refs: ['Zétola — Tratado de Gestão em Saúde do Trabalhador', 'Lei nº 8.213/1991'] },

{ id: 'q-1.5-040', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise crítica pela direção em um sistema de gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'É a etapa em que a alta direção avalia o desempenho do sistema com base em resultados de auditorias, investigações, indicadores e cumprimento de objetivos, decidindo sobre recursos e mudanças — e é o que transforma o sistema em instrumento de decisão, não em documentação.', ok: true,
      why: 'Correta. Sem essa etapa, o sistema produz informação que ninguém usa para decidir.' },
    { t: 'A análise crítica é atribuição do serviço especializado, sem participação da direção.', ok: false,
      why: 'Errada. É justamente da direção, porque envolve decisão sobre recursos e processos.' },
    { t: 'Ela se limita a verificar se os documentos estão atualizados.', ok: false,
      why: 'Errada. Avalia desempenho e adequação do sistema, não conformidade documental.' },
    { t: 'A análise crítica só é necessária quando ocorre acidente grave.', ok: false,
      why: 'Errada. É etapa periódica do ciclo de melhoria contínua.' },
    { t: 'As decisões da análise crítica não precisam ser registradas.', ok: false,
      why: 'Errada. O registro é o que permite acompanhar a implementação do que foi decidido.' }
  ],
  comentario: 'Análise crítica pela direção é onde o sistema vira decisão: recursos, mudança de processo, prioridade. Feita pelo serviço especializado sozinho, ela não tem poder de mudar nada — e é por isso que a norma a atribui à direção.',
  pegadinha: 'Delegar a análise crítica ao serviço técnico esvazia justamente o requisito de comprometimento da alta direção.',
  refs: ['OIT — Sistema de Gestão da SST', 'ISO 45001'] },

{ id: 'q-1.6-040', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a relação entre a política de saúde do trabalhador e a atenção primária à saúde, é CORRETO afirmar:',
  alts: [
    { t: 'A atenção primária é porta de entrada preferencial e território privilegiado para identificar a relação entre adoecimento e trabalho, dada sua proximidade com a população e o conhecimento das atividades produtivas locais.', ok: true,
      why: 'Correta. É onde o trabalhador informal chega, e onde a ocupação pode ser registrada e o padrão percebido.' },
    { t: 'A saúde do trabalhador é matéria de serviços especializados, sem interface com a atenção primária.', ok: false,
      why: 'Errada. A atenção primária é o principal ponto de contato, sobretudo para quem está fora do mercado formal.' },
    { t: 'A atenção primária deve encaminhar todo caso suspeito sem qualquer registro local.', ok: false,
      why: 'Errada. O registro local e a notificação são atribuições do serviço que identifica.' },
    { t: 'Equipes de saúde da família não têm papel na vigilância em saúde do trabalhador.', ok: false,
      why: 'Errada. O conhecimento do território e das atividades produtivas locais é insumo central da vigilância.' },
    { t: 'A ocupação do paciente é dado de interesse exclusivamente previdenciário.', ok: false,
      why: 'Errada. É o dado que permite relacionar adoecimento e trabalho na assistência.' }
  ],
  comentario: 'A atenção primária é onde a saúde do trabalhador acontece na prática, sobretudo para informais. Perguntar a ocupação, registrar e notificar são atos simples com enorme efeito sobre a visibilidade do problema.',
  pegadinha: 'Delegar tudo a serviços especializados deixa fora quem nunca chega a eles.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'Lei nº 8.080/1990'] },

{ id: 'q-1.7-040', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a participação social no sistema público de saúde aplicada à saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Conselhos e conferências de saúde são instâncias de controle social que alcançam também a saúde do trabalhador, e a participação de trabalhadores e de suas representações é prevista como diretriz do sistema.', ok: true,
      why: 'Correta. O controle social é diretriz do sistema e alcança todas as suas áreas de atuação.' },
    { t: 'O controle social não se aplica à saúde do trabalhador, por envolver relações privadas de trabalho.', ok: false,
      why: 'Errada. A saúde do trabalhador integra o campo de atuação do sistema público e está sujeita ao mesmo controle social.' },
    { t: 'A participação se limita a consultas informais, sem instâncias formais previstas.', ok: false,
      why: 'Errada. Há instâncias formais com composição e atribuições definidas.' },
    { t: 'Representações sindicais não podem participar de instâncias do sistema de saúde.', ok: false,
      why: 'Errada. Representações de trabalhadores integram esses espaços.' },
    { t: 'O controle social substitui a fiscalização técnica dos ambientes de trabalho.', ok: false,
      why: 'Errada. São instrumentos complementares, com naturezas distintas.' }
  ],
  comentario: 'Controle social é diretriz do sistema e alcança a saúde do trabalhador. Ele não substitui a fiscalização técnica — soma-se a ela, e é o que dá voz a quem está exposto.',
  pegadinha: 'Alegar que relações de trabalho são "privadas" para afastar o controle social ignora que o objeto é a saúde, que é pública.',
  refs: ['Lei nº 8.080/1990', 'Lei nº 8.142/1990', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.9-040', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a notificação de acidente de trabalho grave, é CORRETO afirmar:',
  alts: [
    { t: 'Acidentes graves e fatais têm notificação com prazo diferenciado, dada a necessidade de investigação oportuna do ambiente e do processo de trabalho antes que a cena e as condições sejam alteradas.', ok: true,
      why: 'Correta. A urgência decorre da necessidade de investigar antes que o local seja modificado e as evidências se percam.' },
    { t: 'Todos os agravos têm o mesmo prazo de notificação, independentemente da gravidade.', ok: false,
      why: 'Errada. Eventos graves e fatais têm tratamento diferenciado quanto à oportunidade.' },
    { t: 'A notificação de acidente grave dispensa a investigação do ambiente de trabalho.', ok: false,
      why: 'Errada, e inverte: a notificação existe para disparar essa investigação.' },
    { t: 'A notificação é dispensável quando a empresa já emitiu a comunicação previdenciária.', ok: false,
      why: 'Errada. São fluxos distintos e coexistentes.' },
    { t: 'Acidente grave em trabalhador informal não é notificável.', ok: false,
      why: 'Errada. A notificação independe do vínculo.' }
  ],
  comentario: 'Acidente grave e fatal tem prazo curto por uma razão prática: se a investigação demora, a máquina é consertada, o setor é reorganizado e as evidências desaparecem. A pressa é metodológica.',
  pegadinha: 'Supor que a comunicação previdenciária dispensa a notificação sanitária confunde dois fluxos com finalidades diferentes.',
  refs: ['SINAN — Ministério da Saúde', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.10-040', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre programas de promoção da saúde no ambiente de trabalho e a proteção de dados dos participantes, é CORRETO afirmar:',
  alts: [
    { t: 'Dados de saúde coletados em programas de promoção são sensíveis e não podem ser usados para decisões sobre o vínculo, a remuneração ou a progressão do trabalhador — e a adesão deve ser voluntária e não vinculada a benefícios contratuais.', ok: true,
      why: 'Correta. Vincular benefício a dado de saúde converte promoção em triagem, e o uso para decisão contratual é vedado.' },
    { t: 'Dados coletados em programas voluntários deixam de ser sensíveis por haver consentimento.', ok: false,
      why: 'Errada. O consentimento não altera a natureza do dado nem autoriza qualquer finalidade.' },
    { t: 'A empresa pode usar os resultados para direcionar promoções e aumentos.', ok: false,
      why: 'Errada. É uso vedado e discriminatório.' },
    { t: 'A adesão pode ser obrigatória, desde que o programa seja gratuito.', ok: false,
      why: 'Errada. Gratuidade não torna legítima a obrigatoriedade em programa de promoção.' },
    { t: 'Resultados individuais podem ser compartilhados com a chefia para acompanhamento.', ok: false,
      why: 'Errada. Resultado individual de saúde não vai à chefia.' }
  ],
  comentario: 'Promoção da saúde e proteção de dados se encontram aqui: adesão voluntária, dado sensível, resultado agregado e proibição de uso para decisão contratual. Sem isso, o programa vira triagem disfarçada de cuidado.',
  pegadinha: 'O consentimento aparece de novo como salvo-conduto — e em relação de emprego ele é frágil e não legitima qualquer finalidade.',
  refs: ['LGPD — Lei nº 13.709/2018', 'OMS — Ambientes de trabalho saudáveis', 'Código de Ética Médica'] }

);
