/* Lote AT — fechamento das metas por tema: 5.x, 6.x, 7.x, 1.x. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-5.4-140', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a análise de documentos de exposição em perícia de doença ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Documentos elaborados pela empresa devem ser analisados criticamente quanto à coerência interna, à data de elaboração e à correspondência com o processo descrito — e a divergência entre o documento e o relato de quem executava a tarefa é achado a investigar, não a descartar.', ok: true,
      why: 'Correta. Documento é prova a examinar, não verdade a acatar.' },
    { t: 'Documentos elaborados por profissional habilitado devem ser acatados sem análise crítica.', ok: false,
      why: 'Errada. A habilitação de quem elaborou não dispensa a análise do conteúdo.' },
    { t: 'A divergência entre documento e relato do trabalhador resolve-se sempre a favor do documento.', ok: false,
      why: 'Errada. É achado a investigar, considerando a data de elaboração e o processo real.' },
    { t: 'A data de elaboração do documento é informação irrelevante.', ok: false,
      why: 'Errada. Documento elaborado após o período em discussão tem valor limitado sobre ele.' },
    { t: 'A ausência de documentos de exposição impede qualquer conclusão pericial.', ok: false,
      why: 'Errada. Outros elementos permitem a análise, e a ausência de registro não pode prejudicar o trabalhador automaticamente.' }
  ],
  comentario: 'Documento de exposição se analisa: coerência, data, correspondência com o processo. Elaborado dez anos depois do período discutido, informa pouco sobre ele — e a divergência com o relato é pista, não ruído.',
  pegadinha: 'Acatar o documento por ser assinado por profissional habilitado dispensa a análise que a perícia existe para fazer.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Lei nº 8.213/1991'] },

{ id: 'q-5.4-141', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vistoria do local de trabalho no âmbito de perícia judicial, é CORRETO afirmar:',
  alts: [
    { t: 'Quando realizada, deve considerar que o processo pode ter sido alterado desde o período em discussão, buscando reconstituir as condições da época por meio de documentos, testemunhos e vestígios — a vistoria retrata o presente, não necessariamente o passado relevante.', ok: true,
      why: 'Correta. Vistoriar hoje um posto reformado não informa sobre a exposição de dez anos atrás.' },
    { t: 'A vistoria atual reflete adequadamente as condições do período em discussão.', ok: false,
      why: 'Errada. Processos e instalações mudam, frequentemente após o início do litígio.' },
    { t: 'Documentos e testemunhos não auxiliam a reconstituição das condições pretéritas.', ok: false,
      why: 'Errada. São as principais fontes quando o processo foi alterado.' },
    { t: 'A vistoria dispensa a observação da atividade sendo executada.', ok: false,
      why: 'Errada. Observar a execução revela o trabalho real, distinto do descrito.' },
    { t: 'A ausência de vistoria invalida automaticamente o laudo.', ok: false,
      why: 'Errada. Sua necessidade depende do objeto da perícia e das demais fontes disponíveis.' }
  ],
  comentario: 'A vistoria mostra hoje; a exposição em discussão é de ontem. Reconstituir exige documentos, testemunhos e vestígios — e observar a atividade sendo executada, não apenas o posto vazio.',
  pegadinha: 'Concluir pela exposição atual quando o setor foi reformado depois do afastamento avalia outra coisa.',
  refs: ['Código de Processo Civil', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-5.5-130', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação de capacidade em trabalhador com perda visual parcial, é CORRETO afirmar:',
  alts: [
    { t: 'Além da acuidade, importam campo visual, visão de profundidade, sensibilidade ao contraste e adaptação ao escuro — parâmetros que podem ser determinantes em funções específicas mesmo com acuidade preservada.', ok: true,
      why: 'Correta. Acuidade normal convive com campo visual reduzido, o que muda tudo em algumas funções.' },
    { t: 'A acuidade visual isolada descreve adequadamente a capacidade visual para o trabalho.', ok: false,
      why: 'Errada. Campo, profundidade e contraste podem ser determinantes.' },
    { t: 'A visão de profundidade não é relevante em atividades industriais.', ok: false,
      why: 'Errada. É determinante em operação de equipamentos móveis e trabalho em altura.' },
    { t: 'A adaptação ao escuro não influencia a segurança em trabalho noturno.', ok: false,
      why: 'Errada. É parâmetro relevante em atividades noturnas e em ambientes com variação de iluminação.' },
    { t: 'A perda visual em um olho implica inaptidão para qualquer função.', ok: false,
      why: 'Errada. A avaliação é por função, considerando quais parâmetros ela exige.' }
  ],
  comentario: 'Visão para o trabalho não é só acuidade: campo, profundidade, contraste e adaptação ao escuro decidem em funções específicas. E perda em um olho não inabilita para tudo — avalia-se contra a exigência da função.',
  pegadinha: 'Medir acuidade e concluir deixa de fora o campo visual, que é o que importa em ponte rolante e empilhadeira.',
  refs: ['NR-7', 'Diretrizes de oftalmologia ocupacional'] },

{ id: 'q-5.6-120', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre reabilitação profissional e a empresa de origem, é CORRETO afirmar:',
  alts: [
    { t: 'A permanência na empresa de origem, quando viável, tende a produzir melhores desfechos por preservar vínculo, tempo de casa e conhecimento do ambiente — e a recusa da empresa em receber o reabilitado é barreira frequente que precisa ser enfrentada com os instrumentos disponíveis.', ok: true,
      why: 'Correta. Recolocar onde já se conhece o ambiente é mais fácil e mais estável.' },
    { t: 'A recolocação em nova empresa apresenta melhores resultados que a permanência na origem.', ok: false,
      why: 'Errada. A permanência preserva vínculo e conhecimento do ambiente, favorecendo o desfecho.' },
    { t: 'A recusa da empresa em receber o reabilitado não encontra qualquer instrumento de enfrentamento.', ok: false,
      why: 'Errada. Há reserva legal de vagas e instrumentos de fiscalização e atuação.' },
    { t: 'O conhecimento prévio do ambiente pelo trabalhador é irrelevante para o retorno.', ok: false,
      why: 'Errada. Reduz o tempo de adaptação e facilita a alocação.' },
    { t: 'A empresa não pode ser envolvida no processo conduzido pela previdência.', ok: false,
      why: 'Errada. Sua participação é essencial para descrever funções e viabilizar a recolocação.' }
  ],
  comentario: 'Reabilitar dentro da empresa de origem preserva vínculo, tempo de casa e conhecimento do ambiente — e costuma dar melhor resultado. A recusa da empresa é barreira comum, com instrumentos legais para enfrentá-la.',
  pegadinha: 'Encaminhar direto para recolocação externa descarta a alternativa com maior chance de sucesso.',
  refs: ['Lei nº 8.213/1991 — arts. 89 a 93', 'Literatura sobre retorno ao trabalho'] },

{ id: 'q-5.3-120', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausalidade entre exposições de diferentes empregadores, é CORRETO afirmar:',
  alts: [
    { t: 'Exposições sucessivas em empregadores distintos podem somar-se na determinação do agravo, e a dificuldade de repartir a contribuição entre eles não afasta o reconhecimento da natureza ocupacional — questão que se coloca na esfera da responsabilidade, não na do nexo.', ok: true,
      why: 'Correta. Repartir responsabilidade é problema distinto de reconhecer o nexo.' },
    { t: 'Apenas a exposição no último empregador é considerada.', ok: false,
      why: 'Errada. Exposições anteriores integram a determinação do agravo.' },
    { t: 'A impossibilidade de repartir a contribuição afasta o reconhecimento do nexo.', ok: false,
      why: 'Errada. São questões distintas: nexo e responsabilidade.' },
    { t: 'Exposições sucessivas não se somam na determinação do quadro.', ok: false,
      why: 'Errada. A dose acumulada ao longo da vida laboral é o que importa em vários agravos.' },
    { t: 'A análise dispensa a reconstituição das exposições anteriores.', ok: false,
      why: 'Errada. É justamente ela que permite compreender a dose acumulada.' }
  ],
  comentario: 'Exposições em empregadores sucessivos se somam. Não saber repartir a contribuição é problema de responsabilidade — não de nexo, que se reconhece pela dose acumulada ao longo da vida laboral.',
  pegadinha: 'Olhar só o último empregador em agravo de dose acumulada avalia a menor parte da exposição.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-6.1-130', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre exames complementares no programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser indicados conforme o risco e o efeito crítico do agente, com periodicidade definida por critério técnico — e a inclusão de exames sem relação com a exposição consome recurso, gera achados incidentais e desloca o foco do que deveria ser vigiado.', ok: true,
      why: 'Correta. Exame indicado é o que vigia o efeito crítico daquela exposição.' },
    { t: 'A ampliação da bateria de exames aumenta proporcionalmente a proteção do trabalhador.', ok: false,
      why: 'Errada. Exame sem indicação não vigia a exposição e produz achado incidental.' },
    { t: 'A periodicidade dos exames complementares independe do agente e do nível de exposição.', ok: false,
      why: 'Errada. Ambos determinam a periodicidade adequada.' },
    { t: 'Achados incidentais não geram custos nem consequências ao trabalhador.', ok: false,
      why: 'Errada. Geram investigação, ansiedade e, por vezes, intervenções desnecessárias.' },
    { t: 'A escolha dos exames pode ser padronizada por pacote comercial oferecido pelo prestador.', ok: false,
      why: 'Errada. A indicação é técnica e decorre do risco, não da oferta do fornecedor.' }
  ],
  comentario: 'Exame complementar segue o efeito crítico do agente, com periodicidade por critério técnico. Pacote comercial padronizado vigia o que o fornecedor vende, não o que o trabalhador está exposto.',
  pegadinha: 'Adotar o pacote do prestador transfere a definição técnica do programa para quem o comercializa.',
  refs: ['NR-7', 'ACGIH — BEIs'] },

{ id: 'q-6.2-130', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o exame admissional de candidato com deficiência encaminhado à vaga reservada, é CORRETO afirmar:',
  alts: [
    { t: 'A avaliação verifica compatibilidade com a função considerando adaptações razoáveis, e a conclusão de inaptidão exige demonstração de incompatibilidade que não se resolva por adaptação — não bastando a constatação da deficiência.', ok: true,
      why: 'Correta. Sem essa exigência, o exame vira filtro que esvazia a reserva.' },
    { t: 'A constatação da deficiência é suficiente para concluir pela inaptidão.', ok: false,
      why: 'Errada. É preciso demonstrar incompatibilidade insuperável por adaptação.' },
    { t: 'As adaptações razoáveis não devem ser consideradas na avaliação admissional.', ok: false,
      why: 'Errada. Integram a análise de compatibilidade.' },
    { t: 'A conclusão de inaptidão não precisa ser fundamentada nesses casos.', ok: false,
      why: 'Errada. Exige fundamentação, dado o potencial discriminatório da conclusão.' },
    { t: 'O médico não deve indicar quais adaptações viabilizariam a contratação.', ok: false,
      why: 'Errada. Indicá-las é contribuição central do serviço médico à inclusão.' }
  ],
  comentario: 'Inaptidão de candidato com deficiência exige demonstrar incompatibilidade que a adaptação não resolve — e o médico deve indicar quais adaptações viabilizariam a contratação, em vez de apenas negar.',
  pegadinha: 'Concluir pela deficiência em si transforma o exame admissional no mecanismo que anula a reserva de vagas.',
  refs: ['Lei nº 13.146/2015', 'Lei nº 8.213/1991 — art. 93', 'Lei nº 9.029/1995'] },

{ id: 'q-6.3-130', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação cardiovascular em trabalhadores de funções de alta exigência física, é CORRETO afirmar:',
  alts: [
    { t: 'A avaliação deve considerar a estratificação de risco individual e as exigências reais da atividade, incluindo esforço, calor e uso de equipamentos que aumentam a carga — sendo o combate a incêndio e o resgate exemplos em que a exigência cardiovascular é elevada e mensurável.', ok: true,
      why: 'Correta. Roupa de proteção e calor somam carga cardiovascular relevante.' },
    { t: 'A avaliação cardiovascular ocupacional independe das exigências da função.', ok: false,
      why: 'Errada. É a exigência que define o que precisa ser avaliado.' },
    { t: 'O uso de equipamento de proteção não altera a carga cardiovascular da atividade.', ok: false,
      why: 'Errada. Vestimenta e respirador aumentam a carga de forma significativa.' },
    { t: 'A estratificação de risco individual não tem papel nessa avaliação.', ok: false,
      why: 'Errada. É elemento central da decisão de aptidão.' },
    { t: 'Testes de esforço devem ser aplicados indistintamente a todos os trabalhadores.', ok: false,
      why: 'Errada. A indicação decorre do risco individual e da exigência da função.' }
  ],
  comentario: 'Função de alta exigência física exige avaliar risco individual contra a exigência real — que inclui calor e o peso e a oclusão do equipamento de proteção. Teste de esforço se indica, não se distribui.',
  pegadinha: 'Avaliar o esforço da tarefa sem contar a roupa de proteção subestima a carga cardiovascular real.',
  refs: ['NR-7', 'Diretrizes de cardiologia ocupacional', 'NR-6'] },

{ id: 'q-6.4-130', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a resposta a emergência com múltiplas vítimas em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A triagem visa direcionar recursos limitados para obter o melhor resultado global, o que pode implicar priorizar vítimas com maior chance de sobrevida — lógica distinta do atendimento individual, e que precisa estar prevista e treinada antes do evento.', ok: true,
      why: 'Correta. É decisão difícil que não pode ser improvisada na hora.' },
    { t: 'A triagem segue a mesma lógica do atendimento individual, priorizando o caso mais grave.', ok: false,
      why: 'Errada. Em múltiplas vítimas, prioriza-se o resultado global com recursos limitados.' },
    { t: 'A definição de critérios de triagem pode ser feita no momento do evento.', ok: false,
      why: 'Errada. Precisa estar previamente estabelecida e treinada.' },
    { t: 'A comunicação com serviços externos é secundária nesse cenário.', ok: false,
      why: 'Errada. É determinante para a mobilização de recursos e a distribuição das vítimas.' },
    { t: 'O registro das vítimas e das condutas pode ser feito apenas ao final.', ok: false,
      why: 'Errada. O registro durante o atendimento evita perda de informação e duplicidade.' }
  ],
  comentario: 'Múltiplas vítimas inverte a lógica: prioriza-se o resultado global, não o caso mais grave. É decisão dura, que precisa estar definida e treinada antes — junto com comunicação externa e registro em tempo real.',
  pegadinha: 'Aplicar a lógica do atendimento individual em cenário de múltiplas vítimas consome os recursos no primeiro caso.',
  refs: ['Protocolos de atendimento a múltiplas vítimas', 'NR-1'] },

{ id: 'q-7.3-130', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a competência sanitária relativa a produtos para a saúde e equipamentos utilizados por trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'O registro e a regularização sanitária de produtos e equipamentos alcançam também itens usados na assistência e na proteção, de modo que o uso de produto irregular expõe simultaneamente pacientes e trabalhadores.', ok: true,
      why: 'Correta. Produto irregular na assistência atinge quem recebe e quem manuseia.' },
    { t: 'A regularização sanitária de produtos não tem relação com a proteção de trabalhadores.', ok: false,
      why: 'Errada. Produtos usados na assistência e na proteção alcançam diretamente os trabalhadores.' },
    { t: 'Equipamentos de proteção não estão sujeitos a qualquer controle de conformidade.', ok: false,
      why: 'Errada. Estão sujeitos a certificação e controle de conformidade próprios.' },
    { t: 'O uso de produto sem regularização é irregularidade sem repercussão em saúde.', ok: false,
      why: 'Errada. A ausência de avaliação de segurança e eficácia repercute diretamente em saúde.' },
    { t: 'A notificação de eventos adversos com produtos não integra as atribuições dos serviços.', ok: false,
      why: 'Errada. A notificação alimenta a vigilância pós-comercialização.' }
  ],
  comentario: 'Regularização sanitária de produto alcança o que se usa na assistência e na proteção — e produto irregular expõe paciente e trabalhador. Notificar evento adverso é o que alimenta a vigilância desses itens.',
  pegadinha: 'Separar controle de produto de saúde ocupacional ignora que ambos usam o mesmo item.',
  refs: ['Legislação sanitária de produtos para a saúde', 'NR-6', 'Lei nº 8.080/1990'] },

{ id: 'q-7.4-130', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os requisitos aplicáveis a caldeiras, vasos de pressão e tubulações, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem-se inspeções periódicas por profissional habilitado, documentação de histórico do equipamento e capacitação específica dos operadores — requisitos justificados pelo potencial catastrófico das falhas, que atingem trabalhadores muito além do operador direto.', ok: true,
      why: 'Correta. É risco de evento raro e de consequência devastadora.' },
    { t: 'A inspeção desses equipamentos pode ser realizada por qualquer profissional da manutenção.', ok: false,
      why: 'Errada. Exige-se profissional legalmente habilitado.' },
    { t: 'O histórico documentado do equipamento é dispensável quando não há registro de falhas.', ok: false,
      why: 'Errada. O histórico é exigência e sustenta as decisões de inspeção e reparo.' },
    { t: 'A capacitação do operador é dispensável quando o equipamento é automatizado.', ok: false,
      why: 'Errada. A capacitação específica permanece exigida.' },
    { t: 'O risco desses equipamentos alcança apenas o operador direto.', ok: false,
      why: 'Errada. Falhas catastróficas atingem toda a área e trabalhadores próximos.' }
  ],
  comentario: 'Caldeira e vaso de pressão: inspeção por profissional habilitado, histórico documentado e operador capacitado — inclusive em equipamento automatizado. O risco é de evento raro que atinge muito além do operador.',
  pegadinha: 'Automatizar não elimina a exigência de capacitação de quem opera e acompanha.',
  refs: ['NR-13'] },

{ id: 'q-7.5-100', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a qualidade da informação transmitida nos eventos de saúde e segurança e seus efeitos de longo prazo, é CORRETO afirmar:',
  alts: [
    { t: 'A informação transmitida forma um histórico individual que acompanhará o trabalhador ao longo da vida laboral, sustentando pedidos futuros de reconhecimento — e erros hoje se manifestam como negativa de direito décadas depois, quando a correção é muito mais difícil.', ok: true,
      why: 'Correta. O dano do erro aparece muito depois de quem o cometeu ter saído.' },
    { t: 'Erros na informação transmitida podem ser corrigidos a qualquer tempo sem prejuízo.', ok: false,
      why: 'Errada. A correção tardia é difícil e nem sempre viável.' },
    { t: 'A informação transmitida tem efeito restrito ao período do vínculo atual.', ok: false,
      why: 'Errada. Compõe o histórico que sustenta reconhecimentos futuros.' },
    { t: 'A conferência periódica das informações transmitidas é medida sem utilidade.', ok: false,
      why: 'Errada. É o que permite identificar e corrigir inconsistências enquanto ainda é possível.' },
    { t: 'O trabalhador não tem interesse direto na qualidade dessas informações.', ok: false,
      why: 'Errada. É delas que dependerá o reconhecimento de tempo especial e de nexo no futuro.' }
  ],
  comentario: 'A informação transmitida hoje é a prova de amanhã: sustenta aposentadoria especial e discussão de nexo décadas à frente. Erro cometido agora aparece como negativa de direito quando ninguém mais pode corrigi-lo.',
  pegadinha: 'Tratar o preenchimento como obrigação do mês perde de vista que ele constrói um histórico de trinta anos.',
  refs: ['eSocial — eventos de SST', 'Lei nº 8.213/1991'] },

{ id: 'q-7.6-100', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do médico do trabalho diante de condição de risco grave identificada no ambiente, é CORRETO afirmar:',
  alts: [
    { t: 'Cabe comunicar formalmente à empresa, registrar a comunicação e, persistindo a condição, acionar as autoridades competentes — o registro da comunicação é o que documenta o cumprimento do dever e protege o profissional.', ok: true,
      why: 'Correta. Comunicação verbal não registrada não existe quando o acidente acontece.' },
    { t: 'A comunicação verbal à chefia satisfaz o dever do médico.', ok: false,
      why: 'Errada. Sem registro, não há como demonstrar o cumprimento do dever.' },
    { t: 'O acionamento de autoridades é vedado ao médico contratado pela empresa.', ok: false,
      why: 'Errada. É conduta legítima e prevista diante de risco não corrigido.' },
    { t: 'A identificação de risco grave está fora do escopo de atuação do médico do trabalho.', ok: false,
      why: 'Errada. O conhecimento do ambiente e a comunicação de riscos integram sua atuação.' },
    { t: 'A persistência da condição após a comunicação encerra a responsabilidade do médico.', ok: false,
      why: 'Errada. A persistência é justamente o que motiva o acionamento das autoridades.' }
  ],
  comentario: 'Risco grave identificado: comunicar formalmente, registrar e, se persistir, acionar as autoridades. O registro é o que demonstra o cumprimento do dever — e é o que sobra quando o acidente ocorre.',
  pegadinha: 'A comunicação verbal em reunião não deixa rastro e não protege ninguém depois.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM', 'NR-1'] },

{ id: 'q-7.7-100', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a responsabilidade técnica em serviços de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'O responsável técnico responde pela adequação dos procedimentos e pela qualidade dos atos praticados sob sua coordenação, o que exige conhecimento efetivo do serviço — a assunção formal de responsabilidade por serviço que não se acompanha é prática de risco ético e legal.', ok: true,
      why: 'Correta. Responsabilidade técnica de assinatura, sem acompanhamento, é o cenário de maior exposição.' },
    { t: 'A responsabilidade técnica é atribuição formal sem implicações práticas.', ok: false,
      why: 'Errada. Implica responder pela adequação dos procedimentos do serviço.' },
    { t: 'É admissível assumir responsabilidade técnica de serviços que não se acompanha.', ok: false,
      why: 'Errada. É prática de risco ético e legal.' },
    { t: 'A responsabilidade técnica alcança apenas os atos praticados pessoalmente.', ok: false,
      why: 'Errada. Alcança os procedimentos e a qualidade do serviço sob coordenação.' },
    { t: 'A responsabilidade técnica não gera dever de verificar as condições de trabalho da própria equipe.', ok: false,
      why: 'Errada. Condições inadequadas comprometem a qualidade dos atos pelos quais responde.' }
  ],
  comentario: 'Responsabilidade técnica é responder pelo serviço, não emprestar o nome. Alcança os procedimentos sob coordenação — e as condições em que a própria equipe trabalha, porque delas depende a qualidade dos atos.',
  pegadinha: 'Assinar responsabilidade técnica de serviço que não se visita é o arranjo mais frequente e o de maior exposição.',
  refs: ['Resoluções do CFM', 'Código de Ética Médica'] },

{ id: 'q-7.8-100', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de sistemas de monitoramento e produtividade que coletam dados de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'A coleta deve ter finalidade específica, informada ao trabalhador, e observar proporcionalidade — e o monitoramento contínuo e granular tem efeitos documentados sobre saúde mental, o que o torna também objeto de avaliação de risco psicossocial, e não apenas de proteção de dados.', ok: true,
      why: 'Correta. É simultaneamente questão de dados e de risco psicossocial.' },
    { t: 'O monitoramento de produtividade é assunto exclusivamente de proteção de dados.', ok: false,
      why: 'Errada. Tem efeitos documentados sobre saúde mental e integra a avaliação de riscos psicossociais.' },
    { t: 'O trabalhador não precisa ser informado sobre os dados coletados a seu respeito.', ok: false,
      why: 'Errada. A transparência sobre a coleta é exigência.' },
    { t: 'O poder diretivo autoriza monitoramento de qualquer extensão.', ok: false,
      why: 'Errada. A proporcionalidade e a privacidade limitam a extensão do monitoramento.' },
    { t: 'Dados de produtividade não podem, em nenhuma hipótese, revelar informações sobre saúde.', ok: false,
      why: 'Errada. Padrões de pausa, ritmo e ausência podem revelar condições de saúde, o que exige cautela adicional.' }
  ],
  comentario: 'Monitoramento de produtividade é duas coisas ao mesmo tempo: tratamento de dados com finalidade e proporcionalidade, e fator psicossocial com efeito documentado. E padrões de pausa podem revelar condição de saúde.',
  pegadinha: 'Tratar o tema apenas como conformidade de dados ignora o que o monitoramento contínuo faz com quem é monitorado.',
  refs: ['LGPD', 'NR-1 — fatores psicossociais', 'OIT'] },

{ id: 'q-7.2-130', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a relação entre reconhecimento de doença ocupacional e as obrigações da empresa, é CORRETO afirmar:',
  alts: [
    { t: 'O reconhecimento repercute em estabilidade, recolhimento do fundo de garantia durante o afastamento, indicadores de acidentalidade e alíquota de contribuição — conjunto de efeitos que explica a resistência empresarial e reforça a importância da correção técnica da análise.', ok: true,
      why: 'Correta. Há consequências econômicas concretas, e é por isso que a análise sofre pressão.' },
    { t: 'O reconhecimento não gera repercussões econômicas para a empresa.', ok: false,
      why: 'Errada. Alcança estabilidade, fundo de garantia, indicadores e alíquota.' },
    { t: 'Os indicadores de acidentalidade não são afetados por doenças reconhecidas.', ok: false,
      why: 'Errada. Doenças ocupacionais integram esses indicadores.' },
    { t: 'A pressão sobre a análise técnica é justificativa aceitável para modular a conclusão.', ok: false,
      why: 'Errada. A conclusão é técnica e não se modula por consequência econômica.' },
    { t: 'A alíquota de contribuição por acidentalidade não considera doenças ocupacionais.', ok: false,
      why: 'Errada. Elas compõem o desempenho que determina a variação da alíquota.' }
  ],
  comentario: 'Reconhecer doença ocupacional mexe em estabilidade, fundo de garantia, indicadores e alíquota — o que explica a pressão sobre a análise. E é exatamente por isso que a conclusão precisa ser estritamente técnica.',
  pegadinha: 'Entender por que existe pressão é diferente de aceitá-la como critério de conclusão.',
  refs: ['Lei nº 8.213/1991 — arts. 21-A e 118', 'Lei nº 10.666/2003', 'Lei nº 8.036/1990'] }

);
