/* Lote V — 7.5 (eSocial), 7.3 (legislação sanitária), 7.6 (CEM), 7.7 (CFM), 7.8 (LGPD). AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.5-040', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a finalidade e a estrutura do eSocial no que se refere a segurança e saúde no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Unifica num único envio informações antes prestadas a órgãos distintos, inclusive de saúde e segurança.', ok: true,
      why: 'Correta. A unificação torna o dado cruzável entre fisco, previdência e fiscalização.' },
    { t: 'Unifica informações trabalhistas num único envio, restrito à folha de pagamento e aos vínculos declarados.', ok: false,
      why: 'Errada. Há eventos específicos de segurança e saúde no trabalho.' },
    { t: 'Unifica informações de órgãos distintos, não podendo o que foi enviado ser retificado posteriormente.', ok: false,
      why: 'Errada. Há procedimento de retificação previsto.' },
    { t: 'Unifica informações de órgãos distintos, sendo facultativa a prestação de saúde e segurança às pequenas.', ok: false,
      why: 'Errada. Há cronogramas distintos de obrigatoriedade, não dispensa da obrigação.' },
    { t: 'Unifica informações num único envio, sem que o informado repercuta em outras esferas administrativas.', ok: false,
      why: 'Errada. O cruzamento com previdência e fiscalização é justamente a finalidade do sistema.' }
  ],
  comentario: 'O eSocial unifica envios que antes iam a órgãos separados, incluindo os eventos de saúde e segurança. Isso torna a informação cruzável — e o erro de preenchimento passa a ter consequência em mais de uma esfera.',
  pegadinha: 'Tratar o eSocial como assunto de folha de pagamento deixa os eventos de saúde e segurança sem responsável técnico.',
  refs: ['eSocial — leiaute de eventos de SST', 'Manual de orientação do eSocial'] },

{ id: 'q-7.5-041', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a responsabilidade do médico do trabalho nas informações de monitoramento da saúde enviadas pelo eSocial, é CORRETO afirmar:',
  alts: [
    { t: 'Reproduz os dados do atestado, e o médico responde pela veracidade daquilo que atesta', ok: true,
      why: 'Correta. Quem opera o envio não assume a responsabilidade pelo conteúdo do ato médico.' },
    { t: 'Reproduz os dados do atestado, sendo a responsabilidade pelo conteúdo do setor que realiza o envio.', ok: false,
      why: 'Errada. O conteúdo médico permanece sob responsabilidade de quem o atesta.' },
    { t: 'Reproduz os dados do atestado, devendo informar o diagnóstico apurado no exame do trabalhador.', ok: false,
      why: 'Errada. Informa-se a conclusão de aptidão e os exames realizados, não o diagnóstico.' },
    { t: 'Reproduz os dados do atestado, sendo dispensável o registro do profissional que o emitiu.', ok: false,
      why: 'Errada. A identificação do médico responsável integra o evento.' },
    { t: 'Reproduz os dados do atestado, não podendo erros no envio ser corrigidos depois do prazo.', ok: false,
      why: 'Errada. Há retificação prevista, ainda que possa haver consequências pela intempestividade.' }
  ],
  comentario: 'O evento de monitoramento reproduz o atestado de saúde ocupacional e identifica o médico responsável. Diagnóstico não entra — entra a conclusão de aptidão. E terceirizar o envio não terceiriza a responsabilidade pelo conteúdo.',
  pegadinha: 'Informar diagnóstico em campo de sistema é quebra de sigilo com registro permanente.',
  refs: ['eSocial — evento de monitoramento da saúde do trabalhador', 'NR-7', 'Código de Ética Médica'] },

{ id: 'q-7.5-042', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a comunicação de acidente de trabalho por meio do eSocial, é CORRETO afirmar:',
  alts: [
    { t: 'O evento próprio substitui o formulário para as obrigadas, mantidos os prazos e os legitimados.', ok: true,
      why: 'Correta. Muda o meio de transmissão, não a obrigação nem os legitimados concorrentes.' },
    { t: 'O evento próprio substitui o formulário anterior e alterou os prazos legais de comunicação do acidente.', ok: false,
      why: 'Errada. Os prazos permanecem os previstos em lei.' },
    { t: 'O evento próprio substitui o formulário, passando apenas a empresa a poder comunicar o acidente.', ok: false,
      why: 'Errada. Os demais legitimados mantêm a possibilidade por outras vias.' },
    { t: 'O evento próprio substitui o formulário, deixando os acidentes sem afastamento de ser comunicáveis.', ok: false,
      why: 'Errada. Permanecem sujeitos a comunicação.' },
    { t: 'O evento próprio substitui o formulário anterior e também a investigação interna do acidente.', ok: false,
      why: 'Errada. São obrigações distintas e ambas subsistem.' }
  ],
  comentario: 'O eSocial mudou o meio, não a substância: prazos legais mantidos, casos sem afastamento incluídos, legitimados concorrentes preservados. E comunicar não substitui investigar.',
  pegadinha: 'Supor que a mudança de sistema alterou prazo ou legitimados é confusão entre meio e obrigação.',
  refs: ['eSocial — evento de comunicação de acidente de trabalho', 'Lei nº 8.213/1991 — art. 22'] },

{ id: 'q-7.3-070', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a atuação da vigilância sanitária em ambientes de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Alcança o ambiente de trabalho por ser ambiente de exposição, coexistindo com a do trabalho', ok: true,
      why: 'Correta. Coexistência de competências, não sobreposição excludente.' },
    { t: 'Alcança estabelecimentos abertos ao público, não tendo competência sobre os ambientes de trabalho.', ok: false,
      why: 'Errada. A competência decorre da lei orgânica da saúde.' },
    { t: 'Alcança o ambiente de trabalho, substituindo a atuação sanitária a fiscalização do trabalho nesse campo.', ok: false,
      why: 'Errada. São competências distintas que coexistem e podem atuar de forma articulada.' },
    { t: 'Alcança o ambiente de trabalho, dependendo a interdição sanitária de prévia autuação pela fiscalização.', ok: false,
      why: 'Errada. É medida autônoma, cabível diante de risco à saúde.' },
    { t: 'Alcança apenas estabelecimentos de saúde e de alimentos, onde há exposição direta de terceiros.', ok: false,
      why: 'Errada. Sua competência alcança ambientes que exponham a saúde de pessoas, incluindo os de trabalho.' }
  ],
  comentario: 'Ambiente de trabalho é ambiente de exposição de pessoas — e por isso é objeto de vigilância sanitária, com poder de inspeção e interdição autônomo em relação à fiscalização do trabalho.',
  pegadinha: 'Achar que só o órgão do trabalho atua sobre ambientes laborais ignora uma competência concorrente prevista em lei.',
  refs: ['Lei nº 8.080/1990', 'Legislação sanitária estadual e municipal', 'PNSTT'] },

{ id: 'q-7.3-071', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o controle sanitário de produtos e substâncias perigosas com repercussão sobre trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Envolvem competências sanitárias, ambientais e agrícolas, e as restrições atingem a exposição ocupacional.', ok: true,
      why: 'Correta. A tríplice competência é uma característica marcante desse controle.' },
    { t: 'Envolvem registro e rotulagem, sendo o registro de agrotóxicos competência exclusiva do órgão agrícola.', ok: false,
      why: 'Errada. Envolve também as áreas de saúde e de meio ambiente.' },
    { t: 'Envolvem competências múltiplas, sem que decisões de banimento afetem a exposição ocupacional.', ok: false,
      why: 'Errada. Retirar o produto do mercado é a medida de prevenção de maior alcance.' },
    { t: 'Envolvem competências sanitárias e ambientais, ficando a rotulagem de saneantes fora do controle sanitário.', ok: false,
      why: 'Errada. É objeto expresso de regulação sanitária.' },
    { t: 'Envolvem competências múltiplas, não cabendo ao médico do trabalho comunicar eventos adversos.', ok: false,
      why: 'Errada. A notificação de intoxicações alimenta o sistema que sustenta as decisões regulatórias.' }
  ],
  comentario: 'Agrotóxicos e saneantes têm controle compartilhado entre saúde, meio ambiente e agricultura. Banimento e restrição são as medidas de prevenção mais amplas que existem — e a notificação médica de intoxicações é o que as sustenta.',
  pegadinha: 'Ver o registro como assunto agrícola apaga a competência sanitária que protege quem aplica o produto.',
  refs: ['Legislação de agrotóxicos', 'Anvisa — saneantes', 'Lei nº 8.080/1990'] },

{ id: 'q-7.6-040', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o conflito de interesses do médico do trabalho contratado pela empresa, é CORRETO afirmar:',
  alts: [
    { t: 'O médico atende com os mesmos deveres éticos, e a remuneração pela empresa não cria lealdade prevalente.', ok: true,
      why: 'Correta. Quem paga não é quem o médico serve nesse ato.' },
    { t: 'O médico atende com deveres éticos, estabelecendo o vínculo contratual lealdade prevalente ao contratante.', ok: false,
      why: 'Errada. O dever ético primário é com a saúde do trabalhador examinado.' },
    { t: 'O médico do trabalho avalia a aptidão sem estabelecer relação médica com o trabalhador examinado.', ok: false,
      why: 'Errada. Estabelece, com deveres de sigilo, informação e cuidado.' },
    { t: 'O médico atende com deveres éticos, podendo omitir achados clínicos que não afetem a aptidão.', ok: false,
      why: 'Errada. O trabalhador tem direito de conhecer sua condição e ser orientado.' },
    { t: 'O médico atende com deveres éticos, sendo a independência técnica recomendação sem respaldo internacional.', ok: false,
      why: 'Errada. O código internacional de ética da área a estabelece expressamente.' }
  ],
  comentario: 'Há relação médica com o trabalhador examinado, com sigilo, informação e cuidado — e independência técnica frente a quem contrata. Achado relevante se comunica ao trabalhador mesmo quando não muda a aptidão.',
  pegadinha: 'A ideia de que não há relação médica no exame ocupacional é o que abre caminho para omitir achados e quebrar sigilo.',
  refs: ['Código de Ética Médica', 'ICOH — Código Internacional de Ética'] },

{ id: 'q-7.6-041', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o prontuário do trabalhador sob guarda do serviço médico da empresa, é CORRETO afirmar:',
  alts: [
    { t: 'É documento sob responsabilidade do médico, com guarda separada e acesso restrito à equipe.', ok: true,
      why: 'Correta. O titular tem direito de acesso ao conteúdo; o empregador, não.' },
    { t: 'É documento do serviço médico, tendo o empregador direito de acesso por custear esse serviço.', ok: false,
      why: 'Errada. Custeio não confere acesso a conteúdo clínico.' },
    { t: 'É documento sob responsabilidade do médico, não podendo o trabalhador acessar o próprio prontuário.', ok: false,
      why: 'Errada. O acesso do titular é direito reconhecido.' },
    { t: 'É documento sob guarda do médico, podendo ser descartado imediatamente após o desligamento.', ok: false,
      why: 'Errada. Os prazos de guarda são longos, o que é essencial em latências prolongadas.' },
    { t: 'É documento sob guarda do médico, podendo ser destruído se a empresa encerrar as atividades.', ok: false,
      why: 'Errada. É preciso providenciar guarda adequada, preservando o acesso futuro.' }
  ],
  comentario: 'Prontuário ocupacional: guarda pelo médico, separada do arquivo funcional, acesso do titular garantido e do empregador vedado, prazos longos — inclusive quando a empresa encerra atividades.',
  pegadinha: 'Descartar prontuários no encerramento da empresa elimina a prova de exposição justamente de quem vai adoecer depois.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM sobre prontuário', 'NR-7'] },

{ id: 'q-7.7-040', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a relação entre resoluções do Conselho Federal de Medicina e normas trabalhistas, é CORRETO afirmar:',
  alts: [
    { t: 'Disciplinam a conduta ética e vinculam o médico, ainda que a exigência venha de norma ou contrato.', ok: true,
      why: 'Correta. Cumprir ordem incompatível com dever ético não exime o médico.' },
    { t: 'Disciplinam a conduta ética, prevalecendo a norma trabalhista sobre a resolução nessa matéria.', ok: false,
      why: 'Errada. A conduta ética do médico é disciplinada pelo conselho profissional.' },
    { t: 'Disciplinam a conduta ética, não vinculando médicos contratados por empresas privadas do setor.', ok: false,
      why: 'Errada. Vinculam todo médico inscrito, qualquer que seja o vínculo.' },
    { t: 'Disciplinam a conduta ética, afastando a exigência contratual a responsabilidade disciplinar do médico.', ok: false,
      why: 'Errada. A responsabilidade pessoal pelo ato médico permanece.' },
    { t: 'Disciplinam a conduta ética e podem criar obrigações trabalhistas exigíveis das empresas contratantes.', ok: false,
      why: 'Errada. Disciplinam a conduta médica, não relações entre empresa e empregado.' }
  ],
  comentario: 'Resolução do conselho disciplina a conduta do médico; norma trabalhista disciplina a relação de emprego. Quando uma exigência da empresa colide com dever ético, cumprir não protege o médico da responsabilidade disciplinar.',
  pegadinha: '"Foi ordem da empresa" não é excludente de responsabilidade ética pelo ato médico.',
  refs: ['Resoluções do CFM', 'Código de Ética Médica'] },

{ id: 'q-7.7-041', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre exames toxicológicos com finalidade laboral, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem finalidade legítima, confirmação dos positivos e tratamento do resultado como dado sob sigilo.', ok: true,
      why: 'Correta. Não podem servir de triagem indiscriminada nem de fundamento isolado para punição.' },
    { t: 'Exigem finalidade legítima definida, dispensando o resultado positivo em triagem o exame confirmatório.', ok: false,
      why: 'Errada. Falsos-positivos são frequentes e a confirmação é indispensável.' },
    { t: 'Exigem finalidade legítima, podendo o resultado ir ao setor de pessoal com a substância detectada.', ok: false,
      why: 'Errada. É informação de saúde protegida por sigilo.' },
    { t: 'Exigem procedimento técnico adequado, podendo ser aplicados a qualquer função por decisão da empresa.', ok: false,
      why: 'Errada. Exige finalidade legítima ligada à segurança da atividade.' },
    { t: 'Exigem confirmação dos positivos, sem que o uso de medicamento prescrito interfira na interpretação.', ok: false,
      why: 'Errada. Diversos medicamentos interferem e a interpretação deve considerá-los.' }
  ],
  comentario: 'Toxicológico laboral: finalidade legítima, triagem seguida de confirmação, atenção a medicamentos que interferem, sigilo do resultado. Positivo de triagem tratado como conclusão é injustiça com aparência técnica.',
  pegadinha: 'Agir sobre o resultado de triagem sem confirmação penaliza quem tomou um medicamento prescrito.',
  refs: ['Resoluções do CFM sobre exames toxicológicos', 'Código de Ética Médica'] },

{ id: 'q-7.8-040', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre as bases legais para o tratamento de dados de saúde de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Apoiam-se em obrigação legal e na tutela da saúde, sendo o consentimento base frágil no emprego', ok: true,
      why: 'Correta. A assimetria da relação compromete a livre manifestação de vontade.' },
    { t: 'Apoiam-se preferencialmente no consentimento do empregado, colhido no momento da admissão ao emprego.', ok: false,
      why: 'Errada. A assimetria da relação torna o consentimento base frágil.' },
    { t: 'Apoiam-se em obrigação legal, recebendo os dados de saúde o mesmo tratamento dos demais dados pessoais.', ok: false,
      why: 'Errada. São categoria sensível, com regime mais restritivo.' },
    { t: 'Apoiam-se em obrigação legal e tutela da saúde, não sendo a anonimização aplicável a relatórios ocupacionais.', ok: false,
      why: 'Errada. Relatórios agregados e anonimizados são o formato adequado para a empresa.' },
    { t: 'Apoiam-se em obrigação legal, podendo a empresa controladora acessar todos os dados do serviço médico.', ok: false,
      why: 'Errada. O acesso é limitado pelo sigilo profissional e pela minimização.' }
  ],
  comentario: 'Dado de saúde é sensível: base legal preferencial em obrigação legal e tutela da saúde por profissional, não em consentimento — que na relação de emprego nasce comprometido. À empresa vai o agregado anonimizado.',
  pegadinha: 'Colher assinatura de consentimento na admissão dá aparência de legalidade a um tratamento que a base escolhida não sustenta.',
  refs: ['LGPD — arts. 7º e 11', 'Código de Ética Médica'] },

{ id: 'q-7.8-041', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o conteúdo do atestado de saúde ocupacional à luz da proteção de dados, é CORRETO afirmar:',
  alts: [
    { t: 'Deve conter riscos avaliados, exames realizados e conclusão de aptidão, sem diagnósticos', ok: true,
      why: 'Correta. Minimização: só o necessário à finalidade, que é a decisão sobre alocação.' },
    { t: 'Deve conter os riscos e trazer os resultados detalhados dos exames complementares realizados.', ok: false,
      why: 'Errada. Os resultados permanecem no prontuário sob guarda do médico.' },
    { t: 'Deve conter os exames e a conclusão, sendo obrigatório o diagnóstico para fundamentar restrições.', ok: false,
      why: 'Errada. Fundamenta-se a restrição funcionalmente, sem revelar diagnóstico.' },
    { t: 'Deve conter riscos e conclusão, não se aplicando a minimização a documentos exigidos por norma.', ok: false,
      why: 'Errada. Aplica-se ao conteúdo, mesmo quando o documento é obrigatório.' },
    { t: 'Deve conter riscos, exames e conclusão, sem necessidade de entregar via ao próprio trabalhador.', ok: false,
      why: 'Errada. A entrega de via ao trabalhador é exigência.' }
  ],
  comentario: 'No atestado vão riscos avaliados, exames feitos e conclusão de aptidão. Diagnóstico e resultado detalhado ficam no prontuário. É a minimização aplicada a um documento que a norma exige — e o trabalhador recebe a sua via.',
  pegadinha: 'Detalhar resultados no documento que circula pela empresa transforma exigência normativa em vazamento.',
  refs: ['LGPD — minimização', 'NR-7', 'Código de Ética Médica'] }

);
