/* Lote AO — 7.1 a 7.8, 6.1 a 6.4. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.1-100', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a caracterização de periculosidade e suas diferenças em relação à insalubridade, é CORRETO afirmar:',
  alts: [
    { t: 'A periculosidade decorre de risco acentuado de dano grave e imediato, lógica distinta da insalubridade.', ok: true,
      why: 'Correta. Uma trata de risco de evento agudo; a outra, de dano à saúde ao longo do tempo.' },
    { t: 'A periculosidade decorre de exposição a atividades de risco, na mesma lógica da insalubridade.', ok: false,
      why: 'Errada. Uma se apoia em risco de dano grave e imediato; a outra, em agente nocivo.' },
    { t: 'A periculosidade decorre de risco acentuado, dependendo sua caracterização de medição quantitativa.', ok: false,
      why: 'Errada. Caracteriza-se pela atividade ou operação descrita na norma.' },
    { t: 'A periculosidade decorre de risco de dano imediato, sendo a base de cálculo a mesma da insalubridade.', ok: false,
      why: 'Errada. As bases de cálculo dos dois adicionais são distintas.' },
    { t: 'A periculosidade decorre de risco acentuado, caracterizando-se também na exposição eventual e fortuita.', ok: false,
      why: 'Errada. A exposição eventual, por tempo extremamente reduzido, é excluída.' }
  ],
  comentario: 'Periculosidade: risco de dano grave e imediato, caracterizado pela atividade descrita na norma, sem medição — inflamáveis, explosivos, eletricidade, segurança pessoal, motociclistas. Insalubridade é outra lógica e outra base de cálculo.',
  pegadinha: 'Buscar medição quantitativa para caracterizar periculosidade aplica o método da insalubridade ao instituto errado.',
  refs: ['CLT — art. 193', 'NR-16', 'NR-15'] },

{ id: 'q-7.2-110', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o salário-maternidade e a proteção previdenciária à trabalhadora, é CORRETO afirmar:',
  alts: [
    { t: 'É devido também em aborto não criminoso, adoção e guarda judicial, com prazos próprios.', ok: true,
      why: 'Correta. É benefício próprio, com hipóteses que vão além do parto.' },
    { t: 'É devido exclusivamente no caso de parto, evento que dá origem ao afastamento indenizado.', ok: false,
      why: 'Errada. Alcança também aborto não criminoso, adoção e guarda para adoção.' },
    { t: 'É devido em várias hipóteses e tem os mesmos requisitos do benefício por incapacidade laborativa.', ok: false,
      why: 'Errada. São benefícios de natureza e requisitos distintos.' },
    { t: 'É devido no parto e no aborto não criminoso, não gerando a adoção direito ao benefício.', ok: false,
      why: 'Errada. Gera, com prazos previstos em lei.' },
    { t: 'É devido em várias hipóteses, equivalendo o afastamento por risco à gestação a esse benefício.', ok: false,
      why: 'Errada. O afastamento de atividade insalubre na gestação segue regra própria.' }
  ],
  comentario: 'Salário-maternidade alcança parto, aborto não criminoso, adoção e guarda para adoção — e não se confunde nem com benefício por incapacidade nem com o afastamento de atividade insalubre na gestação.',
  pegadinha: 'Misturar salário-maternidade com o afastamento de insalubre durante a gestação junta dois institutos com regras próprias.',
  refs: ['Lei nº 8.213/1991 — arts. 71 a 73', 'CLT — art. 394-A'] },

{ id: 'q-7.3-110', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o controle sanitário de estabelecimentos de saúde e a proteção dos trabalhadores desses serviços, é CORRETO afirmar:',
  alts: [
    { t: 'As exigências de estrutura, fluxos e processos protegem pacientes e trabalhadores ao mesmo tempo.', ok: true,
      why: 'Correta. As mesmas falhas atingem quem é atendido e quem trabalha.' },
    { t: 'As exigências de estrutura e fluxos visam à proteção dos pacientes atendidos no estabelecimento.', ok: false,
      why: 'Errada. Protegem também os trabalhadores do serviço.' },
    { t: 'As exigências protegem os dois grupos, sem relação dos fluxos de material contaminado com a equipe.', ok: false,
      why: 'Errada. O fluxo inadequado é fonte direta de exposição da equipe.' },
    { t: 'As exigências protegem os dois grupos, sendo a adequação de área física sem repercussão ocupacional.', ok: false,
      why: 'Errada. Espaço insuficiente aumenta risco de acidentes e de exposição.' },
    { t: 'As exigências protegem os dois grupos, sem que a fiscalização sanitária considere condições de trabalho.', ok: false,
      why: 'Errada. Elas integram as condições verificadas na inspeção.' }
  ],
  comentario: 'Em serviço de saúde, o requisito sanitário e o ocupacional convergem: ventilação, fluxo de material contaminado e área física protegem paciente e equipe pelas mesmas razões.',
  pegadinha: 'Separar exigência sanitária de exigência ocupacional trata como distintos dois efeitos da mesma falha.',
  refs: ['RDC sobre estabelecimentos de saúde', 'NR-32', 'Lei nº 8.080/1990'] },

{ id: 'q-7.4-110', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o trabalho em altura, é CORRETO afirmar:',
  alts: [
    { t: 'Exige análise de risco, permissão, proteção contra quedas, capacitação e plano de resgate.', ok: true,
      why: 'Correta. Deter a queda é metade da solução; a outra é resgatar rápido.' },
    { t: 'Exige o uso de cinturão de segurança com talabarte adequado ao ponto de ancoragem disponível.', ok: false,
      why: 'Errada. Análise de risco, permissão, capacitação e plano de resgate também integram.' },
    { t: 'Exige proteção contra quedas, podendo o resgate aguardar a chegada do serviço externo de emergência.', ok: false,
      why: 'Errada. A suspensão inerte prolongada tem risco próprio e exige resgate rápido.' },
    { t: 'Exige análise de risco e capacitação, que é única e não requer reciclagem periódica posterior.', ok: false,
      why: 'Errada. Há previsão de capacitação periódica.' },
    { t: 'Exige análise e capacitação, dispensando a avaliação de saúde quando o trabalhador é experiente.', ok: false,
      why: 'Errada. A avaliação de aptidão é exigência independente da experiência.' }
  ],
  comentario: 'Altura: análise de risco, permissão para o não rotineiro, sistema de retenção, capacitação com reciclagem, avaliação de aptidão e — o mais esquecido — plano de resgate, porque ficar pendurado tem risco próprio.',
  pegadinha: 'Deter a queda e não conseguir resgatar em minutos transforma o sistema de proteção em outra emergência.',
  refs: ['NR-35'] },

{ id: 'q-7.5-080', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o monitoramento da saúde do trabalhador no eSocial e o sigilo das informações, é CORRETO afirmar:',
  alts: [
    { t: 'Transmite a conclusão de aptidão e os exames realizados, sem diagnósticos nem resultados.', ok: true,
      why: 'Correta. Reproduz no digital o limite que separa o atestado do prontuário médico.' },
    { t: 'Transmite os exames realizados e deve conter os resultados dos exames complementares obtidos.', ok: false,
      why: 'Errada. Informa-se a realização, não os resultados.' },
    { t: 'Transmite aptidão e exames, reduzindo a transmissão digital as exigências de sigilo aplicáveis.', ok: false,
      why: 'Errada. As exigências permanecem e a segurança da informação se soma a elas.' },
    { t: 'Transmite a conclusão de aptidão, exigindo o sistema o diagnóstico para validar essa conclusão.', ok: false,
      why: 'Errada. A conclusão de aptidão não requer diagnóstico associado.' },
    { t: 'Transmite aptidão e exames, passando a responsabilidade pelo sigilo ao operador do sistema.', ok: false,
      why: 'Errada. O médico responsável mantém suas obrigações de sigilo.' }
  ],
  comentario: 'No eSocial vai o que já ia no atestado: exames realizados e conclusão de aptidão. Diagnóstico e resultado ficam no prontuário — o meio digital não muda essa fronteira, apenas acrescenta requisitos de segurança.',
  pegadinha: 'Supor que o campo do sistema pede diagnóstico leva a inserir dado sensível em base compartilhada.',
  refs: ['eSocial — evento de monitoramento da saúde', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-7.6-080', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a emissão de atestado de saúde ocupacional por médico que não realizou o exame, é CORRETO afirmar:',
  alts: [
    { t: 'É vedado atestar sobre condição não avaliada pessoalmente, e assinar sem examinar é infração grave.', ok: true,
      why: 'Correta. Aparece em serviços que produzem atestados em volume incompatível com o tempo.' },
    { t: 'É vedado atestar sem exame, salvo quando ele foi realizado por outro profissional da mesma equipe.', ok: false,
      why: 'Errada. Quem assina deve ter realizado a avaliação que atesta.' },
    { t: 'É prática irregular, recaindo a responsabilidade sobre a empresa que organizou o serviço médico.', ok: false,
      why: 'Errada. A responsabilidade pelo ato é pessoal de quem assina.' },
    { t: 'É vedado assinar sem examinar, sendo o volume de exames elemento irrelevante na apuração do fato.', ok: false,
      why: 'Errada. Volume incompatível com o tempo disponível é indício investigado.' },
    { t: 'É vedado assinar sem examinar, configurando apenas irregularidade administrativa, sem efeito ético.', ok: false,
      why: 'Errada. É infração ética, com repercussão disciplinar própria.' }
  ],
  comentario: 'Assinar exame que não se fez é infração ética pessoal — não da empresa, não do serviço. E o volume de atestados por hora é justamente o indício que a fiscalização e o conselho examinam.',
  pegadinha: 'Delegar o exame e assinar o documento não distribui a responsabilidade: ela é de quem assina.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM'] },

{ id: 'q-7.7-080', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o prontuário médico segundo as resoluções do conselho profissional, é CORRETO afirmar:',
  alts: [
    { t: 'É documento único do paciente, de elaboração obrigatória e legível, com prazos definidos de guarda e possibilidade de manutenção em meio eletrônico desde que atendidos requisitos de segurança e integridade.', ok: true,
      why: 'Correta. Único, obrigatório, legível, guardado por prazo definido, admitindo meio eletrônico com requisitos.' },
    { t: 'O prontuário pode ser fragmentado em documentos separados por especialidade.', ok: false,
      why: 'Errada. É documento único do paciente, ainda que com registros de vários profissionais.' },
    { t: 'A guarda em meio eletrônico dispensa requisitos específicos de segurança.', ok: false,
      why: 'Errada. Exige requisitos de segurança, integridade e autenticidade.' },
    { t: 'A elaboração do prontuário é facultativa em atendimentos ocupacionais.', ok: false,
      why: 'Errada. É obrigatória em qualquer atendimento médico.' },
    { t: 'Não há prazo definido para guarda de prontuários.', ok: false,
      why: 'Errada. Há prazos estabelecidos, particularmente relevantes em saúde ocupacional pela latência dos agravos.' }
  ],
  comentario: 'Prontuário: único por paciente, obrigatório, legível, guardado por prazo definido, eletrônico admitido com requisitos de segurança. Em saúde ocupacional a guarda longa é o que sustenta o nexo décadas depois.',
  pegadinha: 'Fragmentar o prontuário por serviço ou especialidade desfaz o histórico que dá sentido a cada registro.',
  refs: ['Resoluções do CFM sobre prontuário', 'Código de Ética Médica'] },

{ id: 'q-7.8-080', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o tratamento de dados biométricos de trabalhadores para controle de jornada e acesso, é CORRETO afirmar:',
  alts: [
    { t: 'São categoria sensível: exigem finalidade específica, proporcionalidade e alternativas avaliadas.', ok: true,
      why: 'Correta. Biometria comprometida não pode ser trocada como uma senha.' },
    { t: 'São dados pessoais comuns, tratados sob as mesmas regras aplicáveis aos demais dados do empregado.', ok: false,
      why: 'Errada. São expressamente categoria sensível.' },
    { t: 'São categoria sensível, dispensando a adoção de biometria a avaliação de alternativas menos invasivas.', ok: false,
      why: 'Errada. A proporcionalidade exige considerar meios menos invasivos.' },
    { t: 'São categoria sensível, sendo o consentimento do empregado base suficiente nesse contexto.', ok: false,
      why: 'Errada. A assimetria da relação de emprego fragiliza essa base.' },
    { t: 'São categoria sensível, com impacto de incidente equivalente ao de um vazamento de senhas.', ok: false,
      why: 'Errada. Biometria não pode ser substituída após comprometimento.' }
  ],
  comentario: 'Biometria é dado sensível e irreversível: senha vazada se troca, digital não. Exige finalidade específica, proporcionalidade e avaliação de alternativas — e o consentimento do empregado é base frágil.',
  pegadinha: 'Tratar incidente com biometria como equivalente a vazamento de senha subestima um dano que é permanente.',
  refs: ['LGPD — art. 5º, II e art. 11', 'Autoridade Nacional de Proteção de Dados'] },

{ id: 'q-6.1-120', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a responsabilidade pela elaboração e coordenação do programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'A coordenação cabe a médico do trabalho, e o programa decorre dos riscos do inventário.', ok: true,
      why: 'Correta. É documento vivo, revisto quando muda o risco, não peça anual repetida.' },
    { t: 'A coordenação pode ser atribuída a qualquer profissional de saúde com formação compatível.', ok: false,
      why: 'Errada. A coordenação é atribuição de médico do trabalho.' },
    { t: 'A coordenação cabe a médico do trabalho, revisto o programa na periodicidade máxima prevista.', ok: false,
      why: 'Errada. Mudança de risco ou de processo exige revisão antecipada.' },
    { t: 'A coordenação cabe a médico do trabalho, independendo a elaboração do inventário de riscos.', ok: false,
      why: 'Errada. O programa médico decorre dos riscos identificados.' },
    { t: 'A coordenação cabe a médico, sendo a responsabilidade técnica da empresa contratante do serviço.', ok: false,
      why: 'Errada. A responsabilidade técnica é pessoal do médico coordenador.' }
  ],
  comentario: 'Coordenação por médico do trabalho, com responsabilidade técnica pessoal, programa derivado do inventário e revisto quando o risco muda — não copiado de um ano para o outro.',
  pegadinha: 'Reeditar o programa anualmente sem revisar os riscos produz documento em dia e desatualizado.',
  refs: ['NR-7', 'NR-4', 'NR-1'] },

{ id: 'q-6.2-120', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre tecnologia assistiva no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Abrange recursos que ampliam funcionalidade e autonomia, indicados a partir da atividade concreta.', ok: true,
      why: 'Correta. Recurso escolhido sem a pessoa costuma virar equipamento parado.' },
    { t: 'Abrange equipamentos de alto custo, adquiridos para ampliar a autonomia do trabalhador na função.', ok: false,
      why: 'Errada. Inclui adaptações simples e de baixo custo, muitas vezes as mais eficazes.' },
    { t: 'Abrange recursos variados, cuja escolha cabe à empresa, sem participação do próprio trabalhador.', ok: false,
      why: 'Errada. A participação é determinante para a adequação e o uso efetivo.' },
    { t: 'Abrange recursos variados, cuja indicação parte do diagnóstico, e não da atividade a executar.', ok: false,
      why: 'Errada. Parte da atividade e da barreira concreta a ser superada.' },
    { t: 'Abrange recursos que ampliam autonomia, dispensando acompanhamento após o fornecimento do recurso.', ok: false,
      why: 'Errada. O ajuste após o uso real costuma ser necessário.' }
  ],
  comentario: 'Tecnologia assistiva parte da atividade e da barreira concreta, com a pessoa participando da escolha — e muita coisa eficaz é simples e barata. Fornecer sem acompanhar produz equipamento encostado.',
  pegadinha: 'Escolher pelo diagnóstico em vez da tarefa entrega o recurso errado com boa intenção.',
  refs: ['Lei nº 13.146/2015', 'CIF — OMS'] },

{ id: 'q-6.3-120', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o trabalhador em uso de medicamentos e a avaliação de aptidão, é CORRETO afirmar:',
  alts: [
    { t: 'Considera efeitos sobre atenção, coordenação e resposta ao ambiente, além da condição tratada.', ok: true,
      why: 'Correta. Restrição automática por uso de medicamento faz o trabalhador esconder o tratamento.' },
    { t: 'Considera a condição tratada, justificando o uso de qualquer medicamento contínuo restrição de função.', ok: false,
      why: 'Errada. A restrição decorre do efeito funcional avaliado, não do uso em si.' },
    { t: 'Considera efeitos sobre atenção, sem relevância os fármacos que aumentam sensibilidade a calor e sol.', ok: false,
      why: 'Errada. Fotossensibilizantes e os que afetam a termorregulação têm relevância direta.' },
    { t: 'Considera os efeitos funcionais, sem necessidade de orientar sobre interações com as exposições.', ok: false,
      why: 'Errada. Essa orientação é parte do cuidado ocupacional.' },
    { t: 'Considera os efeitos funcionais, devendo constar do atestado à empresa os medicamentos em uso.', ok: false,
      why: 'Errada. É informação clínica que permanece no prontuário.' }
  ],
  comentario: 'Avalia-se o efeito funcional do medicamento e a interação com as exposições — fotossensibilidade, termorregulação, atenção. Restringir por uso, em vez de por efeito, ensina o trabalhador a omitir o tratamento.',
  pegadinha: 'A restrição automática por psicotrópico ou anti-hipertensivo produz omissão, que é pior para a segurança.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.4-120', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a organização dos primeiros socorros em frentes de trabalho remotas, é CORRETO afirmar:',
  alts: [
    { t: 'Quanto maior o isolamento, maior a capacidade própria: pessoal, material, comunicação e evacuação.', ok: true,
      why: 'Correta. Em frente remota, o plano de evacuação precisa existir antes de ser necessário.' },
    { t: 'O padrão de primeiros socorros segue o mesmo modelo, independentemente da distância até a emergência.', ok: false,
      why: 'Errada. O tempo de resposta externo determina a capacidade própria exigida.' },
    { t: 'Quanto maior o isolamento, maior a estrutura, sendo os meios de comunicação item acessório.', ok: false,
      why: 'Errada. Sem comunicação confiável, não há acionamento nem evacuação.' },
    { t: 'Quanto maior o isolamento, maior a estrutura, podendo o plano de evacuação ser definido na ocorrência.', ok: false,
      why: 'Errada. Definir durante a emergência consome o tempo que faria diferença.' },
    { t: 'Quanto maior o isolamento, maior a estrutura, com material padronizado seja qual for o risco.', ok: false,
      why: 'Errada. Deve ser compatível com os riscos específicos, como peçonhentos ou químicos.' }
  ],
  comentario: 'Frente remota exige capacidade própria proporcional ao isolamento: gente treinada, material compatível com o risco, comunicação que funcione e evacuação planejada antes — não improvisada durante.',
  pegadinha: 'Kit padronizado em frente com risco de acidente ofídico não tem o que o caso vai exigir.',
  refs: ['NR-31', 'NR-1', 'NR-22'] }

);
