/* Lote H — 7.4, 7.2, 4.4, 2.3. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-7.4-040', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma construtora executa obra com trabalhadores próprios e de três subempreiteiras no mesmo canteiro. Sobre as obrigações de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Deve garantir as proteções coletivas e harmonizar os procedimentos entre todas as empresas atuantes.', ok: true,
      why: 'Correta. Quem controla o canteiro responde pelas condições que oferece a todos que nele trabalham.' },
    { t: 'Deve exigir documentos das subempreiteiras, que respondem isoladamente pelas condições do canteiro.', ok: false,
      why: 'Errada. As proteções coletivas do canteiro são responsabilidade de quem o organiza.' },
    { t: 'Deve garantir as proteções, esgotando-se a obrigação com a exigência de documentos das subempreiteiras.', ok: false,
      why: 'Errada. Verificar documento sem verificar a execução precede acidentes com terceirizados.' },
    { t: 'Deve garantir as proteções coletivas, não integrando os trabalhadores das subempreiteiras os indicadores.', ok: false,
      why: 'Errada. Excluí-los distorce o retrato do risco do canteiro.' },
    { t: 'Deve garantir as proteções, sendo a harmonização de procedimentos boa prática sem previsão normativa.', ok: false,
      why: 'Errada. Há previsão expressa de harmonização e de informação recíproca de riscos.' }
  ],
  comentario: 'Canteiro com múltiplas empresas: quem organiza responde pelas proteções coletivas e pela harmonização. Conferir papel das subempreiteiras não substitui verificar a execução — e os terceirizados contam nos indicadores.',
  pegadinha: 'A alegação de responsabilidade isolada de cada subempreiteira é a defesa padrão em acidentes de canteiro.',
  refs: ['NR-18', 'NR-1'] },

{ id: 'q-7.4-041', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a caracterização de insalubridade por agente para o qual não há limite de tolerância fixado em norma, é CORRETO afirmar:',
  alts: [
    { t: 'Há anexos de avaliação qualitativa, baseada em inspeção e na natureza da atividade.', ok: true,
      why: 'Correta. Nem toda insalubridade se caracteriza por medição, como nos agentes biológicos.' },
    { t: 'Há limites de tolerância para os agentes listados, sem os quais é impossível caracterizar insalubridade.', ok: false,
      why: 'Errada. A avaliação qualitativa existe justamente para essas hipóteses.' },
    { t: 'Há anexos de avaliação qualitativa, que dispensam a inspeção do local onde o trabalho ocorre.', ok: false,
      why: 'Errada. É na inspeção que se verifica a atividade efetivamente realizada.' },
    { t: 'Há anexos qualitativos, método sempre menos confiável do que a avaliação quantitativa por medição.', ok: false,
      why: 'Errada. Para determinados agentes, sobretudo biológicos, é o método adequado.' },
    { t: 'Há anexos qualitativos, eliminando sempre o fornecimento de proteção individual a caracterização.', ok: false,
      why: 'Errada. A neutralização precisa ser demonstrada, e para alguns agentes não ocorre.' }
  ],
  comentario: 'Insalubridade tem duas rotas: quantitativa, por medição contra limite, e qualitativa, pela natureza da atividade descrita em anexo — típica dos agentes biológicos. Ausência de limite numérico não impede a caracterização.',
  pegadinha: 'Supor que só há caracterização com medição elimina de saída todos os anexos qualitativos.',
  refs: ['NR-15'] },

{ id: 'q-7.4-042', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a capacitação em segurança e saúde no trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Deve ser compatível com os riscos, com registro, carga horária adequada e atualização periódica.', ok: true,
      why: 'Correta. Mudança de função ou de processo é gatilho para nova capacitação.' },
    { t: 'Deve ocorrer na admissão, momento em que o trabalhador conhece os riscos da função que assumirá.', ok: false,
      why: 'Errada. Há periodicidade prevista e gatilhos por mudança de risco.' },
    { t: 'Deve ser compatível com os riscos, podendo o material escrito substituir a capacitação supervisionada.', ok: false,
      why: 'Errada. Material informativo é apoio, não substituto do treinamento.' },
    { t: 'Deve ser compatível com os riscos, sendo dispensável o registro quando ministrada internamente.', ok: false,
      why: 'Errada. O registro é exigência independente de quem ministra.' },
    { t: 'Deve ser compatível com os riscos e buscada pelo próprio trabalhador, que responde por sua formação.', ok: false,
      why: 'Errada. É obrigação do empregador, sem custo para o trabalhador.' }
  ],
  comentario: 'Capacitação: compatível com o risco, por profissional capacitado, registrada, com carga adequada, periódica e refeita quando muda a função ou o processo. E custeada pelo empregador, como tudo em saúde e segurança.',
  pegadinha: 'Substituir treinamento por entrega de cartilha é o cumprimento formal mais comum e o menos eficaz.',
  refs: ['NR-1', 'NR-6'] },

{ id: 'q-7.2-040', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador teve benefício por incapacidade concedido como previdenciário, mas entende que se trata de doença ocupacional. Sobre as consequências da natureza do benefício, é CORRETO afirmar:',
  alts: [
    { t: 'A natureza acidentária dispensa carência, mantém o fundo de garantia e gera estabilidade.', ok: true,
      why: 'Correta. As diferenças são concretas e patrimoniais, e por isso a espécie importa.' },
    { t: 'A natureza do benefício concedido é irrelevante ao segurado, pois o valor mensal é o mesmo.', ok: false,
      why: 'Errada. Carência, fundo de garantia e estabilidade diferem substancialmente.' },
    { t: 'A natureza acidentária traz vantagens, sendo impossível a conversão da espécie após a concessão.', ok: false,
      why: 'Errada. Há vias administrativas e judiciais para o reconhecimento da natureza acidentária.' },
    { t: 'A natureza acidentária dispensa carência, existindo a garantia de emprego também nos comuns.', ok: false,
      why: 'Errada. A garantia decorre especificamente da natureza acidentária.' },
    { t: 'A natureza acidentária dispensa carência, ocorrendo o recolhimento do fundo em ambas as espécies.', ok: false,
      why: 'Errada. A manutenção do recolhimento é característica do afastamento acidentário.' }
  ],
  comentario: 'A espécie do benefício não é detalhe burocrático: acidentária dispensa carência, mantém o recolhimento do fundo de garantia e gera estabilidade de doze meses após a alta. É o que está em jogo na discussão de nexo.',
  pegadinha: '"O valor é o mesmo" ignora três consequências patrimoniais relevantes.',
  refs: ['Lei nº 8.213/1991 — arts. 20, 26, 118', 'Lei nº 8.036/1990'] },

{ id: 'q-7.2-041', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a documentação que instrui o requerimento de aposentadoria especial, é CORRETO afirmar:',
  alts: [
    { t: 'A empresa emite documento próprio descrevendo a exposição do trabalhador, lastreado em laudo técnico de condições ambientais elaborado por profissional habilitado — sendo a fidedignidade desse documento responsabilidade da empresa e dos profissionais que o subsidiam.', ok: true,
      why: 'Correta. O documento individual se apoia no laudo técnico, e informação inexata tem consequências previdenciárias e legais.' },
    { t: 'O documento é preenchido pelo próprio trabalhador com base em seu relato.', ok: false,
      why: 'Errada. É emitido pela empresa, com base em laudo técnico.' },
    { t: 'A emissão do documento é facultativa e depende de solicitação judicial.', ok: false,
      why: 'Errada. É obrigação da empresa, com prazos e situações definidos.' },
    { t: 'O documento pode descrever a exposição de forma genérica por setor.', ok: false,
      why: 'Errada. A descrição é individualizada por trabalhador, função e período.' },
    { t: 'A ausência do laudo técnico não compromete a validade do documento emitido.', ok: false,
      why: 'Errada. O documento sem lastro técnico perde a base que o sustenta.' }
  ],
  comentario: 'A cadeia é: laudo técnico de condições ambientais → documento individual de exposição → reconhecimento de tempo especial. Informação genérica ou sem lastro técnico prejudica o trabalhador décadas depois.',
  pegadinha: 'Descrição genérica por setor é a prática que mais compromete aposentadorias especiais.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999', 'eSocial — eventos de SST'] },

{ id: 'q-7.2-042', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a perícia médica previdenciária e a conclusão do médico assistente, é CORRETO afirmar:',
  alts: [
    { t: 'O atestado é elemento de instrução, mas a decisão cabe à perícia, que avalia a incapacidade.', ok: true,
      why: 'Correta. São funções distintas com objetos distintos; a divergência não desqualifica ninguém.' },
    { t: 'O atestado do assistente é elemento de instrução que vincula a decisão da perícia sobre a concessão.', ok: false,
      why: 'Errada. É elemento de instrução, não decisão.' },
    { t: 'O atestado é elemento juntado, devendo a perícia desconsiderar os documentos trazidos pelo segurado.', ok: false,
      why: 'Errada. Devem ser analisados e comentados na fundamentação.' },
    { t: 'O atestado é elemento de instrução, indicando a divergência entre os dois má-fé de um deles.', ok: false,
      why: 'Errada. Decorre da diferença de objeto entre assistência e avaliação de capacidade.' },
    { t: 'O atestado é elemento de instrução, não cabendo ao assistente descrever a repercussão funcional.', ok: false,
      why: 'Errada. É justamente a descrição funcional que torna o relatório útil à perícia.' }
  ],
  comentario: 'Assistente descreve doença e repercussão; perito decide sobre incapacidade para a atividade. Relatório assistencial que descreve função — o que o paciente consegue e não consegue fazer — é o que mais ajuda na perícia.',
  pegadinha: 'Interpretar a divergência como má-fé desqualifica um processo que é normal e esperado.',
  refs: ['Lei nº 8.213/1991', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-4.4-050', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Pedreiro apresenta lesões eczematosas em mãos e antebraços, com fissuras e áreas de ulceração, após anos de contato com cimento úmido. Sobre o quadro, é CORRETO afirmar:',
  alts: [
    { t: 'O cimento atua por dois mecanismos: irritação pelo pH alcalino e sensibilização ao cromo.', ok: true,
      why: 'Correta. Alcalinidade e cromo hexavalente juntos tornam a dermatose do cimento rebelde.' },
    { t: 'O cimento atua pela alcalinidade, causando irritação e queimadura, sem potencial sensibilizante.', ok: false,
      why: 'Errada. O cromo hexavalente presente como contaminante é sensibilizante reconhecido.' },
    { t: 'O cimento causa irritação e sensibilização, afastando a ulceração descrita a origem ocupacional.', ok: false,
      why: 'Errada. Queimadura química por cimento úmido é causa reconhecida de ulceração.' },
    { t: 'O cimento atua por dois mecanismos, sendo a luva de tecido proteção adequada ao contato úmido.', ok: false,
      why: 'Errada. Absorve e mantém o cimento em contato prolongado com a pele.' },
    { t: 'O cimento atua por dois mecanismos, sem efeito preventivo demonstrado da redução do teor de cromo.', ok: false,
      why: 'Errada. A redução do cromo hexavalente é medida preventiva reconhecida.' }
  ],
  comentario: 'Dermatose do cimento tem dois motores: pH alcalino, que queima, e cromo hexavalente, que sensibiliza. Por isso é grave e recidivante. E luva de tecido piora — absorve o cimento e prolonga o contato.',
  pegadinha: 'A luva de tecido é a proteção mais usada em canteiro e a que mais agrava a dermatose.',
  refs: ['Salim — Dermatoses Ocupacionais', 'NR-18'] },

{ id: 'q-4.4-051', tema: '4.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o diagnóstico diferencial entre dermatose ocupacional e dermatose comum agravada pelo trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A distinção muda o enquadramento do nexo, mas em ambos há relação com o trabalho.', ok: true,
      why: 'Correta. O enquadramento muda; a necessidade de afastar o agente, não.' },
    { t: 'A distinção importa, pois dermatose preexistente agravada não guarda relação com o trabalho.', ok: false,
      why: 'Errada. É hipótese expressa de doença relacionada ao trabalho por agravamento.' },
    { t: 'A distinção é conceitual e irrelevante do ponto de vista prático para o caso concreto avaliado.', ok: false,
      why: 'Errada. Ela orienta o enquadramento e a discussão de nexo.' },
    { t: 'A distinção muda o enquadramento, impedindo a presença de atopia qualquer reconhecimento de nexo.', ok: false,
      why: 'Errada. Atopia é fator de suscetibilidade e, quando muito, concausa.' },
    { t: 'A distinção muda o enquadramento, dispensando a dermatose comum agravada o afastamento do agente.', ok: false,
      why: 'Errada. Sem afastar o agente agravante o quadro persiste.' }
  ],
  comentario: 'Duas rotas de nexo em dermatologia ocupacional: causa necessária (dermatose ocupacional propriamente dita) e agravamento de dermatose comum. Muda o enquadramento; não muda a existência de relação com o trabalho nem a conduta.',
  pegadinha: 'Usar a preexistência ou a atopia para negar qualquer relação com o trabalho ignora a hipótese de agravamento.',
  refs: ['Salim — Dermatoses Ocupacionais', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-2.3-050', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador de indústria de baterias apresenta plumbemia elevada. O médico avalia a necessidade de afastamento. Sobre a conduta, é CORRETO afirmar:',
  alts: [
    { t: 'O afastamento segue protocolo, e o retorno depende também da correção das condições do setor.', ok: true,
      why: 'Correta. Devolver o trabalhador ao mesmo ambiente após a queda do indicador reproduz o ciclo.' },
    { t: 'O afastamento segue protocolo, sendo desnecessário enquanto não houver sintomas clínicos presentes.', ok: false,
      why: 'Errada. O indicador biológico existe para agir antes do sintoma.' },
    { t: 'O afastamento segue protocolo, podendo o retorno ocorrer assim que o indicador se normalizar.', ok: false,
      why: 'Errada. Sem correção das condições, a absorção excessiva se repete.' },
    { t: 'O afastamento segue protocolo, cabendo a decisão de afastar ao setor de recursos humanos.', ok: false,
      why: 'Errada. É decisão técnica médica, ainda que operacionalizada pela empresa.' },
    { t: 'O afastamento segue protocolo, permitindo a quelação manter o trabalhador exposto no tratamento.', ok: false,
      why: 'Errada. Tratamento não viabiliza continuidade de exposição não controlada.' }
  ],
  comentario: 'Afastar da exposição, acompanhar a queda do indicador e — condição essencial — só devolver depois de corrigir o que produziu a absorção. Retorno sem correção é garantia de repetição.',
  pegadinha: 'Condicionar o retorno apenas à normalização do indicador ignora metade do problema.',
  refs: ['Buschinelli — Toxicologia Ocupacional', 'NR-7', 'ACGIH — BEIs'] },

{ id: 'q-2.3-051', tema: '2.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o rótulo e a sinalização de produtos químicos no ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A rotulagem preventiva deve identificar o produto, os perigos, as precauções e os primeiros socorros de forma padronizada e compreensível, e produtos transferidos para recipientes menores devem ser igualmente identificados — recipiente sem identificação é risco por si.', ok: true,
      why: 'Correta. O fracionamento sem rotulagem é causa frequente de exposição e de atendimento sem saber a que agente.' },
    { t: 'Apenas os recipientes originais precisam de rotulagem.', ok: false,
      why: 'Errada. Recipientes de fracionamento também devem ser identificados.' },
    { t: 'O rótulo substitui integralmente a ficha de informações de segurança.', ok: false,
      why: 'Errada. São documentos complementares, com níveis de detalhe distintos.' },
    { t: 'A padronização internacional da rotulagem não se aplica no país.', ok: false,
      why: 'Errada. O sistema harmonizado de classificação e rotulagem foi adotado como referência.' },
    { t: 'A capacitação dos trabalhadores sobre a rotulagem é dispensável quando os rótulos são autoexplicativos.', ok: false,
      why: 'Errada. A compreensão dos pictogramas e frases padronizadas exige capacitação.' }
  ],
  comentario: 'Rótulo identifica e alerta; ficha detalha. Ambos necessários. E o ponto que mais falha na prática: recipiente fracionado sem identificação — que foi exatamente o cenário do trabalhador rural intoxicado por produto sem rótulo.',
  pegadinha: 'Limitar a rotulagem aos recipientes originais deixa sem identificação justamente os que o trabalhador manuseia.',
  refs: ['NR-26', 'Buschinelli — Toxicologia Ocupacional'] }

);
