/* Lote AT — fechamento das metas por tema: 5.x, 6.x, 7.x, 1.x. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-5.4-140', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a análise de documentos de exposição em perícia de doença ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser analisados criticamente quanto a coerência, data e correspondência com o processo descrito.', ok: true,
      why: 'Correta. Documento é prova a examinar, não verdade a acatar; divergência é achado a investigar.' },
    { t: 'Devem ser acatados sem análise crítica quando elaborados por profissional legalmente habilitado para tanto.', ok: false,
      why: 'Errada. A habilitação de quem elaborou não dispensa a análise do conteúdo.' },
    { t: 'Devem ser analisados criticamente, resolvendo-se sempre a favor do documento a divergência com o relato.', ok: false,
      why: 'Errada. É achado a investigar, considerando a data de elaboração e o processo real.' },
    { t: 'Devem ser analisados quanto à coerência interna, sendo irrelevante a data em que foram elaborados.', ok: false,
      why: 'Errada. Documento elaborado após o período em discussão tem valor limitado sobre ele.' },
    { t: 'Devem ser analisados criticamente, impedindo sua ausência qualquer conclusão pericial sobre a exposição.', ok: false,
      why: 'Errada. Outros elementos permitem a análise, e a falta de registro não prejudica o trabalhador.' }
  ],
  comentario: 'Documento de exposição se analisa: coerência, data, correspondência com o processo. Elaborado dez anos depois do período discutido, informa pouco sobre ele — e a divergência com o relato é pista, não ruído.',
  pegadinha: 'Acatar o documento por ser assinado por profissional habilitado dispensa a análise que a perícia existe para fazer.',
  refs: ['Resoluções do CFM sobre perícia médica', 'Lei nº 8.213/1991'] },

{ id: 'q-5.4-141', tema: '5.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vistoria do local de trabalho no âmbito de perícia judicial, é CORRETO afirmar:',
  alts: [
    { t: 'Deve considerar que o processo pode ter mudado, reconstituindo a época por documentos e testemunhos.', ok: true,
      why: 'Correta. Vistoriar hoje um posto reformado não informa sobre a exposição de dez anos atrás.' },
    { t: 'Deve retratar as condições atuais do posto, que refletem adequadamente o período em discussão no processo.', ok: false,
      why: 'Errada. Processos e instalações mudam, frequentemente após o início do litígio.' },
    { t: 'Deve considerar que o processo mudou, não auxiliando documentos e testemunhos a reconstituição pretérita.', ok: false,
      why: 'Errada. São as principais fontes quando o processo foi alterado.' },
    { t: 'Deve considerar que o processo pode ter mudado, dispensando a observação da atividade sendo executada.', ok: false,
      why: 'Errada. Observar a execução revela o trabalho real, distinto do descrito.' },
    { t: 'Deve reconstituir as condições da época, invalidando automaticamente o laudo a ausência de vistoria.', ok: false,
      why: 'Errada. Sua necessidade depende do objeto da perícia e das demais fontes disponíveis.' }
  ],
  comentario: 'A vistoria mostra hoje; a exposição em discussão é de ontem. Reconstituir exige documentos, testemunhos e vestígios — e observar a atividade sendo executada, não apenas o posto vazio.',
  pegadinha: 'Concluir pela exposição atual quando o setor foi reformado depois do afastamento avalia outra coisa.',
  refs: ['Código de Processo Civil', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-5.5-130', tema: '5.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação de capacidade em trabalhador com perda visual parcial, é CORRETO afirmar:',
  alts: [
    { t: 'Além da acuidade importam campo visual, profundidade, sensibilidade ao contraste e adaptação ao escuro.', ok: true,
      why: 'Correta. Acuidade normal convive com campo reduzido, o que muda tudo em algumas funções.' },
    { t: 'A acuidade visual isolada descreve a capacidade visual para o trabalho, por integrar as demais funções.', ok: false,
      why: 'Errada. Campo, profundidade e contraste podem ser determinantes.' },
    { t: 'Além da acuidade importam campo e contraste, não sendo a visão de profundidade relevante na indústria.', ok: false,
      why: 'Errada. É determinante em operação de equipamentos móveis e trabalho em altura.' },
    { t: 'Além da acuidade importam campo e profundidade, sem que a adaptação ao escuro influa no trabalho noturno.', ok: false,
      why: 'Errada. É parâmetro relevante em atividades noturnas e com variação de iluminação.' },
    { t: 'Além da acuidade importam outros parâmetros, implicando a perda visual monocular inaptidão a qualquer função.', ok: false,
      why: 'Errada. A avaliação é por função, considerando quais parâmetros ela exige.' }
  ],
  comentario: 'Visão para o trabalho não é só acuidade: campo, profundidade, contraste e adaptação ao escuro decidem em funções específicas. E perda em um olho não inabilita para tudo — avalia-se contra a exigência da função.',
  pegadinha: 'Medir acuidade e concluir deixa de fora o campo visual, que é o que importa em ponte rolante e empilhadeira.',
  refs: ['NR-7', 'Diretrizes de oftalmologia ocupacional'] },

{ id: 'q-5.6-120', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a articulação entre reabilitação profissional e a empresa de origem, é CORRETO afirmar:',
  alts: [
    { t: 'A permanência na origem tende a produzir melhores desfechos por preservar vínculo e conhecimento.', ok: true,
      why: 'Correta. A recusa da empresa em receber o reabilitado é barreira que precisa ser enfrentada.' },
    { t: 'A recolocação em nova empresa apresenta melhores resultados do que a permanência na empresa de origem.', ok: false,
      why: 'Errada. A permanência preserva vínculo e conhecimento do ambiente, favorecendo o desfecho.' },
    { t: 'A permanência na origem produz melhores desfechos, e a recusa da empresa não tem instrumento de enfrentamento.', ok: false,
      why: 'Errada. Há reserva legal de vagas e instrumentos de fiscalização e atuação.' },
    { t: 'A permanência na origem é preferível por razões contratuais, sendo irrelevante o conhecimento prévio do ambiente.', ok: false,
      why: 'Errada. Reduz o tempo de adaptação e facilita a alocação.' },
    { t: 'A permanência na origem produz melhores desfechos, não podendo a empresa ser envolvida no processo previdenciário.', ok: false,
      why: 'Errada. Sua participação é essencial para descrever funções e viabilizar a recolocação.' }
  ],
  comentario: 'Reabilitar dentro da empresa de origem preserva vínculo, tempo de casa e conhecimento do ambiente — e costuma dar melhor resultado. A recusa da empresa é barreira comum, com instrumentos legais para enfrentá-la.',
  pegadinha: 'Encaminhar direto para recolocação externa descarta a alternativa com maior chance de sucesso.',
  refs: ['Lei nº 8.213/1991 — arts. 89 a 93', 'Literatura sobre retorno ao trabalho'] },

{ id: 'q-5.3-120', tema: '5.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a concausalidade entre exposições de diferentes empregadores, é CORRETO afirmar:',
  alts: [
    { t: 'Exposições sucessivas podem somar-se, e a dificuldade de repartir a contribuição não afasta o nexo.', ok: true,
      why: 'Correta. Repartir responsabilidade é problema distinto de reconhecer o nexo.' },
    { t: 'Exposições sucessivas somam-se, considerando-se para o reconhecimento apenas a do último empregador.', ok: false,
      why: 'Errada. Exposições anteriores integram a determinação do agravo.' },
    { t: 'Exposições sucessivas somam-se, afastando o nexo a impossibilidade de repartir a contribuição de cada uma.', ok: false,
      why: 'Errada. São questões distintas: nexo de um lado, responsabilidade de outro.' },
    { t: 'Exposições sucessivas em empregadores distintos não se somam na determinação do quadro apresentado.', ok: false,
      why: 'Errada. A dose acumulada ao longo da vida laboral é o que importa em vários agravos.' },
    { t: 'Exposições sucessivas podem somar-se, dispensando a análise a reconstituição das exposições anteriores.', ok: false,
      why: 'Errada. É justamente ela que permite compreender a dose acumulada.' }
  ],
  comentario: 'Exposições em empregadores sucessivos se somam. Não saber repartir a contribuição é problema de responsabilidade — não de nexo, que se reconhece pela dose acumulada ao longo da vida laboral.',
  pegadinha: 'Olhar só o último empregador em agravo de dose acumulada avalia a menor parte da exposição.',
  refs: ['Lei nº 8.213/1991 — art. 21', 'Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-6.1-130', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre exames complementares no programa de controle médico, é CORRETO afirmar:',
  alts: [
    { t: 'Devem ser indicados conforme o risco e o efeito crítico do agente, com periodicidade por critério técnico.', ok: true,
      why: 'Correta. Exame sem relação com a exposição consome recurso e gera achado incidental.' },
    { t: 'Devem ser ampliados em número, pois a bateria maior aumenta proporcionalmente a proteção do trabalhador.', ok: false,
      why: 'Errada. Exame sem indicação não vigia a exposição e produz achado incidental.' },
    { t: 'Devem ser indicados conforme o efeito crítico, independendo a periodicidade do agente e do nível de exposição.', ok: false,
      why: 'Errada. Ambos determinam a periodicidade adequada.' },
    { t: 'Devem ser indicados conforme o risco, e os achados incidentais não geram custos nem consequências.', ok: false,
      why: 'Errada. Geram investigação, ansiedade e, por vezes, intervenções desnecessárias.' },
    { t: 'Devem ser indicados conforme o risco, podendo a escolha ser padronizada por pacote do prestador contratado.', ok: false,
      why: 'Errada. A indicação é técnica e decorre do risco, não da oferta do fornecedor.' }
  ],
  comentario: 'Exame complementar segue o efeito crítico do agente, com periodicidade por critério técnico. Pacote comercial padronizado vigia o que o fornecedor vende, não o que o trabalhador está exposto.',
  pegadinha: 'Adotar o pacote do prestador transfere a definição técnica do programa para quem o comercializa.',
  refs: ['NR-7', 'ACGIH — BEIs'] },

{ id: 'q-6.2-130', tema: '6.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o exame admissional de candidato com deficiência encaminhado à vaga reservada, é CORRETO afirmar:',
  alts: [
    { t: 'Verifica compatibilidade com adaptações razoáveis, e a inaptidão exige incompatibilidade insuperável.', ok: true,
      why: 'Correta. Sem essa exigência, o exame vira filtro que esvazia a reserva de vagas.' },
    { t: 'Verifica a compatibilidade com a função, bastando a constatação da deficiência para concluir pela inaptidão.', ok: false,
      why: 'Errada. É preciso demonstrar incompatibilidade insuperável por adaptação.' },
    { t: 'Verifica a compatibilidade com a função, não devendo as adaptações razoáveis ser consideradas na admissão.', ok: false,
      why: 'Errada. Integram a análise de compatibilidade.' },
    { t: 'Verifica a compatibilidade com a função, dispensando fundamentação a conclusão de inaptidão nesses casos.', ok: false,
      why: 'Errada. Exige fundamentação, dado o potencial discriminatório da conclusão.' },
    { t: 'Verifica a compatibilidade, não cabendo ao médico indicar quais adaptações viabilizariam a contratação.', ok: false,
      why: 'Errada. Indicá-las é contribuição central do serviço médico à inclusão.' }
  ],
  comentario: 'Inaptidão de candidato com deficiência exige demonstrar incompatibilidade que a adaptação não resolve — e o médico deve indicar quais adaptações viabilizariam a contratação, em vez de apenas negar.',
  pegadinha: 'Concluir pela deficiência em si transforma o exame admissional no mecanismo que anula a reserva de vagas.',
  refs: ['Lei nº 13.146/2015', 'Lei nº 8.213/1991 — art. 93', 'Lei nº 9.029/1995'] },

{ id: 'q-6.3-130', tema: '6.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a avaliação cardiovascular em trabalhadores de funções de alta exigência física, é CORRETO afirmar:',
  alts: [
    { t: 'Considera a estratificação individual e as exigências reais, incluindo esforço, calor e equipamentos.', ok: true,
      why: 'Correta. Roupa de proteção e calor somam carga cardiovascular relevante e mensurável.' },
    { t: 'Considera a estratificação de risco individual, independendo das exigências concretas da função exercida.', ok: false,
      why: 'Errada. É a exigência da função que define o que precisa ser avaliado.' },
    { t: 'Considera a estratificação e o esforço, sem que o equipamento de proteção altere a carga cardiovascular.', ok: false,
      why: 'Errada. Vestimenta e respirador aumentam a carga de forma significativa.' },
    { t: 'Considera as exigências reais da atividade, não tendo a estratificação de risco individual papel na decisão.', ok: false,
      why: 'Errada. É elemento central da decisão de aptidão.' },
    { t: 'Considera a estratificação e as exigências, devendo testes de esforço ser aplicados a todos indistintamente.', ok: false,
      why: 'Errada. A indicação decorre do risco individual e da exigência da função.' }
  ],
  comentario: 'Função de alta exigência física exige avaliar risco individual contra a exigência real — que inclui calor e o peso e a oclusão do equipamento de proteção. Teste de esforço se indica, não se distribui.',
  pegadinha: 'Avaliar o esforço da tarefa sem contar a roupa de proteção subestima a carga cardiovascular real.',
  refs: ['NR-7', 'Diretrizes de cardiologia ocupacional', 'NR-6'] },

{ id: 'q-6.4-130', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a resposta a emergência com múltiplas vítimas em ambiente de trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'A triagem direciona recursos limitados ao melhor resultado global, e precisa ser prevista e treinada antes.', ok: true,
      why: 'Correta. É decisão difícil que não pode ser improvisada na hora do evento.' },
    { t: 'A triagem segue a lógica do atendimento individual, priorizando sempre o caso clinicamente mais grave.', ok: false,
      why: 'Errada. Em múltiplas vítimas, prioriza-se o resultado global com recursos limitados.' },
    { t: 'A triagem direciona recursos limitados, podendo seus critérios ser definidos no momento do evento.', ok: false,
      why: 'Errada. Precisam estar previamente estabelecidos e treinados.' },
    { t: 'A triagem direciona recursos limitados, sendo secundária a comunicação com serviços externos nesse cenário.', ok: false,
      why: 'Errada. É determinante para mobilizar recursos e distribuir as vítimas.' },
    { t: 'A triagem direciona recursos limitados, podendo o registro de vítimas e condutas ser feito apenas ao final.', ok: false,
      why: 'Errada. O registro durante o atendimento evita perda de informação e duplicidade.' }
  ],
  comentario: 'Múltiplas vítimas inverte a lógica: prioriza-se o resultado global, não o caso mais grave. É decisão dura, que precisa estar definida e treinada antes — junto com comunicação externa e registro em tempo real.',
  pegadinha: 'Aplicar a lógica do atendimento individual em cenário de múltiplas vítimas consome os recursos no primeiro caso.',
  refs: ['Protocolos de atendimento a múltiplas vítimas', 'NR-1'] },

{ id: 'q-7.3-130', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a competência sanitária relativa a produtos para a saúde e equipamentos utilizados por trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'Alcançam também itens da assistência e da proteção, de modo que o produto irregular atinge os dois lados.', ok: true,
      why: 'Correta. Produto irregular na assistência atinge quem recebe e quem manuseia.' },
    { t: 'Alcançam produtos usados na assistência, sem relação com a proteção dos trabalhadores do serviço.', ok: false,
      why: 'Errada. Produtos da assistência e da proteção alcançam diretamente os trabalhadores.' },
    { t: 'Alcançam produtos para a saúde, não estando os equipamentos de proteção sujeitos a controle de conformidade.', ok: false,
      why: 'Errada. Estão sujeitos a certificação e controle de conformidade próprios.' },
    { t: 'Alcançam itens da assistência e da proteção, sendo o uso de produto sem registro irregularidade formal.', ok: false,
      why: 'Errada. A ausência de avaliação de segurança e eficácia repercute diretamente em saúde.' },
    { t: 'Alcançam itens da assistência, não integrando a notificação de eventos adversos as atribuições dos serviços.', ok: false,
      why: 'Errada. A notificação alimenta a vigilância pós-comercialização.' }
  ],
  comentario: 'Regularização sanitária de produto alcança o que se usa na assistência e na proteção — e produto irregular expõe paciente e trabalhador. Notificar evento adverso é o que alimenta a vigilância desses itens.',
  pegadinha: 'Separar controle de produto de saúde ocupacional ignora que ambos usam o mesmo item.',
  refs: ['Legislação sanitária de produtos para a saúde', 'NR-6', 'Lei nº 8.080/1990'] },

{ id: 'q-7.4-130', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os requisitos aplicáveis a caldeiras, vasos de pressão e tubulações, é CORRETO afirmar:',
  alts: [
    { t: 'Exigem inspeção periódica por habilitado, histórico documentado e capacitação dos operadores.', ok: true,
      why: 'Correta. É risco de evento raro e de consequência devastadora, muito além do operador.' },
    { t: 'Exigem inspeção periódica, que pode ser realizada por qualquer profissional da equipe de manutenção.', ok: false,
      why: 'Errada. Exige-se profissional legalmente habilitado.' },
    { t: 'Exigem inspeção periódica, sendo o histórico documentado dispensável quando não há registro de falhas.', ok: false,
      why: 'Errada. O histórico é exigência e sustenta as decisões de inspeção e reparo.' },
    { t: 'Exigem inspeção e histórico, sendo a capacitação do operador dispensável em equipamento automatizado.', ok: false,
      why: 'Errada. A capacitação específica permanece exigida.' },
    { t: 'Exigem inspeção e capacitação, alcançando o risco desses equipamentos apenas o operador direto.', ok: false,
      why: 'Errada. Falhas catastróficas atingem toda a área e os trabalhadores próximos.' }
  ],
  comentario: 'Caldeira e vaso de pressão: inspeção por profissional habilitado, histórico documentado e operador capacitado — inclusive em equipamento automatizado. O risco é de evento raro que atinge muito além do operador.',
  pegadinha: 'Automatizar não elimina a exigência de capacitação de quem opera e acompanha.',
  refs: ['NR-13'] },

{ id: 'q-7.5-100', tema: '7.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a qualidade da informação transmitida nos eventos de saúde e segurança e seus efeitos de longo prazo, é CORRETO afirmar:',
  alts: [
    { t: 'Ela forma histórico individual que sustentará pedidos futuros, e o erro de hoje nega direito depois.', ok: true,
      why: 'Correta. O dano do erro aparece muito depois de quem o cometeu ter saído da empresa.' },
    { t: 'Ela forma histórico individual, podendo os erros ser corrigidos a qualquer tempo e sem prejuízo ao trabalhador.', ok: false,
      why: 'Errada. A correção tardia é difícil e nem sempre viável.' },
    { t: 'Ela documenta a situação do vínculo atual, com efeito restrito ao período em que ele esteve vigente.', ok: false,
      why: 'Errada. Compõe o histórico que sustenta reconhecimentos futuros.' },
    { t: 'Ela forma histórico individual, sendo a conferência periódica das informações medida sem utilidade prática.', ok: false,
      why: 'Errada. É o que permite identificar e corrigir inconsistências enquanto ainda é possível.' },
    { t: 'Ela forma histórico individual de interesse da empresa, sem interesse direto do trabalhador em sua qualidade.', ok: false,
      why: 'Errada. É delas que dependerá o reconhecimento de tempo especial e de nexo no futuro.' }
  ],
  comentario: 'A informação transmitida hoje é a prova de amanhã: sustenta aposentadoria especial e discussão de nexo décadas à frente. Erro cometido agora aparece como negativa de direito quando ninguém mais pode corrigi-lo.',
  pegadinha: 'Tratar o preenchimento como obrigação do mês perde de vista que ele constrói um histórico de trinta anos.',
  refs: ['eSocial — eventos de SST', 'Lei nº 8.213/1991'] },

{ id: 'q-7.6-100', tema: '7.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a atuação do médico do trabalho diante de condição de risco grave identificada no ambiente, é CORRETO afirmar:',
  alts: [
    { t: 'Cabe comunicar formalmente, registrar a comunicação e, se persistir, acionar as autoridades competentes.', ok: true,
      why: 'Correta. Comunicação verbal não registrada não existe quando o acidente acontece.' },
    { t: 'Cabe comunicar a condição à chefia imediata, satisfazendo a comunicação verbal o dever do profissional.', ok: false,
      why: 'Errada. Sem registro, não há como demonstrar o cumprimento do dever.' },
    { t: 'Cabe comunicar formalmente e registrar, sendo vedado ao médico contratado acionar as autoridades.', ok: false,
      why: 'Errada. É conduta legítima e prevista diante de risco não corrigido.' },
    { t: 'Cabe registrar os atendimentos, ficando a identificação de risco grave fora do escopo do médico do trabalho.', ok: false,
      why: 'Errada. O conhecimento do ambiente e a comunicação de riscos integram sua atuação.' },
    { t: 'Cabe comunicar formalmente e registrar, encerrando-se a responsabilidade se a condição persistir depois.', ok: false,
      why: 'Errada. A persistência é justamente o que motiva o acionamento das autoridades.' }
  ],
  comentario: 'Risco grave identificado: comunicar formalmente, registrar e, se persistir, acionar as autoridades. O registro é o que demonstra o cumprimento do dever — e é o que sobra quando o acidente ocorre.',
  pegadinha: 'A comunicação verbal em reunião não deixa rastro e não protege ninguém depois.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM', 'NR-1'] },

{ id: 'q-7.7-100', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a responsabilidade técnica em serviços de saúde ocupacional, é CORRETO afirmar:',
  alts: [
    { t: 'Responde pela adequação dos procedimentos sob sua coordenação, o que exige conhecimento efetivo do serviço.', ok: true,
      why: 'Correta. Responsabilidade técnica de assinatura, sem acompanhamento, é o cenário de maior exposição.' },
    { t: 'É atribuição de caráter formal, exigida para registro do serviço, sem implicações práticas para o profissional.', ok: false,
      why: 'Errada. Implica responder pela adequação dos procedimentos do serviço.' },
    { t: 'Responde pela adequação dos procedimentos, sendo admissível assumi-la em serviço que não se acompanha.', ok: false,
      why: 'Errada. É prática de risco ético e legal.' },
    { t: 'Responde pelos procedimentos do serviço, alcançando a responsabilidade apenas os atos praticados pessoalmente.', ok: false,
      why: 'Errada. Alcança os procedimentos e a qualidade do serviço sob coordenação.' },
    { t: 'Responde pela adequação dos procedimentos, sem dever de verificar as condições de trabalho da própria equipe.', ok: false,
      why: 'Errada. Condições inadequadas comprometem a qualidade dos atos pelos quais responde.' }
  ],
  comentario: 'Responsabilidade técnica é responder pelo serviço, não emprestar o nome. Alcança os procedimentos sob coordenação — e as condições em que a própria equipe trabalha, porque delas depende a qualidade dos atos.',
  pegadinha: 'Assinar responsabilidade técnica de serviço que não se visita é o arranjo mais frequente e o de maior exposição.',
  refs: ['Resoluções do CFM', 'Código de Ética Médica'] },

{ id: 'q-7.8-100', tema: '7.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o uso de sistemas de monitoramento e produtividade que coletam dados de trabalhadores, é CORRETO afirmar:',
  alts: [
    { t: 'A coleta exige finalidade específica, informação e proporcionalidade, e é também risco psicossocial.', ok: true,
      why: 'Correta. Monitoramento contínuo e granular tem efeitos documentados sobre saúde mental.' },
    { t: 'A coleta exige finalidade específica e proporcionalidade, sendo assunto exclusivo de proteção de dados.', ok: false,
      why: 'Errada. Tem efeitos sobre saúde mental e integra a avaliação de riscos psicossociais.' },
    { t: 'A coleta exige finalidade específica, sem necessidade de informar o trabalhador sobre os dados coletados.', ok: false,
      why: 'Errada. A transparência sobre a coleta é exigência.' },
    { t: 'A coleta decorre do poder diretivo do empregador, que autoriza monitoramento de qualquer extensão.', ok: false,
      why: 'Errada. A proporcionalidade e a privacidade limitam a extensão do monitoramento.' },
    { t: 'A coleta exige finalidade e proporcionalidade, não podendo dados de produtividade revelar dados de saúde.', ok: false,
      why: 'Errada. Padrões de pausa, ritmo e ausência podem revelá-los, o que exige cautela adicional.' }
  ],
  comentario: 'Monitoramento de produtividade é duas coisas ao mesmo tempo: tratamento de dados com finalidade e proporcionalidade, e fator psicossocial com efeito documentado. E padrões de pausa podem revelar condição de saúde.',
  pegadinha: 'Tratar o tema apenas como conformidade de dados ignora o que o monitoramento contínuo faz com quem é monitorado.',
  refs: ['LGPD', 'NR-1 — fatores psicossociais', 'OIT'] },

{ id: 'q-7.2-130', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a relação entre reconhecimento de doença ocupacional e as obrigações da empresa, é CORRETO afirmar:',
  alts: [
    { t: 'Repercute em estabilidade, fundo de garantia no afastamento, indicadores de acidentalidade e alíquota.', ok: true,
      why: 'Correta. Há consequências econômicas concretas, e é por isso que a análise sofre pressão.' },
    { t: 'Repercute na esfera previdenciária do trabalhador, sem gerar repercussões econômicas para a empresa.', ok: false,
      why: 'Errada. Alcança estabilidade, fundo de garantia, indicadores e alíquota.' },
    { t: 'Repercute em estabilidade e fundo de garantia, sem afetar os indicadores de acidentalidade da empresa.', ok: false,
      why: 'Errada. Doenças ocupacionais integram esses indicadores.' },
    { t: 'Repercute economicamente, sendo a pressão daí decorrente justificativa aceitável para modular a conclusão.', ok: false,
      why: 'Errada. A conclusão é técnica e não se modula por consequência econômica.' },
    { t: 'Repercute em estabilidade e indicadores, não considerando a alíquota por acidentalidade as doenças ocupacionais.', ok: false,
      why: 'Errada. Elas compõem o desempenho que determina a variação da alíquota.' }
  ],
  comentario: 'Reconhecer doença ocupacional mexe em estabilidade, fundo de garantia, indicadores e alíquota — o que explica a pressão sobre a análise. E é exatamente por isso que a conclusão precisa ser estritamente técnica.',
  pegadinha: 'Entender por que existe pressão é diferente de aceitá-la como critério de conclusão.',
  refs: ['Lei nº 8.213/1991 — arts. 21-A e 118', 'Lei nº 10.666/2003', 'Lei nº 8.036/1990'] }

);
