/* Lote Q — 1.4, 1.6, 1.7, 1.9, 1.10, 2.7, 4.10, 2.8, 2.5, 1.5, 1.8. AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-1.4-060', tema: '1.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise de custos em saúde e segurança do trabalho apresentada à direção de uma empresa, é CORRETO afirmar:',
  alts: [
    { t: 'Os custos indiretos — parada, substituição, investigação, perda de qualidade — costumam superar os diretos.', ok: true,
      why: 'Correta. É o argumento econômico que sustenta o investimento em prevenção.' },
    { t: 'Os custos diretos, com despesa médica e afastamento, representam a maior parte do prejuízo do acidente.', ok: false,
      why: 'Errada. Os indiretos costumam ser maiores e são os menos contabilizados.' },
    { t: 'Os custos indiretos superam os diretos, devendo o investimento em prevenção ser justificado por obrigação legal.', ok: false,
      why: 'Errada. Há justificativa econômica e ética; depender só da lei fragiliza o programa.' },
    { t: 'Os custos indiretos superam os diretos, não representando a alíquota variável por acidentalidade custo relevante.', ok: false,
      why: 'Errada. A variação por desempenho em acidentalidade tem impacto financeiro direto.' },
    { t: 'Os custos indiretos superam os diretos, substituindo a análise de custos os indicadores de saúde do programa.', ok: false,
      why: 'Errada. São dimensões complementares, e a econômica não mede proteção.' }
  ],
  comentario: 'Custo indireto supera o direto e é o que raramente aparece na planilha. Somado ao efeito da alíquota variável por acidentalidade, forma o argumento econômico da prevenção — que complementa, mas não substitui, o indicador de saúde.',
  pegadinha: 'Contabilizar apenas a despesa médica faz a prevenção parecer cara e o acidente, barato.',
  refs: ['OIT — custos dos acidentes de trabalho', 'Legislação sobre alíquotas de acidentalidade'] },

{ id: 'q-1.6-060', tema: '1.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a intersetorialidade nas ações de saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Decorre de competências distribuídas entre saúde, trabalho, previdência, ambiente e ministério público.', ok: true,
      why: 'Correta. Cada setor vê um pedaço; sem articulação, nenhum vê o conjunto.' },
    { t: 'Decorre da organização do sistema de saúde, campo de competência exclusiva para esses agravos.', ok: false,
      why: 'Errada. As competências são compartilhadas entre vários setores.' },
    { t: 'Decorre de competências distribuídas, sendo a articulação desejável sem alterar resultados concretos.', ok: false,
      why: 'Errada. Ações articuladas produzem alcance que nenhum setor obtém isoladamente.' },
    { t: 'Decorre de competências entre saúde, trabalho e previdência, sem atuação do ministério público no campo.', ok: false,
      why: 'Errada. Atua por inquéritos, termos de ajustamento de conduta e ações civis públicas.' },
    { t: 'Decorre de competências entre saúde, trabalho e previdência, sem interface da área ambiental com o campo.', ok: false,
      why: 'Errada. Contaminações atingem trabalhadores e comunidade do entorno simultaneamente.' }
  ],
  comentario: 'Saúde, trabalho, previdência, ambiente e ministério público têm competências que se cruzam. A fragmentação entre eles é o que faz o mesmo evento aparecer parcialmente em cada base e integralmente em nenhuma.',
  pegadinha: 'Tratar a intersetorialidade como recomendação retórica ignora que é dela que depende a efetividade das ações.',
  refs: ['PNSTT', 'Lei nº 8.080/1990'] },

{ id: 'q-1.7-060', tema: '1.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre os princípios do Sistema Único de Saúde aplicados à saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'A integralidade implica articular assistência, vigilância e promoção em torno de um mesmo sujeito', ok: true,
      why: 'Correta. Atender o adoecido sem intervir no ambiente é cumprimento parcial do princípio.' },
    { t: 'A integralidade se refere à oferta de todos os níveis de complexidade assistencial ao trabalhador.', ok: false,
      why: 'Errada. Abrange também a articulação entre assistência, prevenção e vigilância.' },
    { t: 'A integralidade articula as dimensões, e a equidade significa oferecer exatamente o mesmo a todos.', ok: false,
      why: 'Errada. Equidade é tratar desigualmente os desiguais conforme a necessidade.' },
    { t: 'A integralidade articula as dimensões, e a universalidade exclui quem tem cobertura de plano privado.', ok: false,
      why: 'Errada. O direito é universal, independentemente de cobertura privada.' },
    { t: 'A integralidade articula assistência e vigilância, não se aplicando o controle social a esse campo.', ok: false,
      why: 'Errada. É princípio expresso e tem instâncias próprias nesse campo.' }
  ],
  comentario: 'Integralidade articula assistência, vigilância e promoção — tratar sem intervir no ambiente é cumprimento pela metade. Equidade é responder por necessidade, não oferecer o mesmo a todos. Universalidade não exclui quem tem plano.',
  pegadinha: 'Reduzir integralidade a níveis de complexidade perde justamente a articulação com a vigilância.',
  refs: ['Lei nº 8.080/1990', 'PNSTT'] },

{ id: 'q-1.9-060', tema: '1.9', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o preenchimento das fichas de notificação de agravos relacionados ao trabalho, é CORRETO afirmar:',
  alts: [
    { t: 'Ocupação, atividade econômica e situação no mercado permitem a análise por setor e por tipo de vínculo', ok: true,
      why: 'Correta. Sem esses campos a notificação entra na contagem e não diz onde intervir.' },
    { t: 'Ocupação e atividade econômica compõem a ficha, sendo opcional o preenchimento do campo de ocupação.', ok: false,
      why: 'Errada. É o campo que dá sentido à notificação em saúde do trabalhador.' },
    { t: 'Ocupação e atividade econômica permitem a análise, devendo a ficha ser preenchida só em casos confirmados.', ok: false,
      why: 'Errada. A notificação se faz por suspeita.' },
    { t: 'Ocupação permite a análise por setor, não devendo notificações de informais registrar a atividade econômica.', ok: false,
      why: 'Errada. É justamente o dado que dá visibilidade ao trabalho informal.' },
    { t: 'Ocupação e vínculo permitem a análise, sem que a qualidade do preenchimento afete a base de dados.', ok: false,
      why: 'Errada. Campos em branco produzem base incapaz de orientar ação.' }
  ],
  comentario: 'Ocupação, atividade econômica e situação no mercado de trabalho são o coração da ficha. Notificação registrada com esses campos em branco cumpre a obrigação e não serve à vigilância.',
  pegadinha: 'Contar notificações emitidas como medida de qualidade da vigilância ignora o preenchimento efetivo.',
  refs: ['SINAN — fichas de agravos relacionados ao trabalho', 'Ministério da Saúde'] },

{ id: 'q-1.10-060', tema: '1.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a promoção da saúde em ambientes de trabalho segundo o modelo proposto pela Organização Mundial da Saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Abrange o ambiente físico, o ambiente psicossocial, os recursos pessoais e a participação na comunidade', ok: true,
      why: 'Correta. São quatro avenidas de ação, não apenas mudança de hábito individual.' },
    { t: 'Concentra-se nos hábitos individuais de saúde, atuando sobre alimentação, atividade física e tabagismo.', ok: false,
      why: 'Errada. Ambiente físico e psicossocial são dois de seus quatro planos.' },
    { t: 'Abrange quatro planos de ação, sendo a participação dos trabalhadores etapa opcional do processo.', ok: false,
      why: 'Errada. É elemento estruturante em todas as etapas.' },
    { t: 'Abrange quatro planos de ação, sem que a liderança da alta direção influencie os resultados obtidos.', ok: false,
      why: 'Errada. O compromisso da direção é apontado como condição de sustentabilidade.' },
    { t: 'Abrange ambiente físico, psicossocial e recursos pessoais, sem incluir a relação com a comunidade.', ok: false,
      why: 'Errada. Constitui um dos quatro planos de ação do modelo.' }
  ],
  comentario: 'Quatro planos: ambiente físico, ambiente psicossocial, recursos pessoais de saúde e comunidade — com participação dos trabalhadores e compromisso da direção. Campanha de hábito isolada cobre um quarto do modelo, na melhor das hipóteses.',
  pegadinha: 'Programas de promoção que só oferecem palestra e ginástica ficam presos ao plano dos recursos pessoais.',
  refs: ['OMS — Healthy Workplace Framework'] },

{ id: 'q-2.7-060', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a avaliação da exposição ocupacional ao ruído conforme as normas de higiene ocupacional de referência técnica, é CORRETO afirmar:',
  alts: [
    { t: 'Considera o nível equivalente ao longo de toda a jornada, e o ruído de impacto segue procedimento próprio', ok: true,
      why: 'Correta. O incremento de duplicação de dose difere entre referências e altera o resultado.' },
    { t: 'Considera o nível equivalente da jornada, seguindo ruído contínuo e de impacto o mesmo procedimento.', ok: false,
      why: 'Errada. O ruído de impacto tem procedimento e critérios próprios.' },
    { t: 'Considera o nível equivalente, sendo o incremento de duplicação de dose idêntico em todas as referências.', ok: false,
      why: 'Errada. Há diferença entre referências, com efeito direto sobre a dose calculada.' },
    { t: 'Considera o nível de ruído, caracterizando a medição pontual com decibelímetro a exposição da jornada.', ok: false,
      why: 'Errada. Exposições variáveis exigem dosimetria ao longo da jornada.' },
    { t: 'Considera o nível equivalente na jornada, sendo dispensável o registro das atividades durante a medição.', ok: false,
      why: 'Errada. Sem ele o resultado não se interpreta nem se reproduz.' }
  ],
  comentario: 'Ruído: nível equivalente na jornada por dosimetria, procedimento próprio para impacto, e atenção ao incremento de duplicação de dose — que difere entre referências e muda o número final. Medição pontual não representa jornada variável.',
  pegadinha: 'Comparar resultados obtidos com incrementos de duplicação diferentes é comparar números que não se equivalem.',
  refs: ['NHO 01 — Fundacentro', 'NR-15 — Anexos 1 e 2', 'ACGIH'] },

{ id: 'q-4.10-060', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a vacinação contra hepatite B em trabalhadores de saúde, é CORRETO afirmar:',
  alts: [
    { t: 'A verificação da resposta sorológica após o esquema é recomendada, pois identifica não respondedores.', ok: true,
      why: 'Correta. Saber quem não respondeu é o que permite decidir corretamente na exposição.' },
    { t: 'A conclusão do esquema vacinal completo dispensa qualquer verificação de resposta nesse grupo exposto.', ok: false,
      why: 'Errada. Em grupo de risco, a verificação é recomendada.' },
    { t: 'A verificação identifica não respondedores, que devem ser afastados definitivamente da assistência.', ok: false,
      why: 'Errada. A conduta é revacinação e, persistindo, manejo específico na exposição.' },
    { t: 'A verificação é recomendada, dispensando a vacinação as precauções padrão com material biológico.', ok: false,
      why: 'Errada. Protege contra um agente e não cobre os demais.' },
    { t: 'A verificação é recomendada, protegendo a vacina contra hepatite B igualmente contra a hepatite C.', ok: false,
      why: 'Errada. Não há vacina disponível contra hepatite C.' }
  ],
  comentario: 'Hepatite B em profissional de saúde: esquema completo mais verificação de resposta, porque o não respondedor precisa de conduta diferente no acidente. E não existe vacina para hepatite C — o que reforça que a barreira é insubstituível.',
  pegadinha: 'A vacina cobre um agente e é frequentemente lida como se cobrisse o risco biológico inteiro.',
  refs: ['NR-32', 'Programa Nacional de Imunizações', 'Protocolos de exposição a material biológico'] },

{ id: 'q-2.8-060', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a seleção de respiradores para atmosferas com deficiência de oxigênio ou concentração imediatamente perigosa à vida e à saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Exige-se respirador de adução de ar ou autônomo, pois os filtros dependem de haver oxigênio suficiente', ok: true,
      why: 'Correta. Filtro não gera oxigênio nem sustenta concentrações extremas; errar aqui é fatal.' },
    { t: 'Exige-se respirador com filtro químico adequado ao contaminante presente na atmosfera deficiente.', ok: false,
      why: 'Errada. Filtro não supre oxigênio; a atmosfera precisa ser respirável.' },
    { t: 'Exige-se respirador de adução de ar, não influenciando a concentração do contaminante essa escolha.', ok: false,
      why: 'Errada. É determinante, junto do fator de proteção requerido.' },
    { t: 'Exige-se respirador autônomo, o que dispensa a avaliação prévia da atmosfera no espaço confinado.', ok: false,
      why: 'Errada. A avaliação prévia e contínua da atmosfera é exigência independente.' },
    { t: 'Exige-se respirador de adução, sendo dispensável verificar o oxigênio quando não há odor perceptível.', ok: false,
      why: 'Errada. Deficiência de oxigênio não tem odor nem qualquer aviso sensorial.' }
  ],
  comentario: 'Deficiência de oxigênio ou atmosfera imediatamente perigosa exige ar fornecido ou equipamento autônomo — filtro não cria oxigênio. E deficiência de oxigênio é inodora: só a medição informa.',
  pegadinha: 'Confiar na ausência de odor em espaço confinado é a sequência que produz vítimas e depois socorristas vitimados.',
  refs: ['NR-33', 'NR-6', 'Programa de Proteção Respiratória — Fundacentro'] },

{ id: 'q-2.5-060', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a priorização de ações em um programa de gerenciamento de riscos ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'Combina severidade e probabilidade, mas o efeito catastrófico exige tratamento mesmo quando improvável', ok: true,
      why: 'Correta. A matriz orienta; não pode adiar o catastrófico nem o trivialmente corrigível.' },
    { t: 'Combina severidade e probabilidade, devendo seguir estritamente a ordem numérica da matriz de risco.', ok: false,
      why: 'Errada. A matriz é ferramenta de apoio, não regra que sobrepõe o julgamento técnico.' },
    { t: 'Combina severidade e probabilidade, podendo os riscos improváveis de alta severidade ser postergados.', ok: false,
      why: 'Errada. São exatamente os que produzem eventos catastróficos.' },
    { t: 'Combina severidade e probabilidade, dispensando o plano de ação prazos e responsáveis definidos.', ok: false,
      why: 'Errada. Sem prazo e responsável, o plano não se implementa nem se cobra.' },
    { t: 'Combina severidade e probabilidade, sendo opcional a verificação de eficácia das medidas adotadas.', ok: false,
      why: 'Errada. Sem verificação, não se sabe se o risco foi efetivamente reduzido.' }
  ],
  comentario: 'Severidade e probabilidade orientam a fila, mas duas coisas furam a fila: o catastrófico de baixa probabilidade e o que se corrige hoje com pouco esforço. Plano sem prazo e responsável não vira ação, e sem verificação de eficácia não se sabe se funcionou.',
  pegadinha: 'Seguir a matriz ao pé da letra empurra o evento raro e catastrófico para o fim da lista.',
  refs: ['NR-1 — gerenciamento de riscos ocupacionais', 'ISO 45001'] },

{ id: 'q-1.5-060', tema: '1.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre indicadores proativos e reativos em gestão de segurança e saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Os reativos medem o que já ocorreu; os proativos medem ações preventivas e condições do ambiente.', ok: true,
      why: 'Correta. Um programa avaliado só por indicadores reativos aprende depois do dano.' },
    { t: 'Os reativos medem taxas de acidentes e são suficientes para avaliar um sistema de gestão em operação.', ok: false,
      why: 'Errada. Informam apenas sobre o que já falhou.' },
    { t: 'Os reativos medem o ocorrido, demonstrando a ausência de acidentes no período um sistema eficaz.', ok: false,
      why: 'Errada. Pode refletir acaso, subnotificação ou baixa exposição no período.' },
    { t: 'Os reativos medem o ocorrido, não podendo os indicadores proativos ser quantificados objetivamente.', ok: false,
      why: 'Errada. São quantificáveis, como percentual de ações concluídas no prazo.' },
    { t: 'Os proativos medem ações preventivas, sendo a premiação por ausência de acidentes estratégia recomendada.', ok: false,
      why: 'Errada. Induz subnotificação e esconde a informação de que o sistema depende.' }
  ],
  comentario: 'Reativo mede o dano ocorrido; proativo mede a prevenção em curso. Zero acidente no trimestre pode ser sorte ou silêncio — e premiar ausência de acidente é a forma mais eficaz de comprar subnotificação.',
  pegadinha: 'A campanha de dias sem acidente é popular e produz o incentivo errado para quem se acidenta.',
  refs: ['ISO 45001', 'OIT — indicadores de desempenho em SST'] },

{ id: 'q-1.8-060', tema: '1.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a análise coletiva do trabalho como método de vigilância em saúde do trabalhador, é CORRETO afirmar:',
  alts: [
    { t: 'Parte do saber dos trabalhadores, reconstituindo coletivamente o processo real e seus riscos.', ok: true,
      why: 'Correta. Revela o trabalho como executado, frequentemente distinto do descrito nos documentos.' },
    { t: 'Parte dos documentos técnicos apresentados pela empresa, que descrevem o processo e os riscos previstos.', ok: false,
      why: 'Errada. O documento descreve o trabalho prescrito, não o executado.' },
    { t: 'Parte do processo real, sendo o relato dos trabalhadores fonte pouco confiável a ser evitada.', ok: false,
      why: 'Errada. É a fonte primária sobre como o trabalho realmente acontece.' },
    { t: 'Parte do saber dos trabalhadores, dispensando o método a observação direta da atividade executada.', ok: false,
      why: 'Errada. Observação e relato se complementam.' },
    { t: 'Parte do saber dos trabalhadores, não devendo os resultados ser devolvidos ao coletivo analisado.', ok: false,
      why: 'Errada. A devolução é parte do método e condição de sua legitimidade.' }
  ],
  comentario: 'Análise coletiva: o trabalhador como sujeito que conhece o processo, reconstituição coletiva do trabalho real, observação direta e devolução dos resultados ao grupo. O documento mostra o prescrito; o risco mora na diferença.',
  pegadinha: 'Auditar só documentos produz relatório conforme sobre um trabalho que ninguém executa daquele jeito.',
  refs: ['PNSTT', 'Ergonomia da atividade — trabalho prescrito e trabalho real'] }

);
