/* Seção 1 — lote de volume. Questões AUTORAIS. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(
{ id: 'q-1.1-025', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um hospital de médio porte discute quem deve chefiar o serviço especializado em segurança e medicina do trabalho. O diretor sugere um engenheiro de produção sem formação em segurança, por ser "o mais organizado". A objeção técnica correta é:',
  alts: [
    { t: 'Os integrantes devem ter formação e qualificação específicas para as funções previstas.', ok: true,
      why: 'Correta. Competência gerencial genérica não supre a exigência técnica.' },
    { t: 'Qualquer profissional de nível superior pode chefiar, desde que haja médico e técnico na equipe.', ok: false,
      why: 'Errada. Cada função exige formação e qualificação próprias.' },
    { t: 'A chefia deve ser obrigatoriamente do médico do trabalho, por deter a responsabilidade técnica final.', ok: false,
      why: 'Errada. Não há essa exigência de chefia médica.' },
    { t: 'A escolha é livre, por ser estrutura interna sujeita apenas ao organograma definido pela empresa.', ok: false,
      why: 'Errada. A composição e a qualificação são definidas em norma.' },
    { t: 'A objeção só vale em grau de risco elevado; em serviços de saúde não há exigência de qualificação.', ok: false,
      why: 'Errada. A exigência de qualificação independe do setor.' }
  ],
  comentario: 'O ponto é a exigência de qualificação específica para integrar o serviço especializado. Boa gestão não substitui habilitação técnica em segurança e saúde no trabalho.',
  pegadinha: 'A alternativa que reserva a chefia ao médico soa corporativamente atraente, mas não corresponde à regra de composição.',
  refs: ['Normas Regulamentadoras — serviço especializado em segurança e medicina do trabalho'] },

{ id: 'q-1.1-026', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao apresentar o relatório anual de saúde ocupacional à diretoria de uma indústria têxtil, o médico do trabalho é criticado por "trazer só números de doença e nenhum indicador de negócio". A resposta que melhor integra as duas linguagens sem descaracterizar a prática médica é:',
  alts: [
    { t: 'Articular os achados de saúde a absenteísmo, rotatividade e custo, em nível agregado.', ok: true,
      why: 'Correta. Os dados clínicos permanecem sem identificação individual.' },
    { t: 'Fornecer a lista nominal de afastados por diagnóstico para a diretoria calcular seu próprio indicador.', ok: false,
      why: 'Errada. Viola o sigilo dos dados clínicos individuais.' },
    { t: 'Recusar qualquer indicador econômico, pois a saúde não deve ser mensurada em termos de custo.', ok: false,
      why: 'Errada. O argumento econômico sustenta o investimento em prevenção.' },
    { t: 'Substituir os indicadores de saúde por metas de produtividade, mais compreensíveis para a diretoria.', ok: false,
      why: 'Errada. Deixa de informar o que a direção precisa decidir.' },
    { t: 'Apresentar apenas o número total de exames realizados, suficiente para demonstrar a efetividade.', ok: false,
      why: 'Errada. Volume de exames não mede efetividade do programa.' }
  ],
  comentario: 'A questão testa a competência de comunicação do médico do trabalho: falar a linguagem da gestão sem violar sigilo e sem reduzir o relatório a contagem de exames.',
  pegadinha: 'Contar exames realizados é o indicador mais fácil e o mais enganoso: mede atividade, não resultado.',
  refs: ['Gestão em saúde do trabalhador — indicadores', 'Código de Ética Médica'] },

{ id: 'q-1.1-027', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de call center pede ao médico do trabalho que "coloque no atestado de saúde ocupacional" que ele tem transtorno de ansiedade, para justificar mudança de setor. A conduta correta é:',
  alts: [
    { t: 'Explicar que o documento não registra diagnóstico e expressar a necessidade como restrição funcional.', ok: true,
      why: 'Correta. A fundamentação clínica permanece no prontuário.' },
    { t: 'Atender ao pedido, pois havendo consentimento expresso do trabalhador não há violação de sigilo.', ok: false,
      why: 'Errada. O documento de aptidão não é o lugar do diagnóstico.' },
    { t: 'Negar o registro e encaminhar o trabalhador ao setor de pessoal para pleitear a mudança sozinho.', ok: false,
      why: 'Errada. Havendo justificativa técnica, cabe registrar a restrição funcional.' },
    { t: 'Registrar o diagnóstico em código de classificação de doenças, o que preserva o sigilo por ser codificado.', ok: false,
      why: 'Errada. O código revela o diagnóstico a quem sabe lê-lo.' },
    { t: 'Emitir atestado de afastamento por tempo indeterminado até que a empresa promova a mudança de setor.', ok: false,
      why: 'Errada. Afastar não é o meio de obter mudança administrativa.' }
  ],
  comentario: 'A questão cobra a tradução do achado clínico em linguagem de aptidão. Restrição funcional é o instrumento que concilia proteção do trabalhador, necessidade da empresa e sigilo.',
  pegadinha: 'O consentimento do trabalhador parece resolver tudo, mas o documento de aptidão simplesmente não é o lugar do diagnóstico.',
  refs: ['Código de Ética Médica', 'Normas Regulamentadoras — controle médico de saúde ocupacional'] },

{ id: 'q-1.1-028', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma transportadora quer implantar um programa de exames em motoristas com base em recomendação de um fornecedor de laboratório, que sugere painel amplo de exames laboratoriais anuais para todos. O médico do trabalho avalia a proposta. A análise tecnicamente correta é:',
  alts: [
    { t: 'Devem ser selecionados pelos riscos e pelas exigências da função, não por pacote comercial.', ok: true,
      why: 'Correta. O painel padronizado gera achados irrelevantes e sobrediagnóstico.' },
    { t: 'Quanto mais exames, melhor a proteção do trabalhador e maior a segurança jurídica da empresa.', ok: false,
      why: 'Errada. Exame sem indicação produz dano por excesso de intervenção.' },
    { t: 'O painel amplo é aceitável porque a norma fixa rol mínimo, e exceder o mínimo é sempre recomendável.', ok: false,
      why: 'Errada. Exceder sem indicação técnica não é benefício.' },
    { t: 'A escolha dos exames é atribuição do laboratório contratado, que detém o conhecimento laboratorial.', ok: false,
      why: 'Errada. A indicação é técnica e cabe ao médico coordenador.' },
    { t: 'Exames laboratoriais anuais dispensam a avaliação clínica periódica, por serem mais objetivos.', ok: false,
      why: 'Errada. O exame clínico é insubstituível na avaliação ocupacional.' }
  ],
  comentario: 'O núcleo é a indicação orientada por risco. Rastreamento indiscriminado no ambiente ocupacional gera sobrediagnóstico, ansiedade e custo, e desvia recursos do controle do risco na fonte.',
  pegadinha: 'A intuição "mais exame protege mais" é o erro mais comum na gestão de programas ocupacionais.',
  refs: ['Normas Regulamentadoras — controle médico de saúde ocupacional', 'Prevenção quaternária'] },

{ id: 'q-1.1-029', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um médico do trabalho é convidado a integrar o quadro de uma empresa de consultoria que atende múltiplas indústrias químicas. Sobre o exercício da autonomia técnica nesse arranjo, é CORRETO afirmar:',
  alts: [
    { t: 'A autonomia técnica deve ser assegurada qualquer que seja o vínculo contratual do médico.', ok: true,
      why: 'Correta. A relação comercial não pode condicionar conclusões médicas.' },
    { t: 'Em contrato de consultoria, as conclusões médicas devem ser previamente validadas pelo cliente.', ok: false,
      why: 'Errada. A conclusão técnica não se subordina ao contratante.' },
    { t: 'A autonomia técnica só existe quando o médico é empregado direto da empresa que está sendo avaliada.', ok: false,
      why: 'Errada. Independe da forma de vinculação.' },
    { t: 'A consultoria pode padronizar as conclusões de aptidão para reduzir a variabilidade entre médicos.', ok: false,
      why: 'Errada. A conclusão é individual e decorre da avaliação de cada caso.' },
    { t: 'A autonomia técnica autoriza o médico a descumprir a norma regulamentadora quando discordar dela.', ok: false,
      why: 'Errada. Autonomia técnica não é dispensa de cumprir a norma.' }
  ],
  comentario: 'A questão delimita a autonomia técnica: ela protege o juízo médico contra pressão comercial e hierárquica, mas não autoriza descumprir norma nem padronizar conclusões individuais.',
  pegadinha: 'Duas alternativas testam os limites opostos da autonomia: submetê-la ao cliente ou transformá-la em licença para ignorar normas.',
  refs: ['Código de Ética Médica', 'Código internacional de ética para profissionais de saúde ocupacional (ICOH)'] },

{ id: 'q-1.1-030', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa quer implantar avaliação ocupacional a distância para trabalhadores administrativos em regime remoto. O médico do trabalho é consultado. Assinale a afirmativa INCORRETA sobre essa possibilidade:',
  alts: [
    { t: 'A avaliação a distância pode substituir o exame presencial em qualquer função, com consentimento.', ok: true,
      why: 'É a INCORRETA. O uso remoto em saúde ocupacional é limitado por normas específicas.' },
    { t: 'A modalidade a distância exige registro adequado, identificação segura e privacidade da comunicação.', ok: false,
      why: 'Correta, portanto não é a resposta. São requisitos do atendimento remoto.' },
    { t: 'A decisão sobre a pertinência da modalidade cabe ao médico, considerando risco e necessidade de exame.', ok: false,
      why: 'Correta, portanto não é a resposta. É juízo técnico do profissional.' },
    { t: 'Riscos ergonômicos do trabalho remoto continuam objeto de avaliação e orientação, ainda que no domicílio.', ok: false,
      why: 'Correta, portanto não é a resposta. As obrigações permanecem.' },
    { t: 'Achados que exijam exame físico devem motivar convocação presencial complementar do trabalhador.', ok: false,
      why: 'Correta, portanto não é a resposta. É a conduta adequada.' }
  ],
  comentario: 'A questão cobra o limite da avaliação a distância: ela é ferramenta, não substituto universal. Consentimento não converte modalidade inadequada em adequada quando o risco exige exame físico.',
  pegadinha: 'A palavra "consentimento" costuma ser lida como autorização suficiente para qualquer arranjo, o que não se sustenta tecnicamente.',
  refs: ['Resoluções do CFM sobre telemedicina', 'Normas Regulamentadoras — controle médico de saúde ocupacional'] },

{ id: 'q-1.1-031', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um frigorífico registra aumento expressivo de queixas osteomusculares. A direção pede ao médico do trabalho que "avalie melhor os candidatos na admissão para não contratar quem já tem problema de coluna". A resposta tecnicamente e eticamente correta é:',
  alts: [
    { t: 'A seleção admissional não controla adoecimento coletivo: cabe intervir na organização.', ok: true,
      why: 'Correta. O aumento das queixas aponta o processo de trabalho, não os candidatos.' },
    { t: 'A triagem admissional rigorosa é a medida de maior custo-efetividade para reduzir essas queixas.', ok: false,
      why: 'Errada. Seleciona pessoas sem alterar a exposição que adoece.' },
    { t: 'Exames de imagem de coluna na admissão preveem com boa acurácia quem terá lombalgia ocupacional.', ok: false,
      why: 'Errada. O poder preditivo é baixo e o achado é prevalente em assintomáticos.' },
    { t: 'A recusa de contratação por achado de imagem é legítima quando documentada por laudo médico.', ok: false,
      why: 'Errada. Recusar por achado sem repercussão funcional é discriminação.' },
    { t: 'Basta condicionar a admissão à assinatura de termo de responsabilidade sobre queixas prévias.', ok: false,
      why: 'Errada. Termo assinado não altera a exposição nem o risco.' }
  ],
  comentario: 'O tema central é o desvio histórico da especialidade: usar o exame admissional como filtro de risco individual em vez de intervir no processo de trabalho. Achados de imagem de coluna são frequentes em assintomáticos e não predizem incapacidade.',
  pegadinha: 'A alternativa que fala em laudo documentado dá aparência de legalidade a uma prática discriminatória.',
  refs: ['Normas Regulamentadoras — ergonomia', 'Protocolo de DORT — Ministério da Saúde'] },

{ id: 'q-1.1-032', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um estudante de medicina pergunta ao preceptor por que a medicina do trabalho é considerada especialidade com forte componente coletivo, diferentemente da maioria das especialidades clínicas. A explicação correta é:',
  alts: [
    { t: 'Porque seu objeto inclui populações expostas a riscos comuns, exigindo raciocínio epidemiológico.', ok: true,
      why: 'Correta. A intervenção alcança o ambiente, além do cuidado individual.' },
    { t: 'Porque o médico do trabalho não realiza atendimento individual, dedicando-se apenas a inspeções.', ok: false,
      why: 'Errada. Realiza avaliações individuais além da atuação coletiva.' },
    { t: 'Porque as doenças relacionadas ao trabalho são sempre infectocontagiosas e exigem controle de surtos.', ok: false,
      why: 'Errada. A maioria não é transmissível.' },
    { t: 'Porque a especialidade é exercida exclusivamente em serviços públicos de vigilância em saúde.', ok: false,
      why: 'Errada. É exercida também em empresas e serviços privados.' },
    { t: 'Porque a legislação proíbe o médico do trabalho de estabelecer diagnóstico individual de doença.', ok: false,
      why: 'Errada. Não há tal proibição.' }
  ],
  comentario: 'A resposta reúne os dois planos da especialidade: o indivíduo exposto e o coletivo de trabalhadores sob o mesmo processo de trabalho. Esse duplo olhar é o que exige domínio de epidemiologia.',
  pegadinha: 'Distratores empurram para extremos: ou nega o atendimento individual, ou nega o componente coletivo.',
  refs: ['Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-1.1-033', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Após um surto de intoxicação por agrotóxico em uma fazenda, o médico do trabalho da empresa produtora é procurado pela imprensa. Sobre sua conduta, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'O médico deve informar à imprensa a evolução clínica dos intoxicados, dado o interesse público.', ok: true,
      why: 'É a INCORRETA. Dados clínicos individuais são protegidos por sigilo.' },
    { t: 'A ocorrência deve ser notificada às autoridades sanitárias competentes pelo serviço que a identificou.', ok: false,
      why: 'Correta, portanto não é a resposta. Intoxicação exógena é agravo notificável.' },
    { t: 'A investigação deve buscar as causas no processo, incluindo armazenamento, diluição e aplicação.', ok: false,
      why: 'Correta, portanto não é a resposta. É onde estão os determinantes.' },
    { t: 'Os trabalhadores expostos, mesmo assintomáticos, devem ser avaliados e acompanhados no período.', ok: false,
      why: 'Correta, portanto não é a resposta. A avaliação alcança todos os expostos.' },
    { t: 'A empresa deve emitir a comunicação de acidente do trabalho para os casos caracterizados.', ok: false,
      why: 'Correta, portanto não é a resposta. É obrigação legal.' }
  ],
  comentario: 'A questão combina resposta a evento agudo (notificação, investigação do processo, avaliação de expostos, comunicação previdenciária) com o limite ético da comunicação pública: não se divulga dado clínico identificável.',
  pegadinha: 'A expressão "interesse público" é usada como falso fundamento para quebra de sigilo.',
  refs: ['Código de Ética Médica', 'SINAN — intoxicação exógena', 'Lei nº 8.213/1991'] },

{ id: 'q-1.1-034', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma multinacional impõe à filial brasileira um protocolo corporativo de saúde ocupacional elaborado no exterior, que prevê exames e periodicidades diferentes das exigidas no país. O médico do trabalho local deve:',
  alts: [
    { t: 'Cumprir a norma nacional como piso e incorporar do protocolo o que a complemente tecnicamente.', ok: true,
      why: 'Correta. O padrão interno soma; não substitui a exigência nacional.' },
    { t: 'Adotar integralmente o protocolo corporativo, por ser padrão internacional mais avançado que o local.', ok: false,
      why: 'Errada. A exigência nacional é piso obrigatório.' },
    { t: 'Recusar qualquer elemento do protocolo estrangeiro, por não ter validade normativa no país.', ok: false,
      why: 'Errada. O que for mais protetor pode e deve ser incorporado.' },
    { t: 'Submeter a divergência ao setor jurídico e suspender o programa até que haja decisão definitiva.', ok: false,
      why: 'Errada. Suspender o programa deixa os trabalhadores desassistidos.' },
    { t: 'Aplicar o protocolo aos expatriados e a norma nacional aos demais, criando dois regimes na planta.', ok: false,
      why: 'Errada. Dois regimes na mesma planta é discriminação.' }
  ],
  comentario: 'O princípio é simples e muito cobrado: norma nacional é piso inderrogável; política corporativa pode elevar o padrão, jamais rebaixá-lo, e não cria regimes distintos por origem do trabalhador.',
  pegadinha: 'A ideia de que padrão internacional "é sempre mais avançado" leva à adoção acrítica e ao descumprimento legal.',
  refs: ['Normas Regulamentadoras', 'OIT — Serviços de Saúde no Trabalho'] },

{ id: 'q-1.1-035', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma pequena empresa de marcenaria com 12 empregados, o proprietário afirma que "não precisa de nada de medicina do trabalho porque é microempresa". O médico consultor esclarece que:',
  alts: [
    { t: 'A dispensa de estruturas no menor porte não elimina identificar riscos nem o controle médico.', ok: true,
      why: 'Correta. As obrigações essenciais permanecem, de forma simplificada.' },
    { t: 'As microempresas estão integralmente dispensadas de exames ocupacionais e de avaliação de riscos.', ok: false,
      why: 'Errada. Há simplificação, não dispensa integral.' },
    { t: 'A obrigação só surge quando ocorrer o primeiro acidente registrado naquele estabelecimento.', ok: false,
      why: 'Errada. É preventiva e independe de evento anterior.' },
    { t: 'Basta que o proprietário assine declaração de inexistência de riscos para afastar as obrigações.', ok: false,
      why: 'Errada. Declaração não substitui identificação técnica de riscos.' },
    { t: 'A responsabilidade recai sobre o sindicato patronal, que deve prestar o serviço às filiadas.', ok: false,
      why: 'Errada. A obrigação é do empregador.' }
  ],
  comentario: 'A questão cobra a distinção entre simplificação por porte e dispensa de obrigações. Marcenaria concentra riscos relevantes, o que torna a alegação de dispensa ainda mais frágil.',
  pegadinha: 'A ideia de "declaração de inexistência de riscos" é atalho comum e juridicamente inócuo quando os riscos são evidentes.',
  refs: ['Normas Regulamentadoras — gerenciamento de riscos e controle médico'] },

{ id: 'q-1.1-036', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Durante processo seletivo, uma candidata informa ao médico examinador que está grávida e pede que a informação não seja repassada à empresa. A conduta correta do médico do trabalho é:',
  alts: [
    { t: 'Preservar a informação, comunicando apenas aptidão e restrições ligadas às exigências da função.', ok: true,
      why: 'Correta. A gestação não é revelada ao empregador.' },
    { t: 'Informar a empresa, pois a gestação altera a exposição permitida e ela precisa saber para se resguardar.', ok: false,
      why: 'Errada. Comunica-se a restrição, não a condição.' },
    { t: 'Considerar a candidata inapta, pois a gestação impede a admissão em ambiente de natureza industrial.', ok: false,
      why: 'Errada. Seria discriminação; adequa-se a exposição.' },
    { t: 'Solicitar teste de gravidez a todas as candidatas, de modo a padronizar a conduta do serviço médico.', ok: false,
      why: 'Errada. É exigência vedada e discriminatória.' },
    { t: 'Adiar a conclusão do exame admissional até o término da gestação da candidata avaliada.', ok: false,
      why: 'Errada. Inviabiliza a contratação e é discriminação.' }
  ],
  comentario: 'O caso reúne sigilo e não discriminação: informa-se aptidão e restrição, nunca a condição; e gestação não gera inaptidão genérica, mas eventual adequação de exposição.',
  pegadinha: 'O argumento de "proteção jurídica da empresa" é usado para justificar revelação desnecessária de dado sensível.',
  refs: ['Código de Ética Médica', 'CLT — proteção à maternidade'] },

{ id: 'q-1.1-037', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de medicina do trabalho terceirizado atende 200 empresas e emite documentos de aptidão em larga escala, com consultas de poucos minutos. Sobre a qualidade dessa prática, a crítica tecnicamente mais precisa é:',
  alts: [
    { t: 'O exame só cumpre sua função se reconhece a exposição e liga os achados ao risco da função.', ok: true,
      why: 'Correta. Volume alto com tempo insuficiente transforma o exame em ato cartorial.' },
    { t: 'O problema é exclusivamente jurídico, pois a norma estabelece tempo mínimo de consulta ocupacional.', ok: false,
      why: 'Errada. O problema é técnico: o juízo exigido não cabe naquele tempo.' },
    { t: 'A prática é adequada desde que os exames complementares sejam feitos em laboratório certificado.', ok: false,
      why: 'Errada. O exame clínico é o que articula achado e exposição.' },
    { t: 'A crítica não procede, pois trabalhadores administrativos não exigem avaliação detalhada de riscos.', ok: false,
      why: 'Errada. Riscos ergonômicos e psicossociais exigem avaliação.' },
    { t: 'O uso de questionário autoaplicado antes da consulta elimina a necessidade de avaliação médica.', ok: false,
      why: 'Errada. É insumo da consulta, não substituto.' }
  ],
  comentario: 'A crítica ao "exame de carimbo" deve ser feita pelo conteúdo: sem conhecimento da exposição e sem tempo de correlação clínica, não há avaliação ocupacional, apenas documento.',
  pegadinha: 'Uma alternativa inventa parâmetro normativo de tempo mínimo; cuidado com distratores que fabricam número onde a crítica é conceitual.',
  refs: ['Normas Regulamentadoras — controle médico de saúde ocupacional', 'Código de Ética Médica'] },

{ id: 'q-1.1-038', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria petroquímica pretende integrar o serviço de medicina do trabalho ao programa de gerenciamento de riscos. O médico propõe que os achados clínicos alimentem a revisão do inventário de riscos. Sobre essa proposta, é CORRETO afirmar:',
  alts: [
    { t: 'É adequada: achados de saúde indicam a efetividade dos controles e revelam exposições não vistas.', ok: true,
      why: 'Correta. A vigilância da saúde realimenta o inventário de riscos.' },
    { t: 'É inadequada, pois dados de saúde são sigilosos e não podem influenciar decisões de engenharia.', ok: false,
      why: 'Errada. Dados agregados orientam decisões sem quebrar o sigilo.' },
    { t: 'O inventário de riscos deve basear-se exclusivamente em medições ambientais de caráter quantitativo.', ok: false,
      why: 'Errada. Achados de saúde e percepção dos trabalhadores também compõem.' },
    { t: 'Achados de saúde só devem gerar revisão do inventário havendo diagnóstico confirmado de doença.', ok: false,
      why: 'Errada. Alterações precoces já sinalizam falha de controle.' },
    { t: 'A revisão do inventário compete ao engenheiro de segurança, cabendo ao médico apenas comunicar casos.', ok: false,
      why: 'Errada. A elaboração é articulada entre as áreas.' }
  ],
  comentario: 'O ponto é a retroalimentação entre vigilância da saúde e gerenciamento de riscos: alteração precoce em trabalhador é sinal de falha de controle e deve disparar revisão da avaliação ambiental.',
  pegadinha: 'Exigir diagnóstico confirmado para revisar o inventário é o erro mais sedutor: parece rigor técnico, mas atrasa a prevenção.',
  refs: ['Normas Regulamentadoras — gerenciamento de riscos ocupacionais e controle médico'] },
{ id: 'q-1.2-010', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de referência analisa por que trabalhadores de uma mesma empresa, com o mesmo posto, adoecem de forma diferente conforme sejam efetivos ou terceirizados. Um técnico propõe explicar o achado pela determinação social do processo saúde-doença. Essa perspectiva sustenta que:',
  alts: [
    { t: 'Vínculo, renda e poder de negociação atuam como determinantes, além da exposição no posto.', ok: true,
      why: 'Correta. A inserção no trabalho explica diferenças com exposição física idêntica.' },
    { t: 'A diferença observada é explicada pela suscetibilidade genética individual de cada trabalhador.', ok: false,
      why: 'Errada. Os determinantes sociais explicam boa parte do gradiente.' },
    { t: 'A determinação social nega o papel dos agentes físicos e químicos no processo de adoecimento.', ok: false,
      why: 'Errada. As abordagens são complementares.' },
    { t: 'A explicação está no acaso, já que a exposição no posto de trabalho é idêntica para todos eles.', ok: false,
      why: 'Errada. O gradiente por inserção é consistente e documentado.' },
    { t: 'A determinação social aplica-se apenas às doenças infecciosas, e não aos agravos ocupacionais.', ok: false,
      why: 'Errada. É perspectiva geral do campo da saúde.' }
  ],
  comentario: 'A determinação social não substitui a análise do agente; ela a insere em relações sociais concretas. Terceirização, precariedade e rotatividade produzem exposições e vulnerabilidades diferentes no mesmo posto.',
  pegadinha: 'A armadilha é ler determinação social como negação do risco físico-químico. Ela é ampliação do olhar, não substituição.',
  refs: ['Determinação social do processo saúde-doença', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.2-011', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um sindicato de químicos organiza grupos de trabalhadores para mapear coletivamente as exposições em uma fábrica, produzindo um "mapa de risco" construído pelos próprios operários. Essa prática se inspira diretamente:',
  alts: [
    { t: 'No modelo operário italiano, que valoriza o saber do trabalhador sobre seu processo.', ok: true,
      why: 'Correta. Inclui a validação consensual do conhecimento pelo grupo homogêneo.' },
    { t: 'No modelo taylorista, que padroniza tarefas a partir da observação sistemática dos operários.', ok: false,
      why: 'Errada. O taylorismo expropria o saber do trabalhador.' },
    { t: 'Na escola de higiene industrial, que fundamenta a avaliação exclusivamente na medição instrumental.', ok: false,
      why: 'Errada. Ali o saber do trabalhador não é fonte de conhecimento.' },
    { t: 'No modelo biomédico de causalidade, que atribui o adoecimento a um agente único e mensurável.', ok: false,
      why: 'Errada. Centra-se no agente, não no coletivo de trabalhadores.' },
    { t: 'Na abordagem comportamental de segurança, centrada na correção do ato inseguro do trabalhador.', ok: false,
      why: 'Errada. Individualiza a culpa em vez de valorizar o saber coletivo.' }
  ],
  comentario: 'O modelo operário italiano é a matriz da participação dos trabalhadores no reconhecimento dos riscos e influenciou fortemente o campo brasileiro da saúde do trabalhador, inclusive a prática de mapa de risco.',
  pegadinha: 'Taylorismo também "observa o operário", mas para expropriar seu saber. A inversão de finalidade é o que a questão testa.',
  refs: ['Modelo operário italiano', 'Oddone — Ambiente de trabalho'] },

{ id: 'q-1.2-012', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma capacitação, pede-se que os participantes ordenem historicamente três paradigmas: Medicina do Trabalho, Saúde Ocupacional e Saúde do Trabalhador. A caracterização CORRETA é:',
  alts: [
    { t: 'Medicina do Trabalho no médico; Saúde Ocupacional no ambiente; Saúde do Trabalhador no processo.', ok: true,
      why: 'Correta. A última acrescenta a participação dos trabalhadores como constitutiva.' },
    { t: 'A Saúde Ocupacional é o paradigma mais recente, tendo superado a Saúde do Trabalhador com normas.', ok: false,
      why: 'Errada. A Saúde do Trabalhador é o paradigma posterior.' },
    { t: 'Os três termos designam a mesma prática, com nomes diferentes conforme o país e a época.', ok: false,
      why: 'Errada. Diferem em objeto, método e sujeito da ação.' },
    { t: 'A Medicina do Trabalho é o paradigma mais amplo, por abranger vigilância e participação social.', ok: false,
      why: 'Errada. É o mais restrito, centrado no médico e no indivíduo.' },
    { t: 'A Saúde do Trabalhador é sinônimo de perícia previdenciária, por tratar de reconhecimento de direitos.', ok: false,
      why: 'Errada. É campo do sistema de saúde, não da previdência.' }
  ],
  comentario: 'A sequência conceitual é cobrada com frequência: unidisciplinar e adaptativa, depois multiprofissional e ambiental, depois social e participativa. Cada etapa amplia o objeto sem eliminar as anteriores.',
  pegadinha: 'A inversão cronológica entre Saúde Ocupacional e Saúde do Trabalhador é o distrator principal.',
  refs: ['Mendes, R.; Dias, E. C. — Da medicina do trabalho à saúde do trabalhador'] },

{ id: 'q-1.2-013', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pesquisadora afirma que "o trabalho é categoria analítica central para compreender o adoecimento contemporâneo". Um colega discorda, dizendo que o desemprego e o trabalho por aplicativo tornaram a categoria obsoleta. A análise CORRETA é:',
  alts: [
    { t: 'As novas formas ampliam a relevância do trabalho, criando exposições com padrões próprios.', ok: true,
      why: 'Correta. Jornadas, vínculos e pressão algorítmica produzem adoecimento específico.' },
    { t: 'A categoria trabalho perde sentido sem vínculo formal, restando a análise do comportamento individual.', ok: false,
      why: 'Errada. O objeto é o processo de trabalho, com ou sem vínculo.' },
    { t: 'Trabalhadores de plataforma não se expõem a riscos relevantes por definirem seus próprios horários.', ok: false,
      why: 'Errada. Acumulam risco de trânsito, jornadas longas e pressão por tempo.' },
    { t: 'A análise do trabalho deve ceder lugar à análise de estilo de vida, mais adequada às crônicas atuais.', ok: false,
      why: 'Errada. Desloca a responsabilidade para o indivíduo.' },
    { t: 'A categoria trabalho só se aplica à produção industrial, e não a serviços e ao trabalho imaterial.', ok: false,
      why: 'Errada. Alcança todas as formas de atividade laboral.' }
  ],
  comentario: 'A questão sustenta a centralidade do trabalho como categoria analítica mesmo diante de vínculos atípicos. A precarização é objeto de análise, não sinal de irrelevância da categoria.',
  pegadinha: 'A alternativa do estilo de vida é o distrator mais forte porque reproduz o discurso de individualização do risco.',
  refs: ['Saúde do trabalhador — trabalho como categoria analítica', 'OIT — trabalho em plataformas digitais'] },

{ id: 'q-1.2-014', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em um conselho municipal de saúde, discute-se a criação de uma comissão intersetorial de saúde do trabalhador com participação de trabalhadores. Sobre o controle social nesse campo, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'O controle social é exercido por técnicos, cabendo aos trabalhadores apenas informar condições.', ok: true,
      why: 'É a INCORRETA. A participação é deliberativa, não meramente informativa.' },
    { t: 'A participação dos trabalhadores qualifica o reconhecimento dos riscos, por trazer a atividade real.', ok: false,
      why: 'Correta, portanto não é a resposta. É informação que nenhuma outra fonte dá.' },
    { t: 'As instâncias de participação previstas no sistema público de saúde alcançam a saúde do trabalhador.', ok: false,
      why: 'Correta, portanto não é a resposta. Conselhos e conferências a alcançam.' },
    { t: 'A intersetorialidade com trabalho, previdência e meio ambiente é característica da política do setor.', ok: false,
      why: 'Correta, portanto não é a resposta. É traço estruturante do campo.' },
    { t: 'A participação sindical é forma historicamente relevante de organização da demanda por saúde.', ok: false,
      why: 'Correta, portanto não é a resposta. É uma das raízes do campo.' }
  ],
  comentario: 'Controle social é participação deliberativa. Reduzir o trabalhador a informante é exatamente o que o campo da saúde do trabalhador recusa desde sua origem.',
  pegadinha: 'A afirmativa incorreta parece elogiosa à participação, mas rebaixa o trabalhador de sujeito a fonte de dados.',
  refs: ['Lei nº 8.142/1990', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.2-015', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de aplicativo de entregas sofre acidente de trânsito durante uma corrida e procura a unidade básica de saúde. O médico se pergunta se o caso pertence ao campo da saúde do trabalhador. A abordagem correta é:',
  alts: [
    { t: 'Sim: o campo alcança todo trabalhador, e o caso deve ser registrado como agravo do trabalho.', ok: true,
      why: 'Correta. Cabe investigar as condições em que a atividade é executada.' },
    { t: 'Não: sem vínculo empregatício não há acidente nem agravo relacionado ao trabalho para nenhum fim.', ok: false,
      why: 'Errada. A notificação e o campo independem do vínculo.' },
    { t: 'Sim, mas apenas se o trabalhador contribuir para a previdência como contribuinte individual inscrito.', ok: false,
      why: 'Errada. A notificação em saúde independe de contribuição.' },
    { t: 'Não: acidentes de trânsito são sempre causas externas gerais, sem qualquer relação com o trabalho.', ok: false,
      why: 'Errada. Ocorrido no exercício da atividade, é acidente de trabalho.' },
    { t: 'Sim, mas o registro é responsabilidade exclusiva da plataforma digital, e não do serviço de saúde.', ok: false,
      why: 'Errada. A notificação é do serviço que identifica o caso.' }
  ],
  comentario: 'A questão separa dois planos que se confundem na prática: cobertura previdenciária e reconhecimento sanitário do agravo. O segundo independe do vínculo e do recolhimento.',
  pegadinha: 'A ligação automática entre "sem vínculo" e "não é acidente de trabalho" é o erro mais frequente entre médicos assistenciais.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'SINAN — acidente de trabalho'] },

{ id: 'q-1.2-016', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma equipe de saúde da família identifica que muitos moradores adoecem por exposição a solventes em oficinas de fundo de quintal do bairro. Ao propor a intervenção, a equipe deve considerar que:',
  alts: [
    { t: 'Trabalho informal e domiciliar integra o objeto da saúde do trabalhador, e a abordagem territorial permite alcançar exposições que escapam à lógica da empresa formal.', ok: true,
      why: 'Correta. A base territorial da atenção primária é uma via privilegiada para alcançar trabalho informal, domiciliar e familiar, invisível às estruturas empresariais.' },
    { t: 'A atuação é inviável, pois sem empregador identificado não há a quem dirigir as ações de vigilância.', ok: false,
      why: 'Errada. A vigilância sanitária e a atenção à saúde alcançam estabelecimentos e situações de trabalho independentemente da existência de empregador formal.' },
    { t: 'O caso deve ser encaminhado exclusivamente à inspeção do trabalho, sem participação do setor saúde.', ok: false,
      why: 'Errada. A ação é intersetorial; a saúde tem competência própria em saúde do trabalhador.' },
    { t: 'A abordagem deve limitar-se à orientação individual sobre uso de máscara pelos moradores.', ok: false,
      why: 'Errada. Reduzir a intervenção a proteção individual ignora medidas coletivas e a análise do processo de trabalho.' },
    { t: 'Trabalho domiciliar não gera exposição relevante por ser realizado em pequena escala.', ok: false,
      why: 'Errada. Pequena escala frequentemente vem com ausência de ventilação e de controles, o que pode elevar a exposição.' }
  ],
  comentario: 'A questão destaca a potência da atenção primária de base territorial para o campo da saúde do trabalhador, especialmente diante do trabalho informal e domiciliar.',
  pegadinha: 'A associação entre pequena escala e baixo risco é intuitiva e falsa em ambientes sem controle de ventilação.',
  refs: ['RENAST', 'Atenção primária e saúde do trabalhador'] },

{ id: 'q-1.2-017', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao discutir saúde global e trabalho, um pesquisador aponta o fenômeno da transferência de riscos entre países. Esse fenômeno se caracteriza por:',
  alts: [
    { t: 'Deslocamento de processos perigosos para países com regulação mais frágil e menor fiscalização.', ok: true,
      why: 'Correta. Transfere a carga de doença para populações mais vulneráveis.' },
    { t: 'Aumento da exportação de tecnologias de proteção coletiva dos países periféricos para os centrais.', ok: false,
      why: 'Errada. O fluxo tecnológico se dá em sentido contrário.' },
    { t: 'Uniformização automática dos limites de exposição em todos os países por força de tratados comerciais.', ok: false,
      why: 'Errada. Os limites permanecem heterogêneos entre países.' },
    { t: 'Redução global e simultânea do uso de amianto e agrotóxicos em todos os países produtores.', ok: false,
      why: 'Errada. Banidos em uns, seguem em uso em outros.' },
    { t: 'Migração de trabalhadores qualificados para países com melhores condições, sem efeito na carga de doença.', ok: false,
      why: 'Errada. Não descreve o fenômeno de transferência de risco.' }
  ],
  comentario: 'A transferência de riscos é conceito-chave em saúde global do trabalho: proibições locais podem conviver com manutenção do risco em outros territórios, o que exige olhar internacional.',
  pegadinha: 'A ideia de harmonização automática de limites por acordos comerciais é atraente e não corresponde à realidade regulatória.',
  refs: ['OMS/OIT — saúde global e trabalho', 'Carga global de doença atribuível ao trabalho'] },

{ id: 'q-1.2-018', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa apresenta campanha interna afirmando que "a maioria dos acidentes decorre de ato inseguro do trabalhador" e propõe premiação por comportamento seguro. Um médico do trabalho formado no campo da saúde do trabalhador critica a proposta porque:',
  alts: [
    { t: 'Atribuir ao ato inseguro individualiza a culpa e desloca a análise das condições de trabalho.', ok: true,
      why: 'Correta. A premiação ainda induz subnotificação por medo de perdê-la.' },
    { t: 'A premiação por ausência de acidentes é vedada por norma, o que torna a campanha simplesmente ilegal.', ok: false,
      why: 'Errada. O problema é técnico e cultural, não de vedação normativa.' },
    { t: 'O comportamento do trabalhador não tem qualquer influência sobre a ocorrência de acidentes no setor.', ok: false,
      why: 'Errada. Influencia, mas é moldado pelas condições e pela organização.' },
    { t: 'A campanha só seria válida se aplicada exclusivamente aos trabalhadores terceirizados da planta.', ok: false,
      why: 'Errada. Aplicá-la a um grupo agravaria a distorção.' },
    { t: 'A crítica é infundada, pois a análise de causa raiz confirma causa comportamental única na maioria.', ok: false,
      why: 'Errada. A análise de causa raiz aponta condições latentes.' }
  ],
  comentario: 'A crítica ao paradigma do ato inseguro é central: ele individualiza a responsabilidade, gera subnotificação por incentivo perverso e impede intervenção nas causas latentes.',
  pegadinha: 'Negar completamente a influência do comportamento é o exagero oposto e também está errado; a crítica correta é sobre o deslocamento da análise.',
  refs: ['Análise de acidentes — causas latentes', 'Saúde do trabalhador — crítica ao ato inseguro'] },

{ id: 'q-1.2-019', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao caracterizar o campo da Saúde do Trabalhador no Brasil, é CORRETO afirmar que sua inserção institucional principal ocorre:',
  alts: [
    { t: 'No sistema público de saúde, com competência constitucional e legal atribuída ao setor.', ok: true,
      why: 'Correta. A execução das ações de saúde do trabalhador é do sistema de saúde.' },
    { t: 'Exclusivamente nos serviços internos das empresas, por meio dos programas obrigatórios previstos.', ok: false,
      why: 'Errada. A competência pública é constitucional e legal.' },
    { t: 'Na estrutura da previdência social, responsável pela concessão dos benefícios acidentários devidos.', ok: false,
      why: 'Errada. A previdência concede benefícios; não executa vigilância.' },
    { t: 'Nas entidades sindicais, que detêm competência legal de fiscalizar os ambientes de trabalho.', ok: false,
      why: 'Errada. Sindicatos acompanham e denunciam; não fiscalizam com poder de polícia.' },
    { t: 'Nas agências reguladoras setoriais, responsáveis por definir os limites de exposição ocupacional.', ok: false,
      why: 'Errada. Os limites são fixados na esfera do trabalho.' }
  ],
  comentario: 'A inserção do campo no sistema público de saúde é o que o distingue do modelo empresarial e o que fundamenta a vigilância em saúde do trabalhador como ação de Estado.',
  pegadinha: 'Confundir onde o campo está institucionalmente inserido com quem executa obrigações empresariais é o erro plantado.',
  refs: ['Constituição Federal de 1988', 'Lei nº 8.080/1990'] },

{ id: 'q-1.2-020', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma trabalhadora de teleatendimento relata que a pressão por metas e a vigilância eletrônica constante geram sofrimento. O supervisor argumenta que "não há risco físico, portanto não há risco ocupacional". A análise correta é:',
  alts: [
    { t: 'A organização do trabalho é fonte de risco: ritmo, metas e falta de autonomia adoecem.', ok: true,
      why: 'Correta. São determinantes reconhecidos de adoecimento ocupacional.' },
    { t: 'Somente agentes físicos, químicos e biológicos configuram risco, conforme a classificação clássica.', ok: false,
      why: 'Errada. Fatores ergonômicos e psicossociais integram o inventário.' },
    { t: 'O sofrimento relatado é de natureza individual e deve ser tratado apenas em terapia externa.', ok: false,
      why: 'Errada. Sem intervir na organização, o padrão persiste.' },
    { t: 'A ausência de diagnóstico psiquiátrico formal impede qualquer intervenção de caráter preventivo.', ok: false,
      why: 'Errada. A prevenção antecede o diagnóstico.' },
    { t: 'A vigilância eletrônica é medida neutra de gestão, sem efeito sobre a saúde de quem é monitorado.', ok: false,
      why: 'Errada. Tem efeitos documentados sobre saúde mental.' }
  ],
  comentario: 'A questão trabalha a ampliação do conceito de risco ocupacional para a organização do trabalho. É um dos pontos em que a perspectiva da saúde do trabalhador se distancia do modelo higienista clássico.',
  pegadinha: 'Exigir diagnóstico psiquiátrico formal para agir é armadilha comum: prevenção não depende de doença instalada.',
  refs: ['Fatores de risco psicossociais no trabalho', 'Dejours — Psicodinâmica do trabalho'] },

{ id: 'q-1.2-021', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um gestor de saúde afirma que a diferença entre "saúde ocupacional" e "saúde do trabalhador" é irrelevante na prática cotidiana. Um técnico responde que a diferença tem consequências operacionais concretas. Assinale a consequência prática que melhor sustenta essa resposta:',
  alts: [
    { t: 'O agravo não se encerra no atendido: dispara vigilância, busca de casos e intervenção.', ok: true,
      why: 'Correta. É o que distingue a perspectiva da saúde do trabalhador.' },
    { t: 'Sob a perspectiva da saúde do trabalhador, o atendimento clínico individual torna-se dispensável.', ok: false,
      why: 'Errada. O cuidado individual permanece e se soma à ação coletiva.' },
    { t: 'A diferença é apenas de nomenclatura dos setores administrativos nas secretarias de saúde.', ok: false,
      why: 'Errada. Muda o objeto e o método da ação.' },
    { t: 'Sob a saúde ocupacional, a participação dos trabalhadores é obrigatória em todas as decisões técnicas.', ok: false,
      why: 'Errada. A participação constitutiva caracteriza a saúde do trabalhador.' },
    { t: 'A saúde do trabalhador substitui a avaliação quantitativa de exposições pela exclusivamente qualitativa.', ok: false,
      why: 'Errada. As duas abordagens permanecem e se complementam.' }
  ],
  comentario: 'A distinção conceitual só ganha valor quando traduzida em conduta: do caso índice à vigilância do ambiente e à busca de casos. Esse é o teste prático do paradigma.',
  pegadinha: 'Duas alternativas transformam a ampliação de escopo em abandono de instrumentos clínicos ou quantitativos, o que não ocorre.',
  refs: ['Mendes, R.; Dias, E. C. — Da medicina do trabalho à saúde do trabalhador', 'VISAT'] },

{ id: 'q-1.2-022', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a relação entre trabalho, desigualdade social e saúde, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'A elevação da renda média elimina os gradientes de adoecimento por posição ocupacional.', ok: true,
      why: 'É a INCORRETA. O gradiente persiste mesmo em países de renda alta.' },
    { t: 'Trabalhadores com menor controle sobre o próprio trabalho têm pior perfil de saúde, mesmo com renda igual.', ok: false,
      why: 'Correta, portanto não é a resposta. É achado clássico da literatura.' },
    { t: 'A precarização do vínculo associa-se a maior exposição a riscos e a menor acesso a proteção.', ok: false,
      why: 'Correta, portanto não é a resposta. É associação documentada.' },
    { t: 'Trabalhadores informais têm menor acesso a diagnóstico e a reconhecimento de doenças do trabalho.', ok: false,
      why: 'Correta, portanto não é a resposta. É a base da subnotificação nesse grupo.' },
    { t: 'A distribuição desigual da exposição a riscos contribui para as desigualdades gerais em saúde.', ok: false,
      why: 'Correta, portanto não é a resposta. É um dos mecanismos do gradiente.' }
  ],
  comentario: 'O ponto é a persistência do gradiente social de saúde: não é apenas pobreza absoluta, mas posição relativa e controle sobre o trabalho que se associam ao adoecimento.',
  pegadinha: 'A afirmativa incorreta soa como conclusão otimista e razoável sobre desenvolvimento econômico, mas contraria os achados de gradiente social.',
  refs: ['Determinantes sociais da saúde', 'Modelo demanda-controle'] },

{ id: 'q-1.2-023', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma equipe realiza roda de conversa com costureiras de uma oficina para entender por que as pausas prescritas não são cumpridas. Elas relatam que o pagamento por peça inviabiliza parar. Essa constatação ilustra:',
  alts: [
    { t: 'A distância entre trabalho prescrito e real, mediada pela forma de remuneração adotada.', ok: true,
      why: 'Correta. A remuneração por produção funciona como determinante da exposição.' },
    { t: 'Falta de conscientização das trabalhadoras sobre a importância das pausas para a recuperação.', ok: false,
      why: 'Errada. Elas conhecem a pausa; a remuneração é que a inviabiliza.' },
    { t: 'Inadequação da recomendação técnica de pausas, que por isso deveria ser abandonada no setor.', ok: false,
      why: 'Errada. A pausa é adequada; o que falha é a condição para usá-la.' },
    { t: 'Necessidade de aumentar a fiscalização individual do cumprimento das pausas pelas trabalhadoras.', ok: false,
      why: 'Errada. Fiscalizar sem mudar a remuneração pune quem já está pressionado.' },
    { t: 'Ausência de risco ergonômico, já que as próprias trabalhadoras optam por não realizar as pausas.', ok: false,
      why: 'Errada. A escolha é condicionada pela forma de pagamento.' }
  ],
  comentario: 'A questão mostra como a organização do trabalho, aqui pela forma de remuneração, determina a exposição real. Intervenção efetiva exige mexer no sistema de incentivos, não na motivação individual.',
  pegadinha: 'A saída pela "conscientização" é o reflexo automático e o mais ineficaz quando o determinante é econômico-organizacional.',
  refs: ['Ergonomia — trabalho prescrito e trabalho real', 'Normas Regulamentadoras — ergonomia'] },

{ id: 'q-1.2-024', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um município investiga adoecimento entre trabalhadores de uma cadeia produtiva com forte presença de trabalho terceirizado e subcontratado. Sobre a chamada "invisibilidade" desses trabalhadores nos sistemas de informação, é CORRETO afirmar:',
  alts: [
    { t: 'A fragmentação dilui o registro entre empregadores e oculta o processo produtivo real.', ok: true,
      why: 'Correta. Subestima a carga de doença atribuível àquela cadeia.' },
    { t: 'A terceirização melhora a qualidade do registro, pois cada prestadora mantém seu próprio sistema.', ok: false,
      why: 'Errada. A fragmentação dispersa e dilui a informação.' },
    { t: 'A invisibilidade decorre apenas da recusa dos trabalhadores em relatar sua ocupação no atendimento.', ok: false,
      why: 'Errada. A causa principal é estrutural, não individual.' },
    { t: 'O problema se resolve integralmente com a exigência do campo ocupação no prontuário eletrônico.', ok: false,
      why: 'Errada. Ajuda, mas não resolve a diluição entre contratantes.' },
    { t: 'Trabalhadores terceirizados têm menor risco, o que explica sua menor frequência nas notificações.', ok: false,
      why: 'Errada. Costumam ter maior risco e menor registro.' }
  ],
  comentario: 'A questão explora um viés de informação com consequência sanitária: a fragmentação contratual produz subnotificação e distorce a atribuição de risco por atividade econômica.',
  pegadinha: 'Interpretar menor frequência de notificação como menor risco é um erro clássico de leitura de dado de vigilância.',
  refs: ['Vigilância em saúde do trabalhador', 'SINAN — qualidade da informação'] }
);
