/* Seção 1 — lote de volume. Questões AUTORAIS. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(
{ id: 'q-1.1-025', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um hospital de médio porte discute quem deve chefiar o serviço especializado em segurança e medicina do trabalho. O diretor sugere um engenheiro de produção sem formação em segurança, por ser "o mais organizado". A objeção técnica correta é:',
  alts: [
    { t: 'Os integrantes do serviço especializado devem ter formação e qualificação específicas para as funções previstas, não bastando competência gerencial genérica.', ok: true,
      why: 'Correta. A composição do serviço exige profissionais com habilitação específica em segurança e em medicina do trabalho; a chefia não pode ser exercida por quem não preenche esse requisito.' },
    { t: 'Qualquer profissional de nível superior pode chefiar o serviço, desde que haja um médico e um técnico entre os integrantes.', ok: false,
      why: 'Errada. A exigência de qualificação alcança os integrantes das funções previstas, não apenas parte da equipe.' },
    { t: 'A chefia deve obrigatoriamente ser do médico do trabalho, por deter a responsabilidade técnica final.', ok: false,
      why: 'Errada. Não há reserva de chefia ao médico; a exigência é de qualificação específica dos profissionais que compõem o serviço.' },
    { t: 'A escolha é livre porque o serviço é estrutura interna, sujeita apenas ao organograma da empresa.', ok: false,
      why: 'Errada. A composição do serviço é matéria normatizada e não fica ao arbítrio do organograma.' },
    { t: 'A objeção só se aplica a empresas de grau de risco elevado; em serviços de saúde não há exigência de qualificação.', ok: false,
      why: 'Errada. Serviços de saúde estão entre os ambientes com riscos relevantes, e a exigência de qualificação não depende disso.' }
  ],
  comentario: 'O ponto é a exigência de qualificação específica para integrar o serviço especializado. Boa gestão não substitui habilitação técnica em segurança e saúde no trabalho.',
  pegadinha: 'A alternativa que reserva a chefia ao médico soa corporativamente atraente, mas não corresponde à regra de composição.',
  refs: ['Normas Regulamentadoras — serviço especializado em segurança e medicina do trabalho'] },

{ id: 'q-1.1-026', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao apresentar o relatório anual de saúde ocupacional à diretoria de uma indústria têxtil, o médico do trabalho é criticado por "trazer só números de doença e nenhum indicador de negócio". A resposta que melhor integra as duas linguagens sem descaracterizar a prática médica é:',
  alts: [
    { t: 'Apresentar os achados de saúde articulados a indicadores de absenteísmo, rotatividade e custo de afastamento, mantendo os dados clínicos em nível agregado e sem identificação individual.', ok: true,
      why: 'Correta. Traduzir achados de saúde em indicadores de gestão é legítimo e potente, desde que preservado o sigilo por meio de agregação.' },
    { t: 'Fornecer a lista nominal de afastados por diagnóstico para que a diretoria calcule o próprio indicador.', ok: false,
      why: 'Errada. Entregar diagnóstico nominal viola o sigilo profissional.' },
    { t: 'Recusar qualquer indicador econômico, pois a saúde não deve ser mensurada em termos de custo.', ok: false,
      why: 'Errada. Recusar o diálogo econômico enfraquece a prevenção; o problema não é medir custo, é expor dado individual.' },
    { t: 'Substituir os indicadores de saúde por metas de produtividade, mais compreensíveis para a diretoria.', ok: false,
      why: 'Errada. Trocar o objeto do relatório descaracteriza sua função de vigilância da saúde.' },
    { t: 'Apresentar apenas o número total de exames realizados, indicador suficiente para demonstrar a efetividade do programa.', ok: false,
      why: 'Errada. Volume de exames é indicador de processo e não mede efetividade sobre a saúde.' }
  ],
  comentario: 'A questão testa a competência de comunicação do médico do trabalho: falar a linguagem da gestão sem violar sigilo e sem reduzir o relatório a contagem de exames.',
  pegadinha: 'Contar exames realizados é o indicador mais fácil e o mais enganoso: mede atividade, não resultado.',
  refs: ['Gestão em saúde do trabalhador — indicadores', 'Código de Ética Médica'] },

{ id: 'q-1.1-027', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de call center pede ao médico do trabalho que "coloque no atestado de saúde ocupacional" que ele tem transtorno de ansiedade, para justificar mudança de setor. A conduta correta é:',
  alts: [
    { t: 'Explicar que o documento de aptidão não registra diagnóstico e, se houver justificativa técnica, expressar a necessidade como restrição funcional específica, com fundamentação no prontuário.', ok: true,
      why: 'Correta. O documento de aptidão comunica capacidade e restrições; o diagnóstico permanece no prontuário sob sigilo. A restrição bem descrita atinge o objetivo legítimo sem expor a doença.' },
    { t: 'Atender ao pedido, pois havendo consentimento expresso do trabalhador não há violação de sigilo.', ok: false,
      why: 'Errada. Mesmo com consentimento, o documento de aptidão não é veículo de diagnóstico, e a exposição tende a gerar prejuízo ao próprio trabalhador.' },
    { t: 'Negar qualquer registro e encaminhar o trabalhador ao setor de recursos humanos para pleitear a mudança administrativamente.', ok: false,
      why: 'Errada. Se há fundamento clínico, a avaliação médica deve produzir a restrição pertinente, e não delegar a decisão técnica ao setor administrativo.' },
    { t: 'Registrar o diagnóstico em código de classificação internacional de doenças, o que preserva o sigilo por ser codificado.', ok: false,
      why: 'Errada. Codificar não protege: o código é decodificável e sua inclusão sem autorização legal expõe informação sensível.' },
    { t: 'Emitir atestado de afastamento por tempo indeterminado até que a empresa promova a mudança de setor.', ok: false,
      why: 'Errada. Afastamento não é instrumento de negociação de posto de trabalho e desvirtua a função do atestado.' }
  ],
  comentario: 'A questão cobra a tradução do achado clínico em linguagem de aptidão. Restrição funcional é o instrumento que concilia proteção do trabalhador, necessidade da empresa e sigilo.',
  pegadinha: 'O consentimento do trabalhador parece resolver tudo, mas o documento de aptidão simplesmente não é o lugar do diagnóstico.',
  refs: ['Código de Ética Médica', 'Normas Regulamentadoras — controle médico de saúde ocupacional'] },

{ id: 'q-1.1-028', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma transportadora quer implantar um programa de exames em motoristas com base em recomendação de um fornecedor de laboratório, que sugere painel amplo de exames laboratoriais anuais para todos. O médico do trabalho avalia a proposta. A análise tecnicamente correta é:',
  alts: [
    { t: 'Exames ocupacionais devem ser selecionados a partir dos riscos identificados e das exigências da função, e não por pacote comercial padronizado, sob pena de gerar achados irrelevantes e dano por sobrediagnóstico.', ok: true,
      why: 'Correta. A indicação de exame decorre do risco e da função; painéis amplos indiscriminados aumentam falsos-positivos, investigações desnecessárias e custo sem benefício.' },
    { t: 'Quanto mais exames, melhor a proteção do trabalhador e maior a segurança jurídica da empresa.', ok: false,
      why: 'Errada. Excesso de exames não equivale a proteção; pode gerar dano e não substitui controle de risco no ambiente.' },
    { t: 'O painel amplo é aceitável porque a legislação estabelece rol mínimo, e exceder o mínimo é sempre permitido e recomendável.', ok: false,
      why: 'Errada. Exceder o mínimo é possível, mas cada exame precisa de justificativa técnica; a permissão formal não torna a prática recomendável.' },
    { t: 'A escolha dos exames é atribuição do laboratório contratado, por deter conhecimento técnico laboratorial.', ok: false,
      why: 'Errada. A indicação é ato médico vinculado ao programa de controle médico, não decisão do prestador de exames.' },
    { t: 'Exames laboratoriais anuais dispensam a avaliação clínica periódica, pois são mais objetivos.', ok: false,
      why: 'Errada. O exame clínico é o eixo da avaliação ocupacional; complementares são auxiliares.' }
  ],
  comentario: 'O núcleo é a indicação orientada por risco. Rastreamento indiscriminado no ambiente ocupacional gera sobrediagnóstico, ansiedade e custo, e desvia recursos do controle do risco na fonte.',
  pegadinha: 'A intuição "mais exame protege mais" é o erro mais comum na gestão de programas ocupacionais.',
  refs: ['Normas Regulamentadoras — controle médico de saúde ocupacional', 'Prevenção quaternária'] },

{ id: 'q-1.1-029', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um médico do trabalho é convidado a integrar o quadro de uma empresa de consultoria que atende múltiplas indústrias químicas. Sobre o exercício da autonomia técnica nesse arranjo, é CORRETO afirmar:',
  alts: [
    { t: 'A autonomia técnica do médico deve ser assegurada independentemente do vínculo contratual, e a relação comercial entre consultoria e cliente não pode condicionar conclusões médicas.', ok: true,
      why: 'Correta. A independência profissional é princípio estruturante da atuação em saúde ocupacional, qualquer que seja a forma de contratação.' },
    { t: 'Em contrato de consultoria, as conclusões médicas devem ser previamente validadas pelo cliente contratante.', ok: false,
      why: 'Errada. Submeter conclusão médica à validação do contratante suprime a independência técnica.' },
    { t: 'A autonomia técnica só existe quando o médico é empregado direto da empresa avaliada.', ok: false,
      why: 'Errada. É o inverso: o vínculo direto tende a gerar mais pressão, e a autonomia deve ser garantida em qualquer arranjo.' },
    { t: 'A consultoria pode padronizar as conclusões de aptidão para reduzir variabilidade entre médicos.', ok: false,
      why: 'Errada. Protocolos podem orientar, mas conclusão de aptidão é individualizada e não pode ser predefinida administrativamente.' },
    { t: 'A autonomia técnica autoriza o médico a descumprir a norma regulamentadora quando discordar dela.', ok: false,
      why: 'Errada. Autonomia técnica não é licença para descumprimento normativo; é liberdade de juízo dentro do marco legal.' }
  ],
  comentario: 'A questão delimita a autonomia técnica: ela protege o juízo médico contra pressão comercial e hierárquica, mas não autoriza descumprir norma nem padronizar conclusões individuais.',
  pegadinha: 'Duas alternativas testam os limites opostos da autonomia: submetê-la ao cliente ou transformá-la em licença para ignorar normas.',
  refs: ['Código de Ética Médica', 'Código internacional de ética para profissionais de saúde ocupacional (ICOH)'] },

{ id: 'q-1.1-030', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa quer implantar avaliação ocupacional a distância para trabalhadores administrativos em regime remoto. O médico do trabalho é consultado. Assinale a afirmativa INCORRETA sobre essa possibilidade:',
  alts: [
    { t: 'A avaliação a distância pode substituir integralmente o exame clínico presencial em qualquer função, desde que haja consentimento do trabalhador.', ok: true,
      why: 'É a afirmativa incorreta e, portanto, a resposta. O consentimento não supre a necessidade de exame presencial quando a função ou o risco exigem avaliação física direta.' },
    { t: 'A modalidade a distância exige registro adequado, identificação segura das partes e garantia de privacidade da comunicação.', ok: false,
      why: 'Verdadeira. Identificação, registro e privacidade são requisitos essenciais da prática a distância.' },
    { t: 'A decisão sobre a pertinência da modalidade cabe ao médico, considerando risco, função e necessidade de exame físico.', ok: false,
      why: 'Verdadeira. A pertinência é juízo médico e não decisão administrativa.' },
    { t: 'Riscos ergonômicos do trabalho remoto continuam sendo objeto de avaliação e orientação, ainda que o local seja o domicílio.', ok: false,
      why: 'Verdadeira. O trabalho remoto não elimina risco ergonômico nem a responsabilidade de orientação.' },
    { t: 'Achados que exijam exame físico devem motivar convocação presencial complementar.', ok: false,
      why: 'Verdadeira. A modalidade a distância deve prever encaminhamento presencial quando necessário.' }
  ],
  comentario: 'A questão cobra o limite da avaliação a distância: ela é ferramenta, não substituto universal. Consentimento não converte modalidade inadequada em adequada quando o risco exige exame físico.',
  pegadinha: 'A palavra "consentimento" costuma ser lida como autorização suficiente para qualquer arranjo, o que não se sustenta tecnicamente.',
  refs: ['Resoluções do CFM sobre telemedicina', 'Normas Regulamentadoras — controle médico de saúde ocupacional'] },

{ id: 'q-1.1-031', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um frigorífico registra aumento expressivo de queixas osteomusculares. A direção pede ao médico do trabalho que "avalie melhor os candidatos na admissão para não contratar quem já tem problema de coluna". A resposta tecnicamente e eticamente correta é:',
  alts: [
    { t: 'A seleção admissional não é instrumento válido de controle do adoecimento coletivo; o aumento das queixas indica necessidade de intervenção na organização e no posto de trabalho.', ok: true,
      why: 'Correta. Transferir o problema para a seleção de trabalhadores é deslocar a causa e tende à exclusão; o adoecimento coletivo aponta para determinantes do processo de trabalho.' },
    { t: 'A triagem admissional rigorosa é a medida de maior custo-efetividade para reduzir DORT em linhas de produção.', ok: false,
      why: 'Errada. Não há sustentação técnica para isso; a exposição continua atuando sobre quem for contratado.' },
    { t: 'Exames de imagem de coluna na admissão permitem prever com boa acurácia quem desenvolverá lombalgia ocupacional.', ok: false,
      why: 'Errada. Achados de imagem têm baixa capacidade preditiva individual e alta prevalência em assintomáticos.' },
    { t: 'A recusa de contratação por achado de imagem é legítima quando documentada por laudo médico.', ok: false,
      why: 'Errada. Documentar o achado não legitima exclusão baseada em risco presumido, prática de caráter discriminatório.' },
    { t: 'Basta condicionar a admissão à assinatura de termo de responsabilidade do candidato sobre queixas prévias.', ok: false,
      why: 'Errada. Termo de responsabilidade não transfere ao trabalhador o risco gerado pelo processo de trabalho.' }
  ],
  comentario: 'O tema central é o desvio histórico da especialidade: usar o exame admissional como filtro de risco individual em vez de intervir no processo de trabalho. Achados de imagem de coluna são frequentes em assintomáticos e não predizem incapacidade.',
  pegadinha: 'A alternativa que fala em laudo documentado dá aparência de legalidade a uma prática discriminatória.',
  refs: ['Normas Regulamentadoras — ergonomia', 'Protocolo de DORT — Ministério da Saúde'] },

{ id: 'q-1.1-032', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um estudante de medicina pergunta ao preceptor por que a medicina do trabalho é considerada especialidade com forte componente coletivo, diferentemente da maioria das especialidades clínicas. A explicação correta é:',
  alts: [
    { t: 'Porque seu objeto inclui populações de trabalhadores expostas a riscos comuns, exigindo raciocínio epidemiológico e intervenções sobre o ambiente, além do cuidado individual.', ok: true,
      why: 'Correta. A especialidade combina clínica individual com análise populacional e ação sobre determinantes ambientais e organizacionais.' },
    { t: 'Porque o médico do trabalho não realiza atendimento individual, dedicando-se apenas a inspeções.', ok: false,
      why: 'Errada. Há atendimento individual relevante; o componente coletivo se soma, não substitui.' },
    { t: 'Porque as doenças relacionadas ao trabalho são sempre infectocontagiosas e exigem controle de surtos.', ok: false,
      why: 'Errada. As doenças relacionadas ao trabalho são majoritariamente não transmissíveis.' },
    { t: 'Porque a especialidade é exercida exclusivamente em serviços públicos de vigilância.', ok: false,
      why: 'Errada. A atuação ocorre em empresas, serviços públicos, perícia e academia.' },
    { t: 'Porque a legislação proíbe o médico do trabalho de estabelecer diagnóstico individual.', ok: false,
      why: 'Errada. Não há tal proibição; o médico do trabalho estabelece diagnósticos e nexos.' }
  ],
  comentario: 'A resposta reúne os dois planos da especialidade: o indivíduo exposto e o coletivo de trabalhadores sob o mesmo processo de trabalho. Esse duplo olhar é o que exige domínio de epidemiologia.',
  pegadinha: 'Distratores empurram para extremos: ou nega o atendimento individual, ou nega o componente coletivo.',
  refs: ['Mendes, R. — Patologia do Trabalho'] },

{ id: 'q-1.1-033', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Após um surto de intoxicação por agrotóxico em uma fazenda, o médico do trabalho da empresa produtora é procurado pela imprensa. Sobre sua conduta, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'O médico deve fornecer à imprensa a evolução clínica dos intoxicados, pois há interesse público envolvido no episódio.', ok: true,
      why: 'É a afirmativa incorreta e, portanto, a resposta. Interesse público na ocorrência não autoriza divulgação de dados clínicos identificáveis; a comunicação deve ser institucional e sem exposição de pacientes.' },
    { t: 'A ocorrência deve ser notificada às autoridades sanitárias competentes.', ok: false,
      why: 'Verdadeira. Intoxicação exógena relacionada ao trabalho é agravo de notificação e alimenta a vigilância.' },
    { t: 'A investigação deve buscar as causas no processo de trabalho, incluindo armazenamento, diluição e aplicação do produto.', ok: false,
      why: 'Verdadeira. A análise do processo é o que permite intervenção efetiva e evita atribuição isolada a erro individual.' },
    { t: 'Os trabalhadores expostos, mesmo assintomáticos, devem ser avaliados e acompanhados.', ok: false,
      why: 'Verdadeira. A avaliação de expostos assintomáticos é parte da resposta ao evento.' },
    { t: 'A empresa deve emitir a comunicação de acidente do trabalho para os casos caracterizados.', ok: false,
      why: 'Verdadeira. Intoxicação aguda relacionada ao trabalho caracteriza acidente do trabalho para fins de comunicação.' }
  ],
  comentario: 'A questão combina resposta a evento agudo (notificação, investigação do processo, avaliação de expostos, comunicação previdenciária) com o limite ético da comunicação pública: não se divulga dado clínico identificável.',
  pegadinha: 'A expressão "interesse público" é usada como falso fundamento para quebra de sigilo.',
  refs: ['Código de Ética Médica', 'SINAN — intoxicação exógena', 'Lei nº 8.213/1991'] },

{ id: 'q-1.1-034', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma multinacional impõe à filial brasileira um protocolo corporativo de saúde ocupacional elaborado no exterior, que prevê exames e periodicidades diferentes das exigidas no país. O médico do trabalho local deve:',
  alts: [
    { t: 'Cumprir a exigência normativa nacional como piso e incorporar o protocolo corporativo apenas naquilo que o complemente e tenha justificativa técnica.', ok: true,
      why: 'Correta. Norma nacional é obrigatória e funciona como patamar mínimo; políticas corporativas podem acrescentar, nunca reduzir.' },
    { t: 'Adotar integralmente o protocolo corporativo, por ser padrão internacional mais avançado.', ok: false,
      why: 'Errada. Padrão estrangeiro não afasta obrigação legal local, e nem sempre é mais protetivo no contexto nacional.' },
    { t: 'Recusar qualquer elemento do protocolo estrangeiro, por não ter validade no país.', ok: false,
      why: 'Errada. Elementos adicionais com base técnica podem ser incorporados sem prejuízo da norma nacional.' },
    { t: 'Submeter a divergência ao setor jurídico e suspender o programa até decisão.', ok: false,
      why: 'Errada. Suspender o programa deixaria trabalhadores desassistidos; a obrigação legal permanece exigível durante a discussão.' },
    { t: 'Aplicar o protocolo corporativo aos expatriados e a norma nacional aos demais, criando dois regimes.', ok: false,
      why: 'Errada. A norma nacional alcança todos os trabalhadores no território, independentemente da nacionalidade.' }
  ],
  comentario: 'O princípio é simples e muito cobrado: norma nacional é piso inderrogável; política corporativa pode elevar o padrão, jamais rebaixá-lo, e não cria regimes distintos por origem do trabalhador.',
  pegadinha: 'A ideia de que padrão internacional "é sempre mais avançado" leva à adoção acrítica e ao descumprimento legal.',
  refs: ['Normas Regulamentadoras', 'OIT — Serviços de Saúde no Trabalho'] },

{ id: 'q-1.1-035', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma pequena empresa de marcenaria com 12 empregados, o proprietário afirma que "não precisa de nada de medicina do trabalho porque é microempresa". O médico consultor esclarece que:',
  alts: [
    { t: 'A dispensa de determinadas estruturas e documentos para empresas de menor porte não elimina a obrigação de identificar riscos e realizar o controle médico compatível com as exposições existentes.', ok: true,
      why: 'Correta. O tratamento diferenciado por porte simplifica exigências formais, mas o dever de prevenção e de vigilância da saúde persiste, especialmente com riscos como poeira de madeira e ruído.' },
    { t: 'Microempresas estão integralmente dispensadas de exames ocupacionais e de avaliação de riscos.', ok: false,
      why: 'Errada. Não há dispensa integral; a simplificação é de forma e não de substância.' },
    { t: 'A obrigação só surge quando ocorrer o primeiro acidente registrado no estabelecimento.', ok: false,
      why: 'Errada. A obrigação é preventiva e anterior à ocorrência de qualquer evento.' },
    { t: 'Basta que o proprietário assine declaração de inexistência de riscos para afastar as obrigações.', ok: false,
      why: 'Errada. Declaração não substitui identificação técnica de riscos; e na marcenaria há riscos evidentes.' },
    { t: 'A responsabilidade recai sobre o sindicato patronal, que deve prestar o serviço a todas as microempresas filiadas.', ok: false,
      why: 'Errada. A responsabilidade é do empregador; apoio sindical pode existir, mas não transfere o dever.' }
  ],
  comentario: 'A questão cobra a distinção entre simplificação por porte e dispensa de obrigações. Marcenaria concentra riscos relevantes, o que torna a alegação de dispensa ainda mais frágil.',
  pegadinha: 'A ideia de "declaração de inexistência de riscos" é atalho comum e juridicamente inócuo quando os riscos são evidentes.',
  refs: ['Normas Regulamentadoras — gerenciamento de riscos e controle médico'] },

{ id: 'q-1.1-036', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Durante processo seletivo, uma candidata informa ao médico examinador que está grávida e pede que a informação não seja repassada à empresa. A conduta correta do médico do trabalho é:',
  alts: [
    { t: 'Preservar a informação, comunicando à empresa apenas a aptidão e eventuais restrições relacionadas às exigências da função, sem revelar a gestação.', ok: true,
      why: 'Correta. A gestação é dado clínico protegido por sigilo; sua revelação não é necessária para o juízo de aptidão e favorece discriminação.' },
    { t: 'Informar a empresa, pois a gestação altera a exposição permitida e o empregador precisa saber para se proteger juridicamente.', ok: false,
      why: 'Errada. A adequação da exposição pode ser assegurada por restrição funcional, sem revelar a condição.' },
    { t: 'Considerar a candidata inapta, pois a gestação impede a admissão em ambiente industrial.', ok: false,
      why: 'Errada. Gestação não é causa de inaptidão genérica; a análise é sobre exposições específicas e admite adequação.' },
    { t: 'Solicitar teste de gravidez a todas as candidatas para padronizar a conduta.', ok: false,
      why: 'Errada. Exigência de teste de gravidez em seleção é prática discriminatória vedada.' },
    { t: 'Adiar a conclusão do exame até o fim da gestação.', ok: false,
      why: 'Errada. Adiar equivale a obstar o acesso ao emprego por condição fisiológica.' }
  ],
  comentario: 'O caso reúne sigilo e não discriminação: informa-se aptidão e restrição, nunca a condição; e gestação não gera inaptidão genérica, mas eventual adequação de exposição.',
  pegadinha: 'O argumento de "proteção jurídica da empresa" é usado para justificar revelação desnecessária de dado sensível.',
  refs: ['Código de Ética Médica', 'CLT — proteção à maternidade'] },

{ id: 'q-1.1-037', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de medicina do trabalho terceirizado atende 200 empresas e emite documentos de aptidão em larga escala, com consultas de poucos minutos. Sobre a qualidade dessa prática, a crítica tecnicamente mais precisa é:',
  alts: [
    { t: 'A avaliação ocupacional só cumpre sua função se for capaz de reconhecer a exposição do trabalhador e articular achados clínicos ao risco da função; volume elevado com tempo insuficiente inviabiliza esse juízo e transforma o exame em ato cartorial.', ok: true,
      why: 'Correta. O valor do exame ocupacional está na correlação entre achado clínico e exposição; sem tempo e sem informação sobre o posto, o documento perde significado técnico.' },
    { t: 'O problema é exclusivamente jurídico, pois a norma estabelece tempo mínimo de consulta ocupacional.', ok: false,
      why: 'Errada. A crítica pertinente é de qualidade técnica; não se deve invocar parâmetro de tempo mínimo inexistente.' },
    { t: 'A prática é adequada se os exames complementares forem realizados em laboratório certificado.', ok: false,
      why: 'Errada. Qualidade laboratorial não compensa ausência de avaliação clínica contextualizada.' },
    { t: 'A crítica não procede, pois trabalhadores administrativos não exigem avaliação detalhada.', ok: false,
      why: 'Errada. Generalizar a dispensa de avaliação por categoria administrativa ignora riscos ergonômicos e psicossociais.' },
    { t: 'O uso de questionário autoaplicado antes da consulta elimina a necessidade de avaliação médica.', ok: false,
      why: 'Errada. Questionário é ferramenta de triagem e apoio, não substituto do juízo médico.' }
  ],
  comentario: 'A crítica ao "exame de carimbo" deve ser feita pelo conteúdo: sem conhecimento da exposição e sem tempo de correlação clínica, não há avaliação ocupacional, apenas documento.',
  pegadinha: 'Uma alternativa inventa parâmetro normativo de tempo mínimo; cuidado com distratores que fabricam número onde a crítica é conceitual.',
  refs: ['Normas Regulamentadoras — controle médico de saúde ocupacional', 'Código de Ética Médica'] },

{ id: 'q-1.1-038', tema: '1.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria petroquímica pretende integrar o serviço de medicina do trabalho ao programa de gerenciamento de riscos. O médico propõe que os achados clínicos alimentem a revisão do inventário de riscos. Sobre essa proposta, é CORRETO afirmar:',
  alts: [
    { t: 'A integração é adequada, pois achados de saúde funcionam como indicador de efetividade das medidas de controle e podem revelar exposições não identificadas na avaliação ambiental.', ok: true,
      why: 'Correta. O ciclo de gestão de riscos se retroalimenta: dados de saúde sinalizam falhas de controle e exposições subestimadas, exigindo revisão do inventário.' },
    { t: 'A integração é inadequada, pois dados de saúde são sigilosos e não podem influenciar decisões de engenharia.', ok: false,
      why: 'Errada. Dados agregados podem e devem orientar decisões técnicas sem violar sigilo individual.' },
    { t: 'O inventário de riscos deve basear-se exclusivamente em medições ambientais quantitativas.', ok: false,
      why: 'Errada. Avaliação qualitativa, análise do processo e dados de saúde compõem o reconhecimento de riscos.' },
    { t: 'Achados de saúde só devem gerar revisão do inventário quando houver diagnóstico confirmado de doença ocupacional.', ok: false,
      why: 'Errada. Sinais precoces e alterações subclínicas já justificam revisão; esperar diagnóstico confirmado é intervir tarde demais.' },
    { t: 'A revisão do inventário compete apenas ao engenheiro de segurança, cabendo ao médico apenas comunicar casos.', ok: false,
      why: 'Errada. O gerenciamento de riscos é multiprofissional e a contribuição médica é parte do processo, não mero repasse de casos.' }
  ],
  comentario: 'O ponto é a retroalimentação entre vigilância da saúde e gerenciamento de riscos: alteração precoce em trabalhador é sinal de falha de controle e deve disparar revisão da avaliação ambiental.',
  pegadinha: 'Exigir diagnóstico confirmado para revisar o inventário é o erro mais sedutor: parece rigor técnico, mas atrasa a prevenção.',
  refs: ['Normas Regulamentadoras — gerenciamento de riscos ocupacionais e controle médico'] },
{ id: 'q-1.2-010', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um serviço de referência analisa por que trabalhadores de uma mesma empresa, com o mesmo posto, adoecem de forma diferente conforme sejam efetivos ou terceirizados. Um técnico propõe explicar o achado pela determinação social do processo saúde-doença. Essa perspectiva sustenta que:',
  alts: [
    { t: 'As condições de inserção no trabalho, o vínculo, a renda e o poder de negociação atuam como determinantes do adoecimento, para além da exposição física idêntica no posto.', ok: true,
      why: 'Correta. A determinação social entende o adoecimento como produto de relações sociais de produção, e não apenas da presença de um agente no ambiente.' },
    { t: 'A diferença é explicada apenas pela suscetibilidade genética individual dos trabalhadores.', ok: false,
      why: 'Errada. A explicação puramente biológica individual é justamente o que a perspectiva da determinação social critica por insuficiência.' },
    { t: 'A determinação social nega o papel dos agentes de risco físicos e químicos no adoecimento.', ok: false,
      why: 'Errada. Não há negação do agente; há incorporação do contexto social que modula exposição, vulnerabilidade e desfecho.' },
    { t: 'A explicação está no acaso, já que a exposição no posto é idêntica para todos.', ok: false,
      why: 'Errada. Atribuir ao acaso ignora diferenças sistemáticas de vínculo, jornada, treinamento e rotatividade.' },
    { t: 'A determinação social aplica-se apenas a doenças infecciosas, não a agravos ocupacionais.', ok: false,
      why: 'Errada. O conceito é geral e tem aplicação central em saúde do trabalhador.' }
  ],
  comentario: 'A determinação social não substitui a análise do agente; ela a insere em relações sociais concretas. Terceirização, precariedade e rotatividade produzem exposições e vulnerabilidades diferentes no mesmo posto.',
  pegadinha: 'A armadilha é ler determinação social como negação do risco físico-químico. Ela é ampliação do olhar, não substituição.',
  refs: ['Determinação social do processo saúde-doença', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.2-011', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um sindicato de químicos organiza grupos de trabalhadores para mapear coletivamente as exposições em uma fábrica, produzindo um "mapa de risco" construído pelos próprios operários. Essa prática se inspira diretamente:',
  alts: [
    { t: 'No modelo operário italiano, que valoriza o saber do trabalhador sobre seu processo de trabalho e a validação consensual do conhecimento pelo grupo homogêneo.', ok: true,
      why: 'Correta. O modelo operário italiano estrutura-se na experiência operária, no grupo homogêneo e na validação consensual, recusando a delegação exclusiva ao especialista.' },
    { t: 'No modelo taylorista de organização científica do trabalho, que padroniza tarefas a partir da observação dos operários.', ok: false,
      why: 'Errada. O taylorismo expropria o saber operário e o transfere à gerência, sentido oposto ao da experiência descrita.' },
    { t: 'Na escola de higiene industrial norte-americana, que fundamenta a avaliação exclusivamente na medição instrumental.', ok: false,
      why: 'Errada. A ênfase instrumental é justamente o que o modelo operário questiona como insuficiente e monopolizado pelo especialista.' },
    { t: 'No modelo biomédico de causalidade, que atribui o adoecimento a um agente único e mensurável.', ok: false,
      why: 'Errada. O modelo descrito é participativo e multicausal, não unicausal.' },
    { t: 'Na abordagem comportamental de segurança, centrada na correção do ato inseguro do trabalhador.', ok: false,
      why: 'Errada. A abordagem comportamental responsabiliza o indivíduo; o modelo operário analisa o processo de trabalho coletivamente.' }
  ],
  comentario: 'O modelo operário italiano é a matriz da participação dos trabalhadores no reconhecimento dos riscos e influenciou fortemente o campo brasileiro da saúde do trabalhador, inclusive a prática de mapa de risco.',
  pegadinha: 'Taylorismo também "observa o operário", mas para expropriar seu saber. A inversão de finalidade é o que a questão testa.',
  refs: ['Modelo operário italiano', 'Oddone — Ambiente de trabalho'] },

{ id: 'q-1.2-012', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma capacitação, pede-se que os participantes ordenem historicamente três paradigmas: Medicina do Trabalho, Saúde Ocupacional e Saúde do Trabalhador. A caracterização CORRETA é:',
  alts: [
    { t: 'Medicina do Trabalho centrada no médico e na adaptação do trabalhador; Saúde Ocupacional multiprofissional e centrada na higiene e no controle do ambiente; Saúde do Trabalhador centrada no processo de trabalho e na participação dos trabalhadores.', ok: true,
      why: 'Correta. É a sequência clássica de deslocamento do objeto e do sujeito da ação, com ampliação progressiva do escopo.' },
    { t: 'Saúde Ocupacional é o paradigma mais recente, tendo superado a Saúde do Trabalhador ao incorporar normas internacionais de gestão.', ok: false,
      why: 'Errada. A ordem está invertida: a Saúde do Trabalhador é o desenvolvimento posterior no contexto brasileiro.' },
    { t: 'Os três termos designam a mesma prática, com nomes diferentes conforme o país.', ok: false,
      why: 'Errada. Há diferenças de objeto, de sujeito e de inserção institucional entre os paradigmas.' },
    { t: 'A Medicina do Trabalho é o paradigma mais amplo, pois abrange vigilância de ambientes e participação social.', ok: false,
      why: 'Errada. Vigilância de ambientes e participação social são marcas da Saúde do Trabalhador.' },
    { t: 'A Saúde do Trabalhador é sinônimo de perícia previdenciária, por tratar do reconhecimento de direitos.', ok: false,
      why: 'Errada. Reconhecimento de direitos é uma das dimensões, mas o campo é bem mais amplo que a atividade pericial.' }
  ],
  comentario: 'A sequência conceitual é cobrada com frequência: unidisciplinar e adaptativa, depois multiprofissional e ambiental, depois social e participativa. Cada etapa amplia o objeto sem eliminar as anteriores.',
  pegadinha: 'A inversão cronológica entre Saúde Ocupacional e Saúde do Trabalhador é o distrator principal.',
  refs: ['Mendes, R.; Dias, E. C. — Da medicina do trabalho à saúde do trabalhador'] },

{ id: 'q-1.2-013', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pesquisadora afirma que "o trabalho é categoria analítica central para compreender o adoecimento contemporâneo". Um colega discorda, dizendo que o desemprego e o trabalho por aplicativo tornaram a categoria obsoleta. A análise CORRETA é:',
  alts: [
    { t: 'As novas formas de organização, como o trabalho intermediado por plataformas, ampliam a relevância da categoria trabalho, pois criam exposições, jornadas e vínculos que produzem adoecimento com padrões próprios.', ok: true,
      why: 'Correta. Mudanças na forma de organizar o trabalho não eliminam sua centralidade; deslocam os mecanismos de adoecimento e exigem novos instrumentos de análise.' },
    { t: 'A categoria trabalho perde sentido quando não há vínculo empregatício formal, restando apenas análise de comportamento individual.', ok: false,
      why: 'Errada. A ausência de vínculo formal é ela própria uma característica do trabalho contemporâneo e produz efeitos sobre a saúde.' },
    { t: 'Trabalhadores de plataforma não estão expostos a riscos ocupacionais relevantes por definirem seus próprios horários.', ok: false,
      why: 'Errada. Autonomia formal convive com pressão algorítmica, jornadas extensas e riscos de trânsito e ergonômicos.' },
    { t: 'A análise do trabalho deve ser substituída pela análise de estilo de vida, mais adequada às doenças crônicas atuais.', ok: false,
      why: 'Errada. Reduzir a doença crônica a estilo de vida individual apaga determinantes ocupacionais como turnos, ritmo e estresse.' },
    { t: 'A categoria trabalho só se aplica à produção industrial, não a serviços e trabalho imaterial.', ok: false,
      why: 'Errada. Serviços e trabalho intelectual estão plenamente incluídos e concentram parte importante do adoecimento atual.' }
  ],
  comentario: 'A questão sustenta a centralidade do trabalho como categoria analítica mesmo diante de vínculos atípicos. A precarização é objeto de análise, não sinal de irrelevância da categoria.',
  pegadinha: 'A alternativa do estilo de vida é o distrator mais forte porque reproduz o discurso de individualização do risco.',
  refs: ['Saúde do trabalhador — trabalho como categoria analítica', 'OIT — trabalho em plataformas digitais'] },

{ id: 'q-1.2-014', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em um conselho municipal de saúde, discute-se a criação de uma comissão intersetorial de saúde do trabalhador com participação de trabalhadores. Sobre o controle social nesse campo, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'O controle social em saúde do trabalhador é exercido por técnicos especializados, cabendo aos trabalhadores apenas o papel de informantes sobre suas condições de trabalho.', ok: true,
      why: 'É a afirmativa incorreta e, portanto, a resposta. O controle social pressupõe participação deliberativa dos trabalhadores e da sociedade, não papel meramente informativo.' },
    { t: 'A participação dos trabalhadores qualifica o reconhecimento dos riscos, por trazer o conhecimento da atividade real.', ok: false,
      why: 'Verdadeira. O saber da experiência revela aspectos do trabalho real invisíveis na prescrição.' },
    { t: 'As instâncias de participação previstas no sistema público de saúde alcançam o tema da saúde do trabalhador.', ok: false,
      why: 'Verdadeira. Conselhos e conferências abrangem a saúde do trabalhador como parte da política de saúde.' },
    { t: 'A intersetorialidade com trabalho, previdência e meio ambiente é característica da política do setor.', ok: false,
      why: 'Verdadeira. A articulação intersetorial é traço estruturante da política nacional da área.' },
    { t: 'A participação sindical é uma das formas historicamente relevantes de organização da demanda por saúde no trabalho.', ok: false,
      why: 'Verdadeira. O movimento sindical teve papel decisivo na constituição do campo no Brasil.' }
  ],
  comentario: 'Controle social é participação deliberativa. Reduzir o trabalhador a informante é exatamente o que o campo da saúde do trabalhador recusa desde sua origem.',
  pegadinha: 'A afirmativa incorreta parece elogiosa à participação, mas rebaixa o trabalhador de sujeito a fonte de dados.',
  refs: ['Lei nº 8.142/1990', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-1.2-015', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de aplicativo de entregas sofre acidente de trânsito durante uma corrida e procura a unidade básica de saúde. O médico se pergunta se o caso pertence ao campo da saúde do trabalhador. A abordagem correta é:',
  alts: [
    { t: 'Sim; o campo da saúde do trabalhador abrange todos os trabalhadores independentemente de vínculo, e o caso deve ser registrado como agravo relacionado ao trabalho, com investigação das condições em que a atividade é executada.', ok: true,
      why: 'Correta. A ausência de vínculo empregatício não retira o caráter ocupacional do agravo nem o dever de registro e de atenção no sistema público.' },
    { t: 'Não; sem vínculo empregatício não há acidente de trabalho nem agravo relacionado ao trabalho para qualquer finalidade.', ok: false,
      why: 'Errada. Confunde a discussão previdenciária de cobertura com o reconhecimento sanitário do agravo relacionado ao trabalho.' },
    { t: 'Sim, mas apenas se o trabalhador contribuir para a previdência como contribuinte individual.', ok: false,
      why: 'Errada. O reconhecimento sanitário do agravo não depende da situação contributiva.' },
    { t: 'Não; acidentes de trânsito são sempre classificados como causas externas gerais, sem relação com o trabalho.', ok: false,
      why: 'Errada. Acidente de trânsito durante a atividade laboral é agravo relacionado ao trabalho.' },
    { t: 'Sim, mas a responsabilidade de registro é exclusiva da plataforma digital, não do serviço de saúde.', ok: false,
      why: 'Errada. O serviço de saúde que atende tem o dever de notificação do agravo relacionado ao trabalho.' }
  ],
  comentario: 'A questão separa dois planos que se confundem na prática: cobertura previdenciária e reconhecimento sanitário do agravo. O segundo independe do vínculo e do recolhimento.',
  pegadinha: 'A ligação automática entre "sem vínculo" e "não é acidente de trabalho" é o erro mais frequente entre médicos assistenciais.',
  refs: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora', 'SINAN — acidente de trabalho'] },

{ id: 'q-1.2-016', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma equipe de saúde da família identifica que muitos moradores adoecem por exposição a solventes em oficinas de fundo de quintal do bairro. Ao propor a intervenção, a equipe deve considerar que:',
  alts: [
    { t: 'Trabalho informal e domiciliar integra o objeto da saúde do trabalhador, e a abordagem territorial permite alcançar exposições que escapam à lógica da empresa formal.', ok: true,
      why: 'Correta. A base territorial da atenção primária é uma via privilegiada para alcançar trabalho informal, domiciliar e familiar, invisível às estruturas empresariais.' },
    { t: 'A atuação é inviável, pois sem empregador identificado não há a quem dirigir as ações de vigilância.', ok: false,
      why: 'Errada. A vigilância sanitária e a atenção à saúde alcançam estabelecimentos e situações de trabalho independentemente da existência de empregador formal.' },
    { t: 'O caso deve ser encaminhado exclusivamente à inspeção do trabalho, sem participação do setor saúde.', ok: false,
      why: 'Errada. A ação é intersetorial; a saúde tem competência própria em saúde do trabalhador.' },
    { t: 'A abordagem deve limitar-se à orientação individual sobre uso de máscara pelos moradores.', ok: false,
      why: 'Errada. Reduzir a intervenção a proteção individual ignora medidas coletivas e a análise do processo de trabalho.' },
    { t: 'Trabalho domiciliar não gera exposição relevante por ser realizado em pequena escala.', ok: false,
      why: 'Errada. Pequena escala frequentemente vem com ausência de ventilação e de controles, o que pode elevar a exposição.' }
  ],
  comentario: 'A questão destaca a potência da atenção primária de base territorial para o campo da saúde do trabalhador, especialmente diante do trabalho informal e domiciliar.',
  pegadinha: 'A associação entre pequena escala e baixo risco é intuitiva e falsa em ambientes sem controle de ventilação.',
  refs: ['RENAST', 'Atenção primária e saúde do trabalhador'] },

{ id: 'q-1.2-017', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao discutir saúde global e trabalho, um pesquisador aponta o fenômeno da transferência de riscos entre países. Esse fenômeno se caracteriza por:',
  alts: [
    { t: 'Deslocamento de processos produtivos perigosos para países com regulação mais frágil e menor capacidade de fiscalização, transferindo a carga de doença para populações trabalhadoras vulneráveis.', ok: true,
      why: 'Correta. A migração de atividades perigosas para contextos de regulação frágil é fenômeno descrito na literatura de saúde global do trabalho.' },
    { t: 'Aumento da exportação de tecnologias de proteção coletiva dos países periféricos para os centrais.', ok: false,
      why: 'Errada. O fluxo descrito na literatura é o inverso em termos de risco, e a afirmação não corresponde ao fenômeno.' },
    { t: 'Uniformização automática dos limites de exposição em todos os países por força de tratados comerciais.', ok: false,
      why: 'Errada. Não há uniformização automática; a heterogeneidade regulatória é justamente parte do problema.' },
    { t: 'Redução global do uso de amianto e agrotóxicos de forma simultânea em todos os países.', ok: false,
      why: 'Errada. O banimento é heterogêneo, e substâncias proibidas em alguns países seguem em uso em outros.' },
    { t: 'Migração de trabalhadores qualificados para países com melhores condições, sem repercussão sobre a carga de doença.', ok: false,
      why: 'Errada. A migração de trabalhadores é outro fenômeno e tem repercussões próprias sobre saúde.' }
  ],
  comentario: 'A transferência de riscos é conceito-chave em saúde global do trabalho: proibições locais podem conviver com manutenção do risco em outros territórios, o que exige olhar internacional.',
  pegadinha: 'A ideia de harmonização automática de limites por acordos comerciais é atraente e não corresponde à realidade regulatória.',
  refs: ['OMS/OIT — saúde global e trabalho', 'Carga global de doença atribuível ao trabalho'] },

{ id: 'q-1.2-018', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa apresenta campanha interna afirmando que "a maioria dos acidentes decorre de ato inseguro do trabalhador" e propõe premiação por comportamento seguro. Um médico do trabalho formado no campo da saúde do trabalhador critica a proposta porque:',
  alts: [
    { t: 'A atribuição do acidente ao ato inseguro individualiza a culpa, desloca a análise das condições e da organização do trabalho e tende a produzir subnotificação por medo de perder a premiação.', ok: true,
      why: 'Correta. Programas centrados em culpa individual reduzem registro sem reduzir risco e obscurecem falhas organizacionais e de projeto.' },
    { t: 'A premiação é vedada por norma, o que torna a campanha ilegal.', ok: false,
      why: 'Errada. A crítica pertinente é técnica e não se baseia em suposta vedação normativa a programas de incentivo.' },
    { t: 'O comportamento do trabalhador não tem qualquer influência sobre a ocorrência de acidentes.', ok: false,
      why: 'Errada. O comportamento influencia, mas é condicionado pelo projeto, pela organização e pela pressão de produção.' },
    { t: 'A campanha só seria válida se aplicada exclusivamente a trabalhadores terceirizados.', ok: false,
      why: 'Errada. Aplicar o modelo a um subgrupo agravaria a discriminação e não resolve o problema conceitual.' },
    { t: 'A crítica é infundada, pois a análise de causa raiz confirma que a maior parte dos eventos tem causa comportamental única.', ok: false,
      why: 'Errada. Análises de causa raiz consistentes revelam múltiplas causas latentes organizacionais por trás do erro humano.' }
  ],
  comentario: 'A crítica ao paradigma do ato inseguro é central: ele individualiza a responsabilidade, gera subnotificação por incentivo perverso e impede intervenção nas causas latentes.',
  pegadinha: 'Negar completamente a influência do comportamento é o exagero oposto e também está errado; a crítica correta é sobre o deslocamento da análise.',
  refs: ['Análise de acidentes — causas latentes', 'Saúde do trabalhador — crítica ao ato inseguro'] },

{ id: 'q-1.2-019', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao caracterizar o campo da Saúde do Trabalhador no Brasil, é CORRETO afirmar que sua inserção institucional principal ocorre:',
  alts: [
    { t: 'No sistema público de saúde, com competência constitucional e legal atribuída ao setor saúde para executar ações de saúde do trabalhador.', ok: true,
      why: 'Correta. O texto constitucional e a lei orgânica da saúde atribuem ao sistema público de saúde a execução de ações de saúde do trabalhador.' },
    { t: 'Exclusivamente nos serviços internos das empresas, por meio dos programas obrigatórios.', ok: false,
      why: 'Errada. Serviços internos executam obrigações empresariais, mas não constituem a inserção institucional do campo.' },
    { t: 'Na estrutura da previdência social, responsável pela concessão de benefícios acidentários.', ok: false,
      why: 'Errada. A previdência atua no reconhecimento de direitos, não como locus principal do campo sanitário.' },
    { t: 'Nas entidades sindicais, que detêm competência legal de fiscalização dos ambientes de trabalho.', ok: false,
      why: 'Errada. Sindicatos têm papel relevante de mobilização e acompanhamento, mas não competência estatal de fiscalização.' },
    { t: 'Nas agências reguladoras setoriais, responsáveis por definir os limites de exposição ocupacional.', ok: false,
      why: 'Errada. Limites ocupacionais no país decorrem sobretudo de normas trabalhistas e referências técnicas, não de agências setoriais.' }
  ],
  comentario: 'A inserção do campo no sistema público de saúde é o que o distingue do modelo empresarial e o que fundamenta a vigilância em saúde do trabalhador como ação de Estado.',
  pegadinha: 'Confundir onde o campo está institucionalmente inserido com quem executa obrigações empresariais é o erro plantado.',
  refs: ['Constituição Federal de 1988', 'Lei nº 8.080/1990'] },

{ id: 'q-1.2-020', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma trabalhadora de teleatendimento relata que a pressão por metas e a vigilância eletrônica constante geram sofrimento. O supervisor argumenta que "não há risco físico, portanto não há risco ocupacional". A análise correta é:',
  alts: [
    { t: 'A organização do trabalho é fonte de risco ocupacional, e fatores como ritmo, metas, controle excessivo e ausência de autonomia são reconhecidos como determinantes de adoecimento.', ok: true,
      why: 'Correta. Os fatores organizacionais e psicossociais integram o quadro de riscos ocupacionais reconhecidos, com repercussão mental e física.' },
    { t: 'Somente agentes físicos, químicos e biológicos configuram risco ocupacional, conforme a classificação clássica.', ok: false,
      why: 'Errada. A classificação clássica é incompleta e o reconhecimento de fatores ergonômicos e psicossociais é consolidado.' },
    { t: 'O sofrimento relatado é de natureza exclusivamente individual e deve ser tratado apenas em terapia externa.', ok: false,
      why: 'Errada. Encaminhamento clínico pode ser necessário, mas não substitui a intervenção nos determinantes organizacionais.' },
    { t: 'A ausência de diagnóstico psiquiátrico formal impede qualquer intervenção preventiva.', ok: false,
      why: 'Errada. Prevenção atua antes do adoecimento; exigir diagnóstico para agir inverte a lógica preventiva.' },
    { t: 'A vigilância eletrônica é medida neutra de gestão, sem efeito sobre a saúde.', ok: false,
      why: 'Errada. Monitoramento intensivo e ausência de margem de decisão estão associados a maior sofrimento e adoecimento.' }
  ],
  comentario: 'A questão trabalha a ampliação do conceito de risco ocupacional para a organização do trabalho. É um dos pontos em que a perspectiva da saúde do trabalhador se distancia do modelo higienista clássico.',
  pegadinha: 'Exigir diagnóstico psiquiátrico formal para agir é armadilha comum: prevenção não depende de doença instalada.',
  refs: ['Fatores de risco psicossociais no trabalho', 'Dejours — Psicodinâmica do trabalho'] },

{ id: 'q-1.2-021', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um gestor de saúde afirma que a diferença entre "saúde ocupacional" e "saúde do trabalhador" é irrelevante na prática cotidiana. Um técnico responde que a diferença tem consequências operacionais concretas. Assinale a consequência prática que melhor sustenta essa resposta:',
  alts: [
    { t: 'Sob a perspectiva da saúde do trabalhador, a análise de um agravo não se encerra no trabalhador atendido: dispara vigilância no ambiente, busca de casos semelhantes e intervenção sobre o processo de trabalho.', ok: true,
      why: 'Correta. A consequência operacional é a passagem do caso individual à ação coletiva sobre o processo de trabalho e à busca ativa de outros casos.' },
    { t: 'Sob a perspectiva da saúde do trabalhador, o atendimento clínico individual é dispensado.', ok: false,
      why: 'Errada. O cuidado individual permanece; o que muda é que ele não encerra a ação.' },
    { t: 'A diferença é apenas de nomenclatura de setores administrativos nas secretarias de saúde.', ok: false,
      why: 'Errada. A diferença é de objeto e de método, com efeitos operacionais concretos.' },
    { t: 'Sob a perspectiva da saúde ocupacional, a participação dos trabalhadores é obrigatória em todas as decisões técnicas.', ok: false,
      why: 'Errada. A participação como princípio é marca do campo da saúde do trabalhador, não do modelo ocupacional clássico.' },
    { t: 'A saúde do trabalhador substitui a avaliação quantitativa de exposições pela avaliação exclusivamente qualitativa.', ok: false,
      why: 'Errada. A avaliação quantitativa continua sendo instrumento; o campo agrega dimensões, não descarta métodos.' }
  ],
  comentario: 'A distinção conceitual só ganha valor quando traduzida em conduta: do caso índice à vigilância do ambiente e à busca de casos. Esse é o teste prático do paradigma.',
  pegadinha: 'Duas alternativas transformam a ampliação de escopo em abandono de instrumentos clínicos ou quantitativos, o que não ocorre.',
  refs: ['Mendes, R.; Dias, E. C. — Da medicina do trabalho à saúde do trabalhador', 'VISAT'] },

{ id: 'q-1.2-022', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a relação entre trabalho, desigualdade social e saúde, assinale a afirmativa INCORRETA:',
  alts: [
    { t: 'A elevação da renda média de um país elimina os gradientes de adoecimento relacionados à posição ocupacional.', ok: true,
      why: 'É a afirmativa incorreta e, portanto, a resposta. Gradientes sociais de saúde persistem mesmo em países ricos, associados à hierarquia ocupacional, ao controle sobre o trabalho e à posição relativa.' },
    { t: 'Trabalhadores em ocupações com menor controle sobre o próprio trabalho apresentam pior perfil de saúde, mesmo controlando renda.', ok: false,
      why: 'Verdadeira. O grau de controle é determinante independente descrito na literatura ocupacional.' },
    { t: 'A precarização do vínculo associa-se a maior exposição a riscos e menor acesso a proteção.', ok: false,
      why: 'Verdadeira. Vínculos precários concentram exposição e reduzem proteção social e sindical.' },
    { t: 'Trabalhadores informais têm menor acesso a diagnóstico e reconhecimento de doenças relacionadas ao trabalho.', ok: false,
      why: 'Verdadeira. A invisibilidade estatística e a ausência de vínculo dificultam reconhecimento e acesso a direitos.' },
    { t: 'A distribuição desigual da exposição a riscos ocupacionais contribui para as desigualdades gerais em saúde.', ok: false,
      why: 'Verdadeira. A exposição ocupacional é um dos mecanismos que produzem desigualdade em saúde entre grupos sociais.' }
  ],
  comentario: 'O ponto é a persistência do gradiente social de saúde: não é apenas pobreza absoluta, mas posição relativa e controle sobre o trabalho que se associam ao adoecimento.',
  pegadinha: 'A afirmativa incorreta soa como conclusão otimista e razoável sobre desenvolvimento econômico, mas contraria os achados de gradiente social.',
  refs: ['Determinantes sociais da saúde', 'Modelo demanda-controle'] },

{ id: 'q-1.2-023', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma equipe realiza roda de conversa com costureiras de uma oficina para entender por que as pausas prescritas não são cumpridas. Elas relatam que o pagamento por peça inviabiliza parar. Essa constatação ilustra:',
  alts: [
    { t: 'A distância entre trabalho prescrito e trabalho real, mediada pela forma de remuneração, que funciona como determinante organizacional da exposição.', ok: true,
      why: 'Correta. A remuneração por produção é mecanismo organizacional que anula, na prática, a medida preventiva formalmente prescrita.' },
    { t: 'Falta de conscientização das trabalhadoras sobre a importância das pausas.', ok: false,
      why: 'Errada. O relato indica constrangimento econômico, não desconhecimento; atribuir à conscientização individualiza o problema.' },
    { t: 'Inadequação da recomendação técnica de pausas, que deveria ser abandonada.', ok: false,
      why: 'Errada. A recomendação é adequada; o que falha é a compatibilidade com o sistema de remuneração.' },
    { t: 'Necessidade de aumentar a fiscalização individual do cumprimento das pausas pelas trabalhadoras.', ok: false,
      why: 'Errada. Fiscalizar o indivíduo sem alterar o incentivo econômico produz punição, não prevenção.' },
    { t: 'Ausência de risco ergonômico, já que as trabalhadoras optam por não pausar.', ok: false,
      why: 'Errada. A "opção" é constrangida; o risco permanece e é agravado pela ausência de recuperação.' }
  ],
  comentario: 'A questão mostra como a organização do trabalho, aqui pela forma de remuneração, determina a exposição real. Intervenção efetiva exige mexer no sistema de incentivos, não na motivação individual.',
  pegadinha: 'A saída pela "conscientização" é o reflexo automático e o mais ineficaz quando o determinante é econômico-organizacional.',
  refs: ['Ergonomia — trabalho prescrito e trabalho real', 'Normas Regulamentadoras — ergonomia'] },

{ id: 'q-1.2-024', tema: '1.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um município investiga adoecimento entre trabalhadores de uma cadeia produtiva com forte presença de trabalho terceirizado e subcontratado. Sobre a chamada "invisibilidade" desses trabalhadores nos sistemas de informação, é CORRETO afirmar:',
  alts: [
    { t: 'A fragmentação da cadeia produtiva dilui o registro do agravo entre múltiplos empregadores e dificulta identificar o processo produtivo real, subestimando a carga de doença atribuível àquela cadeia.', ok: true,
      why: 'Correta. A subcontratação fragmenta o registro, muda o código de atividade econômica informado e impede reconstruir a exposição real da cadeia.' },
    { t: 'A terceirização melhora a qualidade do registro, pois cada prestadora mantém seu próprio sistema de informação.', ok: false,
      why: 'Errada. Múltiplos sistemas fragmentados pioram a consolidação da informação sobre a cadeia.' },
    { t: 'A invisibilidade decorre apenas da recusa dos trabalhadores em relatar sua ocupação.', ok: false,
      why: 'Errada. Há fatores estruturais de registro e de organização produtiva muito além do relato individual.' },
    { t: 'O problema se resolve integralmente com a exigência de ocupação no prontuário eletrônico.', ok: false,
      why: 'Errada. Registrar ocupação é passo importante, mas não reconstitui sozinho a cadeia produtiva e o vínculo real.' },
    { t: 'Trabalhadores terceirizados apresentam menor risco, o que explica sua menor frequência nos sistemas de notificação.', ok: false,
      why: 'Errada. A literatura aponta maior exposição e maior gravidade entre terceirizados, apesar do menor registro.' }
  ],
  comentario: 'A questão explora um viés de informação com consequência sanitária: a fragmentação contratual produz subnotificação e distorce a atribuição de risco por atividade econômica.',
  pegadinha: 'Interpretar menor frequência de notificação como menor risco é um erro clássico de leitura de dado de vigilância.',
  refs: ['Vigilância em saúde do trabalhador', 'SINAN — qualidade da informação'] }
);
