/* Seção 2 (parte A) — lote de volume. Questões AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.1-010', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria de tintas contrata o serviço de saúde ocupacional ainda na fase de projeto de uma nova linha de produção, antes da compra dos equipamentos. O higienista propõe revisar a planta, os fluxos de material e as fichas dos insumos previstos. A etapa da higiene ocupacional exercida nesse momento é:',
  alts: [
    { t: 'Antecipação, que atua sobre projetos e mudanças de processo para evitar que o risco chegue a existir no ambiente.', ok: true,
      why: 'Correta. A antecipação é a etapa que analisa projetos, novas instalações, ampliações e mudanças de processo, quando o custo de eliminar o risco é menor e as opções técnicas são maiores.' },
    { t: 'Reconhecimento, pois envolve a identificação dos agentes presentes nos postos de trabalho já instalados.', ok: false,
      why: 'Errada. O reconhecimento pressupõe o ambiente existente, com trabalhadores e processos em operação; aqui a linha ainda não foi construída.' },
    { t: 'Avaliação, porque o objetivo final é comparar concentrações com limites de exposição.', ok: false,
      why: 'Errada. A avaliação é a etapa de mensuração e comparação com critérios, o que exige a fonte geradora em funcionamento.' },
    { t: 'Controle, uma vez que qualquer intervenção sobre o ambiente é por definição uma medida de controle.', ok: false,
      why: 'Errada. Controle é a etapa que implanta medidas sobre risco já reconhecido e avaliado; a análise de projeto precede logicamente essa fase.' },
    { t: 'Vigilância epidemiológica ocupacional, por se tratar de análise coletiva de exposição.', ok: false,
      why: 'Errada. Vigilância epidemiológica trabalha com dados de saúde de populações expostas, e não com análise de projeto de instalação industrial.' }
  ],
  comentario: 'A sequência clássica da higiene ocupacional é antecipação, reconhecimento, avaliação e controle. A antecipação é a mais barata e a mais eficaz, porque permite escolher processo, insumo e leiaute antes que o risco esteja instalado — é a porta de entrada da eliminação e da substituição.',
  pegadinha: 'Quem decora apenas três etapas costuma trocar antecipação por reconhecimento. O marcador é temporal: se o processo ainda não existe, é antecipação.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-011', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao iniciar o trabalho em uma metalúrgica, o médico do trabalho percorre a planta acompanhado do engenheiro de segurança, conversa com trabalhadores, observa tarefas, consulta fichas de dados de segurança e levanta o inventário de produtos químicos. Sobre a etapa de reconhecimento em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O reconhecimento identifica os agentes, suas fontes, as vias de exposição e os trabalhadores potencialmente expostos, e orienta a decisão de quando e o que medir.', ok: true,
      why: 'Correta. O reconhecimento é a etapa qualitativa que estrutura o problema e define a necessidade e a prioridade da avaliação quantitativa.' },
    { t: 'O reconhecimento exige obrigatoriamente medições quantitativas de todos os agentes identificados na planta.', ok: false,
      why: 'Errada. Medir tudo é inviável e desnecessário; o reconhecimento é qualitativo e serve exatamente para selecionar o que merece medição.' },
    { t: 'A percepção de risco relatada pelos trabalhadores não integra o reconhecimento por ser informação subjetiva.', ok: false,
      why: 'Errada. O saber operário sobre a tarefa real, os picos de exposição e as falhas de controle é fonte primária de informação no reconhecimento.' },
    { t: 'O reconhecimento se limita às atividades de rotina, excluindo manutenção, partidas, paradas e situações de emergência.', ok: false,
      why: 'Errada, e é uma inversão perigosa. Manutenção, limpeza, partida e parada frequentemente concentram as maiores exposições da planta.' },
    { t: 'A ficha de dados de segurança dispensa a observação do trabalho real, pois já descreve integralmente a exposição.', ok: false,
      why: 'Errada. A ficha descreve perigos intrínsecos do produto, mas não a forma de uso, a quantidade manipulada, a ventilação nem a tarefa real.' }
  ],
  comentario: 'Reconhecimento é a etapa que transforma uma planta industrial em um problema tratável: quais agentes, geradas por quais fontes, alcançando quais trabalhadores, por quais vias. É onde se decide o que precisa ser medido — e o que já pode ir direto para controle.',
  pegadinha: 'A exclusão de tarefas não rotineiras é o erro clássico. Manutenção e limpeza costumam ser as atividades de maior exposição e as menos avaliadas.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-012', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma serralheria com dez soldadores, o consultor realizou uma única medição de fumos metálicos, de trinta minutos, no soldador mais experiente, em dia de baixa demanda, e concluiu que "a exposição do grupo está controlada". A principal falha metodológica dessa avaliação é:',
  alts: [
    { t: 'A amostra não é representativa da variabilidade da exposição, pois foi única, curta, em condição atípica e extrapolada indevidamente para todo o grupo.', ok: true,
      why: 'Correta. A exposição ocupacional é variável no tempo e entre trabalhadores; uma amostra isolada, curta e em dia atípico não permite inferência sobre a distribuição de exposições do grupo.' },
    { t: 'A amostragem deveria ter sido feita em ponto fixo do galpão, e não junto ao trabalhador.', ok: false,
      why: 'Errada, e inverte o conceito. A amostragem pessoal, na zona respiratória, é a referência para estimar exposição; a amostragem de ponto fixo serve a outros fins, como avaliar a eficácia de um sistema de ventilação.' },
    { t: 'O erro está em ter escolhido um trabalhador experiente, pois só trabalhadores recém-admitidos podem ser amostrados.', ok: false,
      why: 'Errada. Não há restrição de tempo de casa; o problema é a representatividade da condição amostrada, não a experiência do indivíduo.' },
    { t: 'A avaliação seria válida se o resultado tivesse ficado acima do limite, e só é inválida porque deu abaixo.', ok: false,
      why: 'Errada. A validade metodológica de uma amostragem não depende do resultado obtido; um método frágil é frágil nos dois sentidos.' },
    { t: 'O problema é exclusivamente a duração de trinta minutos, que seria corrigida por qualquer amostra de jornada completa isolada.', ok: false,
      why: 'Errada. A duração é um dos problemas, mas uma única amostra de jornada inteira em dia atípico continua sem caracterizar a variabilidade do grupo.' }
  ],
  comentario: 'Estratégia de amostragem é caracterizar uma distribuição, não obter um número. Exige amostras suficientes, cobrindo a jornada e os dias representativos, com registro das condições operacionais. Um valor isolado abaixo do limite não demonstra controle.',
  pegadinha: 'A alternativa que sugere amostragem de ponto fixo parece técnica, mas inverte o papel dos dois tipos de amostragem.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-013', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma gráfica utiliza um solvente de limpeza altamente volátil e neurotóxico. O higienista propõe trocá-lo por um produto de menor toxicidade e menor pressão de vapor, com desempenho equivalente. Sobre essa medida, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Trata-se de substituição, medida de alta posição na hierarquia de controles, que exige avaliação do novo agente para não gerar risco equivalente ou maior.', ok: true,
      why: 'Correta. A substituição atua sobre o perigo intrínseco, mas só é ganho real se o substituto for avaliado quanto a toxicidade, inflamabilidade e demais propriedades — caso contrário há apenas troca de problema.' },
    { t: 'Trata-se de medida de engenharia, equivalente à instalação de ventilação local exaustora.', ok: false,
      why: 'Errada. Medidas de engenharia agem sobre a propagação ou o confinamento do agente; a troca do produto age sobre o próprio perigo e ocupa degrau superior.' },
    { t: 'A substituição dispensa reavaliação da exposição, pois por definição o novo produto é seguro.', ok: false,
      why: 'Errada. Nenhum produto é seguro por definição; a substituição inadequada pode introduzir agente sensibilizante, carcinogênico ou inflamável.' },
    { t: 'A substituição é medida administrativa, pois depende de decisão gerencial de compra.', ok: false,
      why: 'Errada. A classificação na hierarquia depende do mecanismo de proteção, não de quem toma a decisão; controles administrativos agem sobre a organização do trabalho.' },
    { t: 'Só se justifica substituição quando as concentrações medidas estiverem acima do limite de exposição.', ok: false,
      why: 'Errada. Reduzir perigo intrínseco é sempre desejável, especialmente para agentes de alta toxicidade, e não depende de ultrapassar limite.' }
  ],
  comentario: 'Eliminação e substituição estão no topo da hierarquia porque removem ou reduzem o perigo, e não apenas a exposição. O contraponto obrigatório é a chamada substituição lamentável: trocar por um agente menos estudado que se revela igual ou pior.',
  pegadinha: 'A ideia de que "substituto é seguro por definição" é atraente e falsa. Toda substituição exige análise comparativa do novo agente.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-014', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma reunião de análise de riscos de uma cerâmica, discute-se a hierarquia de medidas de controle. Assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O rodízio de trabalhadores entre postos de alta exposição é medida de engenharia, pois altera fisicamente o ambiente.', ok: true,
      why: 'É a alternativa INCORRETA, portanto a resposta. Rodízio é controle administrativo: não altera o ambiente nem a fonte, apenas redistribui a exposição entre pessoas.' },
    { t: 'A eliminação do agente ou do processo é a medida mais eficaz, porque suprime o perigo em vez de gerenciá-lo.', ok: false,
      why: 'Verdadeira. Eliminar o perigo dispensa a cadeia de controles subsequentes e não depende de comportamento humano.' },
    { t: 'A ventilação local exaustora atua na fonte ou na trajetória do contaminante, protegendo coletivamente os trabalhadores.', ok: false,
      why: 'Verdadeira. É o exemplo clássico de controle de engenharia com característica de proteção coletiva.' },
    { t: 'O equipamento de proteção individual ocupa a base da hierarquia porque sua eficácia depende de seleção correta, ajuste, treinamento e uso contínuo.', ok: false,
      why: 'Verdadeira. Cada uma dessas dependências é ponto de falha, o que torna o EPI a barreira menos confiável.' },
    { t: 'Medidas de níveis diferentes podem ser combinadas, e a adoção de um controle de engenharia não impede a exigência simultânea de EPI durante sua implantação.', ok: false,
      why: 'Verdadeira. A hierarquia orienta prioridade, não exclusividade; durante obras e transições a combinação é a regra.' }
  ],
  comentario: 'Classificar corretamente a medida é o que separa a hierarquia real da hierarquia decorada. Rodízio, redução de jornada na área, pausas e escalonamento de tarefas são controles administrativos, com a limitação ética de distribuir exposição em vez de reduzi-la.',
  pegadinha: 'O rodízio soa protetor e é frequentemente vendido como solução. Ele reduz a exposição individual, mas amplia o número de expostos e não reduz a geração do agente.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-015', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma mineradora não consegue, no curto prazo, reduzir a concentração de poeira respirável em um setor e propõe reduzir a permanência diária dos trabalhadores nesse local. O médico do trabalho é consultado sobre a legitimidade dessa medida. A avaliação mais adequada é:',
  alts: [
    { t: 'É um controle administrativo aceitável como medida transitória, desde que acompanhada de cronograma de implantação de controles de engenharia e de monitoramento, pois não reduz a geração do agente.', ok: true,
      why: 'Correta. Controles administrativos são legítimos como paliativo ou complemento, mas não substituem a obrigação de agir sobre a fonte, e devem vir com prazo e verificação.' },
    { t: 'É medida definitiva e suficiente, pois a dose diária é o único determinante do risco.', ok: false,
      why: 'Errada. Além de a dose não ser o único determinante para todos os agentes, aceitar o paliativo como definitivo perpetua a exposição da coletividade.' },
    { t: 'É inaceitável em qualquer circunstância, pois controles administrativos não integram a hierarquia de controles.', ok: false,
      why: 'Errada. Controles administrativos integram formalmente a hierarquia, apenas em posição inferior aos de engenharia.' },
    { t: 'Equivale a uma medida de proteção coletiva, pois beneficia todo o grupo simultaneamente.', ok: false,
      why: 'Errada. Proteção coletiva age sobre o ambiente; a limitação de tempo age sobre a organização do trabalho e apenas redistribui a exposição.' },
    { t: 'Dispensa monitoramento posterior, já que a exposição foi matematicamente reduzida.', ok: false,
      why: 'Errada. A redução calculada precisa ser verificada na prática, e a rotação pode simplesmente ampliar o número de trabalhadores expostos.' }
  ],
  comentario: 'A questão central dos controles administrativos é ética antes de ser técnica: eles diluem a exposição entre mais pessoas sem reduzir a quantidade total de agente gerado. São aceitáveis como ponte, nunca como destino.',
  pegadinha: 'Negar valor a qualquer controle administrativo é tão errado quanto aceitá-lo como solução definitiva. A resposta exige a nuance do caráter transitório.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-016', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao planejar a avaliação de exposição em uma fábrica de calçados com 400 trabalhadores, a equipe decide organizar os trabalhadores em grupos homogêneos de exposição. Sobre esse conceito, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O grupo reúne trabalhadores com perfil de exposição semelhante em agente, intensidade, frequência e duração, de modo que a amostra de alguns permita inferir sobre todos.', ok: true,
      why: 'Correta. A homogeneidade é de perfil de exposição, e é ela que autoriza a inferência estatística de poucos amostrados para o conjunto do grupo.' },
    { t: 'O grupo deve ser definido exclusivamente pelo cargo formal registrado em carteira, critério objetivo e suficiente.', ok: false,
      why: 'Errada. Trabalhadores com o mesmo cargo podem ter exposições muito distintas conforme setor, turno, equipamento e tarefa real; o cargo é ponto de partida, não critério suficiente.' },
    { t: 'Uma vez definidos, os grupos são permanentes e não devem ser revistos, sob pena de perder a comparabilidade histórica.', ok: false,
      why: 'Errada. Mudança de processo, de leiaute, de insumo ou de organização do trabalho obriga a revisar a composição dos grupos.' },
    { t: 'Se as medições dentro do grupo apresentarem grande dispersão, isso confirma o acerto do agrupamento.', ok: false,
      why: 'Errada, e inverte o critério. Alta variabilidade interna sugere que o grupo não é homogêneo e precisa ser subdividido.' },
    { t: 'O agrupamento dispensa a caracterização das tarefas, pois o resultado analítico é o único dado relevante.', ok: false,
      why: 'Errada. Sem descrição das tarefas e das condições, o resultado não pode ser atribuído a nenhuma situação de exposição nem reproduzido.' }
  ],
  comentario: 'O grupo homogêneo de exposição é uma hipótese a ser testada, não um rótulo administrativo. A dispersão dos resultados dentro do grupo é o próprio teste: se for grande, o grupo estava mal formado.',
  pegadinha: 'Agrupar por cargo ou por setor é o atalho mais comum e a principal fonte de subestimação de exposição de subgrupos.',
  refs: ['AIHA — grupos similares de exposição', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-017', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um técnico realizará amostragem de vapores orgânicos em um pintor de estruturas metálicas. Sobre a técnica de amostragem em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A amostragem pessoal deve ser feita com o dispositivo coletor posicionado na zona respiratória do trabalhador, acompanhando seus deslocamentos durante a jornada.', ok: true,
      why: 'Correta. É a exposição que efetivamente chega às vias aéreas do trabalhador que interessa, e ela varia com a posição e o deslocamento ao longo da tarefa.' },
    { t: 'A amostragem em ponto fixo próximo ao posto substitui integralmente a amostragem pessoal para fins de comparação com limites de exposição.', ok: false,
      why: 'Errada. O ponto fixo é útil para avaliar fontes e eficácia de controles, mas não representa a exposição individual, que depende da posição e do movimento do trabalhador.' },
    { t: 'A calibração da bomba de amostragem pode ser feita apenas ao final da coleta, dispensando verificação inicial.', ok: false,
      why: 'Errada. A vazão deve ser verificada antes e depois; sem a verificação inicial não há como calcular o volume amostrado com confiança.' },
    { t: 'Não é necessário registrar as condições operacionais durante a coleta, pois o resultado analítico é autoexplicativo.', ok: false,
      why: 'Errada. Sem registro de tarefas, ventilação, produção e uso de controles, o resultado não pode ser interpretado nem reproduzido.' },
    { t: 'Amostras de branco de campo são dispensáveis quando o laboratório é acreditado.', ok: false,
      why: 'Errada. O branco de campo controla contaminação no transporte e manuseio, independentemente da qualidade do laboratório.' }
  ],
  comentario: 'A validade de uma medição de higiene depende de três coisas fora do laboratório: posicionamento na zona respiratória, controle do volume amostrado por calibração antes e depois, e registro fiel das condições operacionais.',
  pegadinha: 'A confusão entre amostragem pessoal e de ponto fixo é recorrente. Ponto fixo avalia ambiente; amostragem pessoal avalia exposição.',
  refs: ['NHO 08 — Fundacentro', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-018', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma fábrica de móveis, a exaustão instalada sobre uma lixadeira não reduziu a concentração de poeira de madeira na zona respiratória do operador. Ao inspecionar o sistema, o higienista deve considerar que:',
  alts: [
    { t: 'O captor deve ficar o mais próximo possível da fonte e posicionado de modo que o contaminante não atravesse a zona respiratória do trabalhador antes de ser capturado.', ok: true,
      why: 'Correta. A eficiência de captura cai drasticamente com a distância, e um captor mal posicionado pode literalmente puxar o contaminante através da respiração do operador.' },
    { t: 'A eficiência de captura é independente da distância entre o captor e a fonte, desde que a vazão do ventilador seja elevada.', ok: false,
      why: 'Errada, e é o erro conceitual central em ventilação local exaustora. A velocidade do ar induzido cai muito rapidamente com a distância do captor.' },
    { t: 'A ausência de ar de reposição no galpão é irrelevante para o desempenho do sistema de exaustão.', ok: false,
      why: 'Errada. Sem reposição adequada de ar, o ambiente entra em depressão e a vazão efetiva de exaustão cai, comprometendo todo o sistema.' },
    { t: 'A ventilação geral diluidora é sempre preferível à local exaustora para poeiras geradas em ponto definido.', ok: false,
      why: 'Errada. Para contaminante gerado em fonte pontual, a captação na fonte é a solução correta; a diluição é opção pobre e inadequada para particulados.' },
    { t: 'Uma vez instalado e aprovado no comissionamento, o sistema dispensa verificações periódicas de desempenho.', ok: false,
      why: 'Errada. Dutos entopem, correias afrouxam, filtros saturam e captores são deslocados; a verificação periódica é parte do controle.' }
  ],
  comentario: 'Ventilação local exaustora é o controle de engenharia mais usado e o mais mal instalado. Os três erros clássicos são captor longe da fonte, ausência de ar de reposição e trajetória de captura passando pela zona respiratória do trabalhador.',
  pegadinha: 'Aumentar a potência do ventilador é a resposta intuitiva e ineficaz. A geometria e a proximidade do captor pesam mais que a vazão bruta.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-019', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um laboratório de controle de qualidade manipula um solvente carcinogênico em pequenas quantidades. Discute-se entre instalar ventilação geral diluidora no salão ou enclausurar a operação em capela com exaustão. A orientação tecnicamente correta é:',
  alts: [
    { t: 'Enclausurar a operação, pois a ventilação geral diluidora não é adequada para agentes de alta toxicidade ou carcinogênicos, nem para fontes pontuais intensas.', ok: true,
      why: 'Correta. A diluição apenas reduz a concentração média do salão e expõe todos os presentes; para agentes de alta toxicidade a estratégia é confinar e captar na fonte.' },
    { t: 'Adotar ventilação geral diluidora, por ser mais econômica e proteger simultaneamente todos os ocupantes do salão.', ok: false,
      why: 'Errada. Ela distribui o contaminante por todo o ambiente antes de removê-lo, expondo trabalhadores que não participam da operação.' },
    { t: 'Manter a operação em bancada aberta e fornecer respirador purificador de ar aos analistas.', ok: false,
      why: 'Errada. Recorrer ao EPI havendo solução de engenharia viável inverte a hierarquia de controles, sobretudo para carcinogênico.' },
    { t: 'A escolha é indiferente, pois ambas são medidas de engenharia e portanto equivalentes na hierarquia.', ok: false,
      why: 'Errada. Estar no mesmo degrau da hierarquia não significa ter a mesma eficácia; enclausuramento e captação na fonte são muito superiores à diluição.' },
    { t: 'A ventilação geral diluidora é indicada porque garante concentração uniformemente segura em todo o ambiente.', ok: false,
      why: 'Errada. A mistura nunca é perfeita, e existem gradientes e zonas mortas com concentrações muito acima da média calculada.' }
  ],
  comentario: 'Ventilação geral diluidora tem indicação restrita: contaminantes de baixa toxicidade, gerados de forma difusa e em taxa baixa e uniforme, em ambiente sem trabalhadores próximos à fonte. Fora disso, a solução é enclausurar e captar na fonte.',
  pegadinha: 'A alternativa da diluição usa o argumento de "proteger todo o salão", quando na verdade ela expõe todo o salão.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] }

,

{ id: 'q-2.1-020', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma marcenaria, o empregador afirma que cumpriu sua obrigação legal ao entregar máscaras e protetores auriculares aos trabalhadores, colhendo assinatura no recibo. Sobre a relação entre proteção coletiva e proteção individual, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A proteção individual é subsidiária: só se justifica quando a proteção coletiva for tecnicamente inviável, insuficiente ou estiver em fase de implantação, e sua entrega exige treinamento, fiscalização do uso, higienização e substituição.', ok: true,
      why: 'Correta. A entrega do equipamento é apenas uma das obrigações; sem treinamento, fiscalização e manutenção, a proteção existe no papel e não no trabalhador.' },
    { t: 'A entrega de equipamento individual com registro de recebimento encerra a responsabilidade do empregador quanto àquele risco.', ok: false,
      why: 'Errada. O recibo documenta a entrega, não a proteção; permanecem as obrigações de treinar, fiscalizar o uso, higienizar e substituir quando danificado.' },
    { t: 'A proteção individual é preferível à coletiva por ser ajustada às características de cada trabalhador.', ok: false,
      why: 'Errada, e inverte a hierarquia. A adaptação individual é vantagem operacional, não motivo para preterir medidas que protegem todos independentemente de comportamento.' },
    { t: 'Equipamentos de proteção individual e coletiva são intercambiáveis, cabendo ao empregador escolher livremente entre eles por critério de custo.', ok: false,
      why: 'Errada. A escolha é técnica e hierarquizada, não discricionária nem baseada apenas em custo.' },
    { t: 'O uso de proteção individual dispensa a avaliação ambiental, pois a exposição passa a ser considerada nula.', ok: false,
      why: 'Errada. O equipamento reduz a exposição por um fator, nunca a zera, e a avaliação ambiental permanece necessária para selecioná-lo e verificar sua adequação.' }
  ],
  comentario: 'Proteção coletiva age no ambiente e independe da adesão individual; proteção individual age na interface trabalhador-ambiente e depende de uma cadeia frágil de condições. A entrega documentada é o começo da obrigação, não o fim.',
  pegadinha: 'O argumento do recibo assinado é o mais usado na prática e o mais frágil tecnicamente: prova entrega, não proteção.',
  refs: ['EPC versus EPI', 'NR-6', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-021', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao estruturar o programa de higiene ocupacional de uma fábrica de embalagens, o consultor organiza as ações segundo o modelo fonte-trajetória-receptor. Assinale a alternativa que classifica CORRETAMENTE as medidas propostas:',
  alts: [
    { t: 'Substituir a tinta à base de solvente age na fonte; enclausurar o setor e instalar exaustão agem na trajetória; treinar e fornecer respirador agem no receptor.', ok: true,
      why: 'Correta. O modelo separa onde o agente é gerado, por onde ele se propaga e onde ele encontra o trabalhador, e a prioridade é intervir o mais próximo possível da geração.' },
    { t: 'A ventilação local exaustora é medida sobre o receptor, pois seu objetivo final é proteger o trabalhador.', ok: false,
      why: 'Errada. A finalidade é proteger o trabalhador, mas o mecanismo atua sobre a captação e a propagação do contaminante, e não sobre o receptor.' },
    { t: 'A troca de insumo por outro menos volátil é medida sobre a trajetória, pois altera a dispersão no ambiente.', ok: false,
      why: 'Errada. Alterar o insumo age sobre a geração do contaminante, isto é, sobre a fonte.' },
    { t: 'O rodízio de trabalhadores é medida sobre a fonte, pois reduz a quantidade total de agente gerado.', ok: false,
      why: 'Errada. O rodízio não altera a geração; age sobre o receptor, limitando o tempo de contato de cada indivíduo.' },
    { t: 'A ordem de prioridade do modelo é receptor, trajetória e fonte, do mais simples ao mais complexo.', ok: false,
      why: 'Errada, e inverte a lógica. A prioridade é sempre agir o mais próximo possível da fonte, ainda que seja tecnicamente mais difícil.' }
  ],
  comentario: 'O modelo fonte-trajetória-receptor é uma leitura complementar à hierarquia de controles e ajuda a classificar medidas concretas. Quanto mais perto da fonte, menor o número de pessoas dependentes daquele controle e menor a chance de falha silenciosa.',
  pegadinha: 'A confusão vem de julgar pela finalidade em vez do mecanismo: toda medida visa proteger o trabalhador, mas nem toda medida age sobre ele.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'Hierarquia de controles de risco'] },

{ id: 'q-2.1-022', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pedreira gera grande quantidade de poeira no britador e no transporte por correias. Entre as propostas de controle, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'A umidificação do material aumenta a fração respirável suspensa e deve ser evitada em processos de britagem.', ok: true,
      why: 'É a alternativa INCORRETA, portanto a resposta. A supressão por umidificação aglomera as partículas finas e reduz sua suspensão no ar; é uma das medidas clássicas de controle de poeira mineral.' },
    { t: 'O enclausuramento dos pontos de transferência das correias, associado a captação localizada, reduz a emissão difusa de poeira.', ok: false,
      why: 'Verdadeira. Os pontos de transferência e queda de material são as fontes mais intensas em transporte por correias.' },
    { t: 'Cabines de operação pressurizadas com ar filtrado protegem o operador ao impedir a entrada de ar contaminado.', ok: false,
      why: 'Verdadeira. A pressurização positiva com filtragem é medida coletiva eficaz para postos fixos de comando em ambientes empoeirados.' },
    { t: 'A varrição a seco do pátio deve ser substituída por métodos úmidos ou por aspiração com filtragem adequada.', ok: false,
      why: 'Verdadeira. A varrição a seco ressuspende justamente a fração fina já depositada, gerando picos de exposição.' },
    { t: 'O uso de ar comprimido para limpeza de roupas e superfícies deve ser proscrito por ressuspender a poeira depositada.', ok: false,
      why: 'Verdadeira. Além de ressuspender particulado, o jato de ar comprimido apresenta riscos próprios e é prática condenada.' }
  ],
  comentario: 'O controle de poeira mineral se apoia em quatro pilares: supressão por umidade, enclausuramento das transferências, captação localizada e eliminação de práticas que ressuspendem o material já depositado, como varrição a seco e limpeza com ar comprimido.',
  pegadinha: 'A afirmação falsa inverte um efeito bem estabelecido: a água aglomera partículas finas em vez de liberá-las.',
  refs: ['Ventilação industrial e enclausuramento', 'Controle de poeiras minerais'] },

{ id: 'q-2.1-023', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pequena indústria não dispõe de recursos para amostragem quantitativa de todos os agentes químicos identificados e pede orientação sobre como priorizar. A conduta tecnicamente adequada é:',
  alts: [
    { t: 'Realizar avaliação qualitativa estruturada, categorizando cada situação por potencial de dano do agente e por potencial de exposição, e reservar a medição quantitativa para as situações de maior incerteza ou maior risco estimado.', ok: true,
      why: 'Correta. A avaliação qualitativa estruturada, como as abordagens de agrupamento por faixas de controle, permite priorizar recursos sem deixar situações críticas sem tratamento.' },
    { t: 'Medir todos os agentes com o menor número possível de amostras por agente, garantindo cobertura total do inventário.', ok: false,
      why: 'Errada. Diluir o esforço em amostras insuficientes por agente produz dados sem poder de decisão para nenhum deles.' },
    { t: 'Adiar qualquer ação de controle até que haja orçamento para medir quantitativamente todos os agentes.', ok: false,
      why: 'Errada. Quando a avaliação qualitativa já indica risco elevado, o controle deve ser implantado independentemente da medição.' },
    { t: 'Priorizar exclusivamente pelo número de trabalhadores expostos, independentemente da toxicidade dos agentes.', ok: false,
      why: 'Errada. O número de expostos é um dos critérios, mas ignorar a gravidade do agente pode deixar de fora carcinogênicos com poucos expostos.' },
    { t: 'Considerar que a ausência de medição quantitativa equivale a ausência de risco caracterizado.', ok: false,
      why: 'Errada, e é uma inversão perigosa. Ausência de dados não é evidência de ausência de exposição.' }
  ],
  comentario: 'A avaliação qualitativa não é a versão pobre da quantitativa: é a etapa que decide onde a quantitativa vale a pena. Ela cruza perigo intrínseco do agente com potencial de exposição, e permite acionar controle imediato em situações evidentes.',
  pegadinha: 'Tratar falta de medição como ausência de risco é o argumento defensivo mais comum em laudos e o mais indefensável tecnicamente.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'Avaliação qualitativa de risco químico'] },

{ id: 'q-2.1-024', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Dois anos após instalar sistemas de exaustão em uma galvanoplastia, a empresa relata que os trabalhadores voltaram a queixar-se de irritação nasal. Sobre a etapa de controle em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A implantação de uma medida de controle não encerra o ciclo: são necessárias manutenção programada, verificação periódica de desempenho e reavaliação da exposição.', ok: true,
      why: 'Correta. Sistemas de controle se degradam com o tempo, e a única forma de garantir eficácia continuada é verificar desempenho e reavaliar exposição periodicamente.' },
    { t: 'Queixa de sintomas irritativos não deve ser considerada, pois só medição ambiental caracteriza falha de controle.', ok: false,
      why: 'Errada. Sintomas sentinela em grupo exposto são gatilho legítimo para reinvestigar controles, e frequentemente antecedem a medição.' },
    { t: 'Se o sistema foi dimensionado corretamente no projeto, seu desempenho é constante ao longo da vida útil.', ok: false,
      why: 'Errada. Entupimento de dutos, desgaste de correias, saturação de filtros e alterações de leiaute reduzem o desempenho real ao longo do tempo.' },
    { t: 'A reavaliação só deve ocorrer quando houver mudança formal de processo registrada em documento.', ok: false,
      why: 'Errada. Mudanças informais de tarefa, aumento de produção e improvisos operacionais alteram a exposição sem gerar registro.' },
    { t: 'Diante de queixa persistente, a conduta prioritária é substituir a exaustão por respiradores para todos.', ok: false,
      why: 'Errada. A conduta prioritária é investigar por que o controle de engenharia falhou e restaurá-lo, e não descer na hierarquia de controles.' }
  ],
  comentario: 'O ciclo da higiene ocupacional é contínuo: controlar, verificar, reavaliar e, se necessário, recontrolar. Sintomas sentinela em trabalhadores com controles instalados devem ser lidos como suspeita de falha do controle, não como intolerância individual.',
  pegadinha: 'Descer para o respirador diante da falha da exaustão é a saída fácil e o erro conceitual: primeiro se restaura o degrau superior da hierarquia.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-025', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma indústria química, o médico do trabalho recebe do higienista o relatório de avaliação ambiental e precisa integrá-lo à vigilância da saúde dos trabalhadores. Sobre essa articulação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Os dados de exposição definem quem deve ser incluído na vigilância, quais exames são pertinentes e com que periodicidade, e os achados clínicos, por sua vez, realimentam a revisão das medidas de controle.', ok: true,
      why: 'Correta. A relação é de mão dupla: a higiene define a população e o conteúdo do acompanhamento médico, e os desfechos de saúde questionam a suficiência dos controles.' },
    { t: 'A avaliação ambiental e o acompanhamento médico são atividades independentes, cada uma com seus próprios documentos e conclusões.', ok: false,
      why: 'Errada. Programas desarticulados produzem exames sem relação com a exposição real e controles sem retorno sobre sua eficácia.' },
    { t: 'O acompanhamento médico substitui a avaliação ambiental quando os exames estão normais.', ok: false,
      why: 'Errada, e inverte a lógica preventiva. Exames normais podem apenas significar que o dano ainda não é detectável, e não que a exposição está controlada.' },
    { t: 'A detecção de alteração precoce em um trabalhador é indicação de afastamento individual, sem necessidade de reavaliar o grupo exposto.', ok: false,
      why: 'Errada. Um caso é um evento sentinela: obriga a investigar todo o grupo com exposição semelhante e as medidas de controle.' },
    { t: 'A escolha dos exames complementares deve seguir apenas o cargo formal, sem considerar o perfil de exposição.', ok: false,
      why: 'Errada. É o agente e a intensidade da exposição que determinam a pertinência do exame, não a denominação do cargo.' }
  ],
  comentario: 'Higiene ocupacional e vigilância da saúde são as duas metades do mesmo programa. A avaliação ambiental é prevenção primária; o acompanhamento médico é detecção precoce. Quando o segundo encontra alteração, o primeiro falhou e precisa ser revisto.',
  pegadinha: 'Tratar exame normal como prova de ambiente seguro confunde ausência de efeito detectável com ausência de exposição.',
  refs: ['NR-7 — PCMSO', 'NR-1 — Gerenciamento de Riscos Ocupacionais', 'Higiene ocupacional e vigilância da saúde'] },

{ id: 'q-2.1-026', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadores de uma fábrica de compensados estão expostos simultaneamente a formaldeído, poeira de madeira e ruído. O laudo conclui que "nenhum agente isoladamente ultrapassa seu limite, portanto não há risco". A crítica CORRETA a essa conclusão é:',
  alts: [
    { t: 'Exposições múltiplas exigem análise das interações, pois agentes com o mesmo órgão-alvo podem ter efeito aditivo, e a avaliação isolada de cada agente subestima o risco combinado.', ok: true,
      why: 'Correta. Quando dois ou mais agentes atuam sobre o mesmo sistema, o raciocínio agente a agente não representa a carga total imposta ao trabalhador.' },
    { t: 'A conclusão está correta, pois limites de exposição já incorporam a presença de outros agentes no ambiente.', ok: false,
      why: 'Errada. Os limites são derivados para exposição ao agente isolado e não contemplam automaticamente combinações.' },
    { t: 'Só é necessário considerar interação quando os agentes pertencem à mesma classe química.', ok: false,
      why: 'Errada. O critério relevante é o órgão-alvo e o mecanismo de ação, não a semelhança química; poeira, gás e agente físico podem convergir sobre o mesmo sistema.' },
    { t: 'A presença de ruído é irrelevante para a análise, pois agentes físicos e químicos não interagem em nenhuma hipótese.', ok: false,
      why: 'Errada. Há interações reconhecidas entre ruído e agentes ototóxicos, e a combinação pode agravar o dano auditivo.' },
    { t: 'A interação entre agentes só é considerada quando ambos ultrapassam metade de seus respectivos limites.', ok: false,
      why: 'Errada. Não existe esse critério de corte; a análise de efeito combinado decorre da coincidência de alvo e mecanismo.' }
  ],
  comentario: 'Ambientes reais expõem a misturas. O raciocínio de aditividade se aplica quando os agentes compartilham órgão-alvo. Ruído associado a solventes ototóxicos é o exemplo mais cobrado de interação entre agente físico e químico.',
  pegadinha: 'A frase "cada agente abaixo do seu limite" é tecnicamente verdadeira e conclusivamente insuficiente. É o tipo de conclusão que aparece em laudo e não sobrevive à análise.',
  refs: ['ACGIH — misturas e exposições combinadas', 'Higiene ocupacional — avaliação de exposições'] },

{ id: 'q-2.1-027', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um frigorífico planeja avaliar a exposição de um grupo de trabalhadores a um agente químico e discute se deve amostrar em condição típica ou na condição de maior exposição prevista. Sobre estratégias de amostragem, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A amostragem dirigida ao pior caso é útil como triagem, pois um resultado baixo na pior condição tem alto poder de descartar risco, mas não descreve a distribuição de exposições do grupo.', ok: true,
      why: 'Correta. A estratégia de pior caso é eficiente para excluir problema; para caracterizar a exposição habitual do grupo é preciso amostragem representativa.' },
    { t: 'A amostragem de pior caso é sempre proibida por superestimar a exposição e gerar exigências desnecessárias.', ok: false,
      why: 'Errada. Ela é uma ferramenta legítima de triagem, especialmente quando os recursos são limitados.' },
    { t: 'A amostragem aleatória dentro do grupo é inadequada porque pode selecionar trabalhadores de baixa exposição.', ok: false,
      why: 'Errada, e inverte a lógica estatística. Justamente por incluir toda a faixa de exposições é que a amostragem aleatória permite estimar a distribuição do grupo.' },
    { t: 'Um único resultado abaixo do limite obtido em condição típica autoriza concluir que nenhum trabalhador do grupo excede o limite.', ok: false,
      why: 'Errada. Sem conhecer a variabilidade não se pode afirmar nada sobre os percentis superiores da distribuição do grupo.' },
    { t: 'A escolha da estratégia independe do objetivo da avaliação, sendo definida apenas pelo custo analítico.', ok: false,
      why: 'Errada. A estratégia decorre da pergunta que se quer responder: triar, caracterizar exposição habitual ou verificar eficácia de controle.' }
  ],
  comentario: 'Estratégia de amostragem começa pela pergunta. Se a pergunta é "existe problema aqui?", o pior caso resolve rápido. Se é "qual a exposição habitual deste grupo?", só a amostragem representativa com número suficiente de medições responde.',
  pegadinha: 'A ideia de que amostragem aleatória é ruim por "sortear quem se expõe pouco" confunde representatividade com conservadorismo.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-028', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa vai implantar um novo processo de decapagem ácida e solicita ao serviço de saúde ocupacional uma análise prévia. Sobre a atuação antecipatória da higiene ocupacional em mudanças de processo, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A análise prévia deve considerar insumos, subprodutos e resíduos gerados, o leiaute, a manutenção prevista e os cenários anormais, permitindo incorporar controles ao projeto antes da instalação.', ok: true,
      why: 'Correta. A antecipação avalia todo o ciclo do processo, incluindo o que só aparece em manutenção e em desvio operacional, quando ainda é barato mudar o projeto.' },
    { t: 'A análise deve restringir-se aos insumos declarados na ficha de compra, pois subprodutos não são previsíveis.', ok: false,
      why: 'Errada. Subprodutos e reações indesejadas são previsíveis a partir da química do processo e frequentemente são os agentes mais perigosos gerados.' },
    { t: 'A antecipação se limita a estimar quantos trabalhadores serão alocados no novo setor.', ok: false,
      why: 'Errada. Dimensionar pessoal é insumo da análise, não seu objeto; o objeto é o risco gerado pelo processo.' },
    { t: 'Como não há trabalhadores expostos ainda, não existe base técnica para propor controles nessa fase.', ok: false,
      why: 'Errada, e é o oposto do conceito. É exatamente por não haver exposição instalada que a fase é a mais favorável para eliminar o risco.' },
    { t: 'A análise prévia substitui integralmente a necessidade de avaliação ambiental após a partida do processo.', ok: false,
      why: 'Errada. A antecipação estima; a avaliação após a partida verifica se o previsto se confirmou na operação real.' }
  ],
  comentario: 'Gestão de mudança é onde a higiene ocupacional entrega o melhor retorno. Novos insumos, novos equipamentos, alterações de leiaute e mudanças de turno devem disparar análise prévia de risco, com atenção especial a manutenção e a cenários anormais.',
  pegadinha: 'O argumento de que "sem exposição não há o que avaliar" confunde exposição atual com risco previsível e destrói o conceito de antecipação.',
  refs: ['Higiene ocupacional — antecipação', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-029', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao apresentar os resultados da avaliação ambiental aos trabalhadores de uma fundição, o médico do trabalho é questionado sobre o significado dos números. Sobre a comunicação de risco em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Os trabalhadores têm direito de conhecer os agentes a que estão expostos, os resultados das avaliações e as medidas adotadas, em linguagem acessível, e essa informação é parte do próprio programa de prevenção.', ok: true,
      why: 'Correta. Informação sobre risco é condição para participação, adesão às medidas e reconhecimento precoce de falhas de controle pelos próprios expostos.' },
    { t: 'Resultados de avaliação ambiental são documentos técnicos internos e não devem ser divulgados aos trabalhadores para evitar alarme.', ok: false,
      why: 'Errada. A restrição da informação é contrária ao direito à informação sobre riscos e retira do trabalhador a capacidade de se proteger.' },
    { t: 'A comunicação deve limitar-se a informar se o resultado ficou acima ou abaixo do limite legal, sem discutir incertezas.', ok: false,
      why: 'Errada. Reduzir a comunicação a um veredito binário oculta a limitação dos limites e a variabilidade das medições.' },
    { t: 'A participação dos trabalhadores na identificação de riscos é dispensável quando há laudo elaborado por profissional habilitado.', ok: false,
      why: 'Errada. O conhecimento sobre o trabalho real, os improvisos e os picos de exposição está com quem executa a tarefa.' },
    { t: 'Informar riscos aumenta a responsabilidade do trabalhador e transfere a ele a obrigação de se proteger.', ok: false,
      why: 'Errada. Informar não transfere responsabilidade; a obrigação de eliminar ou reduzir o risco permanece com o empregador.' }
  ],
  comentario: 'A comunicação de risco fecha o ciclo da higiene ocupacional. Ela não é gentileza nem gestão de imagem: é condição para que os expostos participem do reconhecimento, usem corretamente as medidas e percebam falhas antes que virem doença.',
  pegadinha: 'A alternativa que trata informação como transferência de responsabilidade inverte um princípio central: informar é dever adicional, não substituto do controle.',
  refs: ['Direito à informação sobre riscos', 'NR-1 — Gerenciamento de Riscos Ocupacionais', 'Convenção 155 da OIT'] }

,

{ id: 'q-2.1-030', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria farmacêutica precisa manipular um princípio ativo de alta potência em sala dedicada. O projetista pergunta se a sala deve operar com pressão positiva ou negativa em relação aos corredores. A orientação CORRETA, do ponto de vista da proteção do trabalhador, é:',
  alts: [
    { t: 'Pressão negativa em relação às áreas vizinhas, para que o fluxo de ar entre na sala e o contaminante não escape para os demais ambientes.', ok: true,
      why: 'Correta. Quando o objetivo é conter um agente perigoso, a sala deve ser mantida em depressão para que qualquer vazamento de ar ocorra de fora para dentro.' },
    { t: 'Pressão positiva em relação às áreas vizinhas, para impedir a entrada de contaminantes externos na sala.', ok: false,
      why: 'Errada neste contexto. A pressão positiva protege o conteúdo da sala contra contaminação externa, mas empurra o agente perigoso para os corredores.' },
    { t: 'Pressão equalizada, pois qualquer diferencial compromete o conforto térmico dos operadores.', ok: false,
      why: 'Errada. Sem diferencial de pressão não há direção de fluxo definida e a contenção depende apenas da vedação física, que sempre falha.' },
    { t: 'O sentido do diferencial é indiferente desde que o ar seja filtrado antes de ser lançado ao exterior.', ok: false,
      why: 'Errada. A filtragem trata o ar exaurido, mas não impede que o contaminante escape pelas frestas na direção errada.' },
    { t: 'Pressão positiva, pois é o padrão obrigatório para toda sala com exaustão instalada.', ok: false,
      why: 'Errada. Não existe padrão único: o sentido do diferencial decorre do que se pretende proteger, o produto ou as pessoas do entorno.' }
  ],
  comentario: 'A regra é simples: proteja-se o que estiver dentro com pressão positiva; contenha-se o que estiver dentro com pressão negativa. Cabines de operação em ambientes empoeirados são positivas; salas de manipulação de agentes perigosos e de isolamento respiratório são negativas.',
  pegadinha: 'Áreas limpas farmacêuticas costumam ser positivas por exigência de qualidade do produto, o que induz o candidato a generalizar. Quando o alvo é o trabalhador e o entorno, a lógica se inverte.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-031', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma refinaria, a área de amostragem de produto foi delimitada com faixas, sinalizada com placas de advertência e sujeita a permissão de trabalho. Sobre essas medidas, assinale a alternativa CORRETA:',
  alts: [
    { t: 'São controles administrativos e de sinalização, que reduzem a probabilidade de exposição indevida, mas não alteram a geração nem a concentração do agente na área.', ok: true,
      why: 'Correta. Delimitar, sinalizar e autorizar são medidas organizacionais: agem sobre quem entra e quando, e não sobre o agente.' },
    { t: 'São medidas de proteção coletiva de engenharia, equivalentes a enclausuramento.', ok: false,
      why: 'Errada. Enclausuramento é barreira física que contém o agente; sinalização e permissão de trabalho apenas regulam o acesso.' },
    { t: 'Dispensam a avaliação da exposição dos trabalhadores autorizados a entrar na área.', ok: false,
      why: 'Errada. Quem entra na área continua exposto e precisa ter sua exposição caracterizada e controlada.' },
    { t: 'Substituem a necessidade de proteção respiratória para quem executa a amostragem de produto.', ok: false,
      why: 'Errada. A restrição de acesso não reduz a concentração para quem executa a tarefa dentro da área.' },
    { t: 'São suficientes como medida definitiva quando não há orçamento para controles de engenharia.', ok: false,
      why: 'Errada. Restrição orçamentária não converte medida administrativa em solução definitiva; ela pode ser transitória, com cronograma.' }
  ],
  comentario: 'Sinalização, delimitação e permissão de trabalho são valiosas para limitar o número de expostos e organizar tarefas de risco, mas pertencem ao degrau administrativo. Quem executa a tarefa dentro da área permanece plenamente exposto.',
  pegadinha: 'A confusão entre "proteção coletiva" e "medida que abrange várias pessoas" faz o candidato promover sinalização a controle de engenharia.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-032', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma transportadora elabora seu programa de gerenciamento de riscos ocupacionais e pergunta qual a contribuição específica da higiene ocupacional nesse documento. A resposta CORRETA é:',
  alts: [
    { t: 'A higiene ocupacional fornece o reconhecimento dos agentes, a caracterização e a avaliação das exposições e a base técnica para hierarquizar e dimensionar as medidas de controle e seu cronograma.', ok: true,
      why: 'Correta. O inventário de riscos e o plano de ação só têm consistência técnica se alimentados por reconhecimento e avaliação de exposição bem feitos.' },
    { t: 'A contribuição se resume a anexar laudos de medição ao final do documento, sem influência sobre o plano de ação.', ok: false,
      why: 'Errada. Medições desconectadas do plano de ação produzem documento formalmente completo e tecnicamente inútil.' },
    { t: 'A higiene ocupacional atua apenas após a ocorrência de doença ocupacional reconhecida.', ok: false,
      why: 'Errada, e inverte a lógica preventiva. Ela é ferramenta de prevenção primária, anterior ao adoecimento.' },
    { t: 'A avaliação de exposição só é necessária para agentes com limite de tolerância previsto em norma.', ok: false,
      why: 'Errada. Agentes sem limite nacional também exigem caracterização e controle, com apoio em referências técnicas reconhecidas.' },
    { t: 'A hierarquização de riscos deve ser feita exclusivamente pela gravidade do dano, sem considerar probabilidade de ocorrência nem número de expostos.', ok: false,
      why: 'Errada. A priorização combina severidade, probabilidade e abrangência, além da existência de controles já implantados.' }
  ],
  comentario: 'No ciclo de gerenciamento de riscos, a higiene ocupacional responde por identificar, avaliar e propor controle das exposições, e por verificar se o controle funcionou. Sem esse conteúdo, o inventário vira lista genérica e o plano de ação vira intenção.',
  pegadinha: 'A ideia de que só agentes com limite normatizado precisam ser avaliados deixa fora agentes emergentes e boa parte dos carcinogênicos.',
  refs: ['NR-1 — Gerenciamento de Riscos Ocupacionais', 'Higiene ocupacional — avaliação e controle'] },

{ id: 'q-2.1-033', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma indústria de plásticos, a média ponderada da exposição a um solvente irritante ficou confortavelmente abaixo do limite, mas o registro contínuo mostrou picos elevados durante três operações de carga de reator, com duração de poucos minutos cada. A interpretação CORRETA é:',
  alts: [
    { t: 'A média pode mascarar picos de curta duração relevantes; agentes de ação irritante ou de efeito agudo exigem análise específica dos períodos curtos de exposição intensa.', ok: true,
      why: 'Correta. A média ponderada foi concebida para efeitos crônicos dependentes da dose acumulada e não protege contra efeitos agudos disparados por picos.' },
    { t: 'Como a média está abaixo do limite, os picos são irrelevantes para qualquer agente químico.', ok: false,
      why: 'Errada. Essa afirmação só teria sentido para agentes cujo único efeito relevante dependesse da dose acumulada, o que não é o caso de irritantes.' },
    { t: 'Os picos devem ser eliminados da série de dados por serem valores atípicos que distorcem a média.', ok: false,
      why: 'Errada, e é manipulação de dado. Picos operacionais recorrentes são parte da exposição real e devem ser caracterizados, não descartados.' },
    { t: 'A existência de picos indica erro do instrumento, pois exposição real varia pouco ao longo da jornada.', ok: false,
      why: 'Errada. Exposição ocupacional é intrinsecamente variável, e operações específicas produzem picos genuínos.' },
    { t: 'Basta reduzir o tempo total de jornada do trabalhador para eliminar o problema dos picos.', ok: false,
      why: 'Errada. Reduzir jornada diminui a dose acumulada, mas não altera a intensidade dos picos durante a operação de carga.' }
  ],
  comentario: 'Média ponderada e valores de curta duração respondem a perguntas diferentes: dose acumulada e pico agudo. Operações de carga, descarga, amostragem e limpeza são justamente onde os picos se concentram, e são as tarefas mais frequentemente esquecidas na amostragem.',
  pegadinha: 'Descartar picos como valores atípicos é o erro estatístico e ético mais grave possível nessa análise: eles são o dado, não o ruído.',
  refs: ['ACGIH — TLV-TWA e TLV-STEL', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-034', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Durante o reconhecimento de risco químico em uma tinturaria, o médico do trabalho consulta os rótulos e as fichas de dados de segurança dos produtos. Sobre o uso dessas fontes, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Rótulo e ficha de dados de segurança informam perigos, pictogramas, frases de perigo e medidas de primeiros socorros, mas não substituem a caracterização da exposição no posto de trabalho.', ok: true,
      why: 'Correta. Esses documentos descrevem propriedades do produto; a exposição depende da quantidade manipulada, da forma de uso, da ventilação e da tarefa real.' },
    { t: 'A ficha de dados de segurança informa a concentração ambiental esperada em cada posto de trabalho.', ok: false,
      why: 'Errada. Ela não pode prever concentração ambiental, que depende de variáveis específicas de cada instalação.' },
    { t: 'A ausência de pictograma de perigo no rótulo garante que o produto não oferece risco à saúde.', ok: false,
      why: 'Errada. Rotulagem incompleta ou desatualizada é comum, e ausência de símbolo não é prova de inocuidade.' },
    { t: 'Produtos formulados dispensam ficha de dados de segurança quando cada componente isolado já possui a sua.', ok: false,
      why: 'Errada. A mistura tem propriedades próprias e exige documento específico da formulação comercializada.' },
    { t: 'A ficha de dados de segurança dispensa a identificação de subprodutos gerados durante o processo.', ok: false,
      why: 'Errada. Subprodutos de aquecimento, decomposição ou reação não constam do produto original e precisam ser reconhecidos à parte.' }
  ],
  comentario: 'Ficha e rótulo são o ponto de partida do reconhecimento de risco químico, nunca o ponto de chegada. Dois erros derrubam quem confia demais neles: ignorar subprodutos do processo e confundir perigo intrínseco com exposição real.',
  pegadinha: 'Achar que a ficha de dados de segurança informa a concentração no ambiente confunde propriedade do produto com condição da instalação.',
  refs: ['Sistema Globalmente Harmonizado — GHS', 'NR-26', 'Higiene ocupacional — reconhecimento'] },

{ id: 'q-2.1-035', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um residente de medicina do trabalho apresenta um seminário sobre higiene ocupacional em uma indústria de fertilizantes. Assinale a alternativa INCORRETA entre as afirmações apresentadas:',
  alts: [
    { t: 'A etapa de avaliação é sempre obrigatória antes de qualquer medida de controle, mesmo quando o reconhecimento já demonstra situação de risco evidente.', ok: true,
      why: 'É a alternativa INCORRETA, portanto a resposta. Quando o reconhecimento evidencia risco grave, o controle deve ser imediato; esperar a medição para agir é erro de conduta.' },
    { t: 'A antecipação atua sobre projetos e mudanças, evitando a introdução de novos riscos no ambiente de trabalho.', ok: false,
      why: 'Verdadeira. É a definição da etapa e sua principal vantagem econômica e técnica.' },
    { t: 'O reconhecimento identifica agentes, fontes, vias de exposição e trabalhadores potencialmente expostos.', ok: false,
      why: 'Verdadeira. É a etapa qualitativa que estrutura o problema antes de qualquer medição.' },
    { t: 'A avaliação compara a exposição caracterizada com critérios técnicos e legais de referência, considerando a variabilidade das medições.', ok: false,
      why: 'Verdadeira. Avaliar é confrontar dado com critério, reconhecendo a incerteza inerente à amostragem.' },
    { t: 'O controle deve seguir a hierarquia de medidas e ser verificado quanto à eficácia após a implantação.', ok: false,
      why: 'Verdadeira. Sem verificação posterior não se sabe se a medida funcionou nas condições reais de operação.' }
  ],
  comentario: 'As quatro etapas descrevem um método, não uma sequência burocrática obrigatória. Diante de risco evidente e grave reconhecido qualitativamente, o controle é imediato e a medição serve para dimensionar e verificar, não para autorizar a ação.',
  pegadinha: 'A afirmação falsa é sedutora porque parece defender o rigor metodológico, quando na prática transforma o método em desculpa para adiar proteção.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'AIHA — estratégia de avaliação e gerenciamento de exposições'] },

{ id: 'q-2.1-036', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma oficina de solda, um exaustor de teto foi instalado a vários metros acima dos postos, com a justificativa de que "os fumos sobem naturalmente". Trabalhadores continuam com sintomas respiratórios. A análise CORRETA da situação é:',
  alts: [
    { t: 'A captação distante da fonte é ineficaz e, no caso da solda, os fumos ascendentes atravessam a zona respiratória do soldador antes de alcançar o exaustor de teto; a solução é captação localizada junto ao ponto de solda.', ok: true,
      why: 'Correta. A pluma térmica ascendente passa exatamente pela face do soldador debruçado sobre a peça; captar no teto não impede essa passagem.' },
    { t: 'A instalação está correta, pois a convecção térmica garante que o contaminante não permaneça na zona respiratória.', ok: false,
      why: 'Errada. A convecção conduz a pluma para cima justamente através da posição da cabeça do soldador.' },
    { t: 'Correntes de ar cruzadas no galpão melhoram o desempenho da captação, ao empurrar os fumos para o exaustor.', ok: false,
      why: 'Errada. Correntes cruzadas desviam a pluma e prejudicam a captura, sendo uma das principais causas de falha de sistemas de exaustão.' },
    { t: 'O problema se resolve aumentando o pé-direito do galpão, o que diluiria os fumos antes de atingirem o trabalhador.', ok: false,
      why: 'Errada. Maior volume dilui a concentração média do galpão, mas não altera a concentração na zona respiratória junto à fonte.' },
    { t: 'A única solução tecnicamente possível é fornecer respirador de adução de ar a todos os soldadores.', ok: false,
      why: 'Errada. Existem soluções de engenharia consagradas, como braços articulados de exaustão e mesas com captação inferior.' }
  ],
  comentario: 'Solda é o exemplo didático de por que a captação deve ser localizada: a pluma ascendente nasce a poucos centímetros do rosto do trabalhador. Exaustores de teto ventilam o galpão e não protegem o soldador.',
  pegadinha: 'O argumento de que "os fumos sobem" é verdadeiro e leva à conclusão errada: eles sobem passando pela zona respiratória.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-037', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao discutir a amostragem de material particulado em uma cerâmica, o higienista explica ao médico do trabalho as frações de aerodispersoides adotadas em avaliação ocupacional. A explicação CORRETA é:',
  alts: [
    { t: 'A fração inalável corresponde ao que penetra pelo nariz e pela boca, a torácica ao que ultrapassa a laringe e a respirável ao que alcança a região de trocas gasosas, e a escolha da fração depende do local de ação do agente.', ok: true,
      why: 'Correta. As frações são definidas por probabilidade de penetração em regiões sucessivas do trato respiratório, e o agente determina qual delas deve ser amostrada.' },
    { t: 'As três frações são intercambiáveis, bastando amostrar a poeira total para caracterizar qualquer exposição a particulado.', ok: false,
      why: 'Errada. Amostrar poeira total sem definir a fração de interesse impede comparação com critérios e pode subestimar ou superestimar a exposição relevante.' },
    { t: 'A fração respirável é a maior das três em massa, por incluir todas as partículas suspensas no ar.', ok: false,
      why: 'Errada, e inverte a relação. A respirável é a mais restritiva, um subconjunto da torácica, que por sua vez é subconjunto da inalável.' },
    { t: 'Para agentes que atuam nas vias aéreas superiores, a fração respirável é a mais adequada por ser a mais conservadora.', ok: false,
      why: 'Errada. Se o efeito ocorre nas vias superiores, a fração pertinente é a inalável; medir só a respirável deixaria de fora a maior parte do agente relevante.' },
    { t: 'A definição das frações depende exclusivamente da composição química da partícula, e não do seu tamanho aerodinâmico.', ok: false,
      why: 'Errada. As frações são definidas pelo comportamento aerodinâmico das partículas; a composição química determina o efeito, não a penetração.' }
  ],
  comentario: 'A pergunta prática é sempre a mesma: onde o agente causa dano? Sílica cristalina causa fibrose no parênquima e é avaliada na fração respirável; poeira de madeira atua também nas vias superiores e exige a fração inalável. Escolher a fração errada invalida a avaliação.',
  pegadinha: 'A ideia de que a fração respirável é sempre a mais conservadora confunde restritividade do tamanho com severidade do critério.',
  refs: ['NHO 08 — Fundacentro', 'ACGIH — frações de aerodispersoides'] },

{ id: 'q-2.1-038', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma empresa de médio porte, discute-se a divisão de tarefas entre o médico do trabalho, o engenheiro de segurança e o higienista ocupacional na gestão das exposições. Sobre essa atuação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A atuação é interdisciplinar e complementar: a caracterização técnica das exposições subsidia a definição do acompanhamento de saúde, e os achados clínicos e epidemiológicos retroalimentam a revisão dos controles.', ok: true,
      why: 'Correta. Nenhuma das áreas resolve sozinha o problema; a integração entre dado ambiental e dado de saúde é o que permite ajustar o programa.' },
    { t: 'Cabe ao médico do trabalho executar pessoalmente as medições ambientais, sob pena de não poder interpretá-las.', ok: false,
      why: 'Errada. Interpretar competentemente dados de exposição não exige executar a medição, que é atribuição técnica específica.' },
    { t: 'O médico do trabalho deve limitar-se aos exames, sem opinar sobre a suficiência das medidas de controle.', ok: false,
      why: 'Errada. Avaliar se o controle protege é parte central da atuação médica em saúde do trabalho, inclusive quando surgem casos sentinela.' },
    { t: 'Quando há laudo assinado por profissional habilitado, o médico do trabalho não pode questionar suas conclusões.', ok: false,
      why: 'Errada. Laudo é documento técnico sujeito a crítica; conclusões incompatíveis com o quadro de saúde observado devem ser questionadas.' },
    { t: 'A responsabilidade pela eliminação do risco recai sobre o profissional de segurança, e não sobre a empresa.', ok: false,
      why: 'Errada. A responsabilidade pela segurança e saúde no trabalho é do empregador; os profissionais assessoram tecnicamente.' }
  ],
  comentario: 'O médico do trabalho não precisa operar uma bomba de amostragem, mas precisa saber ler um relatório de exposição, identificar amostragem mal feita e reconhecer quando o achado clínico contradiz a conclusão do laudo.',
  pegadinha: 'A alternativa que proíbe o médico de questionar laudo assinado confunde habilitação técnica com infalibilidade e paralisa a vigilância.',
  refs: ['NR-4', 'NR-7 — PCMSO', 'Atuação interdisciplinar em saúde do trabalhador'] }

/* FIM-LOTE */
);
