/* Seção 2 — temas que estavam sem questão nenhuma (2.4, 2.5, 2.7, 2.8)
   Questões AUTORAIS, escritas no estilo da banca. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(

/* ============================ 2.4 Agentes Biológicos ===================== */
{ id: 'q-2.4-010', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um laboratório de análises clínicas vai passar a processar amostras de um agente que, segundo a classificação de risco dos agentes biológicos, pode causar doença grave no ser humano, representa risco para quem trabalha, tem risco limitado de disseminação na comunidade e dispõe de medidas eficazes de tratamento e prevenção. Essa descrição corresponde à classe de risco:',
  alts: [
    { t: 'Classe de risco 3.', ok: true,
      why: 'Correta. A classe 3 reúne agentes de alto risco individual e risco moderado ou limitado para a comunidade, capazes de causar doença grave, com tratamento e profilaxia geralmente disponíveis.' },
    { t: 'Classe de risco 1.', ok: false,
      why: 'Errada. A classe 1 reúne agentes com baixo risco individual e para a comunidade, com pouca ou nenhuma probabilidade de causar doença no ser humano saudável.' },
    { t: 'Classe de risco 2.', ok: false,
      why: 'Errada. A classe 2 tem risco individual moderado e risco comunitário limitado, causando doença geralmente não grave, com exposição de menor gravidade que a descrita.' },
    { t: 'Classe de risco 4.', ok: false,
      why: 'Errada. A classe 4 exige alto risco individual E alto risco de disseminação comunitária, em geral sem tratamento ou profilaxia eficazes — o enunciado diz justamente o contrário nesses dois pontos.' },
    { t: 'A classificação depende exclusivamente da via de transmissão, não da gravidade.', ok: false,
      why: 'Errada. A classificação combina risco individual, risco para a comunidade, gravidade e existência de profilaxia e tratamento; a via de transmissão é um dos elementos, não o único critério.' }
  ],
  comentario: 'A classificação anda em dois eixos: risco para o indivíduo e risco para a comunidade. Classe 1 baixo/baixo; classe 2 moderado/limitado; classe 3 alto/limitado com tratamento disponível; classe 4 alto/alto e em geral sem profilaxia ou tratamento eficazes.',
  pegadinha: 'A diferença entre 3 e 4 está na DISSEMINAÇÃO COMUNITÁRIA e na existência de tratamento. Quem só olha "doença grave" marca 4.',
  refs: ['Classificação de Risco dos Agentes Biológicos — Ministério da Saúde', 'NR-32'] },

{ id: 'q-2.4-011', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em um hospital, discute-se quais precauções adotar para um paciente com suspeita de tuberculose pulmonar bacilífera internado em enfermaria. Sobre precauções e risco biológico ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Além das padrão, precauções para aerossóis, com quarto adequado e respirador apropriado.', ok: true,
      why: 'Correta. A via de transmissão define o equipamento e o tipo de ambiente.' },
    { t: 'Basta a precaução de gotículas, com uso de máscara cirúrgica pelos profissionais que entram.', ok: false,
      why: 'Errada. A via aérea por aerossóis exige respirador com filtração de partículas.' },
    { t: 'As precauções padrão só se aplicam aos pacientes com diagnóstico infeccioso já confirmado.', ok: false,
      why: 'Errada. Aplicam-se a todos os pacientes, sempre.' },
    { t: 'A vacinação prévia do profissional dispensa o uso de proteção respiratória nesse contexto clínico.', ok: false,
      why: 'Errada. A proteção respiratória permanece indicada.' },
    { t: 'O uso de luvas substitui a higienização das mãos quando há contato apenas com superfícies.', ok: false,
      why: 'Errada. A higienização das mãos é indispensável e complementar.' }
  ],
  comentario: 'Precauções padrão valem para todo paciente, sempre. Sobre elas somam-se as precauções por via de transmissão: contato, gotículas ou aerossóis. Tuberculose pulmonar bacilífera pede precaução para aerossóis, com proteção respiratória adequada e ambiente apropriado.',
  pegadinha: 'A confusão entre gotícula e aerossol é a mais explorada: gotícula cai perto, aerossol fica suspenso — e isso muda a máscara e o quarto.',
  refs: ['NR-32', 'Protocolo de vigilância da infecção latente pelo M. tuberculosis — Ministério da Saúde'] },

{ id: 'q-2.4-012', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadores de uma estação de tratamento de esgoto relatam quadros febris após período de chuvas intensas com alagamento da área operacional. Sobre risco biológico em saneamento, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Considerar leptospirose, por contato de pele lesada ou mucosas com água contaminada.', ok: true,
      why: 'Correta. O quadro varia de leve a formas graves, renais e hemorrágicas.' },
    { t: 'O risco no saneamento restringe-se a agentes de veiculação aérea, sendo desprezível a via cutânea.', ok: false,
      why: 'Errada. A via cutânea é a principal na leptospirose.' },
    { t: 'Considerar leptospirose, doença exclusivamente rural, que não ocorre em trabalhadores urbanos.', ok: false,
      why: 'Errada. É frequente em saneamento urbano, por urina de roedores.' },
    { t: 'Considerar leptospirose, que por ser comum na população nunca configura doença do trabalho.', ok: false,
      why: 'Errada. Quando a atividade determina a exposição, o nexo é reconhecido.' },
    { t: 'Considerar leptospirose, cuja única medida eficaz é a vacinação dos trabalhadores expostos.', ok: false,
      why: 'Errada. Não há vacina humana de uso corrente; a prevenção é por barreiras.' }
  ],
  comentario: 'Saneamento concentra risco biológico por contato cutâneo-mucoso. Leptospirose é o exemplo cobrado: transmissão por água ou lama contaminada com urina de roedores, agravada por alagamentos, com espectro clínico amplo. E atenção ao nexo — exposição determinada pela natureza do trabalho afasta a exclusão de "doença endêmica".',
  pegadinha: 'A alternativa que nega o nexo por ser "doença comum na população" reproduz um erro clássico: a exclusão legal tem ressalva expressa para exposição decorrente do trabalho.',
  refs: ['Nota Técnica Leptospirose — Ministério da Saúde', 'Lei nº 8.213/1991 — art. 20, §1º'] },

{ id: 'q-2.4-013', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o gerenciamento do risco biológico em serviços de saúde, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O reencape manual é aceitável com técnica de uma só mão e por profissional treinado.', ok: true,
      why: 'É a INCORRETA. O reencape é prática vedada em qualquer circunstância.' },
    { t: 'Dispositivos de segurança em perfurocortantes reduzem acidentes e devem ser priorizados na compra.', ok: false,
      why: 'Correta, portanto não é a resposta. É medida de engenharia eficaz.' },
    { t: 'O recipiente deve ser rígido, ficar próximo ao procedimento e respeitar o limite de preenchimento.', ok: false,
      why: 'Correta, portanto não é a resposta. São requisitos do descarte seguro.' },
    { t: 'Todo acidente com material biológico deve ser registrado e comunicado, mesmo sem soroconversão.', ok: false,
      why: 'Correta, portanto não é a resposta. O registro é devido no momento do acidente.' },
    { t: 'A capacitação é medida necessária, mas não substitui as medidas de proteção coletiva e de engenharia.', ok: false,
      why: 'Correta, portanto não é a resposta. É a hierarquia de controle.' }
  ],
  comentario: 'Três pontos fixos: reencape de agulha é proibido, sem exceção de técnica; dispositivos de segurança são medida de engenharia prioritária; e todo acidente com material biológico gera registro e comunicação, independentemente de soroconversão.',
  pegadinha: 'A "técnica de uma só mão" existe como manobra descrita em literatura antiga e por isso soa plausível — mas a orientação vigente é não reencapar.',
  refs: ['NR-32', 'PCDT — Profilaxia Pós-Exposição — Ministério da Saúde'] },

{ id: 'q-2.4-014', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um frigorífico de suínos solicita avaliação do risco biológico para seus trabalhadores. Sobre exposição ocupacional a agentes biológicos fora dos serviços de saúde, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Animais, produtos de origem animal e dejetos expõem a zoonoses, conforme as tarefas concretas.', ok: true,
      why: 'Correta. Abate, evisceração e manejo de resíduos importam mais que o setor econômico.' },
    { t: 'O risco biológico ocupacional é matéria restrita aos serviços de saúde e aos laboratórios clínicos.', ok: false,
      why: 'Errada. Agropecuária, saneamento e abate expõem intensamente.' },
    { t: 'A ausência de casos notificados na empresa demonstra que não há exposição a agentes biológicos.', ok: false,
      why: 'Errada. Pode indicar apenas ausência de vigilância e subnotificação.' },
    { t: 'Para agentes biológicos, a avaliação quantitativa no ar é sempre obrigatória e determina o controle.', ok: false,
      why: 'Errada. A avaliação de risco biológico é qualitativa, pelas tarefas.' },
    { t: 'A vacinação dos trabalhadores expostos torna dispensáveis os equipamentos de proteção da atividade.', ok: false,
      why: 'Errada. A vacina cobre um agente; as barreiras cobrem os demais.' }
  ],
  comentario: 'A avaliação de risco biológico é essencialmente qualitativa: identificar fonte, tarefa, via de exposição e população exposta. E o campo não é só hospital — frigorífico, saneamento, campo e coleta de resíduos entram com força.',
  pegadinha: 'A exigência de "avaliação quantitativa obrigatória" transporta a lógica dos agentes químicos para os biológicos, onde ela não se aplica do mesmo modo.',
  refs: ['Classificação de Risco dos Agentes Biológicos — Ministério da Saúde', 'NR-9'] },

{ id: 'q-2.4-015', tema: '2.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de necrotério sofre corte com instrumento contaminado. O serviço médico avalia a conduta. Sobre a exposição ocupacional a material biológico, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Depende do tipo de exposição, do material e do estado sorológico da fonte, quando conhecido.', ok: true,
      why: 'Correta. A avaliação para profilaxia deve ser feita com urgência.' },
    { t: 'Exposições ocorridas fora de serviços assistenciais não configuram acidente com material biológico.', ok: false,
      why: 'Errada. Configuram, e seguem o mesmo protocolo.' },
    { t: 'Depende do tipo de exposição, devendo aguardar as sorologias do trabalhador antes da profilaxia.', ok: false,
      why: 'Errada. A eficácia da profilaxia depende do início precoce.' },
    { t: 'Depende do tipo de exposição, sendo a sorologia basal dispensável no trabalhador assintomático.', ok: false,
      why: 'Errada. A basal é o que permite caracterizar soroconversão depois.' },
    { t: 'Depende do tipo de exposição, sendo desnecessário o seguimento se a profilaxia foi iniciada.', ok: false,
      why: 'Errada. O seguimento sorológico permanece indicado.' }
  ],
  comentario: 'Roteiro: cuidado local, avaliação imediata da exposição e da fonte, decisão sobre profilaxia dentro da janela, coleta de sorologia basal do trabalhador, registro e comunicação, e seguimento sorológico. Nenhuma dessas etapas depende de o serviço ser assistencial.',
  pegadinha: 'A alternativa que manda "aguardar as sorologias" parece prudente e é justamente o erro que inviabiliza a profilaxia.',
  refs: ['PCDT — Profilaxia Pós-Exposição (PEP) — Ministério da Saúde', 'NR-32'] },

/* ============= 2.5 Avaliação e Gerenciamento das Exposições ============== */
{ id: 'q-2.5-010', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao estruturar a avaliação de exposições ocupacionais em uma indústria com centenas de trabalhadores, o higienista propõe agrupar os trabalhadores antes de amostrar. Sobre grupos similares de exposição, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Reúne trabalhadores de exposição presumidamente semelhante, hipótese que precisa ser verificada.', ok: true,
      why: 'Correta. A similaridade se confirma nos resultados, não se presume apenas.' },
    { t: 'Deve seguir o organograma da empresa, reunindo os trabalhadores por setor administrativo de lotação.', ok: false,
      why: 'Errada. O critério é a semelhança de exposição.' },
    { t: 'Reúne exposições semelhantes, bastando uma amostra por grupo para caracterizá-lo conclusivamente.', ok: false,
      why: 'Errada. É preciso amostra suficiente para verificar a homogeneidade.' },
    { t: 'Reúne exposições semelhantes e, uma vez formado, não deve ser revisado, por comparabilidade histórica.', ok: false,
      why: 'Errada. Variabilidade nos resultados obriga a rever o grupo.' },
    { t: 'Reúne exposições semelhantes, dispensando a caracterização básica do ambiente e dos processos.', ok: false,
      why: 'Errada. É ela que fundamenta a formação dos grupos.' }
  ],
  comentario: 'A estratégia é: caracterização básica → formação de grupos similares de exposição → amostragem → julgamento (aceitável, inaceitável ou incerto) → controle → reavaliação. O grupo é hipótese testável, não rótulo administrativo.',
  pegadinha: 'Agrupar por setor ou por cargo é o atalho mais comum na prática e está errado: dois trabalhadores do mesmo cargo podem ter exposições muito diferentes.',
  refs: ['Jahn, Bullock & Ignacio — Uma estratégia para avaliar e gerenciar exposições ocupacionais (ABHO)'] },

{ id: 'q-2.5-011', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um conjunto de medições de um agente químico em um grupo de exposição resultou em valores dispersos, com algumas medidas próximas do limite e outras muito abaixo. O laudo conclui pela regularidade usando a MÉDIA das medições. A crítica CORRETA a essa conclusão é:',
  alts: [
    { t: 'O julgamento se apoia na parte superior da distribuição, e não na média dos resultados.', ok: true,
      why: 'Correta. Importa a probabilidade de exposições acima do limite ao longo do tempo.' },
    { t: 'A média está correta, desde que calculada sobre pelo menos três medições válidas do mesmo grupo.', ok: false,
      why: 'Errada. A média esconde a fração de jornadas acima do limite.' },
    { t: 'A dispersão dos resultados indica erro laboratorial e invalida todas as medições realizadas.', ok: false,
      why: 'Errada. Exposições ocupacionais são naturalmente variáveis.' },
    { t: 'Diante da dispersão, o correto é descartar os valores extremos e recalcular a média do conjunto.', ok: false,
      why: 'Errada. Os extremos superiores são justamente o que interessa.' },
    { t: 'Como algumas medidas ficaram abaixo do limite, está demonstrado que o controle é eficaz no setor.', ok: false,
      why: 'Errada. O que importa é a fração de jornadas acima do limite.' }
  ],
  comentario: 'Exposição ocupacional varia e costuma seguir distribuição assimétrica. Por isso o julgamento olha a cauda superior — a probabilidade de exposições acima do limite — e não a média. Descartar valores altos como "atípicos" é o oposto do que a proteção exige.',
  pegadinha: 'A alternativa de descartar extremos parece rigor estatístico e é, na prática, o artifício mais usado para maquiar laudo.',
  refs: ['Jahn, Bullock & Ignacio — Uma estratégia para avaliar e gerenciar exposições ocupacionais (ABHO)'] },

{ id: 'q-2.5-012', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Após a avaliação de um grupo de exposição, o higienista classifica o resultado como "incerto". Sobre essa categoria de julgamento, a conduta CORRETA é:',
  alts: [
    { t: 'Reunir mais informação até migrar para aceitável ou inaceitável, com medidas de precaução.', ok: true,
      why: 'Correta. Novas amostragens, revisão da caracterização ou dados análogos resolvem.' },
    { t: 'Tratar como aceitável até prova em contrário, para não onerar a empresa sem evidência técnica.', ok: false,
      why: 'Errada. A incerteza recomenda precaução, não permissividade.' },
    { t: 'Tratar automaticamente como inaceitável e paralisar a atividade até nova avaliação conclusiva.', ok: false,
      why: 'Errada. A categoria pede mais informação, não paralisação automática.' },
    { t: 'Encerrar a avaliação, já que a categoria de incerteza não gera obrigação técnica à empresa.', ok: false,
      why: 'Errada. Gera a obrigação de reduzir a incerteza.' },
    { t: 'Substituir a avaliação técnica por questionário de percepção de risco aplicado aos trabalhadores.', ok: false,
      why: 'Errada. A percepção é insumo, não substitui a avaliação.' }
  ],
  comentario: 'O julgamento tem três saídas: aceitável, inaceitável e incerto. A terceira não é um lugar de descanso — é um pedido de mais informação, com precaução mantida enquanto a dúvida existir.',
  pegadinha: 'Converter "incerto" em "aceitável" é o desvio mais comum e o mais perigoso, porque parece neutro.',
  refs: ['Jahn, Bullock & Ignacio — Uma estratégia para avaliar e gerenciar exposições ocupacionais (ABHO)'] },

{ id: 'q-2.5-013', tema: '2.5', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa implanta enclausuramento e ventilação local exaustora em um posto com exposição a vapores orgânicos. Sobre a etapa seguinte do gerenciamento das exposições, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A eficácia precisa ser verificada por reavaliação: controle implantado não é controle eficaz.', ok: true,
      why: 'Correta. Só a medição posterior demonstra a redução obtida.' },
    { t: 'Implantada a medida, a exposição pode ser considerada controlada e o grupo sai do monitoramento.', ok: false,
      why: 'Errada. É preciso medir o desempenho na condição real de operação.' },
    { t: 'A reavaliação só é necessária se algum trabalhador apresentar alteração no monitoramento biológico.', ok: false,
      why: 'Errada. A verificação é parte do ciclo de controle, não reativa.' },
    { t: 'Com controle de engenharia instalado, o programa médico de acompanhamento pode ser descontinuado.', ok: false,
      why: 'Errada. A vigilância da saúde permanece dirigida ao risco.' },
    { t: 'A manutenção do sistema de exaustão é responsabilidade do trabalhador que ocupa aquele posto.', ok: false,
      why: 'Errada. É obrigação da empresa, com rotina definida.' }
  ],
  comentario: 'Gerenciar exposição é ciclo, não evento: caracterizar, avaliar, julgar, controlar e REAVALIAR. A reavaliação é a etapa que a prática costuma pular — e é ela que separa controle presumido de controle demonstrado.',
  pegadinha: 'Condicionar a reavaliação a uma alteração no monitoramento biológico transforma o trabalhador em sensor de falha do sistema.',
  refs: ['Jahn, Bullock & Ignacio — Uma estratégia para avaliar e gerenciar exposições ocupacionais (ABHO)', 'NR-9'] },

/* ================= 2.7 Normas de Higiene Ocupacional (NHO) =============== */
{ id: 'q-2.7-010', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um perito judicial questiona por que a dose de ruído calculada por um laudo baseado em Norma de Higiene Ocupacional da Fundacentro difere daquela obtida pelo critério da norma regulamentadora de insalubridade, para a mesma jornada. A explicação CORRETA é:',
  alts: [
    { t: 'Os dois critérios usam incrementos de duplicação diferentes, o que muda a dose calculada.', ok: true,
      why: 'Correta. A norma de higiene adota critério mais protetor que a de insalubridade.' },
    { t: 'A diferença entre os dois resultados decorre apenas de erro de calibração do dosímetro utilizado.', ok: false,
      why: 'Errada. Decorre do incremento de duplicação de dose adotado.' },
    { t: 'As normas de higiene ocupacional revogaram os critérios da norma regulamentadora para insalubridade.', ok: false,
      why: 'Errada. Coexistem, com finalidades distintas.' },
    { t: 'As normas de higiene ocupacional aplicam-se apenas a agentes químicos, e não à avaliação de ruído.', ok: false,
      why: 'Errada. Há norma de higiene específica para ruído.' },
    { t: 'Ambos os critérios produzem sempre o mesmo resultado com nível constante, o que indica erro no laudo.', ok: false,
      why: 'Errada. Os incrementos diferentes produzem doses diferentes.' }
  ],
  comentario: 'Ponto de ouro deste tema: norma técnica de higiene diz COMO medir e avaliar, com critério mais protetor; norma regulamentadora diz qual é o LIMITE LEGAL e o que caracteriza insalubridade. Convivem, com finalidades distintas, e é normal que os números divirjam.',
  pegadinha: 'Tratar a divergência como erro de medição é o equívoco que a questão persegue. Ela é metodológica e previsível.',
  refs: ['Normas de Higiene Ocupacional — Fundacentro', 'NR-15'] },

{ id: 'q-2.7-011', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a natureza e o uso das Normas de Higiene Ocupacional da Fundacentro, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'Por serem de instituição federal, têm força de norma e geram autuação direta da inspeção.', ok: true,
      why: 'É a INCORRETA. São referências técnicas, não normas regulamentadoras.' },
    { t: 'Padronizam os procedimentos de avaliação, aumentando a comparabilidade e a defensabilidade técnica.', ok: false,
      why: 'Correta, portanto não é a resposta. É sua função principal.' },
    { t: 'Existem normas específicas para diferentes agentes, como ruído, calor e vibração ocupacional.', ok: false,
      why: 'Correta, portanto não é a resposta. O conjunto é organizado por agente.' },
    { t: 'Servem de referência técnica em perícias e em discussões judiciais sobre exposição ocupacional.', ok: false,
      why: 'Correta, portanto não é a resposta. É uso corrente e reconhecido.' },
    { t: 'A adoção de critério mais protetor que o legal é compatível com a política de prevenção da empresa.', ok: false,
      why: 'Correta, portanto não é a resposta. É permitido e recomendável.' }
  ],
  comentario: 'Guarde a distinção de natureza jurídica: norma técnica de higiene é referência metodológica; norma regulamentadora é obrigação legal com poder de autuação. Confundir as duas gera erro tanto na prova quanto na prática pericial.',
  pegadinha: 'Enunciado de "assinale a INCORRETA", e a falsa é a que dá força de lei a documento técnico — hipótese que soa razoável por vir de instituição federal.',
  refs: ['Normas de Higiene Ocupacional — Fundacentro', 'Portaria nº 3.214/1978'] },

{ id: 'q-2.7-012', tema: '2.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao avaliar a exposição ocupacional ao calor em uma siderúrgica seguindo a norma técnica de higiene aplicável, o profissional deve considerar que:',
  alts: [
    { t: 'Combina as variáveis ambientais num índice e o confronta com a taxa metabólica da atividade.', ok: true,
      why: 'Correta. A mesma condição é aceitável no leve e inaceitável no esforço pesado.' },
    { t: 'Basta medir a temperatura do ar no posto, pois as demais variáveis têm influência desprezível.', ok: false,
      why: 'Errada. Umidade, radiação e velocidade do ar compõem o índice.' },
    { t: 'Combina as variáveis num índice, sendo a taxa metabólica irrelevante por já estar nele incorporada.', ok: false,
      why: 'Errada. O índice descreve o ambiente; o metabolismo entra à parte.' },
    { t: 'Combina as variáveis, devendo a avaliação ser feita no período mais frio, como condição habitual.', ok: false,
      why: 'Errada. Avalia-se a condição mais desfavorável da jornada.' },
    { t: 'Combina as variáveis num índice, sendo a avaliação dispensada quando o trabalhador é aclimatado.', ok: false,
      why: 'Errada. A aclimatação altera a tolerância, não a exigência de avaliar.' }
  ],
  comentario: 'Calor se avalia em dois lados: o ambiente, por um índice que combina temperatura, umidade, radiação e velocidade do ar, e o organismo, pela taxa metabólica da tarefa. A condição de aclimatização modula o julgamento, sem eliminá-lo.',
  pegadinha: 'A alternativa que diz que o índice "já incorpora o esforço" é atraente e falsa — ela apaga justamente o segundo lado da comparação.',
  refs: ['NHO 06 — Avaliação da exposição ocupacional ao calor (Fundacentro)'] },

/* ====================== 2.8 Proteção Respiratória ======================== */
{ id: 'q-2.8-010', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa precisa selecionar respiradores para trabalhadores que entrarão em um tanque para limpeza, ambiente onde a concentração do contaminante é desconhecida e há risco de deficiência de oxigênio. A seleção CORRETA é:',
  alts: [
    { t: 'Respirador de adução de ar, autônomo ou de linha com cilindro auxiliar de escape.', ok: true,
      why: 'Correta. Em deficiência de oxigênio o purificador de ar é inadequado.' },
    { t: 'Peça semifacial filtrante de alta eficiência, desde que substituída ao término de cada jornada.', ok: false,
      why: 'Errada. Filtro não supre oxigênio nem cobre concentração desconhecida.' },
    { t: 'Respirador purificador motorizado, pois o fluxo assistido compensa a deficiência de oxigênio.', ok: false,
      why: 'Errada. Purifica o ar existente; não gera oxigênio.' },
    { t: 'Máscara facial inteira com filtro combinado, por oferecer vedação superior às demais opções.', ok: false,
      why: 'Errada. A vedação não resolve a falta de oxigênio.' },
    { t: 'Qualquer respirador certificado, desde que haja treinamento e ensaio de vedação do trabalhador.', ok: false,
      why: 'Errada. A classe do respirador é definida pela atmosfera.' }
  ],
  comentario: 'Regra que resolve a maioria das questões: purificador de ar SÓ serve quando há oxigênio suficiente E o contaminante é conhecido e está dentro da capacidade do filtro. Atmosfera com deficiência de oxigênio, concentração desconhecida ou condição imediatamente perigosa à vida exige adução de ar.',
  pegadinha: 'A alternativa do purificador motorizado explora a ideia de que "mais ar" resolve. O ar continua sendo o do ambiente.',
  refs: ['Torloni & Vieira — Manual de Proteção Respiratória', 'NR-6'] },

{ id: 'q-2.8-011', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Durante a implantação de um programa de proteção respiratória, um trabalhador que usa respirador facial se recusa a raspar a barba por motivo pessoal. Sobre a conduta, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Pelos na zona de vedação comprometem o desempenho: cabe oferecer alternativa sem vedação facial.', ok: true,
      why: 'Correta. Manter equipamento inadequado não é solução.' },
    { t: 'Basta apertar mais os tirantes do respirador para compensar a falha de vedação identificada.', ok: false,
      why: 'Errada. Não corrige a falha e gera desconforto e lesão.' },
    { t: 'O uso sobre a barba é aceitável desde que o trabalhador assine termo de responsabilidade.', ok: false,
      why: 'Errada. Termo assinado não produz proteção.' },
    { t: 'A questão é estética e não interfere no desempenho do equipamento de proteção respiratória.', ok: false,
      why: 'Errada. A vedação é o que define a proteção obtida.' },
    { t: 'O ensaio de vedação é dispensável quando o respirador é de boa qualidade e devidamente certificado.', ok: false,
      why: 'Errada. Certificação atesta o equipamento, não a adequação ao rosto.' }
  ],
  comentario: 'Três pilares do programa: seleção adequada à exposição, ensaio de vedação para o rosto de cada trabalhador e avaliação médica de aptidão para uso. Barba na zona de selagem é incompatível com respirador que dependa de vedação facial — e a resposta é técnica, não disciplinar.',
  pegadinha: 'O "termo de responsabilidade" aparece com frequência e é sempre distrator: não existe consentimento que substitua proteção eficaz.',
  refs: ['Torloni & Vieira — Manual de Proteção Respiratória', 'NR-6'] },

{ id: 'q-2.8-012', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'O médico do trabalho é procurado para definir a avaliação médica dos trabalhadores que usarão respiradores. Sobre esse componente do programa de proteção respiratória, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Verifica se o trabalhador tolera a carga do respirador e da tarefa, inclusive claustrofobia.', ok: true,
      why: 'Correta. Considera função cardiorrespiratória e condições que dificultem a vedação.' },
    { t: 'Limita-se à espirometria, exame que sozinho define a aptidão para o uso de respirador na função.', ok: false,
      why: 'Errada. A avaliação é clínica e mais ampla.' },
    { t: 'Trata-se de exigência puramente formal, sem repercussão prática sobre a segurança do trabalhador.', ok: false,
      why: 'Errada. O respirador impõe carga fisiológica real.' },
    { t: 'Verifica a tolerância à carga, sendo necessária apenas para respiradores de adução de ar.', ok: false,
      why: 'Errada. Aplica-se a qualquer tipo de respirador.' },
    { t: 'Verifica a tolerância e, uma vez apto, dispensa reavaliação enquanto o trabalhador ficar na função.', ok: false,
      why: 'Errada. Condições clínicas mudam e exigem reavaliação.' }
  ],
  comentario: 'O programa tem três exigências que caem sempre: seleção correta do equipamento pela exposição, ensaio de vedação individual e avaliação médica de tolerância. Esta última olha carga cardiorrespiratória, barreiras à vedação e tolerância psicológica — e se repete no tempo.',
  pegadinha: 'Reduzir a avaliação à espirometria é o atalho mais comum e não sustenta a decisão de aptidão.',
  refs: ['Torloni & Vieira — Manual de Proteção Respiratória', 'NR-7'] },

{ id: 'q-2.8-013', tema: '2.8', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o fator de proteção atribuído a um respirador, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Expressa a proteção esperada de uma classe de respirador usada dentro de um programa.', ok: true,
      why: 'Correta. Serve para verificar se o equipamento reduz a exposição a nível aceitável.' },
    { t: 'É característica fixa do modelo, independente do programa de proteção respiratória adotado na empresa.', ok: false,
      why: 'Errada. Pressupõe seleção, ensaio, capacitação e manutenção.' },
    { t: 'Expressa a proteção esperada, sendo tanto menor a proteção quanto maior for o valor do fator.', ok: false,
      why: 'Errada, é o inverso: fator maior significa maior proteção.' },
    { t: 'Expressa a proteção esperada e aplica-se apenas aos respiradores purificadores de ar utilizados.', ok: false,
      why: 'Errada. Há fatores atribuídos também aos de adução de ar.' },
    { t: 'Expressa a proteção esperada, tornando dispensável a avaliação ambiental da exposição do grupo.', ok: false,
      why: 'Errada. É a exposição medida que permite aplicar o fator.' }
  ],
  comentario: 'O fator de proteção é ferramenta de seleção e pressupõe programa funcionando. Fora do programa — sem ensaio de vedação, sem treinamento, sem manutenção — o número vira ficção. E ele nunca substitui a avaliação ambiental: é justamente dela que vem o dado de entrada.',
  pegadinha: 'Tratar o fator como atributo fixo do produto ignora que a proteção real depende do uso e do programa.',
  refs: ['Torloni & Vieira — Manual de Proteção Respiratória', 'NR-6'] }

);
