/* Seção 2 (parte A) — lote de volume. Questões AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-2.1-010', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria de tintas contrata o serviço de saúde ocupacional ainda na fase de projeto de uma nova linha de produção, antes da compra dos equipamentos. O higienista propõe revisar a planta, os fluxos de material e as fichas dos insumos previstos. A etapa da higiene ocupacional exercida nesse momento é:',
  alts: [
    { t: 'Antecipação, que atua sobre projetos e mudanças antes de o risco existir no ambiente.', ok: true,
      why: 'Correta. É a etapa de maior potencial preventivo e menor custo.' },
    { t: 'Reconhecimento, pois envolve identificar os agentes presentes nos postos de trabalho já instalados.', ok: false,
      why: 'Errada. O reconhecimento pressupõe o risco já existente.' },
    { t: 'Avaliação, porque o objetivo final é comparar as concentrações com os limites de exposição vigentes.', ok: false,
      why: 'Errada. A avaliação vem depois, sobre exposição existente.' },
    { t: 'Controle, uma vez que qualquer intervenção sobre o ambiente é por definição medida de controle.', ok: false,
      why: 'Errada. O controle atua sobre risco já instalado.' },
    { t: 'Vigilância epidemiológica ocupacional, por se tratar de análise coletiva das exposições do grupo.', ok: false,
      why: 'Errada. Não é etapa da higiene ocupacional.' }
  ],
  comentario: 'A sequência clássica da higiene ocupacional é antecipação, reconhecimento, avaliação e controle. A antecipação é a mais barata e a mais eficaz, porque permite escolher processo, insumo e leiaute antes que o risco esteja instalado — é a porta de entrada da eliminação e da substituição.',
  pegadinha: 'Quem decora apenas três etapas costuma trocar antecipação por reconhecimento. O marcador é temporal: se o processo ainda não existe, é antecipação.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-011', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Ao iniciar o trabalho em uma metalúrgica, o médico do trabalho percorre a planta acompanhado do engenheiro de segurança, conversa com trabalhadores, observa tarefas, consulta fichas de dados de segurança e levanta o inventário de produtos químicos. Sobre a etapa de reconhecimento em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Identifica agentes, fontes, vias e expostos, e orienta a decisão de quando e o que medir.', ok: true,
      why: 'Correta. É o que dá sentido à etapa de avaliação seguinte.' },
    { t: 'O reconhecimento exige medições quantitativas obrigatórias de todos os agentes identificados na planta.', ok: false,
      why: 'Errada. A quantificação é seletiva e posterior.' },
    { t: 'A percepção de risco relatada pelos trabalhadores não integra o reconhecimento, por ser subjetiva.', ok: false,
      why: 'Errada. É fonte primária sobre o trabalho real.' },
    { t: 'O reconhecimento se limita às atividades de rotina, excluindo manutenção, paradas e emergências.', ok: false,
      why: 'Errada. As situações não rotineiras concentram exposições intensas.' },
    { t: 'A ficha de segurança dispensa a observação do trabalho real, pois já descreve toda a exposição.', ok: false,
      why: 'Errada. Descreve o produto, não como ele é usado no posto.' }
  ],
  comentario: 'Reconhecimento é a etapa que transforma uma planta industrial em um problema tratável: quais agentes, geradas por quais fontes, alcançando quais trabalhadores, por quais vias. É onde se decide o que precisa ser medido — e o que já pode ir direto para controle.',
  pegadinha: 'A exclusão de tarefas não rotineiras é o erro clássico. Manutenção e limpeza costumam ser as atividades de maior exposição e as menos avaliadas.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-012', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma serralheria com dez soldadores, o consultor realizou uma única medição de fumos metálicos, de trinta minutos, no soldador mais experiente, em dia de baixa demanda, e concluiu que "a exposição do grupo está controlada". A principal falha metodológica dessa avaliação é:',
  alts: [
    { t: 'A amostra não representa a variabilidade: foi única, curta, atípica e extrapolada ao grupo.', ok: true,
      why: 'Correta. Uma medição assim não caracteriza a exposição do coletivo.' },
    { t: 'A amostragem deveria ter sido feita em ponto fixo do galpão, e não junto ao próprio trabalhador.', ok: false,
      why: 'Errada. A referência para comparar com limites é a pessoal.' },
    { t: 'O erro está em escolher trabalhador experiente, pois só recém-admitidos podem ser amostrados.', ok: false,
      why: 'Errada. Não há esse critério de seleção.' },
    { t: 'A avaliação seria válida se o resultado tivesse ficado acima do limite, sendo inválida só por dar abaixo.', ok: false,
      why: 'Errada. A validade depende do método, não do resultado.' },
    { t: 'O problema é só a duração de trinta minutos, corrigível por qualquer amostra isolada de jornada inteira.', ok: false,
      why: 'Errada. Uma amostra isolada ainda não descreve a variabilidade.' }
  ],
  comentario: 'Estratégia de amostragem é caracterizar uma distribuição, não obter um número. Exige amostras suficientes, cobrindo a jornada e os dias representativos, com registro das condições operacionais. Um valor isolado abaixo do limite não demonstra controle.',
  pegadinha: 'A alternativa que sugere amostragem de ponto fixo parece técnica, mas inverte o papel dos dois tipos de amostragem.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-013', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma gráfica utiliza um solvente de limpeza altamente volátil e neurotóxico. O higienista propõe trocá-lo por um produto de menor toxicidade e menor pressão de vapor, com desempenho equivalente. Sobre essa medida, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É substituição, medida alta na hierarquia, que exige avaliar o novo agente antes de adotá-lo.', ok: true,
      why: 'Correta. Trocar sem avaliar pode gerar risco equivalente ou maior.' },
    { t: 'É medida de engenharia, equivalente à instalação de um sistema de ventilação local exaustora.', ok: false,
      why: 'Errada. Substituição e engenharia são degraus distintos.' },
    { t: 'É substituição, que dispensa reavaliação porque o novo produto é, por definição, mais seguro.', ok: false,
      why: 'Errada. O substituto pode ter perfil pior ou desconhecido.' },
    { t: 'É medida administrativa, pois depende de decisão gerencial de compra do novo insumo químico.', ok: false,
      why: 'Errada. Altera o agente, não o comportamento; é substituição.' },
    { t: 'É substituição, justificável apenas quando as concentrações medidas ultrapassarem o limite legal.', ok: false,
      why: 'Errada. É exigível sempre que tecnicamente viável.' }
  ],
  comentario: 'Eliminação e substituição estão no topo da hierarquia porque removem ou reduzem o perigo, e não apenas a exposição. O contraponto obrigatório é a chamada substituição lamentável: trocar por um agente menos estudado que se revela igual ou pior.',
  pegadinha: 'A ideia de que "substituto é seguro por definição" é atraente e falsa. Toda substituição exige análise comparativa do novo agente.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-014', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma reunião de análise de riscos de uma cerâmica, discute-se a hierarquia de medidas de controle. Assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O rodízio entre postos de alta exposição é medida de engenharia, por alterar o ambiente.', ok: true,
      why: 'É a INCORRETA. Rodízio é controle administrativo; não altera o ambiente.' },
    { t: 'A eliminação do agente ou do processo é a mais eficaz, por suprimir o perigo em vez de gerenciá-lo.', ok: false,
      why: 'Correta, portanto não é a resposta. É o topo da hierarquia.' },
    { t: 'A ventilação local exaustora atua na fonte ou na trajetória, protegendo coletivamente os expostos.', ok: false,
      why: 'Correta, portanto não é a resposta. É proteção coletiva.' },
    { t: 'O equipamento individual ocupa a base porque depende de seleção, ajuste, treinamento e uso contínuo.', ok: false,
      why: 'Correta, portanto não é a resposta. É o último degrau da hierarquia.' },
    { t: 'Medidas de níveis diferentes podem ser combinadas, e a engenharia não impede exigir proteção individual.', ok: false,
      why: 'Correta, portanto não é a resposta. A combinação é prática comum.' }
  ],
  comentario: 'Classificar corretamente a medida é o que separa a hierarquia real da hierarquia decorada. Rodízio, redução de jornada na área, pausas e escalonamento de tarefas são controles administrativos, com a limitação ética de distribuir exposição em vez de reduzi-la.',
  pegadinha: 'O rodízio soa protetor e é frequentemente vendido como solução. Ele reduz a exposição individual, mas amplia o número de expostos e não reduz a geração do agente.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-015', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma mineradora não consegue, no curto prazo, reduzir a concentração de poeira respirável em um setor e propõe reduzir a permanência diária dos trabalhadores nesse local. O médico do trabalho é consultado sobre a legitimidade dessa medida. A avaliação mais adequada é:',
  alts: [
    { t: 'É controle administrativo aceitável como transição, com cronograma de engenharia e monitoramento.', ok: true,
      why: 'Correta. Não reduz a geração do agente nem a concentração no ambiente.' },
    { t: 'É medida definitiva e suficiente, pois a dose diária é o único determinante do risco para o exposto.', ok: false,
      why: 'Errada. Não reduz a geração e distribui a exposição por mais pessoas.' },
    { t: 'É inaceitável em qualquer circunstância, pois controles administrativos não integram a hierarquia.', ok: false,
      why: 'Errada. Integram a hierarquia, acima da proteção individual.' },
    { t: 'Equivale a medida de proteção coletiva, pois beneficia todo o grupo de trabalhadores ao mesmo tempo.', ok: false,
      why: 'Errada. Não altera o ambiente; apenas redistribui a exposição.' },
    { t: 'Dispensa monitoramento posterior, já que a exposição individual foi matematicamente reduzida.', ok: false,
      why: 'Errada. A verificação da eficácia permanece necessária.' }
  ],
  comentario: 'A questão central dos controles administrativos é ética antes de ser técnica: eles diluem a exposição entre mais pessoas sem reduzir a quantidade total de agente gerado. São aceitáveis como ponte, nunca como destino.',
  pegadinha: 'Negar valor a qualquer controle administrativo é tão errado quanto aceitá-lo como solução definitiva. A resposta exige a nuance do caráter transitório.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-016', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao planejar a avaliação de exposição em uma fábrica de calçados com 400 trabalhadores, a equipe decide organizar os trabalhadores em grupos homogêneos de exposição. Sobre esse conceito, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Reúne perfis semelhantes em agente, intensidade, frequência e duração da exposição.', ok: true,
      why: 'Correta. Permite que a amostra de alguns sirva de inferência para todos.' },
    { t: 'Deve ser definido pelo cargo formal registrado em carteira, critério objetivo e suficiente.', ok: false,
      why: 'Errada. O critério é a semelhança de exposição.' },
    { t: 'Uma vez definido, o grupo é permanente e não deve ser revisto, por comparabilidade histórica.', ok: false,
      why: 'Errada. Deve ser revisto quando os resultados mostram dispersão.' },
    { t: 'Grande dispersão nas medições dentro do grupo confirma o acerto do agrupamento realizado.', ok: false,
      why: 'Errada. Indica exatamente o contrário: o grupo foi mal formado.' },
    { t: 'Dispensa a caracterização das tarefas, pois o resultado analítico é o único dado que importa.', ok: false,
      why: 'Errada. Sem as tarefas o resultado não se interpreta.' }
  ],
  comentario: 'O grupo homogêneo de exposição é uma hipótese a ser testada, não um rótulo administrativo. A dispersão dos resultados dentro do grupo é o próprio teste: se for grande, o grupo estava mal formado.',
  pegadinha: 'Agrupar por cargo ou por setor é o atalho mais comum e a principal fonte de subestimação de exposição de subgrupos.',
  refs: ['AIHA — grupos similares de exposição', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-017', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um técnico realizará amostragem de vapores orgânicos em um pintor de estruturas metálicas. Sobre a técnica de amostragem em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O coletor deve ficar na zona respiratória e acompanhar os deslocamentos da jornada.', ok: true,
      why: 'Correta. É o que caracteriza a amostragem pessoal.' },
    { t: 'A amostragem em ponto fixo próximo ao posto substitui a pessoal para comparação com limites.', ok: false,
      why: 'Errada. A referência para comparar com limites é a pessoal.' },
    { t: 'A calibração da bomba pode ser feita apenas ao final da coleta, dispensando a verificação inicial.', ok: false,
      why: 'Errada. Verifica-se antes e depois da amostragem.' },
    { t: 'Não é necessário registrar as condições operacionais, pois o resultado analítico é autoexplicativo.', ok: false,
      why: 'Errada. Sem as condições, o resultado não se interpreta.' },
    { t: 'Amostras de branco de campo são dispensáveis quando o laboratório analítico é acreditado.', ok: false,
      why: 'Errada. Corrigem contaminação de manuseio e transporte.' }
  ],
  comentario: 'A validade de uma medição de higiene depende de três coisas fora do laboratório: posicionamento na zona respiratória, controle do volume amostrado por calibração antes e depois, e registro fiel das condições operacionais.',
  pegadinha: 'A confusão entre amostragem pessoal e de ponto fixo é recorrente. Ponto fixo avalia ambiente; amostragem pessoal avalia exposição.',
  refs: ['NHO 08 — Fundacentro', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-018', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma fábrica de móveis, a exaustão instalada sobre uma lixadeira não reduziu a concentração de poeira de madeira na zona respiratória do operador. Ao inspecionar o sistema, o higienista deve considerar que:',
  alts: [
    { t: 'O captor fica junto à fonte, de modo que o contaminante não passe pela zona respiratória.', ok: true,
      why: 'Correta. É o princípio básico do desempenho da exaustão localizada.' },
    { t: 'A eficiência independe da distância entre captor e fonte, desde que a vazão do ventilador seja alta.', ok: false,
      why: 'Errada. A velocidade de captura cai rapidamente com a distância.' },
    { t: 'A ausência de ar de reposição no galpão é irrelevante para o desempenho do sistema de exaustão.', ok: false,
      why: 'Errada. Sem reposição o sistema não consegue exaurir.' },
    { t: 'A ventilação geral diluidora é sempre preferível à local para poeiras geradas em ponto definido.', ok: false,
      why: 'Errada. Fonte pontual pede captação localizada.' },
    { t: 'Instalado e aprovado no comissionamento, o sistema dispensa verificações periódicas de desempenho.', ok: false,
      why: 'Errada. Perde desempenho por obstrução e desgaste.' }
  ],
  comentario: 'Ventilação local exaustora é o controle de engenharia mais usado e o mais mal instalado. Os três erros clássicos são captor longe da fonte, ausência de ar de reposição e trajetória de captura passando pela zona respiratória do trabalhador.',
  pegadinha: 'Aumentar a potência do ventilador é a resposta intuitiva e ineficaz. A geometria e a proximidade do captor pesam mais que a vazão bruta.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-019', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um laboratório de controle de qualidade manipula um solvente carcinogênico em pequenas quantidades. Discute-se entre instalar ventilação geral diluidora no salão ou enclausurar a operação em capela com exaustão. A orientação tecnicamente correta é:',
  alts: [
    { t: 'Enclausurar a operação: a diluição não serve a agente de alta toxicidade nem a fonte pontual.', ok: true,
      why: 'Correta. Para cancerígenos, a contenção precede qualquer diluição.' },
    { t: 'Adotar ventilação geral diluidora, por ser econômica e proteger todos os ocupantes do salão.', ok: false,
      why: 'Errada. Dilui o agente por todo o ambiente em vez de contê-lo.' },
    { t: 'Manter a operação em bancada aberta e fornecer respirador purificador de ar aos analistas do setor.', ok: false,
      why: 'Errada. Proteção individual é o último degrau, não o primeiro.' },
    { t: 'A escolha é indiferente, pois ambas são de engenharia e portanto equivalentes na hierarquia.', ok: false,
      why: 'Errada. Contenção e diluição têm eficácias muito distintas.' },
    { t: 'A ventilação geral é indicada porque garante concentração uniformemente segura em todo o ambiente.', ok: false,
      why: 'Errada. Não há uniformidade real, e espalha o agente.' }
  ],
  comentario: 'Ventilação geral diluidora tem indicação restrita: contaminantes de baixa toxicidade, gerados de forma difusa e em taxa baixa e uniforme, em ambiente sem trabalhadores próximos à fonte. Fora disso, a solução é enclausurar e captar na fonte.',
  pegadinha: 'A alternativa da diluição usa o argumento de "proteger todo o salão", quando na verdade ela expõe todo o salão.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] }

,

{ id: 'q-2.1-020', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma marcenaria, o empregador afirma que cumpriu sua obrigação legal ao entregar máscaras e protetores auriculares aos trabalhadores, colhendo assinatura no recibo. Sobre a relação entre proteção coletiva e proteção individual, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É subsidiária: só cabe se a coletiva for inviável, insuficiente ou estiver sendo implantada.', ok: true,
      why: 'Correta. Sua entrega exige treinamento, fiscalização, higienização e substituição.' },
    { t: 'A entrega com registro de recebimento encerra a responsabilidade do empregador quanto àquele risco.', ok: false,
      why: 'Errada. Persistem treinamento, fiscalização e manutenção.' },
    { t: 'A proteção individual é preferível à coletiva, por ser ajustada às características de cada trabalhador.', ok: false,
      why: 'Errada. A coletiva protege independentemente do uso correto.' },
    { t: 'Individual e coletiva são intercambiáveis, cabendo ao empregador escolher por critério de custo.', ok: false,
      why: 'Errada. A hierarquia de controle é exigível.' },
    { t: 'O uso de proteção individual dispensa a avaliação ambiental, pois a exposição passa a ser nula.', ok: false,
      why: 'Errada. A avaliação ambiental permanece necessária.' }
  ],
  comentario: 'Proteção coletiva age no ambiente e independe da adesão individual; proteção individual age na interface trabalhador-ambiente e depende de uma cadeia frágil de condições. A entrega documentada é o começo da obrigação, não o fim.',
  pegadinha: 'O argumento do recibo assinado é o mais usado na prática e o mais frágil tecnicamente: prova entrega, não proteção.',
  refs: ['EPC versus EPI', 'NR-6', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-021', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao estruturar o programa de higiene ocupacional de uma fábrica de embalagens, o consultor organiza as ações segundo o modelo fonte-trajetória-receptor. Assinale a alternativa que classifica CORRETAMENTE as medidas propostas:',
  alts: [
    { t: 'Substituir a tinta age na fonte; enclausurar, na trajetória; treinar e proteger, no receptor.', ok: true,
      why: 'Correta. É a distribuição correta das medidas nos três pontos do modelo.' },
    { t: 'A ventilação local exaustora é medida sobre o receptor, pois seu objetivo é proteger o trabalhador.', ok: false,
      why: 'Errada. Atua na fonte ou na trajetória do contaminante.' },
    { t: 'A troca de insumo por outro menos volátil é medida sobre a trajetória, por alterar a dispersão.', ok: false,
      why: 'Errada. Substituição de insumo é medida sobre a fonte.' },
    { t: 'O rodízio de trabalhadores é medida sobre a fonte, pois reduz a quantidade total de agente gerado.', ok: false,
      why: 'Errada. Atua no receptor e não altera a geração.' },
    { t: 'A ordem de prioridade do modelo é receptor, trajetória e fonte, do mais simples ao mais complexo.', ok: false,
      why: 'Errada. A prioridade é fonte, trajetória e receptor.' }
  ],
  comentario: 'O modelo fonte-trajetória-receptor é uma leitura complementar à hierarquia de controles e ajuda a classificar medidas concretas. Quanto mais perto da fonte, menor o número de pessoas dependentes daquele controle e menor a chance de falha silenciosa.',
  pegadinha: 'A confusão vem de julgar pela finalidade em vez do mecanismo: toda medida visa proteger o trabalhador, mas nem toda medida age sobre ele.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'Hierarquia de controles de risco'] },

{ id: 'q-2.1-022', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pedreira gera grande quantidade de poeira no britador e no transporte por correias. Entre as propostas de controle, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'A umidificação do material aumenta a fração respirável e deve ser evitada na britagem.', ok: true,
      why: 'É a INCORRETA. A supressão úmida reduz a suspensão de poeira.' },
    { t: 'O enclausuramento dos pontos de transferência com captação localizada reduz a emissão difusa.', ok: false,
      why: 'Correta, portanto não é a resposta. É a medida indicada nesses pontos.' },
    { t: 'Cabines pressurizadas com ar filtrado protegem o operador ao impedir a entrada de ar contaminado.', ok: false,
      why: 'Correta, portanto não é a resposta. É proteção coletiva reconhecida.' },
    { t: 'A varrição a seco do pátio deve ser substituída por métodos úmidos ou aspiração com filtragem.', ok: false,
      why: 'Correta, portanto não é a resposta. A varrição a seco ressuspende poeira.' },
    { t: 'O uso de ar comprimido para limpeza de roupas e superfícies deve ser proscrito por ressuspender poeira.', ok: false,
      why: 'Correta, portanto não é a resposta. É prática vedada.' }
  ],
  comentario: 'O controle de poeira mineral se apoia em quatro pilares: supressão por umidade, enclausuramento das transferências, captação localizada e eliminação de práticas que ressuspendem o material já depositado, como varrição a seco e limpeza com ar comprimido.',
  pegadinha: 'A afirmação falsa inverte um efeito bem estabelecido: a água aglomera partículas finas em vez de liberá-las.',
  refs: ['Ventilação industrial e enclausuramento', 'Controle de poeiras minerais'] },

{ id: 'q-2.1-023', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma pequena indústria não dispõe de recursos para amostragem quantitativa de todos os agentes químicos identificados e pede orientação sobre como priorizar. A conduta tecnicamente adequada é:',
  alts: [
    { t: 'Avaliar qualitativamente por potencial de dano e de exposição, medindo onde há maior incerteza.', ok: true,
      why: 'Correta. A quantificação se reserva às situações de maior risco estimado.' },
    { t: 'Medir todos os agentes com o menor número de amostras por agente, cobrindo todo o inventário.', ok: false,
      why: 'Errada. Amostra insuficiente por agente não caracteriza nada.' },
    { t: 'Adiar qualquer ação de controle até haver orçamento para medir quantitativamente todos os agentes.', ok: false,
      why: 'Errada. Riscos evidentes exigem ação imediata.' },
    { t: 'Priorizar exclusivamente pelo número de trabalhadores expostos, seja qual for a toxicidade do agente.', ok: false,
      why: 'Errada. Toxicidade e gravidade também compõem a prioridade.' },
    { t: 'Considerar que a ausência de medição quantitativa equivale a ausência de risco caracterizado.', ok: false,
      why: 'Errada. A avaliação qualitativa já caracteriza risco.' }
  ],
  comentario: 'A avaliação qualitativa não é a versão pobre da quantitativa: é a etapa que decide onde a quantitativa vale a pena. Ela cruza perigo intrínseco do agente com potencial de exposição, e permite acionar controle imediato em situações evidentes.',
  pegadinha: 'Tratar falta de medição como ausência de risco é o argumento defensivo mais comum em laudos e o mais indefensável tecnicamente.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'Avaliação qualitativa de risco químico'] },

{ id: 'q-2.1-024', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Dois anos após instalar sistemas de exaustão em uma galvanoplastia, a empresa relata que os trabalhadores voltaram a queixar-se de irritação nasal. Sobre a etapa de controle em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Implantar não encerra o ciclo: exige manutenção, verificação de desempenho e reavaliação.', ok: true,
      why: 'Correta. Controle instalado não é controle permanentemente eficaz.' },
    { t: 'Queixa de sintomas irritativos não deve ser considerada, pois só a medição caracteriza falha.', ok: false,
      why: 'Errada. A queixa costuma anteceder a medição programada.' },
    { t: 'Dimensionado corretamente no projeto, o desempenho do sistema é constante ao longo da vida útil.', ok: false,
      why: 'Errada. Obstrução e desgaste reduzem o desempenho.' },
    { t: 'A reavaliação só deve ocorrer havendo mudança formal de processo registrada em documento próprio.', ok: false,
      why: 'Errada. A verificação periódica independe de mudança formal.' },
    { t: 'Diante de queixa persistente, a conduta prioritária é substituir a exaustão por respiradores.', ok: false,
      why: 'Errada. Substituiria proteção coletiva por individual, invertendo a hierarquia.' }
  ],
  comentario: 'O ciclo da higiene ocupacional é contínuo: controlar, verificar, reavaliar e, se necessário, recontrolar. Sintomas sentinela em trabalhadores com controles instalados devem ser lidos como suspeita de falha do controle, não como intolerância individual.',
  pegadinha: 'Descer para o respirador diante da falha da exaustão é a saída fácil e o erro conceitual: primeiro se restaura o degrau superior da hierarquia.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-025', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma indústria química, o médico do trabalho recebe do higienista o relatório de avaliação ambiental e precisa integrá-lo à vigilância da saúde dos trabalhadores. Sobre essa articulação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A exposição define quem vigiar, quais exames e com que periodicidade, e os achados realimentam.', ok: true,
      why: 'Correta. É a articulação que fecha o ciclo entre ambiente e saúde.' },
    { t: 'A avaliação ambiental e o acompanhamento médico são independentes, com documentos e conclusões próprias.', ok: false,
      why: 'Errada. O programa médico deriva dos riscos avaliados.' },
    { t: 'O acompanhamento médico substitui a avaliação ambiental quando os exames se mostram normais.', ok: false,
      why: 'Errada. Exame normal não indica exposição controlada.' },
    { t: 'Alteração precoce em um trabalhador indica afastamento individual, sem reavaliar o grupo exposto.', ok: false,
      why: 'Errada. Sinaliza possível falha de controle que alcança os demais.' },
    { t: 'A escolha dos exames complementares deve seguir o cargo formal, sem considerar o perfil de exposição.', ok: false,
      why: 'Errada. É a exposição que define os exames pertinentes.' }
  ],
  comentario: 'Higiene ocupacional e vigilância da saúde são as duas metades do mesmo programa. A avaliação ambiental é prevenção primária; o acompanhamento médico é detecção precoce. Quando o segundo encontra alteração, o primeiro falhou e precisa ser revisto.',
  pegadinha: 'Tratar exame normal como prova de ambiente seguro confunde ausência de efeito detectável com ausência de exposição.',
  refs: ['NR-7 — PCMSO', 'NR-1 — Gerenciamento de Riscos Ocupacionais', 'Higiene ocupacional e vigilância da saúde'] },

{ id: 'q-2.1-026', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadores de uma fábrica de compensados estão expostos simultaneamente a formaldeído, poeira de madeira e ruído. O laudo conclui que "nenhum agente isoladamente ultrapassa seu limite, portanto não há risco". A crítica CORRETA a essa conclusão é:',
  alts: [
    { t: 'Exposições múltiplas exigem analisar interações: mesmo alvo pode significar efeito aditivo.', ok: true,
      why: 'Correta. Avaliar cada agente isoladamente subestima o risco combinado.' },
    { t: 'A conclusão está correta, pois os limites já incorporam a presença de outros agentes no ambiente.', ok: false,
      why: 'Errada. Os limites são estabelecidos para o agente isolado.' },
    { t: 'Só é necessário considerar interação quando os agentes pertencem à mesma classe química de origem.', ok: false,
      why: 'Errada. O critério é o órgão-alvo comum, não a classe.' },
    { t: 'A presença de ruído é irrelevante, pois agentes físicos e químicos não interagem em nenhuma hipótese.', ok: false,
      why: 'Errada. Ruído e solventes ototóxicos interagem de forma documentada.' },
    { t: 'A interação só é considerada quando ambos os agentes ultrapassam metade de seus respectivos limites.', ok: false,
      why: 'Errada. A soma das frações se aplica em qualquer patamar.' }
  ],
  comentario: 'Ambientes reais expõem a misturas. O raciocínio de aditividade se aplica quando os agentes compartilham órgão-alvo. Ruído associado a solventes ototóxicos é o exemplo mais cobrado de interação entre agente físico e químico.',
  pegadinha: 'A frase "cada agente abaixo do seu limite" é tecnicamente verdadeira e conclusivamente insuficiente. É o tipo de conclusão que aparece em laudo e não sobrevive à análise.',
  refs: ['ACGIH — misturas e exposições combinadas', 'Higiene ocupacional — avaliação de exposições'] },

{ id: 'q-2.1-027', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um frigorífico planeja avaliar a exposição de um grupo de trabalhadores a um agente químico e discute se deve amostrar em condição típica ou na condição de maior exposição prevista. Sobre estratégias de amostragem, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O pior caso serve de triagem: resultado baixo ali descarta risco, mas não descreve a distribuição.', ok: true,
      why: 'Correta. Tem alto poder de descarte e baixo poder descritivo.' },
    { t: 'A amostragem de pior caso é proibida por superestimar a exposição e gerar exigências desnecessárias.', ok: false,
      why: 'Errada. É estratégia legítima de triagem.' },
    { t: 'A amostragem aleatória no grupo é inadequada, pois pode selecionar trabalhadores de baixa exposição.', ok: false,
      why: 'Errada. É justamente ela que descreve a distribuição.' },
    { t: 'Um resultado abaixo do limite em condição típica autoriza concluir que ninguém do grupo o excede.', ok: false,
      why: 'Errada. Uma medição não descreve a variabilidade do grupo.' },
    { t: 'A escolha da estratégia independe do objetivo da avaliação, sendo definida pelo custo analítico.', ok: false,
      why: 'Errada. O objetivo é que define a estratégia adequada.' }
  ],
  comentario: 'Estratégia de amostragem começa pela pergunta. Se a pergunta é "existe problema aqui?", o pior caso resolve rápido. Se é "qual a exposição habitual deste grupo?", só a amostragem representativa com número suficiente de medições responde.',
  pegadinha: 'A ideia de que amostragem aleatória é ruim por "sortear quem se expõe pouco" confunde representatividade com conservadorismo.',
  refs: ['AIHA — estratégia de avaliação e gerenciamento de exposições', 'NHO 08 — Fundacentro'] },

{ id: 'q-2.1-028', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa vai implantar um novo processo de decapagem ácida e solicita ao serviço de saúde ocupacional uma análise prévia. Sobre a atuação antecipatória da higiene ocupacional em mudanças de processo, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Deve considerar insumos, subprodutos, resíduos, leiaute, manutenção e cenários anormais.', ok: true,
      why: 'Correta. Permite incorporar controles ao projeto antes da instalação.' },
    { t: 'Deve restringir-se aos insumos declarados na ficha de compra, pois subprodutos não são previsíveis.', ok: false,
      why: 'Errada. Subprodutos de processo são previsíveis e frequentemente mais tóxicos.' },
    { t: 'A antecipação se limita a estimar quantos trabalhadores serão alocados no novo setor produtivo.', ok: false,
      why: 'Errada. Alcança processo, leiaute e cenários de operação.' },
    { t: 'Como ainda não há trabalhadores expostos, não existe base técnica para propor controles nessa fase.', ok: false,
      why: 'Errada. É justamente a fase de maior eficácia preventiva.' },
    { t: 'A análise prévia substitui integralmente a avaliação ambiental após a partida do novo processo.', ok: false,
      why: 'Errada. A avaliação após a partida verifica o que foi projetado.' }
  ],
  comentario: 'Gestão de mudança é onde a higiene ocupacional entrega o melhor retorno. Novos insumos, novos equipamentos, alterações de leiaute e mudanças de turno devem disparar análise prévia de risco, com atenção especial a manutenção e a cenários anormais.',
  pegadinha: 'O argumento de que "sem exposição não há o que avaliar" confunde exposição atual com risco previsível e destrói o conceito de antecipação.',
  refs: ['Higiene ocupacional — antecipação', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-029', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao apresentar os resultados da avaliação ambiental aos trabalhadores de uma fundição, o médico do trabalho é questionado sobre o significado dos números. Sobre a comunicação de risco em higiene ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Têm direito de conhecer agentes, resultados e medidas, em linguagem acessível.', ok: true,
      why: 'Correta. Essa informação é parte do próprio programa de prevenção.' },
    { t: 'Resultados ambientais são documentos internos e não devem ser divulgados, para evitar alarme.', ok: false,
      why: 'Errada. O acesso à informação sobre a própria exposição é direito.' },
    { t: 'A comunicação deve limitar-se a informar se ficou acima ou abaixo do limite, sem discutir incertezas.', ok: false,
      why: 'Errada. A incerteza deve ser comunicada como tal.' },
    { t: 'A participação dos trabalhadores é dispensável quando há laudo de profissional habilitado.', ok: false,
      why: 'Errada. Traz informação sobre o trabalho real que o laudo não capta.' },
    { t: 'Informar riscos aumenta a responsabilidade do trabalhador e transfere a ele a obrigação de se proteger.', ok: false,
      why: 'Errada. Informar não transfere obrigação; ela permanece do empregador.' }
  ],
  comentario: 'A comunicação de risco fecha o ciclo da higiene ocupacional. Ela não é gentileza nem gestão de imagem: é condição para que os expostos participem do reconhecimento, usem corretamente as medidas e percebam falhas antes que virem doença.',
  pegadinha: 'A alternativa que trata informação como transferência de responsabilidade inverte um princípio central: informar é dever adicional, não substituto do controle.',
  refs: ['Direito à informação sobre riscos', 'NR-1 — Gerenciamento de Riscos Ocupacionais', 'Convenção 155 da OIT'] }

,

{ id: 'q-2.1-030', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria farmacêutica precisa manipular um princípio ativo de alta potência em sala dedicada. O projetista pergunta se a sala deve operar com pressão positiva ou negativa em relação aos corredores. A orientação CORRETA, do ponto de vista da proteção do trabalhador, é:',
  alts: [
    { t: 'Pressão negativa em relação às áreas vizinhas, para que o contaminante não escape da sala.', ok: true,
      why: 'Correta. O fluxo de ar deve entrar na sala, e não sair dela.' },
    { t: 'Pressão positiva em relação às áreas vizinhas, para impedir a entrada de contaminantes externos.', ok: false,
      why: 'Errada. Empurraria o contaminante para os ambientes vizinhos.' },
    { t: 'Pressão equalizada, pois qualquer diferencial compromete o conforto térmico dos operadores da sala.', ok: false,
      why: 'Errada. Sem diferencial não há contenção do contaminante.' },
    { t: 'O sentido do diferencial é indiferente, desde que o ar seja filtrado antes de ser lançado ao exterior.', ok: false,
      why: 'Errada. O sentido é o que impede a fuga para dentro do prédio.' },
    { t: 'Pressão positiva, pois é o padrão obrigatório para toda sala que possua sistema de exaustão instalado.', ok: false,
      why: 'Errada. Sala de contaminante opera em pressão negativa.' }
  ],
  comentario: 'A regra é simples: proteja-se o que estiver dentro com pressão positiva; contenha-se o que estiver dentro com pressão negativa. Cabines de operação em ambientes empoeirados são positivas; salas de manipulação de agentes perigosos e de isolamento respiratório são negativas.',
  pegadinha: 'Áreas limpas farmacêuticas costumam ser positivas por exigência de qualidade do produto, o que induz o candidato a generalizar. Quando o alvo é o trabalhador e o entorno, a lógica se inverte.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-031', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma refinaria, a área de amostragem de produto foi delimitada com faixas, sinalizada com placas de advertência e sujeita a permissão de trabalho. Sobre essas medidas, assinale a alternativa CORRETA:',
  alts: [
    { t: 'São controles administrativos e de sinalização: reduzem a probabilidade, não a concentração.', ok: true,
      why: 'Correta. Não alteram a geração do agente na área delimitada.' },
    { t: 'São medidas de proteção coletiva de engenharia, equivalentes ao enclausuramento da operação.', ok: false,
      why: 'Errada. Não alteram fisicamente a fonte nem o ambiente.' },
    { t: 'Dispensam a avaliação da exposição dos trabalhadores autorizados a entrar na área delimitada.', ok: false,
      why: 'Errada. Quem entra continua exposto e precisa ser avaliado.' },
    { t: 'Substituem a necessidade de proteção respiratória para quem executa a amostragem do produto.', ok: false,
      why: 'Errada. A proteção permanece necessária durante a tarefa.' },
    { t: 'São suficientes como medida definitiva quando não há orçamento para controles de engenharia.', ok: false,
      why: 'Errada. São transitórias, com cronograma de engenharia associado.' }
  ],
  comentario: 'Sinalização, delimitação e permissão de trabalho são valiosas para limitar o número de expostos e organizar tarefas de risco, mas pertencem ao degrau administrativo. Quem executa a tarefa dentro da área permanece plenamente exposto.',
  pegadinha: 'A confusão entre "proteção coletiva" e "medida que abrange várias pessoas" faz o candidato promover sinalização a controle de engenharia.',
  refs: ['Hierarquia de controles de risco', 'NR-1 — Gerenciamento de Riscos Ocupacionais'] },

{ id: 'q-2.1-032', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma transportadora elabora seu programa de gerenciamento de riscos ocupacionais e pergunta qual a contribuição específica da higiene ocupacional nesse documento. A resposta CORRETA é:',
  alts: [
    { t: 'Fornece reconhecimento, caracterização e avaliação, e a base para hierarquizar as medidas.', ok: true,
      why: 'Correta. Subsidia o plano de ação e seu cronograma.' },
    { t: 'A contribuição se resume a anexar laudos ao final do documento, sem influência sobre o plano de ação.', ok: false,
      why: 'Errada. É a base técnica da priorização das medidas.' },
    { t: 'A higiene ocupacional atua apenas após a ocorrência de doença ocupacional reconhecida no grupo.', ok: false,
      why: 'Errada. Sua atuação é antecipatória e preventiva.' },
    { t: 'A avaliação de exposição só é necessária para agentes com limite de tolerância previsto em norma.', ok: false,
      why: 'Errada. Agentes sem limite exigem avaliação qualitativa e controle.' },
    { t: 'A hierarquização deve considerar só a gravidade, sem probabilidade nem número de expostos.', ok: false,
      why: 'Errada. Os três elementos compõem a priorização.' }
  ],
  comentario: 'No ciclo de gerenciamento de riscos, a higiene ocupacional responde por identificar, avaliar e propor controle das exposições, e por verificar se o controle funcionou. Sem esse conteúdo, o inventário vira lista genérica e o plano de ação vira intenção.',
  pegadinha: 'A ideia de que só agentes com limite normatizado precisam ser avaliados deixa fora agentes emergentes e boa parte dos carcinogênicos.',
  refs: ['NR-1 — Gerenciamento de Riscos Ocupacionais', 'Higiene ocupacional — avaliação e controle'] },

{ id: 'q-2.1-033', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma indústria de plásticos, a média ponderada da exposição a um solvente irritante ficou confortavelmente abaixo do limite, mas o registro contínuo mostrou picos elevados durante três operações de carga de reator, com duração de poucos minutos cada. A interpretação CORRETA é:',
  alts: [
    { t: 'A média pode mascarar picos curtos relevantes em agentes irritantes ou de efeito agudo.', ok: true,
      why: 'Correta. Esses agentes exigem análise dos períodos de exposição intensa.' },
    { t: 'Como a média está abaixo do limite, os picos são irrelevantes para qualquer agente químico avaliado.', ok: false,
      why: 'Errada. Para efeito agudo, o pico é o que importa.' },
    { t: 'Os picos devem ser retirados da série por serem valores atípicos que distorcem o cálculo da média.', ok: false,
      why: 'Errada. Descartá-los apaga justamente o dado crítico.' },
    { t: 'A existência de picos indica erro do instrumento, pois a exposição real varia pouco na jornada.', ok: false,
      why: 'Errada. Exposições ocupacionais são naturalmente variáveis.' },
    { t: 'Basta reduzir o tempo total de jornada do trabalhador para eliminar o problema dos picos medidos.', ok: false,
      why: 'Errada. Reduz a média sem alterar a intensidade dos picos.' }
  ],
  comentario: 'Média ponderada e valores de curta duração respondem a perguntas diferentes: dose acumulada e pico agudo. Operações de carga, descarga, amostragem e limpeza são justamente onde os picos se concentram, e são as tarefas mais frequentemente esquecidas na amostragem.',
  pegadinha: 'Descartar picos como valores atípicos é o erro estatístico e ético mais grave possível nessa análise: eles são o dado, não o ruído.',
  refs: ['ACGIH — TLV-TWA e TLV-STEL', 'AIHA — estratégia de avaliação de exposições'] },

{ id: 'q-2.1-034', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Durante o reconhecimento de risco químico em uma tinturaria, o médico do trabalho consulta os rótulos e as fichas de dados de segurança dos produtos. Sobre o uso dessas fontes, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Informam perigos, pictogramas e socorros, sem substituir a caracterização da exposição no posto.', ok: true,
      why: 'Correta. Descrevem o produto, não como ele é usado naquele trabalho.' },
    { t: 'A ficha de segurança informa a concentração ambiental esperada em cada posto de trabalho da planta.', ok: false,
      why: 'Errada. Não traz dado de exposição do posto.' },
    { t: 'A ausência de pictograma de perigo no rótulo garante que o produto não oferece risco à saúde.', ok: false,
      why: 'Errada. Pode indicar apenas classificação incompleta ou rótulo irregular.' },
    { t: 'Produtos formulados dispensam ficha quando cada componente isolado já possui a sua própria ficha.', ok: false,
      why: 'Errada. A mistura exige ficha própria.' },
    { t: 'A ficha de segurança dispensa a identificação dos subprodutos gerados durante o processo produtivo.', ok: false,
      why: 'Errada. Subprodutos não constam da ficha do insumo.' }
  ],
  comentario: 'Ficha e rótulo são o ponto de partida do reconhecimento de risco químico, nunca o ponto de chegada. Dois erros derrubam quem confia demais neles: ignorar subprodutos do processo e confundir perigo intrínseco com exposição real.',
  pegadinha: 'Achar que a ficha de dados de segurança informa a concentração no ambiente confunde propriedade do produto com condição da instalação.',
  refs: ['Sistema Globalmente Harmonizado — GHS', 'NR-26', 'Higiene ocupacional — reconhecimento'] },

{ id: 'q-2.1-035', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um residente de medicina do trabalho apresenta um seminário sobre higiene ocupacional em uma indústria de fertilizantes. Assinale a alternativa INCORRETA entre as afirmações apresentadas:',
  alts: [
    { t: 'A avaliação é sempre obrigatória antes de qualquer controle, mesmo com risco evidente.', ok: true,
      why: 'É a INCORRETA. Risco evidente autoriza controle imediato, sem esperar medição.' },
    { t: 'A antecipação atua sobre projetos e mudanças, evitando a introdução de novos riscos no ambiente.', ok: false,
      why: 'Correta, portanto não é a resposta. É a definição da etapa.' },
    { t: 'O reconhecimento identifica agentes, fontes, vias de exposição e trabalhadores potencialmente expostos.', ok: false,
      why: 'Correta, portanto não é a resposta. É a definição da etapa.' },
    { t: 'A avaliação compara a exposição com critérios de referência, considerando a variabilidade das medições.', ok: false,
      why: 'Correta, portanto não é a resposta. É a definição da etapa.' },
    { t: 'O controle deve seguir a hierarquia de medidas e ser verificado quanto à eficácia após a implantação.', ok: false,
      why: 'Correta, portanto não é a resposta. É a definição da etapa.' }
  ],
  comentario: 'As quatro etapas descrevem um método, não uma sequência burocrática obrigatória. Diante de risco evidente e grave reconhecido qualitativamente, o controle é imediato e a medição serve para dimensionar e verificar, não para autorizar a ação.',
  pegadinha: 'A afirmação falsa é sedutora porque parece defender o rigor metodológico, quando na prática transforma o método em desculpa para adiar proteção.',
  refs: ['Higiene ocupacional — antecipação, reconhecimento, avaliação e controle', 'AIHA — estratégia de avaliação e gerenciamento de exposições'] },

{ id: 'q-2.1-036', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma oficina de solda, um exaustor de teto foi instalado a vários metros acima dos postos, com a justificativa de que "os fumos sobem naturalmente". Trabalhadores continuam com sintomas respiratórios. A análise CORRETA da situação é:',
  alts: [
    { t: 'A captação distante é ineficaz: os fumos sobem pela zona respiratória antes de chegar ao teto.', ok: true,
      why: 'Correta. A solução é captação localizada junto ao ponto de solda.' },
    { t: 'A instalação está correta, pois a convecção térmica impede que o contaminante fique na zona respiratória.', ok: false,
      why: 'Errada. É justamente a convecção que leva o fumo ao rosto do soldador.' },
    { t: 'Correntes de ar cruzadas no galpão melhoram a captação, ao empurrar os fumos para o exaustor de teto.', ok: false,
      why: 'Errada. Correntes cruzadas prejudicam a captação.' },
    { t: 'O problema se resolve aumentando o pé-direito do galpão, o que diluiria os fumos antes do trabalhador.', ok: false,
      why: 'Errada. A exposição ocorre antes de qualquer diluição.' },
    { t: 'A única solução tecnicamente possível é fornecer respirador de adução de ar a todos os soldadores.', ok: false,
      why: 'Errada. A captação localizada resolve com proteção coletiva.' }
  ],
  comentario: 'Solda é o exemplo didático de por que a captação deve ser localizada: a pluma ascendente nasce a poucos centímetros do rosto do trabalhador. Exaustores de teto ventilam o galpão e não protegem o soldador.',
  pegadinha: 'O argumento de que "os fumos sobem" é verdadeiro e leva à conclusão errada: eles sobem passando pela zona respiratória.',
  refs: ['Ventilação industrial e enclausuramento', 'ACGIH — Industrial Ventilation'] },

{ id: 'q-2.1-037', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao discutir a amostragem de material particulado em uma cerâmica, o higienista explica ao médico do trabalho as frações de aerodispersoides adotadas em avaliação ocupacional. A explicação CORRETA é:',
  alts: [
    { t: 'Inalável entra por nariz e boca; torácica passa da laringe; respirável chega aos alvéolos.', ok: true,
      why: 'Correta. A escolha da fração depende do local de ação do agente.' },
    { t: 'As três frações são intercambiáveis, bastando amostrar poeira total para qualquer particulado.', ok: false,
      why: 'Errada. Cada fração se deposita em sítio distinto.' },
    { t: 'A fração respirável é a maior das três em massa, por incluir todas as partículas suspensas no ar.', ok: false,
      why: 'Errada. É a menor em massa, por conter só as mais finas.' },
    { t: 'Para agentes que atuam nas vias superiores, a respirável é a mais adequada por ser conservadora.', ok: false,
      why: 'Errada. Para vias superiores usa-se a fração inalável.' },
    { t: 'A definição das frações depende da composição química da partícula, e não do tamanho aerodinâmico.', ok: false,
      why: 'Errada. Depende do diâmetro aerodinâmico.' }
  ],
  comentario: 'A pergunta prática é sempre a mesma: onde o agente causa dano? Sílica cristalina causa fibrose no parênquima e é avaliada na fração respirável; poeira de madeira atua também nas vias superiores e exige a fração inalável. Escolher a fração errada invalida a avaliação.',
  pegadinha: 'A ideia de que a fração respirável é sempre a mais conservadora confunde restritividade do tamanho com severidade do critério.',
  refs: ['NHO 08 — Fundacentro', 'ACGIH — frações de aerodispersoides'] },

{ id: 'q-2.1-038', tema: '2.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em uma empresa de médio porte, discute-se a divisão de tarefas entre o médico do trabalho, o engenheiro de segurança e o higienista ocupacional na gestão das exposições. Sobre essa atuação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É interdisciplinar: a exposição subsidia o acompanhamento e os achados realimentam os controles.', ok: true,
      why: 'Correta. A articulação entre as duas áreas é o que fecha o ciclo.' },
    { t: 'Cabe ao médico do trabalho executar pessoalmente as medições, sob pena de não poder interpretá-las.', ok: false,
      why: 'Errada. A medição é de higiene ocupacional; a interpretação é conjunta.' },
    { t: 'O médico do trabalho deve limitar-se aos exames, sem opinar sobre a suficiência das medidas de controle.', ok: false,
      why: 'Errada. Os achados de saúde avaliam a efetividade dos controles.' },
    { t: 'Havendo laudo assinado por profissional habilitado, o médico não pode questionar suas conclusões.', ok: false,
      why: 'Errada. A análise crítica do conteúdo é sempre cabível.' },
    { t: 'A responsabilidade pela eliminação do risco recai sobre o profissional de segurança, e não sobre a empresa.', ok: false,
      why: 'Errada. A obrigação é do empregador.' }
  ],
  comentario: 'O médico do trabalho não precisa operar uma bomba de amostragem, mas precisa saber ler um relatório de exposição, identificar amostragem mal feita e reconhecer quando o achado clínico contradiz a conclusão do laudo.',
  pegadinha: 'A alternativa que proíbe o médico de questionar laudo assinado confunde habilitação técnica com infalibilidade e paralisa a vigilância.',
  refs: ['NR-4', 'NR-7 — PCMSO', 'Atuação interdisciplinar em saúde do trabalhador'] }

/* FIM-LOTE */
);
