/* Seções 3 e 6 — lote de volume. Questões AUTORAIS. */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-3.1-010', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma central de despacho de emergência, os operadores acompanham simultaneamente três telas, atendem rádio e telefone e precisam decidir prioridades em poucos segundos. O mobiliário foi recentemente substituído por estações reguláveis, mas as queixas de erro e de exaustão persistem. Considerando os domínios da ergonomia, a leitura tecnicamente mais adequada da situação é:',
  alts: [
    { t: 'Domínio cognitivo: carga mental, atenção dividida e projeto da interface de informação.', ok: true,
      why: 'Correta. O problema está no desenho da informação, não no mobiliário.' },
    { t: 'Domínio físico, resolvido com nova regulagem de altura das superfícies e das cadeiras do setor.', ok: false,
      why: 'Errada. A queixa é de erro e sobrecarga atencional, não postural.' },
    { t: 'Domínio organizacional puro: a sobrecarga de atenção decorre só do número de trabalhadores na escala.', ok: false,
      why: 'Errada. O desenho da interface é determinante independente do efetivo.' },
    { t: 'Nenhum: a ergonomia não se aplica a atividades sem esforço físico relevante nem manuseio de cargas.', ok: false,
      why: 'Errada. A ergonomia cognitiva é domínio consolidado da disciplina.' },
    { t: 'Domínio individual: selecionar operadores com maior capacidade atencional por testes na admissão.', ok: false,
      why: 'Errada. Seleciona pessoas sem corrigir o sistema que produz o erro.' }
  ],
  comentario: 'A ergonomia costuma ser dividida em três domínios que se articulam: físico (postura, força, manuseio), cognitivo (carga mental, interface, tomada de decisão, erro humano) e organizacional (processos, comunicação, jornada, cultura). Reconhecer qual domínio predomina define a intervenção; postos de monitoramento e despacho são o exemplo clássico de predomínio cognitivo.',
  pegadinha: 'Trocar mobiliário é a resposta reflexa e por isso o distrator mais confortável. A pista do enunciado é que a intervenção física já foi feita e o problema persistiu.',
  refs: ['IEA — domínios da ergonomia', 'NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-011', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'O setor de engenharia de uma fábrica está projetando uma nova linha de embalagem e convida o médico do trabalho para participar desde o desenho das plantas. Sobre o momento da intervenção ergonômica, é CORRETO afirmar que:',
  alts: [
    { t: 'A intervenção na concepção tem a melhor relação custo-benefício, porque as alternativas ainda estão abertas e alterar custa pouco.', ok: true,
      why: 'Correta. Depois de instalado, corrigir é mais caro e mais limitado.' },
    { t: 'A ergonomia só se aplica a postos em operação, por depender da observação da atividade real.', ok: false,
      why: 'Errada. A ergonomia de concepção é a etapa mais eficaz.' },
    { t: 'A ergonomia de conscientização substitui concepção e correção havendo bom programa de treinamento.', ok: false,
      why: 'Errada. Treinar não corrige posto mal concebido.' },
    { t: 'Intervir na concepção é desaconselhável, pois impede a participação de quem ainda não conhece o posto.', ok: false,
      why: 'Errada. Trabalhadores de atividades similares podem e devem participar.' },
    { t: 'Adotada a ergonomia de concepção, dispensa-se qualquer avaliação posterior do posto em operação.', ok: false,
      why: 'Errada. O trabalho real sempre difere do projetado.' }
  ],
  comentario: 'Concepção, correção e conscientização formam uma escala decrescente de eficácia e crescente de custo por resultado. O ideal é intervir no projeto; a correção é o cotidiano; a conscientização é adjuvante e nunca solução isolada.',
  pegadinha: 'A ideia de que só se pode fazer ergonomia com o posto funcionando parece rigorosa, mas na prática condena a empresa a corrigir sempre depois do dano.',
  refs: ['Couto — Ergonomia', 'NR-17', 'Guérin et al. — Compreender o trabalho para transformá-lo'] },

{ id: 'q-3.1-012', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao projetar o painel de comando de uma prensa, o projetista dispõe de tabelas antropométricas estáticas obtidas com sujeitos em postura padronizada, despidos e imóveis. Sobre o uso desses dados, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Precisam de correção para vestuário, calçado, equipamentos e movimento: a atividade é dinâmica.', ok: true,
      why: 'Correta. Dados estáticos não descrevem alcances funcionais em movimento.' },
    { t: 'Descrevem adequadamente os alcances funcionais, o que dispensa qualquer correção adicional.', ok: false,
      why: 'Errada. Vestuário, calçado e movimento alteram alcances e folgas.' },
    { t: 'A antropometria dinâmica é sinônimo de antropometria estática medida na posição em pé.', ok: false,
      why: 'Errada. Dinâmica descreve alcances durante o movimento.' },
    { t: 'Como o equipamento de proteção reduz as dimensões corporais, as folgas devem ser diminuídas.', ok: false,
      why: 'Errada. O equipamento aumenta as dimensões e exige mais folga.' },
    { t: 'Dados antropométricos envelhecem pouco: tabelas de qualquer década descrevem bem a população atual.', ok: false,
      why: 'Errada. As dimensões populacionais mudam ao longo das décadas.' }
  ],
  comentario: 'A questão cobra a distinção entre antropometria estática e dinâmica e a necessidade de correções por vestuário e proteção individual. Painel projetado para o corpo nu e imóvel produz alcances impossíveis para quem trabalha de luva, botina e capacete.',
  pegadinha: 'A ideia de que proteção individual "diminui" o corpo é um erro grosseiro que, apresentado em linguagem técnica, engana quem lê rápido.',
  refs: ['Couto — Ergonomia', 'Iida — Ergonomia: projeto e produção'] },

{ id: 'q-3.1-013', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um almoxarife precisa retirar caixas de uma prateleira profunda, com os braços estendidos à frente, e depositá-las em um carrinho. O engenheiro pergunta por que a mesma caixa "parece mais pesada" quando retirada do fundo da prateleira. A explicação biomecânica CORRETA é:',
  alts: [
    { t: 'Afastar a carga amplia o braço de alavanca e o momento a vencer, elevando a compressão discal.', ok: true,
      why: 'Correta. É por isso que aproximar a carga do corpo reduz tanto o esforço.' },
    { t: 'O peso real da carga aumenta com a distância, por efeito da gravidade sobre o braço estendido.', ok: false,
      why: 'Errada. O peso não muda; muda o momento sobre a coluna.' },
    { t: 'A compressão discal depende só do peso, sendo indiferente a posição da carga frente ao tronco.', ok: false,
      why: 'Errada. A distância horizontal é determinante do momento.' },
    { t: 'A percepção de esforço aumenta por fator psicológico, sem correspondência com a carga mecânica.', ok: false,
      why: 'Errada. Corresponde a um aumento real da exigência muscular.' },
    { t: 'Afastar a carga reduz a exigência paravertebral, por distribuir o esforço aos membros superiores.', ok: false,
      why: 'Errada. Aumenta a exigência da musculatura extensora da coluna.' }
  ],
  comentario: 'Manter a carga próxima ao corpo é a recomendação biomecânica mais rentável do manuseio manual, porque o braço de alavanca entra na conta como multiplicador. Prateleiras profundas e barreiras que impedem aproximar-se da carga são fatores de risco de projeto, não de comportamento.',
  pegadinha: 'A alternativa que atribui tudo a fator psicológico soa moderna e humanista, mas nega a mecânica elementar do problema.',
  refs: ['Chaffin — Biomecânica Ocupacional', 'NIOSH — Applications Manual for the Revised Lifting Equation'] },

{ id: 'q-3.1-014', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadores de uma vidraçaria sustentam chapas com os braços elevados acima da linha dos ombros durante boa parte do turno. O ambulatório registra aumento de queixas de ombro. Sobre esse padrão de exigência, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Trabalhar com os braços acima dos ombros soma contração estática e redução da perfusão dos tendões do manguito rotador.', ok: true,
      why: 'Correta. É o mecanismo que favorece tendinopatia e síndrome do impacto.' },
    { t: 'As contrações estáticas são menos lesivas que as dinâmicas, por não gerarem movimento articular.', ok: false,
      why: 'Errada. A contração estática mantida reduz a perfusão e fadiga mais.' },
    { t: 'A elevação dos braços é irrelevante desde que o peso sustentado seja de poucos quilos apenas.', ok: false,
      why: 'Errada. A postura mantida é lesiva mesmo com carga baixa.' },
    { t: 'A prevenção adequada é o alongamento no início do turno, sem rever a altura do plano de trabalho.', ok: false,
      why: 'Errada. A altura do plano é o determinante a corrigir.' },
    { t: 'A dor de ombro nesse contexto indica doença degenerativa prévia, sem relação com a tarefa exercida.', ok: false,
      why: 'Errada. A exigência postural é fator reconhecido do quadro.' }
  ],
  comentario: 'Três variáveis explicam a maioria dos quadros de ombro relacionados ao trabalho: altura do plano de trabalho, tempo de sustentação e ausência de apoio. A contração isométrica prolongada é especialmente danosa porque a própria pressão intramuscular restringe o fluxo sanguíneo que a musculatura precisaria para se recuperar.',
  pegadinha: 'A inversão "estático é mais seguro que dinâmico" é o distrator central e contraria a fisiologia muscular do trabalho.',
  refs: ['Chaffin — Biomecânica Ocupacional', 'Couto — Ergonomia', 'NR-17'] },

{ id: 'q-3.1-015', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma linha de montagem de componentes eletrônicos, cada trabalhador executa ciclos curtos e repetidos de aperto com pinça durante toda a jornada. A gerência propõe aumentar o ritmo e compensar com uma pausa única de vinte minutos ao final do turno. Sobre tempo de recuperação, a análise CORRETA é:',
  alts: [
    { t: 'A recuperação depende de pausas distribuídas; concentrar o descanso no fim não previne a fadiga.', ok: true,
      why: 'Correta. A fadiga se acumula ao longo do turno, não só ao final.' },
    { t: 'O que importa é o tempo total de pausa na jornada, sendo indiferente a forma como se distribui.', ok: false,
      why: 'Errada. A distribuição é o que permite a recuperação tecidual.' },
    { t: 'Aumentar o ritmo é neutro quanto ao risco, desde que a força por ciclo permaneça baixa.', ok: false,
      why: 'Errada. A frequência de ações é fator de risco por si.' },
    { t: 'A repetitividade só é risco quando associada a cargas acima da preensão máxima do trabalhador.', ok: false,
      why: 'Errada. Alta repetição com força baixa já adoece.' },
    { t: 'A pausa perde sentido quando usada para atividades pessoais, devendo ser suprimida nesse caso.', ok: false,
      why: 'Errada. A recuperação ocorre pela interrupção da exigência.' }
  ],
  comentario: 'Três parâmetros governam o risco em tarefas repetitivas: força, repetitividade e tempo de recuperação. Aumentar cadência sem rever a razão trabalho/pausa piora o terceiro parâmetro, que é justamente o que permite ao tecido se reparar entre esforços.',
  pegadinha: 'A ideia de que só conta o tempo total de descanso é aritmeticamente atraente e fisiologicamente falsa.',
  refs: ['Colombini e Occhipinti — OCRA', 'NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-016', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Operadores de caixa de um supermercado trabalham sentados durante toda a jornada, com pouca variação postural. Um consultor afirma que "sentado não há risco ergonômico". Sobre trabalho sentado, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A postura sentada prolongada sem alternância eleva a pressão discal lombar e não elimina o risco musculoesquelético do posto.', ok: true,
      why: 'Correta. Sentar não é descansar a coluna; é carregá-la de outro modo.' },
    { t: 'A postura sentada elimina a carga lombar, suportada integralmente pelo assento da cadeira.', ok: false,
      why: 'Errada. A pressão discal sentado é maior que em pé.' },
    { t: 'A alternância entre sentar e ficar em pé é desaconselhada por aumentar o gasto energético.', ok: false,
      why: 'Errada. A alternância é justamente a medida recomendada.' },
    { t: 'O encosto lombar é dispensável quando a cadeira possui apoio de braços com regulagem de altura.', ok: false,
      why: 'Errada. São recursos com funções distintas.' },
    { t: 'O apoio para os pés só é necessário para trabalhadores com estatura acima da média da população.', ok: false,
      why: 'Errada. É necessário para os de menor estatura.' }
  ],
  comentario: 'Sentado, em pé ou alternado, o inimigo é a postura mantida. O projeto adequado busca alternância, apoio adequado da região lombar, altura de assento compatível com a altura poplítea e apoio para os pés quando a superfície de trabalho impõe assento alto.',
  pegadinha: 'A afirmação de que o apoio para os pés serve aos mais altos inverte a lógica antropométrica do ajuste.',
  refs: ['NR-17', 'Couto — Ergonomia', 'Iida — Ergonomia: projeto e produção'] },

{ id: 'q-3.1-017', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma indústria de calçados, um grupo trabalha o dia inteiro em pé, praticamente sem deslocamento, sobre piso de concreto. As queixas mais frequentes são dor em pernas, sensação de peso e edema vespertino. Sobre a situação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O ortostatismo estático prejudica o retorno venoso, e barra de apoio, piso amortecido e alternância com a postura sentada são medidas pertinentes.', ok: true,
      why: 'Correta. A ausência de deslocamento é o que agrava o quadro.' },
    { t: 'Trabalhar em pé é sempre preferível a sentado, seja qual for a tarefa, por preservar a lordose lombar.', ok: false,
      why: 'Errada. Cada postura tem seus custos; a alternância é o que protege.' },
    { t: 'O edema vespertino indica sempre insuficiência cardíaca e exige afastamento imediato do trabalho.', ok: false,
      why: 'Errada. É achado esperado do ortostatismo prolongado.' },
    { t: 'Oferecer assentos para descanso nos intervalos é inútil, pois não altera a exposição no turno.', ok: false,
      why: 'Errada. Permite recuperação do retorno venoso durante a jornada.' },
    { t: 'A dureza do piso não tem relevância, pois o calçado de segurança absorve todo o impacto recebido.', ok: false,
      why: 'Errada. O piso amortecido reduz desconforto de forma documentada.' }
  ],
  comentario: 'O problema do trabalho em pé não é a postura em si, mas a imobilidade. Movimento, alternância, apoio para elevar alternadamente um dos pés e piso com alguma absorção são as intervenções de base.',
  pegadinha: 'A afirmação de que "em pé é sempre melhor" repete um senso comum que a ergonomia contradiz: o inimigo é a fixidez, não a posição.',
  refs: ['NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-018', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa de tecnologia adota estações de trabalho com monitor, teclado e mouse, e solicita orientação sobre o arranjo. Sobre trabalho com terminais de vídeo, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O topo da tela deve ficar acima dos olhos, para estimular a extensão cervical e reduzir a fadiga.', ok: true,
      why: 'É a INCORRETA. O topo da tela deve ficar na altura dos olhos ou pouco abaixo.' },
    { t: 'O teclado deve manter os punhos em posição neutra, evitando extensão e desvio ulnar sustentados.', ok: false,
      why: 'Correta, portanto não é a resposta. É a recomendação padrão.' },
    { t: 'O mouse deve ficar no mesmo plano e próximo ao teclado, para evitar abdução prolongada do ombro.', ok: false,
      why: 'Correta, portanto não é a resposta. Evita carga estática no ombro.' },
    { t: 'A tela deve evitar reflexos de janelas e luminárias, que induzem posturas compensatórias e fadiga.', ok: false,
      why: 'Correta, portanto não é a resposta. O ofuscamento gera postura viciosa.' },
    { t: 'Pausas visuais com foco em objetos distantes reduzem sintomas de fadiga no trabalho com telas.', ok: false,
      why: 'Correta, portanto não é a resposta. É orientação consolidada.' }
  ],
  comentario: 'O arranjo do posto informatizado tem regras estáveis: tela na altura dos olhos ou pouco abaixo, distância confortável de leitura, punhos neutros, mouse ao lado e no mesmo plano do teclado, ausência de reflexos e pausas visuais. Elevar a tela acima dos olhos é erro frequente em improvisações com suportes.',
  pegadinha: 'Enunciado de negativa com quatro recomendações corretas. A falsa aparece disfarçada de justificativa fisiológica ao propor "estimular a extensão cervical", que é exatamente o que se quer evitar.',
  refs: ['NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-019', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um laboratório de análises pede orientação sobre a altura das bancadas, que hoje têm altura única para tarefas de pipetagem de precisão, manuseio de caixas e uso de equipamentos pesados. Sobre a definição da altura do plano de trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A altura varia com a tarefa: precisão pede plano mais alto; força pede plano mais baixo.', ok: true,
      why: 'Correta. A referência é a altura dos cotovelos, ajustada pela exigência.' },
    { t: 'Toda superfície deve ser padronizada na altura dos ombros, de modo a reduzir a flexão do tronco.', ok: false,
      why: 'Errada. Trabalhar na altura dos ombros gera carga estática elevada.' },
    { t: 'Tarefas de força devem ser feitas em plano mais alto, para aproveitar a gravidade sobre os braços.', ok: false,
      why: 'Errada. Força pede plano abaixo dos cotovelos, com o peso do corpo.' },
    { t: 'A altura ideal é sempre a média dos cotovelos da população, seja qual for o tipo de tarefa.', ok: false,
      why: 'Errada. A exigência da tarefa desloca a altura ótima.' },
    { t: 'Bancadas de altura regulável são contraindicadas em laboratório por comprometer a estabilidade.', ok: false,
      why: 'Errada. Há soluções reguláveis estáveis e recomendadas.' }
  ],
  comentario: 'A regra é referenciar o plano de trabalho à altura do cotovelo do trabalhador em pé e ajustar conforme a tarefa: acima do cotovelo para precisão, na altura para trabalho leve, abaixo para trabalho pesado. Superfícies de altura única para tarefas heterogêneas garantem que alguém sempre trabalhará mal.',
  pegadinha: 'A inversão "força em plano alto" invoca a gravidade de modo plausível, mas contraria a mecânica do empurrar e do prensar.',
  refs: ['Iida — Ergonomia: projeto e produção', 'Couto — Ergonomia', 'NR-17'] },

{ id: 'q-3.1-020', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma empresa de logística, o setor de expedição movimenta carrinhos carregados por longas distâncias em piso irregular. O supervisor pergunta se é melhor empurrar ou puxar e por que os trabalhadores reclamam mais no início do movimento. A resposta tecnicamente CORRETA é:',
  alts: [
    { t: 'Empurrar costuma ser preferível a puxar, e a força para iniciar o movimento supera a de mantê-lo.', ok: true,
      why: 'Correta. Arranques repetidos são, por isso, particularmente exigentes.' },
    { t: 'Puxar é sempre preferível, por permitir ao trabalhador visualizar o trajeto à frente do carrinho.', ok: false,
      why: 'Errada. Puxar exige postura menos favorável e mais carga lombar.' },
    { t: 'A força de manutenção do movimento é sempre maior que a inicial, por acúmulo progressivo de fadiga.', ok: false,
      why: 'Errada. A força inicial vence a inércia e é a maior.' },
    { t: 'A qualidade do piso e o estado das rodas são irrelevantes para o esforço exigido no transporte.', ok: false,
      why: 'Errada. São determinantes diretos da força necessária.' },
    { t: 'O transporte com carrinho elimina o risco musculoesquelético e dispensa a avaliação da tarefa.', ok: false,
      why: 'Errada. Empurrar e puxar têm exigências próprias a avaliar.' }
  ],
  comentario: 'Empurrar e puxar têm biomecânica própria: interessam a força inicial e a de manutenção, a altura das alças, o atrito das rodas, a qualidade do piso e a distância percorrida. Substituir levantamento por transporte com carrinho é ganho, mas transfere o problema, não o extingue.',
  pegadinha: 'A inversão entre força inicial e força de manutenção é o distrator central, reforçado pelo apelo intuitivo ao "acúmulo de fadiga".',
  refs: ['Chaffin — Biomecânica Ocupacional', 'Snook e Ciriello — tabelas psicofísicas'] },

{ id: 'q-3.1-021', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um trabalhador da manutenção usa chave de fenda reta para apertar parafusos em painéis verticais, mantendo o punho em desvio acentuado durante todo o movimento. Sobre projeto e uso de ferramentas manuais, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A ferramenta deve permitir punho neutro: dobre a ferramenta, não o punho.', ok: true,
      why: 'Correta. É o princípio que orienta o projeto de ferramentas manuais.' },
    { t: 'A empunhadura com cabo muito fino aumenta a eficiência de preensão e deve ser preferida na tarefa.', ok: false,
      why: 'Errada. Cabo fino concentra pressão e exige mais força.' },
    { t: 'Ferramentas mais pesadas são preferíveis por reduzir a força que o trabalhador precisa aplicar.', ok: false,
      why: 'Errada. O peso é sustentado pelo membro superior e fadiga.' },
    { t: 'O uso de luvas não interfere na força de preensão necessária para operar a ferramenta com segurança.', ok: false,
      why: 'Errada. Luvas reduzem a preensão e exigem mais força.' },
    { t: 'Ferramentas com gatilho de um dedo distribuem melhor o esforço que as de barra para vários dedos.', ok: false,
      why: 'Errada. A barra distribui a força entre os dedos e é preferível.' }
  ],
  comentario: 'O projeto de ferramentas manuais busca punho neutro, diâmetro de cabo adequado, ausência de cantos que concentrem pressão, peso reduzido ou suspenso, acionamento distribuído e proteção contra vibração e frio. Adaptar a ferramenta é intervenção de engenharia; treinar o trabalhador a "usar melhor" é a via mais frágil.',
  pegadinha: 'A defesa de cabos finos e de acionamento por um dedo soa como refinamento de precisão, mas concentra carga onde a lesão aparece.',
  refs: ['Iida — Ergonomia: projeto e produção', 'Couto — Ergonomia'] },

{ id: 'q-3.1-022', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao dimensionar a bancada de uma linha de inspeção, o projetista define a zona em que os componentes de uso frequente serão dispostos. Sobre zonas de alcance, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O que se usa com frequência fica na zona de alcance ótima, definida pelo movimento do antebraço com o braço junto ao corpo.', ok: true,
      why: 'Correta. A zona de alcance máximo se reserva ao uso ocasional.' },
    { t: 'A disposição deve seguir apenas a lógica do fluxo produtivo, sendo o alcance questão secundária.', ok: false,
      why: 'Errada. O alcance define a carga postural repetida.' },
    { t: 'A zona de alcance máximo é a indicada para os itens de maior frequência, por dar mais amplitude.', ok: false,
      why: 'Errada. Alcances amplos repetidos sobrecarregam o ombro.' },
    { t: 'O alcance deve ser dimensionado pelo trabalhador de maior estatura, para conforto de toda a equipe.', ok: false,
      why: 'Errada. Alcance se dimensiona pelo menor; espaço livre, pelo maior.' },
    { t: 'As zonas de alcance aplicam-se apenas ao trabalho sentado, sem utilidade no trabalho em pé.', ok: false,
      why: 'Errada. Aplicam-se às duas posturas.' }
  ],
  comentario: 'Alcance ótimo para o que se usa sempre; alcance máximo apenas para o eventual; e o dimensionamento pelo menor, porque quem define o limite de alcance é ele. É um dos princípios antropométricos mais cobrados.',
  pegadinha: 'A justificativa de "evitar postura fixa" é verdadeira como princípio geral e usada aqui para legitimar exatamente o erro oposto.',
  refs: ['Iida — Ergonomia: projeto e produção', 'Couto — Ergonomia', 'NR-17'] },

{ id: 'q-3.1-023', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'A direção de uma transportadora propõe, como única medida de prevenção de lombalgia, um treinamento anual de "técnica correta de levantamento de peso" para todos os ajudantes. Sobre a eficácia dessa estratégia, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Treinar técnica de levantamento isoladamente tem eficácia limitada e deve vir com medidas de engenharia e de organização do trabalho.', ok: true,
      why: 'Correta. Sem mudar carga, altura e frequência, o treino não sustenta efeito.' },
    { t: 'O treinamento em técnica de levantamento é a medida isolada mais eficaz contra a lombalgia ocupacional.', ok: false,
      why: 'Errada. A evidência mostra eficácia limitada quando isolado.' },
    { t: 'Cintos e coletes lombares substituem com vantagem as medidas de engenharia na prevenção.', ok: false,
      why: 'Errada. Não há evidência de eficácia preventiva dos cintos.' },
    { t: 'Testes de força e flexibilidade na admissão excluem quem desenvolverá lombalgia, resolvendo na seleção.', ok: false,
      why: 'Errada. O poder preditivo é baixo e a prática é discriminatória.' },
    { t: 'A lombalgia ocupacional é puramente biomecânica, sendo irrelevantes fatores organizacionais.', ok: false,
      why: 'Errada. Fatores psicossociais têm peso reconhecido.' }
  ],
  comentario: 'A hierarquia de controle vale também para ergonomia: eliminar o manuseio, mecanizar, reduzir peso e distância, reorganizar o fluxo, e só então informar e treinar. O treinamento isolado é a resposta que a empresa mais gosta e a que menos entrega.',
  pegadinha: 'O cinto lombar é o distrator afetivo do tema: onipresente na prática e sem sustentação como medida preventiva.',
  refs: ['NIOSH — Applications Manual for the Revised Lifting Equation', 'Cochrane — back belts e treinamento em levantamento'] },

{ id: 'q-3.1-024', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um técnico de laboratório passa horas ao microscópio, com o tronco inclinado à frente e o pescoço fletido, sem apoio de antebraços. Sobre a carga postural nessa situação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A flexão cervical mantida aumenta o momento sobre a coluna, e o apoio de antebraços alivia a cintura escapular.', ok: true,
      why: 'Correta. São os dois pontos a corrigir no posto de microscopia.' },
    { t: 'A flexão cervical não altera a carga sobre a coluna, pois o peso da cabeça é sempre constante.', ok: false,
      why: 'Errada. O momento cresce com o ângulo de flexão.' },
    { t: 'A ausência de apoio de antebraços é irrelevante, pois os membros superiores não geram carga estática.', ok: false,
      why: 'Errada. Sustentar os braços sem apoio é carga estática significativa.' },
    { t: 'A solução é orientar o trabalhador a manter postura ereta por força de vontade durante a jornada.', ok: false,
      why: 'Errada. A postura decorre da geometria do posto, não da vontade.' },
    { t: 'A microscopia é atividade sem risco ergonômico, por não envolver força nem movimentos amplos.', ok: false,
      why: 'Errada. Postura estática mantida é exposição relevante.' }
  ],
  comentario: 'Postura mantida, mesmo sem força e sem repetição, é fator de risco. O trabalho ao microscópio, à lupa e em bancadas de inspeção reúne flexão cervical, ausência de apoio e imobilidade prolongada — a intervenção passa por altura de bancada, inclinação da ocular, apoio de antebraços e pausas.',
  pegadinha: 'Definir risco ergonômico apenas por força e repetição exclui indevidamente as posturas estáticas, que são causa frequente de queixa cervical.',
  refs: ['Couto — Ergonomia', 'NR-17'] },

{ id: 'q-3.1-025', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria pergunta ao médico do trabalho qual é "o peso máximo que um trabalhador pode levantar". Sobre a resposta tecnicamente adequada, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Não há valor único: o risco depende de posição da carga, alturas, frequência, torção, pega e duração.', ok: true,
      why: 'Correta. O peso isolado não caracteriza a exigência da tarefa.' },
    { t: 'Existe um valor universal de peso máximo, igual para qualquer trabalhador e qualquer tarefa.', ok: false,
      why: 'Errada. O limite depende das condições concretas do levantamento.' },
    { t: 'O limite deve ser fixado pela força máxima medida em dinamometria individual do trabalhador.', ok: false,
      why: 'Errada. Força máxima não define exposição sustentável.' },
    { t: 'Abaixo do limite psicofísico aceito por três quartos da população, não cabe medida preventiva.', ok: false,
      why: 'Errada. Frequência e duração podem tornar aceitável o insustentável.' },
    { t: 'Se o trabalhador não relata dor, a tarefa está automaticamente dentro de limites seguros.', ok: false,
      why: 'Errada. A ausência de sintoma precede o dano acumulado.' }
  ],
  comentario: 'A pergunta "qual o peso máximo" é uma armadilha frequente na prática. A resposta correta descreve o conjunto de variáveis da tarefa e remete à avaliação com método adequado, em vez de fornecer um número que a empresa transformará em regra.',
  pegadinha: 'Toda alternativa que entrega um número único é atraente para quem quer resposta pronta, e é exatamente o erro conceitual que a questão cobra.',
  refs: ['NIOSH — Applications Manual for the Revised Lifting Equation', 'Snook e Ciriello — tabelas psicofísicas', 'NR-17'] },

{ id: 'q-3.1-026', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Em um centro de distribuição, o médico do trabalho observa que os operadores levantam caixas do piso com tronco fletido e joelhos estendidos, e discute com a equipe as alternativas de técnica. Sobre biomecânica do levantamento, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Flexionar joelhos com tronco ereto reduz o momento lombar, mas depende do formato da carga e do espaço para aproximá-la do corpo.', ok: true,
      why: 'Correta. A técnica não se aplica a qualquer carga nem a qualquer posto.' },
    { t: 'A técnica com joelhos fletidos elimina o risco lombar em qualquer situação de manuseio de cargas.', ok: false,
      why: 'Errada. Reduz, mas não elimina, e nem sempre é praticável.' },
    { t: 'Levantar do piso é equivalente, em exigência, a levantar da altura da cintura do trabalhador.', ok: false,
      why: 'Errada. A altura de origem muda substancialmente a exigência.' },
    { t: 'A torção do tronco durante o levantamento é irrelevante desde que a carga levantada seja leve.', ok: false,
      why: 'Errada. A torção sob carga é fator de risco independente.' },
    { t: 'A qualidade da pega da caixa não influencia o risco, por não alterar o peso efetivamente levantado.', ok: false,
      why: 'Errada. Pega ruim aumenta a força de preensão e afasta a carga.' }
  ],
  comentario: 'A técnica de levantamento é um dos fatores, não o fator. Altura de origem e destino, distância horizontal, assimetria, frequência, pega e duração compõem o risco. Elevar a carga do piso com paletes reguláveis costuma render mais que qualquer treinamento de técnica.',
  pegadinha: 'A promessa de que uma técnica "elimina" o risco é a formulação absoluta que denuncia o distrator.',
  refs: ['NIOSH — Applications Manual for the Revised Lifting Equation', 'Chaffin — Biomecânica Ocupacional'] },

{ id: 'q-3.1-027', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma montadora instala postos com bancada elétrica de altura ajustável que permite alternar entre trabalho sentado e em pé. Passados seis meses, verifica-se que quase ninguém utiliza a regulagem. Sobre a situação, a análise CORRETA é:',
  alts: [
    { t: 'Ter o recurso não garante seu uso: é preciso ver se ritmo, layout, treino e cultura permitem alternar.', ok: true,
      why: 'Correta. Sem isso o investimento não se converte em redução de risco.' },
    { t: 'A ausência de uso demonstra que a alternância não traz benefício e o investimento foi equivocado.', ok: false,
      why: 'Errada. O benefício existe; o que falta é condição para usar.' },
    { t: 'A solução é tornar obrigatória a mudança de postura em horários fixos, sem olhar a tarefa.', ok: false,
      why: 'Errada. Alternância imposta sem relação com a tarefa não funciona.' },
    { t: 'Os trabalhadores devem ser advertidos formalmente por descumprir as orientações ergonômicas dadas.', ok: false,
      why: 'Errada. Pune quem está constrangido pelas condições de trabalho.' },
    { t: 'O uso do recurso é irrelevante, pois a possibilidade de ajuste já caracteriza conformidade do posto.', ok: false,
      why: 'Errada. Conformidade formal sem uso real não reduz exposição.' }
  ],
  comentario: 'Entre o posto prescrito e o posto usado há uma distância que só a análise da atividade revela. Investimentos ergonômicos fracassam com frequência não por erro de especificação, mas por ausência de condições organizacionais que permitam usá-los.',
  pegadinha: 'A conclusão de que o não uso "prova" a inutilidade da alternância confunde falha de implantação com falha de conceito.',
  refs: ['Guérin et al. — Compreender o trabalho para transformá-lo', 'NR-17'] },

{ id: 'q-3.1-028', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um operador de britadeira apresenta queixas de dormência nos dedos e dificuldade de manipular objetos pequenos ao final do turno, além de dor em punho. O ambiente é frio e a tarefa exige preensão firme e contínua da ferramenta. Sobre a interação de fatores, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Vibração de mãos e braços, preensão sustentada e frio atuam de forma combinada e potencializam o risco neurovascular.', ok: true,
      why: 'Correta. Os três fatores coexistem nessa atividade e se somam.' },
    { t: 'A vibração de mãos e braços só produz efeito quando associada a levantamento de cargas pesadas.', ok: false,
      why: 'Errada. Produz efeito por si, e o frio e a preensão o agravam.' },
    { t: 'O frio ambiental protege contra os efeitos da vibração ao reduzir o metabolismo local dos tecidos.', ok: false,
      why: 'Errada. O frio agrava, por somar vasoconstrição periférica.' },
    { t: 'A força de preensão aplicada não influencia a quantidade de vibração transmitida ao membro superior.', ok: false,
      why: 'Errada. Maior preensão transmite mais vibração ao membro.' },
    { t: 'Luvas antivibração eliminam o risco integralmente e dispensam limitar o tempo de exposição diário.', ok: false,
      why: 'Errada. Atenuam parcialmente e não dispensam o controle do tempo.' }
  ],
  comentario: 'A questão cobra a lógica da exposição combinada. Em operações com ferramentas vibratórias, o risco é modulado por força de preensão, temperatura, tempo de exposição, postura e características da ferramenta — e as luvas oferecem alívio parcial, não solução.',
  pegadinha: 'Apresentar o frio como fator protetor com justificativa metabólica é o tipo de inversão que sobrevive à leitura apressada.',
  refs: ['NHO 10 — Fundacentro', 'Chaffin — Biomecânica Ocupacional', 'ISO 5349'] },

{ id: 'q-3.1-029', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma equipe de enfermagem realiza transferências manuais de pacientes acamados várias vezes por turno, em leitos de altura fixa e baixa. Sobre a abordagem ergonômica dessa exposição, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A prioridade é reduzir o manuseio manual com equipamentos de transferência, leitos reguláveis e efetivo adequado.', ok: true,
      why: 'Correta. Treinar técnica sem mudar as condições não sustenta o efeito.' },
    { t: 'O treinamento em movimentação manual basta, pois a carga do paciente se distribui entre os profissionais.', ok: false,
      why: 'Errada. A carga permanece elevada e o efeito do treino é limitado.' },
    { t: 'A altura do leito é irrelevante, pois o profissional pode ajoelhar-se para realizar a transferência.', ok: false,
      why: 'Errada. A altura regulável é medida central de redução da carga.' },
    { t: 'A exposição da enfermagem à lombalgia é igual à da população geral, não justificando ação específica.', ok: false,
      why: 'Errada. É das categorias com maior prevalência documentada.' },
    { t: 'O uso de cinto lombar pelos profissionais é a medida de escolha para a prevenção nesse setor.', ok: false,
      why: 'Errada. Não há evidência de eficácia preventiva do cinto.' }
  ],
  comentario: 'Movimentação de pacientes é o exemplo mais claro de que a hierarquia de controle se aplica à ergonomia: equipamento de transferência, leito regulável, dimensionamento de pessoal e reorganização vencem qualquer treinamento de postura.',
  pegadinha: 'A ideia de que a carga se distribui bem entre profissionais ignora a assimetria e a imprevisibilidade do movimento do paciente.',
  refs: ['NR-32', 'NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-030', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao discutir o projeto de um posto para uma população de trabalhadores com grande variação de estatura, o projetista propõe adotar o percentil 50 para todas as dimensões, "por atender à maioria". Sobre esse raciocínio, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A média não corresponde a ninguém em todas as dimensões e exclui os dois extremos ao mesmo tempo; a saída é regulagem com faixa por percentis opostos.', ok: true,
      why: 'Correta. Alcance pelo menor, espaço livre pelo maior, com ajuste entre eles.' },
    { t: 'O percentil cinquenta atende adequadamente a toda a população quando a distribuição é normal.', ok: false,
      why: 'Errada. Nenhum indivíduo é médio em todas as dimensões.' },
    { t: 'Adotar percentis extremos para todas as dimensões é a solução mais segura, ainda que mais cara.', ok: false,
      why: 'Errada. Cada dimensão pede o percentil adequado à sua função.' },
    { t: 'A ajustabilidade dispensa dados antropométricos, bastando oferecer ampla faixa de regulagem no posto.', ok: false,
      why: 'Errada. É a antropometria que define a faixa necessária.' },
    { t: 'Como a variação de estatura entre adultos é pequena, a escolha do percentil pouco afeta o projeto.', ok: false,
      why: 'Errada. A variação é ampla e determina alcances e folgas.' }
  ],
  comentario: 'Duas ideias sustentam o tema: o "homem médio" não existe, porque as dimensões corporais não são todas correlacionadas; e cada dimensão pede o percentil correspondente à sua função — inferior para alcance, superior para folga —, com regulagem sempre que possível.',
  pegadinha: 'Invocar a distribuição normal dá ares de rigor estatístico a um erro de projeto elementar.',
  refs: ['Iida — Ergonomia: projeto e produção', 'Couto — Ergonomia'] },

{ id: 'q-3.1-031', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma cozinha industrial, os auxiliares transportam panelas quentes e volumosas por curtas distâncias, com pega precária e visão do caminho parcialmente obstruída. Sobre os fatores de risco presentes, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'A obstrução da visão do trajeto é irrelevante, por não alterar a carga mecânica sobre a coluna.', ok: true,
      why: 'É a INCORRETA. Obstruir a visão altera a postura e cria risco de queda.' },
    { t: 'A pega precária aumenta a força de preensão necessária e tende a afastar a carga do corpo.', ok: false,
      why: 'Correta, portanto não é a resposta. Aumenta o braço de alavanca.' },
    { t: 'O volume da carga pode impedir a aproximação ao corpo, ampliando o braço de alavanca mesmo com peso moderado.', ok: false,
      why: 'Correta, portanto não é a resposta. Volume importa tanto quanto peso.' },
    { t: 'O risco térmico do conteúdo quente interage com o ergonômico, pois o receio altera a forma de segurar.', ok: false,
      why: 'Correta, portanto não é a resposta. Os riscos interagem na prática.' },
    { t: 'Carrinhos e mudança do fluxo entre estações reduzem a exposição mais que orientações de técnica.', ok: false,
      why: 'Correta, portanto não é a resposta. Engenharia supera instrução.' }
  ],
  comentario: 'A vinheta reúne os fatores que a avaliação de manuseio manual considera: peso, volume, pega, distância, obstáculos, condições do trajeto e riscos associados. Nenhum deles é avaliado isoladamente, e a visibilidade do percurso integra a segurança do transporte.',
  pegadinha: 'Enunciado negativo com quatro afirmações consistentes. A falsa separa artificialmente segurança e ergonomia, como se apenas a carga mecânica importasse.',
  refs: ['NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-032', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma operadora de caixa de supermercado, gestante de 28 semanas, solicita adequação do posto. Sobre a abordagem ergonômica na gestação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A gestação altera alcances, centro de gravidade e tolerância ao ortostatismo, exigindo reavaliar o posto ao longo da gravidez.', ok: true,
      why: 'Correta. A adequação é progressiva, acompanhando as mudanças.' },
    { t: 'A gestação não altera parâmetros antropométricos relevantes para o projeto do posto de trabalho.', ok: false,
      why: 'Errada. Altera alcances, folgas e centro de gravidade.' },
    { t: 'A única conduta cabível é afastar a trabalhadora de qualquer atividade a partir do segundo trimestre.', ok: false,
      why: 'Errada. Adequa-se o posto; o afastamento é para exposições incompatíveis.' },
    { t: 'A adequação do posto só deve ser feita se houver intercorrência obstétrica devidamente documentada.', ok: false,
      why: 'Errada. A adequação é preventiva e não espera intercorrência.' },
    { t: 'Como a gestação é transitória, não se justifica investir em modificação do posto de trabalho.', ok: false,
      why: 'Errada. A adequação costuma beneficiar também os demais.' }
  ],
  comentario: 'A ergonomia trabalha com a variabilidade das pessoas e do tempo. Gestação, envelhecimento, retorno após afastamento e deficiência são situações em que a mesma tarefa impõe exigências diferentes — e a resposta é adequar o trabalho, não selecionar quem o suporta.',
  pegadinha: 'A alternativa que afasta a trabalhadora por regra parece protetora e é, na prática, medida que restringe direitos sem avaliar risco concreto.',
  refs: ['NR-17', 'CLT — proteção à maternidade', 'Couto — Ergonomia'] },

{ id: 'q-3.1-033', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma fábrica de autopeças mantém trabalhadores com mais de 55 anos em postos que exigem esforço físico moderado e alta demanda de destreza visual de perto. Sobre envelhecimento e projeto do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Perdas de acuidade para perto, de força e de tolerância a turnos pedem adequação do posto e da organização.', ok: true,
      why: 'Correta. A experiência acumulada é preservada e compensa parte do declínio.' },
    { t: 'Trabalhadores mais velhos devem ser transferidos para funções administrativas, sem avaliação individual.', ok: false,
      why: 'Errada. É discriminação por idade, sem base funcional.' },
    { t: 'O envelhecimento não altera parâmetros relevantes: basta manter o padrão adotado para adultos jovens.', ok: false,
      why: 'Errada. Iluminação, alcance e ritmo exigem adequação.' },
    { t: 'A experiência acumulada compensa integralmente qualquer declínio, dispensando adequar o posto.', ok: false,
      why: 'Errada. Compensa parte, não tudo.' },
    { t: 'A tolerância ao trabalho noturno aumenta com a idade, pela maior estabilidade do ritmo circadiano.', ok: false,
      why: 'Errada. A tolerância tende a diminuir com a idade.' }
  ],
  comentario: 'Envelhecimento no trabalho não é sinônimo de incapacidade: é mudança de perfil de capacidades. Iluminação, contraste, redução de exigência de força de pico, margem de autonomia e escalas mais previsíveis costumam ser as adequações de maior retorno.',
  pegadinha: 'A inversão sobre tolerância ao trabalho noturno é sutil e contradiz a literatura de cronobiologia ocupacional.',
  refs: ['Couto — Ergonomia', 'NR-17', 'Ilmarinen — capacidade para o trabalho'] },

{ id: 'q-3.1-034', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um setor de digitação de documentos apresenta queixas difusas de dor em antebraços. O médico do trabalho observa que os trabalhadores mantêm os punhos apoiados na borda da mesa, com extensão e desvio ulnar sustentados, e teclam por longos períodos sem interrupção. Sobre o quadro, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Postura desviada mantida, ausência de pausas e apoio em borda rígida configuram exposição relevante.', ok: true,
      why: 'Correta. A correção passa por apoio adequado, altura e reorganização das pausas.' },
    { t: 'A digitação, por não envolver força expressiva, não constitui exposição ergonômica relevante no setor.', ok: false,
      why: 'Errada. Alta repetição com desvio postural é exposição relevante.' },
    { t: 'Apoiar os punhos na borda da mesa é recomendação ergonômica, pois estabiliza o membro superior.', ok: false,
      why: 'Errada. A compressão em borda rígida é fator de risco.' },
    { t: 'Teclado com maior resistência das teclas reduz a fadiga, por exigir movimentos mais amplos e lentos.', ok: false,
      why: 'Errada. Maior resistência aumenta a força e a fadiga.' },
    { t: 'A conduta adequada é afastar de imediato todos os trabalhadores do setor até a remissão dos sintomas.', ok: false,
      why: 'Errada. Afastar sem corrigir o posto reproduz o quadro no retorno.' }
  ],
  comentario: 'Tarefas de digitação reúnem repetitividade alta, força baixa e postura desviada mantida. O erro comum é achar que "pouca força" significa "pouco risco". Compressão em aresta, extensão de punho e ausência de pausas explicam a maior parte das queixas.',
  pegadinha: 'A recomendação de apoiar o punho na borda da mesa aparece como se fosse boa prática e é justamente o mecanismo de compressão descrito.',
  refs: ['NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.1-035', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma transportadora de bebidas quer estimar a exigência física global da tarefa de carga e descarga ao longo da jornada, e não apenas a carga sobre a coluna em um levantamento isolado. Sobre avaliação da carga fisiológica de trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Frequência cardíaca de trabalho e consumo energético estimado avaliam a carga física global da jornada.', ok: true,
      why: 'Correta. Orientam a necessidade e a distribuição das pausas.' },
    { t: 'A avaliação biomecânica de um levantamento isolado descreve toda a exigência de uma jornada de carga.', ok: false,
      why: 'Errada. Descreve o gesto, não a carga acumulada do turno.' },
    { t: 'A frequência cardíaca não é útil, por sofrer influência de fatores individuais e do ambiente térmico.', ok: false,
      why: 'Errada. É indicador consagrado, interpretado com esses cuidados.' },
    { t: 'A percepção subjetiva de esforço relatada não guarda relação com a carga fisiológica efetivamente imposta.', ok: false,
      why: 'Errada. Correlaciona-se bem com indicadores fisiológicos.' },
    { t: 'Como o trabalho de carga e descarga é dinâmico, não há necessidade de prever pausas de recuperação.', ok: false,
      why: 'Errada. Trabalho dinâmico pesado exige pausas programadas.' }
  ],
  comentario: 'Existem três olhares complementares sobre a carga física: biomecânico (esforço pontual e estruturas sobrecarregadas), fisiológico (custo energético e sustentabilidade da jornada) e psicofísico (o que a população aceita como tolerável). Uma avaliação completa recorre a mais de um.',
  pegadinha: 'Descartar a percepção subjetiva de esforço por ser "subjetiva" ignora que ela é instrumento validado e correlacionado com medidas objetivas.',
  refs: ['Couto — Ergonomia', 'Chaffin — Biomecânica Ocupacional', 'Escala de Borg'] },

{ id: 'q-3.1-036', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa instala em todos os postos administrativos uma cadeira considerada "ergonômica" pelo fabricante, sem regulagens, e informa que o problema ergonômico do escritório está resolvido. Sobre essa afirmação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O rótulo de ergonômico não garante adequação: ela depende do usuário, da tarefa e do conjunto do posto.', ok: true,
      why: 'Correta. A ausência de regulagens compromete a adaptação individual.' },
    { t: 'A certificação do produto como ergonômico pelo fabricante assegura adequação a qualquer usuário e tarefa.', ok: false,
      why: 'Errada. Adequação é relação entre pessoa, tarefa e posto.' },
    { t: 'A cadeira é o único elemento determinante do conforto no trabalho de natureza administrativa.', ok: false,
      why: 'Errada. Mesa, tela, teclado e organização também determinam.' },
    { t: 'Regulagens são desnecessárias quando o mobiliário foi dimensionado pela média da população usuária.', ok: false,
      why: 'Errada. A média não atende à variabilidade real.' },
    { t: 'A adequação do mobiliário dispensa a análise da atividade efetivamente realizada naquele posto.', ok: false,
      why: 'Errada. É a atividade que define o que o posto precisa oferecer.' }
  ],
  comentario: 'Não existe cadeira ergonômica: existe cadeira adequada a determinada pessoa executando determinada tarefa em determinado posto. O selo comercial substitui a análise com frequência e é uma das formas mais comuns de conformidade aparente.',
  pegadinha: 'O apelo à certificação do fabricante transfere a responsabilidade técnica para um rótulo de marketing.',
  refs: ['NR-17', 'Iida — Ergonomia: projeto e produção'] },

{ id: 'q-3.1-037', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em uma linha de inspeção visual de peças, os trabalhadores relatam dificuldade em identificar defeitos pequenos ao final do turno, com dor ocular e cefaleia. A iluminação é geral e difusa, com luminária única no teto. Sobre a situação, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Inspeção de detalhes finos exige iluminamento e contraste compatíveis, muitas vezes com luz suplementar dirigida.', ok: true,
      why: 'Correta. Controlando ofuscamento e sombras projetadas sobre a peça.' },
    { t: 'Quanto maior o nível de iluminamento, melhor o desempenho visual, sem limite ou efeito adverso.', ok: false,
      why: 'Errada. Excesso gera ofuscamento e reduz o desempenho.' },
    { t: 'A fadiga visual ao fim do turno é inevitável e não deve orientar mudanças no posto de inspeção.', ok: false,
      why: 'Errada. É sinal de inadequação da iluminação ou da tarefa.' },
    { t: 'O contraste entre a peça e o fundo é irrelevante quando o nível de iluminamento está adequado.', ok: false,
      why: 'Errada. Contraste é determinante da detecção do defeito.' },
    { t: 'A correção de vícios de refração dos trabalhadores dispensa adequar a iluminação do posto de trabalho.', ok: false,
      why: 'Errada. São medidas complementares, não substitutivas.' }
  ],
  comentario: 'Desempenho visual depende de nível de iluminamento, contraste, tamanho do detalhe, tempo disponível e ausência de ofuscamento. Em inspeção, iluminação localizada e dirigida costuma resolver o que nenhuma lâmpada de teto resolve.',
  pegadinha: 'A ideia de que "mais luz é sempre melhor" ignora ofuscamento e reflexos, que pioram exatamente a tarefa que se quer facilitar.',
  refs: ['NR-17', 'NBR ISO/CIE 8995-1', 'Iida — Ergonomia: projeto e produção'] },

{ id: 'q-3.1-038', tema: '3.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador de manutenção predial realiza tarefas variadas: sobe escadas, trabalha agachado sob pias, mantém braços elevados em forros e carrega ferramentas. O gestor argumenta que, por serem tarefas variadas, não há risco ergonômico. Sobre esse argumento, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A variedade reduz monotonia e componente estático, mas não elimina o risco quando há posturas extremas e picos de esforço.', ok: true,
      why: 'Correta. Tarefa variada com exigências altas segue sendo exposição.' },
    { t: 'A variação de tarefas elimina o risco ergonômico, pois nenhuma postura é mantida por muito tempo.', ok: false,
      why: 'Errada. Posturas extremas e picos de força permanecem.' },
    { t: 'Somente as tarefas repetitivas de ciclo curto configuram risco ergonômico a ser avaliado no posto.', ok: false,
      why: 'Errada. Força, postura e manuseio também configuram risco.' },
    { t: 'Em atividades variadas não é possível avaliação ergonômica, por ausência de ciclo bem definido.', ok: false,
      why: 'Errada. Há métodos próprios para atividades não cíclicas.' },
    { t: 'A avaliação deve considerar apenas a tarefa que ocupa a maior parte do tempo da jornada.', ok: false,
      why: 'Errada. Tarefas curtas e intensas podem ser as mais lesivas.' }
  ],
  comentario: 'Trabalho variado é vantagem quando a variação alterna grupos musculares e permite recuperação; deixa de ser vantagem quando apenas soma posturas extremas. A avaliação de atividades não cíclicas é possível por amostragem, e as tarefas breves de alto pico precisam entrar na conta.',
  pegadinha: 'O argumento de que "não há ciclo, logo não há como avaliar" é usado com frequência para evitar avaliação em manutenção e em serviços.',
  refs: ['NR-17', 'Couto — Ergonomia'] }

,

{ id: 'q-3.2-010', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria de bebidas solicita análise ergonômica do trabalho no setor de envase, após aumento de afastamentos. O consultor entrega, em duas semanas, um relatório baseado apenas na descrição de cargos fornecida pelo departamento de pessoal e em fotografias dos postos. Sobre a adequação metodológica, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O trabalho foi descrito pela tarefa prescrita: falta observar a atividade real e ouvir os trabalhadores.', ok: true,
      why: 'Correta. Registro dos modos operatórios e verbalização são do método.' },
    { t: 'A descrição de cargos é a fonte mais fidedigna da atividade, por representar o trabalho oficial.', ok: false,
      why: 'Errada. Descreve o prescrito, que difere do executado.' },
    { t: 'Fotografias dos postos são suficientes, pois permitem medir ângulos articulares com boa precisão.', ok: false,
      why: 'Errada. Um instante não representa a variabilidade da atividade.' },
    { t: 'A verbalização deve ser evitada, por introduzir subjetividade que compromete a validade da análise.', ok: false,
      why: 'Errada. É componente metodológico essencial.' },
    { t: 'A análise ergonômica dispensa a etapa de restituição dos resultados aos trabalhadores envolvidos.', ok: false,
      why: 'Errada. A restituição integra o método e valida o diagnóstico.' }
  ],
  comentario: 'Análise ergonômica do trabalho não é vistoria de posto. Ela parte da demanda, delimita a tarefa, observa a atividade real, ouve o trabalhador, formula um diagnóstico e produz recomendações validadas com quem faz o trabalho.',
  pegadinha: 'Confundir descrição de cargo com descrição do trabalho é o erro estruturante do tema, e o mais comum em relatórios comerciais.',
  refs: ['Guérin et al. — Compreender o trabalho para transformá-lo', 'NR-17'] },

{ id: 'q-3.2-011', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'A gerência de uma empresa de call center encomenda uma análise ergonômica alegando "queixas de dor nos trabalhadores". Ao iniciar o estudo, o ergonomista identifica que a real preocupação da direção é a queda de produtividade após a mudança do sistema informatizado. Sobre a condução do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É a primeira etapa e deve explicitar quem demanda, o que se busca e quais interesses estão em jogo.', ok: true,
      why: 'Correta. Pode levar à reformulação da demanda inicialmente apresentada.' },
    { t: 'O ergonomista deve responder estritamente à demanda escrita, sem investigar os seus determinantes.', ok: false,
      why: 'Errada. A demanda formulada raramente é o problema real.' },
    { t: 'Se a preocupação é produtividade, a análise não se aplica e o caso vai à engenharia de processos.', ok: false,
      why: 'Errada. Produtividade e saúde costumam ter determinantes comuns.' },
    { t: 'O ergonomista deve ocultar dos trabalhadores o real motivo da intervenção, para não enviesar as observações.', ok: false,
      why: 'Errada. A transparência é condição da participação.' },
    { t: 'A demanda de origem gerencial invalida a análise, que só é legítima quando parte dos trabalhadores.', ok: false,
      why: 'Errada. A origem não invalida; ela é explicitada e analisada.' }
  ],
  comentario: 'A análise da demanda define o rumo de toda a intervenção. Ela identifica os atores, os interesses e a distância entre o problema enunciado e o problema real, e é o momento em que o profissional negocia o escopo do trabalho.',
  pegadinha: 'A ideia de ocultar objetivos "para não enviesar" transporta uma lógica de pesquisa experimental para um contexto onde a confiança é o principal instrumento.',
  refs: ['Guérin et al. — Compreender o trabalho para transformá-lo', 'NR-17'] },

{ id: 'q-3.2-012', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma rede de farmácias com dezenas de lojas pequenas pergunta se precisa realizar análise ergonômica completa em cada unidade. Sobre a relação entre avaliação ergonômica preliminar e análise ergonômica do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A preliminar serve de triagem; não bastando para caracterizar e resolver, faz-se a análise aprofundada.', ok: true,
      why: 'Correta. É a relação prevista entre as duas etapas.' },
    { t: 'A análise aprofundada é obrigatória em todos os postos de qualquer organização, seja qual for o risco.', ok: false,
      why: 'Errada. É indicada quando a preliminar não é suficiente.' },
    { t: 'A avaliação preliminar substitui integralmente a análise aprofundada, desde que esteja documentada.', ok: false,
      why: 'Errada. Situações complexas exigem o aprofundamento.' },
    { t: 'A avaliação preliminar dispensa a participação dos trabalhadores, por ser etapa técnica simplificada.', ok: false,
      why: 'Errada. A participação é prevista também nela.' },
    { t: 'Os achados da preliminar não precisam gerar plano de ação, bastando registro no inventário de riscos.', ok: false,
      why: 'Errada. Devem desdobrar-se em medidas com prazos e responsáveis.' }
  ],
  comentario: 'O raciocínio é o mesmo do gerenciamento de riscos: identificar, avaliar, priorizar e aprofundar onde necessário. A avaliação preliminar é porta de entrada; a análise ergonômica do trabalho é o instrumento de diagnóstico de situações complexas ou persistentes.',
  pegadinha: 'A tentação é tratar a triagem como se fosse o produto final, arquivando o documento sem plano de ação nem reavaliação.',
  refs: ['NR-17', 'Guérin et al. — Compreender o trabalho para transformá-lo'] },

{ id: 'q-3.2-013', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao final de uma análise ergonômica em uma linha de abate de aves, o relatório apresenta apenas a descrição das posturas observadas e a conclusão de que "há risco ergonômico". Sobre os produtos esperados de uma análise ergonômica do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Deve trazer o diagnóstico dos determinantes e recomendações desdobradas em plano com prazos e responsáveis.', ok: true,
      why: 'Correta. Inclui a forma de acompanhar a eficácia das medidas.' },
    { t: 'Basta descrever as posturas e classificar o risco, cabendo à empresa decidir livremente se intervém.', ok: false,
      why: 'Errada. O relatório deve indicar medidas e forma de verificação.' },
    { t: 'O relatório não deve indicar prazos, pois estes dependem exclusivamente do orçamento da empresa.', ok: false,
      why: 'Errada. Sem prazo não há como cobrar nem verificar.' },
    { t: 'A verificação da eficácia é dispensável quando as recomendações foram implantadas conforme o relatório.', ok: false,
      why: 'Errada. Implantar não é o mesmo que ser eficaz.' },
    { t: 'As recomendações devem restringir-se a orientações de postura, por serem de implantação imediata.', ok: false,
      why: 'Errada. Orientação isolada tem eficácia limitada.' }
  ],
  comentario: 'Um relatório de ergonomia que termina em constatação é documento de arquivo. O produto esperado inclui diagnóstico dos determinantes, recomendações hierarquizadas, plano de ação com responsáveis e prazos, e verificação posterior da eficácia.',
  pegadinha: 'Confundir descrição com diagnóstico produz relatórios volumosos e inúteis, muito comuns em auditorias de conformidade.',
  refs: ['NR-17', 'Guérin et al. — Compreender o trabalho para transformá-lo'] },

{ id: 'q-3.2-014', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em um centro de distribuição, os separadores de pedidos são monitorados por sistema que registra o tempo de cada coleta e projeta em painel o desempenho individual comparado à meta. O índice de queixas musculoesqueléticas e de ansiedade cresce. Sobre a organização do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O monitoramento com exposição pública do desempenho intensifica o ritmo e reduz a margem de regulação.', ok: true,
      why: 'Correta. Associa-se a sobrecarga física e a sofrimento psíquico.' },
    { t: 'O monitoramento eletrônico é neutro quanto à saúde, pois apenas registra dados objetivos de produção.', ok: false,
      why: 'Errada. O ritmo imposto e a exposição têm efeito documentado.' },
    { t: 'A exposição pública do desempenho individual é medida motivacional recomendada em saúde ocupacional.', ok: false,
      why: 'Errada. É elemento agravante reconhecido de sofrimento.' },
    { t: 'As queixas musculoesqueléticas nesse contexto decorrem apenas do peso das cargas manuseadas.', ok: false,
      why: 'Errada. O ritmo e a ausência de pausas são determinantes.' },
    { t: 'A solução é oferecer ginástica laboral no início do turno, mantendo inalterado o sistema de metas.', ok: false,
      why: 'Errada. Não toca o determinante do problema.' }
  ],
  comentario: 'Ritmo, metas, autonomia e possibilidade de pausa são variáveis ergonômicas de primeira grandeza. A margem de regulação — a liberdade de acelerar, desacelerar e escolher o modo operatório — é o principal mecanismo de proteção que o trabalhador tem, e sistemas de monitoramento intensivo a suprimem.',
  pegadinha: 'A neutralidade atribuída ao dado "objetivo" ignora que o efeito não vem da medição, mas do uso que se faz dela.',
  refs: ['NR-17', 'De Lucca — Fatores Psicossociais e Saúde Mental no Trabalho', 'Karasek — demanda-controle'] },

{ id: 'q-3.2-015', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma confecção remunera as costureiras por peça produzida. A empresa afirma que o sistema é vantajoso porque cada trabalhadora escolhe seu ritmo. Sobre remuneração por produção, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A remuneração por produção induz mais ritmo, supressão de pausas e ocultamento de sintomas.', ok: true,
      why: 'Correta. É fator de risco reconhecido para distúrbios musculoesqueléticos.' },
    { t: 'A remuneração por produção amplia a autonomia real sobre o ritmo, sendo protetora ergonomicamente.', ok: false,
      why: 'Errada. A autonomia é aparente; o ritmo é ditado pelo ganho.' },
    { t: 'O sistema de pagamento não integra o objeto da análise ergonômica, por ser matéria contratual.', ok: false,
      why: 'Errada. É determinante organizacional da exposição.' },
    { t: 'A supressão de pausas por iniciativa da trabalhadora afasta a responsabilidade da organização.', ok: false,
      why: 'Errada. A iniciativa é condicionada pela forma de remuneração.' },
    { t: 'O ocultamento de sintomas por medo de perder rendimento é raro e sem relevância epidemiológica.', ok: false,
      why: 'Errada. É fenômeno frequente e fonte de subnotificação.' }
  ],
  comentario: 'Sistemas de pagamento por peça, prêmios por produtividade e metas individuais deslocam a decisão sobre o ritmo para o trabalhador sem lhe dar liberdade real. É autonomia formal com determinação econômica, e o resultado costuma ser mais exposição e menos notificação.',
  pegadinha: 'A afirmação de que o trabalhador "escolhe o ritmo" descreve corretamente a forma e falsifica o conteúdo da relação.',
  refs: ['NR-17', 'Couto — Ergonomia', 'De Lucca — Fatores Psicossociais e Saúde Mental no Trabalho'] },

{ id: 'q-3.2-016', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um frigorífico implanta rodízio entre postos para reduzir casos de tendinopatia de membros superiores. Após um ano, a incidência não se altera. Ao examinar a implantação, verifica-se que todos os postos do rodízio exigem preensão com pinça e movimentos repetidos de punho. Sobre o achado, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O rodízio só reduz risco quando alterna exigências sobre estruturas diferentes.', ok: true,
      why: 'Correta. Alternar entre postos de mesma exigência mantém a exposição.' },
    { t: 'O rodízio é sempre eficaz contra distúrbios musculoesqueléticos, quaisquer que sejam os postos.', ok: false,
      why: 'Errada. Depende de alternar as estruturas solicitadas.' },
    { t: 'A ausência de redução da incidência demonstra que os casos não têm relação com o trabalho exercido.', ok: false,
      why: 'Errada. Demonstra que o rodízio foi mal desenhado.' },
    { t: 'O rodízio dispensa avaliar as exigências de cada posto, bastando garantir a alternância entre pessoas.', ok: false,
      why: 'Errada. É a avaliação que define quais postos alternar.' },
    { t: 'O aumento do número de postos incluídos no rodízio garante redução proporcional do risco existente.', ok: false,
      why: 'Errada. Mais postos com a mesma exigência não reduzem nada.' }
  ],
  comentario: 'Rodízio é medida administrativa de eficácia condicionada. Serve quando alterna estruturas solicitadas e distribui exposição; não serve quando é apenas troca de lugar entre tarefas equivalentes. Antes de implantar, é preciso mapear as exigências de cada posto.',
  pegadinha: 'Interpretar a falha da medida como prova de ausência de nexo é o salto lógico que a questão testa.',
  refs: ['Colombini e Occhipinti — OCRA', 'NR-17', 'Couto — Ergonomia'] },

{ id: 'q-3.2-017', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria química opera com turnos ininterruptos e pretende revisar a escala. O médico do trabalho é consultado sobre princípios cronobiológicos. Assinale a alternativa CORRETA:',
  alts: [
    { t: 'O marcapasso circadiano é sincronizado sobretudo pela luz, e escalas previsíveis com rotação horária e poucas noites seguidas são mais toleráveis.', ok: true,
      why: 'Correta. São os parâmetros que mais influem na tolerância à escala.' },
    { t: 'O sincronizador principal do ritmo circadiano é o horário das refeições, sendo a luz fator secundário.', ok: false,
      why: 'Errada. A luz é o sincronizador principal.' },
    { t: 'Escalas imprevisíveis são preferíveis, por permitirem maior flexibilidade de vida pessoal ao trabalhador.', ok: false,
      why: 'Errada. A imprevisibilidade impede planejar o sono.' },
    { t: 'Sequências longas de noites consecutivas são recomendadas, por promoverem adaptação circadiana estável.', ok: false,
      why: 'Errada. A adaptação completa é rara e a sequência longa fadiga.' },
    { t: 'A exposição à luz intensa ao fim do turno noturno, no trajeto para casa, favorece o sono diurno.', ok: false,
      why: 'Errada. A luz matinal atrapalha o sono diurno subsequente.' }
  ],
  comentario: 'Projeto de escalas se apoia em poucos princípios robustos: previsibilidade, rotação preferencialmente horária, limitação de noites consecutivas, intervalos suficientes entre turnos, controle da exposição à luz e possibilidade de cochilo. Nenhum deles envolve decorar números.',
  pegadinha: 'A recomendação sobre luz no trajeto de volta é o detalhe que separa quem entendeu o mecanismo de quem memorizou uma lista.',
  refs: ['Fischer et al. — Trabalho em turnos', 'IARC Monographs', 'NR-17'] },

{ id: 'q-3.2-018', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um técnico de laboratório em escala noturna procura o ambulatório referindo insônia ao tentar dormir de dia, sonolência intensa durante o turno e episódios de quase acidente no trajeto de volta para casa. Sobre a conduta, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É compatível com transtorno do trabalho em turnos: higiene do sono, ajuste de escala e avaliação do deslocamento.', ok: true,
      why: 'Correta. Cabe ainda investigar outros distúrbios do sono associados.' },
    { t: 'É queixa esperada em qualquer trabalhador noturno, sem necessidade de avaliação ou intervenção.', ok: false,
      why: 'Errada. Frequente não significa aceitável nem sem conduta.' },
    { t: 'A conduta de escolha é a prescrição continuada de hipnótico para o sono diurno, sem outras medidas.', ok: false,
      why: 'Errada. Medicar sem ajustar escala e ambiente não resolve.' },
    { t: 'O risco de acidente no deslocamento após o turno noturno não interessa ao médico do trabalho.', ok: false,
      why: 'Errada. É risco decorrente do trabalho e integra a conduta.' },
    { t: 'A sonolência excessiva em trabalhador noturno afasta a necessidade de investigar apneia obstrutiva.', ok: false,
      why: 'Errada. É justamente quando a apneia deve ser investigada.' }
  ],
  comentario: 'Trabalhador de turno com insônia e sonolência exige duas frentes: manejo clínico individual, incluindo busca de distúrbios primários do sono, e intervenção sobre a escala e o ambiente. E a pergunta sobre o trajeto de volta para casa é obrigatória.',
  pegadinha: 'Naturalizar a queixa como "normal para quem trabalha à noite" é a conduta que mais retarda diagnóstico e mais custa em acidentes de trajeto.',
  refs: ['Classificação Internacional dos Distúrbios do Sono', 'Fischer et al. — Trabalho em turnos'] },

{ id: 'q-3.2-019', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Um hospital pretende reduzir os efeitos do trabalho noturno sobre a equipe de enfermagem. Sobre medidas de mitigação, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'Os cochilos programados no turno noturno devem ser proibidos, por prolongar a sonolência.', ok: true,
      why: 'É a INCORRETA. Há evidência de que reduzem sonolência e erros.' },
    { t: 'A iluminação adequada nas áreas de trabalho durante a noite contribui para o estado de alerta.', ok: false,
      why: 'Correta, portanto não é a resposta. A luz sustenta o alerta.' },
    { t: 'Escalas previsíveis e divulgadas com antecedência facilitam o planejamento do sono e da vida social.', ok: false,
      why: 'Correta, portanto não é a resposta. Previsibilidade é fator protetor.' },
    { t: 'Intervalos adequados entre turnos são necessários para permitir sono de recuperação suficiente.', ok: false,
      why: 'Correta, portanto não é a resposta. O intervalo define o sono possível.' },
    { t: 'Orientações sobre escurecimento e controle de ruído no ambiente de sono diurno integram as medidas.', ok: false,
      why: 'Correta, portanto não é a resposta. São higiene do sono do noturno.' }
  ],
  comentario: 'O manejo do trabalho noturno combina medidas organizacionais (escala previsível, intervalos suficientes, limite de noites consecutivas), ambientais (luz, temperatura, disponibilidade de área de descanso) e individuais (higiene do sono, cochilo planejado, cautela no trajeto).',
  pegadinha: 'Enunciado negativo em que a falsa se apoia na inércia do sono, fenômeno real, para negar uma medida cuja eficácia está bem estabelecida.',
  refs: ['Fischer et al. — Trabalho em turnos', 'NR-32', 'NR-17'] },

{ id: 'q-3.2-020', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um ergonomista precisa avaliar o risco de uma tarefa de levantamento de caixas de um palete no piso para uma esteira na altura do peito, com giro de tronco e frequência elevada. Sobre a escolha do método, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A equação de levantamento é adequada: incorpora distância, alturas, assimetria, frequência, duração e pega.', ok: true,
      why: 'Correta. Resulta em um peso limite recomendado para aquela tarefa.' },
    { t: 'A ferramenta indicada é a que avalia repetitividade de membros superiores por ações técnicas por ciclo.', ok: false,
      why: 'Errada. Essa se aplica a trabalho repetitivo, não a levantamento.' },
    { t: 'A equação de levantamento aplica-se também a uma das mãos, sentado e a empurrar e puxar cargas.', ok: false,
      why: 'Errada. Tem condições de aplicação bem delimitadas.' },
    { t: 'Métodos observacionais de postura substituem a avaliação do levantamento por medirem o mesmo construto.', ok: false,
      why: 'Errada. Medem postura, não a exigência do levantamento.' },
    { t: 'Não é preciso método algum: basta comparar o peso da caixa a um limite fixo estabelecido em norma.', ok: false,
      why: 'Errada. Não existe limite fixo aplicável a toda situação.' }
  ],
  comentario: 'Cada método responde a uma pergunta: levantamento de cargas, repetitividade de membros superiores, postura global do corpo, esforço da mão e do punho. Escolher o método é escolher a pergunta — e aplicar um método fora de suas premissas invalida o resultado.',
  pegadinha: 'A alternativa que estende a equação de levantamento a empurrar, puxar e trabalho sentado testa exatamente o conhecimento das premissas de aplicação.',
  refs: ['NIOSH — Applications Manual for the Revised Lifting Equation'] },

{ id: 'q-3.2-021', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao avaliar um posto de montagem em que o trabalhador permanece sentado executando movimentos de punho e cotovelo com pequenas peças, o ergonomista precisa quantificar a exposição postural de membros superiores de forma rápida. Sobre as ferramentas disponíveis, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Pontuam braço, antebraço, punho e pescoço, somam força e uso muscular e geram níveis de ação.', ok: true,
      why: 'Correta. Os níveis de ação orientam a prioridade da intervenção.' },
    { t: 'Esses métodos fornecem diagnóstico clínico de distúrbio musculoesquelético do trabalhador avaliado.', ok: false,
      why: 'Errada. Avaliam exposição postural, não diagnosticam.' },
    { t: 'O escore obtido dispensa a análise da organização, pois já incorpora ritmo, metas e pausas do setor.', ok: false,
      why: 'Errada. Não captam a organização do trabalho.' },
    { t: 'A pontuação independe do avaliador, sendo idêntica em qualquer aplicação do mesmo método.', ok: false,
      why: 'Errada. Há variabilidade entre observadores; exige treino.' },
    { t: 'A avaliação de corpo inteiro e a restrita a membros superiores são intercambiáveis entre si.', ok: false,
      why: 'Errada. Têm objetos e escalas diferentes.' }
  ],
  comentario: 'Instrumentos observacionais entregam um escore de exposição e um nível de ação, não um diagnóstico. São úteis para priorizar e para comparar antes e depois de uma intervenção, e insuficientes para capturar a organização do trabalho.',
  pegadinha: 'Tratar escore de exposição como diagnóstico clínico é erro frequente em relatórios e em perícias.',
  refs: ['McAtamney e Corlett — RULA', 'Hignett e McAtamney — REBA', 'NR-17'] },

{ id: 'q-3.2-022', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um consultor apresenta à empresa um relatório em que todos os postos de uma linha repetitiva foram avaliados por um único método observacional aplicado em uma fotografia por posto. Sobre as limitações dessa abordagem, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Um registro instantâneo não representa a variabilidade do ciclo e do turno, e método único em exposição heterogênea tem baixa validade.', ok: true,
      why: 'Correta. São os dois erros metodológicos do caso.' },
    { t: 'A avaliação por fotografia única é o padrão recomendado, por eliminar a subjetividade do observador.', ok: false,
      why: 'Errada. Um instante não descreve a atividade.' },
    { t: 'Os métodos observacionais são equivalentes, de modo que a escolha não afeta a conclusão obtida.', ok: false,
      why: 'Errada. Cada método tem objeto e sensibilidade próprios.' },
    { t: 'A validade independe do treinamento do avaliador quando o método tem planilha padronizada de registro.', ok: false,
      why: 'Errada. A reprodutibilidade depende de avaliador treinado.' },
    { t: 'Obtido escore abaixo do nível de ação, dispensa-se qualquer reavaliação futura daquele posto.', ok: false,
      why: 'Errada. Mudanças de processo exigem reavaliação.' }
  ],
  comentario: 'As ferramentas de avaliação ergonômica são úteis e limitadas: dependem de amostragem representativa, de treinamento do avaliador e da correspondência entre o método e o tipo de exposição. Nenhuma delas substitui a análise da atividade.',
  pegadinha: 'A promessa de objetividade da fotografia esconde a perda de duração e frequência, que são justamente os fatores que definem o risco cumulativo.',
  refs: ['NR-17', 'McAtamney e Corlett — RULA', 'Colombini e Occhipinti — OCRA'] },

{ id: 'q-3.2-023', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa registra vários casos de tendinopatia de punho no setor de embalagem e institui, como resposta, avaliação médica trimestral de todos os trabalhadores do setor para "detectar casos precocemente". Sobre a estratégia, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A vigilância detecta casos e tendências, mas sem intervir nos determinantes apenas documenta o adoecimento.', ok: true,
      why: 'Correta. Monitorar não é prevenir.' },
    { t: 'A avaliação médica periódica é medida de prevenção primária dos distúrbios musculoesqueléticos.', ok: false,
      why: 'Errada. É prevenção secundária: detecta o efeito já instalado.' },
    { t: 'A identificação de casos dispensa a análise ergonômica quando os acometidos são afastados do setor.', ok: false,
      why: 'Errada. O determinante permanece para quem fica.' },
    { t: 'Casos de distúrbio musculoesquelético relacionado ao trabalho não exigem registro nem comunicação.', ok: false,
      why: 'Errada. São notificáveis e comunicáveis.' },
    { t: 'A ocorrência de casos múltiplos em um mesmo setor sugere causa individual, e não causa coletiva.', ok: false,
      why: 'Errada. Agrupamento aponta causa comum no processo.' }
  ],
  comentario: 'Diante de agrupamento de casos, a resposta é investigar o processo de trabalho. Programas de vigilância clínica sem correção da exposição transformam o serviço médico em contador de casos, e a agregação em um mesmo setor é justamente o sinal que aponta a causa coletiva.',
  pegadinha: 'Chamar rastreamento de prevenção primária é confusão conceitual clássica e vale como distrator em várias áreas do edital.',
  refs: ['NR-17', 'Protocolo de LER/DORT — Ministério da Saúde'] },

{ id: 'q-3.2-024', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Uma empresa de tecnologia adota teletrabalho integral e informa que, por não haver posto físico sob seu controle, não possui responsabilidades ergonômicas sobre os empregados. Sobre teletrabalho e ergonomia, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A empresa mantém o dever de instruir, avaliar as condições e prevenir, mesmo fora de suas dependências.', ok: true,
      why: 'Correta. As obrigações de saúde e segurança alcançam o teletrabalho.' },
    { t: 'Em teletrabalho, a adequação do posto é integralmente do empregado, por se tratar de seu domicílio.', ok: false,
      why: 'Errada. As obrigações do empregador permanecem.' },
    { t: 'A avaliação ergonômica em teletrabalho é tecnicamente impossível, por impedir observar a atividade.', ok: false,
      why: 'Errada. Há métodos remotos e de autoavaliação orientada.' },
    { t: 'O teletrabalho elimina os fatores de risco psicossociais, por conferir autonomia total ao trabalhador.', ok: false,
      why: 'Errada. Introduz isolamento e conexão prolongada.' },
    { t: 'A jornada em teletrabalho não precisa de gestão, pois o trabalhador organiza livremente o seu tempo.', ok: false,
      why: 'Errada. A ausência de limite é fator de risco reconhecido.' }
  ],
  comentario: 'Teletrabalho desloca o posto, não a responsabilidade. As frentes são três: condições físicas do posto domiciliar, organização da jornada e fronteira com a vida pessoal, e riscos psicossociais como isolamento e conectividade permanente.',
  pegadinha: 'O argumento de que "o imóvel é do empregado" confunde propriedade do espaço com responsabilidade pelo trabalho executado nele.',
  refs: ['NR-17', 'CLT — teletrabalho', 'ANAMT — posicionamentos sobre teletrabalho'] },

{ id: 'q-3.2-025', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um banco implanta ergonomia participativa em suas agências, com grupos que reúnem trabalhadores, supervisores e técnicos de segurança para discutir e propor mudanças nos postos. Sobre esse método, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Incorpora o saber do trabalhador e aumenta a adesão, mas exige suporte técnico e poder decisório real.', ok: true,
      why: 'Correta. Sem isso vira consulta simbólica.' },
    { t: 'A participação dos trabalhadores dispensa a atuação de profissional com formação em ergonomia.', ok: false,
      why: 'Errada. O suporte técnico é condição do método.' },
    { t: 'Os grupos participativos devem apenas validar soluções já decididas pela direção, evitando conflito.', ok: false,
      why: 'Errada. Isso descaracteriza a participação.' },
    { t: 'A ergonomia participativa é incompatível com a análise ergonômica, por adotar pressupostos opostos.', ok: false,
      why: 'Errada. São abordagens compatíveis e frequentemente combinadas.' },
    { t: 'A principal vantagem do método é reduzir custos, dispensando investimento em modificar os postos.', ok: false,
      why: 'Errada. Não substitui as mudanças necessárias no posto.' }
  ],
  comentario: 'Participação sem poder de decisão é reunião. Ergonomia participativa funciona quando combina o saber operário sobre a atividade, o suporte técnico qualificado e a capacidade real de transformar o trabalho.',
  pegadinha: 'Apresentar a participação como estratégia de economia é a distorção mais comum na prática das empresas.',
  refs: ['Guérin et al. — Compreender o trabalho para transformá-lo', 'NR-17'] },

{ id: 'q-3.2-026', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao observar uma operadora de caixa de supermercado, o ergonomista percebe que ela desenvolveu um modo próprio de posicionar as mercadorias e de girar o corpo para reduzir o alcance, diferente do procedimento prescrito no treinamento. Sobre esse achado, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É estratégia de regulação criada para dar conta das exigências, e revela determinantes a corrigir.', ok: true,
      why: 'Correta. O desvio é informação, não indisciplina.' },
    { t: 'É descumprimento de procedimento, devendo a trabalhadora ser reorientada e formalmente advertida.', ok: false,
      why: 'Errada. Pune quem compensa uma falha do posto.' },
    { t: 'O desvio em relação ao prescrito indica que o treinamento foi mal absorvido, bastando repeti-lo.', ok: false,
      why: 'Errada. O prescrito é que não dá conta da situação real.' },
    { t: 'As estratégias individuais não devem entrar na análise, por não serem generalizáveis ao coletivo.', ok: false,
      why: 'Errada. São a principal pista sobre os determinantes.' },
    { t: 'A existência de regulação mostra que o posto está adequado, pois o trabalhador conseguiu adaptar-se.', ok: false,
      why: 'Errada. A regulação tem custo para quem a executa.' }
  ],
  comentario: 'A distância entre trabalho prescrito e trabalho real é o objeto da análise ergonômica. As estratégias que os trabalhadores inventam preenchem essa distância e têm um custo, que é justamente o que se quer eliminar transformando o posto.',
  pegadinha: 'Interpretar a adaptação bem-sucedida como prova de adequação do posto inverte o sentido do achado mais importante da observação.',
  refs: ['Guérin et al. — Compreender o trabalho para transformá-lo', 'NR-17'] },

{ id: 'q-3.2-027', tema: '3.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'O serviço de saúde de uma indústria precisa priorizar quais setores receberão análise ergonômica no próximo ano, com recursos limitados. Sobre a priorização, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Deve combinar indicadores de saúde com o inventário de riscos e a percepção dos trabalhadores e da comissão.', ok: true,
      why: 'Correta. Afastamentos, queixas e comunicações entram na priorização.' },
    { t: 'A priorização deve basear-se exclusivamente no número de trabalhadores lotados em cada setor.', ok: false,
      why: 'Errada. Ignora gravidade e intensidade da exposição.' },
    { t: 'Somente os setores com casos já diagnosticados de doença ocupacional devem ser avaliados.', ok: false,
      why: 'Errada. Esperar o diagnóstico é agir tarde demais.' },
    { t: 'A percepção dos trabalhadores não deve entrar, por ser influenciada pela insatisfação com a gestão.', ok: false,
      why: 'Errada. É fonte primária sobre o trabalho real.' },
    { t: 'O critério decisivo deve ser a facilidade de intervenção, priorizando as mudanças mais baratas.', ok: false,
      why: 'Errada. Viabilidade é um dos critérios, não o decisivo.' }
  ],
  comentario: 'Priorizar é decisão técnica e deve cruzar dano observado (afastamentos, queixas, comunicações de acidente) com exposição documentada (inventário de riscos) e com o que os trabalhadores relatam. Facilidade e custo entram depois, para escalonar a execução.',
  pegadinha: 'Descartar a queixa por suposta contaminação por insatisfação elimina o indicador mais sensível e mais precoce disponível.',
  refs: ['NR-17', 'NR-1 — gerenciamento de riscos ocupacionais'] }

/* PROXIMO */
);
