/* Seções 4, 5, 6 e 7 — temas que estavam sem questão nenhuma
   (4.7, 4.10, 5.6, 6.4, 7.1, 7.3, 7.7)
   Questões AUTORAIS, escritas no estilo da banca. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(

/* ==================== 4.7 Psiquiatria Ocupacional ======================= */
{ id: 'q-4.7-010', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Operador de empilhadeira, 38 anos, em tratamento de transtorno depressivo, iniciou medicação com efeito sedativo e relata sonolência diurna nas primeiras semanas. Sobre a conduta do médico do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Considerar o risco da função e a fase do tratamento, com restrição temporária se há sonolência.', ok: true,
      why: 'Correta. A decisão se articula com o médico assistente.' },
    { t: 'O diagnóstico de transtorno depressivo, por si, torna o trabalhador inapto para operar empilhadeira.', ok: false,
      why: 'Errada. O que restringe é o efeito funcional, não o diagnóstico.' },
    { t: 'O uso de psicofármaco deve ser informado ao gestor, para que ele acompanhe o desempenho do operador.', ok: false,
      why: 'Errada. É informação clínica protegida por sigilo.' },
    { t: 'O médico do trabalho deve suspender a medicação, de modo a viabilizar a manutenção na função.', ok: false,
      why: 'Errada. Suspender tratamento necessário cria risco maior.' },
    { t: 'Nenhuma restrição é necessária, pois a sonolência é efeito transitório e esperado do tratamento.', ok: false,
      why: 'Errada. Em função de risco, a sonolência atual importa.' }
  ],
  comentario: 'Aptidão em saúde mental segue a mesma lógica das demais condições: o que pesa é a repercussão funcional atual frente ao risco da tarefa, não o rótulo diagnóstico. Restrição temporária, revisável, com sigilo preservado e diálogo com o assistente.',
  pegadinha: 'Os dois extremos estão nas alternativas: inaptidão automática pelo diagnóstico e negação de qualquer restrição. A resposta está na avaliação funcional.',
  refs: ['Camargo — Psiquiatria Ocupacional', 'Código de Ética Médica'] },

{ id: 'q-4.7-011', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Vigilante sofre assalto com arma de fogo durante o turno. Semanas depois apresenta revivescências do episódio, pesadelos, evitação do local e hipervigilância, com prejuízo funcional. Sobre o quadro, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É compatível com transtorno de estresse pós-traumático relacionado ao evento ocupacional.', ok: true,
      why: 'Correta. Permite reconhecimento como agravo relacionado ao trabalho.' },
    { t: 'Transtornos mentais nunca são relacionados ao trabalho, por dependerem de vulnerabilidade individual.', ok: false,
      why: 'Errada. Constam expressamente da lista de doenças relacionadas.' },
    { t: 'É compatível com o evento, mas a ausência de lesão física afasta a caracterização de acidente.', ok: false,
      why: 'Errada. Perturbação funcional caracteriza acidente do trabalho.' },
    { t: 'É compatível, exigindo o diagnóstico que os sintomas surjam nas primeiras quarenta e oito horas.', ok: false,
      why: 'Errada. Há formas de manifestação tardia.' },
    { t: 'É compatível com o quadro, sendo o tratamento exclusivamente medicamentoso, sem psicoterapia.', ok: false,
      why: 'Errada. A psicoterapia é componente central do tratamento.' }
  ],
  comentario: 'Dois pontos jurídicos e um clínico: perturbação funcional sem lesão física é acidente do trabalho; transtorno mental pode sim ser relacionado ao trabalho; e o quadro pós-traumático combina revivescência, evitação, hiperexcitabilidade e alterações cognitivo-afetivas, com tratamento que inclui psicoterapia.',
  pegadinha: 'A exigência de lesão física para caracterizar acidente é falsa e muito repetida — inclusive por serviços de recursos humanos.',
  refs: ['Lei nº 8.213/1991 — art. 19', 'DSM-5-TR', 'De Lucca — Fatores Psicossociais e Saúde Mental no Trabalho'] },

{ id: 'q-4.7-012', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Em perícia de trabalhador afastado por transtorno mental, o perito precisa avaliar a consistência do relato. Sobre simulação e conceitos correlatos, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Simulação é produzir sintomas falsos por ganho externo, e exige demonstrar intenção e motivação.', ok: true,
      why: 'Correta. Não se presume a partir de inconsistências isoladas.' },
    { t: 'Qualquer inconsistência entre o relato e o exame autoriza concluir pela simulação do periciando.', ok: false,
      why: 'Errada. Exige-se demonstração de inconsistências objetivas e de motivação.' },
    { t: 'Simulação é produzir sintomas falsos, sendo dissimulação apenas outro nome para o mesmo fenômeno.', ok: false,
      why: 'Errada. Dissimular é ocultar sintoma existente.' },
    { t: 'A ausência de achado objetivo em exame de imagem comprova a inexistência do transtorno mental.', ok: false,
      why: 'Errada. Transtornos mentais não têm marcador de imagem.' },
    { t: 'Levantada a suspeita de simulação, o perito deve encerrar a avaliação e concluir pela capacidade.', ok: false,
      why: 'Errada. A suspeita exige investigação, não encerramento.' }
  ],
  comentario: 'Simulação: inventa ou exagera, por ganho externo. Dissimulação: esconde ou minimiza — muito comum em perícia de aptidão, quando o trabalhador teme a inaptidão. Sobressimulação: amplifica sintoma real existente. Nenhuma delas se afirma por inconsistência isolada.',
  pegadinha: 'A troca entre simulação e dissimulação é a inversão preferida da banca neste tema.',
  refs: ['Camargo — Psiquiatria Ocupacional', 'Resoluções do CFM sobre perícia médica'] },

{ id: 'q-4.7-013', tema: '4.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o retorno ao trabalho após afastamento por transtorno mental, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O retorno deve ser na mesma função e carga, pois qualquer adaptação estigmatiza o trabalhador.', ok: true,
      why: 'É a INCORRETA. Voltar ao contexto inalterado é o principal preditor de recidiva.' },
    { t: 'Se o adoecimento tem relação com a organização, devolver ao mesmo contexto tende à recidiva.', ok: false,
      why: 'Correta, portanto não é a resposta. É achado consistente da literatura.' },
    { t: 'O acompanhamento nas primeiras semanas após o retorno é parte da conduta, e não gentileza opcional.', ok: false,
      why: 'Correta, portanto não é a resposta. É quando a recaída costuma ocorrer.' },
    { t: 'A empresa deve saber quais restrições observar, sem receber o diagnóstico do trabalhador afastado.', ok: false,
      why: 'Correta, portanto não é a resposta. É o limite do que circula.' },
    { t: 'Restrições que se prolongam indicam avaliar readaptação ou reabilitação profissional do trabalhador.', ok: false,
      why: 'Correta, portanto não é a resposta. É o encaminhamento adequado.' }
  ],
  comentario: 'Retorno ao trabalho em saúde mental exige três coisas: gradualidade, mudança no determinante organizacional quando ele existe, e acompanhamento próximo nas primeiras semanas. Sigilo do diagnóstico o tempo todo.',
  pegadinha: 'A falsa usa um argumento nobre — evitar estigma — para defender exatamente o que causa recidiva.',
  refs: ['De Lucca — Fatores Psicossociais e Saúde Mental no Trabalho', 'NR-7'] },

/* ==================== 4.10 Imunizações do Trabalhador =================== */
{ id: 'q-4.10-010', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao estruturar a imunização de trabalhadores de um hospital, o médico do trabalho define as vacinas por grupo de exposição. Sobre imunização ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'A indicação decorre do risco, e na hepatite B recomenda-se verificar a resposta sorológica.', ok: true,
      why: 'Correta. Há não respondedores que exigem conduta pós-exposição específica.' },
    { t: 'Todos os trabalhadores devem receber o mesmo conjunto de vacinas, seja qual for a função exercida.', ok: false,
      why: 'Errada. A indicação é dirigida ao risco de cada função.' },
    { t: 'A indicação decorre do risco, sendo desnecessária a sorologia, pois todo vacinado está protegido.', ok: false,
      why: 'Errada. Há não respondedores mesmo após esquema completo.' },
    { t: 'A vacinação é obrigação exclusiva do sistema público, sem custo ou responsabilidade da empresa.', ok: false,
      why: 'Errada. A vacinação ocupacional é custeada pelo empregador.' },
    { t: 'A indicação decorre do risco, devendo a recusa ser ignorada e a vacina aplicada compulsoriamente.', ok: false,
      why: 'Errada. A recusa esclarecida é registrada e reabordada, não vencida à força.' }
  ],
  comentario: 'Três pilares: indicação por risco (não por lista genérica), verificação de resposta quando ela muda a conduta — hepatite B é o exemplo —, e custo do empregador. Recusa se registra, não se vence pela força.',
  pegadinha: 'A ideia de que "vacinado está protegido" ignora o não respondedor, que é justamente quem mais precisa ser identificado antes do acidente.',
  refs: ['Calendário de vacinação ocupacional — SBIm', 'NR-32', 'NR-7'] },

{ id: 'q-4.10-011', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Trabalhador rural que manipula animais e trabalha com solo procura o serviço médico. Sobre imunização nesse contexto ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Deve considerar as exposições da atividade rural, com risco de ferimentos e contato com animais.', ok: true,
      why: 'Correta. O esquema se verifica e se atualiza conforme o risco identificado.' },
    { t: 'Os trabalhadores rurais não têm indicações de imunização ocupacional específicas a considerar.', ok: false,
      why: 'Errada. Tétano, raiva e febre amarela são exemplos correntes.' },
    { t: 'Basta a vacinação recebida na infância, sem necessidade de verificar reforços na vida adulta.', ok: false,
      why: 'Errada. Reforços e esquemas específicos são necessários.' },
    { t: 'Deve considerar as exposições, substituindo a imunização os equipamentos nas atividades de risco.', ok: false,
      why: 'Errada. São medidas complementares, não substitutivas.' },
    { t: 'Deve considerar as exposições, não sendo a carteira registrada no prontuário por ser dado sensível.', ok: false,
      why: 'Errada. É informação essencial e integra o prontuário ocupacional.' }
  ],
  comentario: 'Imunização ocupacional segue o mapa de risco da atividade, exige verificação de esquema e reforços na vida adulta e nunca substitui as demais medidas de controle. O registro fica no prontuário, protegido — não no setor de pessoal.',
  pegadinha: 'A alternativa que confunde "dado sensível" com "não registrar" inverte a proteção de dados: sensível se protege, não se apaga.',
  refs: ['Calendário de vacinação ocupacional — SBIm', 'LGPD — Lei nº 13.709/2018'] },

{ id: 'q-4.10-012', tema: '4.10', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre contraindicações e eventos adversos em imunização ocupacional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Vacinas de agentes vivos exigem cautela em imunossuprimidos e gestantes.', ok: true,
      why: 'Correta. Isso torna a avaliação individual parte necessária do programa.' },
    { t: 'Reação local leve no sítio de aplicação contraindica as doses subsequentes do mesmo esquema.', ok: false,
      why: 'Errada. Reação local leve não contraindica a continuidade.' },
    { t: 'Qualquer relato de alergia do trabalhador contraindica automaticamente a vacinação indicada.', ok: false,
      why: 'Errada. Contraindica a alergia grave a componente da vacina.' },
    { t: 'Eventos adversos pós-vacinação em trabalhadores não precisam ser notificados ao sistema de vigilância.', ok: false,
      why: 'Errada. A notificação é devida e alimenta a farmacovigilância.' },
    { t: 'Doença febril leve constitui contraindicação absoluta à aplicação de qualquer vacina indicada.', ok: false,
      why: 'Errada. Doença febril leve não contraindica a vacinação.' }
  ],
  comentario: 'Contraindicação real: anafilaxia a dose anterior ou componente; e cautela com vacinas de agentes vivos em imunossuprimidos e gestantes. Falsas contraindicações — reação local leve, alergia inespecífica, doença febril leve — são as mais cobradas, porque geram perda de oportunidade de vacinação.',
  pegadinha: 'A prova gosta de listar falsas contraindicações; guarde que a maioria dos motivos usados no dia a dia para adiar vacina não se sustenta.',
  refs: ['Sociedade Brasileira de Imunizações (SBIm)', 'Ministério da Saúde — imunizações'] },

/* ==================== 5.6 Reabilitação Profissional ===================== */
{ id: 'q-5.6-010', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador afastado há oito meses por lesão de ombro com sequela definitiva é considerado incapaz para a função de auxiliar de produção, que exige elevação repetida acima da cabeça, mas mantém capacidade para outras atividades. Sobre a conduta previdenciária adequada, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É caso típico de reabilitação profissional, para retorno a atividade compatível com a residual.', ok: true,
      why: 'Correta. Visa reeducação ou readaptação, aproveitando a capacidade preservada.' },
    { t: 'É caso de incapacidade total e permanente, com indicação de aposentadoria por incapacidade.', ok: false,
      why: 'Errada. Há capacidade residual a ser aproveitada.' },
    { t: 'A alta deve ser dada de imediato para retorno à função original, já consolidada a lesão apresentada.', ok: false,
      why: 'Errada. A função original é incompatível com a limitação residual.' },
    { t: 'É caso de reabilitação, que é facultativa e depende exclusivamente da vontade do próprio trabalhador.', ok: false,
      why: 'Errada. É etapa do processo previdenciário, com participação exigida.' },
    { t: 'É caso de reabilitação, na qual a empresa não tem qualquer participação nem obrigação prevista.', ok: false,
      why: 'Errada. Informa funções, viabiliza treinamento e reintegra.' }
  ],
  comentario: 'A pergunta que resolve: há capacidade residual? Se sim, o caminho é reabilitação e readaptação, não aposentadoria por incapacidade permanente — que exige incapacidade total e insuscetível de reabilitação. A empresa participa da reintegração.',
  pegadinha: 'Confundir "incapaz para a função habitual" com "incapaz para o trabalho" é o erro central, e ele muda completamente o desfecho do caso.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999'] },

{ id: 'q-5.6-011', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao acompanhar o retorno ao trabalho de trabalhadores após afastamentos prolongados, o médico do trabalho observa que alguns casos evoluem para cronificação. Sobre os fatores que dificultam o retorno, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Fatores psicossociais e do contexto pesam tanto quanto ou mais que a gravidade da lesão.', ok: true,
      why: 'Correta. Expectativa, medo de reincidência, conflito e insegurança são determinantes.' },
    { t: 'O tempo de retorno é determinado essencialmente pela extensão da lesão anatômica apresentada.', ok: false,
      why: 'Errada. Fatores não clínicos pesam de forma comparável.' },
    { t: 'Quanto maior o tempo de afastamento, maior a chance de retorno, pela recuperação mais completa.', ok: false,
      why: 'Errada, é o oposto: afastamento longo reduz a probabilidade de retorno.' },
    { t: 'A comunicação entre serviço médico, chefia e trabalhador durante o afastamento é irrelevante ao desfecho.', ok: false,
      why: 'Errada. Manter o vínculo melhora o desfecho do retorno.' },
    { t: 'As restrições formais devem ser evitadas, pois sinalizam fragilidade e prejudicam o trabalhador.', ok: false,
      why: 'Errada. Restrição escrita é o que permite ajustar o trabalho.' }
  ],
  comentario: 'Retorno ao trabalho é fenômeno biopsicossocial. Afastamento longo é fator de risco por si só. Manter contato durante o afastamento, definir restrições claras e cuidar do contexto de retorno mudam mais o desfecho do que qualquer detalhe do exame de imagem.',
  pegadinha: 'A intuição de que "mais tempo parado = mais recuperado" é falsa e importante: a probabilidade de retorno cai com a duração do afastamento.',
  refs: ['Penteado — Perícias em DORT', 'Lei nº 8.213/1991'] },

{ id: 'q-5.6-012', tema: '5.6', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre readaptação funcional dentro da empresa, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Consiste em realocar em atividade compatível, a partir de restrições técnicas sem diagnóstico.', ok: true,
      why: 'Correta. Preserva o trabalhador de exposições incompatíveis com sua limitação.' },
    { t: 'Consiste em realocar o trabalhador, implicando redução salarial proporcional à limitação apurada.', ok: false,
      why: 'Errada. A alteração prejudicial encontra limites na proteção contratual.' },
    { t: 'Deve ser evitada, pois cria precedente para que outros trabalhadores solicitem mudança de função.', ok: false,
      why: 'Errada. A readaptação decorre de necessidade técnica, não de precedente.' },
    { t: 'Consiste em realocar, comunicando as restrições com o diagnóstico para a chefia dimensionar tarefas.', ok: false,
      why: 'Errada. Comunica-se a limitação funcional, não o diagnóstico.' },
    { t: 'Consiste em realocar o trabalhador, que uma vez readaptado não precisa mais ser reavaliado.', ok: false,
      why: 'Errada. A reavaliação periódica permanece necessária.' }
  ],
  comentario: 'A regra prática que resolve o tema: escreva restrição em linguagem de TAREFA e EXPOSIÇÃO — "não elevar membros superiores acima da linha dos ombros", "não permanecer exposto a ruído acima do nível de ação" —, nunca em linguagem de diagnóstico. E reavalie.',
  pegadinha: 'Comunicar diagnóstico "para ajudar o gestor" é a violação de sigilo mais comum e mais bem-intencionada da medicina do trabalho.',
  refs: ['NR-7', 'Código de Ética Médica', 'Lei nº 8.213/1991'] },

/* ============ 6.4 Urgências e emergências no ambiente de trabalho ======= */
{ id: 'q-6.4-010', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador sofre respingo de solução alcalina concentrada no olho durante manuseio em linha de limpeza industrial. A conduta imediata CORRETA é:',
  alts: [
    { t: 'Irrigação abundante e prolongada, iniciada no local antes mesmo do transporte da vítima.', ok: true,
      why: 'Correta. O tempo até o início da irrigação é o principal determinante do dano.' },
    { t: 'Aguardar a chegada ao serviço de emergência para irrigar com solução apropriada e sob supervisão.', ok: false,
      why: 'Errada. O atraso determina a gravidade da lesão final.' },
    { t: 'Neutralizar o álcali com solução ácida diluída, de modo a interromper a reação química no tecido.', ok: false,
      why: 'Errada. A neutralização libera calor e agrava a lesão.' },
    { t: 'Ocluir o olho com curativo compressivo e encaminhar ao especialista, sem irrigação prévia no local.', ok: false,
      why: 'Errada. A oclusão mantém o agente em contato com a córnea.' },
    { t: 'Aplicar colírio anestésico e corticoide antes de qualquer irrigação, para permitir a abertura ocular.', ok: false,
      why: 'Errada. A irrigação é imediata e não espera medicação.' }
  ],
  comentario: 'Queimadura química ocular: irrigar já, no local, em grande volume e por tempo prolongado. Álcalis penetram mais profundamente que ácidos e têm pior prognóstico. Nunca neutralizar, nunca ocluir antes de irrigar.',
  pegadinha: 'A neutralização parece raciocínio químico correto e é justamente a conduta que agrava a lesão.',
  refs: ['Greenberg — Occupational Emergency Medicine'] },

{ id: 'q-6.4-011', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador é encontrado inconsciente no fundo de um tanque de armazenamento. Um colega desce imediatamente para socorrê-lo e também perde a consciência. Sobre esse cenário, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É espaço confinado: a maioria das mortes ocorre entre socorristas improvisados.', ok: true,
      why: 'Correta. O resgate exige equipe treinada, proteção adequada e avaliação da atmosfera.' },
    { t: 'O colega agiu corretamente, pois o socorro imediato é prioridade absoluta em qualquer emergência.', ok: false,
      why: 'Errada. Entrar sem proteção produz a segunda vítima.' },
    { t: 'É espaço confinado, indicando a perda de consciência intoxicação por gás, e não falta de oxigênio.', ok: false,
      why: 'Errada. A deficiência de oxigênio é causa frequente e sem aviso.' },
    { t: 'É espaço confinado, sendo a máscara semifacial com filtro químico suficiente para o resgate.', ok: false,
      why: 'Errada. Filtro não supre oxigênio; exige-se ar fornecido.' },
    { t: 'É espaço confinado, sendo permissão e vigia formalidades dispensáveis em tanques de pequeno porte.', ok: false,
      why: 'Errada. O porte não afasta os requisitos.' }
  ],
  comentario: 'Espaço confinado mata em dupla: a vítima e quem tenta salvá-la. Guarde a sequência — avaliar a atmosfera antes de entrar, permissão de entrada, vigia do lado de fora, plano de resgate e equipamento de adução de ar. Deficiência de oxigênio não dá aviso.',
  pegadinha: 'A alternativa que elogia o socorro imediato explora o instinto correto na situação errada: segurança da cena vem antes.',
  refs: ['NR-33', 'Greenberg — Occupational Emergency Medicine'] },

{ id: 'q-6.4-012', tema: '6.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a organização do atendimento a emergências em ambiente de trabalho, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'Por serem eventos raros, o plano pode ser escrito e arquivado, sem simulados periódicos.', ok: true,
      why: 'É a INCORRETA. Plano nunca testado falha no primeiro uso real.' },
    { t: 'O plano deve definir quem aciona o socorro, por quais meios e qual será a rota de remoção.', ok: false,
      why: 'Correta, portanto não é a resposta. São elementos essenciais do plano.' },
    { t: 'A disponibilidade de desfibrilador e de pessoal treinado melhora o desfecho da parada cardíaca.', ok: false,
      why: 'Correta, portanto não é a resposta. O tempo até o choque decide.' },
    { t: 'A composição do material de primeiros socorros deve refletir os riscos específicos da atividade.', ok: false,
      why: 'Correta, portanto não é a resposta. Material padrão não cobre riscos próprios.' },
    { t: 'O registro do atendimento é necessário, inclusive para eventual caracterização de acidente do trabalho.', ok: false,
      why: 'Correta, portanto não é a resposta. O registro sustenta o reconhecimento.' }
  ],
  comentario: 'Plano de emergência só funciona se for treinado. Os itens que caem: definição de papéis e fluxo de acionamento, acesso a desfibrilador com pessoal capacitado, material compatível com os riscos da atividade e registro de todo atendimento.',
  pegadinha: 'A falsa usa a raridade do evento como argumento para dispensar o treino, quando é ela que torna o treino indispensável.',
  refs: ['Greenberg — Occupational Emergency Medicine', 'NR-1'] },

/* ============= 7.1 Legislação Trabalhista aplicável à MT ================ */
{ id: 'q-7.1-010', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma trabalhadora comunica gravidez à empresa e exerce atividade em setor classificado como insalubre. O gestor pergunta ao médico do trabalho como proceder. A orientação CORRETA é:',
  alts: [
    { t: 'Deve ser afastada das atividades insalubres conforme o grau, sem prejuízo da remuneração.', ok: true,
      why: 'Correta. A permanência em grau menor depende de atestado que assegure ausência de risco.' },
    { t: 'A gravidez, por si, torna a trabalhadora inapta, cabendo afastamento por benefício previdenciário.', ok: false,
      why: 'Errada. Afasta-se da exposição, não do trabalho.' },
    { t: 'A transferência de função autoriza a redução proporcional da remuneração, inclusive do adicional.', ok: false,
      why: 'Errada. A transferência se dá sem prejuízo da remuneração.' },
    { t: 'Nenhuma providência é necessária enquanto a trabalhadora não apresentar sintomas relacionados.', ok: false,
      why: 'Errada. A proteção é preventiva e não espera dano.' },
    { t: 'O afastamento das atividades insalubres só se aplica durante o último trimestre da gestação.', ok: false,
      why: 'Errada. Aplica-se durante toda a gestação.' }
  ],
  comentario: 'Guarde a estrutura: afastamento da exposição conforme o grau de insalubridade, transferência para função compatível sem prejuízo salarial, e possibilidade de permanência em graus menores mediante atestado que assegure ausência de risco. Gravidez afasta da EXPOSIÇÃO, não do trabalho.',
  pegadinha: 'A alternativa que restringe a proteção ao último trimestre inverte a janela de maior vulnerabilidade embrionária.',
  refs: ['CLT — Capítulo V do Título II', 'NR-15'] },

{ id: 'q-7.1-011', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador pergunta se pode receber cumulativamente os adicionais de insalubridade e de periculosidade, já que sua função o expõe a ruído acima do limite e também a inflamáveis. Sobre os adicionais, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Havendo direito a ambos, o empregado opta por um, e cada um depende de perícia técnica.', ok: true,
      why: 'Correta. Eliminada ou neutralizada a condição, cessa o respectivo adicional.' },
    { t: 'Os adicionais são cumulativos sempre que houver exposição simultânea a agentes de natureza distinta.', ok: false,
      why: 'Errada. A regra é a não cumulação, com direito de opção.' },
    { t: 'A percepção do adicional torna a exposição regular e dispensa a adoção de medidas de controle.', ok: false,
      why: 'Errada. O dever de eliminar ou neutralizar independe do pagamento.' },
    { t: 'A caracterização depende apenas da declaração do empregador no registro do empregado exposto.', ok: false,
      why: 'Errada. Depende de perícia técnica.' },
    { t: 'Uma vez concedido, o adicional integra definitivamente o salário e não pode mais cessar.', ok: false,
      why: 'Errada. Cessa com a eliminação ou neutralização da condição.' }
  ],
  comentario: 'Três verdades sobre adicionais: opta-se por um quando ambos cabem; a caracterização é pericial; e o adicional cessa quando a condição cessa. E a quarta, que é a mais importante na prática médica: pagar adicional não é medida de proteção.',
  pegadinha: 'A ideia de que o adicional "regulariza" a exposição aparece com frequência em defesa de empresas e é insustentável.',
  refs: ['CLT — arts. 189 a 195', 'NR-15', 'NR-16'] },

{ id: 'q-7.1-012', tema: '7.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as obrigações previstas na legislação trabalhista em matéria de segurança e medicina do trabalho, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'O custo dos exames ocupacionais pode ser rateado com o empregado se houver acordo coletivo.', ok: true,
      why: 'É a INCORRETA. Os exames correm por conta exclusiva do empregador.' },
    { t: 'Cabe ao empregador instruir os empregados quanto às precauções contra acidentes e doenças.', ok: false,
      why: 'Correta, portanto não é a resposta. É dever legal expresso.' },
    { t: 'A recusa injustificada em observar as instruções e usar o equipamento fornecido é ato faltoso.', ok: false,
      why: 'Correta, portanto não é a resposta. Consta expressamente da lei.' },
    { t: 'Diante de risco grave e iminente, pode haver interdição ou embargo pela autoridade competente.', ok: false,
      why: 'Correta, portanto não é a resposta. São medidas previstas.' },
    { t: 'A empresa deve comunicar as doenças profissionais e as produzidas por condições especiais de trabalho.', ok: false,
      why: 'Correta, portanto não é a resposta. É obrigação legal.' }
  ],
  comentario: 'Regra sem exceção: nenhum custo de saúde e segurança se transfere ao trabalhador — exames, equipamentos de proteção e treinamentos são do empregador, e negociação coletiva não pode reduzir esse patamar.',
  pegadinha: 'Invocar acordo coletivo para legitimar o rateio soa juridicamente sofisticado e esbarra no limite do que é negociável.',
  refs: ['CLT — Capítulo V do Título II', 'NR-6', 'NR-7'] },

/* ============= 7.3 Legislação Sanitária aplicável à MT ================== */
{ id: 'q-7.3-010', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma equipe de vigilância sanitária municipal atua em um estabelecimento onde há risco à saúde dos trabalhadores e da população do entorno. Sobre a interface entre vigilância sanitária e saúde do trabalhador, assinale a alternativa CORRETA:',
  alts: [
    { t: 'As competências se somam: a sanitária alcança ambientes e processos, articulada com a do trabalho.', ok: true,
      why: 'Correta. Uma não exclui a outra; a articulação amplia a intervenção.' },
    { t: 'A competência sobre ambientes de trabalho é exclusiva da inspeção, vedada a atuação sanitária.', ok: false,
      why: 'Errada. A competência sanitária decorre da lei orgânica da saúde.' },
    { t: 'A atuação sanitária se limita à higiene de alimentos e instalações, sem alcançar riscos ocupacionais.', ok: false,
      why: 'Errada. Alcança ambientes que exponham a saúde de pessoas.' },
    { t: 'Autuado pela inspeção do trabalho, o estabelecimento não pode sofrer medida sanitária pelo mesmo fato.', ok: false,
      why: 'Errada. As competências coexistem e se somam.' },
    { t: 'As competências se somam, dependendo a interdição sanitária de autorização judicial em qualquer caso.', ok: false,
      why: 'Errada. É medida administrativa autônoma.' }
  ],
  comentario: 'A chave é entender que existem esferas paralelas: sanitária (saúde), trabalhista (inspeção do trabalho), previdenciária e ambiental. Elas se somam. A prova gosta de sugerir exclusividade de uma delas — e a resposta é quase sempre a complementaridade.',
  pegadinha: 'A ideia de que autuação numa esfera impede atuação em outra confunde autonomia administrativa com bis in idem penal.',
  refs: ['Lei nº 8.080/1990', 'Política Nacional de Saúde do Trabalhador e da Trabalhadora'] },

{ id: 'q-7.3-011', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a notificação compulsória de agravos relacionados ao trabalho no âmbito da legislação sanitária, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É obrigação de serviços públicos e privados, decorre da suspeita e é exceção legal ao sigilo.', ok: true,
      why: 'Correta. Não exige confirmação diagnóstica para ser realizada.' },
    { t: 'Só se notifica após a confirmação diagnóstica do agravo relacionado ao trabalho identificado.', ok: false,
      why: 'Errada. A notificação se faz por suspeita.' },
    { t: 'É obrigação legal que alcança apenas os serviços públicos de saúde da rede assistencial local.', ok: false,
      why: 'Errada. Alcança também os privados.' },
    { t: 'É obrigação legal, dependendo sua realização de autorização expressa do trabalhador atendido.', ok: false,
      why: 'Errada. É exceção legal ao sigilo e independe de autorização.' },
    { t: 'É obrigação legal e substitui a comunicação de acidente do trabalho para fins previdenciários.', ok: false,
      why: 'Errada. São registros distintos, com finalidades próprias.' }
  ],
  comentario: 'Notificação: instrumento sanitário, por suspeita, obrigatória em serviço público e privado, exceção ao sigilo. Comunicação de acidente: instrumento previdenciário, garante direitos. Convivem — e essa distinção cai com frequência.',
  pegadinha: 'Condicionar a notificação ao consentimento do trabalhador troca dever legal por autonomia, em um dos poucos pontos em que a lei já fez essa ponderação.',
  refs: ['Lei nº 8.080/1990', 'Lista Nacional de Notificação Compulsória — Ministério da Saúde'] },

{ id: 'q-7.3-012', tema: '7.3', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria manipula produto químico sujeito a controle especial. Sobre o marco sanitário aplicável, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Incide sobre produção, armazenamento, transporte e descarte, coexistindo com as trabalhistas.', ok: true,
      why: 'Correta. As obrigações sanitárias e as de proteção do trabalhador se somam.' },
    { t: 'O cumprimento das normas trabalhistas de proteção dispensa as obrigações sanitárias do produto.', ok: false,
      why: 'Errada. São conjuntos distintos e cumulativos.' },
    { t: 'A ficha com informações de segurança do produto é documento de uso exclusivo do setor de compras.', ok: false,
      why: 'Errada. É documento de consulta operacional no local de uso.' },
    { t: 'O descarte de resíduos perigosos é matéria ambiental, estranha ao campo da saúde do trabalhador.', ok: false,
      why: 'Errada. Quem manuseia o resíduo é trabalhador exposto.' },
    { t: 'Produtos com registro sanitário estão automaticamente isentos de medidas de controle no trabalho.', ok: false,
      why: 'Errada. O registro não afasta o gerenciamento do risco ocupacional.' }
  ],
  comentario: 'Regra geral do tema: cumprir uma esfera não dispensa a outra. E um detalhe prático que a prova cobra: a ficha de informações de segurança do produto químico é instrumento de trabalho do médico e da higiene ocupacional, não papel de almoxarifado.',
  pegadinha: 'Confundir registro sanitário do produto com segurança do uso é o mesmo erro de confundir certificação com desempenho.',
  refs: ['Lei nº 8.080/1990', 'NR-9', 'Buschinelli — Toxicologia Ocupacional'] },

/* ============ 7.7 Resoluções do Conselho Federal de Medicina ============ */
{ id: 'q-7.7-010', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa contratante exige que o médico do trabalho entregue os prontuários ocupacionais ao setor de recursos humanos ao término do contrato de prestação de serviços. Sobre a conduta, à luz das normas do conselho profissional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Devem ficar sob guarda de médico, com transferência a outro médico responsável.', ok: true,
      why: 'Correta. Nunca a setor administrativo da empresa contratante.' },
    { t: 'Encerrado o contrato, os documentos pertencem à empresa, que pode arquivá-los como preferir.', ok: false,
      why: 'Errada. A guarda é responsabilidade médica, com sigilo preservado.' },
    { t: 'Os prontuários podem ser destruídos ao fim do contrato, já encerrado o vínculo assistencial.', ok: false,
      why: 'Errada. Os prazos de guarda são longos e obrigatórios.' },
    { t: 'A entrega ao setor administrativo é aceitável desde que os documentos sejam devidamente lacrados.', ok: false,
      why: 'Errada. A guarda deve permanecer com médico responsável.' },
    { t: 'O sigilo dos prontuários se extingue com o fim do vínculo empregatício daquele trabalhador.', ok: false,
      why: 'Errada. Persiste inclusive após a morte do paciente.' }
  ],
  comentario: 'Prontuário ocupacional é documento médico: guarda por médico, prazo de guarda a observar, sucessão entre médicos e sigilo que não se extingue com o fim do contrato nem do vínculo empregatício. A empresa paga o serviço; não é dona do conteúdo clínico.',
  pegadinha: 'A alternativa dos documentos lacrados oferece uma solução operacional para um problema que é de titularidade, não de embalagem.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM sobre prontuário e sobre atendimento ao trabalhador', 'LGPD'] },

{ id: 'q-7.7-011', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'O médico do trabalho de uma empresa é procurado por um empregado que solicita atestado para justificar falta ocorrida na semana anterior, quando esteve doente mas não procurou atendimento. Sobre a conduta, assinale a alternativa CORRETA:',
  alts: [
    { t: 'O atestado deve refletir o que o médico constatou; atestar o que não avaliou é falsidade.', ok: true,
      why: 'Correta. A motivação compassiva não altera a natureza do ato.' },
    { t: 'A retroatividade é admissível desde que o trabalhador declare por escrito que estava doente.', ok: false,
      why: 'Errada. Declaração do paciente não substitui a avaliação médica.' },
    { t: 'O médico do trabalho da empresa não pode emitir atestado em nenhuma hipótese ao empregado.', ok: false,
      why: 'Errada. Pode emitir sobre o que efetivamente avaliou.' },
    { t: 'O atestado deve conter obrigatoriamente o diagnóstico codificado para ser aceito pela empresa.', ok: false,
      why: 'Errada. Depende de autorização expressa do paciente.' },
    { t: 'Cabe ao médico do trabalho validar ou recusar atestados de assistentes por avaliação retrospectiva.', ok: false,
      why: 'Errada. A divergência exige avaliação e fundamentação, não recusa unilateral.' }
  ],
  comentario: 'Duas linhas fixas: o atestado declara o que foi constatado, e o diagnóstico só sai com autorização do paciente ou por dever legal. A pressão para "resolver" a falta do colega é justamente a situação em que essas linhas são testadas.',
  pegadinha: 'A alternativa que exige o código diagnóstico no atestado reproduz uma exigência empresarial comum e ilegítima.',
  refs: ['Código de Ética Médica', 'Resoluções do CFM sobre atestado médico'] },

{ id: 'q-7.7-012', tema: '7.7', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as normas do conselho profissional aplicáveis ao médico que atende trabalhadores, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'Por ser contratado pela empresa, responde às determinações técnicas dela quanto à aptidão.', ok: true,
      why: 'É a INCORRETA. A autonomia técnica não se subordina ao contratante.' },
    { t: 'É vedado revelar ao empregador o diagnóstico do trabalhador sem autorização expressa deste.', ok: false,
      why: 'Correta, portanto não é a resposta. É o limite do sigilo.' },
    { t: 'O médico deve comunicar ao trabalhador os achados e as repercussões sobre a saúde dele.', ok: false,
      why: 'Correta, portanto não é a resposta. É dever de informação.' },
    { t: 'É vedado exercer simultaneamente, no mesmo caso, as funções de perito e de assistente de parte.', ok: false,
      why: 'Correta, portanto não é a resposta. As funções são inconciliáveis.' },
    { t: 'O médico deve notificar situações de risco à saúde coletiva identificadas no ambiente de trabalho.', ok: false,
      why: 'Correta, portanto não é a resposta. É dever de comunicação de riscos.' }
  ],
  comentario: 'O eixo ético da especialidade: quem paga não manda no juízo técnico. A autonomia da conclusão de aptidão, o sigilo do diagnóstico perante o empregador, o direito do trabalhador à informação e a incompatibilidade entre perito e assistente formam o núcleo do que a banca cobra em ética.',
  pegadinha: 'Enunciado de "assinale a INCORRETA": a falsa é a que soa como realismo contratual e é justamente o que a norma proíbe.',
  refs: ['Código de Ética Médica', 'Resolução CFM sobre normas para médicos que atendem o trabalhador'] }

);
