/* 6.1 Exames Médicos Ocupacionais (PCMSO) — bloco de aprofundamento.
   Questões AUTORAIS. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(

{ id: 'q-6.1-020', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador é admitido em 3 de março e, por atraso na agenda da clínica, realiza o exame admissional em 12 de março, já tendo iniciado suas atividades em linha de produção com exposição a ruído. O médico coordenador é questionado sobre a regularidade. A resposta CORRETA é:',
  alts: [
    { t: 'Houve irregularidade: o admissional precede a assunção das atividades pelo trabalhador.', ok: true,
      why: 'Correta. A finalidade é avaliar a compatibilidade antes de iniciar a exposição.' },
    { t: 'Não houve irregularidade, pois a realização em até quinze dias é regular sem intercorrência.', ok: false,
      why: 'Errada. O exame deve preceder o início das atividades.' },
    { t: 'Houve irregularidade meramente formal, sem repercussão prática, por estar o trabalhador assintomático.', ok: false,
      why: 'Errada. Perde-se a linha de base e a avaliação prévia de compatibilidade.' },
    { t: 'Não houve irregularidade, pois o admissional é dispensável havendo atestado de emprego anterior.', ok: false,
      why: 'Errada. O exame é dirigido aos riscos da nova função.' },
    { t: 'Houve irregularidade, cuja responsabilidade é do trabalhador, que deveria ter comparecido antes.', ok: false,
      why: 'Errada. A obrigação de realizar o exame é do empregador.' }
  ],
  comentario: 'Três exames são PRÉVIOS por natureza: admissional (antes de assumir), retorno ao trabalho (antes de reassumir) e mudança de riscos ocupacionais (antes da mudança). O periódico e o demissional têm lógica temporal distinta.',
  pegadinha: 'A ideia de uma "tolerância de alguns dias" para o admissional não existe e é oferecida com frequência.',
  refs: ['NR-7', 'CLT — Capítulo V do Título II'] },

{ id: 'q-6.1-021', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadora retorna após 45 dias de afastamento por licença-maternidade. O setor de pessoal pergunta se é necessário exame antes do retorno. A orientação CORRETA é:',
  alts: [
    { t: 'É devido após ausência prolongada por doença, acidente ou parto, antes de reassumir a função.', ok: true,
      why: 'Correta. A licença-maternidade está expressamente entre as hipóteses.' },
    { t: 'É devido após afastamento por doença ou acidente, não se aplicando à licença-maternidade gozada.', ok: false,
      why: 'Errada. O parto consta expressamente entre as hipóteses.' },
    { t: 'É devido, podendo ser feito nos primeiros dias do retorno se a função não for de risco.', ok: false,
      why: 'Errada. Deve preceder a retomada das atividades.' },
    { t: 'É devido, bastando a apresentação da alta do obstetra, o que dispensa o exame ocupacional.', ok: false,
      why: 'Errada. A alta assistencial não substitui a avaliação de aptidão.' },
    { t: 'É devido antes de reassumir a função e substitui o exame periódico devido no mesmo ano.', ok: false,
      why: 'Errada. São exames com finalidades e periodicidades distintas.' }
  ],
  comentario: 'Exame de retorno ao trabalho: cabível após ausência prolongada por doença, acidente OU parto, e sempre realizado antes de reassumir as funções. Alta assistencial não substitui avaliação ocupacional.',
  pegadinha: 'Excluir o parto das hipóteses é o erro mais comum, porque a licença-maternidade não é vista como "afastamento por saúde".',
  refs: ['NR-7'] },

{ id: 'q-6.1-022', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador do setor administrativo será transferido para a área de produção, onde passará a ser exposto a ruído e a agentes químicos. Sobre a avaliação médica, é CORRETO afirmar:',
  alts: [
    { t: 'É devido exame por mudança de riscos, antes da efetivação, com nova condição basal registrada.', ok: true,
      why: 'Correta. Os exames complementares são definidos pelos novos riscos.' },
    { t: 'Nenhum exame é devido, pois o trabalhador já está empregado e tem admissional válido na empresa.', ok: false,
      why: 'Errada. A mudança de risco é fato gerador de novo exame.' },
    { t: 'É devido apenas se a mudança implicar alteração formal de cargo e de salário do trabalhador.', ok: false,
      why: 'Errada. O critério é a mudança de risco, não a de cargo.' },
    { t: 'É devido exame por mudança de riscos, que pode ser feito em até trinta dias da transferência.', ok: false,
      why: 'Errada. Feito depois, perde a função de linha de base.' },
    { t: 'É devido, bastando atualizar o atestado anterior com o acréscimo dos novos riscos por escrito.', ok: false,
      why: 'Errada. Exige-se avaliação dirigida ao novo risco.' }
  ],
  comentario: 'Guarde o gatilho: mudança de RISCOS ocupacionais, não de cargo. Alguém pode mudar de cargo sem mudar de exposição — e mudar de exposição sem mudar de cargo, por alteração do processo produtivo. É a exposição que manda.',
  pegadinha: 'Vincular o exame à formalidade contratual (cargo, salário) desloca o critério do risco para o papel.',
  refs: ['NR-7', 'NR-1'] },

{ id: 'q-6.1-023', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao revisar os atestados de saúde ocupacional emitidos pela clínica contratada, o médico coordenador identifica documentos que trazem o código diagnóstico do trabalhador no campo de observações. Sobre o conteúdo do atestado, é CORRETO afirmar:',
  alts: [
    { t: 'Deve trazer identificação, função, riscos, exames com datas, conclusão e médico responsável.', ok: true,
      why: 'Correta. Jamais o diagnóstico, que permanece no prontuário.' },
    { t: 'Deve trazer riscos e conclusão, e o diagnóstico sempre que houver restrição a ser compreendida.', ok: false,
      why: 'Errada. Comunica-se a limitação funcional, não o diagnóstico.' },
    { t: 'Deve trazer riscos e conclusão, podendo o diagnóstico constar se o trabalhador autorizar verbalmente.', ok: false,
      why: 'Errada. A autorização, quando cabível, é expressa e não muda o conteúdo do documento.' },
    { t: 'Deve trazer identificação e conclusão, sendo emitido em via única, arquivada pela empresa.', ok: false,
      why: 'Errada. Uma via é entregue ao trabalhador.' },
    { t: 'Deve trazer identificação, exames e conclusão, sendo dispensável a identificação dos riscos.', ok: false,
      why: 'Errada. Os riscos avaliados integram o conteúdo obrigatório.' }
  ],
  comentario: 'O atestado ocupacional é a fronteira entre o que a empresa pode e não pode saber: identificação, função, riscos, exames com datas, conclusão de aptidão e o médico responsável. Diagnóstico, nunca. E o trabalhador recebe a sua via.',
  pegadinha: 'A justificativa de que "a empresa precisa entender a restrição" é a mais usada para incluir diagnóstico e é sempre indevida.',
  refs: ['NR-7', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-6.1-024', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa de grau de risco elevado pergunta ao médico coordenador quais exames complementares devem compor a bateria dos trabalhadores expostos a determinado agente químico. A orientação CORRETA é:',
  alts: [
    { t: 'Definem-se pelos riscos do inventário e pelo agente, com periodicidade compatível.', ok: true,
      why: 'Correta. Não existe bateria padrão aplicável indistintamente a todos.' },
    { t: 'Definem-se por bateria única e ampla para todos os empregados, garantindo cobertura máxima.', ok: false,
      why: 'Errada. Exame sem indicação não vigia a exposição e gera achado incidental.' },
    { t: 'Definem-se pelos riscos, sendo facultativos quando a empresa fornece proteção individual.', ok: false,
      why: 'Errada. A vigilância da saúde independe do fornecimento de equipamento.' },
    { t: 'Definem-se pelo laboratório contratado, que conhece melhor os métodos analíticos disponíveis.', ok: false,
      why: 'Errada. A indicação é técnica e cabe ao médico coordenador.' },
    { t: 'Definem-se pelos riscos, com periodicidade sempre anual, qualquer que seja o agente e o nível.', ok: false,
      why: 'Errada. A periodicidade decorre do agente e do nível de exposição.' }
  ],
  comentario: 'A cadeia é: gerenciamento de riscos identifica a exposição → o programa médico define quem monitorar, com que exame e com que periodicidade. Sem essa articulação, o programa vira bateria genérica — cara, invasiva e cega ao risco real.',
  pegadinha: 'A "bateria ampla para todos" soa como zelo e é exemplo clássico de dano por excesso de intervenção.',
  refs: ['NR-7', 'NR-9', 'Ferreira Junior — Rastreamento de doenças'] },

{ id: 'q-6.1-025', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador é considerado apto com restrição para não operar máquinas em movimento por período de três meses. O gerente devolve o atestado ao serviço médico dizendo que "restrição não serve, ou é apto ou é inapto". A conduta CORRETA é:',
  alts: [
    { t: 'Manter a conclusão: a aptidão com restrição é instrumento técnico legítimo e frequente.', ok: true,
      why: 'Correta. A conclusão sobre aptidão é ato médico com autonomia técnica.' },
    { t: 'Reemitir o atestado como apto, registrando a restrição apenas no prontuário do trabalhador.', ok: false,
      why: 'Errada. A restrição precisa constar para que a empresa a implemente.' },
    { t: 'Reemitir o atestado como inapto, dado não ser possível concluir por aptidão com restrição.', ok: false,
      why: 'Errada. A aptidão com restrição é conclusão prevista e adequada.' },
    { t: 'Acatar a orientação do gerente, pois é a empresa quem contrata o serviço médico prestado.', ok: false,
      why: 'Errada. A conclusão técnica não se subordina ao contratante.' },
    { t: 'Encaminhar a decisão ao setor de pessoal para arbitrar entre a aptidão e a inaptidão do caso.', ok: false,
      why: 'Errada. A conclusão é ato médico e não se delega.' }
  ],
  comentario: 'Aptidão com restrição é ferramenta cotidiana da especialidade e a alternativa ao falso dilema entre apto e inapto. Escreva a restrição em linguagem de tarefa e exposição, com prazo de reavaliação — assim o gestor consegue realocar sem conhecer o diagnóstico.',
  pegadinha: 'Os dois extremos são oferecidos juntos: apagar a restrição ou declarar inaptidão. Ambos prejudicam o trabalhador.',
  refs: ['NR-7', 'Código de Ética Médica'] },

{ id: 'q-6.1-026', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o relatório analítico do programa de controle médico de saúde ocupacional, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'Por conter dados de saúde, deve identificar nominalmente quem apresentou alterações.', ok: true,
      why: 'É a INCORRETA. O relatório é consolidado, sem identificação individual.' },
    { t: 'Deve analisar a ocorrência dos agravos e a evolução dos indicadores ao longo do período avaliado.', ok: false,
      why: 'Correta, portanto não é a resposta. É o conteúdo esperado do relatório.' },
    { t: 'Deve apontar a necessidade de mudança nas medidas de controle quando os achados assim indicarem.', ok: false,
      why: 'Correta, portanto não é a resposta. É o que fecha o ciclo com o ambiente.' },
    { t: 'É de responsabilidade técnica do médico coordenador do programa de controle médico da empresa.', ok: false,
      why: 'Correta, portanto não é a resposta. A responsabilidade técnica é dele.' },
    { t: 'Deve ser elaborado ainda que não tenha havido nenhum caso de doença ocupacional no período.', ok: false,
      why: 'Correta, portanto não é a resposta. A ausência de casos também é resultado.' }
  ],
  comentario: 'O relatório analítico é o elo entre o que a saúde detecta e o que o controle de risco precisa corrigir. Sempre agregado, sempre sob responsabilidade médica, sempre com conclusão sobre a necessidade de mudar as medidas de controle.',
  pegadinha: 'Enunciado de "assinale a INCORRETA": a falsa invoca uma necessidade gerencial real para justificar violação de sigilo.',
  refs: ['NR-7', 'Código de Ética Médica', 'LGPD'] },

{ id: 'q-6.1-027', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa encerra o contrato com a clínica que executava o programa de controle médico e pergunta o que fazer com os prontuários ocupacionais e por quanto tempo guardá-los. A orientação CORRETA é:',
  alts: [
    { t: 'Devem ser guardados por prazo prolongado sob responsabilidade médica, com sucessão prevista.', ok: true,
      why: 'Correta. O descarte prematuro elimina prova essencial de nexo futuro.' },
    { t: 'Podem ser descartados assim que se encerra o contrato de prestação de serviços com a empresa.', ok: false,
      why: 'Errada. A guarda deve ser transferida a outro médico responsável.' },
    { t: 'Devem ser entregues ao setor de pessoal, que passa a ser o responsável pela guarda dos registros.', ok: false,
      why: 'Errada. A guarda é de responsabilidade médica.' },
    { t: 'Podem ser descartados assim que o trabalhador é desligado da empresa e homologada a rescisão.', ok: false,
      why: 'Errada. É depois do vínculo que o registro se torna essencial.' },
    { t: 'Devem ser guardados, autorizando a digitalização o descarte imediato do original sem cuidados.', ok: false,
      why: 'Errada. A guarda digital exige integridade, autenticidade e segurança.' }
  ],
  comentario: 'O prazo de guarda prolongado dos registros de saúde ocupacional existe por uma razão prática: câncer ocupacional, pneumoconioses e perdas auditivas se manifestam muito depois do vínculo. Sem prontuário, o trabalhador perde o nexo por falta de prova.',
  pegadinha: 'Confira a redação vigente da norma quanto ao prazo exato de guarda — ele já foi objeto de alteração e a prova costuma cobrar o conceito de guarda prolongada.',
  refs: ['NR-7', 'Código de Ética Médica', 'Resoluções do CFM sobre prontuário'] },

{ id: 'q-6.1-028', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Ao elaborar o programa de controle médico de uma empresa, o médico coordenador constata que o inventário de riscos está desatualizado e não contempla os agentes efetivamente presentes em dois setores. A conduta CORRETA é:',
  alts: [
    { t: 'Comunicar formalmente a inconsistência e articular a atualização do inventário de riscos.', ok: true,
      why: 'Correta. Base inexata produziria acompanhamento inadequado dos expostos.' },
    { t: 'Elaborar o programa médico com base apenas nos exames que a empresa já vinha realizando.', ok: false,
      why: 'Errada. Reproduz a rotina existente sem correspondência com os riscos reais.' },
    { t: 'Elaborar o programa de forma autônoma, pois ele independe do inventário de riscos da empresa.', ok: false,
      why: 'Errada. O programa médico decorre dos riscos identificados.' },
    { t: 'Elaborar ele próprio o inventário de riscos, substituindo a equipe tecnicamente responsável.', ok: false,
      why: 'Errada. Cabe articular a correção, não assumir a atribuição alheia.' },
    { t: 'Registrar a inconsistência apenas no prontuário dos trabalhadores afetados pela exposição.', ok: false,
      why: 'Errada. A comunicação formal é o que dispara a correção do inventário.' }
  ],
  comentario: 'Programa médico não é lista de exames: é a resposta de saúde ao mapa de riscos. Inventário errado gera programa errado. E há um ponto de prova relevante: comunicar formalmente a inconsistência é o que documenta a atuação do médico.',
  pegadinha: 'Assumir a elaboração do inventário parece proatividade e confunde as responsabilidades entre o serviço médico e o gerenciamento de riscos.',
  refs: ['NR-7', 'NR-1', 'NR-9'] },

{ id: 'q-6.1-029', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma rede de lojas com trabalhadores exclusivamente administrativos, de grau de risco baixo, questiona se precisa de programa de controle médico e de exames ocupacionais. A orientação CORRETA é:',
  alts: [
    { t: 'Há tratamento diferenciado por porte e grau de risco, mas não dispensa integral das obrigações.', ok: true,
      why: 'Correta. Riscos ergonômicos e psicossociais existem também em atividades administrativas.' },
    { t: 'Empresas de risco baixo com atividades administrativas ficam integralmente dispensadas do programa.', ok: false,
      why: 'Errada. Há simplificação, não dispensa das obrigações essenciais.' },
    { t: 'Há tratamento simplificado, bastando o exame admissional e sendo dispensados os demais tipos.', ok: false,
      why: 'Errada. Os demais exames permanecem devidos conforme o risco.' },
    { t: 'Há tratamento simplificado, não se aplicando riscos ergonômicos e psicossociais ao administrativo.', ok: false,
      why: 'Errada. São justamente os riscos predominantes nessas atividades.' },
    { t: 'Há tratamento simplificado, dependendo a dispensa apenas do número de empregados da empresa.', ok: false,
      why: 'Errada. Porte e grau de risco compõem o critério.' }
  ],
  comentario: 'Porte pequeno e risco baixo geram simplificação, jamais isenção. E o erro prático mais comum é supor que escritório não tem risco: ergonômico e psicossocial estão lá, e são os que mais afastam nesse perfil de empresa.',
  pegadinha: 'A alternativa da dispensa integral é a expectativa de quase todo empregador de pequeno porte.',
  refs: ['NR-1', 'NR-7', 'NR-17', 'Teixeira — Gestão da Saúde no Trabalho'] },

{ id: 'q-6.1-030', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o exame demissional, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É devido no prazo da homologação, com dispensa se o último exame for recente conforme a norma.', ok: true,
      why: 'Correta. O intervalo de dispensa varia conforme o grau de risco da atividade.' },
    { t: 'É sempre obrigatório na rescisão, sem qualquer hipótese de dispensa prevista na norma vigente.', ok: false,
      why: 'Errada. Há hipótese de dispensa por exame clínico recente.' },
    { t: 'É sempre dispensável quando o desligamento decorre de pedido do próprio trabalhador da empresa.', ok: false,
      why: 'Errada. A dispensa não depende da iniciativa do desligamento.' },
    { t: 'É devido no prazo da homologação, com a finalidade de comprovar ausência de doença adquirida.', ok: false,
      why: 'Errada. A finalidade é documentar o estado de saúde, não atestar ausência.' },
    { t: 'É devido, podendo ser realizado a qualquer tempo depois do desligamento, sem prazo definido.', ok: false,
      why: 'Errada. Há prazo vinculado à homologação da rescisão.' }
  ],
  comentario: 'Demissional: devido no prazo ligado à homologação, com dispensa condicionada à recência do último exame clínico ocupacional — intervalo menor quanto maior o grau de risco. Confira os prazos na redação vigente, pois já foram alterados.',
  pegadinha: 'Vincular a dispensa à forma do desligamento (pedido, justa causa, acordo) desloca o critério, que é a recência do exame.',
  refs: ['NR-7'] },

{ id: 'q-6.1-031', tema: '6.1', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Durante exame periódico de trabalhador exposto a ruído, a audiometria mostra piora dos limiares em relação à audiometria de referência, ainda sem repercussão em frequências da fala. A conduta CORRETA é:',
  alts: [
    { t: 'Investigar a evolução, o repouso e a qualidade do exame e revisar controle e proteção.', ok: true,
      why: 'Correta. O achado é sinal de falha do sistema de proteção e exige ação.' },
    { t: 'Aguardar o comprometimento das frequências da fala antes de adotar qualquer providência.', ok: false,
      why: 'Errada. As agudas são acometidas primeiro; esperar é perder a janela de ação.' },
    { t: 'Concluir pelo diagnóstico e emitir a comunicação do agravo de imediato, sem outras verificações.', ok: false,
      why: 'Errada. Exige confirmação com repouso auditivo e avaliação complementar.' },
    { t: 'Substituir o protetor auditivo por outro de maior atenuação e encerrar o acompanhamento do caso.', ok: false,
      why: 'Errada. Superproteção traz riscos e não corrige a exposição na fonte.' },
    { t: 'Registrar o achado, que não tem significado clínico por não haver queixa auditiva do trabalhador.', ok: false,
      why: 'Errada. O desencadeamento precede a queixa e é o momento de agir.' }
  ],
  comentario: 'Monitoramento existe para detectar antes do sintoma. Piora de limiares dispara três frentes: verificar a validade do exame, reavaliar o trabalhador em intervalo menor e revisar o controle de risco — porque a piora sinaliza que a proteção falhou.',
  pegadinha: 'As duas armadilhas opostas: esperar a fala ser afetada e fechar diagnóstico em exame único sem verificar repouso auditivo.',
  refs: ['NR-7', 'Gândara — Doenças Otorrinolaringológicas Relacionadas ao Trabalho'] }

);
