/* 7.4 Normas Regulamentadoras e 7.2 Legislação Previdenciária — aprofundamento.
   Questões AUTORAIS. Ver banco/README-formato.md */
window.BANCO = window.BANCO || [];
window.BANCO.push(

/* ===================== 7.4 Normas Regulamentadoras ====================== */
{ id: 'q-7.4-030', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um trabalhador recusa-se a executar tarefa em andaime que apresenta travamento improvisado com arame, alegando risco grave e iminente. O encarregado ameaça puni-lo por insubordinação. Sobre a situação, é CORRETO afirmar:',
  alts: [
    { t: 'Pode interromper diante de risco grave e iminente, comunicando ao superior hierárquico.', ok: true,
      why: 'Correta. A interrupção legítima não configura insubordinação.' },
    { t: 'A recusa configura insubordinação, pois avaliar o risco compete apenas ao serviço especializado.', ok: false,
      why: 'Errada. O direito de recusa é do trabalhador diante de risco iminente.' },
    { t: 'Pode recusar-se, mas só depois da interdição formal do local pela autoridade competente.', ok: false,
      why: 'Errada. A interrupção é imediata; esperar anularia a proteção.' },
    { t: 'Pode recusar-se, ficando obrigado a apresentar laudo técnico que comprove o risco alegado.', ok: false,
      why: 'Errada. Não se exige laudo prévio do trabalhador.' },
    { t: 'Pode recusar-se a executar a tarefa, autorizando a recusa o desconto das horas não trabalhadas.', ok: false,
      why: 'Errada. A interrupção legítima não gera prejuízo remuneratório.' }
  ],
  comentario: 'Direito de recusa: interromper a atividade diante de risco grave e iminente, com comunicação imediata ao superior. Não exige laudo, não exige interdição prévia e não configura insubordinação.',
  pegadinha: 'Condicionar o direito de recusa a laudo ou a interdição prévia é a forma mais comum de anulá-lo na prática.',
  refs: ['NR-1', 'CLT — Capítulo V do Título II'] },

{ id: 'q-7.4-031', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma indústria apresenta ao médico do trabalho seu inventário de riscos e seu plano de ação. Sobre o gerenciamento de riscos ocupacionais, é CORRETO afirmar:',
  alts: [
    { t: 'O inventário consolida perigos e riscos; o plano define medidas com prazos e responsáveis.', ok: true,
      why: 'Correta. Ambos se revisam a cada mudança de processo ou evento.' },
    { t: 'O inventário substitui o programa de controle médico, por já conter a avaliação de saúde dos expostos.', ok: false,
      why: 'Errada. São documentos distintos e articulados entre si.' },
    { t: 'O inventário consolida os riscos, sendo o plano de ação facultativo se todos forem classificados baixos.', ok: false,
      why: 'Errada. O plano é exigido sempre que houver medidas a adotar.' },
    { t: 'O inventário consolida os riscos, revisado apenas na periodicidade fixa, seja qual for o evento.', ok: false,
      why: 'Errada. Mudança de processo e acidente disparam revisão antecipada.' },
    { t: 'O gerenciamento de riscos permanece regulado pela norma de agentes físicos, químicos e biológicos.', ok: false,
      why: 'Errada. Está na norma de disposições gerais e gerenciamento de riscos.' }
  ],
  comentario: 'Estrutura atual: gerenciamento de riscos na norma de disposições gerais, com inventário de riscos e plano de ação como produtos. A norma de agentes cuida da avaliação e do controle das exposições. E a revisão é disparada por evento, não só por calendário.',
  pegadinha: 'A alternativa que devolve o gerenciamento à norma de agentes reproduz a estrutura antiga, do tempo do PPRA.',
  refs: ['NR-1', 'NR-9'] },

{ id: 'q-7.4-032', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador eleito representante dos empregados na comissão interna de prevenção de acidentes é comunicado de sua dispensa sem justa causa dois meses após o término do mandato. Sobre a situação, é CORRETO afirmar:',
  alts: [
    { t: 'A garantia vai do registro da candidatura até período posterior ao fim do mandato.', ok: true,
      why: 'Correta. A dispensa nesse intervalo exige motivo comprovado.' },
    { t: 'A garantia de emprego do representante eleito cessa no próprio dia do término do mandato exercido.', ok: false,
      why: 'Errada. Estende-se por período posterior ao término.' },
    { t: 'A garantia vai da candidatura ao pós-mandato e alcança também os representantes indicados pelo empregador.', ok: false,
      why: 'Errada. A garantia é dos representantes eleitos pelos empregados.' },
    { t: 'A garantia vai da candidatura ao pós-mandato e se aplica ao titular, sem proteger o suplente eleito.', ok: false,
      why: 'Errada. O suplente também é protegido.' },
    { t: 'A garantia existe, condicionada ao comparecimento do representante a todas as reuniões da comissão.', ok: false,
      why: 'Errada. Não há esse condicionamento.' }
  ],
  comentario: 'Guarde três pontos: a garantia vale do registro da candidatura até período após o término do mandato; protege eleitos (titulares e suplentes), não indicados pelo empregador; e existe para blindar quem cobra segurança contra retaliação.',
  pegadinha: 'Encerrar a garantia no último dia do mandato é a leitura mais intuitiva e está errada.',
  refs: ['NR-5', 'CLT'] },

{ id: 'q-7.4-033', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Um hospital solicita orientação sobre as exigências específicas aplicáveis aos seus trabalhadores. Sobre a norma de segurança e saúde em serviços de saúde, é CORRETO afirmar:',
  alts: [
    { t: 'Trata de riscos biológicos, químicos e radiações, com programa de perfurocortantes e vacinação.', ok: true,
      why: 'Correta. A vacinação dos expostos é gratuita e o programa tem participação dos trabalhadores.' },
    { t: 'Trata de riscos biológicos, restringindo-se aos profissionais de nível superior da assistência direta.', ok: false,
      why: 'Errada. Alcança todos os trabalhadores dos serviços de saúde.' },
    { t: 'Trata de riscos e prevê vacinação, cujo custo pode ser dividido com o empregado beneficiado.', ok: false,
      why: 'Errada. É gratuita para o trabalhador.' },
    { t: 'Trata de riscos biológicos, ficando os químicos restritos à norma específica de agentes nocivos.', ok: false,
      why: 'Errada. A norma alcança expressamente os riscos químicos.' },
    { t: 'Trata de perfurocortantes, permitindo o reencape de agulhas quando há treinamento específico.', ok: false,
      why: 'Errada. O reencape é prática vedada.' }
  ],
  comentario: 'A norma de serviços de saúde alcança TODOS os trabalhadores do estabelecimento, cobre riscos biológicos, químicos e radiações, exige plano de prevenção de perfurocortantes com participação dos trabalhadores e garante vacinação gratuita aos expostos.',
  pegadinha: 'Restringir a aplicação aos profissionais assistenciais deixa de fora justamente quem mais se acidenta com perfurocortante descartado incorretamente.',
  refs: ['NR-32'] },

{ id: 'q-7.4-034', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre o dimensionamento e a natureza do serviço especializado em segurança e medicina do trabalho, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Considera o grau de risco da atividade e o total de empregados, com profissionais qualificados.', ok: true,
      why: 'Correta. A formação específica para cada função é exigida.' },
    { t: 'O dimensionamento depende do número de empregados do estabelecimento onde o serviço se instala.', ok: false,
      why: 'Errada. O grau de risco da atividade também determina.' },
    { t: 'Considera risco e porte, podendo qualquer profissional de nível superior ocupar as funções previstas.', ok: false,
      why: 'Errada. Exige-se formação e qualificação específicas.' },
    { t: 'Considera risco e porte, substituindo o serviço especializado a comissão interna de prevenção.', ok: false,
      why: 'Errada. São estruturas distintas e ambas exigidas.' },
    { t: 'Considera risco e porte, dispensando sua existência a elaboração do gerenciamento de riscos.', ok: false,
      why: 'Errada. O serviço executa o programa, não o dispensa.' }
  ],
  comentario: 'Serviço especializado: dimensionado por grau de risco e número de empregados, com profissionais de formação específica. Comissão interna: paritária, com representantes eleitos. Coexistem — um se contrata, o outro se elege.',
  pegadinha: 'A confusão entre serviço especializado e comissão interna é o erro mais recorrente do tema.',
  refs: ['NR-4', 'NR-5', 'NR-1'] },

{ id: 'q-7.4-035', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Após inspeção, a autoridade competente determina a interdição de um setor por risco grave e iminente. A empresa questiona os efeitos sobre os trabalhadores. A orientação CORRETA é:',
  alts: [
    { t: 'Os trabalhadores recebem salários como se em efetivo exercício durante a paralisação.', ok: true,
      why: 'Correta. Cabe à empresa sanar as condições para requerer o levantamento.' },
    { t: 'Os trabalhadores devem ter suas férias antecipadas durante o período de paralisação da atividade.', ok: false,
      why: 'Errada. O período é computado como de trabalho efetivo.' },
    { t: 'A paralisação garante salários, dependendo a interdição de autorização judicial prévia para valer.', ok: false,
      why: 'Errada. É ato administrativo de autoridade competente.' },
    { t: 'A paralisação garante salários, podendo a empresa descontá-los do banco de horas dos trabalhadores.', ok: false,
      why: 'Errada. Não há desconto nem compensação do período.' },
    { t: 'A paralisação garante salários, alcançando a interdição sempre o estabelecimento inteiro.', ok: false,
      why: 'Errada. Pode recair sobre setor ou máquina isolada.' }
  ],
  comentario: 'Interdição e embargo são as medidas extremas para risco grave e iminente: ato administrativo, alcance graduável (máquina, setor ou estabelecimento) e salários mantidos durante a paralisação. O levantamento depende de sanar a causa.',
  pegadinha: 'Descontar horas ou antecipar férias durante a paralisação transfere ao trabalhador o custo da falha da empresa.',
  refs: ['CLT — Capítulo V do Título II', 'NR-3'] },

{ id: 'q-7.4-036', tema: '7.4', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre as normas aplicáveis a atividades de alto risco, assinale a alternativa INCORRETA:',
  alts: [
    { t: 'A aptidão para altura pode ser presumida do exame admissional, sem avaliação dirigida.', ok: true,
      why: 'É a INCORRETA. Exige-se avaliação de saúde específica para trabalho em altura.' },
    { t: 'O espaço confinado exige permissão de entrada, avaliação prévia da atmosfera e vigia permanente.', ok: false,
      why: 'Correta, portanto não é a resposta. São requisitos expressos da norma.' },
    { t: 'A norma de eletricidade exige prontuário de instalações e capacitação dos trabalhadores autorizados.', ok: false,
      why: 'Correta, portanto não é a resposta. São exigências previstas.' },
    { t: 'A norma de máquinas exige proteções e dispositivos que impeçam o acesso às zonas de perigo.', ok: false,
      why: 'Correta, portanto não é a resposta. É o núcleo dessa norma.' },
    { t: 'Atividades em altura exigem análise de risco e autorização prévia para a execução do trabalho.', ok: false,
      why: 'Correta, portanto não é a resposta. São requisitos expressos.' }
  ],
  comentario: 'Atividades de alto risco compartilham uma lógica: análise de risco, autorização prévia por escrito, capacitação específica e avaliação de aptidão dirigida. Nenhuma delas se satisfaz com o exame admissional genérico.',
  pegadinha: 'Enunciado de "assinale a INCORRETA": a falsa dispensa a avaliação dirigida de aptidão, que é exigência autônoma.',
  refs: ['NR-33', 'NR-35', 'NR-10', 'NR-12', 'NR-7'] },

/* ================ 7.2 Legislação Previdenciária ======================== */
{ id: 'q-7.2-030', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Empregado sofre acidente de trabalho e permanece afastado por 40 dias. A empresa pergunta quem paga o período. A orientação CORRETA é:',
  alts: [
    { t: 'Os primeiros quinze dias são da empresa; do décimo sexto em diante, da previdência.', ok: true,
      why: 'Correta. No caso, o benefício tem natureza acidentária.' },
    { t: 'A previdência paga desde o primeiro dia em qualquer hipótese de acidente do trabalho ocorrido.', ok: false,
      why: 'Errada. Os primeiros quinze dias são de responsabilidade da empresa.' },
    { t: 'A empresa paga todo o período de afastamento, independentemente da duração da incapacidade.', ok: false,
      why: 'Errada. A partir do décimo sexto dia cabe à previdência.' },
    { t: 'Os primeiros quinze dias são da empresa, prazo que também define quando comunicar o acidente.', ok: false,
      why: 'Errada. A comunicação é até o primeiro dia útil seguinte.' },
    { t: 'Os primeiros quinze dias são da empresa, salvo no trajeto, quando ela fica isenta desse período.', ok: false,
      why: 'Errada. O trajeto é equiparado e segue a mesma regra.' }
  ],
  comentario: 'Dois prazos que a banca embaralha: quinze dias é a divisão do CUSTEIO entre empresa e Previdência; a obrigação de COMUNICAR o acidente independe de afastamento e não se confunde com aquele prazo.',
  pegadinha: 'Vincular a obrigação de comunicar o acidente ao prazo de quinze dias é a confusão mais frequente do tema.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-031', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhador com dois meses de contribuição sofre acidente de motocicleta no fim de semana, sem qualquer relação com o trabalho, e fica incapacitado. Sobre a carência, é CORRETO afirmar:',
  alts: [
    { t: 'A carência é dispensada em acidente de qualquer natureza, inclusive não ocupacional.', ok: true,
      why: 'Correta. O benefício pode ser devido apesar das poucas contribuições.' },
    { t: 'A carência de doze contribuições é exigida em todos os casos de incapacidade, sem exceção prevista.', ok: false,
      why: 'Errada. Acidente de qualquer natureza dispensa carência.' },
    { t: 'A carência é dispensada, aplicando-se essa dispensa somente aos acidentes do trabalho típicos.', ok: false,
      why: 'Errada. Alcança acidente de qualquer natureza.' },
    { t: 'A carência é dispensada, e nesse caso o benefício seria acidentário, com estabilidade posterior.', ok: false,
      why: 'Errada. Acidente não ocupacional não gera benefício acidentário.' },
    { t: 'A carência é dispensada, dependendo essa dispensa de o acidente ter ocorrido em dia útil de trabalho.', ok: false,
      why: 'Errada. Não há esse condicionamento.' }
  ],
  comentario: 'Dispensa de carência: acidente de QUALQUER natureza, doença profissional ou do trabalho, e doenças graves listadas. Mas atenção: dispensar carência não transforma o benefício em acidentário — a espécie depende da relação com o trabalho.',
  pegadinha: 'A alternativa que confunde dispensa de carência com natureza acidentária mistura dois efeitos independentes.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-032', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Trabalhadora teve alta de benefício por incapacidade temporária de natureza acidentária em 10 de março e recebeu auxílio-acidente a partir de então, por sequela que reduz sua capacidade. A empresa pretende dispensá-la em setembro do mesmo ano. A orientação CORRETA é:',
  alts: [
    { t: 'A garantia é de doze meses da cessação do benefício acidentário, e a dispensa seria irregular.', ok: true,
      why: 'Correta. Independe da percepção de auxílio-acidente.' },
    { t: 'A percepção de auxílio-acidente é condição para a existência da garantia de emprego posterior.', ok: false,
      why: 'Errada. A garantia independe desse benefício.' },
    { t: 'O prazo de doze meses conta-se do início do afastamento, já esgotado na situação descrita.', ok: false,
      why: 'Errada. Conta-se da cessação do benefício.' },
    { t: 'A alta pericial restabelece plenamente o poder de dispensa do empregador sobre o trabalhador.', ok: false,
      why: 'Errada. A estabilidade acidentária começa justamente aí.' },
    { t: 'A garantia aplica-se apenas a acidentes típicos, não alcançando as doenças ocupacionais reconhecidas.', ok: false,
      why: 'Errada. Doença ocupacional é equiparada a acidente.' }
  ],
  comentario: 'Três detalhes decidem: prazo mínimo de doze meses; termo inicial na CESSAÇÃO do benefício (não no início do afastamento); e independência em relação ao auxílio-acidente. Doença ocupacional entra por equiparação.',
  pegadinha: 'Mudar o termo inicial para o começo do afastamento mantém o prazo certo e erra o marco — é o distrator mais eficaz.',
  refs: ['Lei nº 8.213/1991 — arts. 86 e 118'] },

{ id: 'q-7.2-033', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre o auxílio-acidente, assinale a alternativa CORRETA:',
  alts: [
    { t: 'É indenizatório, devido após a consolidação, compatível com trabalho e cessa na aposentadoria.', ok: true,
      why: 'Correta. Pressupõe redução da capacidade para o trabalho habitual.' },
    { t: 'É benefício por incapacidade e, como tal, incompatível com o exercício de atividade remunerada.', ok: false,
      why: 'Errada. Tem natureza indenizatória e é compatível com o trabalho.' },
    { t: 'É indenizatório e devido durante o tratamento, antes da consolidação das lesões apresentadas.', ok: false,
      why: 'Errada. Depende da consolidação para avaliar a sequela.' },
    { t: 'É indenizatório e exige incapacidade total e permanente do segurado para ser concedido.', ok: false,
      why: 'Errada. Pressupõe capacidade residual com redução.' },
    { t: 'É indenizatório e pode decorrer de qualquer doença, sem relação com trabalho ou com acidente.', ok: false,
      why: 'Errada. Decorre de sequela de acidente de qualquer natureza.' }
  ],
  comentario: 'Auxílio-acidente é o benefício que mais confunde: NÃO é benefício por incapacidade. É indenização por sequela consolidada que REDUZ a capacidade, acumula com o trabalho e com o salário, e cessa com a aposentadoria.',
  pegadinha: 'Classificá-lo entre os benefícios por incapacidade leva a errar tudo o mais: compatibilidade com trabalho, pressuposto de consolidação e grau de comprometimento exigido.',
  refs: ['Lei nº 8.213/1991 — art. 86', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-034', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Uma empresa contesta administrativamente a aplicação do nexo técnico epidemiológico a diversos benefícios concedidos a seus empregados. Sobre o instituto, é CORRETO afirmar:',
  alts: [
    { t: 'Estabelece-se pelo cruzamento entre atividade econômica e entidade mórbida, com presunção relativa.', ok: true,
      why: 'Correta. A empresa pode afastá-la administrativamente.' },
    { t: 'A presunção decorrente do nexo epidemiológico é absoluta e não admite contestação pela empresa.', ok: false,
      why: 'Errada. É relativa, com via própria de contestação.' },
    { t: 'O nexo epidemiológico depende da prévia emissão da comunicação de acidente pela empresa empregadora.', ok: false,
      why: 'Errada. Independe da comunicação.' },
    { t: 'Aplicado o nexo epidemiológico, não há repercussão sobre o custo previdenciário da empresa.', ok: false,
      why: 'Errada. Repercute em alíquota e indicadores de acidentalidade.' },
    { t: 'O nexo epidemiológico substituiu integralmente as demais formas de reconhecimento de nexo causal.', ok: false,
      why: 'Errada. Convive com o nexo individual e o técnico.' }
  ],
  comentario: 'Três formas de nexo: profissional ou do trabalho (listas de agente-doença), individual (análise do caso concreto) e epidemiológico (cruzamento entre atividade econômica e agravo, com presunção relativa). Coexistem.',
  pegadinha: 'Trocar "presunção relativa" por "absoluta" é a armadilha número um deste tema.',
  refs: ['Lei nº 8.213/1991 — art. 21-A', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-035', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'intermediario',
  enunciado: 'Sobre a aposentadoria por incapacidade permanente, assinale a alternativa CORRETA:',
  alts: [
    { t: 'Exige incapacidade total insuscetível de reabilitação, com reavaliação periódica prevista.', ok: true,
      why: 'Correta. O benefício pode cessar se constatada recuperação.' },
    { t: 'Uma vez concedida, a aposentadoria por incapacidade permanente não pode mais ser revista.', ok: false,
      why: 'Errada. Há previsão de reavaliação periódica.' },
    { t: 'Basta a incapacidade para a atividade habitualmente exercida pelo segurado antes do afastamento.', ok: false,
      why: 'Errada. Exige incapacidade insuscetível de reabilitação.' },
    { t: 'A irreversibilidade da lesão apresentada é suficiente para caracterizar o direito ao benefício.', ok: false,
      why: 'Errada. É preciso afastar a viabilidade de reabilitação.' },
    { t: 'É incompatível com qualquer acréscimo, mesmo havendo necessidade de assistência permanente de terceiro.', ok: false,
      why: 'Errada. Há acréscimo previsto nessa hipótese.' }
  ],
  comentario: 'Requisitos cumulativos: incapacidade total, permanente e insuscetível de reabilitação. Havendo capacidade residual, o caminho é a reabilitação profissional. E "permanente" não significa imutável: há reavaliação.',
  pegadinha: 'Equiparar lesão irreversível a incapacidade total é o erro que atravessa todo o bloco de perícia e previdência.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999'] },

{ id: 'q-7.2-036', tema: '7.2', tipo: 'autoral', fonte: null, nivel: 'dificil',
  enunciado: 'Sobre a aposentadoria especial, é CORRETO afirmar:',
  alts: [
    { t: 'Exige exposição habitual e permanente, comprovada por documentação com base em laudo técnico.', ok: true,
      why: 'Correta. O período exigido varia conforme o agente nocivo.' },
    { t: 'Exige sempre vinte e cinco anos de exposição ao agente, qualquer que seja a sua natureza.', ok: false,
      why: 'Errada. O período varia conforme o agente.' },
    { t: 'Exige exposição a agentes nocivos, sendo suficiente a exposição eventual e intermitente ao agente.', ok: false,
      why: 'Errada. A eventualidade afasta o enquadramento.' },
    { t: 'Exige exposição habitual, comprovando a percepção de adicional de insalubridade esse direito.', ok: false,
      why: 'Errada. São enquadramentos distintos, com critérios próprios.' },
    { t: 'Exige exposição habitual, descaracterizando sempre o fornecimento de proteção individual a exposição.', ok: false,
      why: 'Errada. O efeito varia conforme o agente; o ruído tem tratamento próprio.' }
  ],
  comentario: 'Aposentadoria especial: exposição habitual e permanente, tempo conforme o agente, comprovação documental técnica. E dois cuidados: adicional de insalubridade não prova exposição para esse fim, e a neutralização por equipamento individual não vale para todos os agentes.',
  pegadinha: 'Equiparar adicional de insalubridade a prova de exposição mistura o plano trabalhista com o previdenciário.',
  refs: ['Lei nº 8.213/1991', 'Decreto nº 3.048/1999'] }

);
