/* =============================================================================
   EDITAL.JS — Taxonomia oficial do Edital nº 2512 / ANAMT
   Título de Especialista em Medicina do Trabalho 2026

   FONTE DA VERDADE de todo o aplicativo. Nenhum módulo (questões, flashcards,
   treino, materiais, cronograma, planilha) pode usar rótulo de tema que não
   esteja aqui.

   Base: item 15.1 (Conteúdo programático) + item 16 (Bibliografia) do edital.
   origem: 'E' = termo literal do 15.1
           'D' = desdobramento de um termo literal
           'B' = derivado da bibliografia oficial (cláusula final do 15.1)
   peso:   'alto' = tema de alto rendimento na prova (meta 45 questões)
           'medio' = meta 30 questões
   ========================================================================== */
(function (root) {
  'use strict';

  var SECOES = [
    { id: 1, nome: 'Fundamentos, Epidemiologia e Gestão em Saúde do Trabalhador' },
    { id: 2, nome: 'Higiene Ocupacional, Exposições e Toxicologia' },
    { id: 3, nome: 'Ergonomia' },
    { id: 4, nome: 'Patologia do Trabalho e Doenças Relacionadas ao Trabalho' },
    { id: 5, nome: 'Acidentes do Trabalho, Nexo, Perícia e Incapacidade' },
    { id: 6, nome: 'Prática Clínica Ocupacional' },
    { id: 7, nome: 'Legislação, Normas Regulamentadoras e Ética' }
  ];

  var TEMAS = [
    // ---------------------------------------------------------------- Seção 1
    { id: '1.1', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Medicina do Trabalho',
      sub: ['Histórico da especialidade e Ramazzini', 'Campo de atuação e atribuições do médico do trabalho',
            'Serviço Especializado em Segurança e Medicina do Trabalho (SESMT)',
            'Relação médico do trabalho / empresa / trabalhador', 'Demografia médica e mercado da especialidade'] },
    { id: '1.2', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Saúde do Trabalhador',
      sub: ['Diferença conceitual entre Medicina do Trabalho, Saúde Ocupacional e Saúde do Trabalhador',
            'Determinação social do processo saúde-doença', 'Modelo operário italiano e controle social',
            'Trabalho como categoria analítica', 'Saúde global e trabalho'] },
    { id: '1.3', sec: 1, origem: 'E', peso: 'alto',
      nome: 'Epidemiologia Clínica e Bioestatística',
      sub: ['Medidas de frequência: incidência, prevalência, densidade de incidência',
            'Medidas de associação: risco relativo, razão de chances, risco atribuível',
            'Desenhos de estudo: coorte, caso-controle, transversal, ensaio clínico',
            'Validade de testes: sensibilidade, especificidade, VPP, VPN, razão de verossimilhança',
            'Viés, confundimento e modificação de efeito', 'Testes de hipótese, valor de p e intervalo de confiança',
            'Vigilância epidemiológica aplicada ao trabalho'] },
    { id: '1.4', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Gestão em Saúde do Trabalhador',
      sub: ['Indicadores de saúde ocupacional e absenteísmo', 'Custos da doença e do afastamento',
            'Gestão de programas de saúde na empresa', 'Auditoria e qualidade em serviços de SST',
            'Gestão do PCMSO na micro, pequena e grande empresa'] },
    { id: '1.5', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Sistemas de Gestão em Segurança e Saúde no Trabalho',
      sub: ['Ciclo PDCA aplicado à SST', 'Diretrizes da OIT sobre sistemas de gestão de SST',
            'ISO 45001 — estrutura e requisitos gerais', 'Cultura de segurança e comportamento seguro',
            'Melhoria contínua e auditoria de sistema'] },
    { id: '1.6', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Políticas Públicas de Saúde do Trabalhador',
      sub: ['Política Nacional de Saúde do Trabalhador e da Trabalhadora (PNSTT)',
            'RENAST e os CEREST', 'Política Nacional de Promoção da Saúde',
            'Intersetorialidade entre Saúde, Trabalho e Previdência'] },
    { id: '1.7', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Sistema Único de Saúde (SUS)',
      sub: ['Princípios e diretrizes do SUS', 'Lei nº 8.080/1990 e competências em saúde do trabalhador',
            'Atenção primária e a saúde do trabalhador', 'Redes de atenção e referência/contrarreferência'] },
    { id: '1.8', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Vigilância em Saúde do Trabalhador',
      sub: ['VISAT: conceito, objeto e instrumentos', 'Vigilância de ambientes e processos de trabalho',
            'Vigilância epidemiológica de agravos relacionados ao trabalho',
            'Inspeção sanitária e interdição', 'Investigação de acidente de trabalho grave e fatal'] },
    { id: '1.9', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Sistema de Informação de Agravos de Notificação (SINAN)',
      sub: ['Notificação compulsória: conceito e fluxo', 'Agravos relacionados ao trabalho de notificação compulsória',
            'Ficha de investigação e preenchimento', 'Diferença entre notificação ao SINAN e emissão de CAT',
            'Outros sistemas de informação em saúde do trabalhador'] },
    { id: '1.10', sec: 1, origem: 'E', peso: 'medio',
      nome: 'Promoção da Saúde',
      sub: ['Prevenção primária, secundária, terciária e quaternária',
            'Programas de promoção da saúde no ambiente de trabalho',
            'Modelo da OMS de ambientes de trabalho saudáveis', 'Prevenção do uso de álcool e outras drogas no trabalho',
            'Qualidade de vida no trabalho e limites do "wellness"'] },

    // ---------------------------------------------------------------- Seção 2
    { id: '2.1', sec: 2, origem: 'E', peso: 'medio',
      nome: 'Higiene Ocupacional',
      sub: ['Antecipação, reconhecimento, avaliação e controle', 'Hierarquia de controles de risco',
            'Estratégia de amostragem e grupos homogêneos de exposição',
            'Ventilação industrial e enclausuramento', 'EPC versus EPI'] },
    { id: '2.2', sec: 2, origem: 'D', peso: 'alto',
      nome: 'Exposição Ocupacional aos Agentes Físicos',
      sub: ['Ruído: contínuo, intermitente e de impacto; dose e nível de exposição',
            'Vibração de mãos e braços e de corpo inteiro', 'Calor: IBUTG e sobrecarga térmica; trabalho a céu aberto',
            'Frio e trabalho em ambientes artificialmente frios', 'Radiações ionizantes e não ionizantes',
            'Pressões anormais e trabalho hiperbárico', 'Iluminação e conforto visual'] },
    { id: '2.3', sec: 2, origem: 'D', peso: 'alto',
      nome: 'Exposição Ocupacional aos Agentes Químicos',
      sub: ['Vias de absorção e classificação dos agentes químicos',
            'Poeiras, fumos, névoas, gases e vapores', 'Solventes orgânicos e hidrocarbonetos',
            'Metais pesados: chumbo, mercúrio, cromo, cádmio, manganês', 'Sílica, asbesto e poeiras minerais',
            'Agrotóxicos e praguicidas', 'Benzeno e o Acordo Nacional do Benzeno'] },
    { id: '2.4', sec: 2, origem: 'D', peso: 'alto',
      nome: 'Exposição Ocupacional aos Agentes Biológicos',
      sub: ['Classes de risco dos agentes biológicos', 'Risco biológico em serviços de saúde',
            'Exposição em saneamento, agropecuária e laboratórios',
            'Precauções padrão e de transmissão', 'Acidente com material biológico e conduta pós-exposição'] },
    { id: '2.5', sec: 2, origem: 'E', peso: 'medio',
      nome: 'Avaliação e Gerenciamento das Exposições Ocupacionais',
      sub: ['Estratégia AIHA de avaliação e gerenciamento de exposições',
            'Grupos similares de exposição (GSE/SEG)', 'Interpretação estatística de dados de exposição',
            'Priorização de riscos e plano de ação', 'Reavaliação e monitoramento periódico'] },
    { id: '2.6', sec: 2, origem: 'E', peso: 'alto',
      nome: 'Limites de Exposição Ocupacional',
      sub: ['Conceito de limite de tolerância e de TLV', 'TLV-TWA, TLV-STEL e TLV-C',
            'Índices Biológicos de Exposição (BEI)', 'Diferenças entre os limites da NR-15 e os TLVs da ACGIH',
            'Fator de desvio e jornadas atípicas', 'Notações: pele, sensibilizante, carcinogenicidade'] },
    { id: '2.7', sec: 2, origem: 'E', peso: 'medio',
      nome: 'Normas de Higiene Ocupacional (NHO)',
      sub: ['Papel das NHO da Fundacentro', 'NHO de avaliação da exposição ao ruído',
            'NHO de avaliação da exposição ao calor', 'NHO de avaliação de vibrações',
            'NHO de amostragem de aerodispersoides', 'Relação entre NHO e as Normas Regulamentadoras'] },
    { id: '2.8', sec: 2, origem: 'E', peso: 'medio',
      nome: 'Proteção Respiratória',
      sub: ['Programa de Proteção Respiratória (PPR)', 'Tipos de respiradores: purificadores e de adução de ar',
            'Fator de proteção atribuído e seleção do respirador', 'Ensaio de vedação qualitativo e quantitativo',
            'Avaliação médica para uso de respirador', 'Guarda, higienização e manutenção'] },
    { id: '2.9', sec: 2, origem: 'E', peso: 'alto',
      nome: 'Toxicologia Ocupacional',
      sub: ['Toxicocinética: absorção, distribuição, biotransformação e excreção',
            'Toxicodinâmica e relação dose-resposta', 'Monitoramento biológico e indicadores biológicos',
            'Intoxicações agudas e crônicas por agentes ocupacionais',
            'Neurotoxicidade, hepatotoxicidade e nefrotoxicidade ocupacionais',
            'Interferentes do monitoramento biológico', 'Antídotos e condutas em intoxicação ocupacional'] },

    // ---------------------------------------------------------------- Seção 3
    { id: '3.1', sec: 3, origem: 'D', peso: 'medio',
      nome: 'Ergonomia — fundamentos, antropometria e biomecânica',
      sub: ['Conceito e domínios da ergonomia (física, cognitiva, organizacional)',
            'Antropometria aplicada ao posto de trabalho', 'Biomecânica ocupacional e levantamento de cargas',
            'Postura, força, repetitividade e tempo de recuperação', 'Trabalho sentado, em pé e alternado',
            'Mobiliário, equipamentos e trabalho com telas'] },
    { id: '3.2', sec: 3, origem: 'D', peso: 'alto',
      nome: 'Ergonomia — organização do trabalho e análise ergonômica',
      sub: ['Análise Ergonômica do Trabalho: etapas e produtos', 'Avaliação ergonômica preliminar x AET',
            'Organização do trabalho, ritmo, metas e pausas', 'Trabalho em turnos e noturno; cronobiologia',
            'Ferramentas de avaliação de risco ergonômico (RULA, REBA, NIOSH, OCRA, Strain Index)',
            'Ergonomia e prevenção de LER/DORT', 'Teletrabalho e ergonomia'] },

    // ---------------------------------------------------------------- Seção 4
    { id: '4.1', sec: 4, origem: 'E', peso: 'medio',
      nome: 'Patologia do Trabalho',
      sub: ['Conceito de doença profissional e doença do trabalho',
            'Classificação de Schilling', 'Lista de Doenças Relacionadas ao Trabalho do Ministério da Saúde',
            'História ocupacional e anamnese dirigida', 'Períodos de latência e de indução'] },
    { id: '4.2', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Doenças Relacionadas ao Trabalho',
      sub: ['LER/DORT: quadros clínicos, diagnóstico e conduta',
            'Doenças osteomusculares de coluna relacionadas ao trabalho',
            'Doenças cardiovasculares e trabalho', 'Doenças hematológicas ocupacionais',
            'Nefropatias e hepatopatias ocupacionais', 'Doenças oftalmológicas relacionadas ao trabalho',
            'Distúrbios da reprodução relacionados ao trabalho'] },
    { id: '4.3', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Pneumologia Ocupacional',
      sub: ['Pneumoconioses: silicose, asbestose, pneumoconiose dos trabalhadores de carvão',
            'Asma ocupacional e asma agravada pelo trabalho; peak flow seriado',
            'Pneumonite de hipersensibilidade e alveolites', 'DPOC ocupacional e bronquite industrial',
            'Doenças pleurais relacionadas ao asbesto', 'Espirometria ocupacional: indicação e interpretação',
            'Radiografia de tórax padrão OIT'] },
    { id: '4.4', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Dermatoses Ocupacionais',
      sub: ['Dermatite de contato irritativa x alérgica', 'Testes de contato e sua interpretação',
            'Urticária de contato e dermatoses fotoinduzidas', 'Cloracne, discromias e ulcerações ocupacionais',
            'Câncer de pele ocupacional', 'Prevenção: barreiras, luvas e cremes',
            'Diagnóstico diferencial com dermatoses não ocupacionais'] },
    { id: '4.5', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Otorrinolaringologia Ocupacional',
      sub: ['Perda Auditiva Induzida por Ruído: fisiopatologia e critérios diagnósticos',
            'Audiometria ocupacional: realização, repouso auditivo e interpretação',
            'Diagnóstico diferencial das perdas auditivas', 'Definição legal de deficiência auditiva',
            'Ototoxicidade química e interação ruído-solvente', 'Conservação auditiva e PCA',
            'Zumbido, vertigem e disfonia ocupacional'] },
    { id: '4.6', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Saúde Mental e Fatores Psicossociais Relacionados ao Trabalho',
      sub: ['Fatores de risco psicossociais: identificação e gerenciamento',
            'Modelos teóricos: demanda-controle e desequilíbrio esforço-recompensa',
            'Burnout: conceito, diagnóstico e repercussões previdenciárias',
            'Assédio moral e sexual no trabalho', 'Psicodinâmica do trabalho (Dejours)',
            'Prevenção do suicídio e manejo da crise', 'Retorno ao trabalho após afastamento psiquiátrico'] },
    { id: '4.7', sec: 4, origem: 'E', peso: 'medio',
      nome: 'Psiquiatria Ocupacional',
      sub: ['Transtornos de ansiedade e depressivos no contexto laboral',
            'Transtorno de estresse pós-traumático relacionado ao trabalho',
            'Transtornos por uso de álcool e outras substâncias', 'Psicofármacos e aptidão para o trabalho',
            'Avaliação psiquiátrica pericial', 'Critérios diagnósticos (CID e DSM) aplicados ao trabalho'] },
    { id: '4.8', sec: 4, origem: 'E', peso: 'alto',
      nome: 'Câncer Relacionado ao Trabalho',
      sub: ['Classificação de carcinogenicidade da IARC', 'LINACH — Lista Nacional de Agentes Cancerígenos',
            'Cânceres ocupacionais mais frequentes e seus agentes',
            'Fração atribuível e vigilância do câncer ocupacional',
            'Rastreamento e acompanhamento de expostos', 'Nexo causal em câncer ocupacional'] },
    { id: '4.9', sec: 4, origem: 'E', peso: 'medio',
      nome: 'Doenças Infectocontagiosas de Interesse Ocupacional',
      sub: ['Tuberculose ocupacional e infecção latente', 'Hepatites virais B e C no trabalho',
            'HIV ocupacional e profilaxia pós-exposição', 'Leptospirose e outras zoonoses ocupacionais',
            'Arboviroses e trabalho a céu aberto', 'Doenças imunopreveníveis em profissionais de saúde',
            'Biossegurança e acidentes perfurocortantes'] },
    { id: '4.10', sec: 4, origem: 'E', peso: 'medio',
      nome: 'Imunizações do Trabalhador',
      sub: ['Calendário de vacinação ocupacional', 'Vacinação por grupo de risco ocupacional',
            'Avaliação de resposta vacinal e revacinação', 'Contraindicações e eventos adversos',
            'Registro, recusa vacinal e aspectos éticos'] },

    // ---------------------------------------------------------------- Seção 5
    { id: '5.1', sec: 5, origem: 'E', peso: 'alto',
      nome: 'Acidentes do Trabalho',
      sub: ['Conceito legal de acidente do trabalho', 'Acidente típico, de trajeto e equiparados',
            'Comunicação de Acidente do Trabalho (CAT): tipos, prazos e legitimados',
            'Investigação e análise de acidentes', 'Estabilidade acidentária e repercussões',
            'Acidente grave e fatal: fluxo de notificação', 'Indicadores de acidentalidade'] },
    { id: '5.2', sec: 5, origem: 'E', peso: 'alto',
      nome: 'Nexo Causal',
      sub: ['Critérios de causalidade aplicados ao trabalho',
            'Nexo técnico profissional ou do trabalho', 'Nexo técnico epidemiológico previdenciário (NTEP)',
            'Nexo técnico individual', 'Classificação de Schilling aplicada ao nexo',
            'Elementos do raciocínio de nexo: exposição, latência, plausibilidade e exclusão'] },
    { id: '5.3', sec: 5, origem: 'E', peso: 'medio',
      nome: 'Concausalidade',
      sub: ['Concausa preexistente, concomitante e superveniente',
            'Agravamento de doença preexistente pelo trabalho', 'Doença degenerativa x doença relacionada ao trabalho',
            'Repercussões da concausa no nexo e na conduta pericial'] },
    { id: '5.4', sec: 5, origem: 'E', peso: 'alto',
      nome: 'Perícia Médica',
      sub: ['Perícia administrativa, judicial e securitária', 'Quesitos, laudo e parecer técnico',
            'Papel do assistente técnico', 'Ética na atividade pericial e sigilo',
            'Perícia em DORT e em transtornos mentais', 'Simulação, dissimulação e sobressimulação',
            'Perícia e o Código de Ética Médica'] },
    { id: '5.5', sec: 5, origem: 'E', peso: 'alto',
      nome: 'Avaliação da Incapacidade Laborativa e do Dano Corporal',
      sub: ['Incapacidade total x parcial, temporária x permanente',
            'Deficiência, incapacidade e handicap; modelo da CIF',
            'Benefícios por incapacidade e seus requisitos', 'Auxílio-acidente e aposentadoria por incapacidade permanente',
            'Tabela brasileira para apuração do dano corporal', 'Dano estético e dano funcional',
            'Avaliação da incapacidade em DORT'] },
    { id: '5.6', sec: 5, origem: 'E', peso: 'medio',
      nome: 'Reabilitação Profissional',
      sub: ['Programa de reabilitação profissional da Previdência',
            'Retorno ao trabalho e readaptação funcional', 'Restrições, limitações e adaptação do posto',
            'Papel do médico do trabalho no retorno ao trabalho',
            'Barreiras ao retorno e fatores de risco de cronificação'] },

    // ---------------------------------------------------------------- Seção 6
    { id: '6.1', sec: 6, origem: 'E', peso: 'alto',
      nome: 'Exames Médicos Ocupacionais',
      sub: ['PCMSO: objetivo, elaboração e responsabilidades',
            'Exames admissional, periódico, de retorno ao trabalho, de mudança de risco e demissional',
            'Atestado de Saúde Ocupacional (ASO): conteúdo e guarda',
            'Exames complementares por risco e sua periodicidade',
            'Relatório analítico do PCMSO', 'Aptidão, inaptidão e aptidão com restrição',
            'Articulação entre PCMSO e programa de gerenciamento de riscos'] },
    { id: '6.2', sec: 6, origem: 'E', peso: 'medio',
      nome: 'Inclusão da Pessoa com Deficiência (legislação e acessibilidade)',
      sub: ['Estatuto da Pessoa com Deficiência (Lei nº 13.146/2015)',
            'Lei de Cotas e laudo caracterizador de deficiência', 'Definição legal de deficiência auditiva',
            'Acessibilidade e adaptação razoável no ambiente de trabalho',
            'Avaliação biopsicossocial da deficiência', 'Papel do médico do trabalho na inclusão'] },
    { id: '6.3', sec: 6, origem: 'B', peso: 'medio',
      nome: 'Clínica médica aplicada à aptidão laboral e ao rastreamento',
      sub: ['Hipertensão arterial e aptidão para funções críticas',
            'Diabetes mellitus, hipoglicemia e trabalho', 'Obesidade, síndrome metabólica e trabalho',
            'Epilepsia e rastreamento para atividades de risco', 'Distúrbios do sono e sonolência ocupacional',
            'Rastreamento de doenças e limites do check-up ocupacional',
            'Trabalhador em uso de medicamentos e aptidão'] },
    { id: '6.4', sec: 6, origem: 'B', peso: 'medio',
      nome: 'Urgências e emergências no ambiente de trabalho',
      sub: ['Atendimento inicial ao acidentado no trabalho',
            'Queimaduras químicas, térmicas e elétricas', 'Intoxicação aguda e exposição maciça',
            'Espaço confinado e resgate', 'Emergências cardiovasculares no trabalho e uso do DEA',
            'Plano de resposta a emergências e primeiros socorros'] },

    // ---------------------------------------------------------------- Seção 7
    { id: '7.1', sec: 7, origem: 'D', peso: 'medio',
      nome: 'Legislação Trabalhista aplicável à Medicina do Trabalho',
      sub: ['Capítulo V do Título II da CLT — Segurança e Medicina do Trabalho',
            'Jornada, intervalos, prorrogação e compensação', 'Trabalho da mulher, do menor e proteção à maternidade',
            'Adicionais de insalubridade e de periculosidade', 'Estabilidades e rescisão relacionadas à saúde',
            'Fiscalização do trabalho e autuação'] },
    { id: '7.2', sec: 7, origem: 'D', peso: 'alto',
      nome: 'Legislação Previdenciária aplicável à Medicina do Trabalho',
      sub: ['Lei nº 8.213/1991 — planos de benefícios', 'Regulamento da Previdência Social (Decreto nº 3.048/1999)',
            'Benefícios por incapacidade: requisitos, carência e cessação',
            'Auxílio-acidente e aposentadoria especial', 'Fator Acidentário de Prevenção e alíquotas RAT',
            'Lista de doenças ocupacionais do anexo previdenciário',
            'Ação regressiva acidentária'] },
    { id: '7.3', sec: 7, origem: 'D', peso: 'medio',
      nome: 'Legislação Sanitária aplicável à Medicina do Trabalho',
      sub: ['Competências sanitárias em saúde do trabalhador',
            'Notificação compulsória e legislação sanitária', 'Vigilância sanitária de ambientes de trabalho',
            'Controle de produtos e substâncias perigosas', 'Interface entre vigilância sanitária e do trabalhador'] },
    { id: '7.4', sec: 7, origem: 'E', peso: 'alto',
      nome: 'Normas Regulamentadoras',
      sub: ['Estrutura e natureza jurídica das NRs; Portaria nº 3.214/1978',
            'NR de gerenciamento de riscos ocupacionais (PGR) e inventário de riscos',
            'NR de controle médico de saúde ocupacional (PCMSO)',
            'NR de atividades e operações insalubres e de periculosidade',
            'NR de ergonomia', 'NR de segurança em serviços de saúde',
            'NRs de espaço confinado, trabalho em altura, eletricidade e máquinas',
            'CIPA e capacitação em SST'] },
    { id: '7.5', sec: 7, origem: 'E', peso: 'medio',
      nome: 'eSocial',
      sub: ['Estrutura e finalidade do eSocial', 'Eventos de SST: quais são e o que informam',
            'Comunicação de acidente do trabalho pelo eSocial',
            'Monitoramento da saúde do trabalhador no eSocial', 'Prazos, retificações e penalidades',
            'Responsabilidade do médico do trabalho no preenchimento'] },
    { id: '7.6', sec: 7, origem: 'E', peso: 'medio',
      nome: 'Código de Ética Médica',
      sub: ['Princípios fundamentais aplicáveis ao médico do trabalho',
            'Sigilo médico no ambiente de trabalho e prontuário',
            'Conflito de interesses entre empresa e trabalhador', 'Publicidade médica e relação com colegas',
            'Atestado médico: emissão e vedações', 'Código internacional de ética para profissionais de saúde ocupacional (ICOH)'] },
    { id: '7.7', sec: 7, origem: 'E', peso: 'medio',
      nome: 'Resoluções do Conselho Federal de Medicina',
      sub: ['Resolução sobre normas específicas para médicos que atendem o trabalhador',
            'Resoluções sobre perícia médica e assistente técnico',
            'Resoluções sobre prontuário, atestado e telemedicina',
            'Resoluções sobre exames toxicológicos e testes laboratoriais no trabalho',
            'Hierarquia entre resoluções do CFM e normas trabalhistas'] },
    { id: '7.8', sec: 7, origem: 'E', peso: 'medio',
      nome: 'Lei Geral de Proteção de Dados (LGPD)',
      sub: ['Conceitos: dado pessoal, dado sensível, titular, controlador e operador',
            'Bases legais para tratamento de dados de saúde do trabalhador',
            'Dados de saúde no PCMSO, ASO e prontuário à luz da LGPD',
            'Direitos do titular e incidentes de segurança',
            'Compartilhamento de dados com a empresa e limites do ASO'] }
  ];

  // Metas de questões por peso.
  //
  // Calibração original (Fase 1): alto 45 / medio 30 = 1.770 questões, ponderada
  // apenas pelo peso de cada tema na prova.
  //
  // RECALIBRADA em 07/08/2026 para alto 25 / medio 15 = 935 questões avulsas
  // (+100 de casos clínicos ≈ 1.035 no total). Motivo: o cronograma reserva 34
  // horas a questões até 01/11/2026, o que comporta cerca de 1.000 questões
  // lidas com o comentário. A meta anterior produziria um banco maior do que
  // é possível percorrer no tempo disponível de estudo.
  var META = { alto: 25, medio: 15 };

  var byId = {};
  TEMAS.forEach(function (t) {
    t.meta = META[t.peso];
    t.secNome = (SECOES.filter(function (s) { return s.id === t.sec; })[0] || {}).nome || '';
    byId[t.id] = t;
  });

  var PROVA = {
    data: '2026-11-01',
    dataBR: '01/11/2026',
    inicio: '09:00',
    fim: '14:00',
    duracaoMin: 300,
    local: 'Centro de Convenções Salvador – BA',
    objetivas: 50,
    pesoObjetiva: 0.9,
    casos: 5,
    questoesPorCaso: 5,
    pesoPratica: 1.8,
    maxProvas: 90,
    maxCurriculo: 10,
    notaCorte: 70
  };

  root.EDITAL = {
    secoes: SECOES,
    temas: TEMAS,
    meta: META,
    prova: PROVA,
    tema: function (id) { return byId[id] || null; },
    nome: function (id) { return byId[id] ? byId[id].nome : id; },
    rotulo: function (id) { return byId[id] ? id + ' ' + byId[id].nome : id; },
    daSecao: function (secId) { return TEMAS.filter(function (t) { return t.sec === secId; }); },
    valido: function (id) { return !!byId[id]; },
    totalMeta: function () { return TEMAS.reduce(function (a, t) { return a + t.meta; }, 0); }
  };

  if (typeof module !== 'undefined' && module.exports) { module.exports = root.EDITAL; }
})(typeof window !== 'undefined' ? window : globalThis);
